"""Manually authored recognition cards for both full English texts of the Comedy.

The original is Longfellow's blank-verse translation; the modern edition is
prose. Both run to 100 cantos and 4,812 paragraphs and align paragraph for
paragraph. Longfellow spells the guide Virgilius where the prose says Virgil.

Almost everyone in this poem is a real person — a Florentine neighbour, a pope,
an emperor, a classical poet, a saint — and a reader without notes cannot place
them. That is what these cards are for.

Chapters 1-34 are the Inferno, 35-67 the Purgatorio, 68-100 the Paradiso.

Scope: named people, gods, angels, devils, personified powers, named monsters
and named peoples. Places, rivers, mountains and the names of books are not
cast, except where a river of the underworld is treated as a power.
"""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

# --------------------------------------------------------------- the travellers
for row in [
('dante','Dante','The poet who is also the pilgrim of his own poem. He names himself exactly once in the whole Comedy, when Beatrice calls him by name in the earthly paradise.','Dante','central'),
('virgil','Virgil','The Roman poet of the Aeneid, sent to guide Dante through Hell and Purgatory; a soul of Limbo, saved from damnation but not from exclusion. Longfellow spells him Virgilius.','Virgilius|Virgil','central'),
('beatrice','Beatrice','The Florentine woman Dante loved, now among the blessed; she sends Virgil to his aid and takes over as his guide in the earthly paradise and through Heaven.','Beatrice','central'),
('statius','Statius','The Roman poet of the Thebaid, who joins the travellers in Purgatory and reveals that Virgil’s own verses converted him.','Statius','major'),
]:add(*row)

# ------------------------------------------------- Inferno: the powers of Hell
for row in [
('lucifer','Lucifer','The emperor of the kingdom of grief, fixed in ice at the centre of the earth; also called Dis, Satan and Beelzebub.','Lucifer|Satan|Beelzebub','major','deity'),
('charon','Charon','The ancient ferryman with wheels of flame about his eyes, who carries the damned across Acheron.','Charon','supporting','mythological-figure'),
('minos','Minos','The judge of the damned, who winds his tail about himself to sentence each soul to its circle.','Minos','supporting','mythological-figure'),
('cerberus','Cerberus','The three-throated dog who howls over the gluttons in the rain.','Cerberus','supporting','mythological-figure'),
('plutus','Plutus','The hoarse-voiced guardian of the fourth circle, where the misers and spendthrifts roll their weights.','Plutus','supporting','mythological-figure'),
('phlegyas','Phlegyas','The boatman who ferries Dante and Virgil across the marsh of Styx.','Phlegyas','supporting','mythological-figure'),
('megaera','Megaera','One of the three Furies on the tower of Dis.','Megaera','supporting','deity'),
('alecto','Alecto','One of the three Furies on the tower of Dis.','Alecto','supporting','deity'),
('tisiphone','Tisiphone','One of the three Furies on the tower of Dis.','Tisiphone','supporting','deity'),
('medusa','Medusa','The Gorgon the Furies call for, whose face would turn Dante to stone.','Medusa|Gorgon','supporting','mythological-figure'),
('minotaur','The Minotaur','The bull-man of Crete, who guards the descent into the circle of violence.','Minotaur','supporting','mythical-being'),
('chiron','Chiron','The centaur who raised Achilles, chief of the troop that patrols the river of blood.','Chiron','supporting','mythological-figure'),
('nessus','Nessus','The centaur who died for Deianira and now guides the travellers along the boiling river.','Nessus','supporting','mythological-figure'),
('pholus','Pholus','A centaur of the river bank, full of wrath.','Pholus','supporting','mythological-figure'),
('harpies','The Harpies','The bird-women who nest in the wood of the suicides.','Harpies','supporting','group'),
('geryon','Geryon','The monster with an honest face and a scorpion’s tail, who carries the travellers down to the eighth circle.','Geryon','supporting','mythical-being'),
('malebranche','The Malebranche','The demon squad of the fifth ditch, who hook the barrators out of the boiling pitch.','Malebranche','supporting','group'),
('malacoda','Malacoda','The captain of the Malebranche, who lies to Virgil about the broken bridge.','Malacoda','supporting','deity'),
('barbariccia','Barbariccia','A demon of the Malebranche, put in charge of the squad of ten.','Barbariccia','supporting','deity'),
('alichino','Alichino','A demon of the Malebranche.','Alichino','supporting','deity'),
('calcabrina','Calcabrina','A demon of the Malebranche.','Calcabrina','supporting','deity'),
('cagnazzo','Cagnazzo','A demon of the Malebranche.','Cagnazzo','supporting','deity'),
('libicocco','Libicocco','A demon of the Malebranche.','Libicocco','supporting','deity'),
('draghignazzo','Draghignazzo','A demon of the Malebranche.','Draghignazzo','supporting','deity'),
('ciriatto','Ciriatto','A demon of the Malebranche, tusked like a boar.','Ciriatto','supporting','deity'),
('graffiacane','Graffiacane','A demon of the Malebranche.','Graffiacane','supporting','deity'),
('farfarello','Farfarello','A demon of the Malebranche.','Farfarello','supporting','deity'),
('rubicante','Rubicante','A demon of the Malebranche.','Rubicante','supporting','deity'),
('scarmiglione','Scarmiglione','A demon of the Malebranche.','Scarmiglione','supporting','deity'),
('nimrod','Nimrod','The giant of Babel, whose gibberish no one can understand; his tower is why the world has many tongues.','Nimrod','supporting'),
('ephialtes','Ephialtes','A giant who warred against the gods, bound in chains at the pit’s edge.','Ephialtes','supporting','mythological-figure'),
('briareus','Briareus','A giant of the war against the gods, named but not seen.','Briareus','reference','mythological-figure'),
('antaeus','Antaeus','The unbound giant who lifts the travellers down to the frozen lake.','Antaeus','supporting','mythological-figure'),
('tityus','Tityus','A giant named among those the travellers do not want to be handed to.','Tityus','reference','mythological-figure'),
('typhoeus','Typhoeus','A giant named among those the travellers do not want to be handed to.','Typhon|Typhoeus','reference','mythological-figure'),
('old-man-of-crete','The Old Man of Crete','The great statue inside Mount Ida, cracked and weeping, whose tears make the rivers of Hell.','','supporting','personification'),
('fortune','Fortune','The ministering power Virgil defends, who turns the goods of the world from one people to another.','Fortune','supporting','personification'),
]:add(*row)

# ------------------------------------------- Inferno: the souls Dante meets
for row in [
('homer','Homer','The sovereign poet, first of the four who meet Virgil in Limbo.','Homer','supporting'),
('horace','Horace','The Roman satirist, one of the four poets of Limbo.','Horace','supporting'),
('ovid','Ovid','The Roman poet of the Metamorphoses, one of the four poets of Limbo.','Ovid','supporting'),
('lucan','Lucan','The Roman poet of the Pharsalia, one of the four poets of Limbo.','Lucan','supporting'),
('electra','Electra','Dardanus’s mother, seen among the great souls of Limbo.','Electra','reference'),
('hector','Hector','Troy’s defender, seen among the great souls of Limbo.','Hector','reference'),
('aeneas','Aeneas','The founder of the Roman line, seen among the great souls of Limbo; his journey to the dead is Dante’s precedent.','Aeneas','supporting'),
('camilla','Camilla','The warrior maiden of the Aeneid, who died for Italy.','Camilla','reference'),
('penthesilea','Penthesilea','The Amazon queen, seen among the great souls of Limbo.','Penthesilea','reference'),
('latinus','Latinus','The Latin king, seated with his daughter in Limbo.','Latinus','reference'),
('lavinia','Lavinia','Latinus’s daughter, seated beside him in Limbo.','Lavinia','reference'),
('brutus-elder','Brutus','The Brutus who drove out Tarquin and founded the Roman republic, seen in Limbo.','',''),
('brutus-caesar','Brutus','Caesar’s assassin, chewed in Lucifer’s mouth at the centre of Hell.','',''),
('tarquin','Tarquin','The last king of Rome, driven out by Brutus.','Tarquin','reference'),
('lucretia','Lucretia','A Roman matron seen among the great souls of Limbo.','Lucretia','reference'),
('julia','Julia','Caesar’s daughter and Pompey’s wife, seen in Limbo.','Julia','reference'),
('marcia','Marcia','Cato’s wife, seen in Limbo; Virgil invokes her when asking Cato’s leave in Purgatory.','Marcia','reference'),
('cornelia','Cornelia','The mother of the Gracchi, seen in Limbo.','Cornelia','reference'),
('saladin','Saladin','The Sultan of Egypt, seated alone and apart in Limbo.','Saladin','reference'),
('aristotle','The master of those who know','Aristotle, seated in the philosophical family of Limbo; the poem names him only by that title.','','supporting','unnamed-person'),
('socrates','Socrates','The Athenian philosopher, closest to Aristotle in Limbo.','Socrates','reference'),
('plato','Plato','The Athenian philosopher, closest to Aristotle in Limbo.','Plato','reference'),
('democritus','Democritus','The philosopher who attributes the world to chance.','Democritus','reference'),
('diogenes','Diogenes','A philosopher of Limbo.','Diogenes','reference'),
('anaxagoras','Anaxagoras','A philosopher of Limbo.','Anaxagoras','reference'),
('thales','Thales','A philosopher of Limbo.','Thales','reference'),
('zeno','Zeno','A philosopher of Limbo.','Zeno','reference'),
('empedocles','Empedocles','A philosopher of Limbo.','Empedocles','reference'),
('heraclitus','Heraclitus','A philosopher of Limbo.','Heraclitus','reference'),
('dioscorides','Dioscorides','The great collector of the properties of plants.','Dioscorides','reference'),
('orpheus','Orpheus','The singer of myth, seen in Limbo.','Orpheus','reference'),
('cicero','Cicero','The Roman orator, seen in Limbo. Longfellow spells him Tully.','Cicero|Tully','reference'),
('livy','Livy','The Roman historian, seen in Limbo.','Livy','reference'),
('seneca','Seneca','The Roman moralist, seen in Limbo.','Seneca','reference'),
('euclid','Euclid','The geometer, seen in Limbo.','Euclid','reference'),
('ptolemy','Ptolemy','The astronomer, seen in Limbo.','Ptolemy','reference'),
('galen','Galen','The physician, seen in Limbo.','Galen','reference'),
('hippocrates','Hippocrates','The physician, seen in Limbo.','Hippocrates','reference'),
('avicenna','Avicenna','The Persian physician and philosopher, seen in Limbo.','Avicenna','reference'),
('averroes','Averroes','The Arab philosopher who wrote the great Commentary on Aristotle.','Averroes','reference'),
('semiramis','Semiramis','The Assyrian queen who made lust lawful, first of the carnal sinners named.','Semiramis','supporting'),
('ninus','Ninus','Semiramis’s husband, whom she succeeded.','Ninus','reference'),
('dido','Dido','The queen of Carthage who killed herself for love and broke faith with Sychaeus’s ashes.','Dido','supporting'),
('sychaeus','Sychaeus','Dido’s dead husband, whose ashes she broke faith with.','Sychaeus|Sichaeus','reference'),
('cleopatra','Cleopatra','The Egyptian queen, among the carnal sinners.','Cleopatra','reference'),
('helen','Helen','The woman for whose sake the Trojan war was fought.','Helen','reference'),
('achilles','Achilles','The Greek hero who at the last fought against Love.','Achilles','supporting'),
('paris','Paris','The Trojan who carried Helen away.','Paris','reference'),
('tristan','Tristan','The lover of romance, among the carnal sinners.','Tristan','reference'),
('francesca','Francesca','Francesca da Rimini, who tells Dante how she and her husband’s brother were carried away by a book, and were killed for it.','Francesca','major'),
('lancelot','Lancelot','The knight whose story Francesca and her companion were reading.','Lancelot|Launcelot','reference','literary-figure'),
('ciacco','Ciacco','A Florentine glutton who prophesies the city’s coming strife.','Ciacco','supporting'),
('farinata','Farinata','Farinata degli Uberti, the Ghibelline leader who rises out of his burning tomb and speaks of Florence.','Farinata','major'),
('guido-cavalcanti','Guido','Guido Cavalcanti, the poet and Dante’s friend, asked after by his father in the tombs of the heretics.','',''),
('frederick-ii','Frederick','The emperor Frederick the Second, named as lying among the Epicureans, and whose leaden capes are a byword.','','supporting'),
('cardinal','The Cardinal','Ottaviano degli Ubaldini, named only by his office among the heretics.','Cardinal','reference'),
('anastasius','Anastasius','The pope whose tomb Dante passes, said to have been led from the true path.','Anastasius','reference'),
('photinus','Photinus','The deacon said to have led Pope Anastasius astray.','Photinus','reference'),
('alexander-tyrant','Alexander','A tyrant boiling in the river of blood, named beside Dionysius.','',''),
('alexander-great','Alexander','Alexander the Great, whose army in India saw flames fall unbroken from the sky.','',''),
('dionysius','Dionysius','The tyrant of Syracuse, boiling in the river of blood.','','reference'),
('azzolino','Azzolino','Ezzelino da Romano, the black-haired tyrant in the river of blood.','Azzolino','reference'),
('obizzo','Obizzo','Obizzo d’Este, the fair-haired tyrant in the river of blood, killed by his own stepson.','Obizzo','reference'),
('attila','Attila','The scourge of the earth, deep in the boiling blood.','Attila','reference'),
('pyrrhus','Pyrrhus','A tyrant in the boiling blood.','Pyrrhus','reference'),
('sextus','Sextus','A tyrant in the boiling blood.','Sextus','reference'),
('rinier-corneto','Rinier da Corneto','A highway robber, boiling in the river of blood.','',''),
('rinier-pazzo','Rinier Pazzo','A highway robber, boiling in the river of blood.','',''),
('pier-della-vigna','The one who held both keys','Frederick the Second’s chancellor, who turned his master’s heart softly in locking and unlocking, and killed himself when envy turned the court against him. He is the speaking tree of the wood of the suicides, and the canto never gives his name.','','supporting','unnamed-person'),
('lano','Lano','A Sienese squanderer, hunted through the wood by black hounds.','Lano','reference'),
('jacopo-sant-andrea','Jacopo da Sant’Andrea','A Paduan squanderer, torn apart by the hounds in the wood of the suicides.','',''),
('florentine-suicide','The Florentine who hanged himself','The bush who speaks last in the wood, from the city that changed its patron saint to the Baptist.','','supporting','unnamed-person'),
('capaneus','Capaneus','One of the seven kings who besieged Thebes, who held God in contempt and holds him in contempt still on the burning sand.','Capaneus','supporting'),
('brunetto-latini','Brunetto','Ser Brunetto Latini, the Florentine scholar who taught Dante how man makes himself eternal, and whom Dante finds among the sodomites.','Brunetto','major'),
('priscian','Priscian','A grammarian named among the clerks on the burning sand.','Priscian','reference'),
('francesco-accorso','Francesco d’Accorso','A Bolognese jurist named among the clerks on the burning sand. Longfellow calls him Francis of Accorso.','Accorso','reference'),
('guido-guerra','Guido Guerra','A Florentine of great worth, grandson of the good Gualdrada, one of the three who circle on the burning sand. Longfellow writes the name as one word, Guidoguerra.','Guidoguerra','supporting'),
('gualdrada','Gualdrada','The Florentine woman named as Guido Guerra’s grandmother.','Gualdrada','reference'),
('tegghiaio','Tegghiaio','Tegghiaio Aldobrandi, whose counsel Florence should have heeded.','Tegghiaio','reference'),
('jacopo-rusticucci','Jacopo Rusticucci','A Florentine who blames his savage wife for his ruin, one of the three on the burning sand.','',''),
('guglielmo-borsiere','Guglielmo Borsiere','A Florentine newly arrived in Hell, who has been telling the others how the city has changed.','','reference'),
('vitaliano','Vitaliano','A Paduan usurer, expected in Hell by the one already there.','Vitaliano','reference'),
('venedico','Venedico','Venedico Caccianemico, a Bolognese who sold his own sister to the Marquis.','Venedico','supporting'),
('ghisola','Ghisola','Venedico’s sister, whom he persuaded to satisfy the Marquis.','Ghisola','reference'),
('jason','Jason','The leader of the Argonauts, punished as a seducer for Hypsipyle and Medea.','Jason','supporting'),
('hypsipyle','Hypsipyle','The woman Jason deceived and abandoned on Lemnos.','Hypsipyle','reference'),
('medea','Medea','The woman Jason abandoned after Hypsipyle.','Medea','reference'),
('alessio-interminei','Alessio Interminei','A flatterer of Lucca, sunk in filth.','Alessio','reference'),
('thais','Thais','The harlot of Terence’s comedy, named as the last of the flatterers.','Thais','reference','literary-figure'),
('simon-magus','Simon Magus','The man who tried to buy the power of the Holy Spirit, and gave his name to the sin punished in the third ditch.','',''),
('boniface','Boniface','Pope Boniface the Eighth, whom Nicholas mistakes Dante for and expects to take his place head-down in the rock.','','supporting'),
('constantine','Constantine','The emperor whose gift to the first wealthy Father is named as the root of the Church’s corruption.','Constantine','reference'),
('sylvester','Sylvester','The pope Constantine sought out at Soracte to cure his leprosy.','Sylvester','reference'),
('amphiaraus','Amphiaraus','One of the seven against Thebes, swallowed by the earth; now a diviner walking backwards.','Amphiaraus','reference'),
('tiresias','Tiresias','The Theban seer who changed from man to woman and back, among the diviners.','Tiresias','supporting'),
('aruns','Aruns','An Etruscan diviner of the hills of Luni.','Aruns','reference'),
('manto','Manto','Tiresias’s daughter, the virgin seer who settled where Mantua now stands; Virgil tells her story to correct the legend of his own city.','Manto','supporting'),
('eurypylus','Eurypylus','The augur who with Calchas cut the first cable at Aulis.','Eurypylus','reference'),
('calchas','Calchas','The Greek augur of the Trojan war.','Calchas','reference'),
('michael-scot','Michael Scot','The Scottish astrologer, thin in the flanks, who knew every trick of magical illusion.','',''),
('guido-bonatti','Guido Bonatti','An astrologer of Forlì, among the diviners.','',''),
('asdente','Asdente','A cobbler of Parma turned soothsayer, who now wishes he had stuck to his leather.','Asdente','reference'),
('santa-zita-elder','The elder of Santa Zita','The barrator of Lucca whom a demon carries in and throws into the pitch.','','supporting','unnamed-person'),
('ciampolo','The Navarrese','The barrator born in the kingdom of Navarre, who tricks the demons into letting him dive.','','supporting','unnamed-person'),
('fra-gomita','Fra Gomita','A friar of Gallura, a vessel of every fraud, who sold his master’s enemies their freedom.','Gomita','reference'),
('michel-zanche','Don Michel Zanche','A barrator of Logodoro in Sardinia.','Zanche','reference'),
('catalano','Catalano','A Jovial Friar of Bologna, one of the two hypocrites in leaden capes who governed Florence together.','Catalano','supporting'),
('loderingo','Loderingo','A Jovial Friar of Bologna, Catalano’s partner in governing Florence.','Loderingo','supporting'),
('caiaphas','The one pinned to the ground','The high priest who counselled that one man should suffer for the people, crucified across the path of the hypocrites.','','supporting','unnamed-person'),
('vanni-fucci','Vanni Fucci','A thief of Pistoia, a mule of a man, who robbed the sacristy and let another man be blamed.','Vanni Fucci','supporting'),
('cacus','Cacus','The centaur who guards the thieves, whose thefts by fraud set him apart from his brothers.','Cacus','supporting','mythological-figure'),
('cianfa','Cianfa','A Florentine thief, transformed into a six-footed serpent.','Cianfa','reference'),
('agnello','Agnello','A Florentine thief, fused with the serpent that attacks him.','Agnello','reference'),
('buoso-abati','Buoso','A Florentine thief, changed into a serpent as the poet watches.','',''),
('buoso-donati','Buoso Donati','The dead man whom Gianni Schicchi impersonated in order to forge a will.','',''),
('puccio','Puccio','A Florentine thief, the only one of the five who was not transformed.','Puccio','reference'),
('ulysses','Ulysses','The Greek whose cunning took Troy, and who tells of his last voyage beyond the pillars of Hercules; he burns in a double flame with Diomedes.','Ulysses','major'),
('diomedes','Diomedes','Ulysses’s companion, burning in the same flame. Longfellow spells him Diomed.','Diomedes|Diomed','supporting'),
('deidamia','Deidamia','Achilles’s bride, who still mourns him; the cunning that took him from her is part of what Ulysses burns for.','Deidamia','reference'),
('guido-montefeltro','Guido','Guido da Montefeltro, the soldier turned friar, damned for advising Boniface to promise much and keep little.','',''),
('guido-cassero','Messer Guido','Guido del Cassero, one of the two best men of Fano, warned of drowning off La Cattolica.','',''),
('angiolello','Angiolello','One of the two best men of Fano, warned with Guido del Cassero.','Angiolello','reference'),
('mahomet','Mahomet','The founder of Islam, cleft from chin to belly among the sowers of discord.','Mahomet|Mohammed','supporting'),
('ali','Ali','Cleft in the face, walking weeping before Mahomet.','Ali','reference'),
('fra-dolcino','Fra Dolcino','The heretic leader whom Mahomet sends a warning to arm himself with food.','Dolcino','reference'),
('pier-da-medicina','Pier da Medicina','A sower of discord with his throat pierced and his nose cut away, who sends the warning to Fano.','',''),
('curio','Curio','The shade with his tongue cut out, who urged Caesar across the Rubicon.','Curio','reference'),
('mosca','Mosca','Mosca dei Lamberti, whose counsel — "a thing done has an end" — began the Guelf and Ghibelline split in Florence.','Mosca','supporting'),
('bertran-de-born','Bertran de Born','The troubadour who carries his own severed head like a lantern, punished for setting a son against his father.','Bertran|Bertram','supporting'),
('geri-del-bello','Geri del Bello','Dante’s kinsman, seen pointing at him in anger because his death is unavenged.','Geri','supporting'),
('alberto-siena','Alberto','Alberto of Siena, who had the Aretine alchemist burned for a joke about flying.','',''),
('capocchio','Capocchio','An alchemist who falsified metals, and a good ape of nature.','Capocchio','supporting'),
('gianni-schicchi','Gianni Schicchi','The Florentine who impersonated the dead Buoso Donati to forge a will and take the best mare in the stud.','Schicchi','supporting'),
('myrrha','Myrrha','The shade who disguised herself to lie with her own father, running mad beside Gianni Schicchi.','Myrrha','supporting'),
('master-adam','Master Adam','The counterfeiter of Florentine coin, swollen with dropsy, who dreams of the streams of the Casentino.','',''),
('guido-romena','Guido','One of the Counts of Romena, for whom Master Adam counterfeited, and whose soul he longs to see in the ditch.','',''),
('alessandro-romena','Alessandro','One of the Counts of Romena, named with his brother Guido.','','reference'),
('potiphars-wife','The false woman who accused Joseph','Potiphar’s wife, burning with fever beside Sinon.','','reference','unnamed-person'),
('sinon','Sinon','The Greek who talked Troy into taking in the horse, burning with fever.','Sinon','supporting'),
('bocca','Bocca','Bocca degli Abati, the traitor of Montaperti, who refuses to give his name until Dante tears at his hair.','Bocca','supporting'),
('camicion','Camicion','Camicion de’ Pazzi, frozen in Caina, who names the traitors around him and awaits his kinsman Carlino.','Camicion','supporting'),
('carlino','Carlino','The kinsman whose worse treachery Camicion says will excuse his own.','Carlino','reference'),
('albert-alberti','Albert','The father of the two brothers of the Bisenzio valley, frozen face to face in Caina.','',''),
('mordred','The one Arthur pierced','The traitor whose breast and shadow were broken by one blow of his own father’s hand.','','reference','unnamed-person'),
('focaccia','Focaccia','A traitor of Pistoia named among the frozen.','Focaccia','reference'),
('sassol','Sassol Mascheroni','A Florentine traitor named among the frozen.','Sassol','reference'),
('gianni-soldanier','Gianni del Soldanieri','A Florentine traitor in the ice; Longfellow drops the final vowel.','','reference'),
('ganelon','Ganelon','The betrayer of Roland at Roncesvalles. Longfellow spells him Ganellon.','Ganelon|Ganellon','reference'),
('tebaldello','Tebaldello','The man who opened Faenza’s gates while the city slept.','Tebaldello','reference'),
('ugolino','Ugolino','Count Ugolino della Gherardesca, who gnaws the head of the archbishop who starved him and his children in the tower.','Ugolino','major'),
('ruggieri','Ruggieri','Archbishop Ruggieri of Pisa, who locked Ugolino and his sons in the tower and threw away the key.','Ruggieri','supporting'),
('anselmuccio','Anselm','One of Ugolino’s children in the tower, who asks his father why he stares.','Anselmuccio','supporting'),
('gaddo','Gaddo','One of Ugolino’s children, who falls at his father’s feet in the tower.','Gaddo','supporting'),
('uguccione','Uguccione','One of Ugolino’s children in the tower.','Uguccione','reference'),
('brigata','Brigata','One of Ugolino’s children in the tower.','Brigata','reference'),
('alberigo','Alberigo','Friar Alberigo, who served the fruit at his own treacherous banquet, and whose soul is in Hell while his body still walks the world.','Alberigo','supporting'),
('branca-doria','Branca d’Oria','A Genoese whose soul has been in the ice for years while a devil wears his body.','Branca','supporting'),
('judas','Judas','The betrayer of Christ, head-first in Lucifer’s central mouth.','Judas','supporting'),
('cassius','Cassius','Caesar’s assassin, hanging from one of Lucifer’s black jaws.','Cassius','supporting'),
]:add(*row)

# ------------------------------------- scripture, myth and history referred to
for row in [
('christ','Christ','The Redeemer, named in Paradise and referred to in Hell only by circumlocution.','Christ','major','religious-figure'),
('mary','Mary','The mother of Christ, the gracious Lady who first moved to help Dante and who receives the last prayer of the poem.','Mary','major','religious-figure'),
('peter','Peter','Saint Peter, keeper of the keys of Heaven; his gate and his seat recur throughout.','','supporting','religious-figure'),
('paul','Paul','The apostle whose journey to the third heaven Dante names beside Aeneas’s as precedent.','Paul','supporting','religious-figure'),
('john-baptist','The Baptist','John the Baptist, the patron Florence adopted in place of Mars.','Baptist','supporting','religious-figure'),
('lucia','Lucia','Saint Lucy, the enemy of all cruelty, who sends Beatrice to Dante’s aid and carries him while he sleeps.','Lucia','supporting','religious-figure'),
('rachel','Rachel','Jacob’s wife, seated beside Beatrice among the blessed and a figure of the contemplative life.','Rachel','supporting','religious-figure'),
('adam','Adam','The first father, drawn out of Limbo by the Harrowing.','','supporting','religious-figure'),
('eve','Eve','The first mother, who took the bitter fruit from the serpent.','Eve','supporting','religious-figure'),
('abel','Abel','Adam’s son, drawn out of Limbo by the Harrowing.','Abel','reference','religious-figure'),
('noah','Noah','Drawn out of Limbo by the Harrowing.','Noah','reference','religious-figure'),
('moses','Moses','The lawgiver, drawn out of Limbo by the Harrowing.','Moses','reference','religious-figure'),
('abraham','Abraham','The patriarch, drawn out of Limbo by the Harrowing.','Abraham','reference','religious-figure'),
('david','David','The psalmist king, drawn out of Limbo by the Harrowing.','David','reference','religious-figure'),
('israel','Israel','Jacob, drawn out of Limbo with his father and his children.','Israel','reference','religious-figure'),
('cain','Cain','The first murderer; the man in the moon carrying thorns is called by his name.','Cain','reference','religious-figure'),
('michael','Michael','The archangel who took vengeance on the proud rebellion.','',''),
('elijah','Elijah','The prophet taken up in the chariot of fire.','Elijah','reference','religious-figure'),
('elisha','Elisha','The prophet who watched Elijah’s chariot depart.','Elisha','reference','religious-figure'),
('joseph','Joseph','The patriarch falsely accused by Potiphar’s wife.','Joseph','reference','religious-figure'),
('judas-maccabee','placeholder','unused','',''),
('caesar','Caesar','Julius Caesar, seen armed in Limbo and named through the poem as the founder of the empire.','Caesar','supporting'),
('augustus','Augustus','The emperor under whom Virgil lived.','Augustus','reference'),
('scipio','Scipio','The Roman who became the heir of glory by routing Hannibal.','Scipio','reference'),
('hannibal','Hannibal','The Carthaginian routed by Scipio.','Hannibal','reference'),
('charlemagne','Charlemagne','The emperor whose rout at Roncesvalles cost him his holy campaign.','Charlemagne','reference'),
('roland','Roland','The paladin whose horn sounded at Roncesvalles.','Roland|Orlando','reference'),
('robert-guiscard','Robert Guiscard','The Norman conqueror in Apulia, whose wars left bones still gathered on the field.','Robert|Guiscard','reference'),
('jove','Jove','The chief of the pagan gods, whose thunderbolt and whose blacksmith are invoked.','Jove|Jupiter','supporting','deity'),
('juno','Juno','The goddess whose rage against the Theban house drove Athamas mad.','Juno','reference','deity'),
('mars','Mars','The god of war, Florence’s first patron before the Baptist.','Mars','supporting','deity'),
('neptune','Neptune','The god of the sea.','Neptune','reference','deity'),
('apollo','Apollo','The god of poetry, invoked at the opening of the Paradiso.','Apollo','supporting','deity'),
('diana','Diana','The goddess of the moon and the hunt; Trivia is her name at the crossroads, and in Heaven it is the moon she smiles from.','Diana|Trivia','reference','deity'),
('minerva','Minerva','The goddess of wisdom.','Minerva','reference','deity'),
('bacchus','Bacchus','The god of wine; Thebes is called his city.','Bacchus','reference','deity'),
('latona','Latona','The mother of Apollo and Diana, who gave birth on Delos.','Latona','reference','deity'),
('muses','The Muses','The goddesses of poetry, invoked at the outset of each canticle.','Muses','supporting','group'),
('circe','Circe','The enchantress who kept Ulysses near Gaeta for more than a year.','Circe','reference','deity'),
('phaethon','Phaethon','The boy who dropped the reins of the sun’s chariot and scorched the sky.','Phaethon|Phaeton','reference','mythological-figure'),
('arachne','Arachne','The weaver turned spider, named for the pattern of Geryon’s hide.','Arachne','reference','mythological-figure'),
('narcissus','Narcissus','The boy who pined at his own reflection; his mirror is the water Master Adam thirsts for.','Narcissus','reference','mythological-figure'),
('theseus','Theseus','The Duke of Athens who killed the Minotaur, and whom the Furies wish they had punished.','Theseus','reference','mythological-figure'),
('hercules','Hercules','The hero whose club ended Cacus, and whose pillars mark the limit Ulysses passed.','Hercules','reference','mythological-figure'),
('deianira','Deianira','The woman Nessus died for.','Deianira','reference','mythological-figure'),
('semele','Semele','The Theban woman whose love of Jove brought Juno’s rage on her house.','Semele','reference','mythological-figure'),
('athamas','Athamas','The king driven mad by Juno, who killed his own son.','Athamas','reference','mythological-figure'),
('hecuba','Hecuba','Troy’s queen, who went mad with grief and howled like a dog.','Hecuba','reference','mythological-figure'),
('polydorus','Polydorus','Hecuba’s son, found dead on the seashore.','Polydorus','reference','mythological-figure'),
('polyxena','Polyxena','Hecuba’s daughter, whose death she saw.','Polyxena','reference','mythological-figure'),
('charybdis','Charybdis','The whirlpool whose waves crash and break, likened to the clash of the hoarders and spenders.','Charybdis','reference','mythical-being'),
('icarus','Icarus','The boy whose wings failed him, named when Dante rides down on Geryon.','Icarus','reference','mythological-figure'),
('daedalus','Daedalus','Icarus’s father, who called to him as the wax melted.','Daedalus','reference','mythological-figure'),
('atropos','Atropos','The Fate who cuts the thread.','Atropos','reference','deity'),
('epicurus','Epicurus','The philosopher whose followers held that the soul dies with the body, and whose cemetery is the sixth circle.','Epicurus','reference'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ----------------------------------------------------------------- the peoples
for row in [
('florentines','The Florentines','Dante’s own city and its people, the subject of more of the poem’s anger than any other.','Florentines|Florentine','supporting','group'),
('trojans','The Trojans','The people of Troy, from whose survivors Rome descends.','Trojans','reference','group'),
('greeks','The Greeks','The people who took Troy.','Greeks|Greek','reference','group'),
('romans','The Romans','The people of the empire Virgil sang and Dante defends.','Romans|Roman','supporting','group'),
('jews','The Jews','Named in the ditch of the hypocrites and in the sowing of evil seed.','Jews','reference','group'),
('christians','The Christians','Named in the poem’s reproaches to the living.','Christians|Christian','supporting','group'),
('pharisees','The Pharisees','The council that took counsel against Christ.','Pharisees','reference','group'),
('saracens','The Saracens','Named among the enemies the papacy did not make war on.','Saracens','reference','group'),
('cherubim','The Cherubim','An order of angels; one of the black Cherubim claims Guido da Montefeltro.','Cherubim','reference','group'),
('seraphim','The Seraphim','The highest order of angels.','Seraphim','reference','group'),
('thebans','The Thebans','The people who saw the earth open for Amphiaraus.','Thebans','reference','group'),
('sienese','The Sienese','A people the poem calls the vainest in the world.','Sienese','reference','group'),
('bolognese','The Bolognese','Named in the ditch of the panders, and again by the two Jovial Friars.','','reference','group'),
('genoese','The Genoese','A people at odds with every virtue, in the poem’s judgment.','Genoese','reference','group'),
('lombards','The Lombards','The people of Virgil’s parents.','Lombards','reference','group'),
('mantuans','The Mantuans','The people of Virgil’s city.','Mantuan|Mantuans','reference','group'),
('tuscans','The Tuscans','The people of Dante’s region.','Tuscan|Tuscans','supporting','group'),
('aretines','The Aretines','The people of Arezzo.','Aretine|Aretines','reference','group'),
('paduans','The Paduans','The people of Padua.','Paduan|Paduans','reference','group'),
('french','The French','Named beside the Sienese for vanity.','French','reference','group'),
]:add(*row)

# ============================================================== PURGATORIO
for row in [
('cato','Cato','Cato of Utica, the stern old guardian of the shore of Purgatory, who killed himself for liberty and is saved for it.','Cato','major'),
('casella','Casella','The musician and friend who sets one of Dante’s own songs to music on the shore, and holds the souls spellbound until Cato scatters them.','Casella','supporting'),
('manfred','Manfredi','King Manfred of Sicily, the Empress Constance’s grandson, killed at Benevento and excommunicated, who sends word to his daughter that no curse can shut out eternal love.','Manfredi','major'),
('constance-empress','Constance','The Empress Constance, Manfred’s grandmother.','','reference'),
('buonconte','Buonconte','Buonconte da Montefeltro, killed at Campaldino, whose body the river carried away and whose soul one angel won and one devil lost.','Buonconte','major'),
('giovanna','Giovanna','Buonconte’s widow, who no longer prays for him.','Giovanna','reference'),
('pia','La Pia','The Sienese woman, made by Siena and unmade by the Maremma, who asks only to be remembered.','Pia','supporting'),
('ghin-di-tacco','Ghin di Tacco','The brigand at whose hands an Aretine met his death.','Tacco','reference'),
('federigo-novello','Federigo Novello','A soul praying with outstretched hands among the late-repentant.','Novello','reference'),
('marzucco','Marzucco','The good man whose fortitude a Pisan’s death showed.','Marzucco','reference'),
('orso','Orso','Count Orso, among the souls who died by violence.','Orso','reference'),
('pierre-de-la-brosse','Pierre de la Brosse','The soul torn from its body by spite and envy, who warns the Lady of Brabant.','Brosse','supporting'),
('lady-of-brabant','The Lady of Brabant','The woman Pierre de la Brosse warns to take heed while she is still in the world.','Brabant','reference'),
('sordello','Sordello','The poet of Mantua who springs up at the sound of Virgil’s birthplace and embraces him, then shows the travellers the valley of the princes.','Sordello','major'),
('albert-of-germany','German Albert','The emperor reproached for abandoning Italy.','',''),
('rudolf','Rudolf','The Emperor Rudolf of Habsburg, seated highest in the valley of the princes, who could have healed Italy’s wounds and did not; Charles Martel names him as a grandfather of the kings Sicily never got.','Rudolf|Rudolph','supporting'),
('ottocar','Ottocar','The king who governed the land of the Moldau, better in swaddling clothes than his son was bearded.','Ottocar','supporting'),
('wenceslaus','Wenceslaus','Ottocar’s son, who feeds on luxury and ease.','Wenceslaus','reference'),
('henry-of-navarre','The large-nosed one','The king of Navarre seated in the valley, father-in-law of the Plague of France.','','supporting','unnamed-person'),
('peter-of-aragon','Peter','Peter of Aragon, singing in the valley of the princes beside the large-nosed king.','',''),
('margaret','Margaret','A queen named in the comparison of wives who boast of their husbands.','Margaret','reference'),
('constance-aragon','Constance','Peter of Aragon’s widow, who still boasts of her husband.','',''),
('henry-of-england','Henry','Henry of England, the monarch of the simple life, seated alone with a better harvest in his descendants.','',''),
('marquis-william','William','The Marquis William of Monferrato, seated lowest and looking upward, whose war made Alessandria weep.','','supporting'),
('frederick-sicily','Frederick','Frederick of Sicily, who holds a kingdom but not the better heritage.','',''),
('james-aragon','James','James of Aragon, who holds a kingdom but not the better heritage.','',''),
('nino','Nino','Judge Nino Visconti of Gallura, delighted to be found among the saved, who speaks bitterly of his widow’s remarriage.','Nino','supporting'),
('currado-malaspina','Currado','Currado Malaspina the younger, who foretells that Dante will learn the worth of his house within seven years.','','supporting'),
('lucia-purg','placeholder','unused','',''),
('omberto','Omberto','Omberto Aldobrandeschi, crushed under his stone on the terrace of pride, whose family arrogance killed him.','Omberto','supporting'),
('guglielmo-aldobrandeschi','Guglielmo Aldobrandeschi','Omberto’s father, head of a great Tuscan family.','Aldobrandeschi','reference'),
('oderisi','Oderisi','Oderisi of Gubbio, the illuminator, who tells Dante that fame is only a breath of wind.','Oderisi','major'),
('franco-bolognese','Franco Bolognese','The illuminator whose brush now outshines Oderisi’s.','Franco','reference'),
('cimabue','Cimabue','The painter who thought he held the field until Giotto took the acclaim.','Cimabue','reference'),
('giotto','Giotto','The painter whose acclaim has dimmed Cimabue’s.','Giotto','reference'),
('provenzan-salvani','Provenzan Salvani','The Sienese who presumed to seize all Siena, and who begged in the Campo to ransom a friend.','Provenzan|Salvani','supporting'),
('sapia','Sapia','The Sienese woman who rejoiced at her own city’s defeat, now sewn-eyed on the terrace of envy.','Sapia','supporting'),
('pier-pettignano','Pier Pettignano','The holy man whose prayers shortened Sapia’s waiting.','Pettignano','reference'),
('guido-del-duca','Guido del Duca','The Romagnole who names the lost worthies of his country and weeps that no one now inherits their worth.','Duca','major'),
('rinier-calboli','Renier','Rinier da Calboli, the pride and honour of his house, seated beside Guido del Duca.','Renier','supporting'),
('lizio','Lizio','A lost worthy of Romagna.','Lizio','reference'),
('arrigo-manardi','Arrigo Manardi','A lost worthy of Romagna.','Manardi','reference'),
('pier-traversaro','Pier Traversaro','A lost worthy of Romagna.','Traversaro','reference'),
('guido-carpigna','Guido di Carpigna','A lost worthy of Romagna.','Carpigna','reference'),
('fabbro','Fabbro','A man of Bologna named among the lost worthies.','Fabbro','reference'),
('bernardin-di-fosco','Bernardin di Fosco','A noble shoot from a humble root, of Faenza.','Bernardin','reference'),
('guido-da-prata','Guido da Prata','A man of Romagna whose memory makes Guido del Duca weep.','Prata','reference'),
('ugolin-dazzo','Ugolin d’Azzo','A man who lived among the Romagnoles, remembered with Guido da Prata.','',''),
('federigo-tignoso','Federigo Tignoso','A man of Romagna named among the lost, with his circle.','Tignoso','reference'),
('ugolin-fantoli','Ugolin de’ Fantoli','A Romagnole whose name is safe, since no one is expected who could darken it.','',''),
('aglaurus','Aglaurus','The envious sister turned to stone, whose voice cracks the air on the terrace of envy.','Aglaurus','reference'),
('marco-lombardo','Marco','Marco the Lombard, who explains in the smoke of anger that the fault is not in the stars but in free will and bad government.','',''),
('currado-da-palazzo','Currado da Palazzo','One of the three old men in whom the good of the former age survives.','Palazzo','reference'),
('gherardo','Gherardo','Gherardo da Camino, the good Lombard, one of the three old men of the former age.','Gherardo','reference'),
('guido-da-castel','Guido da Castel','One of the three old men in whom the good of the former age survives, called the honest Lombard in the French way.','',''),
('gaia','Gaia','Gherardo’s daughter, by whom Marco says he can be identified.','Gaia','reference'),
('siren','The Siren','The stammering, squint-eyed woman of Dante’s dream who becomes lovely as he looks, and is stripped by a holy lady.','Siren','supporting','personification'),
('adrian','The successor of Peter','Pope Adrian the Fifth, face down on the terrace of avarice, who will not let Dante kneel to him.','','supporting','unnamed-person'),
('alagia','Alagia','Adrian’s granddaughter, good in herself unless her house corrupts her.','Alagia','reference'),
('hugh-capet','Hugh Capet','The son of a Parisian butcher and root of the French royal line, who denounces his own descendants.','Capet','major'),
('philip-the-fair-2','placeholder','unused','',''),
('charles-of-anjou','Charles','Charles of Anjou, who came to Italy, made a victim of Conradin and, for amends, thrust Thomas back to heaven.','',''),
('conradin','Conradin','The young Hohenstaufen whom Charles of Anjou executed.','Conradin','reference'),
('thomas-aquinas','Thomas','Thomas Aquinas, the Dominican whom Charles of Anjou is said to have thrust back to heaven; in the sphere of the sun he speaks for the twelve wise lights and tells the life of Saint Francis.','','major','religious-figure'),
('fabricius','Fabricius','The Roman who chose virtue with poverty over wealth with vice.','Fabricius','reference'),
('nicholas-saint','Nicholas','Saint Nicholas, whose generosity to the three maidens guided their youth toward honour.','',''),
('pygmalion-tyre','Pygmalion','Dido’s brother, whose hunger for gold made him traitor, thief and parricide.','',''),
('midas','Midas','The king whose outrageous demand can only be laughed at.','Midas','reference'),
('achan','Achan','The man who stole from the spoils and brought Joshua’s wrath on himself.','Achan','reference'),
('sapphira','Sapphira','Named with her husband among the examples of avarice punished.','Sapphira','reference'),
('heliodorus','Heliodorus','The man whose kicking by heavenly hooves is praised.','Heliodorus','reference'),
('polymnestor','Polymnestor','The king who murdered Polydorus for his gold.','Polymnestor','reference'),
('crassus','Crassus','The Roman asked what gold tastes like.','Crassus','reference'),
('forese','Forese','Forese Donati, Dante’s old friend, wasted with hunger on the terrace of gluttony, who praises his widow and foretells his brother’s end.','Forese','major'),
('nella','Nella','Forese’s widow, whose prayers brought him so quickly up the mountain.','Nella','supporting'),
('bonagiunta','Buonagiunta','Buonagiunta of Lucca, who names the knot that held the old poets back from the sweet new style.','Buonagiunta','supporting'),
('martin-iv','The one from Tours','Pope Martin the Fourth, purging with fasting the eels of Bolsena and the Vernaccia.','','supporting','unnamed-person'),
('ubaldin','Ubaldin dalla Pila','A glutton biting the empty air.','Ubaldin','reference'),
('boniface-ravenna','Boniface','Boniface, Archbishop of Ravenna, who pastured many people with his staff.','',''),
('marchese','Messer Marchese','A man of Forlì who was never satisfied with drinking.','Marchese','reference'),
('gentucca','placeholder','unused','',''),
('notary','The Notary','Giacomo da Lentini, named with Guittone as falling short of the sweet new style.','Notary','reference'),
('guittone','Guittone','The poet named with the Notary as short of the sweet new style.','Guittone','reference'),
('piccarda','Piccarda','Forese’s sister, already triumphing in her crown in Heaven; Dante meets her again in the moon.','Piccarda','major'),
('guinizelli','Guido Guinizelli','The father of the sweet new style, who points out a better craftsman than himself and vanishes into the fire. Longfellow spells him Guinicelli.','Guinizelli|Guinicelli','major'),
('arnaut','Arnaut','Arnaut Daniel, the better craftsman of the mother tongue, who speaks his eight lines in Provençal and dives back into the refining fire.','Arnaut','major'),
('giraut','The one from Limoges','Giraut de Bornelh, whom fools rate above Arnaut Daniel.','','reference','unnamed-person'),
('matilda','Matilda','The lady gathering flowers alone in the earthly paradise, who explains the wood and the two rivers and carries Dante through Lethe.','Matilda|Matelda','major'),
('leah','Leah','The woman of Dante’s dream in the earthly paradise, gathering flowers to make a garland; a figure of the active life.','Leah','supporting','religious-figure'),
('griffin','The Griffin','The double-natured creature, eagle and lion, that draws the chariot of the Church in the procession.','Griffin','major','mythical-being'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']
print(len(entities),'after Purgatorio cast')

# --------------------------- Purgatorio: scripture, myth and further reference
for row in [
('calliope','Calliope','The Muse invoked to rise higher at the opening of the Purgatorio.','Calliope','reference','deity'),
('michal','Michal','David’s wife, who looked down in scorn as he danced before the Ark.','Michal','reference','religious-figure'),
('trajan','Trajan','The Roman emperor whose generosity to a widow moved Gregory to his great victory.','Trajan','supporting'),
('gregory','Gregory','The pope whose prayers are said to have won Trajan’s soul.','Gregory','reference','religious-figure'),
('saul','Saul','The king shown fallen on his own sword on Gilboa.','Saul','reference','religious-figure'),
('sennacherib','Sennacherib','The king killed in the temple by his own sons.','Sennacherib','reference'),
('tomyris','Tomyris','The queen who gave Cyrus his fill of blood.','Tomyris','reference'),
('cyrus','Cyrus','The king whose thirst for blood Tomyris satisfied.','Cyrus','reference'),
('holofernes','Holofernes','The general whose death routed the Assyrians.','Holofernes','reference','religious-figure'),
('rehoboam','placeholder','unused','',''),
('alcmaeon','Alcmaeon','The son who made his mother pay dearly for the cursed ornament.','Alcmaeon','reference','mythological-figure'),
('niobe','Niobe','An example of pride punished, carved in the pavement.','Niobe','reference','mythological-figure'),
('arachne-purg','placeholder','unused','',''),
('thymbraeus','Thymbraeus','Apollo under that name, armed beside Pallas and Mars around their father in the carved rout of the giants.','Thymbraeus','reference','deity'),
('pallas-goddess','Pallas','Minerva, armed beside Thymbraeus and Mars in the carved rout of the giants.','',''),
('briareus-purg','placeholder','unused','',''),
('metellus','Metellus','The Roman torn from the Tarpeian Rock when Caesar took the treasury.','Metellus','reference'),
('polycletus','Polycletus','The sculptor whose art the carvings on the terrace of pride would shame.','Polycletus','reference'),
('ahasuerus','Ahasuerus','The king in the carved example of anger, with Esther and Mordecai.','Ahasuerus','reference','religious-figure'),
('esther','Esther','Ahasuerus’s wife in the carved example.','Esther','reference','religious-figure'),
('mordecai','Mordecai','The upright man of the carved example.','Mordecai','reference','religious-figure'),
('haman','placeholder','unused','',''),
('orestes-purg','Orestes','The friend who cried his own name to take his friend’s death, heard as a voice on the terrace of envy.','',''),
('pyramus','Pyramus','The lover who opened his eyes at Thisbe’s name as the mulberry turned crimson.','Pyramus','reference','mythological-figure'),
('thisbe','Thisbe','Pyramus’s beloved.','Thisbe','reference','mythological-figure'),
('xerxes','Xerxes','The king whose crossing of the Hellespont is still a rebuke to human arrogance.','Xerxes','reference'),
('leander','Leander','The swimmer who hated the water between Sestos and Abydos.','Leander','reference','mythological-figure'),
('proserpina','Proserpina','The girl who lost the spring when her mother lost her; Matilda in the flowers recalls her.','Proserpina|Proserpine','reference','deity'),
('urania','Urania','The Muse called on to help put the procession into verse.','Urania','reference','deity'),
('argus-purg','Argus','The hundred-eyed watchman, whose eyes the wings of the living creatures recall, and who was lulled by the tale of Syrinx.','','reference','mythological-figure'),
('syrinx','Syrinx','The nymph whose tale put Argus to sleep.','Syrinx','reference','mythological-figure'),
('ezekiel','Ezekiel','The prophet who described the living creatures as he saw them.','Ezekiel','reference','religious-figure'),
('africanus','Africanus','Scipio Africanus, named in the comparison of triumphal chariots.','Africanus','reference'),
('meleager','Meleager','The man whose life wasted with a burning firebrand, used to explain how souls can waste.','Meleager','reference','mythological-figure'),
('lachesis','Lachesis','The Fate who measures the thread of life.','Lachesis','reference','deity'),
('clotho','Clotho','The Fate who loads the flax upon the distaff.','Clotho','reference','deity'),
('pasiphae','Pasiphae','The example of unnatural lust called out on the terrace of the fire.','Pasiphae|Pasipha','reference','mythological-figure'),
('lycurgus-purg','Lycurgus','The king whose sons saw their mother again, a comparison for Statius meeting Virgil.','','reference','mythological-figure'),
('erysichthon','Erysichthon','The man withered by famine, a comparison for the gluttons.','Erysichthon','reference','mythological-figure'),
('helice','Helice','The nymph Diana drove out of the forest for tasting the poison of Venus.','Helice','reference','mythological-figure'),
('venus','Venus','The goddess of love, whose poison Helice tasted; also the planet, called Cytherea, and the Cyprian goddess the old world blamed for the madness of love.','Venus|Cytherea|Cyprian','reference','deity'),
('titus','Titus','The emperor who avenged the wounds from which the blood Judas sold poured out.','Titus','reference'),
('domitian','Domitian','The emperor whose persecution of the Christians drew Statius’s tears.','Domitian','reference'),
('juvenal','Juvenal','The satirist who came down to Limbo and told Virgil of Statius’s affection.','Juvenal','reference'),
('terence','Terence','A Latin poet Statius asks after.','Terence','reference'),
('caecilius','Caecilius','A Latin poet Statius asks after.','Caecilius','reference'),
('plautus','Plautus','A Latin poet Statius asks after.','Plautus','reference'),
('varro','Varro','A Latin poet Statius asks after.','Varro','reference'),
('persius','Persius','A Latin poet named among those in Limbo.','Persius','reference'),
('euripides','Euripides','A Greek poet in Limbo.','Euripides','reference'),
('antiphon','Antiphon','A Greek poet in Limbo.','Antiphon','reference'),
('simonides','Simonides','A Greek poet in Limbo.','Simonides','reference'),
('agathon','Agathon','A Greek poet in Limbo.','Agathon','reference'),
('antigone','Antigone','One of Statius’s own characters, seen in Limbo.','Antigone','reference','literary-figure'),
('deiphyle','Deiphyle','One of Statius’s own characters, seen in Limbo.','Deiphyle','reference','literary-figure'),
('argia','Argia','One of Statius’s own characters, seen in Limbo.','Argia','reference','literary-figure'),
('ismene','Ismene','One of Statius’s own characters, still sorrowful in Limbo.','Ismene','reference','literary-figure'),
('hypsipyle-purg','placeholder','unused','',''),
('manto-purg','placeholder','unused','',''),
('thetis-purg','placeholder','unused','',''),
('jocasta','Jocasta','The mother whose twofold grief Statius sang.','Jocasta','reference','mythological-figure'),
('clio','Clio','The Muse who accompanied Statius in the Thebaid.','Clio','reference','deity'),
('gideon','Gideon','The judge who refused the soft drinkers as companions.','Gideon','reference','religious-figure'),
('daniel','Daniel','The prophet who rejected food and won understanding.','Daniel','reference','religious-figure'),
('joshua','Joshua','The leader whose wrath still stings Achan.','Joshua','reference','religious-figure'),
('barbarossa','Barbarossa','The emperor under whose reign the Abbot of San Zeno lived.','Barbarossa','reference'),
('abbot-san-zeno','The Abbot of San Zeno','The soul on the terrace of sloth who names himself by his office in Verona.','','supporting','unnamed-person'),
('themis','Themis','The oracular goddess whose dark sayings clouded men’s minds.','Themis','reference','deity'),
('sphinx','The Sphinx','The riddler named with Themis for dark prophecy.','Sphinx','reference','mythical-being'),
('naiads','placeholder','unused','',''),
('latona-purg','placeholder','unused','',''),
('aurora-purg','placeholder','unused','',''),
('aeolus-purg','Aeolus','The keeper of the winds, who unleashes the south wind on the pine forest of Chiassi.','Aeolus','reference','deity'),
('ganymede-purg','Ganymede','The boy snatched up to the high assembly of the gods, recalled in Dante’s dream of the eagle.','Ganymede','reference','mythological-figure'),
('tithonus','Tithonus','The old consort of the dawn.','Tithonus','reference','mythological-figure'),
('samaritan-woman','The Samaritan woman','The woman who begged for the water of grace, recalled for the thirst that is never quenched.','Samaritan','reference','religious-figure'),
('luke','Luke','The evangelist who writes how Christ appeared to two travellers on the road.','Luke','reference','religious-figure'),
('psalmist','The humble Psalmist','David, dancing before the Ark with his robes girded up.','Psalmist','supporting','religious-figure'),
('justinian','Justinian','The emperor who repaired the bridle of the law — Sordello asks what good it did with the saddle empty — and who, in the sphere of Mercury, tells the whole flight of the Roman eagle from Troy to Charlemagne.','','major'),
('clement-iv','Clement','Pope Clement the Fourth, who sent the pastor of Cosenza to hunt down Manfred’s bones.','',''),
('marcellus-purg','Marcellus','The Roman whose name stands for the partisan who makes himself a tyrant.','','reference'),
('octavian','Octavian','The emperor who had Virgil’s bones buried at Naples.','Octavian','reference'),
]:add(*row)

# ====================================================== Paradiso (chapters 68-100)
# The Paradiso is a poem of teachers. Almost every soul Dante meets here is a
# theologian, a founder or an emperor, and almost none of them is introduced.
# Thomas Aquinas names twenty-three people in two cantos without explaining one.

# -------------------------------------------------- the spheres and their poets
for row in [
('marsyas','Marsyas','The satyr who challenged Apollo to a contest of music and was flayed for losing; Dante asks the god to draw him out of himself the same way.','Marsyas','reference','mythological-figure'),
('glaucus','Glaucus','The fisherman who tasted a herb and became a sea god; Dante uses him for the change he has no word for.','Glaucus','reference','mythological-figure'),
('intelligences','The Intelligences','The blessed angelic minds that turn the spheres — Dante’s astronomy and his theology are the same science.','Intelligences','reference','group'),
('pegasea','Pegasea','The Muse invoked by the name of Pegasus, asked to make genius last as long as the cities it praises.','Pegasea','reference','deity'),
('polyhymnia','Polyhymnia','The Muse of sacred song, named with her sisters when Dante says even all of them together could not tell what Beatrice’s smile was like.','Polyhymnia','reference','deity'),
]:add(*row)

# ------------------------------------------------------- Paradiso IV-V: the vows
for row in [
('samuel','Samuel','The prophet, named with Moses and Mary among the souls closest to God — none of whom, Beatrice says, sits higher in Heaven than the Seraphim Dante is looking at.','Samuel','reference','religious-figure'),
('gabriel','Gabriel','The archangel of the Annunciation, shown to men in human shape because human sight needs a shape; he crowns Mary in the eighth heaven.','Gabriel','supporting','angel'),
('mercury','Mercury','The god the old world worshipped in the planet, named with Jupiter and Mars as proof of how badly the doctrine of the spheres was misread.','Mercury','reference','deity'),
('tobias','Tobias','The man in the Book of Tobit whose blindness an angel healed; the angel is named in scripture and not here.','Tobias','reference','religious-figure'),
('lawrence','Lawrence','The deacon held to the gridiron, named with Mucius for a will that did not bend under fire.','Lawrence','reference','religious-figure'),
('mucius','Mucius','The Roman who thrust his own right hand into the flame before the enemy king, named with Saint Lawrence for the same unbending will.','Mucius|Mutius','reference'),
('nebuchadnezzar','Nebuchadnezzar','The king whose forgotten dream made him cruel until Daniel recovered it; Beatrice does for Dante what Daniel did for him.','Nebuchadnezzar','reference','religious-figure'),
('jephthah','Jephthah','The judge who vowed the first thing to meet him on his return and had to keep the vow against his daughter — Dante’s example of a vow that should have been broken.','Jephthah','reference','religious-figure'),
('iphigenia','Iphigenia','The daughter Agamemnon sacrificed for a wind, named beside Jephthah’s daughter: the same crime made twice by wise men and fools alike.','Iphigenia','reference','mythological-figure'),
]:add(*row)

# ------------------------------- Paradiso VI: Justinian and the flight of the eagle
for row in [
('agapetus','Agapetus','The pope who talked Justinian out of the heresy that Christ had one nature only.','Agapetus','reference','religious-figure'),
('belisarius','Belisarius','The general to whom Justinian handed the armies, so plainly favoured by Heaven that the emperor took it as leave to stop fighting and start legislating.','Belisarius','supporting'),
('sabines','The Sabine women','The women carried off by the first Romans; Justinian dates the eagle’s career from that theft to Lucretia’s suicide.','Sabine','reference','group'),
('brennus','Brennus','The Gaulish chief the Roman standard beat back, named first in Justinian’s roll of defeated enemies.','Brennus','reference'),
('torquatus','Torquatus','A Roman commander of the early republic, one of the names Justinian says the eagle made famous rather than the other way round.','Torquatus','reference'),
('cincinnatus','Quinctius Cincinnatus','The dictator called from his plough, named in the poem by his nickname — the unkempt hair — and again in Cacciaguida’s Florence as a measure of how far the city has fallen.','Quinctius|Cincinnatus','reference'),
('decii','The Decii','A Roman family whose men gave their own lives in battle by ritual devotion, named in Justinian’s roll of republican fame.','Decii','reference','group'),
('fabii','The Fabii','A Roman family of the early republic, named with the Decii among the houses the eagle made glorious.','Fabii','reference','group'),
('pompey','Pompey','The young commander who triumphed under the republic’s eagle and, grown old, lost to Caesar at Pharsalia.','Pompey|Pompeian','reference'),
('juba','Juba','The African king struck down by Caesar’s lightning march after Pharsalia.','Juba','reference'),
('janus','Janus','The god whose temple stood open in war; Justinian’s proof of the peace Augustus made is that its door was shut.','Janus','reference','deity'),
('ghibellines','The Ghibellines','The imperial party, told to stop conducting their faction under the eagle’s sign — the banner is not theirs.','Ghibellines','reference','group'),
('guelfs','The Guelfs','The papal party, whose new Charles is warned that the eagle has stripped the hide off stronger lions.','Guelfs|Guelphs','reference','group'),
('arabs','The Arabs','Justinian’s name for the Carthaginians who crossed the Alps with Hannibal.','Arabs|Arabians','reference','group'),
('romeo','Romeo','The pilgrim steward who made Raymond Berengar rich and married off four daughters to four kings, was accused of theft, and walked out with nothing.','Romeo','supporting'),
('raymond-berenger','Raymond Berengar','The count of Provence whose four daughters all became queens, through the work of his steward Romeo.','Berengar|Berenger','supporting'),
]:add(*row)

# ------------------------------------- Paradiso VIII-IX: Venus, Charles Martel, Folco
for row in [
('charles-martel','Charles Martel','The eldest son of Charles II, who died at twenty-four; he greets Dante as a friend from Florence and explains why a mild father breeds a grasping son.','','major'),
('charles-ii','Charles II','Charles the Second of Naples, the Cripple of Jerusalem — the new Charles warned off the eagle, mourned while still alive, and marked in the Eagle’s book with one virtue against many vices.','','supporting'),
('charles-of-valois','Charles of Valois','The Charles drawn out of France with the lance of treachery, who took Florence for the Black Guelfs and left it in ruins.','','supporting'),
('clemence','Clemence','The woman Charles Martel addresses when he foretells the wrongs his line will suffer — his wife or his daughter; the poem does not say which.','Clemence','reference'),
('dione','Dione','The mother of Venus in the old mythology, and in Dante’s sky the planet Venus itself.','Dione','reference','deity'),
('cupid','Cupid','The son of Venus, whom the old poets sent to sit in Dido’s lap in the shape of her guest’s child.','Cupid','reference','deity'),
('solon','Solon','The Athenian lawgiver, named as one of the unlike natures Providence scatters among brothers.','Solon','reference'),
('melchisedec','Melchisedec','The priest-king of Genesis, named with Solon and Xerxes to show how differently men are born to their work.','Melchisedec','reference','religious-figure'),
('esau','Esau','The twin who differed from his brother in the womb; Dante’s proof that nature does not follow family.','Esau','reference','religious-figure'),
('jacob','Jacob','Esau’s twin, named for the same argument — and, in the last heaven, one of the patriarchs seated in the rose.','Jacob','reference','religious-figure'),
('quirinus','Quirinus','Romulus under his godlike name, born of so low a father that Rome assigned him to Mars instead.','Quirinus','reference'),
('cunizza','Cunizza','Ezzelino’s sister, who lived by love and says so without apology; she shines in Venus and prophesies ruin for the March of Treviso.','Cunizza','major'),
('folco','Folco','Folquet of Marseille, troubadour turned bishop, who burned as hotly as Dido in his youth and here remembers it without shame.','Folco','major'),
('belus','Belus','The father of Dido, named so that Folco can measure his own youth against hers.','Belus','reference','mythological-figure'),
('creusa','Creusa','The wife Aeneas lost at Troy, wronged along with Sychaeus when Dido took Aeneas in.','Creusa','reference','mythological-figure'),
('demophoon','Demophoon','The man whose broken promise killed Phyllis of Rhodope, named by Folco among the great loves.','Demophoon','reference','mythological-figure'),
('iole','Iole','The girl Hercules locked in his heart, which cost him his life through Deianira’s jealousy.','Iole','reference','mythological-figure'),
('rahab','Rahab','The harlot of Jericho who hid Joshua’s spies; she is the highest soul in the sphere of Venus and the first that Christ’s harrowing took there.','Rahab','supporting','religious-figure'),
]:add(*row)

# --------------------------------------- Paradiso X-XIII: the twelve wise lights
for row in [
('albert-of-cologne','Albert of Cologne','Albertus Magnus, Aquinas’s own master, standing at his right in the first crown of lights.','Albertus','supporting','religious-figure'),
('gratian','Gratian','The canonist whose Decretum reconciled church law with civil law, which Paradise counts as a service.','Gratian','reference','religious-figure'),
('peter-lombard','Peter Lombard','The author of the Sentences, the textbook every medieval theologian was trained on; he offered his one talent to the Church as the widow offered her mite.','','supporting','religious-figure'),
('solomon','Solomon','The fifth and brightest of the twelve lights, whose wisdom the world is still hungry for; Aquinas has to explain that his unequalled seeing was kingly prudence, not universal knowledge.','','major','religious-figure'),
('dionysius-areopagite','Dionysius','The Areopagite, credited with the book on the angelic orders; Paradise confirms he got them right, having heard them from Saint Paul.','','supporting','religious-figure'),
('isidore','Isidore','Isidore of Seville, whose encyclopaedia carried the ancient world into the Middle Ages.','Isidore','reference','religious-figure'),
('bede','Bede','The English monk and historian, named with Isidore and Richard among the burning spirits.','Bede|Beda','reference','religious-figure'),
('richard-st-victor','Richard','Richard of Saint Victor, whose writing on contemplation made him, Aquinas says, more than a man at it.','Richard','reference','religious-figure'),
('siger','Siger','Siger of Brabant, who lectured in the Street of Straw in Paris and drew hatred for conclusions that were merely true; Aquinas, who argued against him on earth, names him with honour here.','Siger|Sigier','supporting','religious-figure'),
('ariadne','Ariadne','The daughter of Minos, whose crown became a constellation; Dante asks the reader to picture two such crowns turning against each other.','Ariadne','reference','mythological-figure'),
('parmenides','Parmenides','A Greek philosopher, named with Melissus and Bryson among those who set out confidently and did not know where they were going.','Parmenides','reference'),
('melissus','Melissus','A Greek philosopher named with Parmenides as a warning against quick conclusions.','Melissus','reference'),
('bryson','Bryson','A Greek geometer who claimed to have squared the circle, named among the confident and wrong.','Bryson|Brissus','reference'),
('sabellius','Sabellius','A heresiarch on the Trinity, named with Arius as one of the swords that twisted scripture out of true.','Sabellius','reference','religious-figure'),
('arius','Arius','The heresiarch who denied the Son’s full divinity, named with Sabellius for the same distortion.','Arius','reference','religious-figure'),
('dame-bertha','Dame Bertha','Any ordinary woman — the medieval equivalent of Jane Doe — warned with Ser Martin not to judge who is saved and who is damned.','Bertha','reference'),
('ser-martin','Ser Martin','Any ordinary man, named with Dame Bertha in Aquinas’s warning against confident judgement of souls.','Martin','reference'),
]:add(*row)

# --------------------------- Paradiso XI-XII: the two founders and their companies
for row in [
('francis','Francis','Francis of Assisi, whose life Aquinas tells as a marriage to Poverty; the sun that rose over the world from Ascesi — better called Orient. He comes for Guido da Montefeltro’s soul in the Inferno and loses it to a black Cherub.','','major','religious-figure'),
('poverty','Poverty','The widow no one had courted for eleven hundred years, since her first husband died on the cross; Francis married her in front of his father and his bishop.','Poverty','supporting','personification'),
('bernard-quintavalle','Bernard','Bernard of Quintavalle, the first man to follow Francis — he stripped his feet bare and ran, and thought he was running too slowly.','','supporting','religious-figure'),
('ubaldo','Ubaldo','The blessed bishop of Gubbio, whose chosen hill Dante uses to fix the position of Assisi.','Ubaldo|Ubald','reference','religious-figure'),
('amyclas','Amyclas','The fisherman too poor to fear Caesar, who did not stir when the voice that terrified the world called at his door; Poverty stood by him and nobody noticed.','Amyclas','reference'),
('pietro-bernardone','Pietro Bernardone','Francis’s father, the cloth merchant he renounced in public — a shame the poem says Francis bore like a king.','Bernardone','reference'),
('innocent-iii','Innocent','Pope Innocent the Third, who gave Francis’s rule its first seal.','Innocent','reference','religious-figure'),
('honorius','Honorius','Pope Honorius the Third, who confirmed the Franciscan rule a second time.','Honorius','reference','religious-figure'),
('dominic','Dominic','The founder of the Preachers, whose life Bonaventure tells as Aquinas told Francis’s: a champion sent against heresy, and a wheel of the chariot the Church rode in.','Dominic','major','religious-figure'),
('felix','Felix','Dominic’s father, whose name means happy — the poem says it meant it truly.','Felix','reference'),
('joanna','Joanna','Dominic’s mother, whose name Dante reads as ‘grace of God’.','Joanna','reference'),
('ostiense','Ostiense','The cardinal of Ostia, a commentator on canon law; his name and Taddeo’s stand for the profitable studies men take up instead of theology.','Ostiense','reference','religious-figure'),
('taddeo','Taddeo','A famous physician of Bologna, named with Ostiense for the lucrative learning that draws students away from the bread of Heaven.','Taddeo','reference'),
('bonaventure','Bonaventure','The Franciscan minister general, who tells the life of Dominic in return for Aquinas telling the life of Francis — and names his own order’s deserters while he is at it.','Bonaventure|Bonaventura','major','religious-figure'),
('illuminato','Illuminato','One of the first companions of Francis, who went with him to Egypt.','Illuminato','reference','religious-figure'),
('augustine-of-assisi','Augustino','An early Franciscan, named with Illuminato among the first to go barefoot and take the cord; Longfellow spells him Agostino.','Augustino|Agostino','reference','religious-figure'),
('hugh-st-victor','Hugh of Saint Victor','The theologian of the Paris abbey, named among the lights of Bonaventure’s crown.','','reference','religious-figure'),
('peter-mangiatore','Peter Mangiatore','Peter Comestor, ‘the eater’ — so called for devouring books; Longfellow keeps the Italian, Mangiador.','Mangiatore|Mangiador','reference','religious-figure'),
('peter-of-spain','Peter of Spain','The logician whose twelve books of Summulae were the standard textbook — and who became Pope John XXI.','','reference','religious-figure'),
('nathan','Nathan','The prophet who told David his own crime back to him as a parable.','Nathan','reference','religious-figure'),
('chrysostom','Chrysostom','John Chrysostom, patriarch of Constantinople, the golden-mouthed preacher.','Chrysostom','reference','religious-figure'),
('anselm-canterbury','Anselm','Anselm of Canterbury, named among the lights; Longfellow spells him Anselmus.','Anselmus','reference','religious-figure'),
('donatus','Donatus','The grammarian whose textbook taught the first of the liberal arts to the whole Middle Ages.','Donatus','reference'),
('rabanus','Rabanus','Rabanus Maurus, the Carolingian scholar and commentator on scripture.','Rabanus','reference','religious-figure'),
('joachim','Joachim','The Calabrian abbot Joachim of Fiore, gifted with prophecy — praised here by a Franciscan, though his followers had split the order.','Joachim','supporting','religious-figure'),
]:add(*row)

# -------------------------------- Paradiso XV-XVII: Cacciaguida and the old Florence
for row in [
('anchises','Anchises','Aeneas’s father, who reached out to his son in Elysium; Cacciaguida greets Dante with the same tenderness.','Anchises','reference','mythological-figure'),
('cacciaguida','Cacciaguida','Dante’s great-great-grandfather, who was christened in the Baptistery, knighted by the Emperor Conrad and died on crusade; he describes the old Florence, names the houses, and tells Dante he will be exiled.','Cacciaguida','central'),
('eliseo','Eliseo','One of Cacciaguida’s two brothers; the family name may have come from him.','Eliseo','reference'),
('moronto','Moronto','One of Cacciaguida’s two brothers, named once and never again.','Moronto','reference'),
('emperor-conrad','Conrad','The Emperor Conrad the Third, who knighted Cacciaguida and took him on the crusade he died in.','Conrad','supporting'),
('bellincion-berti','Bellincion Berti','A great Florentine of the plain old city, who went about belted in leather and bone; his wife left her mirror unpainted.','Berti|Bellincion|Bellincione','supporting'),
('cianghella','Cianghella','A Florentine woman of Dante’s own day, notorious enough that the old city would have gawked at her.','Cianghella','reference'),
('lapo-salterello','Lapo Salterello','A Florentine lawyer and politician of Dante’s day, named with Cianghella as the kind of citizen the old city could not have imagined.','Salterello','reference'),
('old-florentine-houses','The old houses of Florence','Cacciaguida’s roll of the families who made the city when it was small and at peace. Almost all of them were ruined, exiled or absorbed within a century, and Dante names them the way a man reads gravestones.','Ughi|Catellini|Filippi|Greci|Ormanni|Alberichi|Sannella|Arca|Ardinghi|Bostichi|Ravignani|Pressa|Galigaio|Sacchetti|Giuochi|Fifanti|Barucci|Galli|Calfucci|Sizii|Arrigucci|Gualterotti|Importuni|Nerli|Vecchietti|Infangato|Caponsacco|Giuda','supporting','group'),
('ubertino-donato','Ubertino Donato','A Florentine who was displeased when his father-in-law married another daughter into the Adimari — one small snub, still remembered.','Ubertino|Ubertin','reference'),
('guinevere','Guinevere','Arthur’s queen, whose first slip with Lancelot drew a cough from her lady-in-waiting; Beatrice’s smile at Dante is the same kind of warning.','Guinevere|Guenever','reference','literary-figure'),
('thomas-apostle','Thomas','The apostle, whose feast day keeps alive the name of the great baron of Florence.','','reference','religious-figure'),
('hugh-the-great','The great baron','Hugh of Tuscany, the imperial vicar who knighted several Florentine families into his own arms; Dante keeps his memory with the feast of Saint Thomas.','','reference'),
('clymene','Clymene','Phaethon’s mother, who confirmed to him what he had heard about his father — and so made every father since wary of his son’s questions.','Clymene','reference','mythological-figure'),
('hippolytus','Hippolytus','The son driven out of Athens by his stepmother’s lie; Cacciaguida uses him to tell Dante how exile comes — undeserved, and arranged.','Hippolytus','reference','mythological-figure'),
('clement-v','The Gascon','Pope Clement the Fifth, who called the Emperor Henry into Italy and then worked against him.','Gascon','supporting','religious-figure'),
('henry-vii','Henry','Henry the Seventh of Luxembourg, the emperor Dante hoped would set Italy right; a throne is already crowned and waiting for him in the rose.','','supporting'),
('bartolommeo-scala','The great Lombard','Bartolommeo della Scala of Verona, Dante’s first host in exile, who bears the imperial eagle over the ladder of his arms.','','supporting'),
]:add(*row)

# ------------------------------ Paradiso XVIII-XX: the cross, the eagle, the just
for row in [
('maccabee','The Maccabee','Judas Maccabaeus, whose name spins a light like a top in the cross of Mars.','Maccabee','reference','religious-figure'),
('william-of-orange','William of Orange','The hero of a French epic cycle, a warrior who ended as a monk; named with his companion Renouard.','','supporting'),
('renouard','Renouard','The giant Saracen convert of the William of Orange poems, who fought with a club.','Renouard','reference','literary-figure'),
('godfrey','Godfrey','Godfrey of Bouillon, who led the First Crusade and took Jerusalem.','Godfrey','supporting'),
('cripple-of-jerusalem','The Cripple of Jerusalem','Charles the Second of Naples as the Eagle’s book records him: one stroke of a letter for his goodness against a thousand for his vices.','','reference'),
('persians','The Persians','The heathen who will stand up at the judgement and ask Christian kings what the record says about them.','Persians','reference','group'),
('ethiopians','The Ethiopians','Thirsty for cold water in Purgatory, and in Paradise the heathen who will condemn Christians when the two companies are divided.','Ethiopian|Ethiopians|Ethiop','reference','group'),
('ripheus','Ripheus','A Trojan named once by Virgil as the most just of his people; Dante puts him in the eye of the Eagle, a pagan saved, and offers no explanation the reader can check.','Ripheus','supporting','literary-figure'),
('william-of-sicily','William','William the Second of Sicily, called the Good, mourned by the land that now has to endure Charles and Frederick alive.','','supporting'),
]:add(*row)

# --------------------------- Paradiso XXI-XXII: the contemplatives and their ladder
for row in [
('peter-damian','Peter Damian','The hermit of the Adriatic who became a cardinal against his will; he answers Dante out of the ladder of gold and then breaks off into a cry against fat prelates.','Damian|Damiano','major','religious-figure'),
('benedict','Benedict','The founder of Western monasticism, who cleared Monte Cassino of its pagans; he shows Dante the ladder and says his rule is now waste paper.','Benedict','major','religious-figure'),
('macarius','Macarius','An early desert father, named by Benedict among his own.','Macarius','reference','religious-figure'),
('romualdus','Romualdus','Romuald, founder of the Camaldolese hermits, named by Benedict with Macarius.','Romualdus|Romuald','reference','religious-figure'),
('hyperion','Hyperion','The Titan father of the sun in the old mythology; Dante looks back down through the spheres and names the planets by their gods.','Hyperion','reference','deity'),
('maia','Maia','The mother of Mercury, and so Dante’s name for the planet.','Maia','reference','deity'),
]:add(*row)

# ------------------------- Paradiso XXIV-XXVII: the examinations and Peter’s anger
for row in [
('james-apostle','James','The apostle, who examines Dante on hope; the baron of Compostela, for whose sake Galicia is a place of pilgrimage.','','supporting','religious-figure'),
('john-evangelist','John','The evangelist who lay on Christ’s breast and was taken from the cross to care for his mother; he examines Dante on love, and puts down the legend that he went to Heaven in the body.','','supporting','religious-figure'),
('ananias','Ananias','The disciple whose hands restored Saul’s sight; Beatrice’s look does as much for Dante’s.','Ananias','reference','religious-figure'),
('linus','Linus','An early pope and martyr, named by Saint Peter with Cletus among those whose blood was not shed to buy gold.','Linus','reference','religious-figure'),
('cletus','Cletus','An early pope and martyr, named with Linus in Peter’s indictment of his own successors.','Cletus','reference','religious-figure'),
('sixtus','Sixtus','A martyred pope, named in Peter’s roll of those who died for the life of Heaven and not for a bank.','Sixtus','reference','religious-figure'),
('pope-pius','Pius','A martyred pope, named with Sixtus, Callixtus and Urban.','Pius','reference','religious-figure'),
('callixtus','Callixtus','A martyred pope in Peter’s roll.','Callixtus|Calixtus','reference','religious-figure'),
('urban','Urban','A martyred pope, the last named in Peter’s roll before he turns on the living ones.','Urban','reference','religious-figure'),
('gascons','The Gascons','With the Cahorsines, the nations Peter says are preparing to drink the blood of the Church — Clement the Fifth’s countrymen and John the Twenty-Second’s.','Gascons','reference','group'),
('cahorsines','The Cahorsines','Named with the Gascons in Peter’s prophecy; Cahors was a byword for usury and the birthplace of Pope John XXII.','Cahorsines|Caorsines','reference','group'),
('europa','Europa','The girl Jove carried off in the shape of a bull; Dante marks how far he has travelled by the shore where she was taken.','Europa','reference','mythological-figure'),
('leda','Leda','The mother of the Twins; Dante calls Gemini her fair nest, and Beatrice’s look lifts him out of it.','Leda','reference','mythological-figure'),
]:add(*row)

# ------------------------------- Paradiso XXVIII-XXIX: the orders of the angels
for row in [
('thrones','The Thrones','The third angelic order, mirrors in which God’s judgement is reflected down to the spheres below.','Thrones','supporting','angel'),
('dominions','The Dominions','The fourth angelic order, first of the second hierarchy.','Dominions','reference','angel'),
('virtues','The Virtues','The fifth angelic order, named between the Dominions and the Powers.','','reference','angel'),
('powers','The Powers','The sixth angelic order, closing the second hierarchy.','Powers','reference','angel'),
('principalities','The Principalities','The seventh angelic order, wheeling in the penultimate dances.','Principalities','reference','angel'),
('archangels','The Archangels','The eighth angelic order, named with the Principalities.','Archangels','reference','angel'),
('boreas','Boreas','The north wind, whose gentler cheek leaves the sky clear; Dante uses it for the air after Beatrice has swept an error away.','Boreas','reference','deity'),
('jerome','Jerome','The church father who wrote that the angels were made long ages before the rest of creation — which Beatrice contradicts, gently, on the authority of scripture.','Jerome','reference','religious-figure'),
('anthony','Anthony','Saint Anthony the Abbot, whose pig is fattened on the offerings of the credulous, along with others the poem says are more piggish still.','Anthony','reference','religious-figure'),
('spaniards','The Spaniards','Named with the Indians and the Jews as witnesses that the darkness at the Crucifixion was seen everywhere, not only at Jerusalem.','Spaniards','reference','group'),
('indians','The Indians','Named for their forests and their thirst, and with the Spaniards as witnesses to the eclipse at the Crucifixion.','Indians|Indian','reference','group'),
]:add(*row)

# ------------------------------------ Paradiso XXXI-XXXIII: the rose and the vision
for row in [
('bernard-clairvaux','Bernard','Bernard of Clairvaux, who takes over from Beatrice for the last three cantos, shows Dante the order of the rose, and makes the prayer to the Virgin that wins him the final sight.','','central','religious-figure'),
('veronica','The Veronica','The cloth at Saint Peter’s said to carry the face of Christ; Dante uses the pilgrim who comes from Croatia to stare at it for his own staring at Bernard.','Veronica','reference'),
('sarah','Sarah','Abraham’s wife, seated in the rose in the line of Hebrew women that divides the flower.','Sarah','reference','religious-figure'),
('rebecca','Rebecca','Isaac’s wife, named in the line of Hebrew women below Eve, Mary, Rachel and Beatrice.','Rebecca','reference','religious-figure'),
('judith','Judith','The woman who killed Holofernes, seated in the rose with Sarah and Rebecca.','Judith','reference','religious-figure'),
('anna','Anna','The mother of Mary, seated opposite Saint Peter and so content with looking at her daughter that she will not turn her eyes even to sing.','Anna','reference','religious-figure'),
('augustine','Augustine','Augustine of Hippo, seated with Francis and Benedict beneath John the Baptist; the advocate of the Christian ages supplied him his rhetoric.','Augustine','supporting','religious-figure'),
('orosius','The advocate of the Christian ages','Paulus Orosius, whose history against the pagans armed Augustine with his arguments; the poem names his work and not his name.','','reference','religious-figure'),
('sibyl','The Sibyl','The prophetess whose answers were written on light leaves and scattered by the wind — Dante’s figure for how much of the vision he has already lost.','Sibyl','reference','mythological-figure'),
]:add(*row)

entities[:]=[e for e in entities if e['name']!='placeholder']
print(len(entities),'entities after Paradiso')
Path(__file__).parent.joinpath('editorial.json').write_text(json.dumps(dict(
 contentVersion='2026-09-11.2',
 coverage='Both full English editions. All three canticles are authored: Inferno (chapters 1-34), Purgatorio (35-67) and Paradiso (68-100). Named people, gods, angels, devils, personified powers, named monsters and named peoples. Places, rivers, mountains and book titles are not cast, except where a river of the underworld is treated as a power.',
 entities=entities),ensure_ascii=False,indent=2)+'\n')
print(len(entities),'entities')
