"""Manually authored recognition cards for both full English texts of the Comedy.

The original is Longfellow's blank-verse translation; the modern edition is
prose. Both run to 100 cantos and 4,812 paragraphs and align paragraph for
paragraph. Longfellow spells the guide Virgilius where the prose says Virgil.

Almost everyone in this poem is a real person — a Florentine neighbour, a pope,
an emperor, a classical poet, a saint — and a reader without notes cannot place
them. That is what these cards are for.

Chapters 1-34 are the Inferno, 35-67 the Purgatorio, 68-100 the Paradiso.

Scope: named people, gods, angels, devils, personified powers, named monsters
and named peoples. Places, rivers, mountains and the names of books are not
cast, except where a river of the underworld is treated as a power.
"""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

# --------------------------------------------------------------- the travellers
for row in [
('dante','Dante','The poet who is also the pilgrim of his own poem. He names himself exactly once in the whole Comedy, when Beatrice calls him by name in the earthly paradise.','Dante','central'),
('virgil','Virgil','The Roman poet of the Aeneid, sent to guide Dante through Hell and Purgatory; a soul of Limbo, saved from damnation but not from exclusion. Longfellow spells him Virgilius.','Virgilius|Virgil','central'),
('beatrice','Beatrice','The Florentine woman Dante loved, now among the blessed; she sends Virgil to his aid and takes over as his guide in the earthly paradise and through Heaven.','Beatrice','central'),
('statius','Statius','The Roman poet of the Thebaid, who joins the travellers in Purgatory and reveals that Virgil’s own verses converted him.','Statius','major'),
]:add(*row)

# ------------------------------------------------- Inferno: the powers of Hell
for row in [
('lucifer','Lucifer','The emperor of the kingdom of grief, fixed in ice at the centre of the earth; also called Dis, Satan and Beelzebub.','Lucifer|Satan|Beelzebub','major','deity'),
('charon','Charon','The ancient ferryman with wheels of flame about his eyes, who carries the damned across Acheron.','Charon','supporting','mythological-figure'),
('minos','Minos','The judge of the damned, who winds his tail about himself to sentence each soul to its circle.','Minos','supporting','mythological-figure'),
('cerberus','Cerberus','The three-throated dog who howls over the gluttons in the rain.','Cerberus','supporting','mythological-figure'),
('plutus','Plutus','The hoarse-voiced guardian of the fourth circle, where the misers and spendthrifts roll their weights.','Plutus','supporting','mythological-figure'),
('phlegyas','Phlegyas','The boatman who ferries Dante and Virgil across the marsh of Styx.','Phlegyas','supporting','mythological-figure'),
('megaera','Megaera','One of the three Furies on the tower of Dis.','Megaera','supporting','deity'),
('alecto','Alecto','One of the three Furies on the tower of Dis.','Alecto','supporting','deity'),
('tisiphone','Tisiphone','One of the three Furies on the tower of Dis.','Tisiphone','supporting','deity'),
('medusa','Medusa','The Gorgon the Furies call for, whose face would turn Dante to stone.','Medusa|Gorgon','supporting','mythological-figure'),
('minotaur','The Minotaur','The bull-man of Crete, who guards the descent into the circle of violence.','Minotaur','supporting','mythical-being'),
('chiron','Chiron','The centaur who raised Achilles, chief of the troop that patrols the river of blood.','Chiron','supporting','mythological-figure'),
('nessus','Nessus','The centaur who died for Deianira and now guides the travellers along the boiling river.','Nessus','supporting','mythological-figure'),
('pholus','Pholus','A centaur of the river bank, full of wrath.','Pholus','supporting','mythological-figure'),
('harpies','The Harpies','The bird-women who nest in the wood of the suicides.','Harpies','supporting','group'),
('geryon','Geryon','The monster with an honest face and a scorpion’s tail, who carries the travellers down to the eighth circle.','Geryon','supporting','mythical-being'),
('malebranche','The Malebranche','The demon squad of the fifth ditch, who hook the barrators out of the boiling pitch.','Malebranche','supporting','group'),
('malacoda','Malacoda','The captain of the Malebranche, who lies to Virgil about the broken bridge.','Malacoda','supporting','deity'),
('barbariccia','Barbariccia','A demon of the Malebranche, put in charge of the squad of ten.','Barbariccia','supporting','deity'),
('alichino','Alichino','A demon of the Malebranche.','Alichino','supporting','deity'),
('calcabrina','Calcabrina','A demon of the Malebranche.','Calcabrina','supporting','deity'),
('cagnazzo','Cagnazzo','A demon of the Malebranche.','Cagnazzo','supporting','deity'),
('libicocco','Libicocco','A demon of the Malebranche.','Libicocco','supporting','deity'),
('draghignazzo','Draghignazzo','A demon of the Malebranche.','Draghignazzo','supporting','deity'),
('ciriatto','Ciriatto','A demon of the Malebranche, tusked like a boar.','Ciriatto','supporting','deity'),
('graffiacane','Graffiacane','A demon of the Malebranche.','Graffiacane','supporting','deity'),
('farfarello','Farfarello','A demon of the Malebranche.','Farfarello','supporting','deity'),
('rubicante','Rubicante','A demon of the Malebranche.','Rubicante','supporting','deity'),
('scarmiglione','Scarmiglione','A demon of the Malebranche.','Scarmiglione','supporting','deity'),
('nimrod','Nimrod','The giant of Babel, whose gibberish no one can understand; his tower is why the world has many tongues.','Nimrod','supporting'),
('ephialtes','Ephialtes','A giant who warred against the gods, bound in chains at the pit’s edge.','Ephialtes','supporting','mythological-figure'),
('briareus','Briareus','A giant of the war against the gods, named but not seen.','Briareus','reference','mythological-figure'),
('antaeus','Antaeus','The unbound giant who lifts the travellers down to the frozen lake.','Antaeus','supporting','mythological-figure'),
('tityus','Tityus','A giant named among those the travellers do not want to be handed to.','Tityus','reference','mythological-figure'),
('typhoeus','Typhoeus','A giant named among those the travellers do not want to be handed to.','Typhon|Typhoeus','reference','mythological-figure'),
('old-man-of-crete','The Old Man of Crete','The great statue inside Mount Ida, cracked and weeping, whose tears make the rivers of Hell.','','supporting','personification'),
('fortune','Fortune','The ministering power Virgil defends, who turns the goods of the world from one people to another.','Fortune','supporting','personification'),
]:add(*row)

# ------------------------------------------- Inferno: the souls Dante meets
for row in [
('homer','Homer','The sovereign poet, first of the four who meet Virgil in Limbo.','Homer','supporting'),
('horace','Horace','The Roman satirist, one of the four poets of Limbo.','Horace','supporting'),
('ovid','Ovid','The Roman poet of the Metamorphoses, one of the four poets of Limbo.','Ovid','supporting'),
('lucan','Lucan','The Roman poet of the Pharsalia, one of the four poets of Limbo.','Lucan','supporting'),
('electra','Electra','Dardanus’s mother, seen among the great souls of Limbo.','Electra','reference'),
('hector','Hector','Troy’s defender, seen among the great souls of Limbo.','Hector','reference'),
('aeneas','Aeneas','The founder of the Roman line, seen among the great souls of Limbo; his journey to the dead is Dante’s precedent.','Aeneas','supporting'),
('camilla','Camilla','The warrior maiden of the Aeneid, who died for Italy.','Camilla','reference'),
('penthesilea','Penthesilea','The Amazon queen, seen among the great souls of Limbo.','Penthesilea','reference'),
('latinus','Latinus','The Latin king, seated with his daughter in Limbo.','Latinus','reference'),
('lavinia','Lavinia','Latinus’s daughter, seated beside him in Limbo.','Lavinia','reference'),
('brutus-elder','Brutus','The Brutus who drove out Tarquin and founded the Roman republic, seen in Limbo.','',''),
('brutus-caesar','Brutus','Caesar’s assassin, chewed in Lucifer’s mouth at the centre of Hell.','',''),
('tarquin','Tarquin','The last king of Rome, driven out by Brutus.','Tarquin','reference'),
('lucretia','Lucretia','A Roman matron seen among the great souls of Limbo.','Lucretia','reference'),
('julia','Julia','Caesar’s daughter and Pompey’s wife, seen in Limbo.','Julia','reference'),
('marcia','Marcia','Cato’s wife, seen in Limbo; Virgil invokes her when asking Cato’s leave in Purgatory.','Marcia','reference'),
('cornelia','Cornelia','The mother of the Gracchi, seen in Limbo.','Cornelia','reference'),
('saladin','Saladin','The Sultan of Egypt, seated alone and apart in Limbo.','Saladin','reference'),
('aristotle','The master of those who know','Aristotle, seated in the philosophical family of Limbo; the poem names him only by that title.','','supporting','unnamed-person'),
('socrates','Socrates','The Athenian philosopher, closest to Aristotle in Limbo.','Socrates','reference'),
('plato','Plato','The Athenian philosopher, closest to Aristotle in Limbo.','Plato','reference'),
('democritus','Democritus','The philosopher who attributes the world to chance.','Democritus','reference'),
('diogenes','Diogenes','A philosopher of Limbo.','Diogenes','reference'),
('anaxagoras','Anaxagoras','A philosopher of Limbo.','Anaxagoras','reference'),
('thales','Thales','A philosopher of Limbo.','Thales','reference'),
('zeno','Zeno','A philosopher of Limbo.','Zeno','reference'),
('empedocles','Empedocles','A philosopher of Limbo.','Empedocles','reference'),
('heraclitus','Heraclitus','A philosopher of Limbo.','Heraclitus','reference'),
('dioscorides','Dioscorides','The great collector of the properties of plants.','Dioscorides','reference'),
('orpheus','Orpheus','The singer of myth, seen in Limbo.','Orpheus','reference'),
('cicero','Cicero','The Roman orator, seen in Limbo. Longfellow spells him Tully.','Cicero|Tully','reference'),
('livy','Livy','The Roman historian, seen in Limbo.','Livy','reference'),
('seneca','Seneca','The Roman moralist, seen in Limbo.','Seneca','reference'),
('euclid','Euclid','The geometer, seen in Limbo.','Euclid','reference'),
('ptolemy','Ptolemy','The astronomer, seen in Limbo.','Ptolemy','reference'),
('galen','Galen','The physician, seen in Limbo.','Galen','reference'),
('hippocrates','Hippocrates','The physician, seen in Limbo.','Hippocrates','reference'),
('avicenna','Avicenna','The Persian physician and philosopher, seen in Limbo.','Avicenna','reference'),
('averroes','Averroes','The Arab philosopher who wrote the great Commentary on Aristotle.','Averroes','reference'),
('semiramis','Semiramis','The Assyrian queen who made lust lawful, first of the carnal sinners named.','Semiramis','supporting'),
('ninus','Ninus','Semiramis’s husband, whom she succeeded.','Ninus','reference'),
('dido','Dido','The queen of Carthage who killed herself for love and broke faith with Sychaeus’s ashes.','Dido','supporting'),
('sychaeus','Sychaeus','Dido’s dead husband, whose ashes she broke faith with.','Sychaeus','reference'),
('cleopatra','Cleopatra','The Egyptian queen, among the carnal sinners.','Cleopatra','reference'),
('helen','Helen','The woman for whose sake the Trojan war was fought.','Helen','reference'),
('achilles','Achilles','The Greek hero who at the last fought against Love.','Achilles','supporting'),
('paris','Paris','The Trojan who carried Helen away.','Paris','reference'),
('tristan','Tristan','The lover of romance, among the carnal sinners.','Tristan','reference'),
('francesca','Francesca','Francesca da Rimini, who tells Dante how she and her husband’s brother were carried away by a book, and were killed for it.','Francesca','major'),
('lancelot','Lancelot','The knight whose story Francesca and her companion were reading.','Lancelot|Launcelot','reference','literary-figure'),
('ciacco','Ciacco','A Florentine glutton who prophesies the city’s coming strife.','Ciacco','supporting'),
('farinata','Farinata','Farinata degli Uberti, the Ghibelline leader who rises out of his burning tomb and speaks of Florence.','Farinata','major'),
('guido-cavalcanti','Guido','Guido Cavalcanti, the poet and Dante’s friend, asked after by his father in the tombs of the heretics.','',''),
('frederick-ii','Frederick','The emperor Frederick the Second, named as lying among the Epicureans, and whose leaden capes are a byword.','Frederick','supporting'),
('cardinal','The Cardinal','Ottaviano degli Ubaldini, named only by his office among the heretics.','Cardinal','reference'),
('anastasius','Anastasius','The pope whose tomb Dante passes, said to have been led from the true path.','Anastasius','reference'),
('photinus','Photinus','The deacon said to have led Pope Anastasius astray.','Photinus','reference'),
('alexander-tyrant','Alexander','A tyrant boiling in the river of blood, named beside Dionysius.','',''),
('alexander-great','Alexander','Alexander the Great, whose army in India saw flames fall unbroken from the sky.','',''),
('dionysius','Dionysius','The tyrant of Syracuse, boiling in the river of blood.','Dionysius','reference'),
('azzolino','Azzolino','Ezzelino da Romano, the black-haired tyrant in the river of blood.','Azzolino','reference'),
('obizzo','Obizzo','Obizzo d’Este, the fair-haired tyrant in the river of blood, killed by his own stepson.','Obizzo','reference'),
('attila','Attila','The scourge of the earth, deep in the boiling blood.','Attila','reference'),
('pyrrhus','Pyrrhus','A tyrant in the boiling blood.','Pyrrhus','reference'),
('sextus','Sextus','A tyrant in the boiling blood.','Sextus','reference'),
('rinier-corneto','Rinier da Corneto','A highway robber, boiling in the river of blood.','',''),
('rinier-pazzo','Rinier Pazzo','A highway robber, boiling in the river of blood.','',''),
('pier-della-vigna','The one who held both keys','Frederick the Second’s chancellor, who turned his master’s heart softly in locking and unlocking, and killed himself when envy turned the court against him. He is the speaking tree of the wood of the suicides, and the canto never gives his name.','','supporting','unnamed-person'),
('lano','Lano','A Sienese squanderer, hunted through the wood by black hounds.','Lano','reference'),
('jacopo-sant-andrea','Jacopo da Sant’Andrea','A Paduan squanderer, torn apart by the hounds in the wood of the suicides.','',''),
('florentine-suicide','The Florentine who hanged himself','The bush who speaks last in the wood, from the city that changed its patron saint to the Baptist.','','supporting','unnamed-person'),
('capaneus','Capaneus','One of the seven kings who besieged Thebes, who held God in contempt and holds him in contempt still on the burning sand.','Capaneus','supporting'),
('brunetto-latini','Brunetto','Ser Brunetto Latini, the Florentine scholar who taught Dante how man makes himself eternal, and whom Dante finds among the sodomites.','Brunetto','major'),
('priscian','Priscian','A grammarian named among the clerks on the burning sand.','Priscian','reference'),
('francesco-accorso','Francesco d’Accorso','A Bolognese jurist named among the clerks on the burning sand. Longfellow calls him Francis of Accorso.','Accorso','reference'),
('guido-guerra','Guido Guerra','A Florentine of great worth, grandson of the good Gualdrada, one of the three who circle on the burning sand. Longfellow writes the name as one word, Guidoguerra.','Guidoguerra','supporting'),
('gualdrada','Gualdrada','The Florentine woman named as Guido Guerra’s grandmother.','Gualdrada','reference'),
('tegghiaio','Tegghiaio','Tegghiaio Aldobrandi, whose counsel Florence should have heeded.','Tegghiaio','reference'),
('jacopo-rusticucci','Jacopo Rusticucci','A Florentine who blames his savage wife for his ruin, one of the three on the burning sand.','',''),
('guglielmo-borsiere','Guglielmo Borsiere','A Florentine newly arrived in Hell, who has been telling the others how the city has changed.','Guglielmo','reference'),
('vitaliano','Vitaliano','A Paduan usurer, expected in Hell by the one already there.','Vitaliano','reference'),
('venedico','Venedico','Venedico Caccianemico, a Bolognese who sold his own sister to the Marquis.','Venedico','supporting'),
('ghisola','Ghisola','Venedico’s sister, whom he persuaded to satisfy the Marquis.','Ghisola','reference'),
('jason','Jason','The leader of the Argonauts, punished as a seducer for Hypsipyle and Medea.','Jason','supporting'),
('hypsipyle','Hypsipyle','The woman Jason deceived and abandoned on Lemnos.','Hypsipyle','reference'),
('medea','Medea','The woman Jason abandoned after Hypsipyle.','Medea','reference'),
('alessio-interminei','Alessio Interminei','A flatterer of Lucca, sunk in filth.','Alessio','reference'),
('thais','Thais','The harlot of Terence’s comedy, named as the last of the flatterers.','Thais','reference','literary-figure'),
('simon-magus','Simon Magus','The man who tried to buy the power of the Holy Spirit, and gave his name to the sin punished in the third ditch.','',''),
('nicholas-iii','Nicholas','Pope Nicholas the Third, planted head downward in the rock, who mistakes Dante for the pope who will succeed him.','Nicholas','supporting'),
('boniface','Boniface','Pope Boniface the Eighth, whom Nicholas mistakes Dante for and expects to take his place head-down in the rock.','','supporting'),
('clement','Clement','The pope from the west who will come after Boniface, a lawless shepherd.','Clement','reference'),
('constantine','Constantine','The emperor whose gift to the first wealthy Father is named as the root of the Church’s corruption.','Constantine','reference'),
('sylvester','Sylvester','The pope Constantine sought out at Soracte to cure his leprosy.','Sylvester','reference'),
('amphiaraus','Amphiaraus','One of the seven against Thebes, swallowed by the earth; now a diviner walking backwards.','Amphiaraus','reference'),
('tiresias','Tiresias','The Theban seer who changed from man to woman and back, among the diviners.','Tiresias','supporting'),
('aruns','Aruns','An Etruscan diviner of the hills of Luni.','Aruns','reference'),
('manto','Manto','Tiresias’s daughter, the virgin seer who settled where Mantua now stands; Virgil tells her story to correct the legend of his own city.','Manto','supporting'),
('eurypylus','Eurypylus','The augur who with Calchas cut the first cable at Aulis.','Eurypylus','reference'),
('calchas','Calchas','The Greek augur of the Trojan war.','Calchas','reference'),
('michael-scot','Michael Scot','The Scottish astrologer, thin in the flanks, who knew every trick of magical illusion.','',''),
('guido-bonatti','Guido Bonatti','An astrologer of Forlì, among the diviners.','',''),
('asdente','Asdente','A cobbler of Parma turned soothsayer, who now wishes he had stuck to his leather.','Asdente','reference'),
('santa-zita-elder','The elder of Santa Zita','The barrator of Lucca whom a demon carries in and throws into the pitch.','','supporting','unnamed-person'),
('ciampolo','The Navarrese','The barrator born in the kingdom of Navarre, who tricks the demons into letting him dive.','','supporting','unnamed-person'),
('fra-gomita','Fra Gomita','A friar of Gallura, a vessel of every fraud, who sold his master’s enemies their freedom.','Gomita','reference'),
('michel-zanche','Don Michel Zanche','A barrator of Logodoro in Sardinia.','Zanche','reference'),
('catalano','Catalano','A Jovial Friar of Bologna, one of the two hypocrites in leaden capes who governed Florence together.','Catalano','supporting'),
('loderingo','Loderingo','A Jovial Friar of Bologna, Catalano’s partner in governing Florence.','Loderingo','supporting'),
('caiaphas','The one pinned to the ground','The high priest who counselled that one man should suffer for the people, crucified across the path of the hypocrites.','','supporting','unnamed-person'),
('vanni-fucci','Vanni Fucci','A thief of Pistoia, a mule of a man, who robbed the sacristy and let another man be blamed.','Vanni Fucci','supporting'),
('cacus','Cacus','The centaur who guards the thieves, whose thefts by fraud set him apart from his brothers.','Cacus','supporting','mythological-figure'),
('cianfa','Cianfa','A Florentine thief, transformed into a six-footed serpent.','Cianfa','reference'),
('agnello','Agnello','A Florentine thief, fused with the serpent that attacks him.','Agnello','reference'),
('buoso-abati','Buoso','A Florentine thief, changed into a serpent as the poet watches.','',''),
('buoso-donati','Buoso Donati','The dead man whom Gianni Schicchi impersonated in order to forge a will.','',''),
('puccio','Puccio','A Florentine thief, the only one of the five who was not transformed.','Puccio','reference'),
('ulysses','Ulysses','The Greek whose cunning took Troy, and who tells of his last voyage beyond the pillars of Hercules; he burns in a double flame with Diomedes.','Ulysses','major'),
('diomedes','Diomedes','Ulysses’s companion, burning in the same flame. Longfellow spells him Diomed.','Diomedes|Diomed','supporting'),
('deidamia','Deidamia','Achilles’s bride, who still mourns him; the cunning that took him from her is part of what Ulysses burns for.','Deidamia','reference'),
('guido-montefeltro','Guido','Guido da Montefeltro, the soldier turned friar, damned for advising Boniface to promise much and keep little.','',''),
('guido-cassero','Messer Guido','Guido del Cassero, one of the two best men of Fano, warned of drowning off La Cattolica.','',''),
('angiolello','Angiolello','One of the two best men of Fano, warned with Guido del Cassero.','Angiolello','reference'),
('mahomet','Mahomet','The founder of Islam, cleft from chin to belly among the sowers of discord.','Mahomet|Mohammed','supporting'),
('ali','Ali','Cleft in the face, walking weeping before Mahomet.','Ali','reference'),
('fra-dolcino','Fra Dolcino','The heretic leader whom Mahomet sends a warning to arm himself with food.','Dolcino','reference'),
('pier-da-medicina','Pier da Medicina','A sower of discord with his throat pierced and his nose cut away, who sends the warning to Fano.','',''),
('curio','Curio','The shade with his tongue cut out, who urged Caesar across the Rubicon.','Curio','reference'),
('mosca','Mosca','Mosca dei Lamberti, whose counsel — "a thing done has an end" — began the Guelf and Ghibelline split in Florence.','Mosca','supporting'),
('bertran-de-born','Bertran de Born','The troubadour who carries his own severed head like a lantern, punished for setting a son against his father.','Bertran|Bertram','supporting'),
('geri-del-bello','Geri del Bello','Dante’s kinsman, seen pointing at him in anger because his death is unavenged.','Geri','supporting'),
('alberto-siena','Alberto','Alberto of Siena, who had the Aretine alchemist burned for a joke about flying.','',''),
('capocchio','Capocchio','An alchemist who falsified metals, and a good ape of nature.','Capocchio','supporting'),
('gianni-schicchi','Gianni Schicchi','The Florentine who impersonated the dead Buoso Donati to forge a will and take the best mare in the stud.','Schicchi','supporting'),
('myrrha','Myrrha','The shade who disguised herself to lie with her own father, running mad beside Gianni Schicchi.','Myrrha','supporting'),
('master-adam','Master Adam','The counterfeiter of Florentine coin, swollen with dropsy, who dreams of the streams of the Casentino.','',''),
('guido-romena','Guido','One of the Counts of Romena, for whom Master Adam counterfeited, and whose soul he longs to see in the ditch.','',''),
('alessandro-romena','Alessandro','One of the Counts of Romena, named with his brother Guido.','Alessandro','reference'),
('potiphars-wife','The false woman who accused Joseph','Potiphar’s wife, burning with fever beside Sinon.','','reference','unnamed-person'),
('sinon','Sinon','The Greek who talked Troy into taking in the horse, burning with fever.','Sinon','supporting'),
('bocca','Bocca','Bocca degli Abati, the traitor of Montaperti, who refuses to give his name until Dante tears at his hair.','Bocca','supporting'),
('camicion','Camicion','Camicion de’ Pazzi, frozen in Caina, who names the traitors around him and awaits his kinsman Carlino.','Camicion','supporting'),
('carlino','Carlino','The kinsman whose worse treachery Camicion says will excuse his own.','Carlino','reference'),
('albert-alberti','Albert','The father of the two brothers of the Bisenzio valley, frozen face to face in Caina.','',''),
('mordred','The one Arthur pierced','The traitor whose breast and shadow were broken by one blow of his own father’s hand.','','reference','unnamed-person'),
('focaccia','Focaccia','A traitor of Pistoia named among the frozen.','Focaccia','reference'),
('sassol','Sassol Mascheroni','A Florentine traitor named among the frozen.','Sassol','reference'),
('gianni-soldanier','Gianni del Soldanieri','A Florentine traitor in the ice; Longfellow drops the final vowel.','Soldanieri|Soldanier','reference'),
('ganelon','Ganelon','The betrayer of Roland at Roncesvalles. Longfellow spells him Ganellon.','Ganelon|Ganellon','reference'),
('tebaldello','Tebaldello','The man who opened Faenza’s gates while the city slept.','Tebaldello','reference'),
('ugolino','Ugolino','Count Ugolino della Gherardesca, who gnaws the head of the archbishop who starved him and his children in the tower.','Ugolino','major'),
('ruggieri','Ruggieri','Archbishop Ruggieri of Pisa, who locked Ugolino and his sons in the tower and threw away the key.','Ruggieri','supporting'),
('anselmuccio','Anselm','One of Ugolino’s children in the tower, who asks his father why he stares.','Anselm|Anselmuccio','supporting'),
('gaddo','Gaddo','One of Ugolino’s children, who falls at his father’s feet in the tower.','Gaddo','supporting'),
('uguccione','Uguccione','One of Ugolino’s children in the tower.','Uguccione','reference'),
('brigata','Brigata','One of Ugolino’s children in the tower.','Brigata','reference'),
('alberigo','Alberigo','Friar Alberigo, who served the fruit at his own treacherous banquet, and whose soul is in Hell while his body still walks the world.','Alberigo','supporting'),
('branca-doria','Branca d’Oria','A Genoese whose soul has been in the ice for years while a devil wears his body.','Branca','supporting'),
('judas','Judas','The betrayer of Christ, head-first in Lucifer’s central mouth.','Judas','supporting'),
('cassius','Cassius','Caesar’s assassin, hanging from one of Lucifer’s black jaws.','Cassius','supporting'),
]:add(*row)

# ------------------------------------- scripture, myth and history referred to
for row in [
('christ','Christ','The Redeemer, named in Paradise and referred to in Hell only by circumlocution.','Christ','major','religious-figure'),
('mary','Mary','The mother of Christ, the gracious Lady who first moved to help Dante and who receives the last prayer of the poem.','Mary','major','religious-figure'),
('peter','Peter','Saint Peter, keeper of the keys of Heaven; his gate and his seat recur throughout.','Peter','supporting','religious-figure'),
('paul','Paul','The apostle whose journey to the third heaven Dante names beside Aeneas’s as precedent.','Paul','supporting','religious-figure'),
('john-baptist','The Baptist','John the Baptist, the patron Florence adopted in place of Mars.','Baptist','supporting','religious-figure'),
('lucia','Lucia','Saint Lucy, the enemy of all cruelty, who sends Beatrice to Dante’s aid and carries him while he sleeps.','Lucia','supporting','religious-figure'),
('rachel','Rachel','Jacob’s wife, seated beside Beatrice among the blessed and a figure of the contemplative life.','Rachel','supporting','religious-figure'),
('adam','Adam','The first father, drawn out of Limbo by the Harrowing.','','supporting','religious-figure'),
('eve','Eve','The first mother, who took the bitter fruit from the serpent.','Eve','supporting','religious-figure'),
('abel','Abel','Adam’s son, drawn out of Limbo by the Harrowing.','Abel','reference','religious-figure'),
('noah','Noah','Drawn out of Limbo by the Harrowing.','Noah','reference','religious-figure'),
('moses','Moses','The lawgiver, drawn out of Limbo by the Harrowing.','Moses','reference','religious-figure'),
('abraham','Abraham','The patriarch, drawn out of Limbo by the Harrowing.','Abraham','reference','religious-figure'),
('david','David','The psalmist king, drawn out of Limbo by the Harrowing.','David','reference','religious-figure'),
('israel','Israel','Jacob, drawn out of Limbo with his father and his children.','Israel','reference','religious-figure'),
('cain','Cain','The first murderer; the man in the moon carrying thorns is called by his name.','Cain','reference','religious-figure'),
('michael','Michael','The archangel who took vengeance on the proud rebellion.','',''),
('elijah','Elijah','The prophet taken up in the chariot of fire.','Elijah','reference','religious-figure'),
('elisha','Elisha','The prophet who watched Elijah’s chariot depart.','Elisha','reference','religious-figure'),
('joseph','Joseph','The patriarch falsely accused by Potiphar’s wife.','Joseph','reference','religious-figure'),
('judas-maccabee','placeholder','unused','',''),
('caesar','Caesar','Julius Caesar, seen armed in Limbo and named through the poem as the founder of the empire.','Caesar','supporting'),
('augustus','Augustus','The emperor under whom Virgil lived.','Augustus','reference'),
('scipio','Scipio','The Roman who became the heir of glory by routing Hannibal.','Scipio','reference'),
('hannibal','Hannibal','The Carthaginian routed by Scipio.','Hannibal','reference'),
('charlemagne','Charlemagne','The emperor whose rout at Roncesvalles cost him his holy campaign.','Charlemagne','reference'),
('roland','Roland','The paladin whose horn sounded at Roncesvalles.','Roland','reference'),
('robert-guiscard','Robert Guiscard','The Norman conqueror in Apulia, whose wars left bones still gathered on the field.','Robert|Guiscard','reference'),
('jove','Jove','The chief of the pagan gods, whose thunderbolt and whose blacksmith are invoked.','Jove|Jupiter','supporting','deity'),
('juno','Juno','The goddess whose rage against the Theban house drove Athamas mad.','Juno','reference','deity'),
('mars','Mars','The god of war, Florence’s first patron before the Baptist.','Mars','supporting','deity'),
('neptune','Neptune','The god of the sea.','Neptune','reference','deity'),
('apollo','Apollo','The god of poetry, invoked at the opening of the Paradiso.','Apollo','supporting','deity'),
('diana','Diana','The goddess of the moon and the hunt.','Diana','reference','deity'),
('minerva','Minerva','The goddess of wisdom.','Minerva','reference','deity'),
('bacchus','Bacchus','The god of wine; Thebes is called his city.','Bacchus','reference','deity'),
('latona','Latona','The mother of Apollo and Diana, who gave birth on Delos.','Latona','reference','deity'),
('muses','The Muses','The goddesses of poetry, invoked at the outset of each canticle.','Muses','supporting','group'),
('circe','Circe','The enchantress who kept Ulysses near Gaeta for more than a year.','Circe','reference','deity'),
('phaethon','Phaethon','The boy who dropped the reins of the sun’s chariot and scorched the sky.','Phaethon','reference','mythological-figure'),
('arachne','Arachne','The weaver turned spider, named for the pattern of Geryon’s hide.','Arachne','reference','mythological-figure'),
('narcissus','Narcissus','The boy who pined at his own reflection; his mirror is the water Master Adam thirsts for.','Narcissus','reference','mythological-figure'),
('theseus','Theseus','The Duke of Athens who killed the Minotaur, and whom the Furies wish they had punished.','Theseus','reference','mythological-figure'),
('hercules','Hercules','The hero whose club ended Cacus, and whose pillars mark the limit Ulysses passed.','Hercules','reference','mythological-figure'),
('deianira','Deianira','The woman Nessus died for.','Deianira','reference','mythological-figure'),
('semele','Semele','The Theban woman whose love of Jove brought Juno’s rage on her house.','Semele','reference','mythological-figure'),
('athamas','Athamas','The king driven mad by Juno, who killed his own son.','Athamas','reference','mythological-figure'),
('hecuba','Hecuba','Troy’s queen, who went mad with grief and howled like a dog.','Hecuba','reference','mythological-figure'),
('polydorus','Polydorus','Hecuba’s son, found dead on the seashore.','Polydorus','reference','mythological-figure'),
('polyxena','Polyxena','Hecuba’s daughter, whose death she saw.','Polyxena','reference','mythological-figure'),
('charybdis','Charybdis','The whirlpool whose waves crash and break, likened to the clash of the hoarders and spenders.','Charybdis','reference','mythical-being'),
('icarus','Icarus','The boy whose wings failed him, named when Dante rides down on Geryon.','Icarus','reference','mythological-figure'),
('daedalus','Daedalus','Icarus’s father, who called to him as the wax melted.','Daedalus','reference','mythological-figure'),
('atropos','Atropos','The Fate who cuts the thread.','Atropos','reference','deity'),
('epicurus','Epicurus','The philosopher whose followers held that the soul dies with the body, and whose cemetery is the sixth circle.','Epicurus','reference'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ----------------------------------------------------------------- the peoples
for row in [
('florentines','The Florentines','Dante’s own city and its people, the subject of more of the poem’s anger than any other.','Florentines|Florentine','supporting','group'),
('trojans','The Trojans','The people of Troy, from whose survivors Rome descends.','Trojans','reference','group'),
('greeks','The Greeks','The people who took Troy.','Greeks|Greek','reference','group'),
('romans','The Romans','The people of the empire Virgil sang and Dante defends.','Romans|Roman','supporting','group'),
('jews','The Jews','Named in the ditch of the hypocrites and in the sowing of evil seed.','Jews','reference','group'),
('christians','The Christians','Named in the poem’s reproaches to the living.','Christians|Christian','supporting','group'),
('pharisees','The Pharisees','The council that took counsel against Christ.','Pharisees','reference','group'),
('saracens','The Saracens','Named among the enemies the papacy did not make war on.','Saracens','reference','group'),
('cherubim','The Cherubim','An order of angels; one of the black Cherubim claims Guido da Montefeltro.','Cherubim','reference','group'),
('seraphim','The Seraphim','The highest order of angels.','Seraphim','reference','group'),
('thebans','The Thebans','The people who saw the earth open for Amphiaraus.','Thebans','reference','group'),
('sienese','The Sienese','A people the poem calls the vainest in the world.','Sienese','reference','group'),
('bolognese','The Bolognese','Named in the ditch of the panders.','Bolognese','reference','group'),
('genoese','The Genoese','A people at odds with every virtue, in the poem’s judgment.','Genoese','reference','group'),
('lombards','The Lombards','The people of Virgil’s parents.','Lombard|Lombards','reference','group'),
('mantuans','The Mantuans','The people of Virgil’s city.','Mantuan|Mantuans','reference','group'),
('tuscans','The Tuscans','The people of Dante’s region.','Tuscan|Tuscans','supporting','group'),
('aretines','The Aretines','The people of Arezzo.','Aretine|Aretines','reference','group'),
('paduans','The Paduans','The people of Padua.','Paduan|Paduans','reference','group'),
('french','The French','Named beside the Sienese for vanity.','French','reference','group'),
]:add(*row)

Path(__file__).parent.joinpath('editorial.json').write_text(json.dumps(dict(
 contentVersion='2026-09-11.1',
 coverage='Both full English editions. INFERNO (chapters 1-34) is authored; Purgatorio (35-67) and Paradiso (68-100) are in progress. Named people, gods, angels, devils, personified powers, named monsters and named peoples. Places, rivers, mountains and book titles are not cast, except where a river of the underworld is treated as a power.',
 entities=entities),ensure_ascii=False,indent=2)+'\n')
print(len(entities),'entities')
