"""Manually authored recognition cards for both full English texts of the Odyssey.

Butler's original renders the gods and the hero with their Roman names
(Ulysses, Jove, Minerva, Neptune); the modern edition restores the Greek
(Odysseus, Zeus, Athena, Poseidon). Every affected entity carries both forms as
aliases, so one card serves both editions.

Scope: named people, gods, personified powers, named animals and named peoples.
Places, rivers, mountains, islands, ships, stars and the adjectival forms of
place names are not cast and are not bound.
"""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person',snapshots=None,roleAfter=None):
 e=dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=snapshots or [])
 if roleAfter:e['roleAfter']=roleAfter
 entities.append(e)

# ---------------------------------------------------------------- the household
for row in [
('odysseus','Odysseus','King of Ithaca, husband of Penelope and father of Telemachus. He sacked Troy and has been twenty years getting home. Butler’s original calls him by his Roman name, Ulysses.','Ulysses|Odysseus','central'),
('telemachus','Telemachus','Odysseus’s son, a young man who has grown up without ever meeting his father.','Telemachus','central'),
('penelope','Penelope','Odysseus’s wife, holding his household together against the suitors who want her to remarry.','Penelope','major'),
('laertes','Laertes','Odysseus’s father, the old king of Ithaca, who has withdrawn to his farm in the country.','Laertes','major'),
('anticlea','Anticlea','Odysseus’s mother, daughter of Autolycus.','Anticlea|Anticleia','supporting'),
('eurycleia','Euryclea','The old nurse of Odysseus’s house, bought by Laertes; she nursed Odysseus and then Telemachus. The modern edition spells her name both Euryclea and Eurycleia.','Euryclea|Eurycleia','major'),
('eumaeus','Eumaeus','Odysseus’s swineherd, who keeps the pig farm in the hills and is loyal to the absent master.','Eumaeus','major'),
('philoetius','Philoetius','Odysseus’s stockman, in charge of the cattle on the mainland.','Philoetius','major'),
('melanthius','Melanthius','Odysseus’s goatherd, son of Dolius, who has taken the suitors’ side.','Melanthius','major'),
('eurynome','Eurynome','Penelope’s head waiting woman and housekeeper.','Eurynome','supporting'),
('dolius','Dolius','The old gardener given to Penelope by her father when she married; father of Melanthius and Melantho.','Dolius','supporting'),
('melantho','Melantho','A maid of the house, daughter of Dolius, brought up by Penelope; she sides with the suitors.','Melantho','supporting'),
('medon','Medon','A servant and herald of Odysseus’s house who waits on the suitors at table.','Medon','supporting'),
('phemius','Phemius','The bard of Ithaca, son of Terpes, forced to sing for the suitors.','Phemius','supporting'),
('actor-daughter','The maid who keeps the bedroom door','Penelope’s maidservant, daughter of Actor, the only servant who knows the secret of the marriage bed.','','supporting','unnamed-person'),
('argos','Argos','Odysseus’s hunting dog, bred by him before he left for Troy and now old and neglected.','','supporting','animal'),
('ctimene','Ctimene','Odysseus’s younger sister, brought up alongside Eumaeus and married away to Same.','Ctimene','supporting'),
]:add(*row)

# ------------------------------------------------------------------ the suitors
for row in [
('antinous','Antinous','Son of Eupeithes and the most aggressive of the suitors courting Penelope.','Antinous','major'),
('eurymachus','Eurymachus','Son of Polybus and, with Antinous, a leader among the suitors.','Eurymachus','major'),
('amphinomus','Amphinomus','A suitor from Dulichium, son of Nisus; the most decent-spoken of them, and Penelope’s favourite among them.','Amphinomus','major'),
('agelaus','Agelaus','A suitor, son of Damastor.','Agelaus'),
('ctesippus','Ctesippus','A suitor from Same, a coarse-mannered rich man’s son.','Ctesippus'),
('leiodes','Leiodes','A suitor, son of Oenops, who acts as sacrificial priest to the others.','Leiodes'),
('eurynomus-suitor','Eurynomus','A suitor, one of the three surviving sons of the old Ithacan Aegyptius.','Eurynomus'),
('amphimedon','Amphimedon','A suitor of Ithaca, son of Melaneus, who once hosted Agamemnon.','Amphimedon'),
('demoptolemus','Demoptolemus','A suitor who fights in the front rank at the end.','Demoptolemus'),
('pisander','Pisander','A suitor, son of Polyctor.','Pisander'),
('polybus-suitor','Polybus','A suitor, son of Polyctor.',''),
('polybus-eurymachus','Polybus','Father of the suitor Eurymachus.','','reference'),
('eurydamas','Eurydamas','A suitor.','Eurydamas'),
('leocritus','Leocritus','A suitor, son of Evenor, who breaks up the Ithacan assembly. Butler’s original spells him Leiocritus at his first appearance.','Leiocritus|Leocritus'),
('euryades','Euryades','A suitor killed in the hall.','Euryades'),
('elatus','Elatus','A suitor killed in the hall.','Elatus'),
('mulius','Mulius','A servant from Dulichium who waits on Amphinomus.','Mulius'),
('autonoe','Autonoe','One of Penelope’s waiting women.','Autonoe'),
('hippodamia','Hippodamia','One of Penelope’s waiting women.','Hippodamia'),
]:add(*row)

# --------------------------------------------------------------- Ithaca at home
for row in [
('irus','Irus','The town beggar of Ithaca, a big idle man whose real name is Arnaeus; the young men call him Irus because he runs their errands.','Irus|Arnaeus'),
('mentor','Mentor','An old friend of Odysseus, left in charge of the household when he sailed for Troy. Athena repeatedly takes his shape and voice.','Mentor','supporting'),
('mentes','Mentes','Chief of the Taphians and an old guest-friend of Odysseus’s house, son of Anchialus; Athena comes to Ithaca in his shape.','Mentes','supporting'),
('halitherses','Halitherses','The best reader of omens in Ithaca, son of Mastor, and an old friend of Odysseus’s house.','Halitherses'),
('aegyptius','Aegyptius','A very old Ithacan who speaks first at the assembly; father of Antiphus, Eurynomus and two sons who work his land.','Aegyptius'),
('antiphus','Antiphus','Son of the old Ithacan Aegyptius; he sailed with Odysseus and was killed by the Cyclops.','',''),
('antiphus-elder','Antiphus','An elder of Ithaca, one of the old friends of Odysseus’s house with whom Telemachus sits in the assembly.','',''),
('eupeithes','Eupeithes','Father of Antinous; Odysseus once saved him from an Ithacan mob.','Eupeithes'),
('noemon','Noemon','An Ithacan, son of Phronius, who lends Telemachus a ship.','Noemon'),
('phronius','Phronius','Father of Noemon.','Phronius','reference'),
('piraeus','Piraeus','Telemachus’s friend, son of Clytius, who keeps his guest and his gifts while the house is unsafe.','Piraeus'),
('clytius','Clytius','Father of Piraeus.','Clytius','reference'),
('theoclymenus','Theoclymenus','A seer of the house of Melampus, in exile from Argos for killing a man; Telemachus brings him home to Ithaca.','Theoclymenus','major'),
('pisenor-herald','Pisenor','The herald of the Ithacan assembly, who brings Telemachus his staff.','',''),
('evenor','Evenor','Father of the suitor Leocritus.','Evenor','reference'),
('damastor','Damastor','Father of the suitor Agelaus.','Damastor','reference'),
('polyctor','Polyctor','Father of the suitors Pisander and Polybus.','',''),
('oenops','Oenops','Father of the suitor Leiodes.','Oenops','reference'),
('melaneus','Melaneus','An Ithacan, father of the suitor Amphimedon.','Melaneus','reference'),
('nisus','Nisus','A rich and brave man of Dulichium, son of Aretias and father of Amphinomus.','Nisus','reference'),
('aretias','Aretias','A king, father of Nisus and grandfather of Amphinomus.','Aretias','reference'),
('polytherses','Polytherses','Father of the suitor Ctesippus.','Polytherses','reference'),
('mastor','Mastor','Father of the seer Halitherses.','Mastor','reference'),
('terpes','Terpes','Father of the bard Phemius.','Terpes','reference'),
('ops','Ops','Father of the nurse Euryclea, son of Pisenor.','Ops','reference'),
('pisenor','Pisenor','Father of Ops and grandfather of the nurse Euryclea.','',''),
('icarius','Icarius','Penelope’s father.','Icarius','supporting'),
('iphthime','Iphthime','Penelope’s sister, daughter of Icarius, married to Eumelus of Pherae; Athena sends a phantom in her likeness.','Iphthime','reference'),
('eumelus','Eumelus','Iphthime’s husband, who lives at Pherae.','Eumelus','reference'),
('arceisius','Arceisius','Odysseus’s grandfather, father of Laertes.','Arceisius|Arcesius','reference'),
('autolycus','Autolycus','Odysseus’s maternal grandfather, famous as the most accomplished thief and perjurer alive; he named the boy and gave him the boar-hunt scar.','Autolycus','supporting'),
('amphithea','Amphithea','Odysseus’s grandmother, wife of Autolycus.','Amphithea','reference'),
('icmalius','Icmalius','The craftsman who made Penelope’s inlaid chair.','Icmalius','reference'),
('mesaulius','Mesaulius','A servant Eumaeus bought for himself, who waits at his table.','Mesaulius'),
('ithacus','Ithacus','One of the three men said to have built the town fountain of Ithaca.','Ithacus','reference'),
('neritus','Neritus','One of the three men said to have built the town fountain of Ithaca.','Neritus','reference'),
('sicel-woman','The Sicel woman','The old servant who looks after Laertes on his country farm. The modern edition calls her Sicilian.','','supporting','unnamed-person'),
]:add(*row)

# ------------------------------------------------------------------------- gods
for row in [
('athena','Athena','Daughter of Zeus, goddess of war and cunning, and Odysseus’s protector throughout. Butler’s original calls her Minerva.','Minerva|Athena','major','deity'),
('zeus','Zeus','King of the gods and father of Athena. Butler’s original calls him Jove.','Jove|Zeus','major','deity'),
('poseidon','Poseidon','God of the sea and the earthquake, and the one god set against Odysseus, because Odysseus blinded his son Polyphemus. Butler’s original calls him Neptune.','Neptune|Poseidon','major','deity'),
('hermes','Hermes','The messenger god, guide of travellers and of the dead. Butler’s original calls him Mercury.','Mercury|Hermes','supporting','deity'),
('apollo','Apollo','God of archery, prophecy and sudden death.','Apollo','supporting','deity'),
('artemis','Artemis','Goddess of the hunt and Apollo’s sister. Butler’s original calls her Diana.','Diana|Artemis','supporting','deity'),
('aphrodite','Aphrodite','Goddess of love and beauty. Butler’s original calls her Venus.','Venus|Aphrodite','supporting','deity'),
('ares','Ares','God of war. Butler’s original calls him Mars.','Mars|Ares','supporting','deity'),
('hephaestus','Hephaestus','The smith of the gods, lame and famously skilful, husband of Aphrodite. Butler’s original calls him Vulcan.','Vulcan|Hephaestus','supporting','deity'),
('hera','Hera','Zeus’s wife, queen of the gods. Butler’s original calls her Juno.','Juno|Hera','reference','deity'),
('demeter','Demeter','Goddess of the harvest. Butler’s original calls her Ceres.','Ceres|Demeter','reference','deity'),
('persephone','Persephone','Queen of the dead, who rules in Hades. Butler’s original calls her Proserpine.','Proserpine|Persephone','supporting','deity'),
('hades','Hades','God of the underworld; the name also stands for his house, where the dead go.','Hades','supporting','deity'),
('helios','Helios','The sun god, whose cattle graze on Thrinacia. Butler’s original calls him Hyperion.','Hyperion|Helios','supporting','deity'),
('cronus','Cronus','Zeus’s father. Butler’s original calls him Saturn.','Saturn|Cronus|Cronos','reference','deity'),
('leto','Leto','Mother of Apollo and Artemis by Zeus.','Leto','reference','deity'),
('dawn','Dawn','The goddess of daybreak, who rises each morning from beside Tithonus. Butler’s original also names her Aurora.','Dawn|Aurora','supporting','deity'),
('oceanus','Oceanus','The great river encircling the earth, spoken of as a god and as the father of nymphs.','Oceanus','reference','deity'),
('amphitrite','Amphitrite','Sea goddess; the waves are called hers.','Amphitrite','reference','deity'),
('proteus','Proteus','The old man of the sea, a shape-shifting immortal who tells the truth only under compulsion.','Proteus','supporting','deity'),
('eidothea','Idothea','Daughter of Proteus, who takes pity on Menelaus in Egypt and teaches him how to trap her father.','Idothea|Eidothea','supporting','deity'),
('leucothea','Ino','A mortal woman, daughter of Cadmus, since raised to godhood as Leucothea; she gives Odysseus her veil in the storm.','Ino|Leucothea','supporting','deity'),
('calypso','Calypso','The goddess on Ogygia who kept Odysseus seven years and wanted to marry him.','Calypso','major','deity'),
('circe','Circe','The goddess and enchantress of Aeaea, daughter of the sun and sister of Aeetes.','Circe','major','deity'),
('themis','Themis','Goddess invoked as the beginning and end of councils.','Themis','reference','deity'),
('hebe','Hebe','Daughter of Zeus and Hera, married to Heracles among the gods.','Hebe','reference','deity'),
('eileithyia','Ilithuia','Goddess of childbirth, who has a cave at Amnisus in Crete.','Ilithuia|Eileithyia','reference','deity'),
('paeon','Paeeon','The healer of the gods; the Egyptian physicians are called his race.','Paeeon|Paeon','reference','deity'),
('dionysus','Bacchus','God of wine, who gave the golden urn that holds Achilles’ bones and who denounced Ariadne.','Bacchus|Dionysus','reference','deity'),
('atlas','Atlas','Calypso’s father, who knows the depths of the sea and holds the pillars of heaven apart.','Atlas','reference','deity'),
('thoosa','Thoosa','A sea nymph, daughter of Phorcys and mother of Polyphemus by Poseidon.','Thoosa','reference','deity'),
('phorcys','Phorcys','A sea god, father of Thoosa; a harbour of Ithaca bears his name.','Phorcys','reference','deity'),
('crataiis','Crataiis','Scylla’s mother, whom Odysseus is told to call on as he passes.','Crataiis','reference','deity'),
('halosydne','Halosydne','A sea goddess; the seals are called her flock.','Halosydne','reference','deity'),
('perse','Perse','Daughter of Oceanus and mother, by the sun, of Circe and Aeetes.','Perse','reference','deity'),
('neaera','Neaera','A nymph, mother by Helios of Phaethusa and Lampetie.','Neaera','reference','deity'),
('phaethusa','Phaethusa','A goddess, daughter of Helios, who herds the sun’s cattle on Thrinacia with her sister.','Phaethusa','reference','deity'),
('lampetie','Lampetie','A goddess, daughter of Helios, who herds the sun’s cattle on Thrinacia and reports their slaughter to her father.','Lampetie|Lampetia','reference','deity'),
('maia','Maia','Hermes’s mother.','Maia','reference','deity'),
('thetis','Thetis','A sea goddess, Achilles’ mother, who offered his armour as a prize.','Thetis','reference','deity'),
('erinyes','The Furies','The avenging spirits called down by a wronged parent. Butler’s original names them the Erinyes.','Erinyes|Erinys|Furies','reference','group'),
('graces','The Graces','The goddesses who bathe and anoint Aphrodite.','Graces','reference','group'),
('naiads','The Naiads','The water nymphs of the cave above the harbour of Phorcys in Ithaca.','Naiads|Naiad','reference','group'),
('gaia','Gaia','The earth, named as the mother of Tityus.','Gaia','reference','deity'),
]:add(*row)

# ----------------------------------------------------------- Pylos and Sparta
for row in [
('nestor','Nestor','The old king of Pylos, knight of Gerene, who came home safely from Troy and still gives the best counsel of any Greek.','Nestor','major'),
('pisistratus','Pisistratus','Nestor’s youngest son, who travels with Telemachus to Sparta.','Pisistratus','major'),
('thrasymedes','Thrasymedes','A son of Nestor.','Thrasymedes'),
('perseus-nestorid','Perseus','A son of Nestor.','',''),
('echephron','Echephron','A son of Nestor.','Echephron'),
('stratius','Stratius','A son of Nestor.','Stratius'),
('aretus','Aretus','A son of Nestor.','Aretus'),
('eurydice','Eurydice','Nestor’s wife, eldest daughter of Clymenus.','Eurydice','reference'),
('clymenus','Clymenus','Father of Nestor’s wife Eurydice.','Clymenus','reference'),
('polycaste','Polycaste','Nestor’s youngest daughter, who bathes Telemachus at Pylos.','Polycaste'),
('neleus','Neleus','Nestor’s father, the old king of Pylos, son of Poseidon and Tyro.','Neleus','reference'),
('laerces','Laerceus','The goldsmith at Pylos who gilds the heifer’s horns for Nestor’s sacrifice.','Laerceus|Laerces'),
('menelaus','Menelaus','King of Sparta, Agamemnon’s brother and Helen’s husband; he came home last of all the Greeks.','Menelaus','major'),
('helen','Helen','Menelaus’s wife, daughter of Zeus, whose going to Troy began the war.','Helen','major'),
('megapenthes','Megapenthes','Menelaus’s son by a slave woman, married on the day Telemachus arrives.','Megapenthes'),
('hermione','Hermione','Menelaus and Helen’s only daughter, promised in marriage to Achilles’ son.','Hermione','reference'),
('eteoneus','Eteoneus','Menelaus’s servant, son of Boethous, who keeps his door.','Eteoneus'),
('boethous','Boethous','Father of Menelaus’s servant Eteoneus.','Boethous','reference'),
('asphalion','Asphalion','A servant of Menelaus who pours water over the guests’ hands.','Asphalion'),
('adraste','Adraste','One of Helen’s maids at Sparta.','Adraste'),
('alcippe','Alcippe','One of Helen’s maids at Sparta.','Alcippe'),
('phylo','Phylo','One of Helen’s maids at Sparta, who fetches her work-box.','Phylo'),
('alcandra','Alcandra','An Egyptian woman of Thebes, wife of Polybus, who gave Helen the silver work-box.','Alcandra','reference'),
('polybus-egypt','Polybus','A rich man of Egyptian Thebes who gave Menelaus two silver baths.','',''),
('polybus-phaeacian','Polybus','The Phaeacian craftsman who made the red ball Laodamas and Halios dance with.','',''),
('polydamna','Polydamna','An Egyptian woman, wife of Thon, who gave Helen the drug that quiets all pain.','Polydamna','reference'),
('thon','Thon','An Egyptian, husband of Polydamna.','Thon','reference'),
('phaedimus','Phaedimus','King of the Sidonians, who gave Menelaus the silver mixing bowl.','Phaedimus','reference'),
('diocles','Diocles','The host at Pherae on the road between Pylos and Sparta, son of Ortilochus.','Diocles'),
('ortilochus','Ortilochus','Father of Diocles and grandson of the river Alpheus; his house at Messene is where Odysseus met Iphitus.','Ortilochus','reference'),
('alector','Alector','A Spartan, father of the bride Megapenthes marries.','Alector','reference'),
('phrontis','Phrontis','The steersman of Menelaus’s ship, the best helmsman alive, killed by Apollo off Sunium.','Phrontis','reference'),
]:add(*row)

# ------------------------------------------------------------------ Phaeacians
for row in [
('alcinous','Alcinous','King of the Phaeacians on Scheria, son of Nausithous and husband of Arete.','Alcinous','major'),
('arete','Arete','Queen of the Phaeacians, Alcinous’s wife and niece, honoured by her people beyond any other woman.','Arete','major'),
('nausicaa','Nausicaa','Alcinous and Arete’s daughter, who finds Odysseus on the shore.','Nausicaa','major'),
('demodocus','Demodocus','The blind bard of the Phaeacian court, whom the Muse loves.','Demodocus','supporting'),
('laodamas','Laodamas','Alcinous’s son and his favourite, the best looking of the young Phaeacians.','Laodamas'),
('halios','Halios','A son of Alcinous, who dances with Laodamas. Both editions spell his name Halios once and Halius once.','Halios|Halius'),
('clytoneus','Clytoneus','A son of Alcinous who competes in the games.','Clytoneus'),
('euryalus','Euryalus','A young Phaeacian, son of Naubolus, who taunts Odysseus into the discus throw and then makes amends.','Euryalus'),
('echeneus','Echeneus','The oldest of the Phaeacian elders and their best speaker.','Echeneus'),
('pontonous','Pontonous','Alcinous’s herald, who mixes and serves the wine.','Pontonous'),
('nausithous','Nausithous','The Phaeacians’ former king, son of Poseidon, who moved them from Hypereia to Scheria; father of Alcinous.','Nausithous','reference'),
('rhexenor','Rhexenor','Nausithous’s elder son, killed young by Apollo; Arete’s father.','Rhexenor','reference'),
('periboea','Periboea','Nausithous’s mother, youngest daughter of Eurymedon king of the giants.','Periboea','reference'),
('eurymedon','Eurymedon','A king of the giants, whose people and himself were destroyed; Periboea’s father.','Eurymedon','reference'),
('eurymedusa','Eurymedusa','The old servant from Apeira, given to Alcinous as a prize, who nursed Nausicaa. The modern edition calls her Eurynome — the name it also gives Penelope’s housekeeper.','Eurymedusa'),
('dymas-daughter','The sea captain’s daughter','Nausicaa’s close friend, daughter of the famous sea captain Dymas; Athena takes her shape.','','supporting','unnamed-person'),
('dymas','Dymas','A famous Phaeacian sea captain.','Dymas','reference'),
('naubolus','Naubolus','Father of the Phaeacian Euryalus.','Naubolus','reference'),
('polyneus','Polyneus','A Phaeacian, father of Amphialus and son of Tecton.','Polyneus','reference'),
('tecton','Tecton','A Phaeacian, grandfather of Amphialus.','Tecton','reference'),
]:add(*row)
for n in ['Acroneos|Acroneus','Ocyalus','Elatreus','Nauteus','Prymneus','Anchialus-ph','Eretmeus','Ponteus','Proreus','Thoon','Anabesineus','Amphialus']:
 alias=n.split('|')[0].replace('-ph','')
 # Anchialus is also the name of Mentes's father; this one is bound by position.
 add(alias.lower()+('-phaeacian' if alias=='Anchialus' else ''),alias,'A young Phaeacian who competes in the games held for Odysseus.','' if alias=='Anchialus' else n)

# --------------------------------------------------------------- the wanderings
for row in [
('polyphemus','Polyphemus','The Cyclops whose cave Odysseus enters, son of Poseidon and the nymph Thoosa.','Polyphemus','major'),
('telemus','Telemus','A seer among the Cyclopes, son of Eurymus, who once prophesied to Polyphemus.','Telemus','reference'),
('eurymus','Eurymus','Father of the Cyclops seer Telemus.','Eurymus','reference'),
('noman','Noman','The name Odysseus gives the Cyclops when asked. The modern edition renders it Nobody.','','supporting','assumed-name'),
('aeolus','Aeolus','Son of Hippotas and keeper of the winds on his floating island; he gives Odysseus the bag of storms.','Aeolus','supporting'),
('hippotas','Hippotas','Father of Aeolus the wind king.','Hippotas','reference'),
('antiphates','Antiphates','King of the Laestrygonians, who begins the destruction of Odysseus’s fleet.','',''),
('eurylochus','Eurylochus','Odysseus’s second in command and kinsman by marriage; he argues against his captain twice.','Eurylochus','major'),
('polites','Polites','The companion Odysseus valued most of all, who speaks first at Circe’s door.','Polites'),
('perimedes','Perimedes','One of Odysseus’s crew, who helps at the trench of the dead and at the Sirens.','Perimedes'),
('elpenor','Elpenor','The youngest of Odysseus’s crew, neither brave nor clever, who falls from Circe’s roof and is the first ghost to meet him.','Elpenor','supporting'),
('teiresias','Teiresias','The blind Theban prophet, the one dead man whose understanding Persephone left whole; Odysseus goes to Hades to consult him. The modern edition also spells the name Tiresias.','Teiresias|Tiresias','major'),
('scylla','Scylla','The six-headed monster in the cliff above the strait, daughter of Crataiis.','Scylla','supporting','mythical-being'),
('charybdis','Charybdis','The whirlpool under the fig tree opposite Scylla, which sucks the water down three times a day.','Charybdis','supporting','mythical-being'),
('sirens','The Sirens','The singers on their meadow who enchant every man who hears them.','Sirens','supporting','group'),
('muse','The Muse','The goddess of song, invoked in the first line and named as the source of Demodocus’s gift.','Muse','supporting','deity'),
('maron','Maron','Priest of Apollo at Ismarus, son of Euanthes, who gave Odysseus the strong wine out of gratitude.','Maron','reference'),
('euanthes','Euanthes','Father of Maron, priest of Apollo at Ismarus.','Euanthes','reference'),
('aeetes','Aeetes','A magician, Circe’s brother, and child like her of the sun and Perse.','Aetes|Aeetes','reference'),
('jason','Jason','The hero for whose sake Hera steered the Argo safely past the wandering rocks.','Jason','reference'),
('lamus','Lamus','The founder whose rocky stronghold is the Laestrygonian city.','Lamus','reference'),
]:add(*row)

# ------------------------------------------------------------ the Trojan story
for row in [
('agamemnon','Agamemnon','King of Mycenae and leader of the Greeks at Troy, Menelaus’s brother; he came home to an ambush.','Agamemnon','major'),
('clytemnestra','Clytemnestra','Agamemnon’s wife, daughter of Tyndareus, who took Aegisthus while her husband was at Troy.','Clytemnestra','supporting'),
('aegisthus','Aegisthus','The man who seduced Clytemnestra and killed Agamemnon, and was killed in turn by Orestes.','Aegisthus','supporting'),
('orestes','Orestes','Agamemnon’s son, who avenged his father; the example held up to Telemachus.','Orestes','supporting'),
('achilles','Achilles','Son of Peleus and the greatest of the Greek fighters at Troy.','Achilles','supporting'),
('peleus','Peleus','Achilles’ father, still ruling among the Myrmidons.','Peleus','reference'),
('aeacus','Aeacus','Peleus’s father; Achilles is called his descendant.','Aeacus','reference'),
('patroclus','Patroclus','Achilles’ closest companion, killed at Troy.','Patroclus','reference'),
('antilochus','Antilochus','Nestor’s son, singularly fast on his feet, killed at Troy.','Antilochus','supporting'),
('ajax','Ajax','Son of Telamon and the finest of the Greeks after Achilles; he lost the contest for Achilles’ armour and will not speak to Odysseus even in death.','','supporting'),
('ajax-oileus','Ajax','The Greek leader wrecked on the rocks of Gyrae on the voyage home.','',''),
('telamon','Telamon','Father of the greater Ajax.','Telamon','reference'),
('neoptolemus','Neoptolemus','Achilles’ son, whom Odysseus fetched from Scyros; he came home from Troy unharmed.','Neoptolemus','reference'),
('idomeneus','Idomeneus','King of Crete, who lost no men at sea coming home from Troy.','Idomeneus','reference'),
('philoctetes','Philoctetes','Son of Poias, an archer who came home safely from Troy.','Philoctetes','reference'),
('poias','Poias','Father of Philoctetes.','Poias','reference'),
('diomedes','Diomedes','Son of Tydeus, who stationed his ships at Argos on the way home. Butler’s original spells him Diomed.','Diomed|Diomedes','reference'),
('tydeus','Tydeus','Father of Diomedes.','Tydeus','reference'),
('priam','Priam','King of Troy.','Priam','reference'),
('cassandra','Cassandra','Priam’s daughter, killed beside Agamemnon by Clytemnestra.','Cassandra','reference'),
('deiphobus','Deiphobus','A Trojan who was with Helen when she called to the men inside the wooden horse.','Deiphobus','reference'),
('anticlus','Anticlus','A Greek inside the wooden horse who began to answer Helen’s voice until Odysseus stopped his mouth.','Anticlus','reference'),
('epeus','Epeus','The man who built the wooden horse with Athena’s help.','Epeus','reference'),
('eurypylus','Eurypylus','Son of Telephus and the handsomest man Odysseus ever saw except Memnon; killed by Neoptolemus at Troy.','Eurypylus','reference'),
('telephus','Telephus','Father of Eurypylus.','Telephus','reference'),
('memnon','Memnon','A hero named as the handsomest man at Troy.','Memnon','reference'),
('eurybates','Eurybates','Odysseus’s herald at Troy, round-shouldered, dark and curly-haired; his master valued him above the rest.','Eurybates','reference'),
('atreus','Atreus','Father of Agamemnon and Menelaus.','Atreus','reference'),
('thyestes','Thyestes','Atreus’s brother, who used to live on the headland where Aegisthus later settled.','Thyestes','reference'),
('philomeleides','Philomeleides','The wrestler of Lesbos whom Odysseus threw before the war.','Philomeleides','reference'),
('ilus','Ilus','Son of Mermerus, of Ephyra, who feared the gods and would not sell Odysseus arrow poison.','Ilus','reference'),
('mermerus','Mermerus','Father of Ilus of Ephyra.','Mermerus','reference'),
]:add(*row)

# ------------------------------------------------------ the women and the dead
for row in [
('tyro','Tyro','Daughter of Salmoneus and wife of Cretheus, who bore Pelias and Neleus to Poseidon in the likeness of the river Enipeus.','Tyro','reference'),
('salmoneus','Salmoneus','Tyro’s father.','Salmoneus','reference'),
('cretheus','Cretheus','Son of Aeolus and husband of Tyro.','Cretheus','reference'),
('enipeus','Enipeus','A river spoken of as a person, the most beautiful in the world, whose form Poseidon took to deceive Tyro.','Enipeus','reference','personification'),
('pelias','Pelias','Tyro’s son by Poseidon, a great breeder of sheep at Iolcus.','Pelias','reference'),
('aeson','Aeson','A son of Tyro and Cretheus.','Aeson','reference'),
('pheres','Pheres','A son of Tyro and Cretheus.','Pheres','reference'),
('amythaon','Amythaon','A son of Tyro and Cretheus, a mighty warrior and charioteer.','Amythaon','reference'),
('antiope','Antiope','Daughter of Asopus, mother by Zeus of Amphion and Zethus.','Antiope','reference'),
('asopus','Asopus','Antiope’s father.','Asopus','reference'),
('amphion','Amphion','Son of Zeus and Antiope, who with his brother Zethus founded Thebes and walled it.','',''),
('zethus','Zethus','Son of Zeus and Antiope, who founded Thebes with Amphion; father of the boy Itylus.','Zethus','reference'),
('itylus','Itylus','Zethus’s son, killed by mishap by his own mother, who became the nightingale.','Itylus','reference'),
('pandareus','Pandareus','Father of the nightingale of the spring song, and of the daughters the storm winds carried off.','Pandareus','reference'),
('alcmena','Alcmena','Wife of Amphitryon and mother of Heracles by Zeus.','Alcmena|Alcmene','reference'),
('amphitryon','Amphitryon','Alcmena’s husband.','Amphitryon','reference'),
('megara','Megara','Daughter of King Creon, married to Heracles.','Megara','reference'),
('creon','Creon','A great king, father of Megara.','Creon','reference'),
('epicaste','Epicaste','Mother of Oedipus, who married her own son without knowing it.','Epicaste','reference'),
('oedipus','Oedipodes','King of Thebes, who killed his father and married his own mother unknowing. The modern edition calls him Oedipus.','Oedipodes|Oedipus','reference'),
('chloris','Chloris','Neleus’s wife and queen in Pylos, youngest daughter of Amphion of Orchomenus; mother of Nestor.','Chloris','reference'),
('amphion-orchomenus','Amphion','King of Minyan Orchomenus, son of Iasus and father of Chloris.','',''),
('iasus-orchomenus','Iasus','Father of Amphion king of Orchomenus.','',''),
('chromius','Chromius','A son of Neleus and Chloris, Nestor’s brother.','Chromius','reference'),
('periclymenus','Periclymenus','A son of Neleus and Chloris, Nestor’s brother.','Periclymenus','reference'),
('pero','Pero','Neleus’s daughter, wooed by the whole country and won only through the cattle of Iphicles.','Pero','reference'),
('iphicles','Iphicles','The owner of the cattle of Phylace that had to be raided to win Pero.','Iphicles','reference'),
('leda','Leda','Tyndareus’s wife, mother of Castor and Pollux.','Leda','reference'),
('tyndareus','Tyndarus','Leda’s husband and the father of Castor and Pollux. The modern edition spells him Tyndareus.','Tyndarus|Tyndareus','reference'),
('castor','Castor','Son of Leda and Tyndareus, a breaker of horses; he and Pollux live and die on alternate days.','',''),
('pollux','Pollux','Son of Leda and Tyndareus, a mighty boxer.','Pollux','reference'),
('iphimedeia','Iphimedeia','Wife of Aloeus, who bore Otus and Ephialtes to Poseidon.','Iphimedeia','reference'),
('aloeus','Aloeus','Iphimedeia’s husband.','Aloeus','reference'),
('otus','Otus','A giant son of Iphimedeia, who with his brother threatened to pile the mountains and storm heaven.','Otus','reference'),
('ephialtes','Ephialtes','A giant son of Iphimedeia, who with his brother threatened to pile the mountains and storm heaven.','Ephialtes','reference'),
('phaedra','Phaedra','One of the famous women whose ghost Odysseus sees.','Phaedra','reference'),
('procris','Procris','One of the famous women whose ghost Odysseus sees.','Procris','reference'),
('ariadne','Ariadne','Daughter of Minos, carried off from Crete by Theseus and killed by Artemis on Dia.','Ariadne','reference'),
('minos','Minos','King of Crete at Knossos, who conferred with Zeus every ninth year and now sits in judgement on the dead.','Minos','reference'),
('theseus','Theseus','A hero of Athens, one of the great dead Odysseus wished to see.','Theseus','reference'),
('peirithous','Peirithous','Theseus’s companion, host to the Centaur Eurytion among the Lapiths.','Peirithous|Pirithous','reference'),
('eurytion','Eurytion','The Centaur whom wine inflamed at Peirithous’s house.','Eurytion','reference','mythological-figure'),
('maera','Maera','One of the women’s ghosts Odysseus names.','Maera','reference'),
('clymene','Clymene','One of the women’s ghosts Odysseus names.','Clymene','reference'),
('eriphyle','Eriphyle','A ghost Odysseus names, the woman who sold her own husband for gold.','Eriphyle','reference'),
('tityus','Tityus','A giant son of Gaia, punished in Hades for assaulting Leto.','Tityus','reference'),
('tantalus','Tantalus','A shade punished in Hades with water and fruit that withdraw whenever he reaches.','Tantalus','reference'),
('sisyphus','Sisyphus','A shade punished in Hades by rolling a stone that always runs back down.','Sisyphus','reference'),
('heracles','Heracles','The greatest of the strong men, whose phantom Odysseus meets in Hades while he himself feasts among the gods. Butler’s original calls him Hercules.','Hercules|Heracles','reference'),
('gorgon','The Gorgon','The monstrous head Odysseus fears Persephone will send up out of Hades.','Gorgon','reference','mythical-being'),
('rhadamanthus','Rhadamanthus','The fair-haired ruler of the Elysian plain.','Rhadamanthus','reference'),
('orion','Orion','The hunter loved by Dawn and killed by Artemis in Ortygia; he hunts still among the dead.','Orion','reference'),
('iasion','Iasion','The man Demeter loved and Zeus struck down.','Iasion','reference'),
('tithonus','Tithonus','Dawn’s consort, from whose side she rises each morning.','Tithonus','reference'),
('cadmus','Cadmus','Father of Ino, who became the goddess Leucothea.','Cadmus','reference'),
('erechtheus','Erechtheus','The king of Athens to whose house Athena goes.','Erechtheus','reference'),
('lampus','Lampus','One of the two horses that draw Dawn’s chariot.','Lampus','reference','animal'),
('phaethon','Phaethon','One of the two horses that draw Dawn’s chariot.','Phaethon','reference','animal'),
('actor','Actor','Father of the maidservant who keeps Penelope’s bedroom door.','Actor','reference'),
]:add(*row)

# --------------------------------------------- the seer's line, and the lies
for row in [
('melampus','Melampus','The seer and rich man of Pylos, driven out by Neleus, from whom Theoclymenus is descended.','Melampus','reference'),
('phylacus','Phylacus','The king in whose house Melampus was held prisoner for a year.','Phylacus','reference'),
('antiphates-melampus','Antiphates','A son of Melampus, father of Oicleus.','',''),
('mantius','Mantius','A son of Melampus, father of Polypheides and Cleitus.','Mantius','reference'),
('oicleus','Oicleus','Son of Antiphates and father of the seer Amphiaraus.','Oicleus|Oecleus','reference'),
('amphiaraus','Amphiaraus','A seer dearly loved by Zeus and Apollo, killed at Thebes through a woman’s bribe.','Amphiaraus','reference'),
('alcmaeon','Alcmaeon','A son of Amphiaraus.','Alcmaeon','reference'),
('amphilochus','Amphilochus','A son of Amphiaraus.','Amphilochus','reference'),
('polypheides','Polypheides','Son of Mantius and the greatest seer alive after Amphiaraus; Theoclymenus’s father.','Polypheides','reference'),
('cleitus','Cleitus','Son of Mantius, carried off by Dawn for his beauty.','Cleitus','reference'),
('castor-hylax','Castor','The rich and honoured Cretan whom Odysseus, in his false story, claims as his father.','',''),
('hylax','Hylax','Named in Odysseus’s false Cretan story as his supposed grandfather.','Hylax','reference'),
('aethon','Aethon','The name Odysseus gives Penelope when he tells her he is a Cretan and Idomeneus’s younger brother.','Aethon','supporting','assumed-name'),
('deucalion','Deucalion','Named in Odysseus’s false story as Minos’s son and the father of Idomeneus.','Deucalion','reference'),
('eperitus','Eperitus','The name Odysseus gives Laertes before telling him the truth.','Eperitus','supporting','assumed-name'),
('apheidas','Apheidas','A king named in Odysseus’s last false story as his supposed father.','Apheidas','reference'),
('polypemon','Polypemon','Named in Odysseus’s last false story as his supposed grandfather.','Polypemon','reference'),
('pheidon','Pheidon','King of the Thesprotians, who in Odysseus’s tale entertained him and had news of the real Odysseus.','Pheidon','reference'),
('acastus','Acastus','King of Dulichium, to whom the Thesprotian crew were told to take the beggar.','Acastus','reference'),
('thoas','Thoas','Son of Andraemon, who in Odysseus’s campfire story ran to the ships and left his cloak behind.','Thoas','reference'),
('andraemon','Andraemon','Father of Thoas.','Andraemon','reference'),
('orsilochus','Orsilochus','Idomeneus’s son, whom the beggar claims in his story to have killed in Crete.','Orsilochus','reference'),
('dmetor','Dmetor','A great man of Cyprus, son of Iasus, to whom the beggar says he was given.','Dmetor','reference'),
('iasus-cyprus','Iasus','Father of Dmetor of Cyprus.','',''),
('arybas','Arybas','A rich man of Sidon, father of the nurse who carried Eumaeus away.','Arybas','reference'),
('ctesius','Ctesius','Eumaeus’s father, son of Ormenus, king of one of the two communities of Syra.','Ctesius|Ctesias','reference'),
('ormenus','Ormenus','Eumaeus’s grandfather.','Ormenus','reference'),
('echetus','Echetus','A king on the mainland held up as a threat, who mutilates everyone brought to him.','Echetus','reference'),
('iphitus','Iphitus','Son of Eurytus, who gave Odysseus the great bow in Messene and was later killed by Heracles.','Iphitus','reference'),
('eurytus','Eurytus','The archer of Oechalia who would shoot against the gods; Iphitus’s father.','Eurytus','reference'),
('anchialus-taphian','Anchialus','Father of Mentes, king of the Taphians.','',''),
('alcimus','Alcimus','Named as Mentor’s father.','Alcimus','reference'),
('alpheus','Alpheus','A river spoken of as an ancestor, grandfather of Diocles.','Alpheus','reference','personification'),
('ops-none','placeholder','unused','',''),
]:add(*row)
entities[:]=[e for e in entities if e['id']!='ops-none']

# ------------------------------------------------------------------- the peoples
for row in [
('greeks','The Greeks','The army that fought at Troy. The original calls them Achaeans, Argives and Danaans where the modern edition says Greeks.','Achaeans|Argives|Danaans|Greeks','supporting','group'),
('trojans','The Trojans','The people of Troy, against whom the Greeks fought for nine years.','Trojans','reference','group'),
('phaeacians','The Phaeacians','The seafaring people of Scheria, near kin to the gods, who ferry strangers home.','Phaeacians','supporting','group'),
('cyclopes','The Cyclopes','A lawless people who neither plant nor plough and have no assemblies or laws. The singular Cyclops in this book always means Polyphemus.','Cyclopes','supporting','group'),
('laestrygonians','The Laestrygonians','The giant people of Telepylus who wreck Odysseus’s fleet.','Laestrygonians','supporting','group'),
('cicones','The Cicons','The people of Ismarus, the first Odysseus raided after Troy. The modern edition calls them Cicones.','Cicons|Cicones','supporting','group'),
('thesprotians','The Thesprotians','The mainland people whose king Pheidon figures in the beggar’s story.','Thesprotians','reference','group'),
('phoenicians','The Phoenicians','Seafaring traders who appear in both the beggar’s tales and Eumaeus’s.','Phoenicians','reference','group'),
('sidonians','The Sidonians','The people of Sidon.','Sidonians','reference','group'),
('egyptians','The Egyptians','The people of Egypt, skilled in medicine.','Egyptians','reference','group'),
('ethiopians','The Ethiopians','The people at the world’s end, split into two halves, where Poseidon goes to be feasted.','Ethiopians','reference','group'),
('taphians','The Taphians','A seafaring and pirating people; Mentes is their chief.','Taphians','reference','group'),
('myrmidons','The Myrmidons','Achilles’ people, ruled after him by Neoptolemus and by old Peleus.','Myrmidons','reference','group'),
('cephallenians','The Cephallenians','The people over whom Odysseus and Laertes ruled.','Cephallenians','reference','group'),
('epeans','The Epeans','The people who rule in Elis.','Epeans','reference','group'),
('cretans','The Cretans','The people of Crete, among whom the beggar claims his family stood high.','Cretans','reference','group'),
('pylians','The Pylians','Nestor’s people.','Pylians','reference','group'),
('lapiths','The Lapithae','The people among whom the Centaur Eurytion grew violent with wine. The modern edition calls them the Lapiths.','Lapithae|Lapiths','reference','group'),
('cimmerians','The Cimmerians','The people who live wrapped in mist and darkness at the edge of Oceanus.','Cimmerians','reference','group'),
('sintians','The Sintians','The people of Lemnos, whose speech Hephaestus calls barbarous.','Sintians','reference','group'),
('solymi','The Solymi','A people whose mountains Poseidon passes on his way back from Ethiopia.','Solymi','reference','group'),
('erembians','The Erembians','One of the peoples Menelaus visited in his wanderings.','Erembians','reference','group'),
('messenians','The Messenians','The people who carried off three hundred Ithacan sheep.','Messenians','reference','group'),
('eteocretans','The Eteocretans','One of the peoples of Crete.','Eteocretans','reference','group'),
('dorians','The Dorians','One of the peoples of Crete, of threefold race.','Dorians','reference','group'),
('pelasgians','The Pelasgi','One of the peoples of Crete. The modern edition calls them the Pelasgians.','Pelasgi|Pelasgians','reference','group'),
('ceteans','The Ceteians','The people who fell around Eurypylus at Troy. The modern edition calls them the Ceteans.','Ceteians|Ceteans','reference','group'),
('cydonians','The Cydonians','A people of Crete, living around the river Iardanus.','Cydonians','reference','group'),
('sicels','The Sicels','A people to whom the suitors propose selling the beggar and the seer.','Sicels','reference','group'),
('cauconians','The Cauconians','A people to whom Athena, as Mentor, says she must go to collect a debt.','Cauconians','reference','group'),
]:add(*row)

# Later identity clarifications, each released at the end of the paragraph that
# establishes it in the source. Nothing here anticipates an outcome.
SNAPSHOTS={
 'telemachus':[([16,22],'Odysseus’s son. He has now met his father, who revealed himself to him at the swineherd’s hut.')],
 'eumaeus':[([15,33],'Odysseus’s swineherd, loyal to the absent master. He was born a king’s son on the island of Syra, the child of Ctesius son of Ormenus.')],
 'irus':[([18,10],'The town beggar of Ithaca, really named Arnaeus, who challenged the stranger at the door and was beaten.')],
 'theoclymenus':[([20,30],'The seer Telemachus brought home from Pylos, of the house of Melampus; he reads the darkness that falls over the suitors at their meal.')],
}
for e in entities:
 for after,body in SNAPSHOTS.get(e['id'],[]):e['snapshots'].append(dict(after=after,body=body))

Path(__file__).parent.joinpath('editorial.json').write_text(json.dumps(dict(
 contentVersion='2026-09-11.1',
 coverage='Both full English editions, all twenty-four books: named people, gods, personified powers, named animals and named peoples. Places, rivers, mountains, islands, ships, stars and adjectival forms of place names are excluded.',
 entities=entities),ensure_ascii=False,indent=2)+'\n')
print(len(entities),'entities')
