"""Manually reviewed historical and editorial references, including namesakes."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',kind='person',category='reference'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))
for row in [
('lorenzo','Lorenzo de’ Medici','Lorenzo di Piero de’ Medici, the young Florentine ruler to whom Machiavelli dedicates the book.','Lorenzo Di Piero De’ Medici|Lorenzo di Piero de’ Medici|Lorenzo di Piero de\' Medici|Your Magnificence|your Magnificence'),
('machiavelli','Niccolò Machiavelli','The Florentine diplomat and author of this advice on political power.','Niccolò Machiavelli|Nicolo Machiavelli|Nicolo Machiavel|Machiavelli'),
('francesco','Francesco Sforza','The military commander who became Duke of Milan; Lodovico’s father.','Francesco Sforza|Francesco'),
('ferdinand','Ferdinand of Aragon','Ferdinand II of Aragon, the Spanish king repeatedly used as an example of political strategy.','Ferdinand of Aragon|Ferdinand II|Ferdinand|King of Spain'),
('julius','Pope Julius II','Giuliano della Rovere, the pope whose military and political campaigns Machiavelli examines.','Pope Julius the Second|Pope Julius II|Pope Julius|Julius the Second|Julius II|Julius|Giuliano della Rovere|Cardinal of San Pietro ad Vincula|San Pietro ad Vincula'),
('louis12','Louis XII','The French king whose attempts to hold territory in Italy Machiavelli analyzes.','Louis the Twelfth|Louis XII|King Louis|Louis'),
('lodovico','Lodovico Sforza','The Duke of Milan known as Lodovico Moro; Francesco Sforza’s son and Beatrice d’Este’s husband.','Duke Lodovico|Lodovico Moro|Lodovico'),
('beatrice','Beatrice d’Este','Lodovico Sforza’s wife, the duchess of Milan.',"Beatrice d’Este|Beatrice d'Este"),
('antiochus','Antiochus III','The Seleucid king whose intervention in Greece brought him into conflict with Rome.','Antiochus'),
('philip5','Philip V of Macedon','The Macedonian king who fought Rome and was defeated by Flamininus.',''),
('philip2','Philip II of Macedon','Alexander the Great’s father, the Macedonian king cited on military power.',''),
('charles8','Charles VIII','The French king whose invasion of Italy preceded the campaigns of Louis XII.','Charles VIII|Charles'),
('alexander6','Pope Alexander VI','Rodrigo Borgia, the pope and father of Cesare Borgia.','Pope Alexander VI|Pope Alexander|Alexander the Sixth|Alexander VI'),
('jeanne','Jeanne of France','Louis XII’s first wife and Louis XI’s daughter.','Jeanne'),
('louis11','Louis XI','The French king who was Charles VII’s son and Jeanne’s father.','Louis the Eleventh|Louis XI'),
('anne','Anne of Brittany','The duchess of Brittany who married Charles VIII and later Louis XII.','Anne of Brittany'),
('rouen','Georges d’Amboise','The French cardinal and archbishop of Rouen, an adviser to Louis XII.','The Archbishop of Rouen|Georges d’Amboise|Cardinal Rouen|Rouen'),
('cesare','Cesare Borgia','Pope Alexander VI’s son, the military ruler also called Duke Valentino.','Cesare Borgia|Duke Valentino|Valentino|Cesare'),
('alexander-great','Alexander the Great','The Macedonian conqueror and son of Philip II.','Alexander the Great'),
('darius3','Darius III','The Persian king whose empire Alexander the Great conquered.',''),
('darius1','Darius I','The Persian king cited for installing dependent rulers in Greek territories.',''),
('pyrrhus','Pyrrhus','The king of Epirus cited in the discussion of holding conquered territory.','Pyrrhus'),
('cyrus','Cyrus the Great','The founder of the Persian Empire, used as a model of a ruler who establishes a new state.','Cyrus'),
('savonarola','Girolamo Savonarola','The Florentine friar and religious reformer cited as an unarmed prophet.','Fra Girolamo Savonarola'),
('hiero','Hiero II','The ruler of Syracuse used as an example of building power through one’s own forces.','Hiero the Syracusan|Hiero of Syracuse|Hiero II|Hiero'),
('bianca-visconti','Bianca Maria Visconti','Francesco Sforza’s wife and Filippo Maria Visconti’s daughter.','Bianca Maria Visconti'),
('filippo','Filippo Maria Visconti','The Duke of Milan whose daughter Bianca Maria married Francesco Sforza.','Filippo Visconti|Duke Filippo'),
('vitellozzo','Vitellozzo Vitelli','The military commander, brother of Pagolo Vitelli and associate of Oliverotto da Fermo.','Vitellozzo Vitelli|Vitellozzo'),
('pagolo-orsini','Paolo Orsini','The Orsini commander who mediates the reconciliation with Cesare Borgia; called Signor Pagolo.','Signor Pagolo'),
('ramiro','Ramiro d’Orco','Cesare Borgia’s governor in the Romagna, also called Ramiro de Lorqua.','Messer Ramiro d’Orco|Ramiro d’Orco|Ramiro de Lorqua|Ramiro'),
('riario-cardinal','Raffaello Riario','The cardinal of San Giorgio, named among those injured by Cesare Borgia.','San Giorgio|Raffaello Riario'),
('ascanio','Ascanio Sforza','The cardinal of the Milanese Sforza family named among Cesare Borgia’s opponents.','Ascanio Sforza|Ascanio'),
('colonna-cardinal','Giovanni Colonna','The Colonna cardinal named among those with grounds to resent Cesare Borgia.',''),
('agathocles','Agathocles','The ruler of Syracuse used in the discussion of acquiring power through violence.','Agathocles the Sicilian|Agathocles'),
('hamilcar','Hamilcar','The Carthaginian commander in Sicily with whom Agathocles reaches an understanding.','Amilcar|Hamilcar'),
('oliverotto','Oliverotto da Fermo','The military commander and nephew of Giovanni Fogliani, discussed as a ruler who seizes power violently.','Oliverotto da Fermo|Oliverotto'),
('fogliani','Giovanni Fogliani','Oliverotto da Fermo’s maternal uncle, who brings him up.','Giovanni Fogliani'),
('pagolo-vitelli','Paolo Vitelli','The Florentine military commander called Pagolo Vitelli; Vitellozzo’s brother.','Pagolo Vitelli'),
('burd','L. Arthur Burd','The editor and commentator on The Prince cited in the translation’s notes.','Mr Burd|Mr. Burd|Burd'),
('nabis','Nabis','The ruler of Sparta used in the argument about securing popular support.','Nabis the Spartan|Nabis'),
('scali','Giorgio Scali','The Florentine political leader cited as an example of misplaced reliance on popular support.','Messer Giorgio Scali|Giorgio Scali'),
('flamininus','Titus Quinctius Flamininus','The Roman commander who fought Philip V and Nabis.','Flamininus|Titus Quintius'),
('sixtus','Pope Sixtus IV','The pope cited in the account of papal authority and Rome’s rival baronial families.','Sixtus'),
('leo','Pope Leo X','Giovanni de’ Medici, the Medici pope reigning when Machiavelli writes.','Pope Leo X|Pope Leo|Leo X|Cardinal de’ Medici|Cardinal de\' Medici'),
('bacon','Francis Bacon','The English writer whose history of Henry VII is quoted in an editorial note.','Lord Bacon'),
('henry7','Henry VII of England','The English king who is the subject of Bacon’s history cited in a note.','Henry VII'),
('epaminondas','Epaminondas','The Theban commander mentioned in the discussion of mercenary armies.','Epaminondas'),
('muzio','Muzio Attendolo Sforza','Francesco Sforza’s father, a mercenary captain employed by Joanna II of Naples.',''),
('joanna','Joanna II of Naples','The queen of Naples who employs Sforza’s father.','Queen Johanna of Naples|Johanna II|Johanna'),
('alfonso5','Alfonso V of Aragon','The Aragonese king to whom Joanna II turns for protection.','King of Aragon'),
('hawkwood','John Hawkwood','The English mercenary commander known in Italy as Giovanni Acuto.','Sir John Hawkwood|John Hawkwood|Giovanni Acuto'),
('braccio','Braccio da Montone','The mercenary captain whose military following rivals the Sforza commanders.','Braccio'),
('carmagnola','Carmagnola','Francesco Bussone, the mercenary commander who serves Milan and Venice.','Carmignuola|Francesco Bussone'),
('colleoni','Bartolomeo Colleoni','The Venetian commander from Bergamo, named among Venice’s hired captains.','Bartolomeo Colleoni of Bergamo|Bartolomeo da Bergamo'),
('sanseverino','Roberto Sanseverino','The military commander named among Venice’s hired captains.','Roberto da San Severino|Roberto of San Severino'),
('pitigliano','Niccolò Orsini','The Count of Pitigliano, a military commander employed by Venice.','Count of Pitigliano|count of Pitigliano|Nicolo Orsini'),
('ladislaus','Ladislaus of Naples','The king of Naples named in the note on Joanna II.','Ladislao'),
('edward3','Edward III of England','The English king mentioned in the note on John Hawkwood.','Edward III'),
('donnina','Donnina Visconti','John Hawkwood’s wife and Bernabò Visconti’s daughter; called Domnia in the original edition.','Domnia|Donnina'),
('bernabo','Bernabò Visconti','The ruler of Milan cited for conspicuous rewards and punishments; Donnina’s father.','Bernabo Visconti|Bernabò Visconti|Messer Bernabo da Milano|Messer Bernabò of Milan'),
('sigismund','Sigismund of Austria','The Habsburg duke named in the note on Roberto Sanseverino’s last campaign.','Sigismund'),
('alberico','Alberico da Barbiano','The mercenary commander who leads the Company of St George; also called Alberigo da Conio.','Alberigo da Conio|Alberico da Barbiano|Count of Cunio'),
('john6','John VI Kantakouzenos','The Byzantine emperor cited for bringing Turkish auxiliary troops into Greece.','The Emperor of Constantinople|Joannes Cantacuzenus'),
('charles7','Charles VII','The French king cited for establishing his own military forces; Louis XI’s father.','Charles the Seventh|Charles VII'),
('balfour','Arthur Balfour','The British politician quoted in an editorial note on military obligations.','Mr Balfour|Mr. Balfour'),
('philopoemen','Philopoemen','The Achaean leader cited for studying military situations even in peacetime.','Philopoemen'),
('caesar','Julius Caesar','The Roman general and ruler cited as a model of political and military ambition.','Caesar'),
('scipio','Scipio Africanus','The Roman commander who defeated Hannibal, cited on military discipline and imitation of Cyrus.','Scipio'),
('xenophon','Xenophon','The Greek writer whose account of Cyrus supplies a model of princely conduct.','Xenophon'),
('virgil','Virgil','The Roman poet quoted through Dido’s speech in the Aeneid.','Virgil'),
('pitt','Christopher Pitt','The English translator credited for the verse from Virgil.','Christopher Pitt'),
('hannibal','Hannibal','The Carthaginian commander cited for maintaining discipline in a diverse army.','Hannibal'),
('fabius','Fabius Maximus','The Roman commander who criticizes Scipio’s leniency.','Fabius Maximus'),
('cicero','Cicero','The Roman statesman and philosopher whose On Duties is cited in a note.','Cicero'),
('south','Robert South','The English preacher quoted in the note on religion and political appearances.','South'),
('annibale1','Annibale I Bentivoglio','The earlier ruler of Bologna; Giovanni II’s father and Annibale II’s grandfather.','Messer Annibale Bentivogli'),
('annibale2','Annibale II Bentivoglio','The younger Annibale, grandson of the earlier Bolognese ruler.',''),
('giovanni2','Giovanni II Bentivoglio','The ruler of Bologna who is Annibale I’s son and Annibale II’s father.','Messer Giovanni Bentivogli|Giovanni Bentivogli|Messer Giovanni'),
('sante','Sante Bentivoglio','The Bentivoglio relative raised in Florence who is called to govern Bologna during Giovanni’s childhood.',''),
('boscoli','Pietro Paolo Boscoli','The Florentine conspirator whose case is mentioned in the note about Machiavelli’s arrest.','Boscoli'),
('marcus','Marcus Aurelius','The Roman emperor and philosopher, father of Commodus.','Marcus the philosopher|Marcus'),
('commodus','Commodus','The Roman emperor who succeeds his father, Marcus Aurelius.','Commodus'),
('pertinax','Pertinax','The Roman emperor who succeeds Commodus, discussed in relation to the army’s power.','Pertinax'),
('julian','Didius Julianus','The Roman emperor called Julian, who precedes Septimius Severus.','Emperor Julian|Julian'),
('severus','Septimius Severus','The Roman emperor, father of Caracalla, examined as an example of force and cunning.','Severus'),
('caracalla','Caracalla','The Roman emperor and son of Septimius Severus, also called Antoninus.','Antoninus Caracalla|Antoninus|Caracalla'),
('macrinus','Macrinus','The Roman emperor who follows Caracalla, included in the survey of imperial rule.','Macrinus'),
('elagabalus','Elagabalus','The Roman emperor called Heliogabalus in this translation.','Heliogabalus'),
('alexander-severus','Severus Alexander','The Roman emperor discussed after Elagabalus, distinct from Alexander the Great and Pope Alexander VI.',''),
('maximinus','Maximinus Thrax','The Roman emperor who rises from the army after Severus Alexander.','Maximinus'),
('niger','Pescennius Niger','The eastern commander who competes with Septimius Severus for the Roman throne.','Niger'),
('albinus','Clodius Albinus','The western commander whose imperial ambitions conflict with those of Septimius Severus.','Albinus'),
('petrucci','Pandolfo Petrucci','The ruler of Siena whose choice of advisers Machiavelli praises.','Pandolfo Petrucci|Pandolfo'),
('nicolo-vitelli','Niccolò Vitelli','The ruler of Città di Castello cited for demolishing fortresses.','Messer Nicolo Vitelli|Messer Niccolò Vitelli|Nicolo Vitelli|Niccolò Vitelli'),
('guidobaldo','Guidobaldo da Montefeltro','The Duke of Urbino cited in the discussion of fortresses.','Guido Ubaldo|Duke of Urbino'),
('caterina','Caterina Sforza','The ruler of Forlì, wife of Girolamo Riario; called Catherine Sforza in the notes.','Countess of Forli|Countess of Forlì|my lady of Forli|lady of Forlì|Catherine Sforza'),
('girolamo','Girolamo Riario','Caterina Sforza’s husband and co-ruler at Forlì.','Count Girolamo'),
('galeazzo','Galeazzo Maria Sforza','The Duke of Milan who is Caterina Sforza’s father.','Galeazzo Sforza'),
('lucrezia','Lucrezia Landriani','Caterina Sforza’s mother.','Lucrezia Landriani'),
('fortunati','Fortunati','Caterina Sforza’s correspondent, quoted on Machiavelli’s appointment as envoy.','Fortunati'),
('pasolini','Count Pasolini','The author of the biography of Caterina Sforza cited in the notes.','Count Pasolini'),
('sylvester','P. Sylvester','The translator credited for the biography of Caterina Sforza.','P. Sylvester'),
('florio','John Florio','The lexicographer quoted on the Italian word for a trade guild.','Florio'),
('staley','Edgcumbe Staley','The writer on Florentine guilds cited in the notes.','Edgcumbe Staley'),
('wallace','Donald Mackenzie Wallace','The writer whose account of Russian labor associations is quoted in a note.','Sir Mackenzie Wallace'),
('maude','Aylmer Maude','The writer consulted in the note on the Russian word artel.','Aylmer Maude'),
('venafro','Antonio da Venafro','Pandolfo Petrucci’s adviser, used as an example of a well-chosen minister.','Messer Antonio da Venafro|Antonio da Venafro|Venafro'),
('luca','Fra Luca','The agent of Emperor Maximilian whose account of the emperor’s indecision Machiavelli reports.','Fra Luca'),
('maximilian','Maximilian I','The Holy Roman emperor whose way of consulting advisers Machiavelli criticizes.','Maximilian I|Maximilian'),
('mary-burgundy','Mary of Burgundy','Maximilian I’s first wife and Charles the Bold’s daughter.','Mary'),
('charles-bold','Charles the Bold','The duke of Burgundy whose daughter Mary marries Maximilian I.','Charles the Bold'),
('bianca-sforza','Bianca Maria Sforza','Maximilian I’s second wife, from Milan’s ruling family.','Bianca Sforza'),
('frederick','Frederick the Great','The Prussian king quoted on the power of chance in an editorial note.','Frederick the Great'),
('sorel','Albert Sorel','The historian whose Eastern Question is cited for the remark attributed to Frederick the Great.','Sorel'),
('clement','Pope Clement VII','Giulio de’ Medici, the Medici cardinal identified as Clement VII in the final chapter’s note.','Clement VII'),
('petrarch','Petrarch','The Italian poet whose appeal for Italy closes Machiavelli’s exhortation.','Petrarch'),
('dacre','Edward Dacre','The translator credited for the closing lines from Petrarch.','Edward Dacre'),
]:add(*row)
for row in [
('moses','Moses','The biblical leader of the Israelites, cited as a founder and lawgiver.','Moses','religious-figure'),
('god','God','The divine authority invoked in the discussions of founders, religion and Italy’s deliverance.','God','religious-figure'),
('romulus','Romulus','The legendary founder of Rome, used as a model of founding a new state.','Romulus','mythological-figure'),
('theseus','Theseus','The legendary Athenian king credited with uniting Athens.','Theseus','mythological-figure'),
('achilles','Achilles','The Greek hero of the Trojan War, cited as Alexander’s model and Chiron’s pupil.','Achilles','literary-figure'),
('chiron','Chiron','The centaur who teaches Achilles in Greek legend.','Centaur Chiron|Chiron','mythological-figure'),
('dido','Dido','The queen of Carthage in Virgil’s Aeneid, quoted on the insecurity of a new reign.','Dido','literary-figure'),
('david','David','The biblical hero who refuses Saul’s armor before confronting Goliath.','David','religious-figure'),
('saul','Saul','The biblical king who offers David his weapons and armor.','Saul','religious-figure'),
('goliath','Goliath','The Philistine champion confronted by David in the biblical story.','Goliath','religious-figure'),
('ferrara','The Este dukes of Ferrara','The hereditary dynasty invoked through the attacks of 1484 and 1510, which fall under different dukes.','','group'),
('ercole','Ercole I d’Este','The Duke of Ferrara among the Italian rulers who make advances to Louis XII.','','person'),
('turk','The Ottoman sultan','The Ottoman ruler, called the Turk, whose centralized government Machiavelli contrasts with France.','Turk','unnamed-role'),
('soldan','The Mamluk sultan','The ruler of Egypt, called the Soldan, whose power depends on the military elite.','Soldan','unnamed-role'),
('orsini','The Orsini family','The Roman baronial family and its political and military following.','Orsini','group'),
('colonna','The Colonna family','The Roman baronial family and faction also called the Colonnesi.','Colonnesi|Colonna','group'),
('vitelli','The Vitelli family','The family of military commanders associated with Città di Castello.','Vitelli|Vitelleschi','group'),
('baglioni','The Baglioni family','The Perugian ruling family named among Cesare Borgia’s opponents.','Baglioni','group'),
('bentivogli','The Bentivoglio family','The ruling family of Bologna, called the Bentivogli in this translation.','Bentivogli','group'),
('sforza-family','The Sforza family','The ruling dynasty of Milan established by Francesco Sforza.','house of Sforza','group'),
('gracchi','The Gracchi','The Roman reforming brothers Tiberius and Gaius Gracchus, cited on reliance on popular support.','Gracchi','group'),
('canneschi','The Canneschi','The Bolognese family whose conspiracy targets Annibale Bentivoglio.','Canneschi','group'),
('cancellieri','The Cancellieri','One of the rival Pistoian families named in the note on civil disorder.','Cancellieri','group'),
('panciatichi','The Panciatichi','One of the rival Pistoian families named in the note on civil disorder.','Panciatichi','group'),
('bracceschi','The Bracceschi','The soldiers and captains of Braccio’s military following.','Bracceschi','group'),
('medici','The Medici family','The Florentine ruling family addressed in the final appeal to liberate Italy.','','group'),
('mantua','The Marquess of Mantua','The Mantuan ruler named among the Italian allies sought by Louis XII.','Marquess of Mantua','unnamed-role'),
('lords','The lords of the smaller Italian states','The rulers of Faenza, Pesaro, Rimini, Camerino and Piombino who seek friendship with Louis XII.','','group'),
]:add(*row)
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='the-prince',contentVersion='2026-09-10.1',coverage='Dedication, all 26 chapters and their surviving editorial notes in both English editions. Historical, religious, literary and editorial references, named families and specific ruler roles. Generic princes, offices and population names are not automatically individual people.',entities=entities),ensure_ascii=False,indent=2)+'\n')
