#!/usr/bin/env python3
"""Small philosophy titles: clickable-names sweep.

Minimal cards for every named figure the essays cite or argue with, after
rebind_junk_cards.py restored the plain names of the first-generation
cards. Homonyms handled by paragraph restriction:

  aristotle-politics   Cleisthenes of Athens / of Sicyon (5,78); king
                       Pausanias / Pausanias who killed Philip (5,54);
                       Chares the Parian (1,40) / the Athenian general.
  fear-and-trembling   "Sarah" in the Tobias passage is Raguel's daughter,
                       not Abraham's wife; "Isaac" was bound only as "Take
                       Isaac" x2 and is rebound; "Diogenes" is Laertius.
  meditations          bare "Alexander" outside the grammarian/Platonist
                       paragraphs is Alexander the Great.
  genealogy-of-morals  "Paul" outside chapter 1 (Paul Rée) is the apostle.
  magna-carta          "Henry" in the witness lists is the archbishop of
                       Dublin; "King Henry" is Henry II; "Hugh" alone is the
                       bishop of Lincoln once Hugh de Neville and John Fitz
                       Hugh are bound; bare "William" (seven men) is left.
  second-treatise      "William" (16,3) is the Conqueror.

Usage: add_philosophy_sweep_entities.py BOOK...
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from add_histories_helpers import add_entity_excluding as add_e
from add_aliases import add_aliases
from add_aliases_restricted import add_aliases_restricted

ROOT = Path(__file__).resolve().parents[2]
P, D, G = 'person', 'deity', 'group'


def _paras(book):
    ed = json.loads((ROOT / f'app/public/data/editions/{book}-original-en.json').read_text())
    return [(c['number'], i, p) for c in ed['chapters'] for i, p in enumerate(c['paragraphs'])]


def chapters(book, *chs):
    return {(ch, i) for ch, i, p in _paras(book) if ch in chs}


def paras_with(book, pattern):
    rx = re.compile(pattern)
    return {(ch, i) for ch, i, p in _paras(book) if rx.search(p)}


def card_paras(book, cid):
    pkg = json.loads((ROOT / f'app/public/data/characters/{book}.v1.json').read_text())
    return {(m['chapterNumber'], m['paragraphIndex']) for m in pkg['editions']['original-en']['mentions'] if m['characterId'] == cid}


def drop_mentions(book, cid, paragraphs=None, text=None):
    path = ROOT / f'app/public/data/characters/{book}.v1.json'
    pkg = json.loads(path.read_text())
    for ek, ed in pkg['editions'].items():
        before = len(ed['mentions'])
        ed['mentions'] = [m for m in ed['mentions'] if not (m['characterId'] == cid
                                                             and (paragraphs is None or (m['chapterNumber'], m['paragraphIndex']) in paragraphs)
                                                             and (text is None or m['text'] == text))]
        print(book, ek, cid, 'dropped', before - len(ed['mentions']))
    path.write_text(json.dumps(pkg, ensure_ascii=False, indent=2) + '\n')


def maker(book):
    def r(eid, name, subtitle, body, aliases, kind=P, role='reference', **kw):
        kw.setdefault('strict_editions', ())
        add_e(book, eid, name, subtitle, body, role, kind, aliases, **kw)
    return r


def politics():
    B = 'aristotle-politics'; r = maker(B)
    r('homer', 'Homer', '', "", ['Homer'])
    r('hesiod', 'Hesiod', '', "", ['Hesiod'])
    r('zeus', 'Zeus', '', "", ['Olympian Zeus', 'Zeus'], kind=D)
    r('minos', 'Minos', 'Lawgiver of Crete', "", ['Minos'])
    r('charondas', 'Charondas', 'Lawgiver of Catana', "", ['Charondas'])
    r('zaleucus', 'Zaleucus', 'Lawgiver of the Locrians', "", ['Zaleucus'])
    r('philolaus', 'Philolaus', 'The Corinthian, lawgiver of Thebes', "", ['Philolaus'])
    r('onomacritus', 'Onomacritus', '', "", ['Onomacritus'])
    r('draco', 'Draco', '', "", ['Draco'])
    r('pittacus', 'Pittacus', 'Of Mitylene', "", ['Pittacus'])
    r('androdamas', 'Androdamas', 'Of Rhegium', "", ['Androdamas'])
    r('pheidon', 'Pheidon', '', "", ['Pheidon'])
    add_aliases(B, 'phaleas-of-chalcedon', ['Phaleas'])
    add_aliases(B, 'hippodamus', ['Hippodamus'])
    r('gelo', 'Gelo', 'Tyrant of Syracuse', "", ['Gelo'])
    r('hiero', 'Hiero', 'Tyrant of Syracuse', "Gelo's brother.", ['Hiero'])
    r('thrasybulus', 'Thrasybulus', '', "Tyrant of Miletus, to whom Periander sent his counsel; also the brother of Hiero.", ['Thrasybulus'])
    r('periander', 'Periander', 'Tyrant of Corinth', "", ['Periander'])
    r('cypselus', 'Cypselus', 'Tyrant of Corinth', "", ['Cypselus'])
    r('psammetichus', 'Psammetichus', '', "", ['Psammetichus'])
    r('dionysius', 'Dionysius', 'Tyrant of Syracuse', "The elder and the younger.", ['Dionysius'])
    r('dion', 'Dion', '', "Who attacked the younger Dionysius.", ['Dion'])
    r('archelaus', 'Archelaus', 'King of Macedon', "", ['Archelaus'])
    r('crataeus', 'Crataeus', '', "", ['Crataeus'])
    r('decamnichus', 'Decamnichus', '', "", ['Decamnichus'])
    r('hellanocrates', 'Hellanocrates', 'Of Larissa', "", ['Hellanocrates'])
    r('amyntas', 'Amyntas', '', "", ['Amyntas'])
    r('derdas', 'Derdas', '', "", ['Derdas'])
    r('arrhibaeus', 'Arrhibaeus', '', "", ['Arrhibaeus'])
    r('sirrhas', 'Sirrhas', '', "", ['Sirrhas'])
    r('cleopatra', 'Cleopatra', '', "", ['Cleopatra'])
    r('philip', 'Philip', 'Of Macedon', "", ['Philip'])
    r('pausanias-assassin', 'Pausanias', "Philip's assassin", "", ['Pausanias'], only_paragraphs={(5, 54)})
    r('pausanias', 'Pausanias', 'King of Sparta', "", ['Pausanias'], exclude_paragraphs={(5, 54)})
    r('lysander', 'Lysander', '', "", ['Lysander'])
    r('charilaus', 'Charilaus', 'King of Sparta', "", ['King Charilaus', 'Charilaus'])
    r('cleomenes', 'Cleomenes', 'The Lacedaemonian', "", ['Cleomenes'])
    r('harmodius', 'Harmodius', '', "", ['Harmodius'])
    r('aristogeiton', 'Aristogeiton', '', "", ['Aristogeiton'])
    r('peisistratus', 'Peisistratus', 'Tyrant of Athens', "", ['Peisistratus'])
    r('peisistratidae', 'The Peisistratidae', '', "", ['Peisistratidae'], kind=G)
    r('cleisthenes-of-sicyon', 'Cleisthenes', 'Tyrant of Sicyon', "", ['Cleisthenes'], only_paragraphs={(5, 78)})
    r('cleisthenes', 'Cleisthenes', 'Of Athens', "", ['Cleisthenes'], exclude_paragraphs={(5, 78)})
    r('ephialtes', 'Ephialtes', '', "", ['Ephialtes'])
    r('pericles', 'Pericles', '', "", ['Pericles'])
    r('theagenes', 'Theagenes', 'Of Megara', "", ['Theagenes'])
    r('panaetius', 'Panaetius', 'Of Leontini', "", ['Panaetius'])
    r('orthagoras', 'Orthagoras', 'Of Sicyon', "", ['Orthagoras'])
    r('myron', 'Myron', 'Of Sicyon', "", ['Myron'])
    r('cleander', 'Cleander', 'Of Gela', "", ['Cleander'])
    r('anaxilaus', 'Anaxilaus', 'Of Rhegium', "", ['Anaxilaus'])
    r('antileon', 'Antileon', 'Of Chalcis', "", ['Antileon'])
    r('phalaris', 'Phalaris', '', "", ['Phalaris'])
    r('timophanes', 'Timophanes', '', "", ['Timophanes'])
    r('doxander', 'Doxander', '', "", ['Doxander'])
    r('diagoras', 'Diagoras', '', "", ['Diagoras'])
    r('iphiades', 'Iphiades', '', "", ['Iphiades'])
    r('thrasymachus', 'Thrasymachus', '', "", ['Thrasymachus'])
    r('mithridates', 'Mithridates', '', "", ['Mithridates'])
    r('ariobarzanes', 'Ariobarzanes', '', "", ['Ariobarzanes'])
    r('artapanes', 'Artapanes', '', "", ['Artapanes'])
    r('xerxes', 'Xerxes', '', "", ['Xerxes'])
    r('darius', 'Darius', '', "", ['Darius'])
    r('cyrus', 'Cyrus', '', "", ['Cyrus'])
    r('smerdis', 'Smerdis', '', "", ['Smerdis'])
    r('penthilus', 'Penthilus', '', "", ['Penthilus'])
    r('amadocus', 'Amadocus', '', "", ['Amadocus'])
    r('seuthes', 'Seuthes', 'The Thracian', "", ['Seuthes'])
    r('evagoras', 'Evagoras', 'Of Cyprus', "", ['Evagoras'])
    r('codrus', 'Codrus', '', "", ['Codrus'])
    r('hanno', 'Hanno', '', "", ['Hanno'])
    r('thibron', 'Thibron', '', "", ['Thibron'])
    r('sesostris', 'Sesostris', '', "", ['Sesostris'])
    r('italus', 'Italus', 'King of Oenotria', "", ['Italus'])
    r('oxylus', 'Oxylus', '', "", ['Oxylus'])
    r('onomarchus', 'Onomarchus', '', "", ['Onomarchus'])
    r('euthycrates', 'Euthycrates', '', "", ['Euthycrates'])
    r('mnason', 'Mnason', '', "", ['Mnason'])
    r('mnaseas', 'Mnaseas', '', "", ['Mnaseas'])
    r('paches', 'Paches', '', "", ['Paches'])
    r('chares-parian', 'Chares', 'The Parian', "", ['Chares'], only_paragraphs={(1, 40)})
    r('chares', 'Chares', 'The Athenian general', "", ['Chares'], exclude_paragraphs={(1, 40)})
    r('apollodorus', 'Apollodorus', 'The Lemnian', "", ['Apollodorus'])
    r('simos', 'Simos', '', "", ['Simos'])
    r('cleotimus', 'Cleotimus', '', "", ['Cleotimus'])
    r('theopompus', 'Theopompus', '', "", ['Theopompus'])
    r('eubulus', 'Eubulus', '', "", ['Eubulus'])
    r('autophradates', 'Autophradates', '', "", ['Autophradates'])
    r('thales', 'Thales', 'The Milesian', "", ['Thales'])
    r('midas', 'Midas', '', "", ['Midas'])
    r('amasis', 'Amasis', '', "", ['Amasis'])
    r('epimenides', 'Epimenides', 'The Cretan', "", ['Epimenides'])
    r('euripides', 'Euripides', '', "", ['Euripides'])
    r('theodectes', 'Theodectes', '', "", ['Theodectes'])
    r('agamemnon', 'Agamemnon', '', "", ['Agamemnon'])
    r('achilles', 'Achilles', '', "", ['Achilles'])
    r('odysseus', 'Odysseus', '', "", ['Odysseus'])
    r('heracles', 'Heracles', '', "", ['Heracles'])
    r('jason', 'Jason', 'Of Pherae', "", ['Jason'])
    r('alcaeus', 'Alcaeus', 'The poet', "", ['Alcaeus'])
    r('antimenides', 'Antimenides', '', "", ['Antimenides'])
    r('tyrtaeus', 'Tyrtaeus', '', "", ['Tyrtaeus'])
    r('archilochus', 'Archilochus', '', "", ['Archilochus'])
    r('heracleitus', 'Heracleitus', '', "", ['Heracleitus'])
    r('hippocrates', 'Hippocrates', '', "", ['Hippocrates'])
    r('gorgias', 'Gorgias', 'Of Leontini', "", ['Gorgias'])
    r('musaeus', 'Musaeus', '', "", ['Musaeus'])
    r('pauson', 'Pauson', '', "", ['Pauson'])
    r('polygnotus', 'Polygnotus', '', "", ['Polygnotus'])
    r('philoxenus', 'Philoxenus', '', "", ['Philoxenus'])
    r('olympus', 'Olympus', 'The musician', "", ['Olympus'])
    r('perioeci', 'The Perioeci', '', "The subject population of Crete.", ['Perioeci'], kind=G)
    r('helots', 'The Helots', '', "", ['Helots'], kind=G)
    r('penestae', 'The Penestae', '', "", ['Penestae'], kind=G)
    r('basilidae', 'The Basilidae', '', "", ['Basilidae'], kind=G)
    r('aristotle', 'Aristotle', 'The author', "", ['Aristotle'])


def vindication():
    B = 'vindication-rights-of-woman'; r = maker(B)
    r('pope', 'Pope', 'The poet', "", ['Pope'])
    r('dr-johnson', 'Dr. Johnson', '', "", ['Dr. Johnson', 'Johnson'])
    r('adam', 'Adam', "Milton's Adam", "", ['Adam'])
    r('eve', 'Eve', '', "", ['Eve'])
    r('adam-smith', 'Dr. Smith', 'Theory of Moral Sentiments', "", ['Dr. Smith', 'Smith'])
    r('sophia', 'Sophia', "Rousseau's Sophia", "", ['Sophia'])
    r('emilius', 'Emilius', "Rousseau's pupil", "", ['Emilius'])
    r('eloisa', 'Eloisa', '', "", ['Eloisa'])
    r('st-preux', 'St. Preux', '', "", ['St. Preux'])
    r('cervantes', 'Cervantes', '', "", ['Cervantes'])
    r('solomon', 'Solomon', '', "", ['Solomon'])
    r('mahomet', 'Mahomet', '', "", ['Mahomet'])
    r('priestley', 'Dr. Priestley', '', "", ['Dr. Priestley', 'Priestley'])
    r('shakespeare', 'Shakespeare', '', "", ['Shakespeare'])
    r('hume', 'Mr. Hume', '', "", ['Mr. Hume', 'Hume'])
    r('chesterfield', 'Lord Chesterfield', '', "", ['Lord Chesterfield', 'Chesterfield'])
    r('lewis-xiv', 'Lewis XIV', '', "", ['Lewis XIV'])
    r('richardson', 'Richardson', '', "", ['Richardson'])
    r('clarissa', 'Clarissa', '', "", ['Clarissa'])
    r('lovelace', 'Lovelace', '', "", ['Lovelace'])
    r('sappho', 'Sappho', '', "", ['Sappho'])
    r('moses', 'Moses', '', "", ['Moses'])
    r('tully', 'Tully', '', "", ['Tully'])
    r('newton', 'Sir Isaac Newton', '', "", ['Sir Isaac Newton', 'Isaac Newton', 'Newton'])
    r('mrs-piozzi', 'Mrs. Piozzi', '', "", ['Mrs. Piozzi', 'Piozzi'])
    r('madame-genlis', 'Madame Genlis', '', "", ['Madame Genlis', 'Genlis'])
    r('mrs-chapone', 'Mrs. Chapone', '', "", ['Mrs. Chapone', 'Chapone'])
    r('mrs-barbauld', 'Mrs. Barbauld', '', "", ['Mrs. Barbauld', 'Barbauld'])
    r('jesus-christ', 'Jesus Christ', '', "", ['Jesus Christ', 'Christ', 'Jesus'])
    r('peter', 'Peter', 'The apostle', "", ['Peter'], only_paragraphs={(9, 2)})
    r('knox', 'Knox', "Knox's Essays", "", ['Knox'])
    r('diana', 'Diana', '', "", ['Diana'], kind=D)
    r('juno', 'Juno', '', "", ['Juno'], kind=D)
    r('cerberus', 'Cerberus', '', "", ['Cerberus'])
    r('locke', 'Mr. Locke', '', "", ['Mr. Locke', 'Locke'])
    r('macbeth', 'Macbeth', '', "", ['Macbeth'])
    r('hamlet', 'Hamlet', '', "", ['Hamlet'])
    r('swift', 'Dean Swift', '', "", ['Dean Swift', 'Swift'])
    r('bacon', 'Lord Bacon', '', "", ['Lord Bacon', 'Bacon'])
    r('dryden', 'Dryden', '', "", ['Dryden'])
    r('cowper', 'Cowper', '', "", ['Cowper'])
    r('cato', 'Cato', '', "", ['Cato'])
    r('butler', 'Butler', '', "", ['Butler'])
    r('satan', 'Satan', "Milton's Satan", "", ['Satan'], kind=D)
    r('telemachus', 'Telemachus', '', "", ['Telemachus'])
    r('dr-price', 'Dr. Price', '', "", ['Dr. Price'])
    r('talleyrand', 'Talleyrand', '', "", ['Talleyrand-Perigord', 'Talleyrand'])
    r('hercules', 'Hercules', '', "", ['Hercules'])
    r('brutus', 'Brutus', '', "", ['Brutus'])
    r('voltaire', 'Voltaire', '', "", ['Voltaire'])
    r('sterne', 'Sterne', '', "", ['Sterne'])
    r('fenelon', 'Fenelon', '', "", ['Fenelon'])
    r('werter', 'Werter', '', "", ['Werter'])
    r('petrarch', 'Petrarch', '', "", ['Petrarch'])
    r('ovid', 'Ovid', '', "", ['Ovid'])
    r('st-paul', 'St. Paul', '', "", ['St. Paul'])
    r('day', 'Mr. Day', '', "", ['Mr. Day'])
    r('macaulay-empress', 'The Empress of Russia', '', "", ['Empress of Russia'])
    r('madame-deon', "Madame d'Eon", '', "", ["Madame d'Eon"])


def bge():
    B = 'beyond-good-and-evil'; r = maker(B)
    r('goethe', 'Goethe', '', "", ['Goethe'])
    r('socrates', 'Socrates', '', "", ['Socrates'])
    r('napoleon', 'Napoleon', '', "", ['Napoleon'])
    r('hegel', 'Hegel', '', "", ['Hegel'])
    r('schumann', 'Robert Schumann', '', "", ['Robert Schumann', 'Schumann'])
    r('mozart', 'Mozart', '', "", ['Mozart'])
    r('beethoven', 'Beethoven', '', "", ['Beethoven'])
    r('weber', 'Weber', '', "", ['Weber'])
    r('marschner', 'Marschner', '', "", ['Marschner'])
    r('mendelssohn', 'Felix Mendelssohn', '', "", ['Felix Mendelssohn', 'Mendelssohn'])
    r('luther', 'Luther', '', "", ['Luther'])
    r('cromwell', 'Cromwell', '', "", ['Cromwell'])
    r('jesus', 'Jesus', '', "", ['Jesus'])
    r('balzac', 'Balzac', '', "", ['Balzac'])
    r('homer', 'Homer', '', "", ['Homer'])
    r('shakespeare', 'Shakespeare', '', "", ['Shakespeare'])
    r('jean-paul', 'Jean Paul', '', "", ['Jean Paul'])
    r('darwin', 'Darwin', '', "", ['Darwin'])
    r('mill', 'John Stuart Mill', '', "", ['John Stuart Mill'])
    r('spencer', 'Herbert Spencer', '', "", ['Herbert Spencer'])
    r('heine', 'Heinrich Heine', '', "", ['Heinrich Heine', 'Heine'])
    r('moliere', 'Moliere', '', "", ['Moliere'])
    r('boscovich', 'Boscovich', '', "", ['Boscovich'])
    r('copernicus', 'Copernicus', '', "", ['Copernicus'])
    r('locke', 'Locke', '', "", ['Locke'])
    r('hume', 'Hume', '', "", ['Hume'])
    r('hobbes', 'Hobbes', '', "", ['Hobbes'])
    r('bacon', 'Bacon', '', "", ['Bacon'])
    r('carlyle', 'Carlyle', '', "", ['Carlyle'])
    r('spinoza', 'Spinoza', '', "", ['Spinoza', 'Spinozas'])
    r('giordano-bruno', 'Giordano Bruno', '', "", ['Giordano Bruno', 'Giordano Brunos'])
    r('bayle', 'Bayle', '', "", ['Bayle'])
    r('voltaire', 'Voltaire', '', "", ['Voltaire'])
    r('diderot', 'Diderot', '', "", ['Diderot'])
    r('lessing', 'Lessing', '', "", ['Lessing'])
    r('renan', 'Ernest Renan', '', "", ['Ernest Renan', 'Renan'])
    r('sainte-beuve', 'Sainte-Beuve', '', "", ['Sainte-Beuve'])
    r('caesar-borgia', 'Caesar Borgia', '', "", ['Caesar Borgia'])
    r('caesar', 'Caesar', '', "", ['Caesar'])
    r('alcibiades', 'Alcibiades', '', "", ['Alcibiades'])
    r('leonardo', 'Leonardo da Vinci', '', "", ['Leonardo da Vinci'])
    r('frederick', 'Frederick the Second', 'The Hohenstaufen', "", ['Frederick the Second'])
    r('frederick-the-great', 'Frederick the Great', '', "", ['Frederick the Great'])
    r('eugen-duhring', 'Eugen Duhring', '', "", ['Eugen Duhring'])
    r('hartmann', 'Eduard von Hartmann', '', "", ['Eduard von Hartmann'])
    r('montaigne', 'Montaigne', '', "", ['Montaigne'])
    r('dante', 'Dante', '', "", ['Dante'])
    r('george-sand', 'George Sand', '', "", ['George Sand', 'Sand'])
    r('madame-roland', 'Madame Roland', '', "", ['Madame Roland'])
    r('madame-de-stael', 'Madame de Stael', '', "", ['Madame de Stael'])
    r('madame-de-guyon', 'Madame de Guyon', '', "", ['Madame de Guyon'])
    r('madame-de-lambert', 'Madame de Lambert', '', "", ['Madame de Lambert'])
    r('fichte', 'Fichte', '', "", ['Fichte'])
    r('schelling', 'Schelling', '', "", ['Schelling'])
    r('rousseau', 'Rousseau', '', "", ['Rousseau'])
    r('schiller', 'Schiller', '', "", ['Schiller'])
    r('shelley', 'Shelley', '', "", ['Shelley'])
    r('byron', 'Byron', '', "", ['Byron'])
    r('musset', 'Musset', '', "", ['Musset'])
    r('poe', 'Poe', '', "", ['Poe'])
    r('leopardi', 'Leopardi', '', "", ['Leopardi'])
    r('kleist', 'Kleist', '', "", ['Kleist'])
    r('gogol', 'Gogol', '', "", ['Gogol'])
    r('stendhal', 'Stendhal', 'Henri Beyle', "", ['Henri Beyle', 'Stendhal'])
    r('delacroix', 'Delacroix', '', "", ['Delacroix'])
    r('flaubert', 'Flaubert', '', "", ['Flaubert'])
    r('taine', 'Taine', '', "", ['Taine'])
    r('comte', 'Auguste Comte', '', "", ['Auguste Comte', 'Comte'])
    r('michelet', 'Michelet', '', "", ['Michelet'])
    r('galiani', 'Abbe Galiani', '', "", ['Abbe Galiani', 'Galiani'])
    r('helvetius', 'Helvetius', '', "", ['Helvetius'])
    r('siegfried', 'Siegfried', '', "", ['Siegfried'])
    r('horace', 'Horace', '', "", ['Horace'])
    r('raphael', 'Raphael', '', "", ['Raphael'])
    r('ariadne', 'Ariadne', '', "", ['Ariadne'])
    r('dionysus', 'Dionysus', '', "", ['Dionysus'], kind=D)
    r('zarathustra', 'Zarathustra', '', "", ['Zarathustra'])
    r('epicurus', 'Epicurus', '', "", ['Epicurus'])
    r('descartes', 'Descartes', '', "", ['Descartes'])
    r('leibniz', 'Leibniz', '', "", ['Leibniz'])
    r('hamlet', 'Hamlet', '', "", ['Hamlet'])
    r('circe', 'Circe', '', "", ['Circe'])
    r('ulysses', 'Ulysses', '', "", ['Ulysses'])
    r('nausicaa', 'Nausicaa', '', "", ['Nausicaa'])
    r('petronius', 'Petronius', '', "", ['Petronius'])
    r('aristophanes', 'Aristophanes', '', "", ['Aristophanes'])
    r('buddha', 'Buddha', '', "", ['Buddha'])
    r('heraclitus', 'Heraclitus', '', "", ['Heraclitus'])
    r('empedocles', 'Empedocles', '', "", ['Empedocles'])
    r('machiavelli', 'Machiavelli', '', "", ['Machiavelli'])
    r('augustine', 'St. Augustine', '', "", ['St. Augustine', 'Augustine'])
    r('tacitus', 'Tacitus', '', "", ['Tacitus'])
    r('cagliostro', 'Cagliostro', '', "", ['Cagliostro'])
    r('catalina', 'Catalina', '', "", ['Catalina'])
    r('pericles', 'Pericles', '', "", ['Pericles'])
    r('aristotle', 'Aristotle', '', "", ['Aristotle'])
    r('stoics', 'The Stoics', '', "", ['Stoics'], kind=G)


def treatise():
    B = 'second-treatise'; r = maker(B)
    r('hezekiah', 'Hezekiah', '', "", ['Hezekiah'])
    r('ahaz', 'Ahaz', '', "", ['Ahaz'])
    r('noah', 'Noah', '', "", ['Noah'])
    r('abraham', 'Abraham', '', "", ['Abraham'])
    r('saul', 'Saul', '', "", ['Saul'])
    r('david', 'David', '', "", ['king David', 'David'])
    r('samuel', 'Samuel', '', "", ['Samuel'])
    r('king-james', 'King James', 'The first', "", ['King James', 'king James'])
    r('cain', 'Cain', '', "", ['Cain'])
    r('abel', 'Abel', '', "", ['Abel'])
    r('eve', 'Eve', '', "", ['Eve'])
    r('esau', 'Esau', '', "", ['Esau'])
    r('garcilasso', 'Garcilasso de la Vega', '', "", ['Garcilasso de la Vega'])
    r('jephtha', 'Jephtha', '', "", ['Jephtha', 'Jeptha'])
    r('acosta', 'Josephus Acosta', '', "", ['Josephus Acosta'])
    r('salmanasser', 'Salmanasser', '', "", ['Salmanasser'])
    r('xerxes', 'Xerxes', '', "", ['Xerxes'])
    r('jotham', 'Jotham', '', "", ['Jotham'])
    r('gideon', 'Gideon', '', "", ['Gideon'])
    r('abimelech', 'Abimelech', '', "", ['Abimelech'])
    r('william-the-conqueror', 'William', 'The Conqueror', "", ['William'], only_paragraphs={(16, 3)})
    r('hingar', 'Hingar', '', "", ['Hingar'])
    r('hubba', 'Hubba', '', "", ['Hubba'])
    r('buchanan', 'Buchanan', '', "", ['Buchanan'])
    r('bilson', 'Bilson', '', "", ['Bilson'])
    r('bracton', 'Bracton', '', "", ['Bracton'])
    r('fortescue', 'Fortescue', '', "", ['Fortescue'])
    r('barclay', 'Barclay', '', "", ['Barclay'])
    r('locke', 'Mr. Locke', 'The author', "", ['Mr. Locke'])
    r('ulysses', 'Ulysses', '', "", ['Ulysses'])
    r('polyphemus', 'Polyphemus', '', "", ['Polyphemus'])
    r('nero', 'Nero', '', "", ['Nero'])
    r('caligula', 'Caligula', '', "", ['Caligula'])


def genealogy():
    B = 'genealogy-of-morals'; r = maker(B)
    add_aliases(B, 'immanuel-kant', ['Kant'])
    r('luther', 'Luther', '', "", ['Luther'])
    r('calvin', 'Calvin', '', "", ['Calvin'])
    r('plato', 'Plato', '', "", ['Plato'])
    r('wagner', 'Richard Wagner', '', "", ['Richard Wagner', 'Wagner'])
    r('parsifal', 'Parsifal', '', "", ['Parsifal'])
    r('jesus', 'Jesus', 'Of Nazareth', "", ['Jesus of Nazareth', 'Jesus'])
    r('buddha', 'Buddha', '', "", ['Buddha'])
    r('rahoula', 'Râhoula', "Buddha's son", "", ['Râhoula'])
    r('stendhal', 'Stendhal', '', "", ['Stendhal'])
    r('spencer', 'Herbert Spencer', '', "", ['Herbert Spencer', 'Spencer'])
    r('huxley', 'Huxley', '', "", ['Huxley'])
    r('mirabeau', 'Mirabeau', '', "", ['Mirabeau'])
    r('dante', 'Dante', '', "", ['Dante'])
    r('peter', 'Peter', 'The fisher', "", ['Peter'], only_paragraphs={(2, 35)})
    r('paul', 'Paul', 'The tent-maker', "", ['Paul'], exclude_paragraphs=chapters(B, 1))
    r('mary', 'Mary', '', "", ['Mary'])
    r('heracles', 'Heracles', '', "", ['Heracles'])
    r('zeus', 'Zeus', '', "", ['Zeus'], kind=D)
    r('jove', 'Jove', '', "", ['Jove'], kind=D)
    r('adam', 'Adam', '', "", ['Adam'])
    r('zarathustra', 'Zarathustra', '', "", ['Zarathustra'])
    r('feuerbach', 'Feuerbach', '', "", ['Feuerbach'])
    r('homer', 'Homer', '', "", ['Homer'])
    r('hesiod', 'Hesiod', '', "", ['Hesiod'])
    r('herwegh', 'Herwegh', '', "", ['Herwegh'])
    r('hegel', 'Hegel', '', "", ['Hegel'])
    r('geulincx', 'Geulincx', '', "", ['Geulincx'])
    r('thomas-moore', 'Thomas Moore', '', "", ['Thomas Moore'])
    r('gwinner', 'Dr. Gwinner', "Schopenhauer's executor", "", ['Dr. Gwinner', 'Gwinner'])
    r('thayer', 'Thayer', "Beethoven's biographer", "", ['Thayer'])
    r('janssen', 'Janssen', '', "", ['Janssen'])
    r('ranke', 'Leopold Ranke', '', "", ['Leopold Ranke', 'Ranke'])
    r('doudan', 'Xaver Doudan', '', "", ['Xaver Doudan'])
    r('goethe', 'Goethe', '', "", ['Goethe'])
    r('socrates', 'Socrates', '', "", ['Socrates'])
    r('napoleon', 'Napoleon', '', "", ['Napoleon'])
    r('tertullian', 'Tertullian', '', "", ['Tertullian'])
    r('aquinas', 'Thomas of Aquinas', '', "", ['Thomas of Aquinas'])
    r('spinoza', 'Spinoza', '', "", ['Spinoza'])
    r('la-rochefoucauld', 'La Rochefoucauld', '', "", ['La Rochefoucauld'])
    r('descartes', 'Descartes', '', "", ['Descartes'])
    r('leibnitz', 'Leibnitz', '', "", ['Leibnitz'])
    r('heracleitus', 'Heracleitus', '', "", ['Heracleitus'])
    r('pascal', 'Pascal', '', "", ['Pascal'])
    r('pericles', 'Pericles', '', "", ['Pericles'])
    r('achilles', 'Achilles', '', "", ['Achilles'])
    r('hafiz', 'Hafiz', '', "", ['Hafiz'])
    r('epicurus', 'Epicurus', '', "", ['Epicurus'])
    r('shakespeare', 'Shakespeare', '', "", ['Shakespeare'])
    r('byron', 'Lord Byron', '', "", ['Lord Byron', 'Byron'])
    r('beethoven', 'Beethoven', '', "", ['Beethoven'])
    r('renan', 'Renan', '', "", ['Renan'])
    r('taine', 'Taine', '', "", ['Taine'])
    r('darwin', 'Darwin', '', "", ['Darwin'])
    r('christ', 'Christ', '', "", ['Christ'])
    r('don-quixote', 'Don Quixote', '', "", ['Don Quixote'])
    r('dostoiewsky', 'Dostoiewsky', '', "", ['Dostoiewsky', 'Dostoievsky', 'Dostoevsky'])
    r('sir-christopher', 'Sir Christopher', 'In Shakespeare', "", ['Sir Christopher'])


def fear():
    B = 'fear-and-trembling'; r = maker(B)
    # Isaac: first-gen bound only "Take Isaac" x2
    drop_mentions(B, 'isaac', text='Take Isaac')
    add_aliases(B, 'isaac', ['Isaac'])
    # Sarah: the Tobias passage is Raguel's daughter
    tobias = paras_with(B, r'Tobias|Raguel|Asmodeus|Book of Tobit') & chapters(B, 7)
    drop_mentions(B, 'sarah', paragraphs=tobias)
    r('sarah-daughter-of-raguel', 'Sarah', 'Daughter of Raguel', "The bride of Tobias, in the Book of Tobit.", ['Sarah'], only_paragraphs=tobias, role='supporting')
    r('tobias', 'Tobias', '', "", ['Tobias'], role='supporting')
    r('raguel', 'Raguel', '', "", ['Raguel'])
    r('edna', 'Edna', '', "", ['Edna'])
    r('the-merman', 'The Merman', '', "The seducer of Agnete in the legend.", ['Merman'], role='supporting')
    r('agamemnon', 'Agamemnon', '', "", ['Agamemnon'], role='supporting')
    r('iphigenia', 'Iphigenia', '', "", ['Iphigenia'], role='supporting')
    r('clytemnestra', 'Clytemnestra', '', "", ['Clytemnestra'])
    r('calchas', 'Calchas', '', "", ['Calchas'])
    r('achilles', 'Achilles', '', "", ['Achilles'])
    r('jephthah', 'Jephthah', '', "", ['Jephthah'], role='supporting')
    r('brutus', 'Brutus', '', "", ['Brutus'], role='supporting')
    r('faust', 'Faust', '', "", ['Faust'], role='supporting')
    r('margaret', 'Margaret', "Faust's Gretchen", "", ['Margaret'])
    r('mephistopheles', 'Mephistopheles', '', "", ['Mephistopheles'])
    r('virgin-mary', 'Mary', 'The Virgin', "", ['Virgin Mary', 'Mary'])
    r('hagar', 'Hagar', '', "", ['Hagar'])
    r('jacob', 'Jacob', '', "", ['Jacob'])
    r('laban', 'Laban', '', "", ['Laban'])
    r('moses', 'Moses', '', "", ['Moses'])
    r('christ', 'Christ', '', "", ['Christ'])
    r('judas', 'Judas', '', "", ['Judas'])
    r('shakespeare', 'Shakespeare', '', "", ['Shakespeare'])
    r('gloster', 'Gloster', 'Afterwards Richard the Third', "", ['Richard the Third', 'Gloster'])
    r('edward-iv', 'King Edward IV', '', "", ['King Edward IV', 'Edward IV'])
    r('clarence', 'Clarence', '', "", ['Clarence'])
    r('queen-elizabeth', 'Queen Elizabeth', '', "", ['Queen Elizabeth', 'Elizabeth'])
    r('essex', 'Essex', '', "", ['Essex'])
    r('aristotle', 'Aristotle', '', "", ['Aristotle'])
    r('cartesius', 'Cartesius', 'Descartes', "", ['Cartesius', 'Descartes'])
    r('socrates', 'Socrates', '', "", ['Socrates'])
    r('plato', 'Plato', '', "", ['Plato'])
    r('heraclitus', 'Heraclitus', '', "", ['Heraclitus'])
    r('pythagoras', 'Pythagoras', '', "", ['Pythagoras'])
    r('diogenes-laertius', 'Diogenes', 'Laertius', "", ['Diogenes'])
    r('euripides', 'Euripides', '', "", ['Euripides'])
    r('lessing', 'Lessing', '', "", ['Lessing'])
    r('goethe', 'Goethe', '', "", ['Goethe'])
    r('rousseau', 'Rousseau', '', "", ['Rousseau'])
    r('boileau', 'Boileau', '', "", ['Boileau'])
    r('daub', 'Daub', '', "", ['Daub'])
    r('jakel', 'Master Jakel', '', "", ['Master Jakel', 'Jakel'])
    r('gregorius', 'Gregorius Riminensis', '', "", ['Gregorius Riminensis'])
    r('cumberland', 'Cumberland', "Cumberland's Jew", "", ['Cumberland'])
    r('bluebeard', 'Bluebeard', '', "", ['Bluebeard'])
    r('orpheus', 'Orpheus', '', "", ['Orpheus'])
    r('psyche', 'Psyche', '', "", ['Psyche'])
    r('amor', 'Amor', '', "", ['Amor'], kind=D)
    r('longus', 'Longus', '', "", ['Longus'])


def meditations():
    B = 'meditations'; r = maker(B)
    other_alex = card_paras(B, 'alexander-grammarian') | card_paras(B, 'alexander-platonist')
    r('alexander-the-great', 'Alexander', 'The Great', "", ['Alexander'], exclude_paragraphs=other_alex)
    r('caius-caesar', 'Caius Caesar', 'Julius Caesar', "", ['Caius Caesar', 'Caesar'])
    r('pompeius', 'Pompeius', '', "", ['Pompeius'])
    r('philippus', 'Philippus', '', "", ['Philippus'])
    r('croesus', 'Croesus', '', "", ['Croesus'])
    r('zeus', 'Zeus', '', "", ['Zeus'], kind=D)
    r('apollo', 'Apollo', '', "", ['Apollo'], kind=D)
    r('aesculapius', 'Aesculapius', '', "", ['Aesculapius'], kind=D)
    r('clotho', 'Clotho', 'One of the Fates', "", ['Clotho'], kind=D)
    r('cecrops', 'Cecrops', '', "", ['Cecrops'])
    r('thrasea', 'Thrasea', '', "", ['Thrasea'])
    r('helvidius', 'Helvidius', '', "", ['Helvidius'])
    r('cato', 'Cato', '', "", ['Cato'])
    r('dion', 'Dion', '', "", ['Dion'])
    r('brutus', 'Brutus', '', "", ['Brutus'])
    r('phalaris', 'Phalaris', '', "", ['Phalaris'])
    r('nero', 'Nero', '', "", ['Nero'])
    r('agathon', 'Agathon', '', "", ['Agathon'])
    r('camillus', 'Camillus', '', "", ['Camillus'])
    r('caeso', 'Caeso', '', "", ['Caeso'])
    r('volesus', 'Volesus', '', "", ['Volesus'])
    r('leonnatus', 'Leonnatus', '', "", ['Leonnatus'])
    r('scipio', 'Scipio', '', "", ['Scipio'])
    r('augustus', 'Augustus', '', "", ['Augustus'])
    r('hadrianus', 'Hadrianus', '', "", ['Hadrianus', 'Hadrian'])
    r('vespasian', 'Vespasian', '', "", ['Vespasian'])
    r('trajan', 'Trajan', '', "", ['Trajan'])
    r('tiberius', 'Tiberius', '', "", ['Tiberius'])
    r('crates', 'Crates', '', "", ['Crates'])
    r('xenocrates', 'Xenocrates', '', "", ['Xenocrates'])
    r('menippus', 'Menippus', '', "", ['Menippus'])
    r('monimus', 'Monimus', 'The Cynic', "", ['Monimus'])
    r('telauges', 'Telauges', '', "", ['Telauges'])
    r('leon', 'Leon', 'Of Salamis', "", ['Leon'])
    r('lucilla', 'Lucilla', '', "", ['Lucilla'])
    r('secunda', 'Secunda', '', "", ['Secunda'])
    r('celer', 'Celer', '', "", ['Celer'])
    r('epitynchanus', 'Epitynchanus', '', "", ['Epitynchanus'])
    r('diotimus', 'Diotimus', '', "", ['Diotimus'])
    r('faustina', 'Faustina', '', "", ['Faustina'])
    r('charax', 'Charax', '', "", ['Charax'])
    r('demetrius', 'Demetrius', 'The Platonist', "", ['Demetrius'])
    r('eudaemon', 'Eudaemon', '', "", ['Eudaemon'])
    r('agrippa', 'Agrippa', '', "", ['Agrippa'])
    r('areius', 'Areius', '', "", ['Areius'])
    r('maecenas', 'Maecenas', '', "", ['Maecenas'])
    r('panthea', 'Panthea', '', "", ['Panthea'])
    r('fergamus', 'Fergamus', '', "", ['Fergamus'])
    r('chaurias', 'Chaurias', '', "", ['Chaurias'])
    r('eutyches', 'Eutyches', '', "", ['Eutyches'])
    r('hymen', 'Hymen', '', "", ['Hymen'])
    r('euphrates', 'Euphrates', '', "", ['Euphrates'])
    r('eutychion', 'Eutychion', '', "", ['Eutychion'])
    r('silvanus', 'Silvanus', '', "", ['Silvanus'])
    r('alciphron', 'Alciphron', '', "", ['Alciphron'])
    r('tropaeophorus', 'Tropaeophorus', '', "", ['Tropaeophorus'])
    r('satyron', 'Satyron', 'The Socratic', "", ['Satyron'])
    r('xenophon', 'Xenophon', '', "", ['Xenophon'])
    r('crito', 'Crito', '', "", ['Crito'])
    r('perdiccas', 'Perdiccas', '', "", ['Perdiccas'])
    r('xanthippe', 'Xanthippe', '', "", ['Xanthippe'])
    r('empedocles', 'Empedocles', '', "", ['Empedocles'])
    r('lucius-lupus', 'Lucius Lupus', '', "", ['Lucius Lupus'])
    r('catullinus', 'Catullinus', '', "", ['Catullinus', 'Catellinus'])
    r('stertinius', 'Stertinius', '', "", ['Stertinius'])
    r('velius-rufus', 'Velius Rufus', '', "", ['Velius Rufus'])
    r('democritus', 'Democritus', '', "", ['Democritus'])
    r('heraclitus', 'Heraclitus', '', "", ['Heraclitus'])
    r('pythagoras', 'Pythagoras', '', "", ['Pythagoras'])
    r('diogenes', 'Diogenes', '', "", ['Diogenes'])
    r('antisthenes', 'Antisthenes', '', "", ['Antisthenes'])
    r('epicurus', 'Epicurus', '', "", ['Epicurus'])
    r('fabius', 'Fabius', '', "", ['Fabius'])
    r('julianus', 'Julianus', '', "", ['Julianus'])
    r('lepidus', 'Lepidus', '', "", ['Lepidus'])
    r('cadicianus', 'Cadicianus', '', "", ['Cadicianus'])
    r('philistion', 'Philistion', '', "", ['Philistion'])
    r('phoebus', 'Phoebus', '', "", ['Phoebus'])
    r('origanion', 'Origanion', '', "", ['Origanion'])
    r('archimedes', 'Archimedes', '', "", ['Archimedes'])
    r('eudoxus', 'Eudoxus', '', "", ['Eudoxus'])
    r('hipparchus', 'Hipparchus', '', "", ['Hipparchus'])
    r('hippocrates', 'Hippocrates', '', "", ['Hippocrates'])
    r('tandasis', 'Tandasis', '', "", ['Tandasis'])
    r('marcianus', 'Marcianus', '', "", ['Marcianus'])
    r('bacchius', 'Bacchius', '', "", ['Bacchius'])
    r('benedicta', 'Benedicta', '', "", ['Benedicta'])
    r('theodotus', 'Theodotus', '', "", ['Theodotus'])
    r('domitius', 'Domitius', '', "", ['Domitius'])
    r('athenodotus', 'Athenodotus', '', "", ['Athenodotus'])
    r('homer', 'Homer', '', "", ['Homer'])
    r('hesiod', 'Hesiod', '', "", ['Hesiod'])
    r('euripides', 'Euripides', '', "", ['Euripides'])
    r('aristophanes', 'Aristophanes', '', "", ['Aristophanes'])
    r('zeno', 'Zeno', '', "", ['Zeno'])
    r('cleanthes', 'Cleanthes', '', "", ['Cleanthes'])
    r('menander', 'Menander', '', "", ['Menander'])
    r('chabrias', 'Chabrias', '', "", ['Chabrias'])
    r('aristotle', 'Aristotle', '', "", ['Aristotle'])
    r('marcus-aurelius', 'Marcus Aurelius', 'The author', "", ['Marcus Aurelius Antoninus', 'Marcus Aurelius', 'Marcus'])
    r('commodus', 'Commodus', '', "", ['Commodus'])
    r('achilles', 'Achilles', '', "", ['Achilles'])
    r('ulysses', 'Ulysses', '', "", ['Ulysses'])
    r('priam', 'Priam', '', "", ['Priam'])


def magna():
    B = 'magna-carta'; r = maker(B)
    add_aliases(B, 'stephen-langton', ['Stephen archbishop of Canterbury'])
    add_aliases(B, 'master-pandulf', ['Pandulf'])
    r('henry-archbishop-of-dublin', 'Henry', 'Archbishop of Dublin', "", ['Henry archbishop of Dublin', 'Henry'], exclude_paragraphs={(1, 52)})
    r('king-henry', 'King Henry', 'Henry II', "Our father King Henry.", ['King Henry'])
    r('king-richard', 'King Richard', 'Richard I', "Our brother King Richard.", ['King Richard'])
    r('william-bishop-of-london', 'William', 'Bishop of London', "", ['William bishop of London'])
    r('william-bishop-of-coventry', 'William', 'Bishop of Coventry', "", ['William bishop of Coventry'])
    r('william-earl-of-salisbury', 'William', 'Earl of Salisbury', "", ['William earl of Salisbury'])
    r('william-earl-of-warren', 'William', 'Earl of Warren', "", ['William earl of Warren'])
    r('william-earl-of-arundel', 'William', 'Earl of Arundel', "", ['William earl of Arundel'])
    r('peter-bishop-of-winchester', 'Peter', 'Bishop of Winchester', "", ['Peter bishop of Winchester'])
    r('jocelin', 'Jocelin', 'Bishop of Bath and Glastonbury', "", ['Jocelin'])
    r('hugh-de-neville', 'Hugh de Neville', '', "", ['Hugh de Neville'])
    r('john-fitz-hugh', 'John Fitz Hugh', '', "", ['John Fitz Hugh'])
    r('john-marshal', 'John Marshal', '', "", ['John Marshal'])
    r('hugh-bishop-of-lincoln', 'Hugh', 'Bishop of Lincoln', "", ['Hugh'])
    r('walter', 'Walter', 'Bishop of Worcester', "", ['Walter'])
    r('benedict', 'Benedict', 'Bishop of Rochester', "", ['Benedict'])
    r('aymeric', 'Brother Aymeric', 'Master of the Knights Templar', "", ['Brother Aymeric', 'Aymeric'])
    r('alan-de-galloway', 'Alan de Galloway', 'Constable of Scotland', "", ['Alan de Galloway'])
    r('warin-fitz-gerald', 'Warin Fitz Gerald', '', "", ['Warin Fitz Gerald'])
    r('peter-fitz-herbert', 'Peter Fitz Herbert', '', "", ['Peter Fitz Herbert'])
    r('hubert-de-burgh', 'Hubert de Burgh', 'Seneschal of Poitou', "", ['Hubert de Burgh'])
    r('matthew-fitz-herbert', 'Matthew Fitz Herbert', '', "", ['Matthew Fitz Herbert'])
    r('thomas-basset', 'Thomas Basset', '', "", ['Thomas Basset'])
    r('alan-basset', 'Alan Basset', '', "", ['Alan Basset'])
    r('philip-daubeny', 'Philip Daubeny', '', "", ['Philip Daubeny'])
    r('robert-de-roppeley', 'Robert de Roppeley', '', "", ['Robert de Roppeley'])
    r('innocent-iii', 'Pope Innocent III', '', "", ['Pope Innocent III', 'Innocent III'])
    r('gerard-de-ath', 'Gerard de Ath', '', "", ['Gerard de Ath'])
    r('andrew-de-chanceaux', 'Andrew de Chanceaux', '', "", ['Andrew de Chanceaux'])
    r('guy-de-cigogne', 'Guy de Cigogne', '', "", ['Guy de Cigogne'])
    r('engelard-de-cigogne', 'Engelard de Cigogné', '', "", ['Engelard de Cigogné', 'Engelard de Cigogn', 'Engelard'])
    r('geoffrey-de-martigny', 'Geoffrey de Martigny', '', "", ['Geoffrey de Martigny'])
    r('philip-marc', 'Philip Marc', '', "", ['Philip Marc'])
    r('alexander-king-of-scotland', 'Alexander', 'King of Scotland', "", ['Alexander'])
    r('llywelyn', 'Llywelyn', '', "", ['Llywelyn'])


def ethics():
    B = 'nicomachean-ethics'; r = maker(B)
    r('homer', 'Homer', '', "", ['Homer'])
    r('hesiod', 'Hesiod', '', "", ['Hesiod'])
    r('hector', 'Hector', '', "", ['Hector'])
    r('diomed', 'Diomed', '', "", ['Diomed', 'Diomede'])
    r('glaucus', 'Glaucus', '', "", ['Glaucus'])
    r('agamemnon', 'Agamemnon', '', "", ['Agamemnon'])
    r('ulysses', 'Ulysses', '', "", ['Ulysses'])
    r('calypso', 'Calypso', '', "", ['Calypso'])
    r('helen', 'Helen', '', "", ['Helen'])
    r('thetis', 'Thetis', '', "", ['Thetis'])
    r('jupiter', 'Jupiter', '', "", ['Jupiter', 'Jove'], kind=D)
    r('neoptolemus', 'Neoptolemus', '', "", ['Neoptolemus'])
    r('philoctetes', 'Philoctetes', '', "", ['Philoctetes'])
    r('speusippus', 'Speusippus', '', "", ['Speusippus'])
    r('eudoxus', 'Eudoxus', '', "", ['Eudoxus'])
    r('agathon', 'Agathon', '', "", ['Agathon'])
    r('phalaris', 'Phalaris', '', "", ['Phalaris'])
    r('merope', 'Merope', '', "", ['Merope'])
    r('simonides', 'Simonides', '', "", ['Simonides'])
    r('bias', 'Bias', '', "", ['Bias'])
    r('brasidas', 'Brasidas', '', "", ['Brasidas'])
    r('phidias', 'Phidias', '', "", ['Phidias'])
    r('polyclitus', 'Polyclitus', '', "", ['Polyclitus'])
    r('anaxagoras', 'Anaxagoras', '', "", ['Anaxagoras', 'Anexagoras'])
    r('thales', 'Thales', '', "", ['Thales'])
    r('protagoras', 'Protagoras', '', "", ['Protagoras'])
    r('milo', 'Milo', '', "", ['Milo'])
    r('pericles', 'Pericles', '', "", ['Pericles'])
    r('sardanapalus', 'Sardanapalus', '', "", ['Sardanapalus'])
    r('endymion', 'Endymion', '', "", ['Endymion'])
    r('pittacus', 'Pittacus', '', "", ['Pittacus'])
    r('empedocles', 'Empedocles', '', "", ['Empedocles'])
    r('heraclitus', 'Heraclitus', '', "", ['Heraclitus'])
    r('theognis', 'Theognis', '', "", ['Theognis'])
    r('euripides', 'Euripides', '', "", ['Euripides'])
    r('sophocles', 'Sophocles', '', "", ['Sophocles'])
    r('aeschylus', 'Aeschylus', '', "", ['Aeschylus'])
    r('alcmaeon', 'Alcmaeon', '', "", ['Alcmaeon'])
    r('niobe', 'Niobe', '', "", ['Niobe'])
    r('satyrus', 'Satyrus', '', "", ['Satyrus'])
    r('theodectes', 'Theodectes', '', "", ['Theodectes'])
    r('carcinus', 'Carcinus', '', "", ['Carcinus'])
    r('cercyon', 'Cercyon', '', "", ['Cercyon'])
    r('evenus', 'Evenus', '', "", ['Evenus'])
    r('xenophantus', 'Xenophantus', '', "", ['Xenophantus'])
    r('anacharsis', 'Anacharsis', '', "", ['Anacharsis'])
    r('epicharmus', 'Epicharmus', '', "", ['Epicharmus'])
    r('anaxandrides', 'Anaxandrides', '', "", ['Anaxandrides'])
    r('rhadamanthus', 'Rhadamanthus', '', "", ['Rhadamanthus'])
    r('pythagoreans', 'The Pythagoreans', '', "", ['Pythagoreans'], kind=G)
    r('aristotle', 'Aristotle', 'The author', "", ['Aristotle'])


BOOKS = {'aristotle-politics': politics, 'vindication-rights-of-woman': vindication, 'beyond-good-and-evil': bge,
         'second-treatise': treatise, 'genealogy-of-morals': genealogy, 'fear-and-trembling': fear,
         'meditations': meditations, 'magna-carta': magna, 'nicomachean-ethics': ethics}

if __name__ == '__main__':
    for b in (sys.argv[1:] or BOOKS):
        BOOKS[b]()
