#!/usr/bin/env python3
"""Walden: clickable-names pass.

Walden's cast is almost entirely allusion: the neighbours of the woods
(the woodchopper, John Field, the former inhabitants) were already
carded; everything else is people Thoreau cites — Cato, Evelyn, Confucius,
Homer, Sadi — and the mythological figures he reaches for. Minimal cards
for all of them, bound in both editions (non-strict on modern-en, which
sometimes modernises spellings).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from add_histories_helpers import add_entity_excluding as add_e
from add_aliases import add_aliases

BOOK = 'walden'
P = 'person'
D = 'deity'


def r(eid, name, subtitle, body, aliases, kind=P, role='reference', **kw):
    add_e(BOOK, eid, name, subtitle, body, role, kind, aliases, **kw)


def main():
    # aliases on existing cards
    add_aliases(BOOK, 'john-field', ['Field'])
    add_aliases(BOOK, 'hugh-quoil', ['Col. Quoil', 'Quoil'])
    add_aliases(BOOK, 'wyman', ['Wyman the potter', 'Wyman the younger'])
    add_aliases(BOOK, 'brister-freeman', ['Sippio Brister'])

    # the neighbourhood
    r('james-collins', 'James Collins', 'Irish railroad labourer', "Sold Thoreau his shanty for boards.", ['James Collins', 'Collins', 'James'], role='supporting')
    r('mrs-c', 'Mrs. C.', "James Collins's wife", "Showed Thoreau the shanty from the inside.", ['Mrs. C.'])
    r('seeley', 'Seeley', 'Irish neighbour', "Carted off the nails and staples from the shanty.", ['Seeley'])
    r('patrick', 'Patrick', '', "The young Irishman who informed on Seeley.", ['Patrick'])
    r('hollowell', 'The Hollowell place', 'The farm Thoreau nearly bought', "", ['Hollowell'])
    r('mr-coleman', 'Mr. Coleman', 'Agricultural reporter', "Author of the state agricultural reports.", ['Mr. Coleman', 'Coleman'])
    r('mr-balcom', 'Mr. Balcom', 'Young architect', "Designs the house on the back of his Vitruvius.", ['Mr. Balcom', 'Balcom'])
    r('spaulding', 'Spaulding', '', "Whose furniture Thoreau cannot tell from a cart-load of empty boxes.", ['Spaulding'])
    r('bose', 'Bose', 'A village dog', "", ['Bose'])
    r('duncan-ingraham', 'Duncan Ingraham', 'Esquire', "Cato's master, who built him a house in Walden Woods.", ['Duncan Ingraham'])
    r('squire-cummings', 'Squire Cummings', '', "Brister Freeman's former master.", ['Squire Cummings'])
    r('breed', 'Breed', 'Former inhabitant', "Whose hut burned a dozen years before.", ['Breed'])
    r('nutting', 'Nutting', 'Former inhabitant', "Lived by the lilac bushes; Sam Nutting hunted bears on Fair Haven Ledges.", ['Sam Nutting', 'Nutting'])
    r('le-grosse', 'Le Grosse', 'Former inhabitant', "", ['Le Grosse'])
    r('burgoyne', 'Burgoyne', "Nutting's fox-hound", "", ['Burgoyne'])
    r('stratton', 'The Strattons', 'Old Concord family', "Hezekiah Stratton, sergeant in the old French war, kept the ledger with the wild-cat skin.", ['Hezekiah Stratton', 'Stratton'])
    r('codman', 'Codman', '', "The Codman place.", ['Codman'])
    r('gilian-baker', 'Gilian Baker', '', "At whose farm-house the winged cat lived.", ['Mr. Gilian Baker', 'Gilian Baker'])
    r('flint', 'Flint', 'Farmer', "The unclean and stupid farmer for whom Flint's Pond is named.", ['Farmer Flint', 'Flint'])
    r('moore', 'Moore of Moore Hill', "The country's champion", "", ['Moore'])
    r('buttrick', 'Buttrick', 'Major at Concord Fight', "'Fire! for God's sake fire!'", ['Buttrick'])
    r('luther-blanchard', 'Luther Blanchard', 'Wounded at Concord Fight', "", ['Luther Blanchard'])
    r('davis', 'Davis', 'Killed at Concord Fight', "", ['Davis'])
    r('hosmer', 'Hosmer', 'Killed at Concord Fight', "", ['Hosmer'])
    r('tom-hyde', 'Tom Hyde', 'The tinker on the gallows', "", ['Tom Hyde'])
    r('jonas', 'Jonas', 'Farm hand', "", ['Jonas'])
    r('solomon-hand', 'Solomon', 'Farm hand', "", ['Solomon'], only_paragraphs={(1, 32)})

    # cited authors and worthies
    r('cato', 'Cato', 'Marcus Porcius Cato', "The Roman farmer-author whose De Re Rustica is Thoreau's 'Cultivator'.", ['Marcus Porcius Cato', 'Old Cato', 'Cato'], exclude_paragraphs={(14, 1)})
    r('evelyn', 'Evelyn', 'John Evelyn', "The diarist and gardener, quoted on soil and compost.", ['Evelyn'])
    r('king-solomon', 'Solomon', '', "", ['Solomon'], only_paragraphs={(1, 15)})
    r('hippocrates', 'Hippocrates', '', "", ['Hippocrates'])
    r('confucius', 'Confucius', '', "", ['Confucius', 'Khoung-tseu'])
    r('kieou-he-yu', 'Kieou-he-yu', 'Dignitary of Wei', "", ['Kieou-he-yu'])
    r('thseng-tseu', 'Thseng-tseu', 'Confucian sage', "", ['Thseng-tseu'])
    r('mencius', 'Mencius', '', "", ['Mencius'])
    r('darwin', 'Darwin', 'The naturalist', "On the Fuegians.", ['Darwin'])
    r('madam-pfeiffer', 'Madam Pfeiffer', 'Traveller', "", ['Madam Pfeiffer'])
    r('henry-viii', 'Henry VIII', '', "", ['Henry VIII.', 'Henry VIII'])
    r('queen-elizabeth', 'Queen Elizabeth', '', "", ['Queen Elizabeth'])
    r('samuel-laing', 'Samuel Laing', '', "On the Laplander's skin dress.", ['Samuel Laing', 'Laing'])
    r('gookin', 'Gookin', 'Superintendent of Indians', "", ['Gookin'])
    r('rumford', 'Rumford', '', "The Rumford fireplace.", ['Rumford'])
    r('chapman', 'Chapman', 'Poet', "", ['Chapman'])
    r('old-johnson', 'Johnson', 'Wonder-Working Providence', "", ['Johnson'])
    r('adam-smith', 'Adam Smith', 'Economist', "", ['Adam Smith'])
    r('ricardo', 'Ricardo', 'Economist', "", ['Ricardo'])
    r('say', 'Say', 'Economist', "", ['Say'], only_paragraphs={(1, 79)})
    r('vitruvius', 'Vitruvius', '', "", ['Vitruvius'])
    r('howard', 'Howard', 'Philanthropist', "", ['Howard'])
    r('penn', 'Penn', '', "", ['Penn'])
    r('mrs-fry', 'Mrs. Fry', '', "", ['Mrs. Fry'])
    r('shakespeare', 'Shakespeare', '', "", ['Shakespeare'])
    r('bacon', 'Bacon', '', "", ['Bacon'], only_paragraphs={(1, 128)})
    r('cromwell', 'Cromwell', '', "", ['Cromwell'])
    r('milton', 'Milton', '', "", ['Milton'])
    r('newton', 'Newton', '', "", ['Newton'])
    r('sheik-sadi', 'Sheik Sadi', 'Of Shiraz', "Author of the Gulistan.", ['Sheik Sadi', 'Sadi'])
    r('raleigh', 'Raleigh', '', "", ['Raleigh'])
    r('wilberforce', 'Wilberforce', '', "", ['Wilberforce'])
    r('damodara', 'Damodara', '', "", ['Damodara'])
    r('mir-camar-uddin-mast', 'Mîr Camar Uddîn Mast', 'Poet', "", ['Mîr Camar Uddîn Mast'])
    r('homer', 'Homer', '', "", ['Homer'])
    r('aeschylus', 'Æschylus', '', "", ['Æschylus', 'Aeschylus'])
    r('virgil', 'Virgil', '', "", ['Virgil'])
    r('plato', 'Plato', '', "", ['Plato'])
    r('zoroaster', 'Zoroaster', '', "", ['Zoroaster'])
    r('jesus-christ', 'Jesus Christ', '', "", ['Jesus Christ', 'Christ'], kind=D)
    r('alexander', 'Alexander', 'The Great', "Carried the Iliad with him.", ['Alexander'])
    r('bonaparte', 'Bonaparte', 'Napoleon', "", ['Bonaparte', 'Napoleon'])
    r('winslow', 'Winslow', 'Governor of Plymouth Colony', "", ['Winslow'])
    r('massasoit', 'Massasoit', '', "", ['Massasoit'])
    r('goffe', 'Goffe', 'Regicide', "", ['Goffe'])
    r('whalley', 'Whalley', 'Regicide', "", ['Whalley'])
    r('paganini', 'Paganini', '', "", ['Paganini'])
    r('kenelm-digby', 'Sir Kenelm Digby', '', "", ['Sir Kenelm Digby', 'Kenelm Digby'])
    r('varro', 'Varro', '', "", ['Varro'])
    r('michael-angelo', 'Michael Angelo', '', "", ['Michael Angelo'])
    r('benvenuto-cellini', 'Benvenuto Cellini', '', "", ['Benvenuto Cellini', 'Cellini'])
    r('guy-faux', 'Guy Faux', '', "", ['Guy Faux'])
    r('kirby-and-spence', 'Kirby and Spence', 'Entomologists', "", ['Kirby and Spence', 'Kirby', 'Spence'])
    r('huber', 'Huber', 'Entomologist', "", ['Huber'])
    r('aeneas-sylvius', 'Æneas Sylvius', '', "", ['Æneas Sylvius', 'Aeneas Sylvius'])
    r('polk', 'Polk', 'President', "", ['Polk'])
    r('webster', 'Webster', 'Daniel Webster', "", ['Webster'])
    r('gilpin', 'William Gilpin', '', "", ['William Gilpin', 'Gilpin'])
    r('michaux', 'Michaux', '', "", ['Michaux'])
    r('goody-blake', 'Goody Blake', "Wordsworth's ballad", "", ['Goody Blake'])
    r('harry-gill', 'Harry Gill', "Wordsworth's ballad", "", ['Harry Gill'])
    r('robinhood', 'Robinhood', '', "", ['Robinhood', 'Robin Hood'])
    r('davenant', 'Davenant', 'Gondibert', "", ['Davenant'])
    r('chalmers', 'Chalmers', 'English poetry collection', "", ['Chalmers'])
    r('chaucer', 'Chaucer', '', "", ['Chaucer'])
    r('grinnell', 'Mr. Grinnell', '', "", ['Mr. Grinnell', 'Grinnell'])
    r('franklin', 'Franklin', 'Lost explorer', "", ['Franklin'])
    r('mungo-park', 'Mungo Park', '', "", ['Mungo Park'])
    r('lewis-and-clarke', 'Lewis and Clarke', '', "", ['Lewis and Clarke'])
    r('frobisher', 'Frobisher', '', "", ['Frobisher'])
    r('symmes', 'Symmes', '', "Symmes' Hole.", ['Symmes'])
    r('mirabeau', 'Mirabeau', '', "", ['Mirabeau'])
    r('kouroo-artist', 'The artist of Kouroo', '', "Who strove after perfection and made a staff while the ages passed.", ['artist in the city of Kouroo'])
    r('nebuchadnezzar', 'Nebuchadnezzar', '', "", ['Nebuchadnezzar'])
    r('chanticleer', 'Chanticleer', '', "", ['Chanticleer'])
    r('sardanapalus', 'Sardanapalus', '', "", ['Sardanapalus'])
    r('croesus', 'Crœsus', '', "", ['Crœsus', 'Croesus'])
    r('jonathan', 'Jonathan', 'Brother Jonathan', "", ['Jonathan'])
    r('john-brother', 'John', 'John Bull', "", ['John'], only_paragraphs={(18, 23)})

    # myth and scripture
    r('adam', 'Adam', '', "", ['Adam'], exclude_paragraphs={(1, 79)})
    r('eve', 'Eve', '', "", ['Eve'])
    r('deucalion', 'Deucalion', '', "", ['Deucalion'])
    r('pyrrha', 'Pyrrha', '', "", ['Pyrrha'])
    r('hercules', 'Hercules', '', "", ['Hercules'])
    r('iolas', 'Iolas', '', "", ['Iolas', 'Iolaus'])
    r('achilles', 'Achilles', '', "", ['Achilles'])
    r('patroclus', 'Patroclus', '', "", ['Patroclus'])
    r('theseus', 'Theseus', '', "", ['Theseus'])
    r('hector', 'Hector', '', "", ['Hector'])
    r('menoetius', 'Menœtius', '', "", ['Menœtius'])
    r('peleus', 'Peleus', '', "", ['Peleus'])
    r('ulysses', 'Ulysses', '', "", ['Ulysses'])
    r('orpheus', 'Orpheus', '', "", ['Orpheus'])
    r('sirens', 'The Sirens', '', "", ['Sirens'])
    r('aurora', 'Aurora', 'Goddess of dawn', "", ['Aurora'], kind=D)
    r('memnon', 'Memnon', '', "", ['Memnon'])
    r('hygeia', 'Hygeia', '', "", ['Hygeia'], kind=D)
    r('aesculapius', 'Æsculapius', '', "", ['Æsculapius', 'Aesculapius'], kind=D)
    r('hebe', 'Hebe', '', "", ['Hebe'], kind=D)
    r('juno', 'Juno', '', "", ['Juno'], kind=D)
    r('jupiter', 'Jupiter', '', "", ['Jupiter', 'Jove'], kind=D)
    r('minerva', 'Minerva', '', "", ['Minerva'], kind=D)
    r('momus', 'Momus', '', "", ['Momus'], kind=D)
    r('ceres', 'Ceres', '', "", ['Ceres'], kind=D)
    r('plutus', 'Plutus', '', "", ['Plutus'], kind=D)
    r('vulcan', 'Vulcan', '', "", ['Vulcan'], kind=D)
    r('terminus', 'Terminus', '', "", ['Terminus'], kind=D)
    r('neptune', 'Neptune', '', "", ['Neptune'], kind=D)
    r('thor', 'Thor', '', "", ['Thor'], kind=D)
    r('atlas', 'Atlas', '', "", ['Atlas'])
    r('antaeus', 'Antæus', '', "", ['Antæus', 'Antaeus'])
    r('phaeton', 'Phaeton', '', "", ['Phaeton'])
    r('admetus', 'Admetus', '', "", ['Admetus'])
    r('cerberus', 'Cerberus', '', "", ['Cerberus'])
    r('nimrod', 'Nimrod', '', "", ['Nimrod'])
    r('robin-goodfellow', 'Robin Goodfellow', '', "", ['Robin Goodfellow'])
    r('william-tell', 'Tell', 'William Tell', "", ['Tell'], only_paragraphs={(4, 10)})
    r('saint-vitus', 'Saint Vitus', '', "", ['Saint Vitus'])
    r('brahma', 'Brahma', '', "", ['Brahma'], kind=D)
    r('vishnu', 'Vishnu', '', "", ['Vishnu'], kind=D)
    r('indra', 'Indra', '', "", ['Indra'], kind=D)
    r('don-carlos', 'Don Carlos', '', "", ['Don Carlos'])
    r('don-pedro', 'Don Pedro', '', "", ['Don Pedro'])


if __name__ == '__main__':
    main()
