import json,sys
from pathlib import Path
sys.path.insert(0,"tools/audio-highlight")
import prodapi
root=Path("artifacts/bella-completion-retry02-2026-09-21");root.mkdir(parents=True,exist_ok=True)
targets=json.loads("[{\"bookId\":\"merchant-of-venice\",\"edition\":\"original-en\",\"chapter\":4},{\"bookId\":\"merchant-of-venice\",\"edition\":\"original-en\",\"chapter\":11},{\"bookId\":\"as-you-like-it\",\"edition\":\"original-en\",\"chapter\":6},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":337},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":312},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":91},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":297},{\"bookId\":\"merchant-of-venice\",\"edition\":\"original-en\",\"chapter\":10},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":316},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":213},{\"bookId\":\"bible\",\"edition\":\"web-en\",\"chapter\":976},{\"bookId\":\"as-you-like-it\",\"edition\":\"original-en\",\"chapter\":15},{\"bookId\":\"bible\",\"edition\":\"web-en\",\"chapter\":413},{\"bookId\":\"henry-iv-part-2\",\"edition\":\"original-en\",\"chapter\":15},{\"bookId\":\"taming-of-the-shrew\",\"edition\":\"original-en\",\"chapter\":4},{\"bookId\":\"taming-of-the-shrew\",\"edition\":\"original-en\",\"chapter\":9},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":115},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":121},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":127},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":156},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":266},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":291},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":300},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":313},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":326},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":39},{\"bookId\":\"war-and-peace\",\"edition\":\"original-en\",\"chapter\":79}]")
targets=[t for t in targets if prodapi.audio_object_size(f'{t["bookId"]}/{t["edition"]}/ch{t["chapter"]}/words.json')[0]==404]
(root/"batch.json").write_text(json.dumps(targets,indent=1))
print(len(targets),"failed chapters retried with stronger recognition and tested prefix fix")
