# -*- coding: utf-8 -*-
"""The Odyssey, Book 10 — modern-English candidate text, frozen draft v1.

Drafted from Samuel Butler's 1900 prose translation (the served
`original-en`, Project Gutenberg #1727) and from nothing else. No other
translation was read, consulted, or recalled; the served `modern-en` being
replaced supplied no wording and was not opened.

Paragraph-aligned one-to-one with the source: 49 paragraphs, in order.

**This file is a MIRROR, not a source.** The text is written in
`scripts/draft_book10_v1.py`, which is the only thing that writes
`book10/candidate-v1.json`; this module exists because
`build_book_package.py` reads the candidate through
`scripts/candidates/bookN.py` to build the review packets, and it is generated
from the frozen candidate so that the two cannot drift. A discrepancy between
this file and `candidate-v1.json` is a defect in whichever was edited by hand.
"""
PARAGRAPHS = [
"“From there we went on to the Aeolian island, where Aeolus son of Hippotas lives, dear to the immortal gods. It is an island that floats, as it were, upon the sea, iron-bound with a wall that girds it. Aeolus has six daughters and six stalwart sons, so he made the sons marry the daughters, and they all live with their dear father and mother, feasting and enjoying every luxury anyone could think of. All day long the air of the house is loaded with the smell of roasting meat till the whole place groans with it, yard and all; but at night they sleep on their well-made bedsteads, each with his own wife between the blankets. These were the people we had now come among.",
"“Aeolus entertained me for a whole month, asking me questions the whole time about Troy, the Argive fleet, and the homecoming of the Achaeans. I told him exactly how everything had happened. When I said I must go, and asked him to help me on my way, he made no difficulty of any kind, but set about it at once. He flayed me a prime ox hide to hold the ways of the roaring winds, and shut them up in the hide as in a sack—for Zeus had made him master of the winds, and he could rouse or still each one of them as he pleased. He put the sack in the ship and bound its mouth so tightly with a silver thread that not even a breath of a side-wind could get out from any quarter. The West wind, which was fair for us, he alone let blow as it chose. But it all came to nothing, for we were lost through our own folly.",
"“Nine days and nine nights we sailed, and on the tenth day our native land showed on the horizon. We got so close in that we could see the stubble fires burning. Then I, being by that time worn out, fell into a light sleep, for I had never let the rudder out of my own hands, so that we might get home the faster. At this the men fell to talking among themselves, and said I was bringing back gold and silver in the sack that Aeolus had given me. ‘Bless my heart,’ one would say, turning to his neighbor, ‘how this man gets honored and makes friends wherever he goes, whatever the city or the country. See what fine prizes he is taking home from Troy, while we, who have traveled just as far as he has, come back with our hands as empty as when we set out—and now Aeolus has given him ever so much more. Quick—let us see what it all is, and how much gold and silver there is in the sack he gave him.’",
"“So they talked, and evil counsels won the day. They loosed the sack, and at once the wind flew howling out and raised a storm that carried us weeping out to sea and away from our own country. Then I woke, and did not know whether to throw myself into the sea or to live on and make the best of it. But I bore it, covered myself up, and lay down in the ship, while the men lamented bitterly as the fierce winds bore our fleet back to the Aeolian island.",
"“When we reached it we went ashore to take in water, and dined close by the ships. Immediately after dinner I took a herald and one of my men and went straight to the house of Aeolus, where I found him feasting with his wife and family. So we sat down as suppliants on the threshold. They were astounded when they saw us, and said, ‘Odysseus, what brings you here? What god has been ill-treating you? We took great pains to help you on your way home to Ithaca, or wherever else it was you wanted to go.’",
"“So they spoke, but I answered sorrowfully, ‘My men have undone me. They, and cruel sleep, have ruined me. My friends, mend me this mischief, for you can if you will.’",
"“I spoke as movingly as I could, but they said nothing, till their father answered, ‘Vilest of mankind, get out of this island at once. I will help no man whom heaven hates. Be off, for you come here as one heaven abhors.’ And with these words he sent me sorrowing from his door.",
"“From there we sailed sadly on till the men were worn out with long and fruitless rowing, for there was no longer any wind to help them. Six days, night and day, we toiled, and on the seventh day we reached the rocky stronghold of Lamus—Telepylus, the city of the Laestrygonians, where the shepherd driving in his sheep and goats to be milked greets the one driving out his flock to feed, and this last answers the greeting. In that country a man who could do without sleep might earn double wages, one as a herdsman of cattle and another as a shepherd, for they work much the same by night as they do by day.",
"“When we reached the harbor we found it landlocked under steep cliffs, with a narrow entrance between two headlands. My captains took all their ships inside and made them fast close to one another, for there was never so much as a breath of wind inside, but always dead calm. I kept my own ship outside, and moored it to a rock at the very end of the point. Then I climbed a high rock to look about me, but could see no sign of man or cattle, only some smoke rising from the ground. So I sent two of my company, with an attendant, to find out what sort of people lived there.",
"“When the men got ashore they followed a level road by which the people draw their firewood down from the mountains into the town, till presently they met a young woman who had come out to fetch water, the daughter of a Laestrygonian named Antiphates. She was going to the fountain Artacia, from which the people bring in their water, and when my men had come close up to her they asked her who the king of that country might be, and over what kind of people he ruled. She directed them to her father’s house, but when they got there they found his wife to be a giantess as huge as a mountain, and they were horrified at the sight of her.",
"“She at once called her husband Antiphates from the place of assembly, and he set about killing my men straight away. He snatched up one of them and began to make his dinner off him then and there, while the other two ran back to the ships as fast as they could. But Antiphates raised a hue and cry after them, and thousands of sturdy Laestrygonians sprang up from every quarter—ogres, not men. They threw huge rocks at us from the cliffs as though they had been mere stones, and I heard the horrible sound of the ships crunching up against one another, and the death cries of my men, as the Laestrygonians speared them like fishes and took them home to eat. While they were killing my men inside the harbor I drew my sword, cut the cable of my own ship, and told my men to row with all their might if they did not want to fare like the rest. So they laid out for their lives, and we were thankful enough when we got into open water out of reach of the rocks they hurled at us. As for the others, there was not one of them left.",
"“From there we sailed sadly on, glad to have escaped death though we had lost our comrades, and came to the Aeaean island, where Circe lives—a great and cunning goddess, own sister to the magician Aeetes, for they are both children of the sun by Perse, who is daughter to Oceanus. We brought our ship into a safe harbor without a word, for some god guided us there, and having landed we lay there for two days and two nights, worn out in body and mind. When the morning of the third day came I took my spear and my sword and went away from the ship to look about me, and see whether I could make out any sign of human handiwork, or hear the sound of voices. Climbing to the top of a high lookout I caught sight of the smoke of Circe’s house rising up out of a dense forest of trees. When I saw this I was uncertain whether, having seen the smoke, to go on at once and find out more, but in the end I judged it best to go back to the ship, give the men their dinners, and send some of them instead of going myself.",
"“When I had nearly got back to the ship some god took pity on my loneliness, and sent a fine antlered stag right into the middle of my path. He was coming down from his pasture in the forest to drink at the river, for the heat of the sun drove him, and as he passed I struck him in the middle of the back. The bronze point of the spear went clean through him, and he lay groaning in the dust till the life went out of him. Then I set my foot on him, drew my spear from the wound, and laid it down. I also gathered rough grass and rushes and twisted them into a fathom or so of good stout rope, with which I bound the four feet of the noble creature together. Having done this I hung him round my neck and walked back to the ship leaning on my spear, for the stag was much too big for me to carry on my shoulder, steadying him with one hand. As I threw him down in front of the ship I called the men, and spoke cheeringly to each of them, man by man. ‘Look here, my friends,’ said I, ‘we are not going to die so much before our time after all, and at any rate we shall not starve so long as we have got something to eat and drink on board.’ At this they uncovered their heads on the seashore and admired the stag, for he was indeed a splendid fellow. Then, when they had feasted their eyes on him long enough, they washed their hands and began to cook him for dinner.",
"“So through the whole long day to the going down of the sun we stayed there eating and drinking our fill, but when the sun went down and it came on dark we camped on the seashore. When the child of morning, rosy-fingered Dawn, appeared, I called a council and said, ‘My friends, we are in very great difficulties, so listen to me. We have no idea where the sun either sets or rises, so we do not even know East from West. I see no way out of it; nevertheless we must try and find one. We are certainly on an island, for I went as high as I could this morning and saw the sea reaching all round it to the horizon. It lies low, but toward the middle I saw smoke rising out of a thick forest of trees.’",
"“Their hearts sank as they heard me, for they remembered how they had been treated by the Laestrygonian Antiphates, and by the savage ogre Polyphemus. They wept bitterly in their dismay, but there was nothing to be got by crying, so I divided them into two companies and set a captain over each. I gave one company to Eurylochus, and took command of the other myself. Then we cast lots in a helmet, and the lot fell on Eurylochus. So he set out with his twenty-two men, and they wept, as did we who were left behind.",
"“When they reached Circe’s house they found it built of cut stones, on a site that could be seen from far off, in the middle of the forest. There were wild mountain wolves and lions prowling all round it—poor bewitched creatures whom she had tamed by her enchantments and drugged into submission. They did not attack my men, but wagged their great tails, fawned on them, and rubbed their noses lovingly against them. As hounds crowd round their master when they see him coming from dinner—for they know he will bring them something—even so did these wolves and lions with their great claws fawn on my men, but the men were terribly frightened at the sight of such strange creatures. Presently they reached the gates of the goddess’s house, and as they stood there they could hear Circe within, singing most beautifully as she worked at her loom, making a web so fine, so soft, and of such dazzling colors as no one but a goddess could weave. At this Polites, whom I valued and trusted more than any other of my men, said, ‘There is someone inside working at a loom and singing most beautifully; the whole place rings with it. Let us call her and see whether she is woman or goddess.’",
"“They called her, and she came down, unfastened the door, and asked them to come in. Thinking no evil, they followed her, all except Eurylochus, who suspected mischief and stayed outside. When she had got them into her house she set them on benches and seats, and mixed them a mess with cheese, honey, meal, and Pramnian wine, but she drugged it with wicked poisons to make them forget their homes. When they had drunk she turned them into pigs with a stroke of her wand, and shut them up in her pigsties. They were like pigs—head, hair, and all, and they grunted just as pigs do; but their minds were the same as before, and they remembered everything.",
"“So they were shut up squealing, and Circe threw them some acorns and beech mast such as pigs eat, while Eurylochus hurried back to tell me the sad fate of our comrades. He was so overcome with dismay that though he tried to speak he could find no words. His eyes filled with tears and he could only sob and sigh, till at last we forced his story out of him and he told us what had happened to the others.",
"“‘We went,’ said he, ‘as you told us, through the forest, and in the middle of it there was a fine house built of cut stones, in a place that could be seen from far off. There we found a woman, or else she was a goddess, working at her loom and singing sweetly. The men shouted to her and called her, and she came down at once, opened the door, and invited us in. The others did not suspect any mischief, so they followed her into the house, but I stayed where I was, for I thought there might be some treachery. From that moment I saw them no more, for not one of them ever came out, though I sat a long time watching for them.’",
"“Then I took my sword of bronze and slung it over my shoulders. I took my bow as well, and told Eurylochus to come back with me and show me the way. But he took hold of me with both his hands and spoke pitifully, saying, ‘Sir, do not force me to go with you, but let me stay here. I know you will not bring one of them back with you, nor even return alive yourself. Let us rather see whether we cannot escape at any rate with the few that are left us, for we may still save our lives.’",
"“‘Stay where you are, then,’ I answered, ‘eating and drinking at the ship, but I must go, for I am most urgently bound to do so.’",
"“With this I left the ship and went up inland. When I had got through the charmed grove and was near the great house of the enchantress Circe, I met Hermes with his golden wand, disguised as a young man in the first bloom of his youth and beauty, with the down just coming on his face. He came up to me and took my hand in his own, saying, ‘My poor unhappy man, where are you going over this mountain top, alone and without knowing the way? Your men are shut up in Circe’s pigsties, like so many wild boars in their lairs. You surely do not imagine you can set them free? I can tell you that you will never get back, and will have to stay there with the rest of them. But never mind, I will protect you and get you out of your difficulty. Take this herb, which is one of great virtue, and keep it about you when you go to Circe’s house. It will be a charm against every kind of mischief.",
"“‘And I will tell you all the wicked witchcraft Circe will try to practice on you. She will mix a mess for you to drink, and she will drug the meal she makes it with, but she will not be able to enchant you, for the virtue of the herb I shall give you will keep her spells from working. I will tell you the whole of it. When Circe strikes you with her wand, draw your sword and spring on her as though you were going to kill her. She will then be frightened, and will ask you to go to bed with her. You must not refuse her point blank, for you want her to set your companions free, and to take good care of you as well, but you must make her swear solemnly by all the blessed gods that she will plot no further mischief against you, or else when she has got you naked she will unman you and make you fit for nothing.’",
"“As he spoke he pulled the herb out of the ground and showed me what it was like. The root was black, while the flower was as white as milk. The gods call it Moly, and mortal men cannot uproot it, but the gods can do whatever they like.",
"“Then Hermes went back to high Olympus, passing over the wooded island, while I fared onward to the house of Circe, and my heart was clouded with care as I walked. When I got to the gates I stood there and called the goddess, and as soon as she heard me she came down, opened the door, and asked me to come in. So I followed her—much troubled in my mind. She set me on a richly decorated seat inlaid with silver, and there was a footstool under my feet, and she mixed a mess in a golden goblet for me to drink; but she drugged it, for she meant me mischief. When she had given it me, and I had drunk it without its enchanting me, she struck me with her wand. ‘There now,’ she cried, ‘be off to the pigsty, and make your lair with the rest of them.’",
"“But I rushed at her with my sword drawn as though I would kill her, and she fell with a loud scream, clasped my knees, and spoke pitifully, saying, ‘Who are you, and where do you come from? From what place and what people? How can it be that my drugs have no power to enchant you? Never yet was any man able to stand so much as a taste of the herb I gave you. You must be spell-proof; surely you can be none other than the bold hero Odysseus, who Hermes always said would come here some day with his ship on his way home from Troy. So be it, then; sheathe your sword and let us go to bed, that we may make friends and learn to trust each other.’",
"“And I answered, ‘Circe, how can you expect me to be friendly with you when you have just been turning all my men into pigs? And now that you have got me here myself, you mean me mischief when you ask me to go to bed with you, and will unman me and make me fit for nothing. I shall certainly not agree to go to bed with you unless you will first take your solemn oath to plot no further harm against me.’",
"“So she swore at once, as I had told her, and when she had finished her oath then I went to bed with her.",
"“Meanwhile her four servants, who are her housemaids, set about their work. They are the children of the groves and fountains, and of the holy waters that run down into the sea. One of them spread a fair purple cloth over a seat and laid a carpet under it. Another brought tables of silver up to the seats, and set them with baskets of gold. A third mixed some sweet wine with water in a silver bowl and put golden cups on the tables, while the fourth brought in water and set it to boil in a great cauldron over a good fire she had lighted. When the water in the cauldron was boiling she poured cold into it till it was just as I liked it, and then she set me in a bath and began washing me from the cauldron about the head and shoulders, to take the weariness and stiffness out of my limbs. As soon as she had done washing me and anointing me with oil, she clothed me in a good cloak and shirt and led me to a richly decorated seat inlaid with silver, and there was a footstool under my feet. A maidservant then brought me water in a beautiful golden ewer and poured it into a silver basin for me to wash my hands, and she drew a clean table beside me. An upper servant brought me bread and offered me many things of what there was in the house, and then Circe asked me to eat, but I would not, and sat without heeding what was in front of me, still moody and suspicious.",
"“When Circe saw me sitting there without eating, and in great grief, she came to me and said, ‘Odysseus, why do you sit like that as though you were dumb, gnawing at your own heart, and refusing both meat and drink? Is it that you are still suspicious? You ought not to be, for I have already sworn solemnly that I will not hurt you.’",
"“And I said, ‘Circe, no man with any sense of what is right can think of either eating or drinking in your house until you have set his friends free and let him see them. If you want me to eat and drink, you must free my men and bring them to me, that I may see them with my own eyes.’",
"“When I had said this she went straight through the court with her wand in her hand and opened the pigsty doors. My men came out like so many prime hogs and stood looking at her, but she went about among them and anointed each with a second drug, and the bristles the bad drug had given them fell off, and they became men again, younger than they were before, and much taller and better looking. They knew me at once, and each of them seized me by the hand and wept for joy, till the whole house was filled with the sound of their hallooing. Circe herself was so sorry for them that she came up to me and said, ‘Odysseus, noble son of Laertes, go back at once to the sea where you have left your ship, and first draw it up on to the land. Then hide all your ship’s gear and property in some cave, and come back here with your men.’",
"“I agreed to this, so I went back to the seashore, and found the men at the ship weeping and wailing most pitifully. When they saw me the silly blubbering fellows began frisking round me as calves break out and gambol round their mothers, when they see them coming home to be milked after they have been feeding all day, and the homestead rings with their lowing. They seemed as glad to see me as though they had got back to their own rugged Ithaca, where they had been born and bred. ‘Sir,’ said the affectionate creatures, ‘we are as glad to see you back as though we had got safe home to Ithaca; but tell us all about the fate of our comrades.’",
"“I spoke comfortingly to them and said, ‘We must draw our ship up on to the land, and hide the ship’s gear with all our property in some cave. Then come with me, all of you, as fast as you can to Circe’s house, where you will find your comrades eating and drinking in the midst of great plenty.’",
"“At this the men would have come with me at once, but Eurylochus tried to hold them back and said, ‘Alas, poor wretches that we are, what will become of us? Do not rush on your ruin by going to the house of Circe, who will turn us all into pigs or wolves or lions, and we shall have to keep guard over her house. Remember how the Cyclops treated us when our comrades went inside his cave, and Odysseus with them. It was all through his sheer folly that those men lost their lives.’",
"“When I heard him I was in two minds whether or not to draw the keen blade that hung by my sturdy thigh and cut his head off, in spite of his being a near relation of my own; but the men interceded for him and said, ‘Sir, if it may be so, let this fellow stay here and mind the ship, but take the rest of us with you to Circe’s house.’",
"“At this we all went inland, and Eurylochus was not left behind after all, but came on too, for he was frightened by the severe reprimand I had given him.",
"“Meanwhile Circe had been seeing that the men who had been left behind were washed and anointed with olive oil. She had also given them woollen cloaks and shirts, and when we came we found them all comfortably at dinner in her house. As soon as the men saw each other face to face and knew one another, they wept for joy and cried aloud till the whole palace rang again. At this Circe came up to me and said, ‘Odysseus, noble son of Laertes, tell your men to leave off crying. I know how much you have all of you suffered at sea, and how badly you have fared among cruel savages on the mainland, but that is over now, so stay here, and eat and drink till you are once more as strong and hearty as you were when you left Ithaca. At present you are weakened both in body and mind; you keep thinking all the time of the hardships you have suffered on your travels, so that you have no cheerfulness left in you.’",
"“So she spoke, and we assented. We stayed with Circe for a whole twelvemonth, feasting on an untold quantity of both meat and wine. But when the year had passed in the waning of moons and the long days had come round, my men called me aside and said, ‘Sir, it is time you began to think about going home, if you are to be spared to see your house and native country at all.’",
"“So they spoke, and I assented. Then through the whole long day to the going down of the sun we feasted our fill on meat and wine, but when the sun went down and it came on dark the men lay down to sleep in the covered cloisters. I, however, after I had got into bed with Circe, entreated her by her knees, and the goddess listened to what I had to say. ‘Circe,’ said I, ‘please keep the promise you made me about helping me on my homeward voyage. I want to get back, and so do my men. They are always pestering me with their complaints as soon as ever your back is turned.’",
"“And the goddess answered, ‘Odysseus, noble son of Laertes, none of you shall stay here any longer if you do not want to, but there is another journey you have got to take before you can sail homeward. You must go to the house of Hades and of dread Persephone, to consult the ghost of the blind Theban prophet Teiresias, whose reason is still unshaken. To him alone has Persephone left his understanding even in death, while the other ghosts flit about aimlessly.’",
"“I was dismayed when I heard this. I sat up in bed and wept, and would gladly have lived no longer to see the light of the sun, but presently, when I was tired of weeping and tossing myself about, I said, ‘And who shall guide me on this voyage—for the house of Hades is a port that no ship can reach.’",
"“‘You will want no guide,’ she answered. ‘Raise your mast, set your white sails, sit quite still, and the North Wind will blow you there of itself. When your ship has crossed the waters of Oceanus, you will reach the fertile shore of Persephone’s country, with its groves of tall poplars and willows that shed their fruit before its time. Beach your ship here on the shore of Oceanus, and go straight on to the dark house of Hades. You will find it near the place where the rivers Pyriphlegethon and Cocytus (which is a branch of the river Styx) flow into Acheron, and you will see a rock near it, just where the two roaring rivers run into one another.",
"“‘When you have reached this spot, as I now tell you, dig a trench a cubit or so in length, breadth, and depth, and pour into it as a drink offering to all the dead, first honey mixed with milk, then wine, and in the third place water—sprinkling white barley meal over the whole. You must also offer many prayers to the poor feeble ghosts, and promise them that when you get back to Ithaca you will sacrifice a barren heifer to them, the best you have, and will load the pyre with good things. More particularly you must promise that Teiresias shall have a black sheep all to himself, the finest in all your flocks.",
"“‘When you have thus entreated the ghosts with your prayers, offer them a ram and a black ewe, bending their heads toward Erebus; but turn away from them yourself as though you were making for the river. At this, many dead men’s ghosts will come to you, and you must tell your men to skin the two sheep you have just killed, and offer them as a burnt sacrifice with prayers to Hades and to Persephone. Then draw your sword and sit there, so as to keep any other poor ghost from coming near the spilt blood before Teiresias has answered your questions. The seer will come to you presently, and will tell you about your voyage—what stages you are to make, and how you are to sail the sea so as to reach your home.’",
"“It was daybreak by the time she had finished speaking, so she dressed me in my shirt and cloak. As for herself, she threw a beautiful light gossamer fabric over her shoulders, fastening it with a golden girdle round her waist, and she covered her head with a mantle. Then I went about among the men everywhere all over the house, and spoke kindly to each of them, man by man: ‘You must not lie sleeping here any longer,’ said I to them, ‘we must be going, for Circe has told me all about it.’ And at this they did as I asked them.",
"“Even so, I did not get them away without mishap. We had with us a young man named Elpenor, not very remarkable for sense or courage, who had got drunk and was lying on the housetop away from the rest of the men, to sleep off his drink in the cool. When he heard the noise of the men bustling about, he jumped up suddenly and forgot all about coming down by the main staircase, so he tumbled right off the roof and broke his neck, and his soul went down to the house of Hades.",
"“When I had got the men together I said to them, ‘You think you are about to start home again, but Circe has explained to me that instead of this we have got to go to the house of Hades and Persephone, to consult the ghost of the Theban prophet Teiresias.’",
"“The men were broken-hearted as they heard me, and threw themselves on the ground groaning and tearing their hair, but they did not mend matters by crying. When we reached the seashore, weeping and lamenting our fate, Circe brought the ram and the ewe, and we made them fast close by the ship. She passed through the midst of us without our knowing it, for who can see the comings and goings of a god, if the god does not wish to be seen?",
]
