"""Manually authored recognition cards for both full English texts of the Aeneid.

The original is Dryden's rhymed couplets; the modern edition is prose. Both run
to twelve books and 544 paragraphs and align paragraph for paragraph, but Dryden
paraphrases freely, so a name present in one edition is sometimes absent from the
other. Those are recorded as omittedEntities, not repaired.

Dryden uses the Roman names throughout, so there is no Greek/Roman split to
handle — but the Latin catalogues reuse names heavily, and the boat race in book
five names four ships after monsters.

Scope: named people, gods, personified powers, named monsters and named peoples.
Places, rivers as geography, mountains, islands and SHIPS are not cast.
"""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

# ------------------------------------------------------------------ principals
for row in [
('aeneas','Aeneas','Son of Venus and Anchises, leader of the Trojan survivors and the man the poem follows from burning Troy to Italy.','Aeneas','central'),
('turnus','Turnus','King of the Rutulians, betrothed to Lavinia before the Trojans came, and Aeneas’s enemy through the second half of the poem.','Turnus','central'),
('dido','Dido','Queen and founder of Carthage, a widow who fled Tyre after her brother murdered her husband. The poem also calls her Eliza.','Dido|Eliza','major'),
('ascanius','Ascanius','Aeneas’s young son, also called Iulus, from whom Rome’s Julian line is traced.','Ascanius|Iulus','major'),
('anchises','Anchises','Aeneas’s father, carried out of Troy on his son’s shoulders.','Anchises','major'),
('venus','Venus','Goddess of love and Aeneas’s mother, who works constantly on his behalf.','Venus|Cytherea|Cyprian','major','deity'),
('juno','Juno','Queen of the gods, who hates the Trojans and drives the whole action against them. The poem also calls her Saturnia.','Juno|Saturnia','major','deity'),
('jove','Jove','King of the gods, who holds to the fate promised the Trojans. The poem also calls him Jupiter and the Thunderer.','Jove|Jupiter|Thunderer','major','deity'),
('latinus','Latinus','King of Latium, Lavinia’s father, who would give his daughter to Aeneas.','Latinus','major'),
('lavinia','Lavinia','Latinus’s only daughter and heiress, promised first to Turnus and then to Aeneas.','Lavinia','major'),
('amata','Amata','Latinus’s queen, who wants Turnus for a son-in-law and is driven mad by the Fury.','Amata','major'),
('evander','Evander','The old Arcadian king at Pallanteum on the future site of Rome, who allies with Aeneas.','Evander','major'),
('pallas','Pallas','Evander’s young son, sent to war under Aeneas’s protection.','','major'),
('pallas-athena','Pallas','Minerva under her Greek by-name; the goddess who helped ruin Troy and whose temple and image recur through the poem.','','major','deity'),
('pallas-ancestor','Pallas','Evander’s great-grandsire, after whom the town of Pallanteum is named.','','reference'),
('mezentius','Mezentius','The exiled Etruscan tyrant, a contemner of the gods, who fights for Turnus.','Mezentius','major'),
('lausus','Lausus','Mezentius’s son, the handsomest of the Italian youth, who dies defending his father.','Lausus','major'),
('camilla','Camilla','The Volscian warrior queen, raised to the hunt and the spear, who leads her troops for Turnus.','Camilla','major'),
('achates','Achates','Aeneas’s closest companion, called faithful throughout.','Achates','major'),
('sibyl','The Sibyl','The prophetess of Cumae, Apollo’s and Diana’s priestess, who guides Aeneas through the underworld. Her name is Deiphobe.','Sibyl|Sibylla|Deiphobe','major'),
('priam','Priam','The old king of Troy, killed at his own altar on the night the city fell.','Priam','major'),
('hector','Hector','Priam’s son and Troy’s great defender, already dead when the poem opens; his ghost warns Aeneas to flee.','Hector','major'),
('creusa','Creusa','Aeneas’s first wife, lost in the sack of Troy; her ghost sends him on to Italy.','Creusa|Creüsa','major'),
('anna','Anna','Dido’s sister and confidante.','Anna','major'),
('nisus','Nisus','A Trojan, son of Hyrtacus, famous for his devotion to Euryalus; the two go out together on the night raid.','','major'),
('euryalus','Euryalus','A Trojan boy of great beauty, Nisus’s inseparable friend.','Euryalus','major'),
('acestes','Acestes','King of the Sicilian Trojans, born of Trojan parentage, who twice receives Aeneas’s fleet.','Acestes','major'),
('mnestheus','Mnestheus','A Trojan captain, founder of the Memmian line, who commands in Aeneas’s absence.','Mnestheus','major'),
('serestus','Serestus','A Trojan captain who walks the camp with Mnestheus. Dryden spells him Serestus once and Seresthus elsewhere.','Serestus|Seresthus','supporting'),
('cloanthus','Cloanthus','A Trojan captain, founder of the Cluentian line, who wins the boat race.','Cloanthus','supporting'),
('ilioneus','Ilioneus','The eldest and gravest of the Trojan captains, who speaks for them to Dido and to Latinus.','Ilioneus','supporting'),
('sergesthus','Sergesthus','A Trojan captain, founder of the Sergian line, whose galley is wrecked on the rocks in the boat race.','Sergesthus','supporting'),
('messapus','Messapus','A Latin captain, Neptune’s son, whom no steel can wound.','Messapus','major'),
('drances','Drances','A Latin elder, a powerful speaker and Turnus’s bitter opponent in council.','Drances','major'),
('juturna','Juturna','Turnus’s sister, a nymph made immortal by Jove, who keeps her brother from his death as long as she can.','Juturna','major','deity'),
('tarchon','Tarchon','The Etruscan chief who brings his people to Aeneas.','Tarchon','supporting'),
('helenus','Helenus','Priam’s son, a seer, now reigning in Epirus with Andromache; he tells Aeneas his route.','Helenus','major'),
('andromache','Andromache','Hector’s widow, taken by Pyrrhus and afterwards married to Helenus.','Andromache','supporting'),
('palinurus','Palinurus','Aeneas’s helmsman, lost overboard off the Italian coast.','Palinurus','major'),
('misenus','Misenus','Aeneas’s trumpeter, once Hector’s, who challenges the sea gods and drowns for it.','Misenus','supporting'),
('sinon','Sinon','The Greek who lets himself be captured and talks Troy into taking in the horse.','Sinon','major'),
('laocoon','Laocoon','Neptune’s priest at Troy, who warns against the horse and is killed with his sons by serpents. The modern edition spells him Laocoön.','Laocoon|Laocoön','major'),
('pyrrhus','Pyrrhus','Achilles’ son, who kills Priam at the altar; also called Neoptolemus.','Pyrrhus|Neoptolemus','supporting'),
('ulysses','Ulysses','The Greek whose cunning the Trojans blame for their ruin; the poem also calls him Ithacus.','Ulysses|Ithacus','supporting'),
('achilles','Achilles','The greatest of the Greeks at Troy, dead before the poem begins; also called Pelides.','Achilles|Pelides','supporting'),
('diomede','Diomede','A Greek captain at Troy, now settled in Italy, who refuses to join the war against Aeneas. The poem spells him Diomede and Diomedes.','Diomede|Diomedes','supporting'),
('aeolus','Aeolus','King of the winds, who looses the storm at Juno’s request.','Aeolus','supporting','deity'),
('neptune','Neptune','God of the sea, who calms the storm and later demands one life for the fleet’s safe passage.','Neptune','major','deity'),
('mercury','Mercury','The messenger god, sent to move Aeneas out of Carthage. The poem also calls him Cyllenius and, in the modern edition, Hermes.','Mercury|Cyllenius|Hermes','supporting','deity'),
('iris','Iris','Juno’s messenger, who comes down on the rainbow.','Iris','supporting','deity'),
('alecto','Alecto','The Fury Juno raises out of hell to break the peace.','Alecto','major','deity'),
('vulcan','Vulcan','The smith of the gods, who forges Aeneas’s shield at Venus’s asking. Called the Lemnian god and Mulciber.','Vulcan|Mulciber','supporting','deity'),
('apollo','Apollo','God of prophecy and archery, whose oracles direct the Trojans; called Phoebus and the Delian god.','Apollo|Phoebus','major','deity'),
('diana','Diana','Goddess of the hunt and the moon; called Phoebe, Trivia and Cynthia.','Diana|Phoebe|Trivia|Cynthia','supporting','deity'),
]:add(*row)

# ------------------------------------------------------------------------ gods
for row in [
('mars','Mars','God of war.','Mars','supporting','deity'),
('minerva','Minerva','Goddess of war and craft; the poem more often calls her Pallas.','Minerva','supporting','deity'),
('saturn','Saturn','The old god who ruled Latium in the golden age, Jove’s father.','Saturn','reference','deity'),
('pluto','Pluto','King of the dead, whose palace Aeneas must visit.','Pluto','reference','deity'),
('proserpine','Proserpine','Queen of the dead, whose golden bough Aeneas must carry.','Proserpine','supporting','deity'),
('hecate','Hecate','The threefold goddess of the crossroads, invoked in Dido’s rites.','Hecate','reference','deity'),
('ceres','Ceres','Goddess of the harvest, whose ruined temple is the Trojans’ meeting point.','Ceres','reference','deity'),
('bacchus','Bacchus','God of wine, invoked at the Carthaginian feast.','Bacchus','reference','deity'),
('cybele','Cybele','The mother of the gods, whose pines become Aeneas’s ships.','Cybele','reference','deity'),
('vesta','Vesta','Goddess of the hearth, whose relics Aeneas carries out of Troy.','Vesta','reference','deity'),
('latona','Latona','Mother of Apollo and Diana.','Latona','reference','deity'),
('aurora','Aurora','The dawn goddess, who leaves her saffron bed each morning.','Aurora','supporting','deity'),
('boreas','Boreas','The north wind.','Boreas','reference','deity'),
('eurus','Eurus','The east wind, who drives three ships onto the shoals.','Eurus','reference','deity'),
('triton','Triton','A sea god who heaves the stranded ships off the rocks.','Triton','reference','deity'),
('nereids','The Nereids','The sea nymphs; Aeneas’s ships are turned into them.','Nereids','reference','group'),
('cymothoe','Cymothoe','A sea nymph who helps free the grounded ships.','Cymothoe','reference','deity'),
('doto','Doto','A sea nymph, named when the ships are promised her shape.','Doto','reference','deity'),
('harpies','The Harpies','The foul bird-women of the Strophades, who befoul the Trojans’ meal.','Harpies','supporting','group'),
('celaeno','Celaeno','The Harpies’ leader, who prophesies that hunger will make the Trojans eat their tables.','Celaeno','supporting','deity'),
('charon','Charon','The ferryman of the dead.','Charon','supporting','deity'),
('cerberus','Cerberus','The three-headed dog at the gate of the underworld.','Cerberus','supporting','animal'),
('furies','The Furies','The avenging sisters of hell; the poem also names them the Dirae.','Furies|Dirae','supporting','group'),
('fame','Fame','Rumour personified, the swiftest of evils, who grows as she goes and spreads the news of Dido and Aeneas.','Fame','supporting','personification'),
('hymen','Hymen','The god of marriage, invoked for the union in the cave.','Hymen','reference','deity'),
('faunus','Faunus','A god of the Latin woods, Latinus’s father.','Faunus','supporting','deity'),
('picus','Picus','Faunus’s father, a king turned into a bird, whose image stands in Latinus’s hall.','Picus','reference'),
('marica','Marica','A Laurentian nymph, Latinus’s mother.','Marica','reference','deity'),
('janus','Janus','The two-faced god whose gates stand open in war.','Janus','reference','deity'),
('quirinus','Quirinus','Romulus under his divine name.','Quirinus','reference','deity'),
('bellona','Bellona','The war goddess, who leads the bride to her wedding.','Bellona','reference','deity'),
('feronia','Feronia','A goddess whose grove and temple stand by Lake Ciminius.','Feronia','reference','deity'),
('carmenta','Carmenta','Evander’s mother, a prophetess who foretold the Roman race.','Carmenta','reference','deity'),
('tiberinus','The river god Tiber','The river of Latium, who rises in a dream to tell Aeneas he has reached his promised land.','','supporting','deity'),
('atlas','Atlas','The Titan whose head sustains the sky; Mercury’s grandfather and Dardanus’s ancestor.','Atlas','reference','deity'),
('maia','Maia','Mercury’s mother, Atlas’s daughter.','Maia','reference','deity'),
('chaos','Chaos','A power of the world below, invoked in Dido’s rites.','Chaos','reference','deity'),
('erebus','Erebus','The darkness of the world below, invoked as a power.','Erebus','reference','deity'),
('somnus','Sleep','The god who slides down to Palinurus at the helm.','','supporting','personification'),
('genius','placeholder','unused','',''),
('muses','The Muses','The goddesses of song, called on to open the catalogue of Italian chiefs.','Muses|Muse','supporting','group'),
('erato','Erato','The Muse invoked at the poem’s second opening.','Erato','reference','deity'),
('parcae','The Fates','The sisters who spin and cut the thread of every life.','Fates','supporting','group'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# --------------------------------------------------------- Trojans and allies
for row in [
('abas-trojan','Abas','A Trojan captain whose ship is disabled in the opening storm.','',''),
('abas-greek','Abas','A Greek whose brazen shield Aeneas hung on the temple door at Actium.','',''),
('abas-etruscan','Abas','An Etruscan captain in Aeneas’s alliance, killed by Mezentius.','',''),
('orontes','Orontes','Captain of the Lycian ship, lost with all hands in the storm.','Orontes'),
('gyas','Gyas','A Trojan captain, who commands the Chimaera in the boat race and loses it by temper.','',''),
('gyas-italian','Gyas','An Italian of monstrous bulk, killed by Aeneas.','',''),
('lycus-trojan','Lycus','A Trojan captain given up for lost after the storm.','',''),
('lycus-tower','Lycus','A young Trojan who escapes the burning tower and is run down by Turnus.','',''),
('amycus-trojan','Amycus','A Trojan captain given up for lost after the storm.','',''),
('amycus-huntsman','Amycus','A Trojan huntsman, skilled in poisoned darts, killed by Turnus in the camp.','',''),
('amycus-horseman','Amycus','An Italian whom Turnus throws from his horse, one of two brothers killed together.','',''),
('alethes','Alethes','The oldest of the Trojan counsellors, who blesses Nisus and Euryalus.','Alethes'),
('capys','Capys','A Trojan captain.','',''),
('capys-alban','Capys','An Alban king in the parade of Aeneas’s descendants.','',''),
('antheus','Antheus','A Trojan captain.','Antheus'),
('caicus','Caicus','A Trojan captain.','Caicus'),
('bitias-carthage','Bitias','A Tyrian lord at Dido’s feast, the first to take up the challenge of the cup.','',''),
('bitias-trojan','Bitias','A giant Trojan, son of Alcanor and the nymph Hiera, who opens the camp gate and dies for it.','',''),
('pandarus-trojan','Pandarus','A giant Trojan, Bitias’s brother, who shuts Turnus inside the camp and is killed by him.','',''),
('pandarus-lycian','Pandarus','The Lycian archer who broke the truce at Troy, named as Eurytion’s brother.','',''),
('alcanor-father','Alcanor','Father of the giant brothers Pandarus and Bitias.','',''),
('alcanor-italian','Alcanor','An Italian who reaches out to save his wounded brother and is maimed by Aeneas.','',''),
('hiera','Hiera','The nymph who bore Pandarus and Bitias on Ida.','Hiera','reference'),
('helymus','Helymus','A Sicilian of Acestes’ following who runs in the foot race.','Helymus'),
('panopes','Panopes','A Sicilian huntsman of Acestes’ following.','Panopes'),
('salius','Salius','An Acarnanian in Acestes’ following who is tripped in the foot race and claims the prize.','Salius'),
('patron','Patron','An Arcadian in Acestes’ following who runs in the foot race.','Patron'),
('diores','Diores','A Trojan of Priam’s royal line, third in the foot race.','Diores'),
('entellus','Entellus','The old Sicilian boxer, Eryx’s pupil, who takes up Dares’ challenge.','Entellus'),
('dares','Dares','The Trojan boxer who challenges all comers and is beaten by Entellus.','Dares'),
('eryx','Eryx','The old boxer and king of Sicily, Entellus’s master, whose gauntlets are produced.','Eryx','reference'),
('hippocoon','Hippocoon','A Trojan whose lot is drawn first in the archery contest.','Hippocoon'),
('eurytion','Eurytion','A Trojan archer, brother of the Lycian Pandarus, who brings down the dove.','Eurytion'),
('atys','Atys','A Trojan boy brought up with Iulus, who leads the second squadron in the riding display.','Atys'),
('nautes','Nautes','The old Trojan seer who advises leaving the weary behind in Sicily.','Nautes'),
('beroe','Beroe','Doryclus’s aged wife, whose shape Iris takes to fire the Trojan ships.','Beroe','reference'),
('doryclus','Doryclus','Beroe’s husband, of Tmarus.','Doryclus','reference'),
('pyrgo','Pyrgo','The old nurse of Priam’s children, who sees through Iris’s disguise.','Pyrgo'),
('acmon','Acmon','A Trojan of Sarpedon’s blood who holds the wall with his brother.','Acmon'),
('asius','Asius','A Trojan of Sarpedon’s blood who holds the wall with his brother.','Asius'),
('haemon','Haemon','A young Trojan at the defence of the wall.','Haemon'),
('caeneus-trojan','Caeneus','A Trojan who kills Ortygius at the wall and is killed by Turnus.','',''),
('caeneus-underworld','Caeneus','A shade in the fields of mourning, once a woman and once a man.','',''),
('helenor','Helenor','A Lydian king’s bastard son by the slave Licymnia, who leaps from the burning tower and dies fighting.','Helenor'),
('licymnia','Licymnia','The slave who bore Helenor and sent him secretly to Troy.','Licymnia','reference'),
('idaeus-trojan','Idaeus','A Trojan sent with Actor to carry Euryalus’s mother away.','',''),
('idaeus-charioteer','Idaeus','Priam’s charioteer, seen among the shades.','',''),
('actor-trojan','Actor','A Trojan sent with Idaeus to carry Euryalus’s mother away.','',''),
('actor-auruncan','Actor','An Auruncan whose great lance Turnus took and wields.','',''),
('corynaeus','Corynaeus','A Trojan priest, who performs the rites at Misenus’s funeral and later fights with a brand from his own altar.','Corynaeus'),
('achaemenides','Achaemenides','A Greek of Ithaca left behind in the Cyclops’ country, taken aboard by the Trojans.','Achaemenides'),
('acoetes','Acoetes','Evander’s old squire, sent with Pallas and left to watch his body.','Acoetes'),
('aletes','placeholder','unused','',''),
('iapyx','Iapyx','The physician who tends Aeneas’s wound; Apollo’s favourite, who chose healing over prophecy.','Iapis|Iapyx'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ---------------------------------------------------- Italians and the Latins
for row in [
('ufens','Ufens','A Latin captain who leads the mountain troops of Nursia.','',''),
('halesus','Halesus','A captain born of Agamemnon’s line, a lifelong enemy of Troy, who brings his people to Turnus.','Halesus'),
('aventinus','Aventinus','Hercules’ son by the priestess Rhea, who comes to the war with his father’s lion skin.','Aventinus'),
('rhea','Rhea','The priestess whom Hercules found on the Aventine; Aventinus’s mother.','Rhea','reference'),
('catillus','Catillus','One of the three brothers of Tibur, who lead Argive horse for Turnus.','Catillus'),
('coras','Coras','One of the three brothers of Tibur, who lead Argive horse for Turnus.','Coras'),
('tiburs','Tiburs','The brother who gave Tibur its name.','Tiburs','reference'),
('caeculus','Caeculus','The founder of Praeneste, said to be Vulcan’s son, found in the fire.','Caeculus'),
('clausus','Clausus','A Sabine captain who is an army in himself, and the founder of the Claudian house.','Clausus'),
('virbius','Virbius','Hippolytus’s son, named for his father’s second life, who comes to the war from Aricia’s groves.','Virbius'),
('hippolytus','Hippolytus','Theseus’s son, torn apart by his horses and restored to life by the healing god.','Hippolytus','reference'),
('aricia','Aricia','Hippolytus’s wife, who bore Virbius in the Egerian groves.','Aricia','reference'),
('tyrrheus','Tyrrheus','Latinus’s chief ranger, whose tame stag the Trojans shoot.','Tyrrheus'),
('silvia','Silvia','Tyrrheus’s daughter, who reared the stag.','Silvia'),
('almon','Almon','Tyrrheus’s eldest son, the first man killed in the new war.','Almon'),
('venulus','Venulus','The Latin envoy sent to ask Diomede for help.','Venulus'),
('tolumnius','Tolumnius','The Latins’ augur, who reads the omen and throws the spear that breaks the truce.','Tolumnius'),
('camers','Camers','A rich young Latin, Volscens’s son, killed by Aeneas.','Camers'),
('numa','Numa','A strong young Latin killed by Aeneas.','',''),
('numa-king','placeholder','unused','',''),
('volscens','Volscens','The Latin cavalry commander who kills Euryalus and is killed by Nisus.','Volscens'),
('rhamnes','Rhamnes','An augur and Turnus’s favourite, killed asleep by Nisus.','Rhamnes'),
('remus-rutulian','Remus','A Rutulian killed in his sleep with his armour-bearer and his slaves.','',''),
('remus-brother','Remus','Romulus’s brother, named in the promise of a Rome at peace.','',''),
('romulus','Romulus','The wolf-suckled founder of Rome, Mars’s son by Ilia.','Romulus','reference'),
('ilia','Ilia','The priestess who bears Romulus and Remus to Mars.','Ilia','reference'),
('serranus','Serranus','A fair young Rutulian killed in his sleep.','Serranus'),
('lamus','Lamus','A Rutulian killed in his sleep by Nisus.','Lamus'),
('lamyrus','Lamyrus','A Rutulian killed in his sleep by Nisus.','Lamyrus'),
('rhoetus','Rhoetus','A Rutulian who wakes and hides behind a jar, and is killed by Euryalus.','Rhoetus'),
('fadus','Fadus','A Rutulian killed by Euryalus.','Fadus'),
('hebesus','Hebesus','A Rutulian killed by Euryalus.','Hebesus'),
('caedicus','Caedicus','A rich man who gave Remulus the golden belt that Euryalus takes.','Caedicus','reference'),
('remulus','Remulus','A Tiburtine to whom Caedicus gave the belt; his heir wore it until the Ardeans took it.','Remulus','reference'),
('sulmo','Sulmo','A Rutulian speared in the back during the night pursuit.','Sulmo'),
('tagus','Tagus','A Rutulian killed beside Sulmo.','Tagus'),
('numanus','Numanus','Turnus’s brother-in-law, who taunts the Trojans and is shot by Ascanius.','Numanus'),
('lucetius','Lucetius','A Rutulian crushed by a rock as he brings fire to the gate.','Lucetius'),
('ortygius','Ortygius','A Rutulian killed by Caeneus.','Ortygius'),
('itys','Itys','A Trojan killed by Turnus at the wall.','Itys'),
('clonius','Clonius','A Trojan killed by Turnus at the wall.','Clonius'),
('sagar','Sagar','A Trojan killed by Turnus at the wall.','Sagar'),
('ida','Ida','A Trojan killed by Turnus while standing on the wall.','',''),
('privernus','Privernus','A Trojan killed at the wall after clapping his hand to a slight wound.','Privernus'),
('themilla','Themilla','A Rutulian who gives Privernus his first, slight wound.','Themilla'),
('antiphates','Antiphates','Sarpedon’s bastard son by a Theban slave, the first man Turnus meets inside the camp.','Antiphates'),
('meropes','Meropes','A Trojan killed by Turnus inside the camp.','Meropes'),
('erymanthus','Erymanthus','A Trojan killed by Turnus inside the camp.','',''),
('aphidnus','Aphidnus','A Trojan killed by Turnus inside the camp.','Aphidnus'),
('quercens','Quercens','A Rutulian who rushes the open gate.','Quercens'),
('tmarus','Tmarus','A Rutulian who rushes the open gate.','Tmarus'),
('equicolus','Equicolus','A Rutulian in bright armour who rushes the open gate.','Equicolus'),
('clytius','Clytius','A Trojan killed by Turnus inside the camp.','Clytius'),
('lucagus','Lucagus','A Latin who fights from the chariot his brother Liger drives; killed by Aeneas.','Lucagus'),
('liger','Liger','Lucagus’s brother, who drives their chariot and taunts Aeneas.','',''),
('asylas-etruscan','Asylas','An Etruscan captain and diviner, who reads the stars and the flight of birds, and leads the chase.','',''),
('mimas','Mimas','A Trojan born the same night as Paris, killed by Mezentius.','Mimas'),
('evas','Evas','A Trojan killed by Mezentius.','Evas'),
('orsilochus','Orsilochus','A Trojan who does not dare face Camilla and is killed by her.','',''),
('butes-boxer','Butes','The giant of Amycus’s Bebrycian stock whom Eryx beat at Hector’s funeral games.','',''),
('butes-squire','Butes','Anchises’ old squire, left to attend Ascanius; Apollo takes his shape.','',''),
('butes-trojan','Butes','A bulky Trojan killed breast to breast by Camilla.','',''),
('butes-turnus','Butes','A Trojan thrown by his floundering horse and killed by Turnus.','',''),
('thoas-greek','Thoas','One of the Greeks who came down out of the wooden horse.','',''),
('thoas-italian','Thoas','A warrior struck in the forehead with a stone by Pallas.','',''),
('menoetes-pilot','Menoetes','Gyas’s pilot in the boat race, thrown overboard for steering too cautiously.','',''),
('menoetes-arcadian','Menoetes','A peaceful Arcadian who had long shunned war, killed by Turnus.','',''),
('rhoeteus','Rhoeteus','A man who crosses the plain by chance and takes the spear Pallas meant for Ilus.','Rhoeteus'),
('ilus-trojan','Ilus','Tros’s son, an ancestor of the Trojan house, enjoying fame in Elysium.','',''),
('ilus-italian','Ilus','The man Pallas aimed at when Rhoeteus crossed the flight of the spear.','',''),
('herminius','Herminius','The mighty champion of the Tuscan crew, killed by Catillus.','Herminius'),
('iolas','Iolas','A man killed by Catillus.','Iolas'),
('aruns','Aruns','The Etruscan who stalks Camilla, kills her from cover and is killed by Diana’s nymph.','Aruns'),
('opis','Opis','Diana’s nymph, sent to avenge Camilla.','Opis'),
('metiscus','Metiscus','Turnus’s charioteer, whose shape Juturna takes.','Metiscus'),
('acca','Acca','Camilla’s companion, sent to carry her last message to Turnus.','Acca'),
('cydon','Cydon','A Latin whom Aeneas spares the doom of, and whose seven brothers attack.','',''),
('dryops','Dryops','A Trojan speared through the throat by Clausus.','Dryops'),
('hyarbas','Hyarbas','The African king who courted Dido and prays to Jove against her Trojan guest. The modern edition spells him Iarbas.','Hyarbas|Iarbas'),
('sychaeus','Sychaeus','Dido’s murdered husband, whose ghost tells her to flee Tyre.','Sychaeus|Sichaeus'),
('pygmalion','Pygmalion','Dido’s brother, king of Tyre, who murdered Sychaeus for his wealth.','Pygmalion'),
('belus','Belus','Dido’s father, who once conquered Cyprus.','Belus','reference'),
('barce','Barce','Sychaeus’s old nurse, whom Dido sends away at the end.','Barce'),
('daunus','Daunus','Turnus’s father.','Daunus','reference'),
('pilumnus','Pilumnus','Turnus’s ancestor, a god four generations back.','Pilumnus','reference'),
('dardanus','Dardanus','Founder of the Trojan line, born in Italy, which makes Italy the Trojans’ ancient mother.','Dardanus','reference'),
('iasius','Iasius','Dardanus’s brother, born in the same country.','Iasius|Jasius','reference'),
('teucer-trojan','Teucer','The ancestor from Crete whose name the Trojans bear.','',''),
('teucer-salamis','Teucer','The exile from Salamis who once came to Sidon and was helped by Belus.','',''),
('assaracus','Assaracus','An ancestor of the Trojan house, enjoying fame in Elysium.','Assaracus','reference'),
('laomedon','Laomedon','Priam’s father, whose broken faith is held against Troy.','Laomedon','reference'),
('ganymede','Ganymede','The Trojan boy carried up to serve Jove, one of Juno’s standing grievances.','Ganymede','reference'),
('electra','Electra','Atlas’s daughter and Dardanus’s mother, another of Juno’s grievances.','Electra','reference'),
('paris','Paris','The Trojan whose judgment against Juno began her hatred, and who carried Helen away.','Paris','supporting'),
('helen','Helen','Menelaus’s wife, carried off by Paris; Aeneas finds her hiding at Vesta’s shrine.','Helen','supporting'),
('orestes','Orestes','Agamemnon’s son, who kills Pyrrhus at his father’s altar.','',''),
('agamemnon','Agamemnon','The Greek commander at Troy.','Agamemnon','reference'),
('menelaus','Menelaus','Helen’s husband and Agamemnon’s brother.','Menelaus','reference'),
('atreus','Atreus','Father of the two brother kings.','Atreus','reference'),
('calchas','Calchas','The Greek augur whose word Sinon uses to frame his story.','Calchas','reference'),
('palamedes','Palamedes','The Greek Sinon claims as his kinsman, put to death on a false charge.','Palamedes','reference'),
('thymoetes','Thymoetes','The Trojan who urges bringing the horse inside.','Thymoetes'),
('capys-trojan','placeholder','unused','',''),
('cassandra','Cassandra','Priam’s daughter, whose true prophecies Apollo doomed to be disbelieved.','Cassandra','supporting'),
('coroebus','Coroebus','Cassandra’s suitor, killed at Pallas’s altar on the night Troy fell.','Coroebus'),
('ripheus','Ripheus','The justest of the Trojans, killed on the night Troy fell.','Ripheus'),
('iphitus','Iphitus','An aged Trojan who fights at Aeneas’s side on the last night.','Iphitus'),
('dymas','Dymas','A Trojan who joins Aeneas’s band on the last night.','',''),
('dymas-father','placeholder','unused','',''),
('hypanis','Hypanis','A Trojan who joins Aeneas’s band on the last night.','Hypanis'),
('pantheus','Pantheus','Apollo’s priest on the citadel, who brings Aeneas the household gods.','Pantheus'),
('androgeos','Androgeos','The Greek captain who mistakes Aeneas’s band for his own men.','Androgeos'),
('peneleus','Peneleus','The Greek who kills Coroebus at Pallas’s altar.','Peneleus'),
('polites','Polites','Priam’s son, run down and killed in front of his parents.','Polites'),
('hecuba','Hecuba','Priam’s queen, sheltering at the altar with her daughters.','Hecuba'),
('polydorus','Polydorus','Priam’s youngest son, murdered for his gold in Thrace; his voice comes out of the ground. Dryden calls him Polydore.','Polydore|Polydorus'),
('lycurgus','Lycurgus','The fierce king who once ruled Thrace.','Lycurgus','reference'),
('idomeneus','Idomeneus','The Cretan king driven out of his own country, which leaves Crete open.','Idomeneus','reference'),
('anius','Anius','The priest-king of Delos, Anchises’ old guest-friend.','Anius'),
('deiphobus','Deiphobus','Priam’s son, whose house burns first, and whose mutilated shade Aeneas meets below.','Deiphobus','supporting'),
('sthenelus','Sthenelus','One of the Greeks who comes out of the horse.','Sthenelus'),
('tysander','Tysander','One of the Greeks who comes out of the horse.','Tysander'),
('athamas','Athamas','One of the Greeks who comes out of the horse.','Athamas'),
('epeus','Epeus','The Greek who built the horse.','Epeus','reference'),
('demoleus','Demoleus','A Greek from whom Aeneas took a coat of mail.','Demoleus','reference'),
('cisseus','Cisseus','The Thracian who gave Anchises a figured goblet.','Cisseus','reference'),
('marcellus','Marcellus','The young Roman in the parade of souls whose early death the poem mourns.','Marcellus','reference'),
('caesar','Caesar','The ruler promised to rise from the Julian line.','Caesar','reference'),
('numitor','Numitor','An Alban king in the parade of Aeneas’s descendants.','Numitor','reference'),
('procas','Procas','An Alban king in the parade of Aeneas’s descendants.','Procas','reference'),
('silvius','Silvius','Aeneas’s last-begotten son, born in the woods to Lavinia.','',''),
('silvius-aeneas','Silvius Aeneas','A later Alban king who bears Aeneas’s name.','',''),
('tullus','Tullus','An early Roman king in the parade of souls.','Tullus','reference'),
('ancus','Ancus','An early Roman king in the parade of souls.','Ancus','reference'),
('tarquin','Tarquin','The Roman kings whose line the avenging sword ends.','Tarquin','reference'),
('brutus','Brutus','The Roman who put his own sons to death for the republic.','Brutus','reference'),
('cato','Cato','The Roman renowned for gravity, seen in the parade of souls.','Cato','reference'),
('cossus','Cossus','A conquering Roman seen in the parade of souls.','Cossus','reference'),
('hercules','Hercules','The hero who killed Cacus on the future site of Rome, worshipped there ever since. The poem also calls him Alcides.','Hercules|Alcides','supporting'),
('cacus','Cacus','The fire-breathing monster of the Aventine cave, killed by Hercules.','Cacus','supporting','mythical-being'),
('geryon','Geryon','The triple-bodied giant Hercules killed in Spain.','Geryon','reference','mythological-figure'),
('potitius','Potitius','The founder of Hercules’ annual rites at Rome.','Potitius','reference'),
('evadne','Evadne','A shade in the fields of mourning.','Evadne','reference'),
('laodamia','Laodamia','A shade in the fields of mourning.','Laodamia','reference'),
('pasiphae','Pasiphae','A shade in the fields of mourning; the modern edition spells her Pasiphaë.','Pasiphae|Pasiphaë','reference'),
('phaedra','Phaedra','A shade in the fields of mourning.','Phaedra','reference'),
('procris','Procris','A shade in the fields of mourning.','Procris','reference'),
('eriphyle','Eriphyle','A shade in the fields of mourning.','Eriphyle','reference'),
('theseus','Theseus','The hero seated for ever in the underworld.','Theseus','reference'),
('pirithous','Pirithous','Theseus’s companion, punished below; the modern edition spells him Peirithous.','Pirithous|Peirithous','reference'),
('minos','Minos','The judge who shakes the urn over the silent shades.','Minos','reference'),
('rhadamanthus','Rhadamanthus','The judge of the guilty in Tartarus.','Rhadamanthus','reference'),
('tisiphone','Tisiphone','The Fury who keeps the gate of Tartarus.','Tisiphone','reference','deity'),
('salmoneus','Salmoneus','The shade punished for counterfeiting Jove’s thunder.','Salmoneus','reference'),
('tityus','Tityus','The giant whose liver the vulture feeds on for ever.','Tityus','reference'),
('ixion','Ixion','A shade punished in Tartarus.','Ixion','reference'),
('phlegyas','Phlegyas','The shade who cries out a warning to learn justice.','Phlegyas','reference'),
('musaeus','Musaeus','The divine singer among the blessed, who shows the way to Anchises.','Musaeus','reference'),
('orpheus','Orpheus','The Thracian singer, seen among the blessed in his long robe.','Orpheus','reference'),
('ilus-ancestor','placeholder','unused','',''),
('memnon','Memnon','The swarthy warrior in the Carthaginian frescoes.','Memnon','reference'),
('penthesilea','Penthesilea','The Amazon queen in the Carthaginian frescoes. Dryden spells her Penthisilea.','Penthesilea|Penthisilea','reference'),
('troilus','Troilus','Priam’s young son, dragged behind his chariot in the frescoes.','Troilus','reference'),
('sarpedon','Sarpedon','The Lycian who fell at Troy, named as father of the brothers who hold the wall.','Sarpedon','reference'),
('glaucus','Glaucus','One of Antenor’s sons, seen among the shades of the Trojan dead.','Glaucus','reference'),
('medon','Medon','One of Antenor’s sons, seen among the shades of the Trojan dead.','Medon','reference'),
('antenor','Antenor','The Trojan who escaped and founded Padua, cited as a precedent by Venus.','Antenor','reference'),
('harpalyce','Harpalyce','The Thracian huntress Venus is compared to.','Harpalyce','reference'),
('iopas','Iopas','The long-haired bard who sings at Dido’s feast.','Iopas'),
('cupid','Cupid','Venus’s son, sent to Carthage in Ascanius’s shape to fire Dido with love.','Cupid','supporting','deity'),
('amazons','The Amazons','The warrior women of the frescoes and of Camilla’s comparison.','Amazons','reference','group'),
('cyclops','The Cyclops','The one-eyed giants of Sicily; Polyphemus is their most famous. Dryden spells the singular Polypheme.','Cyclops|Cyclopes','supporting','group'),
('polyphemus','Polyphemus','The blinded Cyclops whom the Trojans see groping down to the sea. Dryden calls him Polypheme.','Polypheme|Polyphemus','supporting'),
('scylla','Scylla','The monster whose waist ends in dogs, waiting on the right of the strait.','','supporting','mythical-being'),
('charybdis','Charybdis','The whirlpool on the left of the strait, which swallows and spews the sea three times a day.','Charybdis','supporting','mythical-being'),
('chimaera','The Chimaera','The fire-breathing monster, seen at the gate of hell and blazoned on Turnus’s crest.','','reference','mythical-being'),
('centaurs','The Centaurs','The double-shaped creatures who besiege the gate of hell.','Centaurs','reference','group'),
('briareus','Briareus','The hundred-handed monster at the gate of hell.','Briareus','reference','mythological-figure'),
('gorgons','The Gorgons','Monsters at the gate of hell.','Gorgons|Gorgon','reference','group'),
('hydra','The Hydra','The many-headed monster at the gate of hell, and in Lerna’s lake.','Hydra','reference','mythical-being'),
('typhoeus','Typhoeus','A monster named among the terrors Hercules did not fear.','Typhoeus','reference','mythological-figure'),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ----------------------------------------------------------------- the peoples
for row in [
('trojans','The Trojans','Aeneas’s people, the survivors of Troy; also called Dardans, Phrygians and Teucrians.','Trojans','major','group'),
('latins','The Latins','Latinus’s people, whose land the Trojans are fated to hold.','Latins|Latians','major','group'),
('rutulians','The Rutulians','Turnus’s people, of Ardea.','Rutulians','major','group'),
('tyrians','The Tyrians','Dido’s people, the settlers of Carthage.','Tyrians','supporting','group'),
('greeks','The Greeks','The army that took Troy; the poem also calls them Grecians, Argives and Danaans.','Greeks|Grecians|Argives|Danaans','supporting','group'),
('arcadians','The Arcadians','Evander’s people at Pallanteum.','Arcadians','supporting','group'),
('tuscans','The Tuscans','The Etruscan people who rise against Mezentius and join Aeneas.','Tuscans','supporting','group'),
('volscians','The Volscians','Camilla’s people.','Volscians','supporting','group'),
('italians','The Italians','The peoples of Italy taken together; also called Ausonians and Oenotrians.','Italians|Oenotrians','supporting','group'),
('auruncans','The Auruncans','An Italian people from the hills who join Turnus.','Auruncans','reference','group'),
('equicoli','The Equicolae','A rough Italian people under Ufens; the modern edition spells them Equicoli.','Equicolae|Equicoli','reference','group'),
('faliscans','The Faliscans','An Italian people called to the war.','Faliscans','reference','group'),
('sicanians','The Sicanians','An old people of Sicily and Italy.','Sicanians|Sicanian','reference','group'),
('massylians','placeholder','unused','',''),
('nomads','The Numidians','An African people on Carthage’s frontier.','Numidians','reference','group'),
('gauls','The Gauls','The people whose night attack on the Capitol the geese betrayed, shown on Aeneas’s shield.','Gauls','reference','group'),
('scythians','The Scythians','A far northern people, named among those Rome will face.','Scythians','reference','group'),
('cyclades','placeholder','unused','',''),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

Path(__file__).parent.joinpath('editorial.json').write_text(json.dumps(dict(
 contentVersion='2026-09-11.1',
 coverage='Both full English editions, all twelve books: named people, gods, personified powers, named monsters and named peoples. Places, rivers as geography, mountains, islands and ships are excluded — the boat race in book five names four galleys after monsters, and those occurrences are not cast.',
 entities=entities),ensure_ascii=False,indent=2)+'\n')
print(len(entities),'entities')
