"""Manually authored references for all four books of The Social Contract."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category='reference',kind=kind,subtitle='',snapshots=[]))
for row in [
('grotius','Hugo Grotius','The Dutch jurist whose arguments about sovereignty and slavery Rousseau challenges.','Grotius'),
('hobbes','Thomas Hobbes','The English political philosopher discussed on authority and the relation of religion to government.','Hobbes'),
('philo','Philo','The Jewish philosopher from Alexandria cited as a source for Caligula’s reasoning.','Philo'),
('caligula','Caligula','The Roman emperor used in examples about rulers’ claims to superiority.','Emperor Caligula|Caligula'),
('aristotle','Aristotle','The Greek philosopher cited on slavery, political authority and forms of government.','Aristotle'),
('argenson','The Marquis d’Argenson','The French statesman whose political observations Rousseau quotes.','Marquis d\'Argenson|d\'Argenson'),
('rabelais','François Rabelais','The French satirist cited in the discussion of slavery.','Rabelais'),
('cato-elder','Cato the Elder','The Roman statesman who writes about his son’s military oath.',''),
('cato-son','Cato’s son','Marcus Porcius Cato Licinianus, the elder Cato’s son serving under Popilius.',''),
('cato-younger','Cato the Younger','The Roman republican statesman mentioned in the debate about Caesar’s speech.',''),
('popilius','Popilius','The Roman commander addressed by Cato about his son’s military service.','Popilius'),
('bodin','Jean Bodin','The French political thinker cited in the note on citizens and townsmen.','Bodin'),
('alembert','Jean le Rond d’Alembert','The French scholar cited on Geneva and on the discussion of public morals.','M. d\'Alembert|d\'Alembert'),
('balboa','Vasco Núñez de Balboa','The Spanish explorer whose claim to territory illustrates the argument about possession.','Nuñez Balbao|Balbao'),
('barbeyrac','Jean Barbeyrac','The jurist and translator of Grotius discussed in the note on sovereignty.','Barbeyrac'),
('louis-xiii','Louis XIII','The French king to whom Grotius dedicated his book.','Louis XIII'),
('george','George I','The British king to whom Barbeyrac dedicated his translation.','George I'),
('james','James II','The deposed British king mentioned in the argument about legitimate authority.','James II'),
('william','William III','The king whose succession is discussed alongside James II’s removal.','William'),
('lycurgus','Lycurgus','The traditional Spartan lawgiver used as an example of founding institutions.','Lycurgus'),
('solon','Solon','The Athenian lawgiver cited among founders of political institutions.','Solon'),
('numa','Numa Pompilius','The traditional second king of Rome, cited as a lawgiver.','Numa'),
('servius','Servius Tullius','The Roman king associated with the census and the organization of the voting assemblies.','Servius'),
('montesquieu','Montesquieu','The French political philosopher cited on laws, government and climate.','Montesquieu'),
('plato','Plato','The Greek philosopher whose political thought Rousseau discusses.','Plato'),
('calvin','John Calvin','The religious reformer whose role in Geneva’s laws Rousseau praises.',''),
('machiavelli','Niccolò Machiavelli','The Florentine political writer whose advice to rulers Rousseau reads as instruction for the people.','Macchiavelli|Machiavelli'),
('warburton','William Warburton','The English bishop and writer cited on the relationship between politics and religion.','Warburton'),
('peter','Peter the Great','The Russian tsar whose reforms Rousseau criticizes as premature imitation.','Peter'),
('descartes','René Descartes','The French philosopher invoked in the discussion of political order.','Descartes'),
('palatine','The Count Palatine','The Polish nobleman quoted as preferring dangerous liberty to peaceful servitude.','Count Palatine'),
('archimedes','Archimedes','The ancient mathematician used in a comparison about concentrated power.','Archimedes'),
('dionysius-younger','Dionysius the Younger','The ruler of Syracuse who answers his father’s rebuke in the anecdote about royal upbringing.',''),
('dionysius-elder','Dionysius the Elder','The ruler of Syracuse who rebukes his son in the anecdote about kingship.',''),
('dionysius-grandfather','Dionysius the Younger’s grandfather','The non-royal grandfather invoked in the reply about inherited kingship.',''),
('borgia','Cesare Borgia','The Italian ruler whom Rousseau discusses as Machiavelli’s chosen example.','Cæsar Borgia|Cesare Borgia'),
('livy','Livy','The Roman historian whose work appears in the title of Machiavelli’s Discourses.','Livy'),
('chardin','Jean Chardin','The French traveler cited for observations on life in Persia.','Chardin'),
('retz','Cardinal de Retz','The coadjutor of Paris mentioned in the account of political unrest in France.','Coadjutor of Paris'),
('tacitus','Tacitus','The Roman historian quoted on government and political servility.','Tacitus'),
('sulla','Sulla','The Roman general and dictator cited in the discussion of political decay.','Sulla'),
('caesar','Julius Caesar','The Roman general and statesman cited in the arguments about power and the republic.','Julius Cæsar|Cæsar'),
('augustus','Augustus','The first Roman emperor, cited in the account of the republic’s decline.','Augustus'),
('tiberius','Tiberius','The Roman emperor who succeeded Augustus.','Tiberius'),
('nepos','Cornelius Nepos','The Roman biographer cited on the meaning of tyranny.','Cornelius Nepos'),
('miltiades','Miltiades','The Athenian commander whose biography is cited in the note on tyranny.','Miltiades'),
('xenophon','Xenophon','The Greek writer whose Hiero is cited in discussing tyranny.','Xenophon'),
('cromwell','Oliver Cromwell','The English political and military leader used in examples about manipulation and power.','Cromwell'),
('beaufort','The Duc de Beaufort','The French nobleman invoked as a popular agitator in the comparison with Geneva.','Due de Beaufort|Duc de Beaufort'),
('otho','Otho','The Roman emperor whose senators denounced his rival Vitellius.','Otho'),
('vitellius','Vitellius','Otho’s rival for the Roman imperial throne.','Vitellius'),
('saint-pierre','The Abbé de Saint-Pierre','The French political reformer whose proposal for royal councils Rousseau discusses.','Abbé de Saint-Pierre'),
('varro','Varro','The Roman writer cited on the rural foundations of the republic.','Varro'),
('pliny','Pliny the Elder','The Roman writer cited on the standing of the rural voting tribes.','Pliny'),
('appius','Appius Claudius','The Sabine migrant who became the ancestor of the Roman Claudian family.','Appius Claudius'),
('romulus','Romulus','Rome’s legendary founder and first king.','Romulus'),
('marius','Gaius Marius','The Roman general cited on army recruitment and civil conflict.','Marius'),
('tarquin','Tarquin the Proud','The last king of Rome, referred to as the later Tarquin.','Tarquin'),
('cicero','Cicero','The Roman orator and consul discussed on voting, emergency powers and religion.','Cicero'),
('agis','Agis IV','The Spartan king whose killing by the ephors is discussed.','Agis'),
('cleomenes','Cleomenes III','The Spartan king mentioned in the account of the ephors and Sparta’s decline.','Cleomenes'),
('pompey','Pompey','The Roman general whose struggle with Caesar illustrates military power over civil authority.','Pompey'),
('catiline','Catiline','The Roman conspirator invoked in the discussions of dictatorship and civic loyalty.','Catiline|Catilinarian'),
('bayle','Pierre Bayle','The French philosopher whose views on religion and society Rousseau examines.','Bayle'),
('henry','Henry IV','The French king whose conversion to Catholicism is invoked in the argument about intolerance.','Henry IV'),
('carrieres','Louis de Carrières','The French biblical translator whose rendering of Jephthah’s words Rousseau questions.','Father de Carrières'),
]:add(*row)
for row in [
('adam','Adam','The first man of the biblical creation story, invoked in the satirical discussion of inherited kingship.','King Adam|Adam','religious-figure'),
('noah','Noah','The biblical patriarch used in the same argument about hereditary rule.','Emperor Noah|Noah','religious-figure'),
('noah-sons','Noah’s sons','The three biblical sons of Noah, invoked as supposed founders of kingdoms.','','group'),
('saturn','Saturn','The Roman god invoked in comparing stories of divine and royal descent.','Saturn','mythological-figure'),
('saturn-children','Saturn’s children','The divine children invoked in the comparison with Noah’s sons.','','group'),
('crusoe','Robinson Crusoe','Defoe’s fictional island-dweller, used in an example of sovereignty without subjects.','Robinson Crusoe','literary-figure'),
('ulysses','Ulysses','Odysseus, the Homeric hero whose companions appear in the comparison about submission.','Ulysses','literary-figure'),
('ulysses-companions','Ulysses’s companions','The men of the Homeric hero’s company used in Rousseau’s comparison.','','group'),
('cyclops','The Cyclops','The man-eating giant from the Odyssey, invoked in the discussion of captivity.','Cyclops','literary-figure'),
('god','God','The divine being invoked in the discussion of authority, obligation and civil religion.','God of Israel|God|Supreme Being','religious-figure'),
('ishmael','Ishmael','The biblical son of Abraham invoked in the traditional ancestry of Muhammad.','Ishmael','religious-figure'),
('muhammad','Muhammad','The prophet of Islam whose combination of religious and political authority Rousseau discusses.','Mahomet','religious-figure'),
('minos','Minos','The legendary Cretan ruler associated with its laws.','Minos','mythological-figure'),
('hercules','Hercules','The classical hero used in a comparison about the demands of ruling.','Hercules','mythological-figure'),
('samuel','Samuel','The biblical prophet who warns the Israelites about kingship.','Samuel','religious-figure'),
('moloch','Moloch','The deity named in Rousseau’s argument against conflating different peoples’ gods.','Moloch','religious-figure'),
('chronos','Chronos','The Greek divine figure named alongside Saturn in the argument against merging different gods.','Chronos','mythological-figure'),
('baal','Baal','The Phoenician deity distinguished from Greek Zeus and Roman Jupiter.','Baal','religious-figure'),
('zeus','Zeus','The Greek chief god distinguished here from the gods of other peoples.','Greek Zeus|Zeus','mythological-figure'),
('jupiter','Jupiter','The Roman chief god, including the Jupiter worshipped on the Capitol.','Latin Jupiter|Jupiter','mythological-figure'),
('moses','Moses','The biblical lawgiver mentioned in discussing the God of Israel.','Moses','religious-figure'),
('chamos','Chamos','Chemosh, the deity invoked in the quoted exchange with the Ammonites.','Chamos','religious-figure'),
('jephthah','Jephthah','The biblical judge whose words about territorial rights Rousseau quotes.','Jephthah','religious-figure'),
('jesus','Jesus Christ','The central figure of Christianity, discussed in relation to spiritual and political authority.','Jesus','religious-figure'),
('ali','Ali','Muhammad’s cousin and son-in-law, the foundational figure invoked in discussing Shi‘a Islam.','Ali','religious-figure'),
('homer','Homer','The ancient Greek poet invoked through the depiction of gods taking sides in human wars.','Homer','person'),
('medici','The Medici','The Florentine ruling family whose court is mentioned in the discussion of Machiavelli.','Medici','group'),
('tarquins','The Tarquins','The Roman royal family whose expulsion is discussed.','Tarquins','group'),
('gracchi','The Gracchi','The Roman reforming brothers Tiberius and Gaius Gracchus, invoked in the discussion of popular representation.','Gracchi','group'),
]:add(*row)
add('rousseau','Jean-Jacques Rousseau','The author of The Social Contract, named in editorial notes on quotations.','Rousseau')
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='social-contract',contentVersion='2026-09-10.1',coverage='All four books and 48 local reading units in original-en and modern-en, including surviving footnotes. Named historical, philosophical, literary and religious references with scoped namesakes and identifiable implicit references. No invented personal identities for generic rulers, offices, assemblies or peoples; inherited truncated notes are documented for release review.',entities=entities),ensure_ascii=False,indent=2)+'\n')
