"""Manually authored recognition copy for the Preface and all three essays.

Nietzsche's treatise names no fictional cast; almost every bound entry is a
real philosopher, historian, poet, theologian, or a mythological/scriptural
figure Nietzsche cites by name. Two entries (Schopenhauer, Wagner) are
category 'major': each anchors several consecutive paragraphs of sustained
analysis in the Third Essay rather than a single citation. Everyone else is
'reference'. Collective peoples and confessions (the Jews, the Germans, the
Greeks, the Romans, Buddhists as a group) and works/texts (the Talmud, the
New Testament) are deliberately not bound as persons -- see README.
"""
import json
from pathlib import Path

entities = []


def add(id, name, body, aliases='', category='reference', kind='person'):
    entities.append(dict(
        id=id, name=name, body=body,
        aliases=aliases.split('|') if aliases else [],
        category=category, kind=kind, subtitle='', snapshots=[],
    ))


for row in [
    ('paul-ree', 'Paul Rée',
     "German philosopher and physician whose 1877 book The Origin of the Moral Emotions provoked Nietzsche's own inquiry into the origin of morality.",
     'Dr. Paul Rée|Dr. Rée'),
    ('schopenhauer', 'Arthur Schopenhauer',
     "The philosopher of pessimism and the will, called Nietzsche's early teacher in the Preface and examined at length in the Third Essay as a philosopher who paid homage to the ascetic ideal.",
     'Schopenhauer', 'major'),
    ('plato', 'Plato',
     "The Greek philosopher, cited repeatedly as an early opponent of pity and, in the Third Essay, as art's greatest enemy and the antithesis of Homer.",
     'Plato'),
    ('spinoza', 'Baruch Spinoza',
     'The philosopher whose placement of good and evil in human imagination, and whose account of the sting of conscience, Nietzsche discusses at length.',
     'Spinoza'),
    ('la-rochefoucauld', 'La Rochefoucauld',
     'The French moralist named among the philosophers who held pity in contempt before it became fashionable to praise it.',
     'La Rochefoucauld'),
    ('kant', 'Immanuel Kant',
     'The philosopher whose categorical imperative, definition of the beautiful, and critique of theological dogmatism Nietzsche repeatedly takes up and disputes.',
     'Kant'),
    # No global alias: "Zarathustra" also names Nietzsche's own book (his
    # "my Zarathustra" in the Preface, and the "Thus Spake Zarathustra"
    # epigraph attribution before the Third Essay) -- a work named after its
    # protagonist, the exact trap the editorial policy warns about. Only the
    # Second Essay's closing invocation of Zarathustra as a distinct, living
    # voice ("open alone to Zarathustra, Zarathustra the godless") is a
    # person reference; it is bound by a location-scoped rule in
    # build_genealogy_of_morals.py instead of a bare alias.
    ('zarathustra', 'Zarathustra',
     "The prophet-figure of Nietzsche's own Thus Spoke Zarathustra, invoked at the close of the Second Essay as a voice reserved for what this book leaves unsaid.",
     ''),
    ('herbert-spencer', 'Herbert Spencer',
     "The English philosopher whose evolutionary account of 'good' as the useful, and of life as adaptation, Nietzsche disputes by name.",
     'Herbert Spencer'),
    ('buckle', 'Henry Thomas Buckle',
     "The English historian Nietzsche cites as the case in which modern 'plebeian' prejudice broke out most violently in historical writing.",
     'Buckle'),
    ('theognis', 'Theognis',
     "The Greek poet of Megara whom Nietzsche credits with first making 'the truthful' the nobility's own name for itself.",
     'Theognis'),
    ('virchow', 'Rudolf Virchow',
     "The German pathologist and anthropologist Nietzsche disputes on the racial ancestry of Germany's dark-haired population.",
     'Virchow'),
    ('jesus', 'Jesus of Nazareth',
     "Discussed as the culmination of the Jewish 'transvaluation of values' and, via a quoted early Christian text, as the crucified god whose blood believers claim.",
     'Jesus of Nazareth|Jesus|Christ'),
    ('peter', 'Peter',
     "The apostle, named among the figures before whom, Nietzsche says, 'almost half the world' now bows, and later mocked as an insufferably self-important New Testament voice.",
     'Peter the fisher|Peter'),
    ('paul-apostle', 'Paul',
     "The apostle, named among the figures before whom, Nietzsche says, 'almost half the world' now bows.",
     'Paul the tent-maker'),
    ('mary', 'Mary',
     "The mother of Jesus, named as the fourth of the figures before whom Nietzsche says 'almost half the world' now bows.",
     'Mary'),
    ('napoleon', 'Napoleon',
     "Napoleon Bonaparte, presented as the modern reappearance of the aristocratic ideal, 'that synthesis of Monster and Superman.'",
     'Napoleon'),
    ('pericles', 'Pericles',
     'The Athenian statesman, quoted from his funeral oration as an example of aristocratic audacity and contempt for safety.',
     'Pericles'),
    ('hesiod', 'Hesiod',
     'The Greek poet who divided the ages of man into gold, silver and bronze, which Nietzsche reads as a device for accommodating two incompatible views of the heroic age.',
     'Hesiod'),
    ('mirabeau', 'Mirabeau',
     'The French Revolutionary orator, cited as a modern example of a strong nature who forgives only because he forgets.',
     'Mirabeau'),
    ('homer', 'Homer',
     "The Greek poet, cited for his gods' amused view of human folly, as the creator of Achilles, and as the artist Nietzsche opposes to Plato.",
     'Homer'),
    ('dante', 'Dante',
     'The Italian poet, whose inscription over the gate of Hell in the Divine Comedy Nietzsche calls a crass mistake.',
     'Dante'),
    ('aquinas', 'Thomas of Aquinas',
     'The medieval theologian and saint, quoted on the blessed in heaven taking pleasure in witnessing the torments of the damned.',
     'Thomas of Aquinas'),
    ('tertullian', 'Tertullian',
     'The early Christian writer, quoted at length in Latin from De Spectaculis, anticipating the torment of pagan emperors, philosophers, actors and poets after the Last Judgment.',
     'Tertullian'),
    ('don-quixote', 'Don Quixote',
     "The hero of Cervantes' novel, invoked through the episode at the Duchess's court as a book its first readers could enjoy as pure comedy.",
     'Don Quixote'),
    ('innocent-iii', 'Pope Innocent III',
     "The medieval pope quoted for his catalogue of the human body's indignities, from conception to decay.",
     'Pope Innocent the Third'),
    ('luther', 'Martin Luther',
     "Discussed both as a plain-spoken, quarrelsome opponent of Church etiquette and, through the unrealized 'Luther's Wedding,' as a subject Wagner once considered setting to music.",
     'Luther'),
    ('calvin', 'John Calvin',
     'Named alongside Luther as a source worth consulting on the idea of gods who delight in cruelty.',
     'Calvin'),
    ('heracles', 'Heracles',
     "The Greek hero, invoked as a figure of arduous labor performed under the gaze of witnesses: 'the Heracles of duty.'",
     'Heracles'),
    ('kuno-fischer', 'Kuno Fischer',
     'The German historian of philosophy whose commentary on Spinoza Nietzsche accuses of laboring to misunderstand him.',
     'Kuno Fischer'),
    ('duhring', 'Eugen Dühring',
     'The German philosopher, later a leading anti-Semitic agitator, whose theory that justice originates in resentment Nietzsche attacks by name in both the Second and Third Essays.',
     'E. Dühring|Eugen Dühring|Dühring'),
    ('huxley', 'Thomas Henry Huxley',
     "Cited for his reproach to Herbert Spencer over Spencer's 'administrative Nihilism.'",
     'Huxley'),
    ('goethe', 'Johann Wolfgang von Goethe',
     "Cited on the 'labyrinth of the breast,' as the creator of Faust, and for his claim that there are only thirty-six tragic situations.",
     'Goethe'),
    ('faust', 'Faust',
     "The protagonist of Goethe's drama, invoked to argue that an artist need not himself be what he creates.",
     'Faust'),
    ('achilles', 'Achilles',
     "The hero of Homer's Iliad, invoked as a figure of uncompromising boldness and, later, as an example of a character an author need not resemble.",
     'Achilles'),
    ('aegistheus', 'Aegisthus',
     "The figure Homer's Zeus cites as an example of mortals blaming the gods for disasters of their own making.",
     'Ægistheus'),
    ('zeus', 'Zeus',
     'The king of the Greek gods, quoted via Homer refusing to take the blame for mortal folly, and invoked as an alternative name for blind chance.',
     'Zeus'),
    ('heracleitus', 'Heraclitus',
     'The Greek philosopher of flux, cited for likening the world to a child’s game and for having withdrawn to the temple of Artemis at Ephesus.',
     'Heracleitus'),
    ('adam', 'Adam',
     "The biblical first man, named as the ancestor on whom the curse of humanity's unpayable debt to God is fixed ('original sin').",
     'Adam'),
    ('wagner', 'Richard Wagner',
     'The composer, examined at length as an artist whose late turn to chastity and to the opera Parsifal exemplifies homage to the ascetic ideal.',
     'Richard Wagner|Wagner', 'major'),
    ('feuerbach', 'Ludwig Feuerbach',
     "The philosopher whose motto of 'healthy sensuality' Wagner followed enthusiastically in his youth.",
     'Feuerbach'),
    ('herwegh', 'Georg Herwegh',
     "The poet credited with introducing Wagner to Schopenhauer's philosophy.",
     'Herwegh'),
    ('stendhal', 'Stendhal',
     "The French novelist, whose definition of the beautiful as 'a promise of happiness' Nietzsche sets against Kant's disinterested formula.",
     'Stendhal'),
    ('pygmalion', 'Pygmalion',
     "The sculptor of Greek myth who fell in love with his own statue, cited as evidence against the claim that beauty is contemplated 'without interest.'",
     'Pygmalion'),
    ('epicurus', 'Epicurus',
     'The Greek philosopher, quoted by Schopenhauer on the painless state as the highest good, and later compared to Indian doctrines of redemption through sleep.',
     'Epicurus'),
    ('ixion', 'Ixion',
     "The mythical king condemned to an eternally turning wheel, invoked by Schopenhauer's own words as an image of the will's suffering.",
     'Ixion'),
    ('hegel', 'G. W. F. Hegel',
     "Named among the 'enemies' Nietzsche says Schopenhauer needed in order to keep going.",
     'Hegel'),
    ('descartes', 'René Descartes',
     'Listed among the great philosophers who never married.',
     'Descartes'),
    ('leibnitz', 'Gottfried Wilhelm Leibniz',
     'Listed among the great philosophers who never married.',
     'Leibnitz'),
    ('socrates', 'Socrates',
     'The Athenian philosopher, cited as the one exception among philosophers who married, said to have done so, ironically, only to prove the rule.',
     'Socrates'),
    ('buddha', 'Buddha',
     'The founder of Buddhism, quoted on the birth of his son as a fetter, and on leaving the confinement of the household for freedom.',
     'Buddha'),
    ('vicvamitra', 'King Vicvamitra',
     'The legendary Indian king who, through a thousand years of self-martyrdom, gained the power to build a new heaven.',
     'King Vicvamitra'),
    ('cankara', 'Shankara',
     "The Indian philosopher whose commentaries on redemption through unity with Brahman Nietzsche quotes, via Paul Deussen's translation.",
     'Cankara'),
    ('deussen', 'Paul Deussen',
     "Nietzsche's friend, described here as the first real European expert on Indian philosophy, whose translation of Shankara's commentaries Nietzsche quotes.",
     'Paul Deussen'),
    ('weir-mitchell', 'Silas Weir Mitchell',
     "The American physician after whom the isolating 'rest cure,' invoked as a comparison for priestly asceticism, is named.",
     'Weir-Mitchell'),
    ('pascal', 'Blaise Pascal',
     "Quoted for the ascetic maxim 'il faut s'abêtir' ('one must play the fool').",
     'Pascal'),
    ('st-theresa', 'Teresa of Ávila',
     'The Spanish mystic whose ecstasies Nietzsche cites as a symptom of ascetic self-starvation.',
     'St. Theresa'),
    ('geulincx', 'Arnold Geulincx',
     "The Flemish philosopher whose phrase for self-contempt, 'despectus sui,' Nietzsche borrows.",
     'Geulincx'),
    ('byron', 'Lord Byron',
     'The English poet, said to have written a fully honest personal autobiography.',
     'Lord Byron'),
    ('thomas-moore', 'Thomas Moore',
     "The Irish poet and Byron's literary executor, who burned his friend's papers rather than let the autobiography survive.",
     'Thomas Moore'),
    ('gwinner', 'Wilhelm von Gwinner',
     "Schopenhauer's literary executor, said to have likewise destroyed self-revealing papers.",
     'Gwinner'),
    ('thayer', 'Alexander Wheelock Thayer',
     'The American biographer of Beethoven, said to have abandoned his life of the composer partway through rather than continue.',
     'Thayer'),
    ('beethoven', 'Ludwig van Beethoven',
     "The composer, named as the subject of Thayer's unfinished biography.",
     'Beethoven'),
    ('janssen', 'Johannes Janssen',
     'The Catholic historian whose history of the German Reformation Nietzsche calls harmless and square.',
     'Janssen'),
    ('taine', 'Hippolyte Taine',
     'The French historian and critic cited as a model of fearless, unflinching biography.',
     'Taine'),
    ('ranke', 'Leopold von Ranke',
     "The German historian Nietzsche calls the classic advocate of 'every causa fortior' — every accomplished fact — and 'the cleverest of all the clever opportunists.'",
     'Leopold Ranke'),
    ('copernicus', 'Nicolaus Copernicus',
     "Named as the point from which Nietzsche traces an unbroken progress in man's self-diminishment, after displacing the earth from the center of the universe.",
     'Copernicus'),
    ('doudan', 'Ximénès Doudan',
     'The French essayist quoted on the danger of admiring the unintelligible instead of resting content in the unknown.',
     'Xaver Doudan'),
    ('tolstoi', 'Leo Tolstoy',
     "Named for his late religious 'pity,' one of the few things Nietzsche says still grows in the barren landscape of modern historical writing.",
     'Tolstoi'),
    ('renan', 'Ernest Renan',
     "The French historian of religion Nietzsche mocks, via the phrase 'Renan parfum,' as a scented, half-priest, half-satyr type among modern historians.",
     'Renan'),
    ('anacreon', 'Anacreon',
     "The Greek lyric poet, invoked mock-devotionally ('by St. Anacreon') as patron of kicking rather than merely running away.",
     'Anacreon'),
    ('charles-the-bold', 'Charles the Bold',
     "Duke of Burgundy, whose defiant words against Louis XI ('I fight the universal spider') Nietzsche borrows for humanity's stance toward God.",
     'Charles the Bold'),
    ('louis-xi', 'Louis XI',
     "King of France, Charles the Bold's adversary in the quoted line about fighting 'the universal spider.'",
     'Louis the Eleventh'),
]:
    add(*row)

ids = [e['id'] for e in entities]
assert len(ids) == len(set(ids)), 'duplicate id'

BASE = Path(__file__).resolve().parent
(BASE / 'editorial.json').write_text(json.dumps(dict(
    bookId='genealogy-of-morals',
    contentVersion='2026-09-11.1',
    coverage=(
        'All four reading units (Preface, First Essay, Second Essay, Third Essay) in both English editions. '
        'Named philosophers, historians, poets, theologians, and mythological, scriptural and literary figures '
        'Nietzsche cites by name or unambiguous epithet. Collective peoples and confessions (the Jews, the '
        'Germans, the Greeks, the Romans, Buddhists as a group) and works/texts (the Talmud, the New Testament) '
        'are not bound as persons; see README. One reference ("Sir Christopher" in Shakespeare) is deliberately '
        'left unbound as unresolved.'
    ),
    entities=entities,
), ensure_ascii=False, indent=2) + '\n')

if __name__ == '__main__':
    print(f'{len(entities)} entities written to editorial.json')
