"""Manually authored references, distinct from a cast of Aristotle's treatise."""
import json
from pathlib import Path
entities=[]
def C(id,name,body,aliases=None,kind='person'):
 entities.append(dict(id=id,name=name,category='reference',body=body,subtitle='',kind=kind,aliases=(aliases or name).split('|'),snapshots=[]))
for id,name,body in [
 ('homer','Homer','The ancient Greek poet traditionally credited with the Iliad and Odyssey.'),
 ('empedocles','Empedocles','The Greek philosopher who wrote about nature in verse.'),
 ('sophron','Sophron','The writer of mimes whom Aristotle pairs with Xenarchus.'),
 ('xenarchus','Xenarchus','The writer of mimes whom Aristotle pairs with Sophron.'),
 ('chaeremon','Chaeremon','The poet whose Centaur combines different metres.'),
 ('polygnotus','Polygnotus','The Greek painter Aristotle cites for noble portrayals of people.'),
 ('pauson','Pauson','The painter Aristotle contrasts with Polygnotus.'),
 ('dionysius','Dionysius','The painter cited for portraying people as they are.'),
 ('cleophon','Cleophon','The poet cited for ordinary subjects and plain diction.'),
 ('hegemon','Hegemon','The Thasian poet whom Aristotle credits with inventing parodies.'),
 ('nicochares','Nicochares','The poet named as the author of the Deiliad.'),
 ('timotheus','Timotheus','The poet and musician whose treatment of the Cyclops is compared with Philoxenus’s.'),
 ('philoxenus','Philoxenus','The poet and musician whose treatment of the Cyclops is compared with Timotheus’s.'),
 ('sophocles','Sophocles','The Athenian tragic playwright, author of Oedipus and Antigone.'),
 ('aristophanes','Aristophanes','The Athenian comic playwright.'),
 ('epicharmus','Epicharmus','The early comic poet associated here with Sicily.'),
 ('chionides','Chionides','An early comic poet mentioned alongside Magnes.'),
 ('magnes','Magnes','An early comic poet mentioned alongside Chionides.'),
 ('aeschylus','Aeschylus','The Athenian tragic playwright, credited here with increasing the number of actors.'),
 ('crates','Crates','The Athenian comic playwright credited with moving beyond personal lampoon.'),
 ('euripides','Euripides','The Athenian tragic playwright, author of Medea and other plays discussed here.'),
 ('zeuxis','Zeuxis','The Greek painter used as a point of comparison for dramatic characterization.'),
 ('herodotus','Herodotus','The Greek historian whose writing is contrasted with poetry.'),
 ('alcibiades','Alcibiades','The Athenian public figure cited as a named subject of lampoon.'),
 ('agathon','Agathon','The tragic playwright whose work supplies several examples in the discussion.'),
 ('mitys','Mitys','The man of Argos commemorated by the statue in Aristotle’s example of striking coincidence.'),
 ('astydamas','Astydamas','The tragic playwright named as the author of an Alcmaeon.'),
 ('carcinus','Carcinus','The tragic playwright whose plays supply examples of recognition and staging.'),
 ('polyidus','Polyidus','The sophist whose handling of the Iphigenia story Aristotle discusses.'),
 ('theodectes','Theodectes','The tragic playwright whose Tydeus and Lynceus are discussed.'),
 ('dicaeogenes','Dicaeogenes','The playwright named as the author of the Cyprians.'),
 ('protagoras','Protagoras','The Greek sophist whose criticism of Homer’s opening invocation is discussed.'),
 ('sthenelus','Sthenelus','The poet whose diction is cited alongside Cleophon’s.'),
 ('eucleides','Eucleides','The critic called Eucleides the elder, who mocked poets’ manipulation of syllables.'),
 ('ariphrades','Ariphrades','The critic who ridiculed the unusual phrasing of tragic poets.'),
 ('xenophanes','Xenophanes','The Greek poet and thinker associated with criticism of stories about the gods.'),
 ('hippias','Hippias of Thasos','The interpreter cited for resolving passages through accent or breathing.'),
 ('glaucon','Glaucon','The critic cited on readers who blame poets on the basis of their own assumptions.'),
 ('mynniscus','Mynniscus','The older actor who criticized Callippides’s extravagant gestures.'),
 ('callippides','Callippides','The actor criticized for exaggerated movement.'),
 ('pindarus','Pindarus','The performer mentioned in the discussion of excessive acting.'),
 ('sosistratus','Sosistratus','The epic reciter criticized for overdone gesticulation.'),
 ('mnasitheus','Mnasitheus','The performer from Opus cited for excessive gesture in lyrical competition.')]:C(id,name,body,{'hippias':'Hippias','sosistratus':'Sosi-stratus|Sosistratus'}.get(id))
for id,name,body,aliases in [
 ('margites','Margites','The foolish hero whose name titles the comic poem attributed here to Homer.','Margites'),
 ('heracles','Heracles','The Greek hero whose many exploits illustrate Aristotle’s point about unity of action.','Heracles'),
 ('odysseus','Odysseus','The Greek hero of the Odyssey, husband of Penelope and father of Telemachus.','Odysseus'),
 ('oedipus','Oedipus','The legendary king of Thebes, central to the tragedy Aristotle repeatedly discusses.','Oedipus'),
 ('orestes','Orestes','The son of Agamemnon, brother of Iphigenia and Electra, appearing in several dramatic examples.','Orestes'),
 ('iphigenia','Iphigenia','Agamemnon’s daughter and Orestes’s sister, the subject of several plays discussed here.','Iphigenia'),
 ('lynceus','Lynceus','The Greek legendary figure whose story appears in Theodectes’s tragedy.','Lynceus'),
 ('danaus','Danaus','The legendary king associated with the story of Lynceus.','Danaus'),
 ('thyestes','Thyestes','The member of the royal house of Atreus whose story is a subject of tragedy.','Thyestes'),
 ('alcmaeon','Alcmaeon','The son of Eriphyle whose family story appears in tragic poetry.','Alcmaeon'),
 ('meleager','Meleager','The Greek hero named among the families and figures used in tragedy.','Meleager'),
 ('telephus','Telephus','The legendary king of Mysia and a subject of tragedy.','Telephus'),
 ('aegisthus','Aegisthus','Clytemnestra’s partner and a figure in the story of Orestes.','Aegisthus'),
 ('clytemnestra','Clytemnestra','The wife of Agamemnon and mother of Orestes.','Clytemnestra'),
 ('eriphyle','Eriphyle','The mother of Alcmaeon in the tragic family story.','Eriphyle'),
 ('medea','Medea','The woman from Colchis, wife of Jason, whose story Euripides dramatized.','Medea'),
 ('telegonus','Telegonus','Odysseus’s son in the story dramatized in the Wounded Odysseus.','Telegonus'),
 ('antigone','Antigone','Oedipus’s daughter, the title figure of Sophocles’s play.','Antigone'),
 ('haemon','Haemon','Creon’s son and Antigone’s betrothed in Sophocles’s play.','Haemon'),
 ('creon','Creon','The ruler of Thebes and father of Haemon in the Antigone example.','Creon'),
 ('cresphontes','Cresphontes','The son of Merope in the recognition scene discussed here.','Cresphontes'),
 ('merope','Merope','The mother in the recognition scene from Cresphontes.','Merope'),
 ('helle','Helle','The mythological figure whose name titles a play cited for a recognition scene.','Helle'),
 ('menelaus','Menelaus','The Spartan king and husband of Helen, appearing in a dramatic example.','Menelaus'),
 ('scylla','Scylla','The mythological figure named in the Scylla example from a dithyramb.','Scylla'),
 ('melanippe','Melanippe','The title figure of the tragedy cited for an inappropriately learned speech.','Melanippe'),
 ('achilles','Achilles','The Greek warrior of the Trojan War, son of Peleus.','Achilles'),
 ('tyro','Tyro','The woman of Greek legend whose story supplies a recognition example.','Tyro'),
 ('tereus','Tereus','The legendary Thracian king whose story is dramatized in a play cited here.','Tereus'),
 ('alcinous','Alcinous','The Phaeacian king who hosts Odysseus in the Odyssey.','Alcinous'),
 ('tydeus','Tydeus','The Greek hero whose name titles a play by Theodectes.','Tydeus'),
 ('phineidae','The sons of Phineus','The legendary family named by the title Phineidae.','Phineidae'),
 ('amphiaraus','Amphiaraus','The legendary seer whose story is used in an example about staging.','Amphiaraus'),
 ('ajax','Ajax','The Greek warrior whose story provides an example of tragic suffering.','Ajax'),
 ('ixion','Ixion','The figure of Greek legend whose story is cited as a tragic subject.','Ixion'),
 ('peleus','Peleus','Achilles’s father, a legendary king and subject of drama.','Peleus'),
 ('prometheus','Prometheus','The Titan whose story is used in Greek tragedy.','Prometheus'),
 ('niobe','Niobe','The mother of Greek legend whose story appears in tragic poetry.','Niobe'),
 ('sisyphus','Sisyphus','The figure of Greek legend referred to in the discussion of drama.','Sisyphus'),
 ('philoctetes','Philoctetes','The Greek archer whose story is the subject of tragedies discussed here.','Philoctetes'),
 ('neoptolemus','Neoptolemus','The son of Achilles who takes part in the Trojan War.','Neoptolemus'),
 ('eurypylus','Eurypylus','The warrior named among the subjects drawn from the Little Iliad.','Eurypylus'),
 ('hector','Hector','The Trojan warrior and opponent of Achilles in the Iliad.','Hector'),
 ('laius','Laius','The earlier king of Thebes in the story of Oedipus.','Laius'),
 ('electra','Electra','Agamemnon’s daughter and Orestes’s sister, a subject of tragedy.','Electra'),
 ('dolon','Dolon','The Trojan scout discussed in an example from Homer.','Dolon'),
 ('ganymede','Ganymede','The youth of Greek myth who serves as cupbearer to the gods.','Ganymede'),
 ('icarius','Icarius','Penelope’s father in the question Aristotle discusses about Telemachus’s journey.','Icarius'),
 ('icadius','Icadius','The name given to Odysseus’s father-in-law in the alternative Cephallenian account Aristotle reports.','Icadius'),
 ('telemachus','Telemachus','The son of Odysseus and Penelope.','Telemachus'),
 ('aegeus','Aegeus','The king of Athens whose appearance in Medea Aristotle discusses.','Aegeus'),
 ('ares','Ares','The Greek god of war.','Ares'),
 ('zeus','Zeus','The chief god of the Greek pantheon.','Zeus'),
 ('dionysus','Dionysus','The Greek god associated with wine and theatre.','Dionysus'),
 ('poseidon','Poseidon','The Greek sea god, an opponent of Odysseus in the Odyssey.','Poseidon')]:C(id,name,body,aliases,'cultural-figure')
C('cleon','Cleon, the son','The son in the grammatical example “Cleon son of Cleon”; no historical person is identified.','Cleon','hypothetical-person')
C('cleon-father','Cleon, the father','The father in the grammatical example “Cleon son of Cleon”; no historical person is identified.','Cleon','hypothetical-person')
C('theodorus','Theodorus, the example name','The personal name used to illustrate the parts of a compound word; no particular historical person is identified.','Theodorus','hypothetical-person')
C('hermocaicoxanthus','Hermo-caico-xanthus','The compound personal name used as a linguistic example.','Hermo-caico-xanthus','hypothetical-person')
C('cyclops','The Cyclops','The one-eyed giant whose different portrayals by Timotheus and Philoxenus are compared.','Cyclopes','cultural-figure')
C('phorcides','The daughters of Phorcys','The mythical sisters named by the play title Phorcides.','Phorcides','group')
C('phthiotides','The women of Phthia','The women named by the play title Phthiotides.','Phthiotides','group')
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='poetics',contentVersion='2026-09-10.1',coverage='All 26 sections, both English editions: named writers, artists, performers, critics, cited story figures and the grammatical example Cleon. Work titles without an identified person are not turned into people.',entities=entities),ensure_ascii=False,indent=2)+'\n')
