#!/usr/bin/env python3
"""Join the lead ledger with the independent reviewer's verdicts.

Writes:
- ledger/final-mapping.jsonl: one record per entry, the integration input
- LEDGER.md: the human-readable mapping/drop ledger (all 438 rows)

Disagreements must be resolved explicitly in RESOLUTIONS, or they are recorded
as unresolved. An unresolved entry carries finalDecision "unresolved" and no
span; integration must not bind it.
"""
import hashlib
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# entryId -> (final decision, final class, span or None, resolution note).
# Filled in after reading the reviewer's report; see REVIEW-RESOLUTION in README.
RESOLUTIONS = {}


# Label equivalences between the two reviewers' vocabularies (same meaning).
CLASS_ALIASES = {"removed-with-duplicate-text": "removed"}


def norm_class(decision, cls):
    cls = (cls or "").split("/")[-1]
    cls = CLASS_ALIASES.get(cls, cls)
    return f"{decision}/{cls}"


def span_key(s):
    return None if not s else (s["startOffset"], s["endOffset"], s["text"])


def main():
    lead = [json.loads(l) for l in open(ROOT / "ledger" / "decisions.jsonl")]
    rev = {}
    for l in open(ROOT / "review" / "independent-verdicts.jsonl"):
        if l.strip():
            r = json.loads(l)
            rev[r["entryId"]] = r
    missing = [x["entryId"] for x in lead if x["entryId"] not in rev]
    assert not missing, f"reviewer verdicts missing: {missing}"
    out, rows = [], []
    for x in lead:
        r = rev[x["entryId"]]
        rdec = r["decision"].split("/")[0]
        rcls = norm_class(rdec, r.get("decisionClass"))
        lcls = norm_class(x["decision"], x["decisionClass"])
        agree = rdec == x["decision"] and rcls == lcls and span_key(r.get("finalCandidateSpan")) == span_key(x["finalCandidateSpan"])
        if agree:
            fdec, fcls, fspan, note = x["decision"], x["decisionClass"], x["finalCandidateSpan"], None
        elif x["entryId"] in RESOLUTIONS:
            fdec, fcls, fspan, note = RESOLUTIONS[x["entryId"]]
        else:
            fdec, fcls, fspan, note = "unresolved", "unresolved", None, "Lead and reviewer disagree; not resolved."
        rec = dict(x)
        rec["independentReview"] = {"decision": rdec, "decisionClass": r.get("decisionClass"),
                                    "finalCandidateSpan": r.get("finalCandidateSpan"),
                                    "evidence": r.get("evidence"), "concern": r.get("concern"),
                                    "agreesWithLead": agree}
        rec["finalDecision"], rec["finalDecisionClass"], rec["finalSpan"], rec["resolution"] = fdec, fcls, fspan, note
        out.append(rec)
        e = rec["existingMention"]
        f = fspan
        rows.append(f"| {x['entryId']} | `{x['characterId']}` | {x['chapterNumber']}.{x['paragraphIndex']} | "
                    f"`{e['text']}` {e['startOffset']}–{e['endOffset']} | "
                    + (f"`{x['proposedCandidateSpan']['text']}` {x['proposedCandidateSpan']['startOffset']}–{x['proposedCandidateSpan']['endOffset']}" if x["proposedCandidateSpan"] else "none")
                    + f" | **{fdec}** ({fcls}) | "
                    + (f"`{f['text']}` {f['startOffset']}–{f['endOffset']}" if f else "none")
                    + f" | {'yes' if agree else ('resolved' if x['entryId'] in RESOLUTIONS else 'NO')} | "
                    + (x['rationale'] + (' Resolution: ' + note if note else '')).replace("|", "\\|") + " |")
    with open(ROOT / "ledger" / "final-mapping.jsonl", "w") as fh:
        for rec in out:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
    c = Counter((r["finalDecision"], r["finalDecisionClass"]) for r in out)
    agreed = sum(r["independentReview"]["agreesWithLead"] for r in out)
    md = ["# Mapping/drop ledger: Crime and Punishment character mentions", "",
          "Generated by `tools/finalize.py` from `ledger/decisions.jsonl` (lead) and `review/independent-verdicts.jsonl` (independent reviewer). Do not edit by hand. The integration input is `ledger/final-mapping.jsonl`.",
          "", "Offsets are UTF-16 code units into the normalized paragraph. The chapter is 1-based and the paragraph 0-based. The existing span is in the live modern-en (`914bcdfa…`); the proposed and final spans are in the accepted candidate (`18be4155…`).",
          "", f"Agreement between lead and independent reviewer: **{agreed} of {len(out)}**.", "",
          "| Final decision | Class | Entries |", "|---|---|---|"]
    md += [f"| {d} | {k} | {n} |" for (d, k), n in sorted(c.items())]
    md += ["", "| Entry | Character ID | Ch.¶ | Existing mention | Proposed candidate span | Decision | Final span | Reviewer agrees | Evidence |",
           "|---|---|---|---|---|---|---|---|---|"] + rows
    (ROOT / "LEDGER.md").write_text("\n".join(md) + "\n")
    print(len(out), "agreed", agreed, c)
    print("final-mapping.jsonl", hashlib.sha256((ROOT / "ledger" / "final-mapping.jsonl").read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
