"""Manually authored recognition cards for the narrative and appendix."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))
for row in [
('douglass','Frederick Douglass','The author and narrator, recounting his life under slavery.','Frederick Augustus Washington Bailey|Frederick Douglass|FREDERICK DOUGLASS|Frederick Bailey|Frederick Johnson|Frederick|Freddy|Fred|Douglass|Stanley','central'),
('harriet','Harriet Bailey','Douglass’s mother, enslaved and hired out away from her son.','Harriet Bailey','major'),
('isaac-grandfather','Isaac Bailey','Douglass’s maternal grandfather; Betsey Bailey’s husband.',''),
('betsey','Betsey Bailey','Douglass’s maternal grandmother; Harriet Bailey’s mother.','Betsey Bailey','major'),
('stewart','Mr. Stewart','The man to whom Douglass’s mother is hired out.','Mr. Stewart'),
('anthony','Captain Anthony','Douglass’s first enslaver, who manages Colonel Lloyd’s plantations.','Captain Anthony|Anthony','major'),
('plummer','Mr. Plummer','The overseer employed by Captain Anthony.','Mr. Plummer|Plummer'),
('hester','Aunt Hester','Douglass’s aunt, enslaved in Captain Anthony’s household.','Aunt Hester|Hester'),
('ned','Ned Roberts','A man enslaved by Colonel Lloyd and a companion of Aunt Hester; also called Lloyd’s Ned.','Ned Roberts|Lloyd’s Ned'),
('andrew','Andrew Anthony','Captain Anthony’s son and Lucretia’s brother.','Master Andrew|Andrew'),
('richard','Richard Anthony','Captain Anthony’s younger son; Andrew and Lucretia’s brother.','Richard'),
('lucretia','Lucretia Auld','Captain Anthony’s daughter and Thomas Auld’s wife.','Mrs. Lucretia Auld|Lucretia Auld|Mrs. Lucretia|Lucretia','major'),
('thomas','Thomas Auld','Lucretia’s husband and Hugh Auld’s brother; captain of Colonel Lloyd’s sloop.','Captain Thomas Auld|Master Thomas Auld|Thomas Auld|Captain Auld|Master Thomas','major'),
('lloyd','Colonel Edward Lloyd','The wealthy Maryland plantation owner whose estates Captain Anthony manages.','Colonel Edward Lloyd|Colonel Lloyd','major'),
('peter','Peter','One of the enslaved men who crew Colonel Lloyd’s sloop.','Peter'),
('isaac-crew','Isaac','One of the enslaved men who crew Colonel Lloyd’s sloop.',''),
('rich','Rich','An enslaved crew member aboard Colonel Lloyd’s sloop.','Rich'),
('jake','Jake','One of the enslaved men who crew Colonel Lloyd’s sloop.','Jake'),
('willis','Noah Willis','The overseer at Colonel Lloyd’s Wye Town plantation.','Noah Willis'),
('townsend','Mr. Townsend','The overseer at Colonel Lloyd’s New Design plantation.','Mr. Townsend'),
('woolfolk','Austin Woolfolk','The Baltimore slave trader to whom Colonel Lloyd sends people for sale.','Austin Woolfolk'),
('severe','Mr. Severe','The overseer at Colonel Lloyd’s home plantation before Mr. Hopkins.','Mr. Severe|Severe'),
('hopkins-overseer','Mr. Hopkins','The overseer who succeeds Mr. Severe at Colonel Lloyd’s home plantation.',''),
('mdurmond','Mr. M’Durmond','Colonel Lloyd’s chief gardener.','Mr. M’Durmond|M’Durmond'),
('barney-old','Old Barney','An enslaved stable keeper on Colonel Lloyd’s plantation; young Barney’s father.','old Barney|Old Barney'),
('barney-young','Young Barney','An enslaved stable keeper on Colonel Lloyd’s plantation; old Barney’s son.','young Barney|Young Barney'),
('edward-lloyd','Edward Lloyd','One of Colonel Lloyd’s sons.',''),
('murray','Murray Lloyd','One of Colonel Lloyd’s sons.','Murray'),
('daniel-lloyd','Daniel Lloyd','Colonel Lloyd’s son, whom young Douglass helps on hunting trips.','Master Daniel Lloyd|Daniel Lloyd|Master Daniel'),
('winder','Mr. Winder','One of Colonel Lloyd’s sons-in-law.','Mr. Winder|Winder'),
('nicholson','Mr. Nicholson','One of Colonel Lloyd’s sons-in-law.','Mr. Nicholson|Nicholson'),
('lowndes','Mr. Lowndes','One of Colonel Lloyd’s sons-in-law.','Mr. Lowndes|Lowndes'),
('wilkes','William Wilkes','The enslaved coach driver at Colonel Lloyd’s plantation.','William Wilkes'),
('jepson','Jacob Jepson','A neighboring enslaver whose people argue with Colonel Lloyd’s over their masters’ wealth.','Jacob Jepson|Mr. Jepson'),
('gore','Austin Gore','The overseer who succeeds Mr. Hopkins at Colonel Lloyd’s home plantation.','Mr. Austin Gore|Austin Gore|Mr. Gore|Gore'),
('demby','Demby','A man enslaved by Colonel Lloyd and subject to overseer Austin Gore.','Demby'),
('lanman','Thomas Lanman','A white resident of St. Michael’s whom Douglass names in his account of violence against enslaved people.','Mr. Thomas Lanman|Thomas Lanman'),
('giles','Giles Hicks','The husband of the woman who enslaves Anna’s young cousin.','Mr. Giles Hicks|Giles Hicks'),
('mrs-hicks','Mrs. Hicks','Giles Hicks’s wife, who enslaves Anna’s young cousin.','Mrs. Hicks'),
('bondly','Beal Bondly','The enslaver whose property borders Colonel Lloyd’s.','Mr. Beal Bondly|Beal Bondly|Mr. Bondly|Bondly'),
('hugh','Hugh Auld','Thomas Auld’s brother and Sophia’s husband, in whose Baltimore household Douglass is enslaved.','Mr. Hugh Auld|Master Hugh|Hugh Auld|Hugh','major'),
('sophia','Sophia Auld','Hugh Auld’s wife and little Thomas’s mother, in whose Baltimore household Douglass lives.','Sophia Auld','major'),
('little-thomas','Thomas Auld, the child','Hugh and Sophia Auld’s young son, whom Douglass is sent to look after.','Little Thomas|little Thomas'),
('cousin-tom','Cousin Tom','Douglass’s cousin, whose descriptions of Baltimore make him eager to see it.','Cousin Tom'),
('curtis','Mr. Curtis','The Baltimore slaughterhouse proprietor to whom a cargo of sheep is delivered.','Mr. Curtis'),
('gardner','William Gardner','The Baltimore shipbuilder who runs the shipyard on Fells Point.','Mr. William Gardner|William Gardner|Mr. Gardner|Gardner'),
('thomas-hamilton','Thomas Hamilton','The Baltimore enslaver whose household includes Henrietta and Mary.','Mr. Thomas Hamilton|Thomas Hamilton'),
('mrs-hamilton','Mrs. Hamilton','Thomas Hamilton’s wife, who enslaves Henrietta and Mary.','Mrs. Hamilton'),
('henrietta','Henrietta','One of the two women enslaved by Thomas and Mrs. Hamilton in Baltimore.','Henrietta'),
('mary','Mary','One of the two women enslaved by Thomas and Mrs. Hamilton in Baltimore.','Mary'),
('durgin','Durgin','One of the proprietors of the shipyard near Douglass’s Baltimore home.','Durgin'),
('bailey-yard','Bailey, the shipyard proprietor','Durgin’s partner in the Baltimore shipyard where Douglass watches carpenters mark timber.',''),
('waters','Mr. Waters','The proprietor of the wharf where Douglass helps two Irish laborers unload stone.','Mr. Waters'),
('rowe','Captain Rowe','The captain of the schooner Wild Cat, on which Douglass travels back to be valued with Anthony’s estate.','Captain Rowe'),
('amanda','Amanda Auld','Thomas and Lucretia Auld’s daughter.',''),
('rowena','Rowena Auld','Thomas Auld’s second wife, born Rowena Hamilton; William Hamilton’s daughter.','Rowena Hamilton'),
('william-hamilton','William Hamilton','Rowena Auld’s father and an enslaver near St. Michael’s.','Master William Hamilton|Mr. William Hamilton|William Hamilton'),
('dodson','Captain Edward Dodson','The captain of the sloop Amanda, which takes Douglass from Baltimore to St. Michael’s.','Captain Edward Dodson'),
('eliza','Eliza','Douglass’s sister, enslaved with him in Thomas Auld’s household.','Eliza'),
('priscilla','Priscilla','Douglass’s aunt, enslaved in Thomas Auld’s household.','Priscilla'),
('henny','Henny','A woman enslaved by Thomas Auld, with an arm badly injured in childhood.','Henny'),
('storks','Mr. Storks','One of the preachers who stays at Thomas Auld’s house.','Mr. Storks|Storks'),
('ewery','Mr. Ewery','One of the preachers who stays at Thomas Auld’s house.','Ewery'),
('humphry','Mr. Humphry','One of the preachers who stays at Thomas Auld’s house.','Humphry'),
('hickey','Mr. Hickey','One of the preachers who stays at Thomas Auld’s house.','Hickey'),
('cookman','George Cookman','The minister whose kindness earns the trust of the people enslaved in Thomas Auld’s household.','George Cookman|Mr. Cookman|Cookman'),
('harrison','Samuel Harrison','A wealthy local enslaver mentioned in connection with George Cookman and Edward Covey.','Samuel Harrison'),
('wilson','Mr. Wilson','The young white man who begins a Sabbath school for enslaved people.','Mr. Wilson'),
('west','Garrison West','A Methodist class leader who opposes schooling for enslaved people.','Garrison West|Mr. West'),
('fairbanks','Wright Fairbanks','A Methodist class leader who opposes schooling for enslaved people.','Wright Fairbanks|Mr. Fairbanks'),
('covey','Edward Covey','The farmer and notorious slave-breaker to whom Thomas Auld hires Douglass.','Mr. Edward Covey|Edward Covey|Mr. Covey|Covey','major'),
('caroline','Caroline','The enslaved woman purchased by Edward Covey.','Caroline'),
('lowe','Thomas Lowe','The man from whom Edward Covey purchases Caroline.','Thomas Lowe'),
('smith','Bill Smith','One of the men working alongside Douglass on Edward Covey’s farm.','Bill Smith|Smith|Bill'),
('hughes','William Hughes','One of the men working on Edward Covey’s farm.','William Hughes|Hughes'),
('eli','Eli','One of the men working alongside Douglass on Edward Covey’s farm.','Eli'),
('kemp','Mrs. Kemp','The neighbor through whose fields Douglass passes on his way to St. Michael’s.','Mrs. Kemp'),
('sandy','Sandy Jenkins','An enslaved man who advises Douglass; his wife is free and lives nearby.','Sandy Jenkins|Sandy','major'),
('freeland','William Freeland','The farmer near St. Michael’s who hires Douglass after his year with Covey.','Mr. William Freeland|William Freeland|Mr. Freeland|Freeland','major'),
('weeden','Daniel Weeden','A Reformed Methodist minister and enslaver near William Freeland’s farm.','Rev. Daniel Weeden|Daniel Weeden|Weeden'),
('rigby','Rigby Hopkins','A Reformed Methodist minister and enslaver near William Freeland’s farm.','Rev. Rigby Hopkins|Rigby Hopkins'),
('henry-harris','Henry Harris','A man enslaved by William Freeland and a close companion of Douglass.','Henry Harris'),
('john-harris','John Harris','A man enslaved by William Freeland and a close companion of Douglass.','John Harris'),
('handy','Handy Caldwell','One of the enslaved men hired to work on William Freeland’s farm.','Handy Caldwell'),
('henry-bailey','Henry Bailey','Douglass’s uncle, enslaved by Thomas Auld.','Henry Bailey'),
('charles','Charles Roberts','The husband of Douglass’s aunt, enslaved by William Hamilton.','Charles Roberts|Charles'),
('tom-graham','Tom Graham','One of the constables who comes to arrest Douglass and his companions.','Tom Graham'),
('betsy-freeland','Betsy Freeland','William Freeland’s mother.','Betsy Freeland'),
('joseph-graham','Joseph Graham','The sheriff who runs the Easton jail.','Mr. Joseph Graham|Joseph Graham'),
('watson','Esquire Watson','The Baltimore official Hugh Auld consults about the assault on Douglass.','Esquire Watson|Mr. Watson|Watson'),
('price','Walter Price','The shipyard owner for whom Hugh Auld works as foreman.','Mr. Walter Price|Walter Price'),
('butler','Mr. Butler','The Baltimore shipyard owner from whom Douglass obtains work.','Mr. Butler'),
('ruggles','David Ruggles','The New York abolitionist who assists people escaping slavery.','Mr. David Ruggles|David Ruggles|Mr. Ruggles','major'),
('anna','Anna Murray','Douglass’s intended wife, a free woman from Maryland.','Anna Murray|Anna','major'),
('pennington','James W. C. Pennington','The minister who conducts Frederick and Anna’s marriage ceremony in New York.','Rev. J. W. C. Pennington|J. W. C. Pennington|JAMES W. C. PENNINGTON'),
('michaels','Mrs. Michaels','A witness at Frederick and Anna’s wedding in New York.','Mrs. Michaels'),
('shaw','Mr. Shaw','The Newport contact to whom David Ruggles directs Douglass for help.','Mr. Shaw'),
('ricketson','Joseph Ricketson','A New Bedford resident who befriends Frederick and Anna on their journey.','Joseph Ricketson'),
('taber','William C. Taber','A New Bedford resident who befriends Frederick and Anna on their journey.','William C. Taber'),
('nathan','Nathan Johnson','The New Bedford abolitionist who welcomes Frederick and Anna into his home.','Mr. Nathan Johnson|Nathan Johnson|Mr. Johnson','major'),
('mrs-johnson','Polly Johnson','Nathan Johnson’s wife and fellow abolitionist, who welcomes Frederick and Anna.','Mrs. Johnson'),
('coffin','William C. Coffin','The abolitionist who encourages Douglass to address the Nantucket convention.','Mr. William C. Coffin|William C. Coffin'),
]:add(*row)
for row in [
('ham','Ham','The biblical figure whose descendants are invoked in arguments Douglass examines about slavery.','Ham'),
('job','Job','The biblical figure whose wealth supplies a comparison for Colonel Lloyd’s possessions.','Job'),
('sheridan','Richard Brinsley Sheridan','The Irish-born orator whose speech on Catholic emancipation Douglass reads.','Sheridan'),
('webster','Noah Webster','The author of the spelling book Douglass uses while learning to write.','Webster'),
('whittier','John Greenleaf Whittier','The antislavery poet quoted in Douglass’s account of his grandmother.','Whittier'),
('napoleon','Napoleon Bonaparte','The French military ruler invoked in a comparison with Thomas Auld’s manner.','Napoleon'),
('patrick','Patrick Henry','The American revolutionary orator quoted on liberty and death.','Patrick Henry'),
('pilate','Pontius Pilate','The Roman governor associated with Jesus’s trial, invoked in the appendix’s religious critique.','Pilate'),
('herod','Herod Antipas','The ruler associated with Jesus’s trial, paired with Pilate in the appendix’s poem.','Herod'),
]:add(*row,category='reference')
add('god','God','The divine creator whom Douglass invokes in his reflections on slavery and freedom.','God Almighty|Most High God|God|Creator|Providence|Lord','reference','religious-figure')
add('jesus','Jesus Christ','The central figure of Christianity, whose teachings Douglass contrasts with slaveholding religion.','Lord Jesus Christ|Jesus Christ|Christ|Jesus|Merciful Son','reference','religious-figure')
for id,name,body in [
('father','Douglass’s father','The white man who fathered Douglass; the narrator does not know his identity with certainty.'),
('brother','Douglass’s younger brother','Douglass’s younger brother, enslaved on the Anthony estate.'),
('cousin-anna','Anna’s cousin','Douglass’s wife’s young cousin, enslaved in the Hicks household.'),
('old-oysterman','The elderly oyster gatherer','An elderly man enslaved by Colonel Lloyd who gathers oysters for food.'),
('sandy-wife','Sandy’s wife','Sandy Jenkins’s wife, a free woman living near Covey’s farm.'),
('mrs-covey','Mrs. Covey','Edward Covey’s wife.'),
('harrison-man','The man hired from Harrison','A married enslaved man hired by Edward Covey from Samuel Harrison.'),
('irishmen','The two Irish laborers','The men Douglass helps unload a scow at Mr. Waters’s wharf.'),
('schoolboys','The Baltimore schoolboys','The boys from whom Douglass obtains reading lessons and practices writing.'),
('anonymous-friend','The Liberator subscriber’s agent','The young man who asks Douglass whether he wants to subscribe to the Liberator.'),
]:add(id,name,body,kind='group' if id in ['irishmen','schoolboys'] else 'unnamed-role')
for name in ['Jack','Nell','Tony','Doll','Sam','Jacob','Tom','Dick','Ned','Nanny']:
 add('parody-'+name.lower(),name+' in the parody','An enslaved person named in the appendix’s satirical poem about slaveholding religion.','',category='reference',kind='literary-figure')
add('darg','John P. Darg','The enslaver involved in the New York case mentioned in connection with David Ruggles.','',category='reference')
for e in entities:
 if e['id']=='anna':e['snapshots']=[dict(after=[11,7],body='Douglass’s wife, a free woman from Maryland.')]
 if e['id']=='sophia':e['snapshots']=[dict(after=[7,0],body='Hugh Auld’s wife and little Thomas’s mother.')]
 if e['id']=='harriet':e['snapshots']=[dict(after=[3,0],body='Douglass’s mother.')]
 if e['id']=='betsey':e['snapshots']=[dict(after=[3,0],body='Douglass’s maternal grandmother.')]
 if e['id']=='douglass':e['snapshots']=[dict(after=[3,0],body='The author and narrator.'),dict(after=[11,4],body='The author and narrator, now free after escaping slavery.')]
 if e['id']=='thomas':e['snapshots']=[dict(after=[8,8],body='Douglass’s enslaver in St. Michael’s; Hugh’s brother and Rowena’s husband.')]
 if e['id']=='lucretia':e['snapshots']=[dict(after=[8,5],body='Captain Anthony’s daughter, Thomas Auld’s late wife and Amanda’s mother.')]
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='frederick-douglass',contentVersion='2026-09-10.1',coverage='All eleven chapters and the appendix, in both English editions. Named participants and references, family roles, recurring unnamed people and the appendix parody are reviewed. No claim of exhaustive pronoun coverage; ships, wharves and generic hypothetical people are not treated as personal identities.',entities=entities),ensure_ascii=False,indent=2)+'\n')
