"""Manually authored across all seven stories and their accompanying verse."""
import json
from pathlib import Path
entities=[]
def C(id,name,role,body,aliases='',kind='animal',snapshots=None):
 entities.append(dict(id=id,name=name,category=role,body=body,subtitle='',kind=kind,aliases=aliases.split('|') if aliases else [],snapshots=snapshots or []))
C('mowgli','Mowgli','central','The human raised by wolves, at the center of the first three jungle stories.','Mowgli','person')
C('kotick','Kotick','central','The white fur seal, son of Sea Catch and Matkah.','Kotick|White Seal')
C('rikki','Rikki-tikki-tavi','central','The mongoose living with Teddy’s family, the main character of the bungalow story.','Rikki-tikki-tavi|Rikki-tikki|Rikki-Tikki-Tavi|Rikki')
C('little-toomai','Little Toomai','central','The young son of the elephant driver Big Toomai.','Little Toomai','person',snapshots=[dict(after=[6,81],name='Toomai of the Elephants',body='Big Toomai’s young son, honored as Toomai of the Elephants.')])
for id,name,body,aliases in [
 ('father-wolf','Father Wolf','The wolf who raises Mowgli with Mother Wolf.','Father Wolf'),
 ('mother-wolf','Mother Wolf','Mowgli’s wolf mother, also called Raksha.','Mother Wolf|Raksha'),
 ('bagheera','Bagheera','The black panther, Mowgli’s friend and protector.','Bagheera|Black Panther'),
 ('baloo','Baloo','The bear who teaches Mowgli the Law of the Jungle.','Baloo'),
 ('shere-khan','Shere Khan','The lame tiger, the chief enemy of Mowgli and his wolf family.','Shere Khan|Lungri'),
 ('kaa','Kaa','The great rock python of the jungle.','Kaa'),
 ('gray-brother','Gray Brother','Mother Wolf’s eldest cub and Mowgli’s wolf brother.','Gray Brother'),
 ('sea-catch','Sea Catch','Kotick’s father, a large fighting fur seal.','Sea Catch'),
 ('matkah','Matkah','Kotick’s mother and Sea Catch’s mate.','Matkah'),
 ('nag','Nag','The cobra in Teddy’s garden, Nagaina’s mate.','Nag'),
 ('nagaina','Nagaina','The female cobra, Nag’s mate.','Nagaina'),
 ('darzee','Darzee','The tailorbird living in the garden with his mate.','Darzee'),
 ('darzee-wife','Darzee’s wife','The female tailorbird, Darzee’s mate.',''),
 ('kala-nag','Kala Nag','The experienced elephant cared for by the Toomai family.','Kala Nag|Black Snake'),
 ('billy','Billy','The experienced mule carrying the breech-piece for a mountain gun.','Billy'),
 ('troop-horse','The troop horse','Dick Cunliffe’s Australian cavalry horse, Number Fifteen of the Ninth Lancers.','Number Fifteen'),
 ('two-tails','Two Tails','The elephant working with the siege-gun teams.','Two Tails'),
 ('camp-camel','The baggage camel','The camel from the 39th Native Infantry talking with the other camp animals.',''),
]:C(id,name,'major',body,aliases)
C('akela','Akela','major','The lone wolf who leads the Seeonee pack.','Akela|Lone Wolf',snapshots=[dict(after=[1,112],body='The former leader of the Seeonee wolf pack, an ally of Mowgli.')])
C('bandar-log','The Bandar-log','major','The monkey people of the jungle.','Bandar-log|Bandar-Log|Monkey-People|Monkey People|Monkey-Folk','group')
C('gun-bullocks','The gun bullocks','major','The pair of oxen from Hapur who pull the heavy siege guns.','','group')
for id,name,body,aliases,kind in [
 ('tabaqui','Tabaqui','The jackal who scavenges near the wolves and carries news.','Tabaqui','animal'),
 ('rann','Rann','The kite who flies over the jungle.','Rann','animal'),
 ('mang','Mang','The bat named among the jungle animals.','Mang','animal'),
 ('ikki','Ikki','The porcupine who brings jungle gossip.','Ikki','animal'),
 ('mao','Mao','The peacock named among the jungle creatures.','Mao','animal'),
 ('hathi','Hathi','The wild elephant whose authority is recognized in the jungle.','Hathi','animal'),
 ('wolf-pack','The Seeonee wolf pack','The wolves who meet at Council Rock and follow the Law of the Jungle.','Seeonee Wolf Pack|Seeonee Pack|Free People','group'),
 ('wolf-cubs','Mother Wolf’s cubs','The four wolf cubs raised alongside Mowgli.','','group'),
 ('messua','Messua','The village woman whose son Nathoo was taken by a tiger.','Messua','person'),
 ('buldeo','Buldeo','The village hunter who tells stories about the jungle.','Buldeo','person'),
 ('kamya','Kamya','One of the village boys tending cattle with Mowgli.','Kamya','person'),
 ('rama','Rama','The great buffalo bull at the head of Mowgli’s herd.','Rama','animal'),
 ('village-priest','The village priest','The priest who speaks with Messua when Mowgli arrives.','','unnamed-person'),
 ('village-headman','The village headman','One of the elders gathered beneath the village tree.','','unnamed-person'),
 ('village-watchman','The village watchman','The watchman among the men telling stories beneath the tree.','','unnamed-person'),
 ('village-barber','The village barber','The barber who shares the village gossip.','','unnamed-person'),
 ('messua-husband','Messua’s husband','The wealthy villager married to Messua.','','unnamed-person'),
 ('potter','The village potter','The maker of pots whose donkey Mowgli helps.','','unnamed-person'),
 ('potter-donkey','The potter’s donkey','The animal Mowgli helps out of the clay pit.','','animal'),
 ('limmershin','Limmershin','The winter wren who tells the narrator Kotick’s story.','Limmershin|Winter Wren','animal'),
 ('narrator','The narrator','The human storyteller who recounts the animals’ experiences.','','unnamed-person'),
 ('kerick','Kerick Booterin','The chief of the seal hunters on Saint Paul Island, Patalamon’s father.','Kerick Booterin|Kerick','person'),
 ('patalamon','Patalamon','Kerick Booterin’s son, helping with the seal hunt.','Patalamon','person'),
 ('sea-lion','Sea Lion','The sea lion Kotick consults near the seal grounds.','','animal'),
 ('sea-vitch','Sea Vitch','The large walrus whom Kotick consults.','Sea Vitch|Stareek','animal'),
 ('sea-cows','The sea cows','The silent sea mammals that graze on underwater plants.','Sea Cow','group'),
 ('sea-pig','Sea Pig','The porpoise leading the school that Kotick follows.','Sea Pig','animal'),
 ('albatross','The albatross','The old bird who suggests an island for Kotick to visit.','','animal'),
 ('old-seal','The old seal of Masafuera','The elderly survivor of a lost seal rookery whom Kotick meets.','','animal'),
 ('kotick-mate','Kotick’s companion','The female seal who dances with Kotick and waits for him.','','animal'),
 ('rival-seal','The challenging seal','The young seal who questions Kotick’s right to direct the others.','','animal'),
 ('holluschickie','The holluschickie','The young bachelor seals on the breeding beaches.','holluschickie|holluschick','group'),
 ('burgomaster-gull','The Burgomaster gull','The gull who mocks Sea Vitch and answers Kotick.','','animal'),
 ('chuchundra','Chuchundra','The timid muskrat who gives Rikki advice and keeps close to the walls.','Chuchundra','animal'),
 ('karait','Karait','The small, venomous snake in Teddy’s garden.','Karait','animal'),
 ('teddy','Teddy','The English boy whose family takes in Rikki.','Teddy','person'),
 ('alice','Alice','Teddy’s mother.','Alice','person'),
 ('teddy-father','Teddy’s father','The Englishman living with Alice and Teddy in the bungalow.','','unnamed-person'),
 ('coppersmith','The Coppersmith','The bird whose ringing call carries news through the garden.','Coppersmith','animal'),
 ('big-toomai','Big Toomai','Little Toomai’s father and Kala Nag’s driver.','Big Toomai','person'),
 ('petersen','Petersen Sahib','The official in charge of the government’s elephant-catching operations.','Petersen Sahib','person'),
 ('machua','Machua Appa','The chief elephant tracker in Petersen Sahib’s force.','Machua Appa','person'),
 ('pudmini','Pudmini','Petersen Sahib’s female elephant.','Pudmini','animal'),
 ('gunga','Gunga Pershad','One of the elephants addressed at the camp salute.','Gunga Pershad','animal'),
 ('hira','Hira Guj','One of the elephants named at the camp salute.','Hira Guj','animal'),
 ('birchi','Birchi Guj','One of the elephants named at the camp salute.','Birchi Guj','animal'),
 ('kuttar','Kuttar Guj','One of the elephants named at the camp salute.','Kuttar Guj','animal'),
 ('toomai-mother','Little Toomai’s mother','The mother singing to Little Toomai’s younger brother in the camp.','','unnamed-person'),
 ('toomai-brother','Little Toomai’s brother','The small child being soothed by his mother’s lullaby.','','unnamed-person'),
 ('clerk','The pay clerk','The official paying the elephant drivers at the camp.','','unnamed-person'),
 ('vixen','Vixen','The narrator’s fox terrier.','Vixen','animal'),
 ('young-mule','The young mule','The frightened recruit in Billy’s mountain-gun battery.','','animal'),
 ('amir','The Amir of Afghanistan','The Afghan ruler visiting the military review.','Amir','unnamed-person'),
 ('viceroy','The Viceroy of India','The British imperial official hosting the military review.','Viceroy','unnamed-person'),
 ('asian-chief','The Central Asian chief','The visitor accompanying the Amir who asks how the military animals are controlled.','','unnamed-person'),
 ('indian-officer','The Indian officer','The officer explaining the chain of command to the visiting chief.','','unnamed-person'),
 ('shiva','Shiva','The god called Shiv and Mahadeo in the lullaby about feeding all creatures.','Shiva|Shiv|Mahadeo','deity'),
 ('parbati','Parbati','Shiva’s wife in the lullaby, also known as Parvati.','Parbati','deity'),
 ('grasshopper','The grasshopper','The small creature hidden by Parbati in the lullaby.','','animal'),
]:C(id,name,'supporting',body,aliases,kind)
for id,name,body,aliases,kind in [
 ('nathoo','Nathoo','Messua’s missing son; she sees a resemblance between him and Mowgli.','Nathoo','person'),
 ('purun-dass','Purun Dass','The deceased moneylender in Buldeo’s story about the tiger.','Purun Dass','person'),
 ('bagheera-mother','Bagheera’s mother','The panther who died in captivity, recalled by Bagheera.','','animal'),
 ('rikki-mother','Rikki’s mother','The mongoose mother whose advice Rikki remembers.','','animal'),
 ('rikki-father','Rikki’s father','Rikki’s mongoose father, mentioned with his mother.','','animal'),
 ('chua','Chua','Chuchundra’s cousin, a rat.','Chua','animal'),
 ('radha','Radha Pyari','Kala Nag’s mother, the elephant whose advice he remembers.','Radha Pyari|Radha','animal'),
 ('black-toomai','Black Toomai','Big Toomai’s father, who took Kala Nag to Abyssinia.','Black Toomai','person'),
 ('old-toomai','The earlier Toomai of the Elephants','Big Toomai’s grandfather, who saw Kala Nag captured.','','person'),
 ('theodore','Emperor Theodore','The Ethiopian ruler recalled in the account of Kala Nag’s military service.','Emperor Theodore','person'),
 ('dick','Dick Cunliffe','The cavalry trooper who rides the Australian troop horse.','Dick Cunliffe','person'),
 ('sunol','Sunol','The celebrated trotting horse used as a comparison for the cavalry horse’s pride in breeding.','Sunol','animal'),
 ('carbine','Carbine','The Melbourne Cup winner whom the cavalry horse claims as a relative.','Carbine','animal'),
 ('empress','The Empress','Queen Victoria, the imperial sovereign at the top of the chain of command described in the story.','Empress','person'),
 ('alexander','Alexander','Alexander the Great, invoked in the elephants’ marching song.','Alexander','person'),
 ('hercules','Hercules','The classical hero invoked as an image of strength in the elephants’ song.','Hercules','mythological-figure'),
 ('cupid','Cupid','The god of love, mentioned in the monkeys’ song.','Cupid','deity'),
 ('frog-footman','The Frog Footman','The frog servant from Alice’s Adventures in Wonderland, evoked by the sea cows’ bowing.','Frog Footman','literary-figure'),
 ('brahm','Brahm','Brahma, the god in Nag’s story about the cobra’s hood-mark.','Brahm','deity'),
 ('tweedles','Tweedle-dum and Tweedle-dee','The paired comic names invoked in the heading’s contrast between two ways of doing things.','Tweedle-dum|Tweedle-dee','group'),
]:C(id,name,'reference',body,aliases,kind)
p=Path(__file__).resolve().parent
(p/'editorial.json').write_text(json.dumps(dict(contentVersion='2026-09-10.1',coverage='All seven stories and accompanying verse: human and animal protagonists, family ties, named herds and packs, local participants, reported figures and allusions.',entities=entities),ensure_ascii=False,indent=2)+'\n')
