import type { Edition } from '../types'

export type EditionDifficulty = 'Easy' | 'Medium' | 'Hard'

// Editorial review, 23 September 2026: vocabulary, syntax and conceptual density.
// Ratings are reading guidance, not a measured reading age or a quality judgement.
const reviewed: Record<string, EditionDifficulty> = {
  "odyssey:original-en": "Medium",
  "ulysses:original-en": "Hard",
  "war-and-peace:original-en": "Medium",
  "bible:kjv-en": "Hard",
  "bible:web-en": "Medium",
  "gilgamesh:original-en": "Hard",
  "hamlet:original-en": "Hard",
  "macbeth:original-en": "Hard",
  "midsummer:original-en": "Hard",
  "romeo-and-juliet:original-en": "Hard",
  "the-tempest:original-en": "Hard",
  "the-art-of-war:original-en": "Medium",
  "pride-and-prejudice:original-en": "Medium",
  "crime-and-punishment:original-en": "Medium",
  "the-republic:original-en": "Hard",
  "meditations:original-en": "Hard",
  "divine-comedy:original-en": "Hard",
  "jane-eyre:original-en": "Medium",
  "the-aeneid:original-en": "Hard",
  "paradise-lost:original-en": "Hard",
  "frankenstein:original-en": "Medium",
  "the-manual:original-en": "Medium",
  "apology:original-en": "Medium",
  "symposium:original-en": "Medium",
  "phaedo:original-en": "Hard",
  "crito:original-en": "Medium",
  "phaedrus:original-en": "Hard",
  "poetics:original-en": "Hard",
  "moby-dick:original-en": "Hard",
  "great-expectations:original-en": "Medium",
  "the-histories:original-en": "Medium",
  "niels-lyhne:original-da": "Hard",
  "niels-lyhne:original-en": "Medium",
  "imitation-of-christ:original-en": "Hard",
  "jerusalem:original-en": "Easy",
  "the-awakening:original-en": "Medium",
  "brothers-karamazov:original-en": "Hard",
  "iliad:original-en": "Medium",
  "nicomachean-ethics:original-en": "Hard",
  "the-prince:original-it": "Hard",
  "the-prince:original-en": "Medium",
  "beyond-good-and-evil:original-en": "Hard",
  "kant-groundwork:original-en": "Hard",
  "beowulf:original-en": "Hard",
  "candide:original-en": "Medium",
  "democracy-in-america:original-en": "Hard",
  "oedipus-rex:original-en": "Hard",
  "oedipus-at-colonus:original-en": "Hard",
  "antigone:original-en": "Hard",
  "genealogy-of-morals:original-en": "Hard",
  "descartes-meditations:original-en": "Hard",
  "on-liberty:original-en": "Hard",
  "utilitarianism:original-en": "Hard",
  "peloponnesian-war:original-en": "Hard",
  "aristotle-politics:original-en": "Hard",
  "leviathan:original-en": "Hard",
  "fear-and-trembling:original-da": "Hard",
  "fear-and-trembling:original-en": "Hard",
  "communist-manifesto:original-en": "Medium",
  "second-treatise:original-en": "Hard",
  "hume-enquiry:original-en": "Hard",
  "social-contract:original-en": "Hard",
  "wealth-of-nations:original-en": "Hard",
  "werther:original-en": "Medium",
  "faust-part-1:original-de": "Hard",
  "faust-part-1:original-en": "Medium",
  "oresteia:original-en": "Hard",
  "bacchae:original-en": "Hard",
  "medea:original-en": "Hard",
  "confessions:original-en": "Hard",
  "notes-from-underground:original-en": "Hard",
  "magna-carta:original-en": "Medium",
  "us-founding-documents:original-en": "Hard",
  "federalist-papers:original-en": "Hard",
  "frederick-douglass:original-en": "Easy",
  "a-little-princess:original-en": "Easy",
  "jungle-book:original-en": "Medium",
  "around-the-world-80-days:original-en": "Medium",
  "heart-of-darkness:original-en": "Hard",
  "discourse-on-inequality:original-fr": "Hard",
  "discourse-on-inequality:original-en": "Hard",
  "jekyll-and-hyde:original-en": "Medium",
  "walden:original-en": "Hard",
  "vindication-rights-of-woman:original-en": "Hard",
  "comedy-of-errors:original-en": "Hard",
  "merchant-of-venice:original-en": "Hard",
  "henry-v:original-en": "Hard",
  "as-you-like-it:original-en": "Hard",
  "winters-tale:original-en": "Hard",
  "julius-caesar:original-en": "Hard",
  "twelfth-night:original-en": "Hard",
  "measure-for-measure:original-en": "Hard",
  "henry-iv-part-2:original-en": "Hard",
  "merry-wives-of-windsor:original-en": "Hard",
  "othello:original-en": "Hard",
  "king-lear:original-en": "Hard",
  "much-ado-about-nothing:original-en": "Hard",
  "taming-of-the-shrew:original-en": "Hard",
  "antony-and-cleopatra:original-en": "Hard",
  "richard-iii:original-en": "Hard",
  "coriolanus:original-en": "Hard",
  "cymbeline:original-en": "Hard",
  "anna-karenina:original-en": "Medium",
  "don-quixote:original-en": "Medium",
  "essays-montaigne:original-en": "Hard",
  "ivan-ilyich:original-ru": "Medium",
  "ivan-ilyich:original-en": "Medium"
}

export function editionDifficulty(bookId: string, edition: Edition): EditionDifficulty | undefined {
  if (edition.key === 'modern-en') return 'Easy'
  return reviewed[bookId + ':' + edition.key]
}

export function readerEditionLabel(edition: Edition): string {
  return edition.key === 'modern-en' ? 'Tinct Modern English' : edition.label
}
