export const LAB_COPY = {
  documentTitle: 'Tinct lab',
  bookTitle: 'The Odyssey',
  bookAuthor: 'Homer',
  editionLabel: 'Butler prose, 1900',
  chapterLabel: 'Book 1',
  inTheBook: 'In the book',
  inTheBookHint: 'Search, marks, contents, and the people already on this page.',
  search: 'Search',
  searchPlaceholder: 'Search this page.',
  marks: 'Marks',
  marksEmpty: 'No marks on this page yet. Select a sentence and keep it here.',
  contents: 'Contents',
  cast: 'People on this page',
  castEmpty: 'No one named on this page has a safe introduction yet.',
  askAbout: 'Ask about this person',
  compare: 'Compare',
  compareHint: 'Split the page with the modern English facing Butler.',
  hear: 'Hear',
  listen: 'Listen',
  read: 'Read',
  play: 'Play',
  pause: 'Pause',
  back15: 'Back 15s',
  forward15: 'Forward 15s',
  ask: 'Ask',
  done: 'Done',
  askGreeting: '',
  askPlaceholder: 'Ask',
  leaveConversation: 'Leave the conversation.',
  conversationHint: 'Speak. The page stays behind the conversation.',
  listening: 'Listening',
  speaking: 'Speaking',
  connecting: 'Starting',
  stopTalk: 'Stop talking',
  typedPending: 'A reply is on the way.',
  micLabel: 'Speak a question',
  voiceModeLabel: 'Open voice conversation',
  sendLabel: 'Ask',
  youLabel: 'You',
  signInVoice: 'Sign in to ask by voice.',
  signInAsk: 'Sign in to ask about this page.',
  balanceEmpty: 'Your AI chat balance is empty. Top up to continue.',
  askUnavailable: 'Ask is unavailable right now.',
  offlineCast: 'You can read this introduction now. Ask needs a connection.',
  markAction: 'Keep this passage',
  labNote: 'Private lab for the new reading chrome.',
} as const
