export const LAB_COPY = {
  documentTitle: 'Tinct',
  bookTitle: 'The Bible',
  bookAuthor: 'Various',
  editionLabel: 'King James Version (1611)',
  chapterLabel: 'Genesis 1',
  inTheBook: 'This book',
  inTheBookHint: 'Search, marks, contents, and the people already on this page.',
  search: 'Search',
  searchPlaceholder: 'Search this page.',
  marks: 'Marks',
  marksEmpty: 'No marks on this page yet. Select a sentence and keep it here.',
  contents: 'Contents',
  cast: 'People on this page',
  castShort: 'People',
  castEmpty: 'No one named on this page has a safe introduction yet.',
  askAbout: 'Ask about this person',
  compare: 'Compare',
  compareHint: 'Read the aligned edition alongside this page.',
  settings: 'Settings',
  library: 'Library',
  reading: 'Reading',
  layout: 'Layout',
  fullScreen: 'Full screen',
  exitFullScreen: 'Exit full screen',
  previous: 'Previous',
  next: 'Next',
  hear: 'Listen',
  listen: 'Listen',
  read: 'Read',
  talk: 'Talk',
  chat: 'Chat',
  listenNow: 'Listen',
  returnToBook: 'Return to book',
  play: 'Play',
  pause: 'Pause',
  back15: 'Back 15s',
  forward15: 'Forward 15s',
  ask: 'Ask',
  done: 'Done',
  askGreeting: 'Ask about this page.',
  askPlaceholder: 'Ask',
  leaveConversation: 'Leave the conversation.',
  conversationHint: 'Speak. The page stays behind the conversation.',
  listening: 'Listening',
  speaking: 'Speaking',
  connecting: 'Connecting',
  checkingText: 'Checking text',
  preparingAnswer: 'Preparing answer',
  readyToSpeak: 'Ready to speak',
  stopTalk: 'Stop talking',
  typedPending: 'A reply is on the way.',
  micLabel: 'Speak a question',
  voiceModeLabel: 'Open voice conversation',
  sendLabel: 'Send',
  wordmark: 'Tinct',
  youLabel: 'You',
  tinctLabel: 'Tinct',
  yourTurn: 'Your turn',
  signInVoice: 'Sign in to ask by voice.',
  voiceStartFailed: "Couldn't start voice. Type a question instead.",
  signInAsk: 'Sign in to ask about this page.',
  balanceEmpty: 'Your AI chat balance is empty. Top up to continue.',
  askUnavailable: 'Ask is unavailable right now.',
  offlineCast: 'You can read this introduction now. Ask needs a connection.',
  markAction: 'Keep this passage',
  labNote: 'Private lab for the new reading chrome.',
  accountEyebrow: 'Free account',
  accountTitle: 'Create a free account to keep chatting',
  accountBody: 'Reading stays free; a free account keeps the conversation going, saves your place across devices, and includes 30 days of Premium.',
  accountCreate: 'Create free account',
  accountSignIn: 'Sign in',
  accountDismiss: 'Not now',
  secondBookNudge: 'Keep your place across books: ',
  secondBookNudgeLink: 'create a free account',
  secondBookNudgeDismiss: 'Dismiss',
} as const
