export const LAB_COPY = {
  documentTitle: 'Tinct lab',
  bookTitle: 'The Odyssey',
  bookAuthor: 'Homer',
  editionLabel: 'Butler prose, 1900',
  chapterLabel: 'Book 1',
  inTheBook: 'In the book',
  inTheBookHint: 'Search, marks, contents, and the people already on this page.',
  search: 'Search',
  searchPlaceholder: 'Search this page.',
  marks: 'Marks',
  marksEmpty: 'No marks on this page yet. Select a sentence and keep it here.',
  contents: 'Contents',
  cast: 'People on this page',
  castEmpty: 'No one named on this page has a safe introduction yet.',
  askAbout: 'Ask about this person',
  compare: 'Compare',
  compareHint: 'Split the page with the modern English facing Butler.',
  listen: 'Listen',
  ask: 'Ask',
  askPlaceholder: 'Ask about this page.',
  leaveConversation: 'Leave the conversation.',
  conversationHint: 'Speak. The page stays behind the conversation.',
  listening: 'Listening.',
  thinking: 'Thinking.',
  speaking: 'Speaking.',
  readyToAsk: 'Ready when you are.',
  typedReply: 'This lab answers in the conversation, not in a transcript.',
  offlineCast: 'You can read this introduction now. Ask needs a connection.',
  markAction: 'Keep this passage',
  labNote: 'Private lab for the new reading chrome.',
} as const
