"""Manually authored concise cast and cultural-reference copy."""
import json
from pathlib import Path
entities=[]
def C(id,name,role,body,aliases='',kind='person'):
 entities.append(dict(id=id,name=name,category=role,body=body,subtitle='',kind=kind,aliases=aliases.split('|') if aliases else [],snapshots=[]))
C('socrates','Socrates','central','The Athenian philosopher discussing love, the soul and rhetoric with Phaedrus.','SOCRATES|Socrates')
C('phaedrus','Phaedrus','central','Socrates’ companion, an admirer of Lysias with a passion for speeches.','PHAEDRUS|Phaedrus')
C('lysias','Lysias','major','The Athenian speechwriter whose speech on love Phaedrus brings to the discussion.','Lysias')
for id,name,body,aliases in [
 ('cephalus','Cephalus','Lysias and Polemarchus’s father.','Cephalus'),
 ('acumenus','Acumenus','The physician who is a friend of Socrates and Phaedrus, and Eryximachus’s father.','Acumenus'),
 ('epicrates','Epicrates','The Athenian hosting Lysias in the house associated with Morychus.','Epicrates'),
 ('morychus','Morychus','The Athenian whose house is mentioned as the place where Lysias is staying.','Morychus'),
 ('pindar','Pindar','The Greek lyric poet quoted by Socrates.','Pindar'),
 ('herodicus','Herodicus','The physician known for prescribing exercise, recalled for his walking regimen.','Herodicus'),
 ('sappho','Sappho','The Greek lyric poet whom Socrates invokes as a source of inspiration about love.','Sappho'),
 ('anacreon','Anacreon','The Greek lyric poet associated with love and song.','Anacreon'),
 ('simmias','Simmias of Thebes','The friend of Socrates recalled as an unusually eager lover of argument.','Simmias'),
 ('ibycus','Ibycus','The Greek lyric poet whom Socrates quotes.','Ibycus'),
 ('homer','Homer','The ancient Greek epic poet repeatedly cited in the conversation.','Homer'),
 ('stesichorus','Stesichorus','The Greek lyric poet whose recantation about Helen inspires Socrates’ second speech.','Stesichorus'),
 ('pythocles','Pythocles','Phaedrus’s father, playfully rendered as Vain Man in this translation.','Vain Man'),
 ('euphemus','Euphemus','Stesichorus’s father, rendered as Godly Man in the wordplay.','Godly Man|Euphemus'),
 ('polemarchus','Polemarchus','Lysias’s brother, whom Socrates presents as interested in philosophy.','Polemarchus'),
 ('lycurgus','Lycurgus','The traditional Spartan lawgiver named in the discussion of enduring laws.','Lycurgus'),
 ('solon','Solon','The Athenian lawgiver and poet.','Solon'),
 ('darius','Darius I','The Persian king named as an example of a lawgiver.','Darius'),
 ('gorgias','Gorgias','The celebrated Greek teacher of rhetoric, from Leontini.','Gorgias'),
 ('thrasymachus','Thrasymachus','The teacher of rhetoric from Chalcedon, also called the Chalcedonian giant.','Thrasymachus|Chalcedonian giant'),
 ('theodorus','Theodorus of Byzantium','The teacher of rhetoric whose elaborate divisions of a speech are discussed.','Theodorus|Byzantian word-maker|Byzantine word-maker'),
 ('zeno','Zeno of Elea','The philosopher renowned for paradoxes, playfully called the Eleatic Palamedes.','Zeno|Eleatic Palamedes'),
 ('evenus','Evenus of Paros','The poet and teacher of rhetoric credited with indirect praise and censure.','Evenus'),
 ('tisias','Tisias','The Sicilian teacher of rhetoric associated here with arguments from probability.','Tisias'),
 ('prodicus','Prodicus','The sophist known for distinctions between words and their meanings.','Prodicus'),
 ('hippias','Hippias of Elis','The sophist and teacher called the Elean stranger.','Hippias'),
 ('polus','Polus','The teacher of rhetoric whose collection of technical terms is discussed.','Polus'),
 ('licymnius','Licymnius','The poet and teacher of rhetoric credited with supplying Polus’s terminology.','Licymnius'),
 ('protagoras','Protagoras','The sophist cited for rules of correct expression.','Protagoras'),
 ('eryximachus','Eryximachus','The physician who is Phaedrus’s friend and Acumenus’s son.','Eryximachus'),
 ('sophocles','Sophocles','The Athenian tragic playwright used as an example of mastery of a whole art.','Sophocles'),
 ('euripides','Euripides','The Athenian tragic playwright named alongside Sophocles.','Euripides'),
 ('pericles','Pericles','The Athenian statesman and orator whose education Socrates praises.','Pericles'),
 ('anaxagoras','Anaxagoras','The philosopher whose teaching about nature and mind influenced Pericles.','Anaxagoras'),
 ('hippocrates','Hippocrates','The Greek physician whose approach to understanding the body is compared with rhetoric.','Hippocrates|Asclepiad'),
 ('isocrates','Isocrates','The orator whom Socrates names as a promising friend at the close of the dialogue.','Isocrates'),
 ('cicero','Cicero','The Roman author cited in the translator’s note about the Tusculan Disputations.','Cic.')]:C(id,name,'reference',body,aliases)
for id,name,body,aliases,kind in [
 ('zeus','Zeus','The chief Olympian god, who leads the divine procession in Socrates’ account of the soul.','Olympian Zeus|Zeus','deity'),
 ('boreas','Boreas','The Greek god of the north wind, linked with Orithyia in the local legend.','Boreas','deity'),
 ('orithyia','Orithyia','The Athenian princess carried away by Boreas in the legend discussed beside the stream.','Orithyia','mythological-figure'),
 ('artemis','Artemis','The Greek goddess whose nearby temple is mentioned.','Artemis','deity'),
 ('pharmacia','Pharmacia','Orithyia’s companion in the version of the story Socrates considers.','Pharmacia','mythological-figure'),
 ('centaurs','The centaurs','The half-human, half-horse beings called Hippocentaurs in the discussion of myths.','Hippocentaurs','group'),
 ('chimeras','The chimeras','The composite monsters mentioned among stories that resist rational explanation.','chimeras|Chimeras','group'),
 ('gorgons','The Gorgons','The fearsome female monsters of Greek myth.','Gorgons','group'),
 ('typho','Typhon','The monstrous being called Typho, with whom Socrates compares his own unexplored nature.','Typho','mythological-figure'),
 ('hera','Hera','The Olympian goddess and wife of Zeus, called Here in the original translation.','Hera','deity'),
 ('achelous','Achelous','The river god honored at the place where Socrates and Phaedrus rest.','Achelous','deity'),
 ('nymphs','The Nymphs','The nature divinities associated with the stream and the speakers’ inspiration.','Nymphs','group'),
 ('muses','The Muses','The goddesses of poetry, music and inspired learning.','Muses','group'),
 ('eros','Eros','The god of love, son of Aphrodite in the account discussed here.','Eros','deity'),
 ('aphrodite','Aphrodite','The Greek goddess of love and beauty.','Aphrodite','deity'),
 ('helen','Helen','Helen of Troy, the woman whom Stesichorus reviles and then praises in his recantation.','Helen','mythological-figure'),
 ('sibyl','The Sibyl','The inspired prophetess cited as an example of divine madness.','Sibyl','religious-figure'),
 ('hestia','Hestia','The goddess of the hearth, who remains at home in the divine procession.','Hestia','deity'),
 ('ares','Ares','The Greek god of war, whose followers Socrates describes.','Ares','deity'),
 ('apollo','Apollo','The Greek god associated with prophecy and inspiration.','Apollo','deity'),
 ('ganymede','Ganymede','The beautiful youth loved by Zeus in the myth recalled by Socrates.','Ganymede','mythological-figure'),
 ('odysseus','Odysseus','The Homeric hero renowned for resourceful speech, used in comparisons with rhetoricians.','Odysseus','mythological-figure'),
 ('terpsichore','Terpsichore','The Muse associated here with dancers in the story of the cicadas.','Terpsichore','deity'),
 ('erato','Erato','The Muse associated here with lovers in the story of the cicadas.','Erato','deity'),
 ('calliope','Calliope','The eldest Muse, associated here with philosophy and elevated discourse.','Calliope','deity'),
 ('urania','Urania','The Muse associated with heaven and thought in Socrates’ account.','Urania','deity'),
 ('nestor','Nestor','The wise old king of Pylos in Homer, used as a model of eloquent speech.','Nestor','mythological-figure'),
 ('palamedes','Palamedes','The Greek hero famous for ingenuity, named in the comparison about rhetoric.','Palamedes','mythological-figure'),
 ('pan','Pan','The rustic god invoked in Socrates’ closing prayer.','Pan','deity'),
 ('hermes','Hermes','The Greek messenger god invoked in the conversation.','Hermes','deity'),
 ('midas','Midas','The Phrygian king named in the quoted tomb inscription.','Midas','mythological-figure'),
 ('dionysus','Dionysus','The Greek god associated with initiatory religious madness.','Dionysus','deity'),
 ('adrastus','Adrastus','The legendary king of Argos praised for his honeyed eloquence.','Adrastus','mythological-figure'),
 ('theuth','Theuth','The Egyptian god, usually called Thoth, credited with inventing writing in Socrates’ story.','Theuth','deity'),
 ('thamus','Thamus','The Egyptian king and god who judges Theuth’s inventions, identified here with Ammon.','Thamus|Ammon','deity'),
 ('adonis','Adonis','The mythological youth honored in the short-lived gardens used as Socrates’ comparison.','Adonis','mythological-figure'),
 ('god','God','The divine nature or a divine patron invoked in Socrates’ account of souls.','God','deity')]:C(id,name,'reference',body,aliases,kind)
C('cypselids','The Cypselids','reference','The ruling family of ancient Corinth, recalled for its lavish offerings at Olympia.','Cypselids','group')
for id,name,body,kind in [
 ('lysias-youth','The youth in Lysias’s speech','The imagined young man addressed by the speaker in Lysias’s speech.','unnamed-person'),
 ('nonlover','The speaker in Lysias’s speech','The imagined suitor who presents himself as a non-lover.','unnamed-person'),
 ('socrates-youth','The youth in Socrates’ speech','The imagined young man addressed in Socrates’ speeches about love.','unnamed-person'),
 ('cunning-lover','The concealed lover','The suitor in Socrates’ invented story who pretends not to love the youth.','unnamed-person'),
 ('pythia','The Delphic priestess','The prophetess of Apollo at Delphi, cited as an example of inspired speech.','unnamed-person'),
 ('dodona','The priestesses of Dodona','The women associated with the oracle at Dodona in the discussion of divine inspiration.','group'),
 ('charioteer','The charioteer','The driver in Socrates’ image of the soul, trying to guide its pair of winged horses.','allegorical-figure'),
 ('noble-horse','The noble horse','The obedient horse in the image of the human soul, responsive to guidance and restraint.','allegorical-figure'),
 ('unruly-horse','The unruly horse','The resistant horse in the image of the human soul, pulling against the driver’s guidance.','allegorical-figure'),
 ('cicadas','The cicadas','The singing insects, called grasshoppers in the tale, whom Socrates connects with the Muses.','group'),
 ('bronze-maiden','The bronze maiden','The speaking statue in the quoted inscription on Midas’s tomb.','object')]:C(id,name,'reference',body,'',kind)
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='phaedrus',contentVersion='2026-09-10.1',coverage='Complete dialogue in both English editions: two speakers, Lysias, named human/divine references, imaginary speech roles and chariot figures; context-scoped Hera and Zeno aliases.',entities=entities),ensure_ascii=False,indent=2)+'\n')
