// Antigone — SEO page data for build-seo-pages.cjs
// Sophocles, 11 scenes, Greek tragedy. Voice: tighter than the Iliad, bleak, hard, fast.

module.exports = {
  id: 'antigone',
  title: 'Antigone',
  author: 'Sophocles',
  byline: 'c. 441 BCE · Greek tragedy',
  titleAccent: 'a guided tour',
  hook: 'A young woman buries her brother in defiance of the king\'s edict. The king is her uncle; her fiancé is the king\'s son. By the end of the day everyone in the house is dead except the king, who has to live with it.',
  themesBlurb: 'Divine law against civic law, family against the state, the slow conversion of reason into tyranny.',
  castBlurb: 'The house of Oedipus, the new king, the prophet',
  castDesc: 'A small cast for a play that turns on one decision and the people destroyed by it.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Tragedy', 'Classical literature'],

  about: [
    `<em>Antigone</em> opens the morning after a civil war. Antigone's two brothers, Eteocles and Polyneices, have killed each other fighting for the throne of Thebes. The new king Creon — their uncle — decrees that Eteocles will be buried with full honors and Polyneices, the rebel, will be left to rot outside the walls. Anyone who buries him will die. Antigone defies the decree. She is caught, brought before Creon, and refuses to repent. The play is the collision that follows — between a king who has staked his authority on the edict and a woman who refuses to let her brother lie unburied.`,
    `Sophocles wrote it around 441 BCE, when he was about fifty-five and at the height of his powers. It is short — eleven scenes in roughly 1,350 lines — and built around a single confrontation that ramifies through every other relationship in the house: Creon and his son Haemon, Creon and the prophet Tiresias, Antigone and her sister Ismene, Antigone and herself. By nightfall Antigone is dead in her cave, Haemon has fallen on his sword over her body, Eurydice has cut her own throat at the altar, and Creon — alive, sane, and utterly destroyed — is begging anyone to kill him. Hegel called it the perfect tragedy because no one in it is simply wrong. Two and a half millennia of readers have not settled the argument.`,
  ],
  chaptersSubtitle: 'All 11 scenes summarized — one decision, one day, the destruction of a house.',
  chaptersLead: `<p>Greek tragedy alternates spoken episodes (the actors) with sung choral odes (the chorus). Antigone follows the standard form: prologue, parodos (entry-song), four episodes each followed by a stasimon (standing ode), and an exodos (exit-scene). The play's shape is unusually tight — every scene presses on the central confrontation, and the choral odes are not interludes but commentaries that the rest of the play tests against the action.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `Antigone is a play about a single decision and what it costs. These five threads run through the eleven scenes. None of them resolve neatly; the play does not let them.`,

  groups: [
    { label: 'Scenes 1–3 · The edict and the act', subtitle: 'Antigone defies the decree; the burial is discovered; she is caught.', chapters: [1, 2, 3] },
    { label: 'Scenes 4–7 · The collision', subtitle: 'Antigone before Creon, Ismene\'s plea, Haemon\'s warning.', chapters: [4, 5, 6, 7] },
    { label: 'Scenes 8–11 · The reckoning', subtitle: 'The cave, Tiresias, the late reversal, the dead.', chapters: [8, 9, 10, 11] },
  ],

  themes: [
    {
      slug: 'divine-civic',
      title: 'Divine law against civic law',
      greek: '<em>nomos</em> — law, custom, the unwritten and the written',
      preview: 'Creon\'s edict is one law. Antigone invokes another, older, unwritten. The play stages the collision and refuses to declare a winner.',
      essay: [
        `Creon's edict is rational. A city that has just survived a civil war cannot afford to honor the man who marched against it; the body of the rebel must be made an example. The law is severe, but it is law in the ordinary sense — a decree of the sovereign, backed by force, applying equally to all. It is the kind of law a city is built on.`,
        `Antigone invokes a different law. The duty to bury one's kin is older than any city; it was not made by Creon and cannot be unmade by him. "These laws were not ordained by Zeus," she tells him, "and Justice, who sits enthroned with the gods below, did not establish these human laws. Nor did I think that you, a mortal man, could with a single breath annul and override the immutable, unwritten laws of Heaven." She does not argue that the edict is mistaken. She argues that it is the wrong category of thing — a king's word claiming jurisdiction over what no king's word reaches.`,
        `Sophocles does not stage this as a rhetorical contest in which one side wins. Each speaker is articulate; each is partly right. The play follows the consequences of each position to the end and lets the audience watch what happens. Antigone, by following the older law, dies young and unbroken. Creon, by holding to the newer law past the moment when it is still defensible, watches his house collapse. The two laws are both real. The play's tragedy is that, in the case the play stages, they cannot both be obeyed.`,
        `This is the foundational confrontation in Western thought between conscience and the state. Aquinas takes it up in the question of unjust law. Thoreau takes it up in <em>Civil Disobedience</em>. Martin Luther King invokes it explicitly in the Letter from Birmingham Jail. The shape of the argument has not changed in twenty-five centuries because Sophocles got it right the first time: when an older law and a newer one make incompatible demands, someone is going to die.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (Antigone declares the act)' },
        { n: 3, label: 'Scene 3 (Creon proclaims the edict)' },
        { n: 5, label: 'Scene 5 (the two laws face each other)' },
      ],
    },
    {
      slug: 'family-state',
      title: 'Family against the state',
      greek: '<em>philia</em> — the bond of blood that precedes the city',
      preview: 'For Antigone the dead are kin first, traitors second. For Creon they are citizens first, brothers second. The play does not tell you which order is right.',
      essay: [
        `The other axis the play turns on is family. Antigone's argument for burial is not abstract. Polyneices is her brother; he and Eteocles were born of the same parents; whatever either of them did in the war does not change what they are to her. Her duty is owed to a person, and the person is dead, and the dead require these rites. The state has nothing to add to the question.`,
        `Creon's position is the opposite. The state precedes family in his accounting. To rule, he says in his first speech, is to set country above kin — he despises the man who puts a friend above his city. When his own niece breaks the edict, he holds to the principle and orders her death, even though she is engaged to his only surviving son. Family loyalty is what Creon must override to be a king at all.`,
        `What Sophocles shows, slowly, is that Creon has the order wrong. The household he claims to rule from is destroyed by exactly the priorities he insists on defending. His son dies for the niece he condemned. His wife dies cursing him for the son he forced into despair. The state Creon was protecting from family loyalty has, by the end of the play, lost its prince and its queen, and the king himself is begging to be killed. The state turns out to depend on the bonds Creon was willing to break to save it.`,
        `The play does not endorse Antigone's order either. Her absolute prioritization of the dead Polyneices destroys her relationship with her living sister and ends her engagement to a man who loves her. The point Sophocles makes against both characters is the same point made differently: the city and the family are not separable, and the ruler or the rebel who acts as if one can be subordinated cleanly to the other is heading for the kind of disaster Antigone ends in.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (sisters before brothers)' },
        { n: 5, label: 'Scene 5 (Creon\'s test of kinship)' },
        { n: 11, label: 'Scene 11 (the family that\'s left)' },
      ],
    },
    {
      slug: 'creon-tyranny',
      title: 'How a reasonable man becomes a tyrant',
      greek: '<em>tyrannos</em> — not a monster, but a ruler who cannot bear to be told he is wrong',
      preview: 'Creon does not begin as a tyrant. He becomes one. The play is precise about how — through inflexibility, through pride, through hearing every disagreement as a personal attack.',
      essay: [
        `Creon's first speech is reasonable. He has just inherited a throne in the wake of civil war; the city needs an example; honoring a traitor's body would invite further insurrection. The principle he lays down — country above kin, no traitor honored — is the kind of thing a competent king has to enforce. The play does not pretend he begins in the wrong.`,
        `The conversion happens scene by scene. The guard arrives with news of the burial; Creon hears not a fact but an attempt to undermine him, accuses the man of being bribed, threatens torture. Antigone is brought before him; instead of weighing her argument he hears defiance from a woman and doubles the sentence. Haemon, his son, comes to warn him that the city is murmuring against the edict; Creon hears not counsel but contempt, calls his son a "woman's slave." Tiresias the prophet — who has never yet brought Thebes a false word — arrives to tell him the gods are angry; Creon accuses him of being bought by silver.`,
        `The pattern is the same every time. Anyone who disagrees is reframed as an attacker, a flatterer, a corrupt agent. By the time Creon finally yields to the chorus's plea and runs to free Antigone, his son and his niece are already dead and his wife has minutes to live. The conversion from reasonable ruler to tyrant has taken less than a day.`,
        `What Sophocles is showing is that tyranny is not a different species of person from a reasonable ruler. It is what a reasonable ruler becomes when he cannot tolerate being contradicted. Hannah Arendt and Jean Anouilh both used the play in the twentieth century as a diagnosis of modern political failure; the diagnosis works because it was already exact in 441 BCE. The danger is not the cruel king. The danger is the ordinary king who has decided that any disagreement with him is disloyalty to the state.`,
      ],
      where: [
        { n: 3, label: 'Scene 3 (the edict, first reasonable)' },
        { n: 7, label: 'Scene 7 (Haemon ignored)' },
        { n: 9, label: 'Scene 9 (Tiresias rejected)' },
      ],
    },
    {
      slug: 'ode-to-man',
      title: 'The Ode to Man and its irony',
      greek: '<em>deinos</em> — wonderful and terrible, the same word for both',
      preview: 'The chorus sings a famous hymn to human cleverness. The rest of the play tests cleverness against its limits — and finds them.',
      essay: [
        `Early in the play, after Antigone's act has been discovered but before she has been caught, the chorus sings the most famous ode in Greek tragedy: "Many wonders there are, but nothing more wondrous than man." The ode catalogues human achievement — sailing, plowing, hunting, building, speech, civic order, medicine. Man has provision for everything. Even grim plague he has learned to endure. He is safe, whatever befalls.`,
        `Then a single line breaks the rhythm: "Yet for death he has found no cure." The ode acknowledges, almost in passing, the one limit. And then it goes on, and adds another — when human cleverness is turned against the laws of the gods, the city built on it falls. The ode ends with the chorus refusing to share a hearth with such a man.`,
        `The ode is famous on its own and is often read as a hymn to human dignity. In the play's context it is much darker. The Greek word the ode hinges on is <em>deinos</em>, which means both "wonderful" and "terrible." Man is <em>deinos</em>: skilled and dangerous, capable and frightening, and the same gifts produce both. The ode is sung just before Antigone is dragged onstage in chains. The very next thing the audience sees is what cleverness does when it meets the older laws — Creon's reason has become an instrument of destruction, Antigone's eloquence has condemned her to die alone in a cave.`,
        `Sophocles is not arguing against human achievement. He is showing what it does not solve. The ode's great catalogue contains nothing that can answer the question Antigone is about to put to Creon. Cleverness can build cities and harness horses and compose this very ode. It cannot tell a king when to listen. The limit is not in the universe; it is in the man.`,
      ],
      where: [
        { n: 4, label: 'Scene 4 (the ode itself)' },
        { n: 7, label: 'Scene 7 (Haemon on cleverness vs. counsel)' },
      ],
    },
    {
      slug: 'too-late',
      title: 'The reversal that comes too late',
      greek: '<em>anagnōrisis</em> — recognition arriving after the moment when it could save anyone',
      preview: 'Creon does see what he has done. He sees it in time to acknowledge his error and not in time to undo it. That gap is the play\'s last and cruelest space.',
      essay: [
        `Greek tragedy turns on recognition — the moment the protagonist sees the shape of what he has done. Antigone is unusual in placing that recognition almost at the end of the play, after the catastrophe has already happened, when nothing the recognition reveals can be repaired.`,
        `Creon yields to the chorus's plea after Tiresias's warning and runs to free Antigone. By the time he reaches the cave she has hanged herself with her own veil; Haemon, finding her body, lunges at his father with a sword, misses, falls on the blade himself, and dies clasping her. A messenger brings the news to Eurydice, Creon's wife. She walks back into the palace without a word and cuts her own throat at the household altar, cursing her husband as she dies. Creon is told, in succession, that his son is dead, that his wife is dead, that both deaths are his.`,
        `The recognition is total. Creon does not deny any of it. "The fault was mine, mine only," he says — and again, "I am the guilty cause. I did the deed. I was your murderer. Yes — I plead guilty." He asks to be killed. The chorus, gently, refuses him even that. He has to live with what he has done; he has to keep being king of a city he no longer wants to govern, in a palace empty of everyone he loved. The play's last lines belong to the chorus: "The chief part of happiness is a wise heart. Chastisement for errors past brings wisdom to age at last."`,
        `It is one of the bleakest endings in Greek tragedy. The wisdom Creon is granted is the wisdom of recognizing exactly what he has destroyed and being unable to alter any of it. The play does not offer redemption, or healing, or any consolation that the suffering was for something. It offers, instead, the hard fact that recognition can come too late — and that "too late" is itself a thing the universe permits. Sophocles trusts the audience to see the cost of that without commentary.`,
      ],
      where: [
        { n: 9, label: 'Scene 9 (Tiresias\'s warning)' },
        { n: 10, label: 'Scene 10 (the late yielding)' },
        { n: 11, label: 'Scene 11 (the recognition)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Antigone', role: 'The one who buries him', body: `Daughter of Oedipus, sister to both dead brothers, engaged to Creon's son Haemon. Enters the play having already decided. Asks Ismene to help her bury Polyneices and, when refused, goes alone. Caught, brought before Creon, she neither denies the act nor begs for her life — she argues that the gods' law preceded his and accepts the consequence. The first figure in Western literature to refuse a state law on grounds of conscience.` },
    { name: 'Creon', role: 'The new king', body: `Brother of Iocasta, uncle of Antigone, now ruler of Thebes after both his nephews killed each other. The edict against burying Polyneices is his first act of governance. He is not cruel by nature. He is a new ruler who has confused firmness with wisdom, and he keeps confusing them long after his son and the prophet have warned him otherwise.` },
    { name: 'Ismene', role: 'The sister who refuses', body: `Antigone's younger sister and the first person Antigone tells. Loves her sister and is terrified for her — refuses to help not from indifference but from a clear-eyed reading of the odds. When the burial is discovered, tries to share the blame so she can share the death; Antigone refuses to let her. What reasonable fear looks like next to absolute conviction.` },
    { name: 'Haemon', role: 'Creon\'s son', body: `Engaged to Antigone and Creon's only surviving heir. Comes to his father not to plead for his betrothed but to offer counsel: the city is murmuring, the edict feels wrong, no man is wise enough to stand alone. The one character who tries to give Creon a way out before it is too late. Creon refuses him. Haemon falls on his own sword over Antigone's body in the cave.` },
    { name: 'Tiresias', role: 'The blind prophet', body: `The old seer who has never yet brought Thebes a false word. Arrives after Antigone is sealed in the cave, when the consequences of Creon's decision are already moving in ways no one can see. Reports what the gods have shown him: the altars are polluted, the birds will not feed, the city is sick. Creon accuses him of being bribed. By the time Creon believes him, the damage is finished.` },
    { name: 'Eurydice', role: 'Creon\'s wife', body: `Appears in only one scene. Comes out of the palace having overheard talk of household sorrow and asks the messenger to tell her plainly. He does. She listens to the account of her son's death without a word, walks back inside, and cuts her own throat at the altar — cursing Creon, with her last breath, as the killer of her child.` },
  ],

  castSubtitle: 'A small cast for a play that turns on one decision.',
  castLead: `<p>Antigone has fewer named characters than any of Sophocles' surviving plays. The compression is the point — every figure in it is connected to every other by blood or by the edict, and there is nowhere for any of them to hide. The chorus of Theban elders functions as a seventh major character, watching and commenting and, in the end, prompting the reversal that arrives too late.</p>
      <p>The cards below cover all the speaking parts. Polyneices and Eteocles, the dead brothers, never appear onstage; they are the cause of everything and the absence around which the play turns.</p>`,
  castGroups: [
    {
      label: 'The house of Oedipus',
      subtitle: 'What is left of the family the curse has been working on.',
      characters: [
        { id: 'antigone', tag: 'Mortal', name: 'Antigone', epithet: 'Daughter of Oedipus, the one who buries him', body: `The play's protagonist. Daughter of Oedipus and Iocasta, sister of Ismene and of the two dead brothers, engaged to Creon's son Haemon. Enters the play with the decision already made. She buries Polyneices with a thin scattering of dust, is caught at the second attempt, and is brought before Creon. She does not deny the act, does not beg, does not retract. She is led to a rock-cut cave to be sealed in alive and hangs herself there before Creon's reversal can reach her.`, appears: [1, 5, 9] },
        { id: 'ismene', tag: 'Mortal', name: 'Ismene', epithet: 'Antigone\'s sister', body: `Antigone's younger sister and the first person Antigone tells. Refuses, in the prologue, to help with the burial — they are women, the men hold the power, the family is already destroyed by Oedipus's curse; one more transgression will end the line. Sophocles is not unkind to her. When Antigone is caught, Ismene tries to claim a share of the guilt so she can share the death; Antigone refuses to let her. She does not appear after Scene 5. Her fate is left ambiguous.`, appears: [1, 5] },
        { id: 'creon', tag: 'Mortal', name: 'Creon', epithet: 'King of Thebes, brother of Iocasta', body: `The new king. Brother of Iocasta, uncle of Antigone, husband of Eurydice, father of Haemon. Took the throne when both his nephews killed each other. His first act of governance is the edict against burying Polyneices; his second is to enforce it against his own niece. He is reasonable in his first speech, defensive in his second, paranoid by his fourth, and broken by the end. He survives the play. Whether that survival is a mercy is the play's last open question.`, appears: [3, 5, 7, 8, 9, 10, 11] },
        { id: 'haemon', tag: 'Mortal', name: 'Haemon', epithet: 'Creon\'s son, Antigone\'s betrothed', body: `Creon's only surviving son and Antigone's fiancé. Comes to his father in Scene 7 not to plead for his bride but to offer counsel — the city is murmuring, the edict feels wrong, the trees that bend in a flood survive while those that resist are torn out. Creon hears it as treason. Haemon storms out. He goes to the cave where Antigone has been sealed in, finds her hanged, lunges at his father with a sword, misses, and falls on the blade himself.`, appears: [7, 11] },
        { id: 'eurydice', tag: 'Mortal', name: 'Eurydice', epithet: 'Creon\'s wife', body: `Appears once, in the final scene. Comes out of the palace having overheard the messenger's news, asks him to tell her plainly, listens to the whole account of her son's death, and goes back inside without a word. She kills herself at the household altar with a sword, calling down a curse on Creon with her last breath as the killer of her child. Her single scene is famous for its silence — Sophocles withholds her grief and lets the audience supply it.`, appears: [11] },
      ],
    },
    {
      label: 'The state',
      subtitle: 'The figures who advise, witness, and report.',
      characters: [
        { id: 'tiresias', tag: 'Mortal', name: 'Tiresias', epithet: 'The blind prophet of Thebes', body: `The old seer, blind, led by a boy. Has never yet brought Thebes a false word and Creon knows it. Arrives in Scene 9 with the warning that the gods are angry — the altars are polluted, the birds will not feed, the city is sick. Creon accuses him of being bribed. Tiresias, provoked, prophesies the death of Creon's son in payment for the burial Creon has refused. Then he leaves. Within minutes Creon is running to free Antigone, too late.`, appears: [9] },
        { id: 'chorus', tag: 'Mortal', name: 'The Chorus', epithet: 'Elders of Thebes', body: `Fifteen Theban elders summoned by Creon at the start to witness his accession and endorse his edict. Sing the famous Ode to Man early on — a hymn to human cleverness that the rest of the play quietly tests against the limits of cleverness. They never openly defy Creon. They watch, hedge, and eventually realize the man they are advising is walking toward ruin they could have helped him avoid. It is the chorus, finally, that prompts the reversal — and it comes too late.`, appears: [2, 4, 6, 8, 10, 11] },
        { id: 'guard', tag: 'Mortal', name: 'The Guard', epithet: 'The unlucky messenger', body: `The soldier assigned to watch the body of Polyneices. Drew the lot to bring Creon the bad news — first that the corpse has been mysteriously buried, second that the burier is a young woman caught in the act. His two scenes are the play's only comic relief: a frightened ordinary man trying to save his neck while delivering news that is going to get someone killed. He survives the play; he is the one figure in it who knows when to stop talking.`, appears: [3, 5] },
        { id: 'messenger', tag: 'Mortal', name: 'The Messenger', epithet: 'The teller of the deaths', body: `Arrives in the final scene to report what has happened at the cave. Tells the story of Haemon's discovery of Antigone's body, the lunge at Creon, the fall on the sword. Stays onstage to witness Eurydice's silent exit, then a second messenger comes from inside the palace with the news that the queen has killed herself at the altar. His role is the one Greek tragedy reserves for someone who has seen what cannot be staged: the deaths happen offstage and arrive as words.`, appears: [11] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Prologue: the sisters before the gates', tourTitle: 'The sisters before the gates', hook: 'Before dawn, outside the palace. Antigone has decided. Ismene refuses. The play\'s whole shape is in five minutes of conversation.',
      tour: `Antigone summons her sister Ismene outside the palace gates before sunrise. The civil war ended yesterday; their two brothers, Eteocles and Polyneices, killed each other at the seventh gate; their uncle Creon, the new king, has decreed that Eteocles will be buried with full honors and Polyneices left to rot outside the walls. Anyone who buries him will be stoned to death. Antigone tells Ismene she is going to bury Polyneices anyway and asks her sister to help. Ismene refuses — they are women, the men hold the power, their family is already destroyed by Oedipus's curse, one more transgression will finish the line. Antigone walks off alone toward the body. The chorus enters as the sun rises.`,
      blurb: `Antigone summons Ismene outside the palace before dawn. Their two brothers killed each other in the war; Creon has forbidden burial of one. Antigone says she will bury him anyway. Ismene refuses to help. The sisters part. The play's whole conflict is set up in one short scene.`,
      summary: [
        `Day breaks over Thebes after a civil war. The previous night the two sons of Oedipus, Eteocles and Polyneices, met outside the seventh gate and killed each other — one defending the city, the other besieging it. Their uncle Creon, the brothers' nearest male kin, has taken the throne. His first act of governance is an edict: Eteocles will be buried with full honors; Polyneices, who marched against his own city, will be left outside the walls to rot, food for dogs and birds. Anyone who buries him will be stoned to death.`,
        `Antigone, the dead brothers' sister, summons her sister Ismene outside the palace gates before dawn. She has already decided. She will bury Polyneices herself, with or without help. Ismene begs her to think. They are women; the men hold the power; their family has already been destroyed by Oedipus's curse and the brothers' double death; one more transgression will finish the line. The gods, Ismene says, will pardon what compulsion forces. Antigone refuses the argument. She does not want pardon. She wants the burial. She tells Ismene to keep silent or speak — she does not care which — and walks off alone toward the body.`,
        `The exchange is short and the play's whole shape is in it. Antigone is not arguing on policy; she is acting on a law older than the city. Ismene is not cowardly; she is reasonable, and Sophocles will not punish her for it. The two sisters part as the chorus enters, and the prologue ends without anyone yet knowing whether Antigone will succeed. The audience knows. Everyone in the audience knew the story before the curtain rose. The play is not about what happens. It is about how, and at what cost, and to whom.`,
      ],
      appears: [{ id: 'antigone', name: 'Antigone' }, { id: 'ismene', name: 'Ismene' }],
      themes: [{ slug: 'divine-civic', label: 'Divine vs. civic law' }, { slug: 'family-state', label: 'Family vs. state' }],
    },
    {
      n: 2, title: 'Parodos: the chorus enters', tourTitle: 'The chorus enters', hook: 'The elders of Thebes sing the dawn after the war. The Argive army is broken; the city is saved; the brothers are dead.',
      tour: `The chorus of Theban elders enters at sunrise and sings the parodos — the entry-song. They celebrate the previous night's victory: the Argive army of Polyneices has been driven back, its proud captains killed at the seven gates, its boast struck down by Zeus. The two brothers, born of one mother to one father, drove their lances into each other and both perished. Now Victory returns to Thebes. The chorus calls for feasting and dancing. But the song ends mid-rejoicing — the elders see Creon approaching, summoned them as his trusted councilors, and break off to hear what their new king has to say.`,
      blurb: `The elders of Thebes sing the dawn after the battle. The Argive invaders have been driven back; the brothers killed each other; Victory has returned. The song breaks off when Creon appears — they have been summoned to hear the new king.`,
      summary: [
        `The chorus of Theban elders enters at sunrise. They sing the parodos, the entry-song, in praise of the dawn that has finally come over their seven-gated city. The night before, the Argive army of Polyneices had pressed its claim against Thebes, captain by captain, gate by gate — and Zeus, who hates a braggart's boast, struck them down with the forked blaze of his lightning. The image is of an eagle swooping low and being broken in mid-flight. Of the seven Argive captains at the seven Theban gates, every one fell.`,
        `Two of the dead are the brothers, named without being named — "that ill-starred pair, born of one mother to one father, who drove one against the other and both perished." The lines are stark. The double fratricide is the foundation of everything that will happen in the play, and the chorus already knows the morning's victory cannot be celebrated cleanly. The brothers will not be mourned the same way. One will be honored; the other left for the dogs. The seeds of the day's catastrophe are already in the song.`,
        `The song calls for feasting. Bacchus, shaker of the ground, is invoked to lead the round. Let us throng to the temples; let us dance and sing the whole night through. But the elders break off mid-rejoicing. Creon, the new king, has summoned them. They wonder why. What does our new lord ponder? Why this summons? Why call us, his elders, one and all, bidding us debate with him on some grave concern of state? The first scene of the play has shown what one sister will do; the second has shown the city she lives in; the third is about to show the man who will try to stop her.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'family-state', label: 'Family vs. state' }],
    },
    {
      n: 3, title: 'First Episode: Creon proclaims the edict', tourTitle: 'Creon proclaims the edict', hook: 'The new king lays out his policy. A guard arrives with news the edict has already been broken.',
      tour: `Creon enters and addresses the elders. He explains his policy: country before kin, no traitor honored, the state is the ship that holds all our fortunes. He proclaims the edict aloud — Eteocles buried with honor, Polyneices left to rot. The chorus accepts it. Then a guard arrives, frightened, with news that someone has already covered the corpse with a thin scattering of dust and disappeared. Creon explodes. He accuses the guards of having been bribed, threatens torture, sends the man back to find the culprit on pain of death. The book closes with the guard fleeing, swearing he will never come back. He will, in two scenes, with Antigone in his arms.`,
      blurb: `Creon's first speech of state. He proclaims the edict — Eteocles honored, Polyneices left for the dogs — and the chorus accepts it. Then a guard arrives with news the corpse has already been buried. Creon, furious, threatens torture and death. The chain that ends with everyone dead is now in motion.`,
      summary: [
        `Creon enters and lays out his policy. He has been king for less than a day. He explains himself carefully — any ruler tongue-tied by fear of consequences is the basest of the base; any ruler who puts a friend above his country is no ruler at all. The state is the ship that holds all our fortunes; if she wrecks, everything wrecks with her. From this principle he derives the edict. Eteocles, who fell defending Thebes, will be buried with full rites. Polyneices, who came back to burn his father's city, will be left where he fell. None shall give him burial or mourn for him. The chorus accepts without enthusiasm.`,
        `Then a guard arrives. He is terrified, and the speech he gives is the play's only sustained moment of dark comedy: his conscience plied the spur and the bridle by turns, and he has at last forced himself to face the king with news he does not want to deliver. The corpse, he tells Creon, has been buried — covered with a thin scattering of dust, the proper rites performed, the burier vanished. No tracks, no scratch of pick or mattock. The guards spent the morning quarrelling and accusing each other. The lot fell to him to bring the news.`,
        `Creon hears it as a personal insult. The chorus murmurs that something more than natural may be at work; Creon turns on them — sheer folly, he says, to imagine the gods would honor a traitor. He decides instantly that someone has been bribed; the guards will hang for it if the culprit is not found. The pattern is now established. Disagreement is heard as betrayal. The guard, dismissed with threats, swears under his breath that he will never come back. He will, in two scenes, with Antigone bound between his colleagues.`,
      ],
      appears: [{ id: 'creon', name: 'Creon' }, { id: 'chorus', name: 'The Chorus' }, { id: 'guard', name: 'The Guard' }],
      themes: [{ slug: 'divine-civic', label: 'Divine vs. civic law' }, { slug: 'creon-tyranny', label: 'How tyranny begins' }],
    },
    {
      n: 4, title: 'First Stasimon: the Ode to Man', tourTitle: 'The Ode to Man', hook: 'The most famous chorus in Greek tragedy. Many wonders there are, but nothing more wondrous than man — sung the moment before Antigone is dragged onstage in chains.',
      tour: `The chorus sings the most famous ode in Greek tragedy. Many wonders there are, but nothing more wondrous than man — who sails the surging sea, who furrows the earth, who tames the bull and the stag and the rough-maned steed, who has taught himself speech and swift thought and civic wit. He has provision for everything. Even grim plague he has learned to endure. Yet for death he has found no cure. And when his cleverness turns from the laws of the gods, his city falls. The ode ends mid-thought as the elders look up — the guard has come back, with Antigone in chains, and the song is broken.`,
      blurb: `The chorus sings the most famous ode in Greek tragedy. Man is wondrous in everything — sailing, plowing, hunting, building, speech. He has provision for everything except death. The ode ends as the guards drag Antigone onstage. The cleverness the ode celebrated has just met its limit.`,
      summary: [
        `The chorus, alone onstage, sings the first stasimon — the most famous of all Greek choral odes. Many wonders there are, but nothing more wondrous than man. The ode opens with a sailor crossing the surging sea, white-foamed wind at his back, and unfolds as a catalogue of what humans have done to make the world bear them. He furrows the earth and turns the plow with his yoked team. He traps the birds of the air, the beasts of the forest, the brood of the briny flood. The savage bull and the mountain stag are tamed by his infinite art. The shaggy, rough-maned steed bears the bit at his hand.`,
        `The ode rises through speech and wind-swift thought and the civic wit to live by counsel — all these he has taught himself. Provision against the arrowy rain. Provision against the freezing winter sky. Provision for everything. Even grim plague he has learned to endure. He is safe, whatever befalls. Then a single line breaks the rhythm: yet for death he has found no cure. The catalogue of mastery has run into the one limit, and the ode acknowledges it without elaboration.`,
        `The closing stanza adds the second limit. If man honors the laws of the land and reveres the gods of the state, proudly his city shall stand. But a cityless outcast I reckon whoever departs from the path of right. The ode does not name Antigone or Creon; it does not have to. It is a hymn to human cleverness that ends by warning what cleverness is for. As the last lines fade the chorus looks up — what strange vision meets my eyes? — and the guard enters with Antigone bound between two men. The cleverness the ode celebrated is about to meet, in person, the law it has just warned against breaking.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'ode-to-man', label: 'The Ode to Man' }, { slug: 'divine-civic', label: 'Divine vs. civic law' }],
    },
    {
      n: 5, title: 'Second Episode: Antigone before Creon', tourTitle: 'Antigone before Creon', hook: 'The confrontation the whole play has been moving toward. She does not deny the act. She argues the gods\' law preceded his.',
      tour: `The guard returns with Antigone in chains. He explains how she was caught — the guards swept the dust off the body, sat upwind, and toward midday a whirlwind of dust blotted out the sky; when it cleared she was standing over the corpse, wailing like a mother bird at a robbed nest, pouring libations from a bronze urn. Creon questions her. She admits everything without flinching and argues that the gods' unwritten laws precede his decree. Creon condemns her. Ismene comes out and tries to share the guilt; Antigone refuses to let her. Creon orders both arrested. Ismene reminds him Antigone is engaged to his son. Creon does not care. Let Haemon raise his seed from other fields.`,
      blurb: `Antigone is dragged before Creon. She admits the act and argues that the gods' unwritten laws preceded his decree. Creon condemns her. Ismene comes out trying to share the guilt; Antigone refuses to let her. Reminded that Antigone is engaged to his son, Creon shrugs — let Haemon find another field.`,
      summary: [
        `The guard returns with Antigone bound between him and his colleagues. He recounts the catch. After Creon's earlier threats they had brushed every speck of dust from the corpse and sat upwind of the stench, watching. Toward midday a whirlwind raised a cloud of dust that blotted out the sky. When it cleared, the girl was standing over the body, wailing like a mother bird at a robbed nest, pouring libations from a bronze urn. They swooped down and seized her. She denied nothing.`,
        `Creon questions her. Did you know about the proclamation? She knew. Everyone knew. And yet you broke it? Yes — because these laws were not ordained by Zeus, and Justice, who sits enthroned with the gods below, did not establish these human laws. Nor did I think that you, a mortal man, could with a single breath annul the unwritten laws of Heaven. They are not of today or yesterday. They do not die. She knew she had to die; if death is hastened, she counts it gain. Creon snaps that the most stubborn wills are soonest broken — like over-heated iron. He will not let a woman master him.`,
        `Ismene is brought out, distraught. She tries, against Antigone's earlier refusal, to claim a share of the guilt — let me die with you. Antigone refuses sharply: you wouldn't act with me at first. Don't claim a work you had no hand in. Sophocles makes the rejection painful: Ismene loves her sister and is being denied even the comfort of sharing the death. Creon orders both girls arrested. Ismene asks the question that should give the king pause — would you kill your own son's promised bride? Creon shrugs. Aye — let him raise his seed from other fields. The collision the play was built around has happened. The rest is the working out.`,
      ],
      appears: [{ id: 'antigone', name: 'Antigone' }, { id: 'creon', name: 'Creon' }, { id: 'ismene', name: 'Ismene' }, { id: 'guard', name: 'The Guard' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'divine-civic', label: 'Divine vs. civic law' }, { slug: 'family-state', label: 'Family vs. state' }],
    },
    {
      n: 6, title: 'Second Stasimon: the curse on the house', tourTitle: 'The curse on the house', hook: 'The chorus sings the family\'s long doom. Once a god has cursed a bloodline, the curse runs generation by generation until the cup is drained.',
      tour: `The chorus sings the second stasimon. Three times blessed are those who have never tasted pain; once the curse of Heaven infects a bloodline, the infection spreads generation after generation, and each must drain the cup. They name the house of Labdacus — Antigone's family — and trace the doom from old Cadmus through Oedipus to the brothers and now to the daughters. The light that dawned on its last-born is gone. The bloody axe of Fate has felled the handsome tree that flowered late. The ode then turns to Zeus: untouched by Time, throned in dazzling light, you reign omnipotent. All that exceeds the mean is punished. The song ends as Haemon is seen approaching.`,
      blurb: `The chorus sings the curse on the house of Labdacus. Once a god curses a bloodline, the disease runs generation by generation. Cadmus through Oedipus to the brothers to the daughters. The song ends as Haemon, Creon's son, comes onstage in anger.`,
      summary: [
        `The chorus, with Antigone now condemned, sings the curse on her family. Three times blessed are those who have never tasted pain. Once the gods strike a bloodline the infection lingers, generation after generation, and each must drain the cup. The image is of the Etesian winds from Thrace pouring down on the blackening sea, billow upon billow thundering on the shore — the curse arriving as weather, impersonal, repeating.`,
        `They trace the line. The house of Labdacus has been struck since ancient days. From old Cadmus through Oedipus to the brothers and now to the daughters, the rod of some early god scourges age after age with sorrows that never end. The light that dawned upon its last-born son — Polyneices, the youngest brother — is gone. The bloody axe of Fate has felled the handsome tree that flowered late. The chorus does not soften it; the family is being extinguished and the chorus knows it.`,
        `The ode then turns from family to god. Your might, O Zeus — what mortal power can quell it? Not sleep that lays everything else beneath its spell. Not the moons that never tire. Untouched by Time, throned in dazzling light, you reign king, omnipotent, sublime. All that exceeds the mean is punished by Fate. Hope flits about on never-tiring wings; to some she brings profit, to some light loves; but no one knows how her gifts may turn until the treacherous ashes burn beneath his feet. It is a wise saying, the chorus closes: when evil seems good to any man, Fate is near. They have been describing Antigone. They will, by the end of the play, have been describing Creon. The song ends as Haemon — Creon's son, Antigone's betrothed — is seen approaching in anger, and the elders fall silent to watch.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'family-state', label: 'Family vs. state' }, { slug: 'too-late', label: 'Too late' }],
    },
    {
      n: 7, title: 'Third Episode: Haemon\'s warning', tourTitle: 'Haemon\'s warning', hook: 'Creon\'s son comes to plead — not for his bride, but for his father. The scene is the play\'s last open door before the cave is sealed.',
      tour: `Haemon enters. He does not come to defend Antigone. He comes to warn his father. He begins respectfully: I am yours, father, and your wisdom is my helm. Then he reports what the city is saying — that Antigone is the noblest of women, that she dies for the most generous of crimes, that her name should be written in gold. He warns Creon: no man is wise enough to stand alone; the trees that bend in a flood survive while those that resist are torn out. Creon hears it as betrayal. Father and son escalate, line for line, until Creon orders Antigone killed in front of Haemon. Haemon swears never to see his father again and storms out. The play\'s last open door has just slammed.`,
      blurb: `Haemon, Creon's son, comes to warn his father. The city sees Antigone as noble; no man is wise enough to stand alone; the trees that bend in a flood survive. Creon hears every line as treason. Father and son escalate. Haemon storms out, swearing his father will never see him again.`,
      summary: [
        `Haemon comes to his father. He begins with deference — I am yours, father, your wisdom is my helm; no marriage is more precious to me than your guidance. Creon, satisfied, lectures him on right-minded sons and the dangers of letting a woman fool away one's wits. He concludes with his political principle: whoever the state appoints must be obeyed in everything, in just things and unjust alike. Better that men should cast us out than for it to be said a woman proved our match.`,
        `Haemon's reply is the play's most carefully built speech. He does not contradict his father openly. He notes, instead, what is being said in the city. The common people stand in terror of Creon's frown and dare not speak, but he has heard their muttered complaints — that Antigone is doomed for the noblest of deeds, that her name should be written in gold. Wisdom can come to other men, not only to fathers. The trees beside a stream in flood, if they yield, keep every twig unharmed; by resisting, they perish root and branch. The sailor who keeps his mainsheet taut in a gale finds himself sailing keel-up.`,
        `Creon hears every line as personal attack. He is being lectured by a beardless boy. The exchange escalates. Are we to be schooled by a child? I plead for justice. A strange merit, to sanction lawlessness. The Theban commons say no. Shall the mob dictate my policy? A state for one man alone is no state at all. They strip the conversation down to its single question: must the king be obeyed when he is wrong? Creon's answer is yes. Haemon's answer is no. Creon orders Antigone killed at once, in front of his son. Haemon swears Creon will never see him again and storms out. It was the last open door in the play.`,
      ],
      appears: [{ id: 'creon', name: 'Creon' }, { id: 'haemon', name: 'Haemon' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'creon-tyranny', label: 'How tyranny begins' }, { slug: 'family-state', label: 'Family vs. state' }],
    },
    {
      n: 8, title: 'Third Stasimon: the ode to Eros', tourTitle: 'The ode to Eros', hook: 'A short, bitter ode. Love, irresistible in fight, has set father against son.',
      tour: `The chorus sings a short ode to Eros — Love, irresistible in fight, who pillows all night long on a maiden's cheek. All the god's subjects are mad; even the wisest heart falls into folly at the touch of his poisoned dart. The chorus blames Eros for the strife of kinsman with kin they have just witnessed: love for Antigone has set Haemon against his father. The song is brief. Creon then announces the sentence in detail — not stoning after all but a slower death: she will be sealed alive in a rock-cut cave with a few days' food, leaving the gods to decide her fate without making the city itself blood-guilty.`,
      blurb: `A short bitter ode to Eros. Love has set Haemon against his father; even the wisest heart falls to the god's dart. Then Creon announces the sentence in detail. Antigone will be sealed alive in a rock cave with a few days' food — a slow death the city can call innocent.`,
      summary: [
        `The chorus, in the wake of the Haemon scene, sings a short ode to Eros. Love, irresistible in fight, all yield at a glance of your eye. Love who pillows all night long on a maiden's cheek and ranges over the uplands. All the god's subjects are mad; even the wisest heart falls straight into folly at the touch of his poisoned dart. The chorus reads the scene they have just witnessed through this lens. Eros has kindled the strife of kinsman with kin — by the eyes of a winsome wife, by the longing of her heart to win. The lines suggest, gently, that Haemon's outburst was not pure counsel but partly the love that overrides counsel.`,
        `The ode is shorter than the previous two and ends with the chorus admitting they themselves are swept aside from Justice as they gaze on this bride — Antigone, so young, so fair, hurried down to Death's bower to share the dead. The chorus is no longer pretending to neutrality. They are watching a young woman go to her death and they say so.`,
        `Creon then announces the sentence in detail, in a passage usually counted as the third episode's coda but functioning as part of the act-break. Antigone will not, in the end, be stoned. She will be taken to a desert place where no man treads, and in a rock-hewn cave — with just enough food to avoid the blood-guilt that an outright killing might bring on the state — she will be buried alive. There let her call on the King of Death, the one god she reveres — or learn, at last and too late, that it is wasted labor to reverence the dead. The cruelty is exact. Creon has found a way to kill her without anyone in Thebes having to say they killed her.`,
      ],
      appears: [{ id: 'creon', name: 'Creon' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'creon-tyranny', label: 'How tyranny begins' }],
    },
    {
      n: 9, title: 'Fourth Episode: Antigone\'s lament; Tiresias arrives', tourTitle: 'Antigone goes to the cave', hook: 'Antigone\'s last speech. Then the blind prophet arrives and tells Creon what he has done.',
      tour: `Antigone is led toward the cave. She gives the play\'s longest lyric speech — farewell to the bright sun, lament that no marriage song will be sung for her, that Death is the groom she weds. She names the pollution of her father\'s house and the brother whose burial has cost her this. She walks offstage to be sealed in. Then Tiresias the blind prophet arrives, led by a boy. He reports the signs he has seen: bird-cries are wrong, the altar fires will not light, the city is sick because dogs and birds have been feeding on Polyneices\'s body. He tells Creon: yield. Creon accuses him of being bribed. Tiresias, provoked, prophesies that Creon\'s own son will die in payment, and leaves.`,
      blurb: `Antigone gives her last speech — farewell to the sun, no marriage song will be sung for her, Death is the groom she weds — and is led to the cave. Then Tiresias arrives. The signs are bad; the gods are angry; yield. Creon accuses him of being bribed. Tiresias prophesies the death of Creon's son and leaves.`,
      summary: [
        `Antigone is led toward the cave. She gives the longest lyric speech in the play. She takes one last fond, lingering look at the bright sun. Death drags her young life away and beckons her to Acheron's dark fold — an unwed bride. No youths have sung the marriage song for her, no maidens have strewn her bridal bed with meadow flowers. Death is the groom she weds. The chorus tries to console her with the thought that she goes great and glorious to the dead; she pushes it away. She names her father's incestuous bed, the family curse, the brother whose hand has dealt her this death-blow, and is led off.`,
        `Then Tiresias arrives, led by a boy — the blind prophet of Thebes, who has never yet brought the city a false word. He reports the signs. At the augury throne the birds were tearing each other with bloody talons; the sacrifice fires would not catch; from the thighbones a foul ooze dripped and sputtered in the ashes. The cause is plain: the altars are polluted by what the dogs and birds have brought back from Polyneices's body. The gods are rejecting the city's prayers. Yield, Tiresias says. There is no glory in killing twice the slain.`,
        `Creon does not yield. Prophets, he snaps, are all a money-getting tribe. Tiresias, provoked, gives the prophecy he has been holding back. The coursers of the sun shall not run their race many times more before Creon gives the fruit of his own loins in quittance of his murder — life for life. He has entombed a living soul; he has left a corpse unburied; the avenging spirits of Heaven and Hell are on his trail. He turns to his boy: lead me home. The blind prophet walks offstage. Creon, for the first time in the play, looks afraid.`,
      ],
      appears: [{ id: 'antigone', name: 'Antigone' }, { id: 'creon', name: 'Creon' }, { id: 'tiresias', name: 'Tiresias' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'too-late', label: 'Too late' }, { slug: 'divine-civic', label: 'Divine vs. civic law' }],
    },
    {
      n: 10, title: 'Fourth Stasimon: the late yielding', tourTitle: 'The late yielding', hook: 'The chorus, for the first time, gives Creon direct counsel. Free the girl. Bury the brother. Now.',
      tour: `Tiresias has gone. The chorus, finally, gives Creon direct counsel: that man has never been wrong yet; listen to him. Creon, shaken, asks what he should do. The chorus answers without hedging: go yourself, free the girl from her cave, build a tomb for the unburied man. Now. The vengeance of the gods is swift to overtake the impenitent. Creon obeys. He calls for axes, dispatches his henchmen, and runs out himself to undo the order he has spent the play enforcing. The chorus then sings a hymn to Dionysus, the city\'s patron, asking the god to come and heal the plague Creon has brought on Thebes. The hymn is hopeful. It is also too late.`,
      blurb: `The chorus, for the first time, gives Creon direct counsel. Free the girl. Build the tomb. Now. Creon obeys, runs out himself with his henchmen. The chorus then sings to Dionysus, asking the god to heal the city. The reversal has come. By the time it reaches the cave it will be too late.`,
      summary: [
        `Tiresias has gone. The chorus, for the first time in the play, drops every hedge. That man has gone, my liege, foretelling woe. Since these locks of mine were black as a raven's, I have never known his warning to fail. Creon, shaken, admits as much — to yield is grievous, but the obstinate soul that fights with Fate is smitten grievously. He asks what he should do. The chorus answers in two short lines, the bluntest counsel they have given: go and free the girl from her rocky cell, and build a tomb for the unburied outlaw. This instant.`,
        `Creon yields. It is a wrench to sacrifice his heart's resolve, but Fate is ill to fight. He calls for his henchmen and axes; he will go himself. For all my resolve, my mind now sways this way. I was the one who bound her — I too will set her free. He runs out. The reversal the whole play has been pressing toward has finally come. The chorus, watching him go, allow themselves a moment of hope.`,
        `They sing a brief hymn to Dionysus, patron of Thebes. He is invoked under his many names — child of Zeus the thunderer, lord of Eleusis, lord of Castaly, lord of Nysa with its ivy and vineyards. They beg him to come in this hour. You see with what a plague our townsfolk sicken; we crave your ready help, whether you are descending from Parnassus or sweeping over the roaring straits. Save us, O save. The audience knows what the chorus does not yet know — that the runner is already too late, that Antigone has hanged herself in the cave, that the rocks the henchmen are about to reach contain not a girl who can be saved but a body and a lover already turning his sword on himself.`,
      ],
      appears: [{ id: 'creon', name: 'Creon' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'too-late', label: 'Too late' }],
    },
    {
      n: 11, title: 'Exodos: the dead', tourTitle: 'The dead', hook: 'A messenger arrives. Antigone has hanged herself. Haemon has fallen on his sword over her body. Eurydice walks back into the palace and cuts her own throat.',
      tour: `A messenger arrives from the cave. They had first stopped to give Polyneices proper burial — washed the body, built a pyre, raised a mound. Then they went to the cave and heard a wailing voice from inside. Creon recognized his son's voice. They forced the rocks aside: Antigone had hanged herself with her own veil; Haemon was clasping her cold body. When Creon called to him, Haemon glared, spat in his face, lunged with his sword, missed, and fell on the blade himself. Eurydice has overheard the report. She walks back inside and cuts her own throat at the altar. Creon comes onstage carrying his son's body and learns both deaths are his. He begs to be killed. The chorus refuses him even that.`,
      blurb: `The messenger reports it all. Antigone hanged herself in the cave; Haemon, finding her body, lunged at his father with a sword, missed, and fell on the blade himself. Eurydice walks back into the palace and stabs herself at the altar, cursing Creon as she dies. Creon, carrying his son\'s body, begs to be killed. The chorus refuses him even that.`,
      summary: [
        `The messenger arrives at the palace gates and gives the great speech of the exodos. Creon's party had first stopped to bury Polyneices properly — washed the corpse, laid it on fresh-cut branches, lit a pyre, piled up a great mound of native earth. Then they went on to the cave. As they approached they heard a wailing voice from inside. Creon, white, said: am I a prophet? That is my son's voice calling me. They forced the fallen rocks aside. Antigone had hanged herself with a noose of linen twined about her neck. Haemon was clasping her cold body, lamenting his dead bride and his father's cruelty.`,
        `Creon called to him. The boy looked up with tiger's eyes, spat in his father's face, drew his sword, and lunged. Creon sprang back; the blow missed. Haemon, enraged with himself, fell on his own sword and drove it home. Yet still breathing, he reached for the maiden in his limp arms and her pale cheek turned crimson with his last gasping breaths. Two corpses, the messenger says, one in death — his marriage rites consummated in the halls of Death.`,
        `Eurydice has come out during the speech and overheard. She listens to the rest in silence and walks back inside without a word. Creon enters from the other side, carrying Haemon's body, already weeping — the fault was mine, mine only. The second messenger comes out and tells him his wife has stabbed herself at the household altar, cursing him with her last breath. Creon asks to be killed. The chorus refuses. From the doom Fate decrees, there is no refuge. The play ends with Creon led offstage, alive and destroyed, while the chorus speaks the last lines: chastisement for errors past brings wisdom to age at last. The wisdom has come; the things it could have saved are gone.`,
      ],
      appears: [{ id: 'creon', name: 'Creon' }, { id: 'haemon', name: 'Haemon' }, { id: 'eurydice', name: 'Eurydice' }, { id: 'messenger', name: 'The Messenger' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'too-late', label: 'Too late' }, { slug: 'creon-tyranny', label: 'How tyranny begins' }, { slug: 'family-state', label: 'Family vs. state' }],
    },
  ],
};
