// Bacchae — SEO page data for build-seo-pages.cjs
// Euripides, 11 scenes, Greek tragedy. Voice: cold, exact, ambivalent. Specific.

module.exports = {
  id: 'bacchae',
  title: 'The Bacchae',
  author: 'Euripides',
  byline: '405 BCE · Greek tragedy',
  titleAccent: 'a guided tour',
  hook: 'A god comes home to the city of his birth and is refused. He does not argue. He arranges the conditions in which the city\'s young king dresses himself in women\'s clothes, climbs a mountain to spy on the rites he has banned, and is torn apart by his own mother. The Bacchae is the strangest play in the Greek tragic corpus and the one no one has fully agreed about for two and a half thousand years.',
  themesBlurb: 'The god refused, the limits of reason, the seduction of Pentheus, the mother who does not know, the play at the end of a life.',
  castBlurb: 'A god, a king, a house',
  castDesc: 'Dionysus and the cousin who refused him; the old king and the prophet who did not; the women on the mountain and the messengers who saw them.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Greek tragedy', 'Classical drama'],

  about: [
    `<em>The Bacchae</em> is the play in which the god Dionysus comes home to the city of his birth — Thebes — disguised as a mortal priest of his own cult, and demands recognition. His mother Semele was a Theban princess; his cousin Pentheus is now the young king. Pentheus refuses to acknowledge the new god — calls his rites a fraud, his followers hysterical women, his priest a foreign charlatan. The whole play is the patient unfolding of what Dionysus does about the refusal.`,
    `Across eleven scenes the god allows himself to be arrested, escapes the prison without effort, and drives the women of Thebes — including Pentheus's mother Agave — into Dionysian frenzy on the slopes of Mount Cithaeron. He then persuades Pentheus, the young king who has banned the rites, to dress as a woman and climb the mountain to spy on them. The women find him. They tear him apart with their bare hands. His mother carries his head back to Thebes believing it is a lion's, and her father Cadmus walks her, sentence by sentence, to the recognition of what she is holding.`,
    `Euripides wrote the play in self-imposed exile at the Macedonian court, in the last year or two of his life. It was performed posthumously in Athens in 405 BCE and won first prize, a distinction Euripides had won only a handful of times in his life. It is one of the strangest plays in the Greek tragic corpus, and one of the most violent. Aristotle is silent on it. Nietzsche built his theory of tragedy around it. Wole Soyinka and Donna Tartt and Anne Carson have rewritten it. No one has ever fully agreed on what Euripides meant by it.`,
  ],
  chaptersSubtitle: 'All 11 scenes summarized — a god\'s revenge on the city that refused him.',
  chaptersLead: `<p>The Bacchae is structured around two long messenger speeches that report what is happening on Mount Cithaeron, bracketed by Dionysus's prologue at one end and the recognition scene at the other. Scenes 1–4 are the arrival: the god, the chorus, the two old men in fawn-skins, the young king's refusal. Scenes 5–8 are the contest: Dionysus arrested, the prison shattered, the first messenger's report, and the seduction of Pentheus. Scenes 9–11 are the killing and the recognition: Pentheus dressed as a woman, the second messenger's report from the mountain, Agave with the head, and the long quiet judgement that ends the play.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `The Bacchae is a revenge play, a theology, a study in repression, and a horror story, all at once. These five threads carry it. None of them are decorative.`,

  groups: [
    { label: 'Scenes 1–4 · The arrival', subtitle: 'The god in the city of his birth, the chorus from the east, the two old men, the young king\'s refusal.', chapters: [1, 2, 3, 4] },
    { label: 'Scenes 5–8 · The contest', subtitle: 'The arrest, the broken prison, the first report from the mountain, the seduction.', chapters: [5, 6, 7, 8] },
    { label: 'Scenes 9–11 · The killing and the recognition', subtitle: 'Pentheus dressed as a woman, the second messenger\'s report, Agave with the head.', chapters: [9, 10, 11] },
  ],

  themes: [
    {
      slug: 'refused-god',
      title: 'The god you cannot refuse',
      greek: '<em>theomachia</em> — fighting against a god, the act with no good outcome',
      preview: 'Dionysus does not argue with Pentheus. He does not need to. He arranges the conditions in which Pentheus destroys himself — and the play stages the arrangement, step by patient step.',
      essay: [
        `The Bacchae opens with Dionysus, alone on stage, telling the audience exactly what he intends to do. He has come to Thebes because his mother's sisters denied his divine birth and because his cousin Pentheus has banned his rites. He will drive the women of the city into frenzy on the mountain. He will let himself be arrested. He will arrange for Pentheus to be torn apart. He says it plainly, in the prologue, and the play is the patient unfolding of the plan he has already named.`,
        `What Euripides stages, with terrifying calm, is divine power that does not raise its voice. Dionysus does not strike Pentheus down. He does not argue him into belief. He simply arranges the conditions — the prison from which the prisoner walks out unbound, the messenger's report that lands at exactly the right moment, the offer of a hidden place from which to spy — and Pentheus, at every step, takes the bait that has been offered. By the time the king is climbing the mountain in a wig and a long robe, the god has not lifted a finger against him. He has only let him have what he wanted.`,
        `This is one of the most disturbing depictions of divinity in the Greek corpus. Euripides was the tragedian most sceptical of the gods, the one whose earlier plays question and rationalise and undercut divine authority on every available occasion. In his last year, alone in a foreign court, he wrote a play in which a god is absolutely real and absolutely without mercy — not because he is cruel but because he has been refused. The play does not soften this. The god is right; the man who refused him is destroyed; the city that backed the man is broken. The audience is left to decide what to do with that.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the prologue)' },
        { n: 5, label: 'Scene 5 (the arrest)' },
        { n: 6, label: 'Scene 6 (the prison undone)' },
        { n: 11, label: 'Scene 11 (the judgement)' },
      ],
    },
    {
      slug: 'reason-ecstasy',
      title: 'Reason and ecstasy',
      greek: '<em>sōphrosynē</em> vs <em>mania</em> — the prized self-control of the polis against the divine madness it cannot govern',
      preview: 'Pentheus is a young, capable, rational king. He is destroyed because he refuses to make room — in his city or in himself — for what reason cannot account for.',
      essay: [
        `Pentheus is not stupid. He is intelligent, politically serious, alarmed for good reasons by what the women of his city are doing on the mountain. He governs from inside a coherent picture of the world — a picture in which the polis manages its citizens, the king manages the polis, and what cannot be reasoned with cannot exist. The play sets out to show what that picture cannot account for.`,
        `Tiresias, the old prophet, makes the philosophical case explicitly in the first episode. There are two chief powers among men, he says: Demeter, the earth, who feeds people with dry food, and Semele's son, who matched her gift with the juice of the grape, the drink that brings rest from grief and sleep. One is solid and one is liquid, and a city needs both. To exclude Dionysus from public life is not to eliminate him. It is to concentrate him somewhere else, and to guarantee that what comes back will be worse than what was driven out. Pentheus does not hear a word of it. The play takes the rest of its length to demonstrate, step by step, that Tiresias was right.`,
        `What Euripides has built — and the reason Nietzsche built his theory of tragedy on this play — is a dramatic argument about civilisation itself. The Apollonian principle of order, individuation, lit measure cannot stand alone. The Dionysian must be admitted somewhere, in some controlled form. A city that pushes the wet, the irrational, the ecstatic out of public life has not won; it has built a pressure chamber. The Bacchae is the play that watches the pressure chamber rupture. The young king who insisted hardest on the categories is the one whose body comes apart along the seams he was trying to keep clean.`,
      ],
      where: [
        { n: 3, label: 'Scene 3 (Tiresias\'s defence)' },
        { n: 5, label: 'Scene 5 (the interrogation)' },
        { n: 8, label: 'Scene 8 (the chorus on wisdom)' },
        { n: 9, label: 'Scene 9 (the king dressed)' },
      ],
    },
    {
      slug: 'seduction',
      title: 'The seduction of Pentheus',
      greek: '<em>peithō</em> — persuasion, the soft, exact thing that does what force cannot',
      preview: 'The scene in which Dionysus dresses Pentheus in women\'s clothes is the most uncomfortable in Greek tragedy. Pentheus is not tricked. He is willing. Something in him wants what he has been forbidding.',
      essay: [
        `The hinge of the play is the moment, late in Scene 7, when Pentheus stops resisting and agrees to put on the women's clothes. The text marks the transition with surgical care. Dionysus has been doing nothing for several scenes except being captured, escaping, and standing patiently in front of the king. The herdsman has just reported from the mountain: water, wine and milk rising from the ground, honey dripping from the women's wands, young mothers suckling wolf-cubs, cattle torn apart by bare hands. Pentheus is calling for his armour when the stranger asks him a single question, in Arthur S. Way's 1898 translation: <em>Wouldst thou behold them camped upon the hills?</em> Pentheus answers at once: <em>Ay—though with sumless gold I bought the sight.</em> The play turns on that line.`,
        `What Euripides has written is not coercion. It is the god finding what his opponent most suppresses and offering it back to him as a hidden permission. Pentheus has spent the whole play raging against the women's rites, insisting that they slip away to meet men in the woods, and returning again and again to what he imagines his mother and aunts are doing there. The fixation is the door. Dionysus opens it. Pentheus walks through.`,
        `The dressing scene is calmly, almost domestically staged. Dionysus tucks a stray lock back under the headband, tightens the belt, straightens the hem, and shows the king which hand should hold the thyrsus. Pentheus, by now half-mad, is docile and almost childlike. He sees two suns, he sees the stranger as a bull, and he asks whether he looks like his aunt Ino or his mother. Whatever has been kept down for years is on the surface now, and the god has him. Two and a half thousand years of readers have argued about what Pentheus desires. The play does not decide. It only shows that the desire is real, that the god knew where it was, and that the kingdom of self-government Pentheus built his rule on was no defence at all.`,
      ],
      where: [
        { n: 7, label: 'Scene 7 (the hinge)' },
        { n: 9, label: 'Scene 9 (the dressing)' },
        { n: 10, label: 'Scene 10 (the chorus on the spy)' },
      ],
    },
    {
      slug: 'mother-recognition',
      title: 'The mother who does not know',
      greek: '<em>anagnōrisis</em> — the recognition scene, here turned on the head of a son',
      preview: 'Agave comes down from the mountain carrying her son\'s head, believing it is a lion\'s. Cadmus walks her, sentence by sentence, to the truth. Euripides does not cut away.',
      essay: [
        `The play's most famous scene is also its most controlled. Agave returns from the mountain triumphant, carrying what she believes is a young lion she has killed with her bare hands. She is still possessed. She is, by every visible measure, happy. She wants her son to set up a ladder and nail the trophy to the front of the palace. Her father Cadmus, who has spent the previous scene gathering the scattered pieces of his grandson's body from the woodland, meets her at the gate. The recognition that follows is one of the most precisely written scenes in Greek tragedy.`,
        `Cadmus does not tell her. He asks her questions. He tells her to look up at the sky and asks whether it looks the same. He asks whose house she married into, and what son she bore there. Then he asks whose head she is carrying, and tells her to look at it. The scene is in real time. Each question removes a layer of the divine madness. Agave answers each one more clearly than the last, until the head in her hands is no longer a lion's. Euripides does not cut away. The audience watches the whole return, from her confusion at the brighter sky to the moment she names her son.`,
        `The scene is more devastating than Oedipus's blinding because it depicts not the consequence of a sin but the consequence of a possession. Agave has not knowingly done anything. She is in any normal sense not guilty. But she holds her son's head, and the play is unforgiving about it. There is no Greek consolation here. There is no balancing speech, no choric reassurance that the gods reward the just. There is a mother and a father and a head, and the long flat lines of judgement and exile that close the play. The Bacchae's last word is that what happened was real and that nobody is forgiven for it.`,
      ],
      where: [
        { n: 7, label: 'Scene 7 (Agave on the mountain, in the report)' },
        { n: 11, label: 'Scene 11 (the second messenger)' },
        { n: 11, label: 'Scene 11 (the recognition)' },
      ],
    },
    {
      slug: 'last-play',
      title: 'The play at the end of a life',
      greek: '<em>palinōidia</em> — the song that takes back what was sung before',
      preview: 'Euripides was the Greek tragedian most sceptical of the gods. He wrote The Bacchae in his last year, in exile in Macedonia. It was performed after his death and won first prize. No one has ever fully agreed what he meant by it.',
      essay: [
        `Euripides spent his career picking the gods apart. His Heracles is destroyed by a divine madness sent without justice; his Hippolytus dies because Aphrodite has an unsettled grudge; his Trojan Women is the disaster a divine quarrel leaves on the women of a sacked city. Across thirty years of plays the gods are arbitrary, vain, often petty, often absent. The audiences of the City Dionysia complained. Aristophanes mocked him for it. He left Athens at the end of his life — voluntarily, it seems — and went to the court of King Archelaus of Macedon, in what was effectively cultural exile. He died there, sometime around 406 BCE.`,
        `In his last year or two he wrote The Bacchae. It was performed posthumously in Athens, by his son or nephew, in 405 BCE. It won first prize, an honour Euripides had won only a few times while he was alive. And it is a play in which a god is absolutely real, absolutely powerful, and absolutely without mercy. The man who insisted on questioning the gods has given the audience a theatre of divine action in which the god is not questionable. The reading is so unexpected that scholars have spent two thousand years arguing about what to do with it.`,
        `Some have read it as a recantation — the old sceptic, at the end of his life, finally bowing the knee. Others have read it as the opposite — a darker, more sceptical play than any that came before, in which a god turns out to be exactly the kind of capricious, vindictive force the earlier plays warned about, only this time the play does not protest. Both readings are available; the play does not declare for either. What is certain is that Euripides knew what he was doing. He had spent thirty years exploring what a god is and what one is not. In his last year he wrote the play in which the god is real and the consequences of refusing him are total. He left it, finished, in Macedonia. He did not see it staged. The audience that watched its premiere knew the man who wrote it was already dead.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the prologue)' },
        { n: 3, label: 'Scene 3 (Tiresias\'s defence)' },
        { n: 11, label: 'Scene 11 (the closing judgement)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Dionysus', role: 'God of wine and ecstasy', body: `Son of Zeus and the Theban princess Semele, returning to the city of his birth disguised as a mortal priest of his own cult. Calm, beautiful, and without mercy — not because he is cruel but because he is a god and Pentheus has refused him. He delivers the prologue himself, names the plan, and lets it unfold. He does not raise his voice. He does not need to.` },
    { name: 'Pentheus', role: 'King of Thebes', body: `Grandson of Cadmus, cousin of Dionysus, the young king who has inherited the throne and is determined to govern. Rigid, politically serious, genuinely alarmed by what the women of his city are doing on the mountain — and, as the disguised god discerns within minutes of meeting him, fascinated by it. The play turns on the moment he stops resisting and agrees to put on the women's clothes.` },
    { name: 'Agave', role: 'Mother of Pentheus', body: `Daughter of Cadmus and sister of Semele. She is among the women of Thebes driven to the mountain in divine frenzy. She does not appear until the final scenes, when she descends carrying what she believes is the head of a mountain lion she has killed with her bare hands. The recognition Cadmus walks her through is the emotional climax of the play.` },
    { name: 'Cadmus', role: 'Founder of Thebes', body: `Pentheus's grandfather and Semele's father. He has accepted Dionysus — partly from genuine piety, partly from dynastic calculation — and spends the play trying to warn his grandson away from the collision he can see coming. He survives to gather the pieces of Pentheus's body from the mountain and to walk Agave back to herself. His final scene with her is the tenderest in the play.` },
    { name: 'Tiresias', role: 'The blind prophet', body: `The ancient seer of Thebes, in fawn-skin and ivy alongside Cadmus, ready to dance for the new god despite his age. His speech to Pentheus in the first episode is the play's most sustained rational defence of Dionysus — the god as the necessary wet element in nature, the counterpart to dry rationality, a force that cannot be excluded without consequence. Pentheus ignores every word.` },
    { name: 'The Chorus', role: 'Eastern women', body: `Fifteen women from Lydia and Phrygia who have followed Dionysus from the east to Thebes. They sing the great central odes of the play — on the joy of the rites, on the slow justice of the gods, on the wisdom of the simple life. They are the only constant on stage and the only ones who never lose composure. By the end they are praying for Pentheus's destruction.` },
  ],

  castSubtitle: 'A god, a king, a house.',
  castLead: `<p>The Bacchae has a small named cast and a few crucial unnamed figures. There are no gods on stage in human form except Dionysus himself, disguised as his own priest. There is one young king, two old men in fawn-skins, the king's mother (named only late, when she comes down from the mountain), two messengers, a soldier, and the chorus of eastern women. The other Bacchants — Pentheus's aunts Autonoe and Ino, and the rest of the women of Thebes — are reported on the mountain but never seen.</p>
      <p>The cards below cover every named figure plus the chorus. Spoilers are unavoidable for a play this short and this often performed; the descriptions are written for a reader approaching it for the first time.</p>`,
  castGroups: [
    {
      label: 'The god',
      subtitle: 'In disguise, on stage, the whole play.',
      characters: [
        { id: 'dionysus', tag: 'God', tagClass: 'god', name: 'Dionysus', epithet: 'God of wine and ecstasy, son of Zeus and Semele', body: `The god of the title. Born in Thebes — his mother was the Theban princess Semele, struck by Zeus's lightning while pregnant; the unborn child was sewn into Zeus's thigh and brought to term there. He has come back to the city of his birth disguised as a mortal priest of his own cult, with a chorus of eastern women, to demand the recognition his mother's family has refused him. He delivers the prologue himself, naming the plan; allows himself to be arrested; walks out of the prison unbound; and arranges, with surgical patience, the destruction of the king who refused him.`, appears: [1, 5, 6, 7, 9, 11] },
      ],
    },
    {
      label: 'The house of Cadmus',
      subtitle: 'The royal family of Thebes.',
      characters: [
        { id: 'pentheus', tag: 'Mortal', name: 'Pentheus', epithet: 'King of Thebes, grandson of Cadmus, cousin of the god', body: `The young king. Son of Agave and Echion, grandson of the founding king Cadmus. He has inherited the throne and is determined to govern. He returns from a journey at the start of the play to find the women of his city on the mountain in Bacchic frenzy and the prophet and his own grandfather in fawn-skins; his rage is immediate. He arrests the foreign priest, threatens execution, and accuses the cult of being a cover for orgy and lust. He is destroyed in scenes 7 to 11 — the seduction, the dressing, the climb, the killing — without the god raising a hand against him.`, appears: [3, 5, 7, 9, 11] },
        { id: 'cadmus', tag: 'Mortal', name: 'Cadmus', epithet: 'Founder of Thebes, father of Semele and Agave', body: `The aged founder of Thebes — the man who sowed the dragon's teeth from which the earth-born warriors sprang, Pentheus's father Echion among them. He is also Semele's father and so the god's grandfather. He has accepted Dionysus, partly from genuine piety and partly because the cult exalts his line, and arrives in scene 3 already in fawn-skins beside Tiresias. He warns Pentheus, in vain, of what he can see coming. He returns at the end of the play with the gathered pieces of his grandson's body and walks Agave, sentence by sentence, back to the recognition of what she has done.`, appears: [3, 11] },
        { id: 'agave', tag: 'Mortal', name: 'Agave', epithet: 'Mother of Pentheus, daughter of Cadmus, sister of Semele', body: `Pentheus's mother. Sister of Semele, the god's mother. She is among the women of Thebes driven onto the mountain in divine frenzy and leads one of the three bands described by the first messenger. She does not appear on stage until the final scene, when she descends triumphant, still possessed, carrying what she believes is the head of a mountain lion she has killed with her bare hands. The head is her son's. Cadmus's questioning brings her back to herself in real time. She is sent into exile.`, appears: [11] },
      ],
    },
    {
      label: 'The court of Thebes',
      subtitle: 'The prophet, the messengers, the soldier.',
      characters: [
        { id: 'tiresias', tag: 'Mortal', name: 'Tiresias', epithet: 'Blind prophet of Thebes', body: `The ancient blind seer of Thebes. He arrives in scene 3 already in fawn-skin and ivy, ready to dance for the new god despite his age, and invites Cadmus to come with him to the mountain. His long speech to Pentheus in the same scene is the play's most sustained philosophical defence of Dionysus — the god as the wet element in nature, the necessary counterpart to dry rationality, a force a city cannot exclude without paying for the exclusion. Pentheus ignores every word. Tiresias and Cadmus walk off together at the end of the scene to make their way to the mountain on foot.`, appears: [3] },
        { id: 'soldier', tag: 'Mortal', name: 'The Soldier', epithet: 'The captain of Pentheus\'s guard', body: `The captain Pentheus sends to arrest the foreign priest. He returns in scene 5 leading the disguised Dionysus in chains and is visibly unnerved: the prisoner came without resistance, smiled while being bound, and the women previously arrested have all escaped, their fetters fallen away and the prison doors unbarred without anyone touching them. He half-apologises to the prisoner in front of his king. The play uses him as the first sign that the god's authority is operating at a level the kingdom's force cannot reach.`, appears: [5] },
        { id: 'messenger1', tag: 'Mortal', name: 'The First Messenger', epithet: 'A herdsman from Mount Cithaeron', body: `A herdsman from the mountain, sent down to report what the women are doing. His speech in scene 7 is one of the two longest in the play and contains some of its strangest imagery: the women sleeping in chaste calm under the pines; one striking a rock with her thyrsus and bringing out water, another planting her wand in the ground for the god to send up wine, others scratching the earth for milk; young mothers suckling fawns and wolf-cubs; and then, when the herdsmen tried to seize them, tearing live cattle apart with their bare hands and routing armed villagers with nothing but their wands. He urges Pentheus to receive the god. Pentheus orders his army to march.`, appears: [7] },
        { id: 'messenger2', tag: 'Mortal', name: 'The Second Messenger', epithet: 'One of Pentheus\'s own men, returned from the mountain', body: `One of the small party that climbed Cithaeron with Pentheus and the foreign priest. He returns alone in scene 11, pale and shaken, to deliver the second long messenger speech: the bending of the pine, the king set in the branches, the god's voice from the sky calling the women to see and destroy their hidden spy, and the dismemberment that followed at the hands of Pentheus's mother and aunts. Together with the herdsman's report, it is one of the two longest speeches in the play. He delivers it and leaves before Agave arrives.`, appears: [11] },
      ],
    },
    {
      label: 'The watchers',
      subtitle: 'The chorus from the east.',
      characters: [
        { id: 'chorus', tag: 'Mortal', name: 'The Chorus', epithet: 'Eastern women, followers of Dionysus', body: `Fifteen women from Lydia and Phrygia who have followed the god westward across Asia and arrived with him at Thebes. They enter at the end of his prologue and remain on stage for the rest of the play. Their five great choral odes — on the joy of the rites, on the slow certain justice of the gods, on the slow reach of divine justice, on the spy on the mountain — are among the most sung-over passages in Greek tragedy. They are the only figures in the play who never lose composure. By the end they are openly praying for Pentheus's destruction; by the very end they accept what has happened and sing the play out with the famous final lines on the unexpectedness of what the gods bring to pass.`, appears: [2, 4, 6, 8, 10, 11] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Dionysus\'s prologue', tourTitle: 'The god alone', hook: `A god disguised as a man stands alone beside his mother's smouldering tomb and tells the audience who he is, what he has done to the women of Thebes, and what he intends for its king.`,
      tour: `Dionysus enters alone before the palace of Thebes, having exchanged his divine form for a mortal one. He names himself: son of Zeus and of Semele, Cadmus's daughter, who died in the lightning that brought on his birth. Her tomb beside the palace still smoulders. Her sisters claimed she had been seduced by a mortal and blamed Zeus for it. In return he has driven them, and every woman in the city, out of their homes and onto Mount Cithaeron. Pentheus, to whom Cadmus has handed the throne, shuts the god out of offerings and prayers. Dionysus says he will prove his godhead to Pentheus and to all Thebes, calls his Lydian women to beat their timbrels around the palace, and leaves for the mountain.`,
      blurb: `The god alone beside his mother's tomb, in mortal disguise, laying out the plan. His aunts denied that Zeus was his father; he has driven them and every woman of Thebes onto Cithaeron. Pentheus, the young king, excludes him from offerings and prayers, and Dionysus promises to show him and the whole city what he is. He calls in the women he brought from Lydia and goes up to the mountain.`,
      summary: [
        `Dionysus walks on alone before the palace at Thebes. He has taken a mortal shape, and only the audience knows who he is. In his first lines he names himself: son of Zeus, born of Cadmus's daughter Semele when the lightning forced her into labour. He points to her tomb near the palace. The ruins of her house still smoulder with Zeus's fire, a lasting sign of Hera's anger. Cadmus has made the spot sacred, and the god has covered it with vines. Semele's own sisters, he says, told Thebes that she had slept with a man and named Zeus to hide it, and that Zeus killed her for the lie.`,
        `He has come from Lydia and Phrygia, through Persia, Bactria, Media and Arabia and the coastal cities of Asia, establishing his dances as he went. Thebes is the first Greek city he has entered. He has already struck the daughters of Cadmus with frenzy and driven out every woman of the city with them; they now sit among the pines on the open rocks of the mountain. Cadmus has given his crown to Pentheus, son of another daughter, a king who, in Way's phrase, "wars with Heaven in me." If Thebes sends soldiers against the women, the god will lead them into battle himself.`,
        `He calls his chorus, the women who followed him from Mount Tmolus in Lydia, and tells them to take up the timbrels, "great Mother Rhea's device and mine," and beat them around the palace of Pentheus so the city will notice. Then he leaves for the glens of Cithaeron to join the dancing there. By the end of the prologue the audience has been told who the stranger is, what he has done, and what he means to do. The rest of the play carries it out.`,
      ],
      appears: [{ id: 'dionysus', name: 'Dionysus' }, { id: 'chorus', name: 'The Chorus (entering)' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
    {
      n: 2, title: 'Parodos', tourTitle: 'The chorus arrives', hook: `The women who followed the god from Asia sing his birth, his rites and the joy of the mountain, and call on Thebes to join them.`,
      tour: `The chorus of Asian women, alone on stage, sing the entrance song of Dionysus. They order anyone in their path to step indoors and keep silent. They bless the initiate whose life is pure and who joins the revel on the hills. They retell the god's birth: Semele struck by Zeus's thunder, the unborn child hidden in his father's thigh, fastened with golden clasps, until he was born a horned god crowned with snakes. They call on Thebes to wreathe itself in ivy and briony, and they trace the timbrel back to the dancers of the infant Zeus. The song ends on the mountain itself, with ground running with milk, wine and honey, and the old prophet Tiresias arriving at the palace door.`,
      blurb: `The chorus of Asian women sing the long entrance song. They bless the initiate, retell the god's birth from his father's thigh, call on Thebes to put on ivy and fawn-skin, and describe the mountain: the hunt, the raw feast, the ground running with milk and wine and honey, the dancer racing like a foal among grazing mares. The song ends as the blind prophet Tiresias arrives at the palace door.`,
      summary: [
        `With the god gone, the chorus sing the parodos, the song that brings them fully onto the stage. They have come from Asia, over the ridges of Tmolus, for the god Way calls "the Clamour-king." They order anyone in the street to go indoors and keep their lips from any irreverent word. Then they pronounce a blessing on the person who has been taught the god's mysteries, who keeps a pure life, and who runs with the revellers across the mountains in the rites of Cybele, the ancient Mother.`,
        `The middle of the song is the birth story. Semele, caught by Zeus's thunder, gave birth as she died. Zeus took the premature child, hid him in a slit in his own thigh closed with golden clasps, and kept him there out of Hera's sight until the appointed day. Then he brought out a bull-horned god with snakes twined in his hair, which is why the Maenads wear snakes in theirs. The chorus call on Thebes, Semele's city, to crown itself with ivy, briony, oak and pine, and to fringe its fawn-skins with white wool. They trace the timbrel back to the cave where the infant Zeus was born, to the Corybants who invented it, to Rhea, and to the satyrs who gave it to Dionysus.`,
        `The last section moves to the mountain. A worshipper sinks to the ground in the fawn-skin after hunting down a goat for its raw flesh. The ground flows with milk, wine and honey; the leader of the rout waves a blazing pine-torch and shouts the dancers on. The song closes with the Bacchant running "as of foals round the mares in the meads that are grazing." Then the stage changes register. Tiresias, the old blind prophet of Thebes, comes to the palace door and calls for Cadmus.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'tiresias', name: 'Tiresias (entering)' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 3, title: 'Tiresias, Cadmus, Pentheus', tourTitle: 'The two old men and the young king', hook: `Two old men dressed for the god's dances, and the young king who comes home, finds them in fawn-skins, and answers with the anger that will destroy him.`,
      tour: `Tiresias calls Cadmus out of the palace. Both are dressed for the rites, and both mean to dance on the mountain despite their age. They refuse to ride, since that would lessen the god's honour. Pentheus returns from abroad, furious at reports that the city's women have left home for drink and lovers in the hills under a Lydian stranger. Seeing his grandfather and the prophet in fawn-skins, he mocks them. Tiresias gives a long defence of the god: Demeter gives men bread, Dionysus gives them wine, and with it rest from grief and sleep. Cadmus urges the king to honour the god, if only for the family's sake. Pentheus orders Tiresias's seat of prophecy wrecked and the stranger hunted down.`,
      blurb: `Tiresias and Cadmus, both old, both in fawn-skins, set out to dance for the new god on foot. Pentheus arrives, enraged by the news from the mountain, and sneers at them. Tiresias defends the god as the giver of wine and the rest it brings; Cadmus reminds him of Actaeon, torn apart by his own hounds. Pentheus orders the prophet's seat of augury overturned and the stranger brought in chains to be stoned.`,
      summary: [
        `Tiresias comes to the palace door and calls for Cadmus. Cadmus comes out already dressed for the rites, fawn-skin on, thyrsus in hand, glad to forget his age. They agree to go to the mountain on foot; a chariot, Tiresias says, would diminish the god's honour. They are the only men in Thebes who will dance, and they take that as proof of their good sense. Tiresias adds that the god makes no distinction between young and old; he wants honour from everyone. Then Cadmus sees Pentheus hurrying toward the palace.`,
        `Pentheus has been away and has come back to bad news. The women of the city, his mother Agave and his aunts Ino and Autonoe among them, have left their homes. He is sure the rites are a cover for wine and for meeting men in the woods. Some of the women are already in prison. He has heard of a stranger from Lydia with perfumed golden hair who spends day and night with the women, and he swears to cut off his head. Then he sees the prophet and his own grandfather in fawn-skins. He calls it a sight for laughter, tells Cadmus to throw off the ivy, and accuses Tiresias of promoting the new god for the fees that come with prophecy.`,
        `Tiresias answers with the play's longest defence of Dionysus. There are two chief powers among men, he says. Demeter, the earth, feeds people with dry food. Semele's son matched her gift with the juice of the grape, which brings rest from grief and sleep, "the oblivion of our daily ills." He explains the story of the thigh as a confusion of words, says the god brings prophecy and panic in battle, and insists the god will not corrupt chaste women. Cadmus is more practical: even if this is no god, call him one, since it brings honour to Semele and the family. He reminds Pentheus of Actaeon, torn apart by his own hounds for boasting against Artemis. Pentheus orders Tiresias's seat of augury overturned and sends men to capture the "girl-faced stranger" so he can be stoned. Tiresias and Cadmus leave for the mountain, holding each other up.`,
      ],
      appears: [{ id: 'tiresias', name: 'Tiresias' }, { id: 'cadmus', name: 'Cadmus' }, { id: 'pentheus', name: 'Pentheus' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
    {
      n: 4, title: 'First Stasimon', tourTitle: 'The chorus on holiness', hook: 'The chorus, alone with the audience, respond to what Pentheus has just said, and set out the life their god offers.',
      tour: `The chorus sing the first stasimon. They call on Sanctity, the power that rules even the gods, and ask whether she heard the king's insults. They describe what Dionysus gives: dancing, laughter with the flutes, an end to care, sleep after wine. Unbridled talk and lawless folly end in disaster, they sing, while a quiet, sensible life holds firm; cleverness is not wisdom, and those who reach too high do not live long. They long to escape to Cyprus, or to Pieria and Olympus where the Muses live. Their god loves peace and gives wine's joy to rich and poor alike. As the song ends, Pentheus returns and his servants bring in the stranger, bound.`,
      blurb: `The chorus's first ode. They ask Sanctity whether she has heard the king's blasphemy, and list the god's gifts: dance, music, laughter, release from care, sleep. They warn that unrestrained speech ends in disaster and that cleverness is not wisdom. They long for Cyprus and the Muses' Pieria. The song ends with the stranger led in bound.`,
      summary: [
        `Alone on stage after the king and the old men have gone, the chorus sing the first of the play's four stasima. They address Sanctity, a goddess who rules over the gods yet stoops to earth on golden wings, and ask whether she has heard Pentheus railing against the son of Semele. They describe what that god claims as his own: leading people into the dance, laughter mixed with the flutes, the moment when the worried forget their troubles, and the sleep that comes over drinkers at the feast.`,
        `The second stanza turns to warning. Unbridled tongues and lawless folly come to one end, which is disaster. A calm and sensible life stays steady and keeps a household together. The gods live far off but still watch. Cleverness is not the same as wisdom, the chorus sing, and anyone who reaches for things beyond a mortal's grasp will lose even what he has. This is said to Pentheus without naming him.`,
        `The last two stanzas move into longing. The chorus wish they could escape to Cyprus, Aphrodite's island, or to Pieria, where the Muses sing, and to the slopes of Olympus where the Graces and Desire are, and where the rites are allowed. Their god, the son of Zeus, loves feasts and loves Peace; he gives the pleasure of wine to the high and the low alike, and he hates the man who refuses a happy life. The chorus say the faith of ordinary people is enough for them. Pentheus comes back onstage, and a servant leads in the stranger in bonds.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 5, title: 'The arrest and the interrogation', tourTitle: 'The god in chains', hook: 'The stranger brought in bound, and the king who questions him without understanding who is in front of him.',
      tour: `A servant brings in the stranger and reports, uneasy, that he gave himself up smiling and held out his hands to be tied. Worse, the women Pentheus had jailed are back on the mountain: their fetters fell off and the doors opened by themselves. Pentheus studies the prisoner's long hair and pale skin and questions him. The stranger, who is Dionysus, answers calmly. He is from Lydia, the god initiated him face to face, the rites are secret and mostly held at night. Pentheus threatens to cut his hair, takes his thyrsus, and orders him locked in the stables. Dionysus warns that the god will release him when he chooses, and will make Pentheus pay for the insult.`,
      blurb: `The servant who arrested the stranger reports that he came willingly, and that the women already jailed have walked free, their chains loosened and doors unbarred without a hand on them. Pentheus mocks the prisoner's looks and questions him. The stranger says he is from Lydia, that the god taught him the rites in person, and that the god is standing beside them now. Pentheus takes his thyrsus and has him locked in the stables. The prisoner is Dionysus.`,
      summary: [
        `A servant leads in the prisoner and reports to Pentheus. The capture was easy. The stranger did not run, did not turn pale, and held out his hands, smiling, while they tied them. The servant was ashamed enough to tell him that he was acting under the king's orders, not by choice. There is more. The women Pentheus had locked in the common prison have escaped to the meadows and are dancing again. Their fetters fell away and the doors unbarred themselves. The servant says the man has come to Thebes full of wonders and leaves the rest to the king.`,
        `Pentheus inspects the prisoner. He is handsome enough to tempt women, Pentheus says; his long hair shows he is no wrestler, and his skin is pale from staying out of the sun. The questioning that follows is the first direct contest of the play. The stranger says he comes from Lydia, near Mount Tmolus. Dionysus himself initiated him, face to face and awake. The rites cannot be described to the uninitiated; they are mostly held at night. When Pentheus says these answers tell him nothing, the stranger replies, in Way's line, "Wise answers seem but folly to a fool."`,
        `Pentheus threatens to cut off his hair; the stranger says it is sacred to the god. Pentheus demands the thyrsus; the stranger tells him to take it, since it belongs to Dionysus. Pentheus says he will keep him in his dungeon; the stranger says the god will free him whenever he wishes, and that the god is close by, watching, though Pentheus cannot see him. Pentheus orders him bound and penned in the horse-stalls in darkness, and says the women who came with him will be sold or put to work at the loom. Dionysus goes quietly, warning that the god Pentheus denies will make him pay for this.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus (in disguise)' }, { id: 'soldier', name: 'The Soldier' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 6, title: 'The earthquake', tourTitle: 'The prison undone', hook: `The chorus call for their god, a voice answers from inside the palace, the building shakes, and fire flares on Semele's tomb.`,
      tour: `The chorus sing the second stasimon. They reproach Dirce, the Theban spring that once washed the newborn god, for rejecting them now. They call Pentheus a monster bred from the earth-born Echion, like the giants who fought the gods, and beg Dionysus to come down from Olympus and stop him. Then the god's voice calls from inside the palace. The chorus answer in fragments. An earthquake shakes the building, the stone lintels sway, and at the god's command a blaze of fire surrounds Semele's tomb. The women throw themselves to the ground. Dionysus walks out of the palace.`,
      blurb: `The chorus appeal to Dirce, condemn Pentheus as the offspring of the dragon-born Echion, and ask where their god is lingering. A voice answers from inside the palace. The ground shakes, the palace lintels sway, and fire flares around Semele's tomb. The chorus fall flat in fear and worship, and the stranger walks out free.`,
      summary: [
        `The chorus's second ode opens with Dirce, the river-daughter of Achelous, in whose water the infant Dionysus was bathed after Zeus pulled him from the lightning and sealed him in his thigh. They ask why Dirce now turns them away, and insist that a time will come when Thebes accepts the god. Then they turn on Pentheus. His blood comes from Echion, born from the dragon's teeth sown in the earth, and it shows: they call him a savage creature like the giants who fought the gods. He has imprisoned their companion. They call on the god to come down from Olympus with his golden thyrsus and stop him.`,
        `The third stanza asks where the god is: on Nysa, on the Corycian heights, or in the Olympian forests where Orpheus once drew trees and animals with his music. They imagine him crossing the rivers of Macedonia with his dancers. Then a voice calls from inside the palace, and individual members of the chorus answer one after another. It is Dionysus, naming himself as Semele's son and Zeus's child.`,
        `The ground shakes. The chorus cry that the palace will fall and that the stone lintels are giving way. The god's voice orders the lightning-fire kindled, and flame surrounds the palace and Semele's tomb, the same tomb that has smouldered since her death. The chorus tell one another to throw themselves down, and they fall on their faces. The doors open and Dionysus comes out of the palace alone.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'dionysus', name: 'Dionysus' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 7, title: 'The first messenger and the hinge', tourTitle: 'The hinge', hook: 'A herdsman reports what the women are doing on the mountain, and one quiet question from the stranger finds what the king has been hiding.',
      tour: `Dionysus tells the chorus how he escaped: Pentheus tied up a bull thinking it was his prisoner, fought an imagined fire, and stabbed at a phantom while the palace fell. Pentheus comes out furious. A herdsman arrives from Cithaeron with the first messenger speech: the women asleep in modest calm, nursing fawns and wolf-cubs, bringing water, wine and milk from the ground; then, when the herdsmen tried to seize Agave, tearing cattle apart and raiding villages, unharmed by spears. Pentheus calls out his army. Dionysus warns him, then asks whether he would like to see the women on the hills. Pentheus says yes, at any price. He agrees to be dressed as a woman and goes inside.`,
      blurb: `The god describes his escape: the bull Pentheus bound, the phantom he stabbed, the palace in ruins. Pentheus storms out. A herdsman reports from the mountain: the women sleeping peacefully, wine and milk rising from the earth, then the rampage when the herdsmen tried to catch Agave. Pentheus orders out his army. The stranger asks one question: would he like to see them? Pentheus says yes, whatever it costs. The hinge.`,
      summary: [
        `Dionysus raises the chorus from the ground and tells them how he got free. Pentheus never touched him. In the stables he tied up a bull instead, sweating and biting his lips, while the god sat by and watched. Then the house shook, fire flared on Semele's tomb, and Pentheus, thinking the palace was burning, set his servants hauling water. Next he ran inside with a sword and stabbed at an apparition the god had made. Finally the god brought the building down, and Pentheus dropped his sword and collapsed. Pentheus comes out raging and orders the towers sealed; the stranger asks whether gods cannot pass over walls. A herdsman arrives from Cithaeron and asks whether he may speak freely. Pentheus promises he will not be harmed.`,
        `The herdsman's report is the first of the play's two great messenger speeches. At sunrise he saw three bands of women asleep under the trees, led by Autonoe, Agave and Ino, lying modestly, not drunk as Pentheus claims. Agave woke them at the sound of cattle. They let down their hair, belted their fawn-skins with snakes, and young mothers suckled fawns and wolf-cubs. One struck a rock and water sprang out; another planted her wand and the god sent up wine; others scratched the earth and milk came up, and honey dripped from their staffs. The herdsmen hid to capture Agave as a favour to the king. When they sprang out, she called the women on them. The herdsmen escaped; the cattle did not. The women tore heifers and bulls apart with their hands, raided the villages below the mountain, carried fire in their hair without being burned, and drove off armed villagers whose spears drew no blood. The herdsman urges the king to accept the god, who gave men wine; without wine, he says, there is no love and no other pleasure left.`,
        `Pentheus orders his soldiers to muster at the Electran gate. Dionysus warns him not to take up arms against a god, and offers to bring the women back without weapons; Pentheus suspects a trick and calls for his armour. Then the stranger asks, in Way's line, "Wouldst thou behold them camped upon the hills?" Pentheus answers at once: "Ay—though with sumless gold I bought the sight." From that moment the stranger leads the conversation. To go unseen, Pentheus must wear a linen robe, long hair, a headband, a fawn-skin and a thyrsus. He protests, hesitates, and goes into the palace still undecided. Dionysus turns to the chorus: "Women, the man sets foot within the toils." He will drive Pentheus mad, have him led through Thebes dressed as a woman, and send him to his death at his mother's hands.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'messenger1', name: 'The First Messenger' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'seduction', label: 'The seduction' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 8, title: 'Third Stasimon', tourTitle: 'The chorus on wisdom', hook: 'A short, hard song about escape, divine justice and happiness, sung while the king is being dressed inside the palace.',
      tour: `The chorus sing the third stasimon. They long to dance all night again, and compare themselves to a fawn that has escaped the hunters' nets and dogs and found shelter in the woods. Their refrain asks what greater prize the gods can give than a victorious hand held over an enemy's head, and answers that honour is always precious. They sing that the power of the gods moves slowly but never misses, hunting down those who exalt their own unbelief. They end by calling happy the person whose good fortune grows day by day. Inside the palace, Pentheus is being dressed in women's clothes.`,
      blurb: `The chorus long for the night dances and picture a fawn escaping the hunt into the shelter of the woods. Their refrain asks what prize from the gods is greater than holding a victorious hand over an enemy's head. They sing of the slow, sure reach of divine power against the godless, and of the happiness of a life that improves day by day. Behind the palace door, the king is being dressed.`,
      summary: [
        `With Dionysus and Pentheus inside, the chorus sing the third stasimon. It begins with longing for the all-night dances and the dew on their necks. They picture a fawn that has escaped the hunt, past the watchers and the nets, with the hounds and huntsmen behind her, racing across the river plain until the trees close around her in a place no man tracks. Then comes the refrain, which Way renders: "What wisdom's crown, what guerdon, shines more glorious That Gods can give the sons of men, than this— O'er crests of foes to stretch the hand victorious?" The answer is that honour is always precious. In this setting the image is pointed: the enemy is Pentheus.`,
        `The second stanza is a warning. The power of heaven moves slowly but surely against people who put their own unbelief on a throne and belittle the divine. The gods wait in ambush; time passes, but their purpose does not change, and fate tracks the godless down like a hound. No one should set himself above custom and tradition. It costs little, the chorus sing, to accept that what comes from heaven, and what has been held through the ages, has authority. The refrain returns.`,
        `The final short stanza is about happiness. Blessed is the one who escapes the sea and reaches harbour, and the one who succeeds after hard labour. People rise above one another in wealth and power, and countless hopes burn in countless hearts; some are fulfilled and some come to nothing. Happy is the one whose good fortune grows from day to day. The song ends. Dionysus comes out of the palace and calls Pentheus to follow him.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'seduction', label: 'The seduction' }],
    },
    {
      n: 9, title: 'Pentheus dressed', tourTitle: 'The dressing', hook: 'The young king in a woman\'s robe and long hair, seeing two suns, letting the stranger fix his costume, and setting out for the mountain.',
      tour: `Dionysus calls Pentheus out of the palace. The king appears in a woman's robe, long hair and a headband, already deranged: he sees two suns and two cities of Thebes, and the stranger looks to him like a bull with horns. He asks whether he looks like Ino or his mother. Dionysus tucks a stray lock back under the headband, straightens the belt and hem, and shows him how to carry the thyrsus. Pentheus imagines lifting Cithaeron on his shoulders, then decides to hide among the pines instead of using force. He is told he will be carried home in his mother's arms, and takes it as an honour. Alone, Dionysus calls on Agave and her sisters to receive him.`,
      blurb: `The stranger calls Pentheus out. The king is dressed as a Bacchant and no longer sane: he sees two suns, a double Thebes, a bull where the stranger stands. The god fixes his hair, his belt and his hem, and corrects how he holds the thyrsus. Pentheus boasts he could lift the mountain, settles on hiding in the pines, and hears that he will return carried in his mother's hands. Dionysus sends him off and calls on Cadmus's daughters to meet him.`,
      summary: [
        `Dionysus stands at the door and calls Pentheus out, addressing him as the man who burns to see what is forbidden. Pentheus comes out dressed as a Bacchant, and the god remarks that he looks like one of Cadmus's daughters. He is plainly not in his right mind. He says he sees two suns, a double Thebes with a double set of seven gates, and that the stranger leading him looks like a bull with horns sprouting from his head. Dionysus tells him the god is now on their side, and that he finally sees as he should.`,
        `The dressing scene that follows is staged with domestic care. Pentheus asks whether he looks like Ino or like his mother Agave. The stranger says he seems to see them in him, then notices a lock of hair that has slipped out of place. Pentheus explains he was tossing his head like a Bacchant inside. The god fixes it, then points out that the belt is loose and the hem uneven; Pentheus checks his own ankle. He asks which hand should hold the thyrsus and is told the right, moving in time with the right foot. He asks whether he could lift the glens of Cithaeron on his shoulders, with the women on them. The god says he could, but should leave the shrines of the nymphs and Pan alone. Pentheus agrees that women should not be overcome by force and says he will hide among the pines.`,
        `Pentheus now asks to be led through the middle of Thebes, proud to be the only man who dares this. In a fast exchange the god tells him another will bring him back, high-borne, in his mother's arms; Pentheus takes it as the honour he deserves. "Strange, strange man!" says Dionysus. Pentheus goes. Alone, the god calls on Agave and her sisters, the daughters of Cadmus, to stretch out their hands: he is bringing this young man to a great contest, and he and Bromius will win it. Then he follows Pentheus out.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'seduction', label: 'The seduction' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 10, title: 'Fourth Stasimon', tourTitle: 'The chorus on the spy', hook: 'The chorus drop all restraint. They call on the hounds of Madness, on Justice with her sword, and on the god in the shape of a bull, a dragon or a lion.',
      tour: `The chorus sing the fourth stasimon, the most violent of their songs. They call on the hounds of Madness to race to the mountain and drive the women to tear apart the man who has come dressed as a woman to spy on them. They imagine his mother seeing him first and crying out that no woman bore him, that he must be a lioness's cub or a Gorgon's spawn. They call on Justice to come with her sword and cut the throat of Echion's son. Finally they call on Dionysus to appear as a bull, a many-headed dragon or a flaming lion and snare the hunter among the Maenads. A messenger enters from the mountain.`,
      blurb: `The chorus abandon the restraint of their earlier songs. They call on the hounds of Madness to set the women on the spy, imagine Agave's cry when she sees him, and summon Justice with her sword to cut his throat. They ask the god to come as a bull, a dragon or a lion wrapped in flame and catch the hunter in his own net. A messenger arrives from the mountain.`,
      summary: [
        `With Dionysus gone after Pentheus, the chorus sing their shortest and fiercest ode. It opens with a summons to the hell-hounds of Madness: go to the mountain where Cadmus's daughters are dancing and goad them to tear apart the man who came in women's clothes to spy on them. They picture his mother catching sight of him from a rock or tree and crying out to the others. Who has come spying on Cadmus's daughters? What mother bore him? No woman, she says; he must be the cub of a lioness or a child of the Gorgons.`,
        `The refrain calls on Justice to appear with her avenging sword and cut through the throat of the godless son of earth-born Echion, who fears neither god nor law. The middle stanza states the chorus's position more calmly. Pentheus comes in lawless madness to fight the rites of Bacchus and his mother; a sober spirit, obedient to heaven and content with mortal limits, leads to a life without sorrow. The chorus want no presumptuous cleverness, only a pure and reverent life that honours the gods. The refrain returns, word for word.`,
        `The last stanza is a direct summons. The chorus ask Dionysus to show himself as a bull, as a many-headed dragon, or as a lion with flame around his limbs, and to come smiling and close the net of destruction around the hunter, so that he is caught among the Maenads he came to hunt. As the song ends, a messenger enters. He is one of Pentheus's servants, and he has come down from the mountain.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'messenger2', name: 'The Second Messenger (entering)' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'mother-recognition', label: 'The recognition' }],
    },
    {
      n: 11, title: 'The messenger, Agave, the judgement', tourTitle: 'Agave with the head', hook: 'The second messenger\'s report from the mountain. Agave at the palace carrying her son\'s head and calling it a lion\'s. Cadmus bringing her back to the truth, one question at a time. The god pronouncing what comes next.',
      tour: `The second messenger reports Pentheus's death. On the mountain the stranger bent a pine to the ground, set Pentheus at its top and let it rise; then he vanished, and a voice from the sky told the women to punish the man mocking their rites. They pulled the tree down. Pentheus tore off his headband and begged his mother to know him. She did not, and the women tore him apart. Agave arrives with his head on her thyrsus, calling it a lion's. Cadmus brings in the gathered body and, through a series of questions, brings her back to her senses. Dionysus pronounces the family's fate, and Cadmus and Agave part for exile.`,
      blurb: `The second messenger describes the killing: the bent pine, the voice from the sky, the women uprooting the tree, Pentheus begging his mother, the dismemberment. Agave enters with her son's head, sure it is a lion's. Cadmus arrives with the remains and questions her until she sees what she is holding. Dionysus declares their punishment. Father and daughter say goodbye and go into exile, and the chorus close the play.`,
      summary: [
        `A servant of Pentheus returns from Cithaeron and tells the chorus that the king is dead. They rejoice, and he rebukes them. Then he gives the second great messenger speech. He, Pentheus and the stranger hid in a grassy hollow above a glen where the women sat at peaceful tasks. Pentheus could not see them and asked to climb a tree. The stranger pulled the top of a tall pine down to the ground, bending it like a bow, set Pentheus on it, and let it rise slowly. Pentheus was now more visible to the women than they were to him. The stranger vanished, and a voice from the sky, apparently the god's, called on the women to take vengeance on the man who mocked him and his rites. A column of fire flashed and the glen went silent. At the second call the women rushed up, stoned him, and finally tore the pine out of the ground. Pentheus fell. He pulled off his headband, touched his mother's cheek, and begged her to recognise him. She did not. Agave, Ino, Autonoe and the others tore him apart, and Agave is now bringing his head to the city on her thyrsus.`,
        `The chorus sing briefly, and Agave enters. She is exultant and still possessed. She tells the chorus she has trapped a young lion without nets, and invites them to share the feast. She calls for her father, and for Pentheus to fix the head above the palace entrance. Cadmus arrives with attendants carrying a bier: he has gathered Pentheus's scattered body from the woods. Agave offers him her trophy. Cadmus does not tell her what it is. He asks her to look at the sky, and whether it looks the same; she says it is brighter, and that something in her mind is changing. He asks whom she married and what son she bore. Then he asks whose head she is holding. She looks, and sees it is her son's. Cadmus tells her plainly that she and her sisters killed him, on the same mountain where Actaeon died, because the city denied the god. He mourns the grandson who once protected him.`,
        `The text has a gap here, and in Way's translation the god's speech begins mid-sentence. Dionysus foretells that Cadmus and his wife Harmonia will be turned into snakes, will lead a foreign army against Greek cities, and will finally be brought by Ares to the land of the blessed. Agave pleads that the family has sinned; the god answers, "I am a God: ye did despite to me." Cadmus and Agave embrace and part for exile, and Agave asks to be taken to her sisters, far from Cithaeron. The chorus end the play with lines that also close several other plays by Euripides: the gods bring about the unexpected, leave unfulfilled what people expected, and open paths no one foresaw.`,
      ],
      appears: [{ id: 'messenger2', name: 'The Second Messenger' }, { id: 'chorus', name: 'The Chorus' }, { id: 'agave', name: 'Agave' }, { id: 'cadmus', name: 'Cadmus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'pentheus', name: 'Pentheus (in the report)' }],
      themes: [{ slug: 'mother-recognition', label: 'The recognition' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
  ],
};
