// Bacchae — SEO page data for build-seo-pages.cjs
// Euripides, 11 scenes, Greek tragedy. Voice: cold, exact, ambivalent. Specific.

module.exports = {
  id: 'bacchae',
  title: 'The Bacchae',
  author: 'Euripides',
  byline: '405 BCE · Greek tragedy',
  titleAccent: 'a guided tour',
  hook: 'A god comes home to the city of his birth and is refused. He does not argue. He arranges the conditions in which the city\'s young king dresses himself in women\'s clothes, climbs a mountain to spy on the rites he has banned, and is torn apart by his own mother. The Bacchae is the strangest play in the Greek tragic corpus and the one no one has fully agreed about for two and a half thousand years.',
  themesBlurb: 'The god refused, the limits of reason, the seduction of Pentheus, the mother who does not know, the play at the end of a life.',
  castBlurb: 'A god, a king, a house',
  castDesc: 'Dionysus and the cousin who refused him; the old king and the prophet who did not; the women on the mountain and the messengers who saw them.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Greek tragedy', 'Classical drama'],

  about: [
    `<em>The Bacchae</em> is the play in which the god Dionysus comes home to the city of his birth — Thebes — disguised as a mortal priest of his own cult, and demands recognition. His mother Semele was a Theban princess; his cousin Pentheus is now the young king. Pentheus refuses to acknowledge the new god — calls his rites a fraud, his followers hysterical women, his priest a foreign charlatan. The whole play is the patient unfolding of what Dionysus does about the refusal.`,
    `Across eleven scenes the god allows himself to be arrested, escapes the prison without effort, and drives the women of Thebes — including Pentheus's mother Agave — into Dionysian frenzy on the slopes of Mount Cithaeron. He then persuades Pentheus, the young king who has banned the rites, to dress as a woman and climb the mountain to spy on them. The women find him. They tear him apart with their bare hands. His mother carries his head back to Thebes believing it is a lion's, and her father Cadmus walks her, sentence by sentence, to the recognition of what she is holding.`,
    `Euripides wrote the play in self-imposed exile at the Macedonian court, in the last year or two of his life. It was performed posthumously in Athens in 405 BCE and won first prize — the only one Euripides ever received outright. It is one of the strangest plays in the Greek tragic corpus, and one of the most violent. Aristotle is silent on it. Nietzsche built his theory of tragedy around it. Wole Soyinka and Donna Tartt and Anne Carson have rewritten it. No one has ever fully agreed on what Euripides meant by it.`,
  ],
  chaptersSubtitle: 'All 11 scenes summarized — a god\'s revenge on the city that refused him.',
  chaptersLead: `<p>The Bacchae is structured around two long messenger speeches — the longest in Greek tragedy — that report what is happening on Mount Cithaeron, bracketed by Dionysus's prologue at one end and the recognition scene at the other. Scenes 1–4 are the arrival: the god, the chorus, the two old men in fawn-skins, the young king's refusal. Scenes 5–8 are the contest: Dionysus arrested, the prison shattered, the first messenger's report, and the seduction of Pentheus. Scenes 9–11 are the killing and the recognition: Pentheus dressed as a woman, the second messenger's report from the mountain, Agave with the head, and the long quiet judgement that ends the play.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `The Bacchae is a revenge play, a theology, a study in repression, and a horror story, all at once. These five threads carry it. None of them are decorative.`,

  groups: [
    { label: 'Scenes 1–4 · The arrival', subtitle: 'The god in the city of his birth, the chorus from the east, the two old men, the young king\'s refusal.', chapters: [1, 2, 3, 4] },
    { label: 'Scenes 5–8 · The contest', subtitle: 'The arrest, the broken prison, the first report from the mountain, the seduction.', chapters: [5, 6, 7, 8] },
    { label: 'Scenes 9–11 · The killing and the recognition', subtitle: 'Pentheus dressed as a woman, the second messenger\'s report, Agave with the head.', chapters: [9, 10, 11] },
  ],

  themes: [
    {
      slug: 'refused-god',
      title: 'The god you cannot refuse',
      greek: '<em>theomachia</em> — fighting against a god, the act with no good outcome',
      preview: 'Dionysus does not argue with Pentheus. He does not need to. He arranges the conditions in which Pentheus destroys himself — and the play stages the arrangement, step by patient step.',
      essay: [
        `The Bacchae opens with Dionysus, alone on stage, telling the audience exactly what he intends to do. He has come to Thebes because his mother's sisters denied his divine birth and because his cousin Pentheus has banned his rites. He will drive the women of the city into frenzy on the mountain. He will let himself be arrested. He will arrange for Pentheus to be torn apart. He says it plainly, in the prologue, and the play is the patient unfolding of the plan he has already named.`,
        `What Euripides stages, with terrifying calm, is divine power that does not raise its voice. Dionysus does not strike Pentheus down. He does not argue him into belief. He simply arranges the conditions — the prison from which the prisoner walks out unbound, the messenger's report that lands at exactly the right moment, the offer of a hidden place from which to spy — and Pentheus, at every step, takes the bait that has been offered. By the time the king is climbing the mountain in a wig and a long robe, the god has not lifted a finger against him. He has only let him have what he wanted.`,
        `This is one of the most disturbing depictions of divinity in the Greek corpus. Euripides was the tragedian most sceptical of the gods, the one whose earlier plays question and rationalise and undercut divine authority on every available occasion. In his last year, alone in a foreign court, he wrote a play in which a god is absolutely real and absolutely without mercy — not because he is cruel but because he has been refused. The play does not soften this. The god is right; the man who refused him is destroyed; the city that backed the man is broken. The audience is left to decide what to do with that.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the prologue)' },
        { n: 5, label: 'Scene 5 (the arrest)' },
        { n: 6, label: 'Scene 6 (the prison undone)' },
        { n: 11, label: 'Scene 11 (the judgement)' },
      ],
    },
    {
      slug: 'reason-ecstasy',
      title: 'Reason and ecstasy',
      greek: '<em>sōphrosynē</em> vs <em>mania</em> — the prized self-control of the polis against the divine madness it cannot govern',
      preview: 'Pentheus is a young, capable, rational king. He is destroyed because he refuses to make room — in his city or in himself — for what reason cannot account for.',
      essay: [
        `Pentheus is not stupid. He is intelligent, politically serious, alarmed for good reasons by what the women of his city are doing on the mountain. He governs from inside a coherent picture of the world — a picture in which the polis manages its citizens, the king manages the polis, and what cannot be reasoned with cannot exist. The play sets out to show what that picture cannot account for.`,
        `Tiresias, the old prophet, makes the philosophical case explicitly in the first episode. There are two great powers among men, he says: Demeter, who feeds the body with dry things, and Dionysus, who has come after to perfect her work — the wet, the liquid, the principle of release that lets the worn mind sleep and the locked body open. To exclude Dionysus from public life is not to eliminate him. It is to concentrate him somewhere else, and to guarantee that what comes back will be worse than what was driven out. Pentheus does not hear a word of it. The play takes the rest of its length to demonstrate, step by step, that Tiresias was right.`,
        `What Euripides has built — and the reason Nietzsche built his theory of tragedy on this play — is a dramatic argument about civilisation itself. The Apollonian principle of order, individuation, lit measure cannot stand alone. The Dionysian must be admitted somewhere, in some controlled form. A city that pushes the wet, the irrational, the ecstatic out of public life has not won; it has built a pressure chamber. The Bacchae is the play that watches the pressure chamber rupture. The young king who insisted hardest on the categories is the one whose body comes apart along the seams he was trying to keep clean.`,
      ],
      where: [
        { n: 3, label: 'Scene 3 (Tiresias\'s defence)' },
        { n: 5, label: 'Scene 5 (the interrogation)' },
        { n: 8, label: 'Scene 8 (the chorus on wisdom)' },
        { n: 9, label: 'Scene 9 (the king dressed)' },
      ],
    },
    {
      slug: 'seduction',
      title: 'The seduction of Pentheus',
      greek: '<em>peithō</em> — persuasion, the soft, exact thing that does what force cannot',
      preview: 'The scene in which Dionysus dresses Pentheus in women\'s clothes is the most uncomfortable in Greek tragedy. Pentheus is not tricked. He is willing. Something in him wants what he has been forbidding.',
      essay: [
        `The hinge of the play is the moment, late in Scene 7, when Pentheus stops resisting and agrees to put on the women's clothes. The text marks the transition with surgical care. Dionysus has been doing nothing for several scenes except being captured, escaping, and standing patiently in front of the king. The Messenger has just delivered a report from the mountain in which milk and honey and wine spring from the rock and the women suckle wolf-cubs and tear cattle apart with their hands. Pentheus, ordering his army out, is interrupted by a single quiet question from the priest in front of him: <em>You would gladly look on them at their prayers on the mountain</em>. Pentheus answers without thinking — yes, though it cost me all the gold of Thebes — and the play has its hinge.`,
        `What Euripides has written is not coercion. It is the god finding what his opponent most suppresses and offering it back to him as a hidden permission. Pentheus has spent the whole play raging against the women's rites, accusing the priest of running a brothel on the hill, fixating on the orgies he insists are happening and his sister-women are part of. The fixation is the door. Dionysus opens it. Pentheus walks through.`,
        `The dressing scene is calmly, almost domestically staged. Dionysus arranges the wig, smooths the folds of the robe, corrects the way the king is holding the wand. Pentheus, by now half-mad, is docile and almost childlike — he sees double suns, he sees the priest as a bull, he asks whether his hair is in the right place. Whatever has been kept down for years is on the surface now, and the god has him. Two and a half thousand years of readers have argued about what Pentheus desires. The play does not decide. It only shows that the desire is real, that the god knew where it was, and that the kingdom of self-government Pentheus built his rule on was no defence at all.`,
      ],
      where: [
        { n: 7, label: 'Scene 7 (the hinge)' },
        { n: 9, label: 'Scene 9 (the dressing)' },
        { n: 10, label: 'Scene 10 (the chorus on the spy)' },
      ],
    },
    {
      slug: 'mother-recognition',
      title: 'The mother who does not know',
      greek: '<em>anagnōrisis</em> — the recognition scene, here turned on the head of a son',
      preview: 'Agave comes down from the mountain carrying her son\'s head, believing it is a lion\'s. Cadmus walks her, sentence by sentence, to the truth. Euripides does not cut away.',
      essay: [
        `The play's most famous scene is also its most controlled. Agave returns from the mountain triumphant, carrying what she believes is a young lion she has killed with her bare hands. She is still possessed. She is, by every visible measure, happy. She wants to nail the trophy above her son's door and call her son out to admire it. Her father Cadmus, who has spent the previous scene gathering the scattered pieces of his grandson's body from the woodland, meets her at the gate. The recognition that follows is one of the most precisely written scenes in Greek tragedy.`,
        `Cadmus does not tell her. He asks her questions. What is the sky like above you. What is the wind in your face. Is your husband Echion. Is your son Pentheus. What is the head you are holding. Look. Look once more. Look until it is clear. The scene is in real time. Each question removes a single layer of the divine madness. Agave answers each one, more lucid than the last, until the head in her hands is no longer a lion's. Euripides does not cut away. He gives the audience the full descent — the slow widening of her eyes, the catch in her voice, the moment the weight in her hand becomes recognisable.`,
        `The scene is more devastating than Oedipus's blinding because it depicts not the consequence of a sin but the consequence of a possession. Agave has not knowingly done anything. She is in any normal sense not guilty. But she holds her son's head, and the play is unforgiving about it. There is no Greek consolation here. There is no balancing speech, no choric reassurance that the gods reward the just. There is a mother and a father and a head, and the long flat lines of judgement and exile that close the play. The Bacchae's last word is that what happened was real and that nobody is forgiven for it.`,
      ],
      where: [
        { n: 7, label: 'Scene 7 (Agave on the mountain, in the report)' },
        { n: 11, label: 'Scene 11 (the second messenger)' },
        { n: 11, label: 'Scene 11 (the recognition)' },
      ],
    },
    {
      slug: 'last-play',
      title: 'The play at the end of a life',
      greek: '<em>palinōidia</em> — the song that takes back what was sung before',
      preview: 'Euripides was the Greek tragedian most sceptical of the gods. He wrote The Bacchae in his last year, in exile in Macedonia. It was performed after his death and won first prize. No one has ever fully agreed what he meant by it.',
      essay: [
        `Euripides spent his career picking the gods apart. His Heracles is destroyed by a divine madness sent without justice; his Hippolytus dies because Aphrodite has an unsettled grudge; his Trojan Women is the disaster a divine quarrel leaves on the women of a sacked city. Across thirty years of plays the gods are arbitrary, vain, often petty, often absent. The audiences of the City Dionysia complained. Aristophanes mocked him for it. He left Athens at the end of his life — voluntarily, it seems — and went to the court of King Archelaus of Macedon, in what was effectively cultural exile. He died there, sometime around 406 BCE.`,
        `In his last year or two he wrote The Bacchae. It was performed posthumously in Athens, by his son or nephew, in 405 BCE. It won first prize — the only outright victory of Euripides's career. And it is a play in which a god is absolutely real, absolutely powerful, and absolutely without mercy. The man who insisted on questioning the gods has given the audience a theatre of divine action in which the god is not questionable. The reading is so unexpected that scholars have spent two thousand years arguing about what to do with it.`,
        `Some have read it as a recantation — the old sceptic, at the end of his life, finally bowing the knee. Others have read it as the opposite — a darker, more sceptical play than any that came before, in which a god turns out to be exactly the kind of capricious, vindictive force the earlier plays warned about, only this time the play does not protest. Both readings are available; the play does not declare for either. What is certain is that Euripides knew what he was doing. He had spent thirty years exploring what a god is and what one is not. In his last year he wrote the play in which the god is real and the consequences of refusing him are total. He left it, finished, in Macedonia. He did not see it staged. The audience that watched its premiere knew the man who wrote it was already dead.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the prologue)' },
        { n: 3, label: 'Scene 3 (Tiresias\'s defence)' },
        { n: 11, label: 'Scene 11 (the closing judgement)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Dionysus', role: 'God of wine and ecstasy', body: `Son of Zeus and the Theban princess Semele, returning to the city of his birth disguised as a mortal priest of his own cult. Calm, beautiful, and without mercy — not because he is cruel but because he is a god and Pentheus has refused him. He delivers the prologue himself, names the plan, and lets it unfold. He does not raise his voice. He does not need to.` },
    { name: 'Pentheus', role: 'King of Thebes', body: `Grandson of Cadmus, cousin of Dionysus, the young king who has inherited the throne and is determined to govern. Rigid, politically serious, genuinely alarmed by what the women of his city are doing on the mountain — and, as the disguised god discerns within minutes of meeting him, fascinated by it. The play turns on the moment he stops resisting and agrees to put on the women's clothes.` },
    { name: 'Agave', role: 'Mother of Pentheus', body: `Daughter of Cadmus and sister of Semele. She is among the women of Thebes driven to the mountain in divine frenzy. She does not appear until the final scenes, when she descends carrying what she believes is the head of a mountain lion she has killed with her bare hands. The recognition Cadmus walks her through is the emotional climax of the play.` },
    { name: 'Cadmus', role: 'Founder of Thebes', body: `Pentheus's grandfather and Semele's father. He has accepted Dionysus — partly from genuine piety, partly from dynastic calculation — and spends the play trying to warn his grandson away from the collision he can see coming. He survives to gather the pieces of Pentheus's body from the mountain and to walk Agave back to herself. His final scene with her is the tenderest in the play.` },
    { name: 'Tiresias', role: 'The blind prophet', body: `The ancient seer of Thebes, in fawn-skin and ivy alongside Cadmus, ready to dance for the new god despite his age. His speech to Pentheus in the first episode is the play's most sustained rational defence of Dionysus — the god as the necessary wet element in nature, the counterpart to dry rationality, a force that cannot be excluded without consequence. Pentheus ignores every word.` },
    { name: 'The Chorus', role: 'Eastern women', body: `Fifteen women from Lydia and Phrygia who have followed Dionysus from the east to Thebes. They sing the great central odes of the play — on the joy of the rites, on the slow justice of the gods, on the wisdom of the simple life. They are the only constant on stage and the only ones who never lose composure. By the end they are praying for Pentheus's destruction.` },
  ],

  castSubtitle: 'A god, a king, a house.',
  castLead: `<p>The Bacchae has a small named cast and a few crucial unnamed figures. There are no gods on stage in human form except Dionysus himself, disguised as his own priest. There is one young king, two old men in fawn-skins, the king's mother (named only late, when she comes down from the mountain), two messengers, a soldier, and the chorus of eastern women. The other Bacchants — Pentheus's aunts Autonoe and Ino, and the rest of the women of Thebes — are reported on the mountain but never seen.</p>
      <p>The cards below cover every named figure plus the chorus. Spoilers are unavoidable for a play this short and this often performed; the descriptions are written for a reader approaching it for the first time.</p>`,
  castGroups: [
    {
      label: 'The god',
      subtitle: 'In disguise, on stage, the whole play.',
      characters: [
        { id: 'dionysus', tag: 'God', tagClass: 'god', name: 'Dionysus', epithet: 'God of wine and ecstasy, son of Zeus and Semele', body: `The god of the title. Born in Thebes — his mother was the Theban princess Semele, struck by Zeus's lightning while pregnant; the unborn child was sewn into Zeus's thigh and brought to term there. He has come back to the city of his birth disguised as a mortal priest of his own cult, with a chorus of eastern women, to demand the recognition his mother's family has refused him. He delivers the prologue himself, naming the plan; allows himself to be arrested; walks out of the prison unbound; and arranges, with surgical patience, the destruction of the king who refused him.`, appears: [1, 5, 6, 7, 9, 11] },
      ],
    },
    {
      label: 'The house of Cadmus',
      subtitle: 'The royal family of Thebes.',
      characters: [
        { id: 'pentheus', tag: 'Mortal', name: 'Pentheus', epithet: 'King of Thebes, grandson of Cadmus, cousin of the god', body: `The young king. Son of Agave and Echion, grandson of the founding king Cadmus. He has inherited the throne and is determined to govern. He returns from a journey at the start of the play to find the women of his city on the mountain in Bacchic frenzy and the prophet and his own grandfather in fawn-skins; his rage is immediate. He arrests the foreign priest, threatens execution, and accuses the cult of being a cover for orgy and lust. He is destroyed in scenes 7 to 11 — the seduction, the dressing, the climb, the killing — without the god raising a hand against him.`, appears: [3, 5, 7, 9, 11] },
        { id: 'cadmus', tag: 'Mortal', name: 'Cadmus', epithet: 'Founder of Thebes, father of Semele and Agave', body: `The aged founder of Thebes — the man who sowed the dragon's teeth and grew the soldiers from whom Pentheus's father Echion descended. He is also Semele's father and so the god's grandfather. He has accepted Dionysus, partly from genuine piety and partly because the cult exalts his line, and arrives in scene 3 already in fawn-skins beside Tiresias. He warns Pentheus, in vain, of what he can see coming. He returns at the end of the play with the gathered pieces of his grandson's body and walks Agave, sentence by sentence, back to the recognition of what she has done.`, appears: [3, 11] },
        { id: 'agave', tag: 'Mortal', name: 'Agave', epithet: 'Mother of Pentheus, daughter of Cadmus, sister of Semele', body: `Pentheus's mother. Sister of Semele, the god's mother. She is among the women of Thebes driven onto the mountain in divine frenzy and leads one of the three bands described by the first messenger. She does not appear on stage until the final scene, when she descends triumphant, still possessed, carrying what she believes is the head of a mountain lion she has killed with her bare hands. The head is her son's. Cadmus's questioning brings her back to herself in real time. She is sent into exile.`, appears: [11] },
      ],
    },
    {
      label: 'The court of Thebes',
      subtitle: 'The prophet, the messengers, the soldier.',
      characters: [
        { id: 'tiresias', tag: 'Mortal', name: 'Tiresias', epithet: 'Blind prophet of Thebes', body: `The ancient blind seer of Thebes. He arrives in scene 3 already in fawn-skin and ivy, ready to dance for the new god despite his age, and invites Cadmus to come with him to the mountain. His long speech to Pentheus in the same scene is the play's most sustained philosophical defence of Dionysus — the god as the wet element in nature, the necessary counterpart to dry rationality, a force a city cannot exclude without paying for the exclusion. Pentheus ignores every word. Tiresias and Cadmus walk off together at the end of the scene to make their way to the mountain on foot.`, appears: [3] },
        { id: 'soldier', tag: 'Mortal', name: 'The Soldier', epithet: 'The captain of Pentheus\'s guard', body: `The captain Pentheus sends to arrest the foreign priest. He returns in scene 5 leading the disguised Dionysus in chains and is visibly unnerved: the prisoner came without resistance, smiled while being bound, and the women previously arrested have all walked free of their cells with the doors still locked behind them. He half-apologises to the prisoner in front of his king. The play uses him as the first sign that the god's authority is operating at a level the kingdom's force cannot reach.`, appears: [5] },
        { id: 'messenger1', tag: 'Mortal', name: 'The First Messenger', epithet: 'A herdsman from Mount Cithaeron', body: `A herdsman from the mountain, sent down to report what the women are doing. His speech in scene 7 is one of the longest in Greek tragedy and contains some of its strangest imagery: the women sleeping in chaste calm under the pines; one striking a rock with her wand and producing water, another producing wine, another milk; nursing wolf-cubs; and then, when the herdsmen tried to seize them, tearing live cattle apart with their bare hands and routing armed villagers with nothing but their wands. He urges Pentheus to receive the god. Pentheus orders his army to march.`, appears: [7] },
        { id: 'messenger2', tag: 'Mortal', name: 'The Second Messenger', epithet: 'One of Pentheus\'s own men, returned from the mountain', body: `One of the small party that climbed Cithaeron with Pentheus and the foreign priest. He returns alone in scene 11, pale and shaken, to deliver the second long messenger speech: the bending of the pine, the king set in the branches, the god's voice from the sky calling the women to see and destroy their hidden spy, and the dismemberment that followed at the hands of Pentheus's mother and aunts. The speech is, with the first messenger's, the longest in Greek tragedy. He delivers it and leaves before Agave arrives.`, appears: [11] },
      ],
    },
    {
      label: 'The watchers',
      subtitle: 'The chorus from the east.',
      characters: [
        { id: 'chorus', tag: 'Mortal', name: 'The Chorus', epithet: 'Eastern women, followers of Dionysus', body: `Fifteen women from Lydia and Phrygia who have followed the god westward across Asia and arrived with him at Thebes. They steal onstage at dawn behind his prologue and remain on stage for the rest of the play. Their five great choral odes — on the joy of the rites, on the slow certain justice of the gods, on the simple wise life, on the spy in the pine — are among the most sung-over passages in Greek tragedy. They are the only figures in the play who never lose composure. By the end they are openly praying for Pentheus's destruction; by the very end they accept what has happened and sing the play out with the famous final lines on the unexpectedness of what the gods bring to pass.`, appears: [2, 4, 6, 8, 10, 11] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Dionysus\'s prologue', tourTitle: 'The god alone', hook: 'A god disguised as a man, alone in front of the palace where his mother died, telling the audience exactly what he is going to do — and why.',
      tour: `Dionysus enters alone before the palace of Thebes, in mortal disguise as the priest of his own cult. He names himself: son of Zeus and the dead princess Semele, born from his father's thigh after his mother was struck by lightning. His aunts denied his divine birth; his cousin Pentheus, the young king, has banned his rites. He has driven the women of Thebes — Agave, Ino, Autonoe, every wife and daughter — onto Mount Cithaeron in frenzy. He will deal with Pentheus next. He summons his chorus of eastern women, names what is coming, and walks off to join the rites already happening on the mountain above the city.`,
      blurb: `The god alone in front of the palace where his mother died, in disguise as his own priest, telling the audience the whole plan. His aunts denied his divine birth; his cousin Pentheus, the young king, has banned the rites. He has driven every woman of the city onto the mountain in frenzy. Pentheus is next, and will pay on his own head. He summons the chorus he brought from the east and walks off to join the rites already happening above.`,
      summary: [
        `Dionysus walks on alone before the palace at Thebes, in the loose robes and long curls of an eastern priest of his own cult. The audience is the only one who knows he is the god. He names himself in the second line: son of Zeus and the Theban princess Semele, brought to term in his father's thigh after his mother was destroyed by Zeus's lightning. He points to the smoking ruin of her chamber, still flickering twenty years on, and says her sisters — his aunts, the daughters of Cadmus — have spent those twenty years denying he is divine. They told the city Semele had lain with a mortal and named Zeus to cover the shame. The god has come back to settle that.`,
        `The settling has begun. He has driven every woman of Thebes — Agave, Autonoe, Ino, every wife and daughter from cottage and hall — onto Mount Cithaeron in frenzy. The young king Pentheus, who has inherited the throne from Cadmus, is making war on the new cult: he has banned the offerings, refuses the god's name in prayer, has sent his guards for the foreign priest leading the rites. The god, in disguise as that priest, is waiting for him. He says plainly he will reveal himself through Pentheus, and that Pentheus will pay on his own head.`,
        `He calls his chorus. Fifteen women in long white robes and ivy crowns enter from offstage — the Lydian band he brought west with him, carrying timbrel and thyrsus. The god tells them to gather Thebes to their song around Pentheus's hall, and walks off to the mountain. The play has been running ten minutes. The audience has been told everything that is going to happen and has watched the god who will make it happen leave the stage on his own feet.`,
      ],
      appears: [{ id: 'dionysus', name: 'Dionysus' }, { id: 'chorus', name: 'The Chorus (entering)' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
    {
      n: 2, title: 'Parodos', tourTitle: 'The chorus arrives', hook: 'Fifteen women from the east, in fawn-skin and ivy, singing the entrance song of the god they have brought home.',
      tour: `The Chorus of eastern women, alone on stage, sing the entrance song of Dionysus. They tell the story of his birth from Zeus's thigh, the rites Cybele the Mother first gave their people, the joy of the women on the mountain — milk and wine springing from the rock, the wreath of ivy, the dance that does not stop. They call on Thebes to crown its towers with ivy and join them. They close with one of the most ecstatic lyrics in Greek tragedy: the maenad like a colt running by a river. The song ends with the entrance of the old prophet Tiresias, in fawn-skin, leaning on his staff.`,
      blurb: `The chorus of eastern women, alone after the god has gone, sing the long entrance song. They tell their journey from Asia, the god's birth from Zeus's thigh, the rites Cybele the Mother gave their people, the joy of the mountain — milk and wine springing from the rock, the wreath of ivy, the maenad like a colt running by a river. They call on Thebes to crown its towers and join them. The song ends with the prophet Tiresias arriving at the door, blind, in fawn-skin, leaning on his staff.`,
      summary: [
        `The chorus, alone on stage now that the god has gone, deliver the long entrance song called the parodos. It is one of the great surviving examples of Bacchic lyric. They begin with their journey: from Asia, from the rising of the dawn, they have come for Bromius, glorying in his name. They warn whoever watches them pass to step aside or hide indoors; the heart that defies the god should keep its silence. They sing the beatitude of the man who has drunk from the living fountain and stood near to god — whose sins are lifted like a fallen pall as he worships on the mountain.`,
        `The middle of the song is the god's birth story, retold in their voice: the mother lying in anguish, the lightning that took her, the father who cut his own flesh open to hide the unborn child and closed him in with bitter gold. When the perfect hour came a horned god was found, crowned with serpents — and so the maenads twine serpents around the wands they carry, and the songs of serpents sound through the mazes of their hair.`,
        `The final strophes are pure ecstasy — the god descending in fire, milk and wine streaming on the mountain, the maenad like a colt running by a river when the heart in her sings. The song ends with the women arrayed on stage and the air of Thebes still empty around them. The next entrance follows: Tiresias, the old blind prophet, walking slowly to the palace door in the same fawn-skin the chorus is wearing, leaning on a staff, asking for Cadmus. The play has shifted from the god's east to the god's home.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'tiresias', name: 'Tiresias (entering)' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 3, title: 'Tiresias, Cadmus, Pentheus', tourTitle: 'The two old men and the young king', hook: 'Two old men in fawn-skins, ready to dance for the new god — and the young king who comes home to find them dressed like fools and reacts with the rage that will destroy him.',
      tour: `Tiresias calls Cadmus out, dressed for the rites. The two old men — the prophet and the founder — are going to the mountain on foot. Pentheus enters in a fury: he has heard the rumour, the women are loose on Cithaeron, an effeminate stranger from Lydia is leading them. He sees his grandfather and the prophet in fawn-skins and is horrified. Tiresias delivers the long defence — Dionysus is the wet that completes Demeter the dry, the god of release that no city can exclude. Pentheus does not hear a word. He orders Tiresias's shrine destroyed and sends his guards to find the foreign priest and bring him in chains.`,
      blurb: `Tiresias calls Cadmus out, dressed for the mountain. The two old men greet each other with affection and a slightly comic bravado — no horses, walking on foot, because to take horses would be to mistrust the god. Then Pentheus arrives, raging at the news his own city's women are loose on Cithaeron and a foreign charlatan is leading them. He sees the two old men in fawn-skins and is appalled. Tiresias answers with the philosophical defence of the god. Pentheus does not hear a word. He orders the shrine destroyed and the priest brought in chains.`,
      summary: [
        `Tiresias arrives at the door in fawn-skin and ivy, leaning on his staff, and calls for Cadmus. Cadmus comes out already dressed for the rites — same fawn-skin, same wand. The two old men greet each other with a slightly comic bravado. They are going to the mountain on foot, no horses, because to take horses would be to mistrust the god. Then they look up: Pentheus is hurrying back from a journey, with his guard, talking before he has fully arrived.`,
        `Pentheus has heard the news in the streets. The women of his own city, his sisters and aunts among them, have left their homes for wild rites on the hills. He is sure it is not piety; it is wine, it is sex, it is a foreign charlatan with golden curls who has bewitched the women and lures them into the woods. He has already arrested those he could find. Then he sees his grandfather and the prophet at the door in fawn-skins. He is appalled. He calls Tiresias the prompter of the folly and tells Cadmus to take that crown of ivy off his head.`,
        `Tiresias answers with the long speech that is the play's most sustained philosophical defence of Dionysus. Two great powers, he says, are first among men: Demeter the Earth, who feeds the body with dry sustenance, and the power born from Semele, who came after to perfect her work — the liquid in the grape that gives sleep and drowns the day's cares in cool forgetting. Pentheus is conflating wine with lust; chastity lies in the heart, not the wand. Cadmus, more gently, reminds him of Actaeon torn by his own hounds for boasting against Artemis. Pentheus hears none of it. He orders the shrine ripped down and his guards out to find the priest. The old men walk off toward the mountain.`,
      ],
      appears: [{ id: 'tiresias', name: 'Tiresias' }, { id: 'cadmus', name: 'Cadmus' }, { id: 'pentheus', name: 'Pentheus' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
    {
      n: 4, title: 'First Stasimon', tourTitle: 'The chorus on holiness', hook: 'The chorus, alone with the audience, sing what they have just heard — and what they think it means.',
      tour: `The chorus sing the first stasimon. They begin with horror at Pentheus's blasphemy and ask the goddess of holiness whether she can hear the king. They turn from him to the joy of the god — his place in the dancing and the prayer, the music and the laughter, the vanishing of care, the slumber after the feast. They warn against scorning what cannot be seen. They long, at the end, for a quieter land — Cyprus, Olympus, the dell of the Muses — where the heart's desire is found. The song ends with the guards returning from the city, leading the foreign priest between them in chains, walking calmly.`,
      blurb: `The chorus's first long ode. They open in horror at Pentheus's blasphemy and ask the goddess of holiness if she has heard. They turn from him to the joy of the god — the dancing, the prayer, the laughter, the vanishing of care, the crowned slumber when pain is dead and hate forgiven. They warn against scorning what cannot be seen. They long, at the end, for a quieter country — Cyprus, Olympus, the dell of the Muses. The song ends with the guards returning, leading the foreign priest in chains.`,
      summary: [
        `Alone on stage now that the king and the old men have gone, the chorus deliver the first of their five great choral odes. They open by addressing Holiness directly — the gold-winged goddess who stoops earthward in pity — and ask whether she has heard what Pentheus said. The accusation is not anger; it is bewilderment. The god they have travelled across the world to honour has been called a fraud, the rites a debauch, the women on the mountain a brothel.`,
        `The middle of the ode is the joy of the god. They name his kingdom: in the dancing and the prayer, in the music and the laughter, in the vanishing of care, in the gods' high banquet, in the crowned slumber when pain is dead and hate forgiven. They warn the wise — those who claim more than mortals may — against scorning what they cannot see. Life is a little thing, they say, and the present is already gone, and the dreams the proud cling to do not come. The chorus is not threatening Pentheus. They are describing what he is missing.`,
        `The final strophes are a small geography of peace. They sing of Cyprus, Aphrodite's island, set in the soft sea-foam; of Paphos with its rainless meadows; of Olympus, the high still dell where the Muses dwell. There, they say, is grace, and there is the heart's desire. The god they follow is not only the god of wild ecstasy; he is also the feeder of children, the friend of peace, the giver of wine that has no grudge against the great. The song ends. From the side, the guards Pentheus sent into the city return, marching, with a prisoner walking calmly between them.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 5, title: 'The arrest and the interrogation', tourTitle: 'The god in chains', hook: 'The foreign priest brought in chains — and the king who interrogates him without realising what is standing in front of him.',
      tour: `The guards bring in the priest in chains. The captain reports, troubled, that the prisoner came without resistance, smiled while being bound, and that the women previously arrested have all walked free of their cells. Pentheus interrogates the priest. The priest is Dionysus, in disguise. He answers calmly. He says he is from Lydia. He says the rites are best held by night, that they are not for the unworthy to see, that his god stands close by and sees all. Pentheus mocks him, cuts off a curl of his hair, takes his wand, and orders him chained in the stables. Dionysus warns him: the god will free him when he chooses.`,
      blurb: `The guards return leading the foreign priest, and the captain has news he cannot explain: the women Pentheus arrested earlier have all walked free of their cells, chains fallen, bars slid back, doors untouched. Pentheus mocks the prisoner's appearance and interrogates him line by line. The priest answers calmly: he is from Lydia, the rites came from Dionysus himself, the god stands close by. Pentheus cuts off his curl, takes his wand, and orders him chained in the stables. The prisoner is Dionysus.`,
      summary: [
        `The guards return leading the priest. The captain steps forward to report. The chase was easy; the prisoner did not flinch, did not run, held both hands out without resistance. He laughed while being bound. The captain has worse news. The women Pentheus had arrested earlier and locked in the city dungeon have all walked free — the chains fell from them, the bars slid back, and they are now back on the mountain dancing. He adds, half against himself, that this is no ordinary man.`,
        `Pentheus turns on the prisoner. The interrogation that follows is the centre of the first half of the play. He mocks the priest's appearance — a girlish face for women's eyes, long curls that mean he has never wrestled, a white skin that has never seen the sun. The priest answers each question quietly. He is from Lydia, near the bright hill of Tmolus. The rites came to him from Dionysus himself, son of Zeus and Semele. The god appeared to him face to face, gave the emblems, taught the worship. The priest, never raising his voice, replies that to blinded eyes wise words seem like nothing.`,
        `Pentheus pronounces sentence. He orders the priest's curl cut off; the soldiers do it. He takes the wand. He orders the prisoner chained where the horses are tied — let him stare into the darkness in the manger — and the women who follow him sold across the seas or set to the loom. The priest, allowing it, warns the king plainly: the one Pentheus is denying is now in his prison, and will come after him for recompense. Pentheus does not hear the warning. The guards lead the priest away. The chorus is alone again.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus (in disguise)' }, { id: 'soldier', name: 'The Soldier' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 6, title: 'The earthquake', tourTitle: 'The prison undone', hook: 'A voice from inside the palace, an earthquake, fire on Semele\'s tomb — and the priest walking out unbound through the wreckage.',
      tour: `The chorus sing of Dirce the river and call on the god who is now in the palace dungeon. From within the palace comes the voice of Dionysus, calling them. The Earthquake shakes the columns; fire leaps up on Semele's tomb; the chorus fall to the ground in worship. Dionysus walks out of the palace unbound. He tells the chorus what happened: Pentheus tried to chain him and chained a bull instead, then thought he saw his prisoner and stabbed empty air, then ran from a fire he could not put out. The god allowed it all, and walked out at his own time. Pentheus is on his way out of the palace.`,
      blurb: `The chorus invoke Dirce and beg the god, wherever he is, to lift his wand against the tyrant. From inside the palace a voice cuts through — it is Dionysus. The columns shake; fire leaps on Semele's tomb. The chorus throw themselves to the ground. The priest walks out unbound and tells them what happened inside: Pentheus chained a bull thinking it was him, ran from a fire he could not put out, then stabbed empty air at a phantom in the cell. The god allowed it, and walked out at his own time.`,
      summary: [
        `The chorus's second long ode opens the scene. They invoke Dirce, the holy river of Thebes, and ask why she has fled them. They turn on Pentheus — born of Echion the dragon-seed, no man but a wonder, a giant raised against the thunder. They beg the god, wherever he is, to come down and lift his golden wand against the tyrant. They are still singing when a voice cuts through from inside the palace. It is Dionysus, calling them. The voice calls again — spirit of the chained earthquake, awake! — and the columns of Pentheus's palace shake.`,
        `Fire leaps on the Tomb of Semele beside the palace, the same fire that twenty years ago killed the god's mother. The chorus throw themselves to the ground in worship as the door opens and the priest walks out, unbound, alone. He greets them — did you despair so quickly when I went under the gate? Pentheus, he says, has been chasing shadows. When the king led him down to the stable, the god set a bull in the doorway in his shape; Pentheus fell on it and bound it hand and foot. Then a voice came and the house shook, and Pentheus ran calling for water. Then he thought the prisoner had escaped, ran back with his sword, and stabbed empty air at a phantom the god had set there.`,
        `The priest finishes the report. He is calm — the same calm he has held throughout — and tells the chorus he will bear the king gently when he comes. The ways of wisdom are still, he says, and her temper does not tremble. A footstep sounds inside the palace. Pentheus is on his way out, and the priest is waiting for him at the door, unbound, holding nothing, dressed exactly as he was when he was led in.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'dionysus', name: 'Dionysus' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 7, title: 'The first messenger and the hinge', tourTitle: 'The hinge', hook: 'A herdsman from the mountain reports what the women are doing — and a single quiet question reaches into the king and finds what he has been hiding.',
      tour: `Pentheus comes out raging. The priest is calmly there. While they argue, a herdsman runs in from the mountain and delivers the first long messenger speech: the women asleep in chastity, milk and wine springing from the rock, wolf-cubs at their breasts, then the rampage — cattle torn apart, villages broken, armed men routed by women carrying nothing but wands. Pentheus orders his army to march. Dionysus warns him; Pentheus refuses. Then the priest asks one quiet question — would you like to see them at their prayers? — and Pentheus, without thinking, says yes. The hinge of the play. He agrees to dress as a woman. He goes inside.`,
      blurb: `Pentheus comes out raging; the priest is calmly at the door. A herdsman runs in from the mountain and delivers the first long messenger speech — the women asleep in chastity, milk and wine springing from the rock, wolf-cubs at the breast, then the rampage: cattle torn apart, villages broken, armed men routed by wands. Pentheus orders his army out. The priest warns him. Then, almost in passing, the priest asks one quiet question — would you like to see them at their prayers? Pentheus, without thinking, says yes. The hinge.`,
      summary: [
        `Pentheus comes out furious — the priest has slipped his cell, the prison is wrecked, the eastern knave is at the door again. The priest, unmoved, tells him to set a quiet bearing on his rage. They argue line by line. Then a herdsman runs in from the mountain. He asks whether to tell the whole tale or leave the strange part out. Pentheus tells him to tell everything.`,
        `The first messenger speech is one of the longest in Greek tragedy. The herdsman saw three bands of women asleep beneath the trees — Autonoe, Ino, Agave at the head. They woke at the queen's cry and rose in swift ranks; girt their fawn-skins with snakes; nursed wolf-cubs; struck the rock with their wands and brought up springs of water, wine, and milk; the reed-wands ran with honey. Then the herdsmen tried to seize the queen. The women turned. With empty hands they fell on the cattle — bulls torn limb from limb, flesh hanging on the pines — burst into villages, broke iron, carried fire in their hair. Armed villagers could not touch them. He ends with a plea: receive this god.`,
        `Pentheus orders his army out. The priest warns him quietly not to lift a spear against a god. Pentheus tells him to be quiet. Then the priest changes register. <em>You would gladly look on them at their prayers on the mountain</em>. Pentheus, without thinking, answers yes — though it cost me all the gold of Thebes. The hinge. From that line on Pentheus is no longer in command of the conversation. He agrees to be dressed in a long robe, a wig, a fawn-skin, and led by the priest in secret. He goes back into the palace. Alone, the priest tells the chorus: the lion walks into the net.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'messenger1', name: 'The First Messenger' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'seduction', label: 'The seduction' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'refused-god', label: 'The god refused' }],
    },
    {
      n: 8, title: 'Third Stasimon', tourTitle: 'The chorus on wisdom', hook: 'A small, terrible song — the question of what wisdom actually is, sung over a king who is being dressed inside the palace.',
      tour: `The chorus sing the third stasimon — the most quoted ode of the play. They long for the long dances on the mountain, for feet of a fawn fleeing through grass and loveliness, beyond the snares and the deadly press. They ask: what else is wisdom? — and answer themselves: to stand free of fear, to breathe and wait, to hold a hand uplifted over hate, to love loveliness forever. They sing of the slow, certain reach of the gods against those who scorn them, and of the simple happiness of being alive. The king is being dressed in women's clothes inside the palace as they sing. The song is the contrast.`,
      blurb: `The most quoted song in the play. The chorus on the long dances on the mountain, on the feet of a fawn fleeing through loveliness, on what wisdom is — to stand free of fear, to breathe and wait, to hold a hand uplifted over hate. They sing of the slow certain reach of the gods against those who scorn them, and of the simple happiness of being alive. Inside the palace, behind the door, the king is being dressed in women's clothes as they sing.`,
      summary: [
        `The chorus, alone after the priest has followed Pentheus inside, sing one of the most famous odes in surviving Greek tragedy. It opens with a long ache for the dances they cannot reach — on through the dark till the dim stars wane, the dew on the throat, the wind in the hair. They imagine themselves as a fawn fled to greenwood, leaping ahead of the hunt, beyond the snares and the deadly press; a voice still in the distance, but the dear lone lands ahead, untroubled by men, where the little things of the woodland live unseen.`,
        `The middle of the ode is the question that gives the play its standing in moral philosophy. <em>What else is wisdom? What can man's striving, or god's high grace, be more lovely or more great? — To stand free of fear, to breathe and wait; to hold a hand uplifted over hate; and shall not loveliness be loved forever?</em> They are not preaching the refrain; they are asking it. They turn from longing to warning. The strength of god is slow and still, yet never fails. Those who worship the ruthless will are followed hunter-wise, with time's unhurried stride.`,
        `The final strophe is a small lyric on what happiness actually is. Happy the man on the weary sea who has reached the haven; happy whoever has risen, free, above his striving. The orb of life is strangely graven; men in their millions seethe with hopes, and they win or miss their wills, and the hopes either die or are pined for still. But whoever can know, as the long days go, that simply to live is happiness — he has found his heaven. The song ends. The priest walks back out. He calls Pentheus by name.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'reason-ecstasy', label: 'Reason and ecstasy' }, { slug: 'seduction', label: 'The seduction' }],
    },
    {
      n: 9, title: 'Pentheus dressed', tourTitle: 'The dressing', hook: 'The young king in a wig and a long robe, half-mad, seeing two suns, asking the priest to fix the way the curl falls — and walking off to die.',
      tour: `Dionysus calls Pentheus out. The king emerges already half-mad — he sees double suns, double Thebes, the priest as a horned bull. He is in a long linen robe, a wig falling to his shoulders, fawn-skin, wand. Dionysus arranges the costume gently — the lock of hair under the coif, the sash, the fall of the gown — while Pentheus watches himself and asks whether he stands as Ino or as his mother does. He boasts of strength. He decides not to wreck the rocks of Pan but to lie hidden in the pines. He goes off toward the mountain, led by the priest. Alone, Dionysus says: fell, fell are you, and to a doom so fell you walk.`,
      blurb: `The priest calls Pentheus out. The king emerges already half-mad: he sees double suns, double Thebes, the priest as a horned bull. He is in a long linen robe, a wig falling to his shoulders, fawn-skin and wand. The priest fixes the lock, smooths the sash, corrects the way the gown falls on the right foot. Pentheus turns inside the costume, asks if he stands like his mother, boasts of strength enough to lift Cithaeron. He goes off toward the mountain, led by the priest. Alone, Dionysus names the doom.`,
      summary: [
        `The priest steps to the door and calls. <em>O eye that craves sights you must not see, O heart athirst for what cannot slake — Pentheus, come forth and be seen.</em> The king walks out. He is in the costume the priest described — long linen robe falling to the feet, dappled fawn-skin over it, wig of long curls beneath a snood, wand in his hand. He is also, visibly, no longer in his right mind. The sun, he says, shines double in the sky, and Thebes double, and the seven-gated wall. And is that a wild bull waiting in front of him; there are horns on the priest's brow.`,
        `The dressing scene is staged with strange domestic care. Pentheus asks how he looks: do I stand like Ino, like my mother Agave. The priest, gently — when I look at you it seems I see their very selves — leans in to fix a lock of hair that has come loose, smooths the sash, corrects the way the gown is falling. Pentheus boasts that he could lift Cithaeron on his shoulders; the priest agrees. Pentheus thinks of bringing down the temples of Pan, then catches himself — force is not the right thing for women. He will lie hidden in the pine-thickets.`,
        `Pentheus is now eager. He wants to be borne home in triumph and his mother's hands to share in carrying him. He goes off toward the mountain, led by the priest. Alone for a moment, Dionysus drops the priest's voice. Fell, fell are you, he says, and to a doom so fell you walk that your name from south to north shall shine, a sign forever. He calls on Agave and her sisters to meet this proud prince at his ordeal. Then he follows Pentheus offstage.`,
      ],
      appears: [{ id: 'pentheus', name: 'Pentheus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'chorus', name: 'The Chorus' }],
      themes: [{ slug: 'seduction', label: 'The seduction' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'reason-ecstasy', label: 'Reason and ecstasy' }],
    },
    {
      n: 10, title: 'Fourth Stasimon', tourTitle: 'The chorus on the spy', hook: 'The chorus drop their composure for the only time in the play. They call on the hounds of madness, on Justice, on the god to come as bull or snake or lion and end this.',
      tour: `The chorus sing the fourth stasimon. The composure of the earlier odes is gone. They invoke the hounds of the maddened mind to drive the women to find Pentheus. They imagine the moment of discovery — whose eye will catch him first, will it be his mother. They cry out for Justice to come with her sword and strike the throat. They call on Dionysus — appear, appear, whatever your shape or your name, mountain bull, snake of the hundred heads, lion of burning flame — to laugh aloud and drag the spy to his death. The song ends with a messenger running in pale and distraught from the mountain road, gasping, with news for the city.`,
      blurb: `The chorus drop the composure of the earlier odes. They invoke the hounds of the maddened mind to drive the women to find Pentheus. They call on Justice to come with her sword and strike the throat. They summon the god — appear, whatever your shape or your name, mountain bull, snake of the hundred heads, lion of burning flame — to laugh aloud and drag the spy to his death. The song ends with a second messenger running in pale and shaken from the mountain.`,
      summary: [
        `The chorus, alone after Dionysus has gone after Pentheus, sing the shortest and most violent of their odes. The earlier songs have been ecstatic, philosophical, longing. This one is none of those. It opens with hounds — hounds raging and blind, up by the mountain road, spirits of the maddened mind — and calls them to fill the women's eyes with rage at the watcher in woman's guise, the spy on God's possessed. They imagine the moment of discovery. Whose eye will catch him first. Will it be his mother. Will the cry go up that this is no man but a beast.`,
        `They call directly for the killing. Hither, for doom and deed; hither with lifted sword, Justice, Wrath of the Lord, come in our visible need. Smite till the throat shall bleed. The refrain comes back hard. They name Pentheus's crime: he has trodden tyrannously, marched in defiance against the god's light and his mother's light, blinded in his own craft, trying to crush by violence things unconquerable. They sing one steadier strophe — knowledge, we are not enemies; the world blows toward beautiful things, until life breaks clean and pure and sings glory to god in the height — and then the killing call returns.`,
        `The leader closes the ode with the most direct invocation of the god in the play. <em>Appear, appear, whatever your shape or your name — O Mountain Bull, Snake of the Hundred Heads, Lion of Burning Flame! O God, Beast, Mystery, come!</em> The mystic maids are hunted. Blast their hunter with your breath. Cast over his head your snare. Laugh aloud, and drag him to his death. The song ends. From the side of the stage a man enters at a run, pale, distraught, gasping for breath. He has come down the mountain. He has news for the city.`,
      ],
      appears: [{ id: 'chorus', name: 'The Chorus' }, { id: 'messenger2', name: 'The Second Messenger (entering)' }],
      themes: [{ slug: 'refused-god', label: 'The god refused' }, { slug: 'mother-recognition', label: 'The recognition' }],
    },
    {
      n: 11, title: 'The messenger, Agave, the judgement', tourTitle: 'Agave with the head', hook: 'The second messenger\'s report from the mountain. Agave at the gate carrying her son\'s head, calling it a lion. Cadmus walking her, sentence by sentence, back to the truth. The god in the air, naming the future.',
      tour: `The second messenger reports the killing. Dionysus bent a pine to the ground, set Pentheus in its top, and let it spring back; from the sky he called the women to see their spy. They tore the pine up by the roots; Pentheus, lucid at the last, pleaded with his mother to recognise him. She did not. They tore him apart. Agave enters carrying his head on a thyrsus, calling it a lion's. Cadmus arrives with the gathered body and walks her back, question by question, to the truth in real time. Dionysus appears above the house in his divine form, pronounces exile on Cadmus and Agave, and ends the play.`,
      blurb: `The second messenger gives the longest speech in the play: the bent pine, the call from the sky, the dismemberment. Agave arrives at the gate carrying her son's head, calling it a lion she killed with her hands. Cadmus arrives with the gathered body and walks her back to the truth in real time, question by question, until the head in her hands is no longer a lion's. Dionysus appears above the house and pronounces exile. The chorus close: the end men looked for does not come.`,
      summary: [
        `The second messenger delivers the longest speech in the play. He climbed the mountain with Pentheus and the priest. They lay hidden in a green dell, watching the women at work. Pentheus could not see well enough; he asked to be lifted higher. The priest touched the crown of a great pine and bent it to the ground with strength not mortal, set the king in its branches, and let it back up. A voice came from empty air — the priest was gone, and the voice was the god's: behold, women, I bring you the man who spites both me and you. The women tore the pine from the ground; Pentheus fell, pulled off the wig, begged his mother to recognise him. She did not.`,
        `Agave enters carrying the head. She is, by every visible measure, happy. She calls on the chorus to bless her hunt. The leader cannot answer. Cadmus arrives with a bier — he has gathered what could be gathered of his grandson's body. He does not tell her. He asks her questions. Lift your eyes to the sky. Who was your husband. What son did you bear him. Look at what you are holding. The madness drains. The head is no longer a lion's.`,
        `Dionysus appears above the house in his divine form. There is a missing page here; his speech begins mid-sentence. He pronounces the future: Cadmus turned into a serpent; Agave exiled from Thebes forever. The god is unmoved. <em>You mocked me, who am God; this is your wage.</em> He rises on the cloud and disappears. The chorus close with the lines that close five surviving Euripidean tragedies. <em>There are many shapes of mystery, and many things god brings to pass past hope or fear. The end men looked for does not come, and a path is opened where no man thought.</em>`,
      ],
      appears: [{ id: 'messenger2', name: 'The Second Messenger' }, { id: 'chorus', name: 'The Chorus' }, { id: 'agave', name: 'Agave' }, { id: 'cadmus', name: 'Cadmus' }, { id: 'dionysus', name: 'Dionysus' }, { id: 'pentheus', name: 'Pentheus (in the report)' }],
      themes: [{ slug: 'mother-recognition', label: 'The recognition' }, { slug: 'refused-god', label: 'The god refused' }, { slug: 'last-play', label: 'The last play' }],
    },
  ],
};
