// SEO content data for Paul's Letter to the Romans.
// Composed at Corinth in winter 56-57 CE, dictated to Tertius (Romans 16:22).
// Voice: literary, declarative present. Treat the text as text — for faithful and secular readers alike.

const chapters = require('/tmp/bible-romans-chunk-1.json');

module.exports = {
  id: 'bible-romans',
  title: 'Romans',
  author: 'Paul of Tarsus',
  byline: 'c. 57 CE · New Testament · Pauline Epistle',
  year: 57,
  titleAccent: 'a guided tour',
  hook: 'The most carefully argued letter ever written. Paul dictates sixteen chapters to a scribe in a port city in Greece, and sends them ahead of himself to a church he has never visited — to explain the gospel he has been preaching for twenty years.',
  genre: ['Epistle', 'Theology', 'New Testament'],
  themesBlurb: 'Justification by faith, Jew and Gentile, the divided self, the practice of the gospel.',
  castBlurb: 'Rome and Corinth',
  castDesc: 'The people behind the most influential letter in Western history.',

  blurb:
    "The longest and most carefully argued letter in the New Testament. Paul writes Romans from Corinth in the winter of 56-57 CE to a church he has not yet visited, on the eve of a long-planned trip to Jerusalem and a hoped-for journey beyond Rome to Spain. The letter is his most considered statement of the gospel he has been preaching for two decades — what God has done in Jesus Christ, how Jew and Gentile fit into one community, what justification by faith means, and what kind of life the gospel produces in ordinary practice. Augustine read Romans and was converted. Luther read it and was unsettled into the Reformation. Karl Barth read it in the trenches of the First World War and wrote the commentary that re-founded twentieth-century theology.",

  about: [
    `<em>Romans</em> is the longest and most carefully argued letter in the New Testament. Paul writes it from Corinth in the winter of 56-57 CE, near the end of what scholars call his third missionary journey. He is about to take a collection to Jerusalem, expects trouble there, and plans afterward to travel west — past Rome to Spain. Romans is the letter he writes ahead of that visit, partly to introduce himself to a church he did not found, partly to enlist their support, and mostly to set out the gospel he has been preaching for twenty years in its most sustained form.`,
    `He does not write it himself. Romans 16:22 is one of the most quietly remarkable verses in the New Testament: <em>I Tertius, the writer of this letter, greet you in the Lord</em>. Tertius is a professional scribe taking dictation over multiple sessions; the letter is delivered by Phoebe, a deacon of the church at Cenchreae, travelling to Rome on her own business. The structure is unusually clear for Paul: chapters 1-4 diagnose the universal problem and prescribe justification by faith; chapters 5-8 trace the consequences for believers; chapters 9-11 wrestle with the question of Israel; chapters 12-16 translate the theology into practice. Every serious reader of the Western tradition has had to reckon with it.`,
  ],

  summary: [
    "Paul writes Romans from Corinth in the winter of 56-57 CE, near the end of what scholars call his third missionary journey. He has spent the previous decade founding and tending churches around the eastern Mediterranean — Galatia, Macedonia, Achaea, Asia — and the great work of his recent years has been a collection for the impoverished believers in Jerusalem, gathered from the Gentile churches as a tangible sign of the unity between his mission and the Jerusalem apostles. He is about to take that collection up to Jerusalem in person; he expects trouble there, and he is right (the arrest narrated in Acts 21 is on the other side of this letter). What he plans to do after Jerusalem is travel west, past Rome, to Spain — the western edge of the empire, the end of the earth as Paul's geography would have it. Romans is the letter he writes ahead of that planned visit, partly to introduce himself to a church he has not founded, partly to enlist their support for the Spanish journey, and partly — most importantly — to set out the gospel he preaches in its most sustained form.",
    "He does not write the letter in his own hand. Romans 16:22 is one of the most quietly remarkable verses in the New Testament: I Tertius, the writer of this letter, greet you in the Lord. Tertius is a professional scribe, taking dictation; the letter we have is what he wrote down as Paul spoke. The carrier of the letter is named at the start of chapter 16 — Phoebe, a deacon of the church at Cenchreae (the eastern port of Corinth), travelling to Rome on her own business and entrusted with delivering and probably reading aloud the letter Paul has dictated. The materiality of the document is worth holding in mind. A long parchment letter, dictated over several sessions, carried by a woman across the Aegean and the Adriatic to a church the writer has never seen, read aloud in someone's house in Rome to a gathering of believers who are about to hear, for the first time, what the most argumentative apostle of their generation thinks the gospel actually means.",
    "The structure of the letter is unusually clear for Paul. Chapters 1-4 set out the universal need for the gospel: all human beings, Gentile and Jew alike, are under sin, and justification comes not by works of the law but by faith in Jesus Christ — the position Paul demonstrates from Genesis 15 and the figure of Abraham. Chapters 5-8 follow the consequences for the believer: peace with God through Jesus Christ, the new life in the Spirit, the famous chapter 7 in which the I struggles with the law and the equally famous chapter 8 in which there is therefore now no condemnation for those who are in Christ Jesus. Chapters 9-11 take up the hardest single question Paul faces: if the gospel is for everyone, what becomes of Israel, the original people of the promise? His answer in three chapters is dense, anguished, and ends with one of the most quoted doxologies in Christian literature. Chapters 12-15 turn from theology to practice: present your bodies as a living sacrifice; love one another; be subject to the governing authorities (with all the difficulties that injunction has caused); the strong and the weak in matters of food and observance. Chapter 16 is the long greeting list — twenty-six people named, including Phoebe, Aquila and Prisca, the only female apostle in the New Testament (Junia, Romans 16:7, contested for centuries by translators uncomfortable with the implication), and Tertius the scribe inserting his own greeting — and a final benediction.",
  ],

  tour:
    "Sixteen chapters, four movements, one carefully built argument. Chapters 1-4 are diagnosis (the universal predicament under sin) and prescription (justification by faith, demonstrated from Abraham). Read 1:16-17 carefully — it is the thesis of the whole letter — and then 3:21-26, the most concentrated statement of the gospel anywhere in Paul. Chapters 5-8 are the consequences: peace, hope, the new life. Chapter 7 is the I struggling with the law (whoever the I is — debated for two thousand years), and chapter 8 is the great climax (there is therefore now no condemnation... if God is for us, who is against us?... nothing shall separate us from the love of God in Christ Jesus our Lord). Chapters 9-11 are the long meditation on Israel; do not skip them. Chapter 12 onward is the practice, with 13:1-7 (governing authorities) the most contested few verses in the letter. Chapter 16 is the names. Read them slowly — they are the human face of the early Pauline mission.",

  chaptersSubtitle: 'All 16 chapters summarized — from the greeting and thesis through to the closing names and benediction.',
  chaptersLead: `<p>Romans is structured in four movements. Chapters 1-4 are the diagnosis and the prescription: universal sin, justification by faith, Abraham as the demonstration. Chapters 5-8 are the consequences for believers: peace, hope, the new life in the Spirit — culminating in the great "no condemnation" of chapter 8. Chapters 9-11 are the hardest meditation on Israel. Chapters 12-16 are the practice: living sacrifice, love, governing authorities, the strong and the weak, and the long closing greetings.</p>`,
  themesByline: 'Five threads through the letter',
  themesLead: `Romans is the letter Paul wrote when he had time to think. The others — Galatians, Corinthians, Thessalonians — were written in the middle of crises. Romans was written at relative peace, on the eve of a journey, with the full gospel to set out. These are the threads that run through it.`,

  groups: [
    { label: 'Greeting and thesis · 1-4', subtitle: 'The diagnosis and prescription. Universal sin; justification by faith; Abraham.', chapters: [1, 2, 3, 4] },
    { label: 'New life in the Spirit · 5-8', subtitle: 'Peace, hope, the divided I, and the great climax of chapter 8.', chapters: [5, 6, 7, 8] },
    { label: 'Israel · 9-11', subtitle: "The hardest question. Has God abandoned his promises? Paul's anguished three-chapter answer.", chapters: [9, 10, 11] },
    { label: 'Practical instruction · 12-16', subtitle: 'Living sacrifice, love, governing authorities, the strong and the weak — and the names.', chapters: [12, 13, 14, 15, 16] },
  ],

  chapterLabel: n => 'Romans ' + n,

  themes: [
    {
      slug: 'the-thesis-at-1-16-17',
      title: 'The Thesis at 1:16-17',
      greek: 'to the Jew first and also to the Greek',
      preview: 'Paul states the thesis of the entire letter in two verses. Everything that follows is an unpacking of those verses: salvation, righteousness, faith, Jew, Greek, gospel, power — named in the order he will treat them.',
      essay: [
        `Paul states the thesis of the entire letter in two verses near the beginning, and the structure of everything that follows is built on them. I am not ashamed of the gospel, he writes, for it is the power of God for salvation to everyone who believes, to the Jew first and also to the Greek. For in it the righteousness of God is revealed through faith for faith, as it is written, the one who is righteous will live by faith. The verses are short and dense, and every word will be worked over in the chapters that follow. Salvation, righteousness, faith, Jew, Greek, gospel, power — these are the terms of the argument, and Paul has set them out in the order he will treat them.`,
        `For everyone who believes, to the Jew first and also to the Greek. The phrase to the Jew first and also to the Greek is the structural principle of the first eleven chapters of the letter. Paul wants to argue that the gospel is universal — it is for everyone — but he refuses to argue this by erasing the historical priority of Israel. The Jews come first; the gospel is theirs first; the promises were made to them first; and only because the promises to Israel are being fulfilled in Christ does the gospel reach the Gentiles at all. The careful sequencing is what makes Romans 9-11 necessary. If Paul had simply said the gospel is for everyone, he would not have needed those three anguished chapters on the question of Israel. Because he says to the Jew first, the question of how the priority is preserved when most of the Jewish nation has not embraced the gospel becomes inescapable.`,
        `The righteousness of God is revealed. The Greek phrase dikaiosynē theou has been one of the most contested terms in modern New Testament scholarship. Does it mean the righteousness that God himself possesses, the moral attribute by which he is just? Does it mean the righteousness that God gives to human beings, the gift by which they are made right with him? Does it mean God's faithfulness to his covenant promises, his vindicating action on behalf of his people? The traditional Reformation reading has emphasized the second; the so-called New Perspective on Paul, from E.P. Sanders forward, has emphasized the third; many modern interpreters now hold that all three meanings are at work and that Paul does not separate them. The argument of the letter requires all three: God is just, and gives justification, and is faithful to his promises, and the gospel reveals all of this at once.`,
        `Through faith for faith. The Greek ek pisteōs eis pistin is unusually compressed, and English translations vary widely (from faith to faith, by faith from first to last, through faith for faith). What is plain is that Paul is making faith — pistis — the structural mode of the new relationship between God and human beings. The one who is righteous will live by faith, he quotes from Habakkuk 2:4, and the verse will run through the rest of the letter. Faith, in Paul's vocabulary, is not first an emotion or an opinion. It is the trust by which a human being commits himself to what God has done in Christ. Everything that follows is the working out of what that trust means.`,
      ],
      where: [
        { n: 1, label: 'Romans 1 (the thesis, vv. 16-17)' },
        { n: 3, label: 'Romans 3 (the concentrated statement, vv. 21-26)' },
        { n: 4, label: 'Romans 4 (Abraham as demonstration)' },
        { n: 10, label: 'Romans 10 (faith and confession)' },
      ],
    },
    {
      slug: 'justification-by-faith',
      title: 'Justification by Faith',
      greek: '"apart from law, the righteousness of God has been manifested"',
      preview: 'The doctrine for which Romans is best known. Paul argues from chapter 3 through chapter 4 that no one can be justified by works of the law — and that Abraham himself was reckoned righteous before he was circumcised.',
      essay: [
        `The doctrine for which Romans is best known, and the one on which Augustine, Luther, and the long Protestant tradition built their theology of grace. Paul's argument runs from chapter 3 through chapter 4. The argument has two parts. First, he establishes that no one can be justified by works of the law — by the kind of moral and ritual obedience the Mosaic covenant required. Both Jews and Gentiles are under sin (the long indictment runs from 1:18 through 3:20); both stand condemned; the law itself, far from solving the problem, makes it worse, because the law makes sin definite (3:20: through the law comes knowledge of sin). Second, he sets out the alternative. But now, he writes at 3:21, apart from law, the righteousness of God has been manifested, the law and the prophets bearing witness to it — the righteousness of God through faith in Jesus Christ for all who believe. There is no distinction; for all have sinned and fall short of the glory of God; they are justified by his grace as a gift, through the redemption that is in Christ Jesus, whom God put forward as a propitiation by his blood, to be received by faith.`,
        `The key terms are loaded. Justified — dikaioō in Greek — is a legal metaphor: to declare righteous, to acquit. Grace — charis — is gift, freely given. Redemption — apolytrōsis — is the buying back of a slave or a captive, the freeing of someone who could not free himself. Propitiation — hilastērion — is the place or means by which the wrath of God is appeased, with the Hebrew Bible echo of the kapporeth, the cover of the ark of the covenant in the temple, where the high priest sprinkled blood once a year on the Day of Atonement. Paul is stacking the metaphors deliberately. The justification he is describing is not one thing but a many-sided event — legal, financial, ritual, personal — and he wants the full freight of all the metaphors at once.`,
        `Chapter 4 then takes Abraham as the demonstration. Abraham was justified, Paul argues, before he was circumcised and before the law was given at Sinai. Genesis 15:6 — and he believed the Lord, and the Lord reckoned it to him as righteousness — comes before Genesis 17, when circumcision is instituted, and centuries before Moses. Abraham is therefore the father of all who believe, Jew and Gentile alike, on the basis of faith and not of law. The argument is exegetically careful and rhetorically devastating. The Jewish boast in Abraham as the founder of the circumcised people is reframed: Abraham was a man of faith before he was circumcised, and the faith is what counted.`,
        `What the doctrine has meant in the long history of Christian theology has varied. For Augustine, justification by faith named the priority of grace over human merit and was the cure for the Pelagian temptation to think one could earn one's standing before God. For Luther, who read Romans during the long crisis that produced the Reformation, the doctrine was the central good news of Christianity — the announcement that one could not earn one's way to God by religious performance and that the demand to do so was the chief obstacle to grace. For modern interpreters in the so-called New Perspective, the doctrine is more about the inclusion of Gentiles into the covenant on terms other than the law than about the predicament of the anxious individual conscience. The tradition continues to argue. The text continues to do its work.`,
      ],
      where: [
        { n: 3, label: 'Romans 3 (the case, vv. 21-26)' },
        { n: 4, label: 'Romans 4 (Abraham)' },
        { n: 5, label: 'Romans 5 (peace with God)' },
        { n: 9, label: 'Romans 9 (election)' },
      ],
    },
    {
      slug: 'jew-and-gentile',
      title: 'Jew and Gentile in One Community',
      greek: '"O the depth of the riches and wisdom and knowledge of God!"',
      preview: "The hardest single problem for Paul. The gospel fulfils Israel's promises — yet most of Israel has not received it. Romans 9-11 is his most sustained answer: three anguished chapters ending in a doxology.",
      essay: [
        `The hardest single problem for Paul, in Romans and in his other letters, is the relation between the church and Israel. The gospel he preaches is the fulfilment of the promises made to Israel in the Hebrew Bible — the Messiah of Israel has come, the prophets have been vindicated, the new covenant of Jeremiah has been inaugurated, the Spirit promised by Joel has been poured out. And yet the people to whom these promises were originally made have, by and large, not received the gospel. The early Pauline communities are increasingly Gentile. The historical synagogue, the actual descendants of Abraham, have mostly remained outside the new movement. What does this mean? Has God abandoned his promises? Is the church a replacement for Israel, or a continuation, or something else?`,
        `Romans 9-11 is Paul's most sustained answer, and it is one of the densest pieces of theological reasoning in the New Testament. Chapter 9 is the most painful. I have great sorrow and unceasing anguish in my heart, Paul writes. For I could wish that I myself were accursed and cut off from Christ for the sake of my brothers, my kinsmen according to the flesh. The line is shocking and unforgettable. Paul, who has been the apostle to the Gentiles, is willing to be damned if it would mean Israel's salvation. He then works through the question by appeal to the doctrine of election: God has always chosen freely, and not all who are descended from Israel are Israel in the fullest sense. The argument is hard and has been read in different ways across the tradition.`,
        `Chapter 10 turns from divine election to human responsibility. The word of faith is near you, Paul writes, on your lips and in your heart — that is, the word of faith that we proclaim. If you confess with your lips that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved. Israel has heard the gospel and has not, by and large, accepted it. But the rejection is not the end. The end of the chapter is one of the most quoted appeals in the letter: how are they to call on him in whom they have not believed? And how are they to believe in him of whom they have never heard? And how are they to hear without someone preaching? And how are they to preach unless they are sent?`,
        `Chapter 11 is the most consequential. Has God rejected his people? Paul asks. By no means. He himself is a Jew, and there is a remnant of Jewish believers (he names himself among them). The hardening of most of Israel is a temporary state, with a purpose: it has been the occasion of Gentile inclusion. And eventually — Paul reaches for an image — the Gentiles, like wild olive branches, have been grafted into the cultivated olive tree of Israel; the natural branches that have been broken off can and will be grafted back in; in this way all Israel will be saved. The chapter ends with one of the most extraordinary doxologies in Paul: O the depth of the riches and wisdom and knowledge of God! How unsearchable are his judgments and how inscrutable his ways. The doxology is the moment Paul lets go of the argument and lets the mystery stand.`,
      ],
      where: [
        { n: 9, label: 'Romans 9 (election and anguish)' },
        { n: 10, label: 'Romans 10 (confession and hearing)' },
        { n: 11, label: 'Romans 11 (the olive tree and the doxology)' },
        { n: 4, label: 'Romans 4 (Abraham, father of all)' },
      ],
    },
    {
      slug: 'romans-7-divided-self',
      title: 'Romans 7 and the Divided I',
      greek: '"Wretched man that I am! Who will deliver me from this body of death?"',
      preview: "One of the most personal passages in any of Paul's letters and one of the most contested. The I who cannot do what it wants has been argued over for two thousand years — and quoted by every later writer who needed to describe weakness of will.",
      essay: [
        `Chapter 7 contains one of the most personal passages in any of Paul's letters and one of the most contested. He has been arguing in chapters 5 and 6 that the believer, having died with Christ in baptism, is no longer enslaved to sin. Then in chapter 7 he addresses what role the law plays in the new life. The law itself, he insists, is holy and righteous and good. But the human encounter with the law is not. He uses the example of the commandment you shall not covet (the tenth commandment from Exodus 20). The commandment, far from defeating sin, has actually given sin a foothold; once the prohibition exists, the desire for what is prohibited is sharpened, and what should have led to life leads instead to death.`,
        `Then, beginning at 7:14, the language shifts to a sustained first-person present-tense lament. We know that the law is spiritual; but I am of the flesh, sold under sin. I do not understand my own actions. For I do not do what I want, but I do the very thing I hate. I can will what is right, but I cannot do it. For I do not do the good I want, but the evil I do not want is what I do. Wretched man that I am! Who will deliver me from this body of death? The passage runs for about a dozen verses and is one of the most quoted descriptions of moral self-division in any literature.`,
        `Who is the I? The question has been argued for two thousand years and is still open. Augustine, in the early phase of his thinking, read the I as Paul before his conversion — the unconverted person under the law, struggling without the help of the Spirit. Augustine later changed his mind and read the I as Paul as a believer, struggling with sin even under grace, and Luther followed Augustine's later position. Many modern interpreters have argued that the I is rhetorical: Paul is using the first person to dramatize the predicament of humanity under the law in general, not narrating his own experience. Others have argued that the I is specifically Adam, or Israel under Sinai, or the human being viewed apart from Christ.`,
        `What the chapter undeniably accomplishes, whoever the I is, is a sustained literary depiction of the experience of moral failure even in someone who knows what is right and wants to do it. The famous lines have been quoted by every later writer in the Western tradition who has had to describe akrasia, weakness of will, the gap between intention and action. Augustine in the Confessions reaches for this passage repeatedly. Kierkegaard in The Sickness unto Death builds his anatomy of despair partly out of it. Modern moral psychology has rediscovered, in its own vocabulary, much of what the chapter says. The wretched man who cries out at the end has been one of the most resonant figures in Christian self-understanding, and the deliverance he seeks — Paul names it in the very next breath: thanks be to God through Jesus Christ our Lord — has been the answer most readers come to the chapter for.`,
      ],
      where: [
        { n: 7, label: 'Romans 7 (the divided I)' },
        { n: 6, label: 'Romans 6 (dead to sin)' },
        { n: 8, label: 'Romans 8 (no condemnation)' },
        { n: 5, label: 'Romans 5 (sin entered through Adam)' },
      ],
    },
    {
      slug: 'living-sacrifice',
      title: 'Living Sacrifice — The Practice of the Gospel',
      greek: '"Present your bodies as a living sacrifice, holy and acceptable to God"',
      preview: 'Chapter 12 begins with the word therefore. Everything from here is the working-out of what the theology means in practice: present your bodies, love one another, the governing authorities, the strong and the weak.',
      essay: [
        `Paul's theological argument runs through chapter 11. Chapter 12 begins with the word therefore, and the rest of the letter is the working out of what the theology means in practice. I appeal to you therefore, brothers and sisters, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship. Do not be conformed to this world, but be transformed by the renewal of your mind, that you may discern what is the will of God, what is good and acceptable and perfect.`,
        `The verse establishes the pattern of the practical chapters. The new life is bodily — present your bodies — and Paul refuses any spiritual reading that leaves the body out. It is sacrificial in the sense that it is given over in service, but it is a living sacrifice, not a dead one; the offering is not the end of life but the form of life. It is corporate, not individualist: the body is offered as part of the body of Christ, the community, in which each member has different gifts to be exercised for the good of the whole. Chapter 12 then runs through a long list of practical exhortations: love one another with brotherly affection; outdo one another in showing honour; bless those who persecute you; weep with those who weep; never be conceited; do not repay evil for evil; if your enemy is hungry, feed him.`,
        `Chapter 13 contains the verses that have caused the most controversy in the letter — the instruction to be subject to the governing authorities, on the grounds that there is no authority except from God, and the authorities that exist have been instituted by God. The verses have been used across the tradition to justify obedience to whatever government happens to be in power, including governments that no reader of Romans would defend, and the ways in which they have been used and misused are a long subject. What Paul actually wrote, in the specific situation of the mid-50s in Rome under Nero (still in the relatively benign early years of his reign), is more limited than the long history of citation suggests; the verses are a counsel of public peace for a small minority community in the imperial capital, not a general theology of the state. But the verses are there, and they have done their work, for good and for ill, ever since.`,
        `Chapters 14 and 15 take up a specific dispute in the Roman church between the strong and the weak — those who eat anything and observe no special days, and those who eat only vegetables and observe certain days. Paul's counsel is patience on both sides, and a refusal to despise either. Welcome those who are weak in faith, but not for quarrels over opinions. The strong should bear the failings of the weak. The chapters end with a vision of the unity of Jew and Gentile in the praise of God, and a long quotation of Hebrew Bible texts about the inclusion of the nations. Then the long closing greetings of chapter 16, and the final benediction. The letter ends, as it began, with the gospel — the gospel and the preaching of Jesus Christ, according to the revelation of the mystery that was kept secret for long ages but has now been disclosed.`,
      ],
      where: [
        { n: 12, label: 'Romans 12 (living sacrifice and love)' },
        { n: 13, label: 'Romans 13 (governing authorities)' },
        { n: 14, label: 'Romans 14 (the strong and the weak)' },
        { n: 16, label: 'Romans 16 (the names)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Paul', role: 'Author, Apostle to the Gentiles', body: `Born in Tarsus, a Roman citizen, raised as a Pharisee, converted on the road to Damascus in the mid-30s. Writes Romans from Corinth near the end of his third missionary journey. The letter is the most carefully argued of his surviving writings and his most considered statement of the gospel he has preached for twenty years.` },
    { name: 'Tertius', role: 'Scribe', body: `The professional scribe who took down Paul's dictation and produced the physical letter. He inserts his own greeting at 16:22 — I Tertius, the writer of this letter, greet you in the Lord — one of the most quietly remarkable verses in the New Testament.` },
    { name: 'Phoebe', role: 'Deacon, carrier of the letter', body: `A deacon of the church at Cenchreae, the eastern port of Corinth. Paul commends her to the Roman church at the start of chapter 16. She carried the letter to Rome, and probably read it aloud at its first reception there.` },
    { name: 'Abraham', role: 'Father of faith', body: `Not a contemporary of Paul but the figure on whom the demonstration of justification by faith in chapter 4 turns. Paul argues that Abraham was reckoned righteous before he was circumcised — making him the father not only of the circumcised but of all who believe.` },
    { name: 'The I of Romans 7', role: 'Divided self', body: `The first-person voice that emerges at 7:14 in one of the most contested passages in Paul. I do not do what I want, but I do the very thing I hate. Who the I is — Paul before conversion, Paul as believer, Adam, Israel, humanity — has been argued for two thousand years.` },
    { name: 'Junia', role: 'Apostle (Romans 16:7)', body: `Named at 16:7 as outstanding among the apostles — a woman, which caused translators for centuries to masculinize the name to Junias. Modern scholarship has returned to the female form. She is the only woman in the New Testament identified as an apostle.` },
  ],

  castSubtitle: 'Rome and Corinth — the people behind the most influential letter in Western history.',
  castLead: `<p>Romans names more people than almost any other Pauline letter. Chapter 16 alone contains twenty-six names — men and women, Jews and Gentiles, freed slaves and householders — giving a rare glimpse of the actual social texture of the early Pauline communities. The figures listed here range from Paul's collaborators to the unnamed I of chapter 7.</p>`,
  castGroups: [
    {
      label: 'The writers',
      characters: [
        { id: 'paul', tag: 'Historical', name: 'Paul', epithet: 'Apostle, author of the letter', body: `Born in Tarsus in Cilicia, probably in the first decade of the first century CE, a Roman citizen by birth, raised as a Pharisee, educated in Jerusalem under Gamaliel. Converted on the road to Damascus in the mid-30s by a vision of the risen Jesus. Spends the next two decades founding and tending churches around the eastern Mediterranean. Writes Romans from Corinth in the winter of 56-57 CE on the eve of the trip to Jerusalem that will end with his arrest. He is executed under Nero, probably in 64 or 65, beheaded as a Roman citizen on the Ostian Way outside the city.`, appears: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
        { id: 'tertius', tag: 'Historical', name: 'Tertius', epithet: 'Scribe', body: `The professional scribe to whom Paul dictates Romans. Named explicitly at 16:22, where he inserts his own greeting: I Tertius, the writer of this letter, greet you in the Lord. He would have sat with a stylus taking down Paul's dictation over multiple sessions, probably with revision and second drafts. Whether he had a hand in the phrasing is unknowable; the dense argumentation is clearly Paul's. What is certain is that the letter is a co-production, and the human face of that co-production is Tertius.`, appears: [16] },
      ],
    },
    {
      label: 'The carriers and hosts',
      characters: [
        { id: 'phoebe', tag: 'Historical', name: 'Phoebe', epithet: 'Deacon of Cenchreae, carrier of the letter', body: `A deacon of the church at Cenchreae, the eastern port of Corinth, mentioned at the start of chapter 16. Paul commends her to the Roman church: I commend to you our sister Phoebe, a deacon of the church at Cenchreae, that you may welcome her in the Lord as is fitting for the saints. She carries the letter to Rome on her own business and probably reads it aloud at its first reception there. She is one of the very few women named with an official ecclesiastical title in the New Testament.`, appears: [16] },
        { id: 'aquila-priscilla', tag: 'Historical', name: 'Aquila and Priscilla', epithet: 'Fellow workers, hosts of a house church', body: `Married couple from Pontus, leather-workers of the same trade as Paul. Driven from Rome by Claudius's expulsion of the Jews around 49 CE; Paul met them in Corinth and worked alongside them; they later moved to Ephesus. By the time of Romans they have returned to Rome and host a church in their house. Paul names them at 16:3 as my fellow workers in Christ Jesus, who risked their necks for my life. Priscilla is named first — unusual in ancient practice and probably a mark of her relative prominence.`, appears: [16] },
        { id: 'junia', tag: 'Historical', name: 'Junia', epithet: 'Apostle (Romans 16:7)', body: `Named at 16:7 as outstanding among the apostles. A woman — which caused translators for centuries to masculinize the name to Junias. Modern scholarship has restored the female form. She is, alongside the general greeting of the apostles at the end of 1 Corinthians 15, the only woman in the New Testament identified with the title apostle.`, appears: [16] },
      ],
    },
    {
      label: 'The figures in the argument',
      characters: [
        { id: 'abraham', tag: 'Historical', name: 'Abraham', epithet: 'Father of faith', body: `Not a contemporary of Paul but the figure on whom the demonstration of justification by faith in chapter 4 turns. Paul argues that Abraham was reckoned righteous (Genesis 15:6) before he was circumcised (Genesis 17) and centuries before the law was given at Sinai. Abraham is therefore the father not only of the circumcised but of all who walk in the footsteps of the faith that he had before he was circumcised. The argument is the structural pivot of the doctrine of justification by faith.`, appears: [4, 9, 11] },
        { id: 'divided-i', tag: 'Rhetorical', name: 'The I of Romans 7', epithet: 'Divided self', body: `The first-person voice that emerges at 7:14 in one of the most contested passages in Paul: I do not understand my own actions. For I do not do what I want, but I do the very thing I hate. Wretched man that I am! Who will deliver me from this body of death? Who the I is — Paul before conversion, Paul as a believer struggling with sin, Adam, Israel under the law, or simply rhetorical humanity — has been argued for two thousand years. The passage has been quoted by every later writer in the Western tradition who needed to describe weakness of will.`, appears: [7] },
        { id: 'adam', tag: 'Historical', name: 'Adam', epithet: 'Through whom sin entered', body: `Named at 5:12-21 as the figure through whom sin and death entered the world, and contrasted with Christ as the figure through whom grace and life entered. The contrast — the first Adam and the last Adam — is one of Paul's central typological arguments and appears also in 1 Corinthians 15. In Romans 5 Paul uses it to show that just as one man's trespass led to condemnation for all, so one man's righteous act leads to justification and life for all.`, appears: [5] },
      ],
    },
  ],

  chapters,
};
