// SEO content data for Judges — seventh book of the Hebrew Bible.
// Deuteronomistic History, edited 6th c. BCE.
// Voice: literary, declarative present.

module.exports = {
  id: 'bible-judges',
  title: 'Judges',
  author: 'Anonymous (Deuteronomistic History)',
  byline: 'c. 6th c. BCE · Hebrew Bible · Former Prophets',
  titleAccent: 'a guided tour',
  hook: 'Between Joshua and Samuel, Israel keeps repeating the same mistake. Twelve deliverers rise, save the people, and die. The people immediately forget. The book ends with a question it refuses to answer: who will rule when no one does?',
  genre: ['Scripture', 'Hebrew Bible', 'Historical narrative', 'Ancient literature'],

  about: [
    `<em>Judges</em> is the dark book between Joshua and Samuel — the period of charismatic deliverers who rise when Israel is in trouble and disappear when the trouble is past, leaving the people to slip back into idolatry and chaos. Deborah sings on a hilltop. Gideon throws down his father's altar to Baal. Jephthah makes a vow that costs him his daughter. Samson pulls down the temple of Dagon on his own head. The book closes in two stories of such horror that its final verse — <em>in those days there was no king in Israel; everyone did what was right in his own eyes</em> — reads as both an explanation and a warning.`,
    `Judges reaches its final form during or just after the Babylonian exile in the 6th century BCE, edited as part of the Deuteronomistic History that runs from Joshua through 2 Kings. The Song of Deborah in chapter 5 is widely considered one of the oldest pieces of Hebrew poetry surviving anywhere, possibly going back to the twelfth century BCE; other materials are clearly later. The book covers the period between the death of Joshua and the rise of the prophet Samuel — roughly the late thirteenth to the eleventh century BCE — when Israel is a loose confederation of tribes in the central highlands of Canaan, surrounded by Philistines on the coastal plain, Moabites and Ammonites east of the Jordan, and various Canaanite city-states still occupying parts of the land Joshua was supposed to have taken.`,
  ],

  chaptersSubtitle: 'All 21 chapters — from the unfinished conquest to the horror of Gibeah.',
  chaptersLead: `<p>Judges is structured in three movements. Chapters 1–2 are the frame: the unfinished conquest and the editors' theological explanation of what follows. Chapters 3–16 are the cycle of judges: six major narratives and six minor figures, each in the repeating pattern of sin, oppression, cry, deliverance, peace. Chapters 17–21 are the two appendices — the migration of Dan and the Levite's concubine — which show what the cycle has produced when it finally runs out of judges altogether.</p>`,

  groups: [
    { label: 'Introduction (Ch. 1–2)', subtitle: 'The unfinished conquest. The editors lay out the pattern the whole book will follow.', chapters: [1, 2] },
    { label: 'The Cycle of Judges (Ch. 3–16)', subtitle: 'Six major deliverers and six minor ones. Each cycle darker than the last.', chapters: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] },
    { label: 'Appendices (Ch. 17–21)', subtitle: 'What happens when the cycle runs out. The migration of Dan. The Levite\'s concubine.', chapters: [17, 18, 19, 20, 21] },
  ],

  chapterLabel: n => 'Judges ' + n,

  themes: [
    {
      slug: 'cycle-and-decline',
      title: 'The Cycle and the Decline',
      greek: 'sin, oppression, cry, deliverance — then again',
      preview: 'The opening chapters of Judges set out the pattern explicitly. What the book then shows is that the pattern does not stay flat — each iteration is darker than the last, until the cycle collapses entirely in the closing appendices.',
      essay: [
        `The opening chapters of Judges set out the pattern that the rest of the book will follow. Chapter 2 is essentially a thesis statement from the editors. Whenever the Lord raised up judges for them, the Lord was with the judge and saved them from the hand of their enemies all the days of the judge; for the Lord was moved to pity by their groaning under those who persecuted and oppressed them. But whenever the judge died, they would relapse and behave worse than their ancestors, following other gods, worshipping them, and bowing down to them. They did not refrain from any of their corrupt practices or from their stubborn ways.`,
        `The pattern is mechanical. Sin, oppression, cry, deliverance, peace, sin again. It is the pattern of a loose tribal society in which religious authority has not yet been institutionalized and central political authority does not exist. There is no temple yet — the ark moves between Shiloh and Bethel and other places. There is no king. Each tribe handles its own affairs, and in moments of large external threat a charismatic leader emerges — sometimes from an unlikely tribe or unlikely social position — who rallies several tribes for a particular crisis and then returns to obscurity or dies.`,
        `The brilliance of the book is that the editors, while imposing this cyclical frame on the material, do not make the cycle flat. Each iteration is darker than the last. Othniel, the first judge, is presented as a paradigm — capable, faithful, married into the great family of Caleb. Ehud is already morally edgier — he kills a foreign king with a concealed dagger by deceit. Deborah is the high point of the book, and her song is its theological climax. Gideon starts hesitantly but ends well, then names a son Abimelech who immediately becomes the first claimant of monarchy and slaughters his own brothers to seize it. Jephthah delivers the people but loses his daughter in the process. Samson is a one-man wrecking crew whose faithfulness to his Nazirite vow is broken on every page.`,
        `By the end of the book the cycle has degenerated into a national crisis with no judge at all — a Levite's concubine raped to death, a tribal civil war, six hundred captured women, and the editors' verdict in the closing line. What the structure is showing is the gradual exhaustion of charismatic leadership as a model for ordering a covenant people. The system works for emergencies; it does not produce the kind of stable moral and religious life Deuteronomy was asking for. Each judge is a stopgap. Between the stopgaps, the people drift. By the end the drift has become a fall, and the book is pointing — without saying so explicitly — toward the question that the books of Samuel will then take up: should there be a king?`,
      ],
      where: [
        { n: 2, label: 'Judges 2 (the editors\' thesis)' },
        { n: 9, label: 'Judges 9 (Abimelech, the first king-claimant)' },
        { n: 16, label: 'Judges 16 (Samson\'s fall)' },
        { n: 21, label: 'Judges 21 (the closing horror)' },
      ],
    },
    {
      slug: 'deborah-and-the-song',
      title: 'Deborah and the Song',
      greek: 'the same story told twice — once in prose, once in poetry',
      preview: 'Chapters 4 and 5 tell the same battle twice: once in administrative prose and once in the Song of Deborah, possibly the oldest surviving Hebrew poem. The two versions sit side by side and refuse to harmonize.',
      essay: [
        `Chapters 4 and 5 of Judges tell the same story twice, once in prose and once in poetry. The poetic version, the Song of Deborah in chapter 5, is widely considered one of the oldest pieces of Hebrew poetry surviving anywhere — possibly going back to the twelfth century BCE, almost contemporaneous with the events it describes. To read the prose first and then the poetry is to watch a battle being remembered in two registers, one administrative and one bardic.`,
        `Deborah is a prophet, the wife of Lappidoth, who sits under the palm tree between Ramah and Bethel in the hill country of Ephraim. The Israelites come up to her for judgment. She summons Barak son of Abinoam from Kedesh in Naphtali and tells him: gather ten thousand from Naphtali and Zebulun, take them to Mount Tabor, and the Lord will draw out Sisera the general of Jabin's army, with his nine hundred chariots of iron, to the river Kishon, and give him into your hand. Barak says: if you go with me, I will go; if you do not go with me, I will not go. Deborah says: I will surely go with you, but the road on which you are going will not lead to your glory, for the Lord will sell Sisera into the hand of a woman.`,
        `The battle is brief in the prose account. The Israelites come down from the mountain, the Lord throws Sisera and his chariots into a panic, the Kishon overflows and the iron chariots are mired in the mud. Sisera flees on foot. He comes to the tent of Jael, wife of Heber the Kenite. She offers him hospitality, gives him milk, covers him with a rug while he sleeps from exhaustion, takes a tent peg in one hand and a hammer in the other, drives the peg through his temple into the ground. Then the song. Awake, awake, Deborah, awake, awake, utter a song.`,
        `The poem is fierce, archaic, full of difficult Hebrew that translators have argued about for two thousand years. It curses Meroz, the village that did not come to the battle. It blesses Jael among women. It tells Sisera's death again — between her feet he sank, he fell, he lay still; between her feet he sank, he fell — with a brutal repetition the prose did not have. And then, in one of the most arresting moves in any poem, it cuts to Sisera's mother, watching from her window, asking why his chariot is so long in coming, and being told by her wisest ladies that they must be dividing the spoil — a girl or two for every man, dyed embroidered cloth for the necks of the spoilers. The mother who waits for a son who is not coming home is the mother on every side of every war. Deborah is the only judge whose victory is told twice, in two different literary modes, and the song is in many ways the moral and aesthetic high point of the book.`,
      ],
      where: [
        { n: 4, label: 'Judges 4 (the prose account)' },
        { n: 5, label: 'Judges 5 (the Song of Deborah)' },
      ],
    },
    {
      slug: 'gideon-and-the-fleece',
      title: 'Gideon and the Fleece',
      greek: 'the reluctant warrior, the three hundred, the ephod that becomes a snare',
      preview: 'Gideon is the most fully developed judge in the book: a man who argues with God at the threshing floor, defeats Midian with torches and trumpets, refuses kingship in a famous speech, and then does everything a king would do anyway.',
      essay: [
        `Chapters 6 to 8 tell the long story of Gideon, the most fully developed judge in the book. The Midianites have been sweeping into the land at harvest time for seven years, taking the crops and leaving the people destitute. Gideon, of the tribe of Manasseh, is threshing wheat in a winepress to hide it from them when the angel of the Lord appears under the oak at Ophrah. The Lord is with you, mighty warrior, the angel says. Gideon's reply is sharp: if the Lord is with us, why has all this happened to us, and where are all his wonderful deeds that our ancestors recounted to us? The text does not soften the bitterness. Gideon is being addressed in language that does not match his situation, and he says so.`,
        `The call proceeds through several signs. Gideon tears down his father's altar to Baal in the night and builds an altar to the Lord on the same spot — the men of the town want to kill him for it, but his father Joash defends him with a famous line: if Baal is a god, let him contend for himself. Then the famous fleece. Gideon asks God twice for confirmation — first the fleece wet with dew when the ground is dry, then dry when the ground is wet. The signs are given. Gideon believes. He gathers thirty-two thousand men. The Lord tells him this is too many — the people might claim the victory was their own — and the army is whittled down to three hundred by an obscure test involving how the men drink at a stream.`,
        `The three hundred surround the Midianite camp at night, each carrying a torch hidden in a clay jar in one hand and a trumpet in the other. At a signal they smash the jars, blow the trumpets, and shout: a sword for the Lord and for Gideon. The Midianites panic and turn on one another in the dark. The land has rest for forty years. Gideon then refuses kingship in a famous line — I will not rule over you, neither will my son rule over you, the Lord will rule over you — but he asks each of his men to give him an earring from the spoil, and from the gold he makes an ephod which the people end up worshipping, and which the text plainly calls a snare for Gideon and his family.`,
        `He has seventy sons by his many wives, plus a son named Abimelech by a concubine in Shechem. Within a generation that son will hire a band of mercenaries, return to his father's town, and slaughter his seventy half-brothers on a single stone — all but Jotham, the youngest, who escapes and delivers a blistering parable from the top of Mount Gerizim. The book's pattern of decline runs directly through Gideon's own story: deliverance, ambivalence, compromise, and a son who becomes the first aspirant to monarchy in Israel.`,
      ],
      where: [
        { n: 6, label: 'Judges 6 (the call; the fleece)' },
        { n: 7, label: 'Judges 7 (the three hundred)' },
        { n: 8, label: 'Judges 8 (the ephod; the refusal of kingship)' },
        { n: 9, label: 'Judges 9 (Abimelech)' },
      ],
    },
    {
      slug: 'jephthah-and-the-vow',
      title: 'Jephthah and the Vow',
      greek: 'a rash sentence and a daughter who answers it with grace',
      preview: 'Jephthah is an outcast who bargains his way to command and defeats the Ammonites. On the way he makes a vow. When he returns home victorious, his only child — his daughter — comes out the door to greet him.',
      essay: [
        `Jephthah is a Gileadite, the son of a prostitute, driven out of his father's house by his half-brothers because of his irregular birth. He flees to the land of Tob and gathers around himself a band of outlaws. When the Ammonites threaten Gilead, the elders who had driven him out come and beg him to come back as their commander. He bargains. If you bring me back, and the Lord gives the Ammonites into my hand, I will be your head. They agree. He sends a messenger to the Ammonites with a long historical defence of Israel's claim to the land, and when the Ammonite king refuses, he prepares for battle.`,
        `Then the vow. The spirit of the Lord came upon Jephthah, and he made a vow to the Lord: if you will give the Ammonites into my hand, then whoever comes out of the doors of my house to meet me, when I return victorious, shall be the Lord's, and I will offer him up as a burnt offering. The Hebrew is ambiguous on whether he expected a person or an animal — houses in this period sometimes kept animals on the ground floor — but the result is unambiguous. He defeats the Ammonites with great slaughter. He returns home in victory. His daughter, his only child, comes out of the door of his house with timbrels and dancing.`,
        `Jephthah tears his clothes. Alas, my daughter, you have brought me very low. I have opened my mouth to the Lord and I cannot take back my vow. The daughter — never named in the text, though tradition gives her names — answers with a gravity that is harder to read than her father's grief. My father, if you have opened your mouth to the Lord, do to me according to what has gone out of your mouth. Grant me this one request: let me alone two months, that I may go and wander on the mountains and bewail my virginity, I and my companions. He grants it. She goes. After two months she returns, and the text says simply: he did with her according to the vow he had made.`,
        `The text does not editorialize. It does not say the vow was foolish; it does not say God required the sacrifice; it does not say the law forbidding human sacrifice — which the Pentateuch states clearly more than once — should have stopped him. The chapter ends with the note that it became a custom in Israel for the daughters of Israel to go year by year to lament the daughter of Jephthah for four days. She is mourned by the women of the people, ritually, every year, even though her own father is the one who sacrificed her. The judge who delivered Israel from the Ammonites destroyed his own household to do it, and the price is paid by his daughter.`,
      ],
      where: [
        { n: 10, label: 'Judges 10 (the Ammonite threat)' },
        { n: 11, label: 'Judges 11 (the vow and the daughter)' },
        { n: 12, label: 'Judges 12 (the shibboleth; Jephthah\'s death)' },
      ],
    },
    {
      slug: 'samson-and-decline',
      title: 'Samson and the Long Decline',
      greek: 'a Nazirite from the womb who breaks every part of his vow',
      preview: 'Samson is the most gifted of the judges and the most morally compromised. He is dedicated from birth, breaks his vow on every page, and delivers Israel only through his own death. The book\'s arc of decline reaches its lowest point in his personal story.',
      essay: [
        `Samson takes up four chapters — 13 to 16 — and is the longest single narrative arc in the book. He is born to a barren woman of the tribe of Dan after an annunciation by the angel of the Lord, who tells her that her son is to be a Nazirite from the womb: no razor on his head, no wine, no contact with the dead. He grows up, the spirit of the Lord begins to stir him, and from there the trouble begins. He falls in love with a Philistine woman at Timnah. He kills a lion with his bare hands on the way to the wedding feast and later finds bees nesting in the carcass — the source of the riddle he poses to his wedding guests, who get the answer out of his bride by threatening her family. He kills thirty Philistines to pay off the wager. His wife is given to another.`,
        `He sets fire to the Philistine grain fields with three hundred foxes and burning torches. He is captured and bound by his own people, who hand him over to the Philistines, and he breaks the ropes and kills a thousand Philistines with the jawbone of an ass. He goes to a prostitute in Gaza and tears the city gates off their hinges in the morning. Then he loves Delilah in the valley of Sorek. The Philistine lords offer her eleven hundred pieces of silver each to find out the secret of his strength. Three times she asks him; three times he lies; three times the Philistines spring on him and find his strength intact. The fourth time she presses him until his soul is vexed to death and he tells her: it is the unshorn hair of his Nazirite vow.`,
        `She lulls him to sleep on her knees. They shave him. The strength leaves him. The Philistines seize him, gouge out his eyes, take him down to Gaza, bind him with bronze fetters, and put him to grinding at the mill in the prison. The end is one of the most theatrical scenes in the book. The Philistine lords gather in the temple of Dagon to celebrate. They send for Samson to entertain them. His hair has begun to grow back. He prays — the only sustained prayer Samson ever utters — Lord God, remember me and strengthen me only this once, that with this one act of revenge I may pay back the Philistines for my two eyes. He pushes against the pillars. The temple falls on the lords and on Samson. So the dead whom he killed at his death were more than those he had killed during his life.`,
        `The whole arc is read by the editors as a national figure. Samson is dedicated from the womb, has every advantage, breaks every part of his vow, accomplishes deliverance only through suicide, and ends in a heap of rubble. The judge who was supposed to be set apart from birth becomes a parable of how Israel itself is squandering its calling, and the book's pattern of decline reaches its lowest point in the personal story of the most gifted of the judges.`,
      ],
      where: [
        { n: 13, label: 'Judges 13 (the annunciation)' },
        { n: 14, label: 'Judges 14 (the lion; the riddle)' },
        { n: 15, label: 'Judges 15 (the foxes; the jawbone)' },
        { n: 16, label: 'Judges 16 (Delilah; the temple)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Deborah', role: 'Judge and prophet', body: `The only female judge in the book, and the only one described as both prophet and judge in the strict sense — she sits under the palm tree between Ramah and Bethel and the Israelites come up to her for judgment. She summons Barak, accompanies him to battle when he refuses to go without her, and afterward composes the Song of chapter 5, one of the oldest surviving Hebrew poems. The land has rest for forty years after her victory. She is never undercut by the editors.` },
    { name: 'Gideon', role: 'Judge of Manasseh', body: `Of the tribe of Manasseh, the youngest in his father's house, found threshing wheat in a winepress when the angel finds him. He breaks down his father's altar to Baal, tests God twice with the fleece, and leads three hundred men with torches and trumpets against the camp of Midian. He refuses kingship in a famous speech but makes an ephod that becomes a snare, and his son Abimelech seizes a brief and bloody kingship within a generation of his death. The most ambivalent of the major judges.` },
    { name: 'Jephthah', role: 'Outcast judge of Gilead', body: `A Gileadite, son of a prostitute, driven out by his half-brothers, leader of a band of outlaws in the land of Tob. The elders of Gilead beg him to lead against the Ammonites. He bargains, accepts, defeats them. He is also the man who made the vow that costs him his only child. He gives the longest diplomatic speech of any judge — a sustained historical and theological argument about the land — and then destroys his own household with a single rash sentence. He judges Israel six years and dies.` },
    { name: 'Samson', role: 'Nazirite judge of Dan', body: `Of the tribe of Dan, dedicated as a Nazirite from the womb. Endowed with extraordinary physical strength by the spirit of the Lord. Spends his adult life entangled with Philistine women and producing private vendettas against the Philistines that the text frames as deliverance of Israel. Betrayed by Delilah, blinded, imprisoned. His hair grows back. He pulls down the temple of Dagon on his own head and on three thousand Philistines. The most gifted of the judges and the most morally compromised.` },
    { name: 'Jael', role: 'Tent-peg killer', body: `Wife of Heber the Kenite, the woman in whose tent Sisera takes refuge after the rout at the Kishon. She offers him hospitality, gives him milk in a lordly bowl, covers him with a rug, and when he is asleep drives a tent peg through his temple into the ground. The Song of Deborah blesses her among women — the most blessed of all. She fulfils Deborah's prophecy that the Lord will sell Sisera into the hand of a woman. The text is not ambivalent about her; only later tradition has been.` },
    { name: "The Levite's Concubine", role: 'Unnamed victim', body: `Unnamed, in the closing horror of the book. A Levite's concubine who is pushed out of a house in Gibeah when the men of the town demand the Levite. They rape her through the night. She crawls back to the threshold at dawn and dies there. The Levite cuts her body into twelve pieces and sends one to each tribe. The civil war that follows nearly destroys the tribe of Benjamin. She is one of the most damning witnesses in the Hebrew Bible against the kind of society Judges shows Israel becoming when everyone does what is right in his own eyes.` },
  ],

  castSubtitle: 'The deliverers, the killers, and the victims of a book without a king.',
  castLead: `<p>Judges has twelve named judges — six major figures with extended narratives and six minor ones who get only a verse or two. The book also carries a number of supporting and secondary figures whose stories are among the most memorable passages in the Hebrew Bible. The cast is grouped here by their role in the book's arc.</p>`,

  castGroups: [
    {
      label: 'The major judges',
      characters: [
        { id: 'deborah', tag: 'PROPHET', name: 'Deborah', epithet: 'Judge and prophet', body: `The only female judge in the book, and the only one described as both prophet and judge in the strict sense. She sits under the palm tree of Deborah between Ramah and Bethel in the hill country of Ephraim, and the Israelites come up to her for judgment. She summons Barak to attack Sisera, accompanies him to the battle when he refuses to go without her, and afterward composes the Song of chapter 5 — one of the oldest surviving Hebrew poems, possibly dating to the twelfth century BCE. Deborah is the high point of the book: a leader whose authority is religious, judicial, and military all at once, and the only judge whose victory is told twice, in both prose and poetry. The land has rest for forty years after her victory.`, appears: [4, 5] },
        { id: 'gideon', tag: 'JUDGE', name: 'Gideon', epithet: 'Reluctant warrior of Manasseh', body: `Of the tribe of Manasseh, the youngest in his father's house, found threshing wheat in a winepress to hide it from the Midianites when the angel of the Lord finds him. He breaks down his father's altar to Baal in the night, tests God twice with the fleece, and leads three hundred men with torches and clay jars against the camp of Midian at night — smashing the jars, blowing the trumpets, and routing an entire army. He refuses kingship in a famous speech but makes an ephod from the gold earrings of the spoil that the people end up worshipping, and his concubine's son Abimelech seizes a brutal brief kingship within a generation. The most ambivalent of the major judges.`, appears: [6, 7, 8, 9] },
        { id: 'jephthah', tag: 'JUDGE', name: 'Jephthah', epithet: 'Outcast judge of Gilead', body: `A Gileadite, son of a prostitute, driven out by his half-brothers, who led a band of outlaws in the land of Tob before the elders of Gilead came and begged him to lead against the Ammonites. He bargains, accepts, and defeats them with great slaughter. He is also the man who made the vow that cost him his only child: whoever came out of his door to greet him on his return, he would offer as a burnt offering. His daughter came. He honoured the vow. He then killed forty-two thousand Ephraimites at the fords of the Jordan by means of the shibboleth password. He judged Israel six years and died.`, appears: [10, 11, 12] },
        { id: 'samson', tag: 'NAZIRITE', name: 'Samson', epithet: 'Strongman of Dan', body: `Of the tribe of Dan, dedicated as a Nazirite from the womb after an annunciation to his barren mother — no razor, no wine, no contact with the dead. Endowed with extraordinary strength by the spirit of the Lord. He killed a lion with his bare hands, killed a thousand Philistines with the jawbone of an ass, and tore the gates of Gaza off their hinges in the morning. Betrayed by Delilah, who learned the secret of his Nazirite hair and shaved him in his sleep; captured, blinded, and set to grinding grain in a Gaza prison. His hair grew back. He prayed once, with genuine urgency, and pulled down the temple of Dagon on his own head and on three thousand Philistines. The most gifted judge and the most morally compromised.`, appears: [13, 14, 15, 16] },
      ],
    },
    {
      label: 'Supporting figures',
      characters: [
        { id: 'jael', tag: 'KILLER', name: 'Jael', epithet: 'Wife of Heber the Kenite', body: `The woman in whose tent Sisera, the defeated general, took refuge after the rout at the Kishon river. She offered him hospitality, gave him milk in a lordly bowl, covered him with a rug, and when he fell asleep from exhaustion took a tent peg in one hand and a hammer in the other and drove the peg through his temple into the ground. The Song of Deborah blesses her above all women in the tents, and names her act of killing in brutal poetic repetition: between her feet he sank, he fell, he lay still; between her feet he sank, he fell. She is not ambiguous in the text. Only later interpretation has made her so.`, appears: [4, 5] },
        { id: 'barak', tag: 'COMMANDER', name: 'Barak', epithet: 'Deborah\'s general', body: `Son of Abinoam from Kedesh in Naphtali, the military commander whom Deborah summons to lead ten thousand men against Sisera. He agrees to go only if Deborah goes with him, which she accepts, but tells him the glory of the battle will therefore go to a woman. He leads the attack from Mount Tabor, routes Sisera's nine hundred iron chariots when the Kishon floods and the plain becomes mud, and pursues the fleeing army. He arrives at Jael's tent to find Sisera already dead. He is present in the Song of Deborah as a named partner of the victory, though Deborah and Jael take the poetic foreground.`, appears: [4, 5] },
        { id: 'abimelech', tag: 'TYRANT', name: 'Abimelech', epithet: 'Son of Gideon; would-be king', body: `Son of Gideon by a concubine in Shechem, whose name means "my father is king" — the name itself is the ambition. He hired seventy pieces of silver's worth of worthless fellows, returned to Shechem, and killed his seventy half-brothers on a single stone. He ruled as king over Israel for three years until a woman dropped a millstone on his head from a city wall at Thebez and he had his armour-bearer finish him off so no one could say a woman had killed him. His brief and bloody career is the book's first and bitterest meditation on what kingship without covenant would look like.`, appears: [9] },
        { id: 'delilah', tag: 'BETRAYER', name: 'Delilah', epithet: 'Samson\'s betrayer', body: `A woman from the valley of Sorek whom Samson loved. The Philistine lords offered her eleven hundred pieces of silver each to discover the secret of his strength. She asked him three times; he lied three times. The fourth time she pressed him until his soul was vexed to death — her persistence is rendered with a verbal precision that implies something more than bribery — and he told her about the Nazirite hair. She called a man to shave him while he slept on her knees. He woke to find the Lord had left him. The text gives no verdict on her that it does not give on Samson's own taste for Philistine women throughout his story; the betrayal is framed as the culmination of a pattern, not a surprise.`, appears: [16] },
      ],
    },
    {
      label: 'Figures in the appendices',
      characters: [
        { id: 'levite-concubine', tag: 'VICTIM', name: "The Levite's Concubine", epithet: 'Unnamed victim of Gibeah', body: `Unnamed, in the closing horror of the book. A Levite from the hill country of Ephraim takes her as a concubine. She leaves him and returns to her father's house in Bethlehem. He follows, brings her back, and on the return journey they stop for the night in the Benjaminite town of Gibeah. The men of the town surround the house and demand the Levite. He pushes the concubine out instead. They rape her through the night. She crawls back to the threshold at dawn and dies there. The Levite cuts her body into twelve pieces and sends one to each tribe of Israel. The civil war that follows nearly destroys the tribe of Benjamin. The book records every detail without softening, and she stands as one of the most damning witnesses in the Hebrew Bible against the society Judges shows Israel becoming when there is no king.`, appears: [19, 20, 21] },
        { id: 'micah-ephraim', tag: 'IDOLATER', name: 'Micah of Ephraim', epithet: 'The shrine-builder', body: `A man from the hill country of Ephraim who stole eleven hundred pieces of silver from his mother, confessed, gave it back, and from the returned silver had his mother make a carved image and a metal image for a household shrine. He installed one of his sons as priest, then hired a wandering Levite from Bethlehem to serve as his priest for ten pieces of silver and a suit of clothes a year. The men of Dan, looking for territory, came to his house and took the images and the Levite by force on their migration north. Micah ran after them and protested; they told him to be quiet or brave men would come upon him. He gave up and went home. His story opens the book's two appendices and shows the religious disorder that the absence of central authority has produced: private shrines, hired priests, and idols made from stolen silver.`, appears: [17, 18] },
      ],
    },
  ],

  chapters: require('/tmp/bible-judges-chunk-1.json'),
};
