// SEO content data for Selma Lagerlöf's Jerusalem (1901–1902).
// Nobel Prize novel — Swedish Dalecarlian farming families swept into a religious movement
// and their mass emigration to Palestine. Two volumes: Jerusalem in Dalarna + Jerusalem in the Holy Land.
// Voice: spare, quietly grave, rooted in soil and faith; the weight of community, land, and conscience.

module.exports = {
  id: 'jerusalem',
  title: 'Jerusalem',
  author: 'Selma Lagerlöf',
  byline: '1901–02 · Nobel Prize novel in three books',
  titleAccent: 'a guided tour',
  hook: 'A Swedish farming dynasty has held its land for generations by asking one question in every crisis: what would father have done? Then an American preacher arrives in Dalarna — and the question stops working.',
  genre: ['Novel', 'Swedish literature', 'Historical fiction'],
  themesBlurb: 'Land, faith, conscience, emigration, love against community.',
  castBlurb: 'A Dalecarlian valley',
  castDesc: 'A farming community split between staying and going.',
  castSubtitle: 'The household of an ancient farm and the community it holds together.',
  chapterLabel: n => {
    const map = {
      1: 'Book One',
      2: 'At The Schoolmaster\'s',
      3: 'And They Saw Heaven Open',
      4: 'Karin, Daughter Of Ingmar',
      5: 'In Zion',
      6: 'The Wild Hunt',
      7: 'Hellgum',
      8: 'The New Way',
      9: 'Loss Of L\'Univers',
      10: 'Unity, Unity',
      11: 'Hellgum\'s Letter',
      12: 'The Big Log',
      13: 'The Ingmar Farm',
      14: 'Hoek Matts Ericsson',
      15: 'The Auction',
      16: 'Gertrude',
      17: 'The Dean\'s Widow',
      18: 'The Departure Of The Pilgrims',
    };
    return map[n] || `Chapter ${n}`;
  },

  about: [
    `<em>Jerusalem</em> is the book that won Selma Lagerlöf the Nobel Prize in 1909 — the first woman and the first Swede to receive it. It is rooted in fact: in the 1890s, a Swedish-American preacher named Hellgum arrived in the Dalecarlian parish of Nås and persuaded a community of deeply conservative Lutheran farmers to sell their land and emigrate to Ottoman-controlled Jerusalem to join an American Christian colony there. Lagerlöf spent years gathering testimony from those who went and those who remained. The novel follows the Ingmarsson family through this rupture.`,
    `The book has three parts. The first is a dense portrait of the Ingmarsson dynasty — generations of farmers whose authority in the valley derived from one simple practice: they asked, in every difficulty, what the fathers before them would have done. The second and third follow what happens when a new religious certainty arrives and breaks that ancient habit in two. Half the community sells everything and leaves. The other half watches the valley change shape around a set of empty farms. Lagerlöf tells both halves without sentimentality, and she never decides who was right.`,
  ],

  chaptersSubtitle: 'All 18 chapters across three books — from a plowman\'s morning in Dalarna to the pilgrim wagons leaving in July.',
  chaptersLead: `<p>Jerusalem is divided into three books of unequal length. Book One (Chapter 1) is a long, sweeping portrait of the Ingmarsson family across four generations, ending with young Ingmar\'s marriage to Brita. Book Two (Chapters 2–8) follows the arrival of the Hellgum movement into the parish and its grip on Karin and the community. Book Three (Chapters 9–18) follows the consequences: an Atlantic shipwreck, the approach of departure day, and the slow dissolution of what held the valley together.</p>`,

  themesByline: 'Five threads through the novel',
  themesLead: `Jerusalem is a novel about what happens to a community when the thing that held it together — land, custom, family memory — is challenged by a certainty it cannot answer. Lagerlöf refuses to adjudicate. She only shows the cost.`,

  groups: [
    { label: 'Book One · The dynasty', subtitle: 'Four generations of Ingmarssons on one farm in Dalarna.', chapters: [1] },
    { label: 'Book Two · The movement', subtitle: 'Hellgum arrives. The parish divides. Karin goes first.', chapters: [2, 3, 4, 5, 6, 7, 8] },
    { label: 'Book Three · The departure', subtitle: 'From a shipwreck on the Atlantic to the wagons leaving in July.', chapters: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18] },
  ],

  themes: [
    {
      slug: 'land',
      title: 'The land and what it means to leave it',
      greek: 'the farm as inheritance and as burden',
      preview: 'The Ingmar Farm has been in the same family for generations. Lagerlöf opens the novel with a young farmer plowing on a summer morning and asking himself whether he is as good a man as his father. The farm is not property; it is a test.',
      essay: [
        `The Ingmar Farm is the first character in the novel. Lagerlöf introduces it the way another novelist might introduce a protagonist: with close attention to its physical particulars, its gray outhouses and spreading pear trees, its haystacks behind the barn, the way it rises above the low fields "as pretty a sight as a ship with masts and sails towering above the broad surface of the sea." The man plowing the field beside it is young Ingmar Ingmarsson, and he is not thinking about the farm as property. He is thinking about whether he is good enough for it.`,
        `The Ingmarsson family has worked the same land for so long that the community has come to look to them for guidance the way it looks to the church. When Big Ingmar was alive, the neighbors waited to see when he began haymaking before they began their own. When he plowed the fallow field, plows went into the earth "the length and breadth of the valley." The authority was not legal; it was moral. It derived from continuity, from the visible fact that the family had held the same ground across so many generations that their judgment had been tested by time.`,
        `What the novel asks, with great precision, is what happens to that kind of authority when faith demands its surrender. The Hellgumist movement does not ask the Ingmarssons to do something trivial. It asks them to sell the farm. For the community, this is not a transaction; it is the cancellation of everything the Ingmarsson name stood for. Karin's sale of the farm to follow Hellgum is felt by those who remain as something close to a betrayal of the dead. And yet the novel refuses to condemn her. What Lagerlöf shows instead is the sheer cost — to Ingmar, to Gertrude, to the valley — of a decision that Karin herself cannot say was wrong.`,
        `The land question runs through every chapter. Ingmar's slow accumulation of timber to build a new house for himself and Gertrude — one log, then another, then another, across five years — is the image Lagerlöf sets against the pilgrims' departure. The log in Chapter 12 is as specific and particular as the farm in Chapter 1. Lagerlöf is a novelist of things, and the things in Jerusalem are always also arguments about what it means to stay.`,
      ],
      where: [
        { n: 1, label: 'Chapter 1 (the farm, the fathers)' },
        { n: 12, label: 'Chapter 12 (the big log)' },
        { n: 15, label: 'Chapter 15 (the auction)' },
        { n: 18, label: 'Chapter 18 (the departure)' },
      ],
    },
    {
      slug: 'faith',
      title: 'Faith and its costs',
      greek: '"We are no longer on earth, but in the New Jerusalem"',
      preview: 'The Hellgum movement asks everything of its converts: their farms, their savings, their country, their families. Lagerlöf does not judge it. She only watches what it takes.',
      essay: [
        `Hellgum is not a charlatan. Lagerlöf is careful about this. The novel does not explain away the movement by making its leader a fraud or a manipulator. He is a Swedish-American lay preacher who has been genuinely transformed by a religious experience, who genuinely believes that God has called a community of Swedish farmers to rebuild his holy land, and who has the kind of personal force that makes other people believe it too. The converts — Karin, Strong Ingmar, old Eva Gunnersdotter — are not credulous fools. They are people for whom the faith is real.`,
        `What Lagerlöf is interested in is not the question of whether the faith is true, but the question of what a faith that demands this much costs. The Hellgumist movement asks its converts to do something that the novel presents as genuinely extraordinary: to sell the land their families have held for generations, to uproot children and elders, to cross half the world to a country they have never seen, to live in a foreign colony under foreign skies, trusting entirely in a promise. The novel does not say this is wrong. It simply records what is lost.`,
        `The loss is not only material. Old Eva Gunnersdotter, walking to the last Hellgumist meeting in Chapter 11 in her best clothes as if for church, represents what the movement meant at its height: a community of brothers and sisters who came to visit her in her loneliness, who cleared paths to her cabin after snowfall. The faith gave something before it took everything. Lagerlöf holds both facts at once. The move to Jerusalem is absurd and it is also, in its own terms, sincere. This is why the novel does not end with condemnation.`,
        `The parallel between the two promised lands — the Dalecarlian valley that the schoolmaster's wife thinks is lovelier than anywhere you could travel to, and the Holy Land the Hellgumists are leaving to reclaim — runs quietly beneath every chapter of Book Three. The novel's title is finally ironic and finally not ironic. Jerusalem is where they are going. It is also what they have left.`,
      ],
      where: [
        { n: 3, label: 'Chapter 3 (the spring flood and the mission)' },
        { n: 5, label: 'Chapter 5 (In Zion)' },
        { n: 8, label: 'Chapter 8 (The New Way)' },
        { n: 11, label: 'Chapter 11 (Hellgum\'s letter)' },
      ],
    },
    {
      slug: 'conscience',
      title: 'Conscience and the fathers',
      greek: '"What would Big Ingmar have done?"',
      preview: 'The Ingmarsson family has governed its life for generations by a single method: imagining what the fathers would have decided. The novel\'s central question is what happens when the fathers\' answer is no longer sufficient.',
      essay: [
        `The Ingmarssons have an inherited method for moral difficulty. When a hard decision comes — whether to sell a field, whether to marry a particular woman, whether to take a stand in the parish — they ask themselves what their fathers would have done. The practice is not superstition and not mere convention. It is, in Lagerlöf's telling, a genuine epistemological habit: the past as a kind of accumulated wisdom, tested by time, more reliable than any individual judgment.`,
        `Young Ingmar uses the method throughout Book One with complete seriousness. He imagines his father Big Ingmar settled on a farm in heaven, still wearing his gray homespun, still the most respected man in any gathering. He talks to him in his mind, asks his opinion, uses the imagined answer to test his own impulses. The method works, up to a point. It tells him how to manage the farm, how to treat his tenants, when to speak and when to stay silent. What it does not tell him, and what the novel turns on, is what to do when the entire community's inherited certainty is challenged by a new revelation.`,
        `Karin's conversion to Hellgum's movement is the moment when the fathers' method fails. Big Ingmar was a Lutheran farmer who held his land and minded his parish. He has no answer for an American preacher who arrives with a claim that God has called this specific community to a specific mission in a specific country. The fathers never faced this. Their wisdom cannot reach it. And so Karin must decide for herself — must act, for the first time in the family's history, without the anchor of inherited guidance.`,
        `Young Ingmar's tragedy is that he cannot do the same. He cannot join Karin because he cannot find a father's sanction for going. He cannot condemn her because he cannot find a father's sanction for that either. He is left standing in the middle, without the method that has defined his family, unable to construct a new one. The novel treats this not as weakness but as a kind of faithfulness — faithfulness to a mode of life that the world has simply outrun.`,
      ],
      where: [
        { n: 1, label: 'Chapter 1 (the father\'s method)' },
        { n: 6, label: 'Chapter 6 (after Elof\'s ruin)' },
        { n: 8, label: 'Chapter 8 (Ingmar resists)' },
        { n: 13, label: 'Chapter 13 (the Ingmar Farm in winter)' },
      ],
    },
    {
      slug: 'community',
      title: 'Community and its dissolution',
      greek: 'a valley that knows itself; then does not',
      preview: 'The Dalecarlian parish in the early 1880s is the kind of community that knows its own members absolutely — their bloodlines, their reputations, their inherited standings. The Hellgum movement breaks it in two.',
      essay: [
        `Lagerlöf builds her community before she breaks it. Book One and the opening chapters of Book Two are dense with the texture of parish life: the way the church bell rings at Angelus and the men uncover their heads across the valley; the Sunday ritual of fighting the cold to sit in the same pew generation after generation; the web of obligation and precedent that governs who courts whom, who has credit at the shop, who is consulted when the river needs dredging. This is a community that has held the same shape for a very long time.`,
        `What the Hellgum movement does to this community is not simply to take some of its members away. It introduces a division that the community has no prior vocabulary for. Before Hellgum, disagreements in the parish were conducted within a shared set of assumptions: the land was permanent, the church was Lutheran, the families were continuous, the precedents of the past applied. After Hellgum, some members of the community are operating on entirely different premises — that none of this matters, that God has called them to something that overrides all of it. The two sides can no longer quite understand each other.`,
        `The auction in Chapter 15 is the scene in which this division becomes material. The Ingmar Farm is sold. Mother Stina, the schoolmaster's wife, goes to watch and finds herself unable to speak to Karin. Everything that Karin is doing is legal, intelligible, and in its own terms coherent — and yet the community feels it as a wound. Lagerlöf does not dramatize this as personal vindictiveness. She simply shows the schoolmaster's wife picking wildflowers on the way and thinking that the valley is lovelier than anywhere the pilgrims are going.`,
        `By the final chapter, the pilgrims are leaving and the community is doing something remarkable: it is coming out to witness the departure with respect and grief rather than anger. Beggar Lina standing sober at the roadside, her grandchildren washed and combed, is the chapter's pivot. The leaving is acknowledged as something that cost everyone, including those who are staying. The community dissolves into a kind of honor.`,
      ],
      where: [
        { n: 2, label: 'Chapter 2 (the parish before Hellgum)' },
        { n: 15, label: 'Chapter 15 (the auction)' },
        { n: 17, label: 'Chapter 17 (the Dean\'s widow)' },
        { n: 18, label: 'Chapter 18 (the departure)' },
      ],
    },
    {
      slug: 'love',
      title: 'Love that cannot cross the divide',
      greek: 'Ingmar and Gertrude; what a community costs two people',
      preview: 'Young Ingmar loves Gertrude. Gertrude loves Ingmar. The Hellgum movement puts a question between them neither can answer — and then requires them to live with the result.',
      essay: [
        `The love story in Jerusalem is not a plot to be resolved; it is a casualty. Ingmar and Gertrude grow up together in the schoolmaster's household. She is the schoolmaster's daughter, clever and imaginative, inclined to dreams and fancies. He is the Ingmar heir, slow and steady and intensely loyal. She treats him with affectionate condescension for years. He minds her like a slave, as the novel puts it, and never stops. The relationship is unequal and then, gradually, it is not.`,
        `What prevents them is not rivalry or misunderstanding in the ordinary sense. It is the Hellgum movement. Karin, Ingmar's sister, converts and sells the family farm — the farm Ingmar had expected to inherit. To save the farm from strangers, Ingmar must find money quickly, and the only way to find it is to marry a woman with a dowry. He marries Brita, a disgraced woman whom he chooses partly from genuine compassion and partly because she is the only immediate option. Gertrude learns of this second-hand. The grief she feels is not anger at Ingmar but something stranger: a mounting dread of seeing him at all, a fear that grows until she is avoiding every road in the parish where he might appear.`,
        `Chapter 16 is devoted entirely to what Gertrude's grief does to her — not to the narrative of their separation, but to its psychological texture. Lagerlöf follows Gertrude through the daily mechanics of avoiding the person she loves most: the kerchief pulled down over her face on the road, the detours through the ditches and drains, the constant scan of the horizon when weeding the garden. It is a portrait of interior devastation rendered in completely exterior, physical terms.`,
        `The novel does not resolve this. Gertrude joins the pilgrims partly because the valley has become intolerable to her. Ingmar stays because he cannot find a father's reason to go. The love story ends not with reconciliation or tragedy in the conventional sense but with the simple geography of departure: one person on the cart, one person on the road watching. Lagerlöf is too honest to invent a consolation.`,
      ],
      where: [
        { n: 6, label: 'Chapter 6 (Ingmar and Gertrude at the schoolmaster\'s)' },
        { n: 12, label: 'Chapter 12 (the big log, the plan)' },
        { n: 15, label: 'Chapter 15 (the auction, the loss)' },
        { n: 16, label: 'Chapter 16 (Gertrude\'s fear)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Ingmar Ingmarsson', role: 'Heir to the Ingmar Farm', body: `The young farmer who opens the novel plowing his field and asking himself whether he is as good a man as his father. The Ingmarsson method — asking what the fathers would have done — is both his inheritance and his limitation. He cannot follow Karin to Jerusalem because he cannot find a precedent for it, and he cannot condemn her for going. He marries Brita to save the farm, losing Gertrude in the process.` },
    { name: 'Karin Ingmarsson', role: 'Ingmar\'s sister, the first convert', body: `The elder Ingmarsson sibling, who has managed the farm with more practical authority than her brother. Her conversion to Hellgum's movement is the pivot of the entire novel. She sells the Ingmar Farm — a decision the community experiences as a wound — and departs for Jerusalem. Lagerlöf does not condemn her. The novel simply records what the decision costs.` },
    { name: 'Gertrude', role: 'The schoolmaster\'s daughter', body: `Imaginative, proud, quietly courageous. She grows up in the schoolmaster Storm's household alongside Ingmar, treating him with fond condescension until she realizes she loves him — and then losing him to a marriage of necessity. Chapter 16 follows her grief in complete psychological detail. She eventually joins the pilgrims not from faith but from the geography of loss.` },
    { name: 'Hellgum', role: 'The American preacher', body: `A Swedish-American lay preacher who arrives in Dalarna with a religious certainty Lagerlöf treats as genuine, not fraudulent. He persuades an entire community of conservative Lutheran farmers to sell their property and emigrate to Ottoman Jerusalem. He appears mostly offstage, his power registered through his converts rather than through direct portraiture. His letters are read at meetings like scripture.` },
    { name: 'Storm', role: 'The schoolmaster', body: `An old-fashioned self-taught farmer who became the parish schoolmaster and has managed a hundred children single-handed for thirty years. Respected by the pastor, respected by the community, and deeply confident — too confident, Lagerlöf suggests — in his ability to predict what will and will not penetrate his parish. When Hellgum's movement arrives anyway, the novel gives Storm no satisfaction.` },
    { name: 'Tims Halvor', role: 'Karin\'s husband', body: `A prosperous young shopkeeper who had courted Karin before her first marriage to the disastrous Elof Ersson. He marries her, converts to Hellgumism, and eventually buys the Ingmar Farm — the transaction the community cannot forgive — before departing with the pilgrims. His relationship to Karin is tender and practical and never sentimental.` },
  ],

  castLead: `<p>Jerusalem has a relatively small cast centered on two households — the Ingmarsson farm and the schoolmaster's home — and a surrounding community rendered in crowd scenes and representative figures. The novel's mode is closer to chronicle than drama: individuals matter as representatives of positions the community must take.</p>`,

  castGroups: [
    {
      label: 'The Ingmarsson family',
      characters: [
        { id: 'ingmar', tag: 'Stays', name: 'Ingmar Ingmarsson', epithet: 'Heir to the Ingmar Farm', body: `The young farmer who opens the novel plowing his field on a summer morning and asking whether he is worthy of his fathers. His method of moral reasoning — what would the fathers have done? — is both his strength and his paralysis. He cannot join Karin in Jerusalem, cannot condemn her for going, and cannot save Gertrude in the process. He marries Brita to redeem the farm and lives with what that costs.`, appears: [1, 6, 8, 12, 13, 15, 18] },
        { id: 'karin', tag: 'Goes', name: 'Karin Ingmarsson', epithet: 'Ingmar\'s sister; first convert', body: `The elder sibling, more capable than her brother and more willing to act on conviction. Her conversion to Hellgumism and her decision to sell the family farm are the novel's central events. Lagerlöf does not judge her. The novel records the full cost — to Ingmar, to Gertrude, to the valley — without denying that Karin's faith is genuine.`, appears: [1, 4, 7, 8, 15, 18] },
        { id: 'big-ingmar', tag: 'Dead', name: 'Big Ingmar', epithet: 'The patriarch (remembered)', body: `Never appears alive, only in young Ingmar's memory and imagination. The patriarch whose farm and whose method of moral reasoning — asking what the fathers would have chosen — shapes every decision in the novel. Big Ingmar has no answer for Hellgum. His silence is the novel's central vacuum.`, appears: [1] },
      ],
    },
    {
      label: 'The schoolmaster\'s household',
      characters: [
        { id: 'gertrude', tag: 'Goes', name: 'Gertrude', epithet: 'Storm\'s daughter', body: `The schoolmaster's daughter, clever and given to fancies, who grows up alongside Ingmar with fond condescension and then recognizes, too late, that she loves him. Chapter 16 follows the psychology of her grief with extraordinary precision — the daily mechanics of avoiding the person you love on every road in the parish. She leaves for Jerusalem not from faith but from the impossibility of staying.`, appears: [3, 4, 5, 6, 12, 15, 16, 18] },
        { id: 'storm', tag: 'Stays', name: 'Storm', epithet: 'The schoolmaster', body: `A self-taught farmer turned schoolmaster, the most respected educator in the parish for thirty years. Confident to the point of certainty that Hellgum's movement will not take hold in his parish. He is wrong. Lagerlöf gives him no satisfaction from being wrong; she simply records it.`, appears: [2, 3, 4, 5, 6, 8] },
        { id: 'mother-stina', tag: 'Stays', name: 'Mother Stina', epithet: 'Storm\'s wife', body: `The schoolmaster's wife, practical and warm and deeply attached to the valley. Her walk to the Ingmar Farm auction in Chapter 15, stopping to admire every hawthorn in bloom and thinking that nothing could be lovelier than this, is one of the novel's most moving passages. She represents those who stay not from argument but from love of the particular.`, appears: [4, 15] },
      ],
    },
    {
      label: 'The community and the pilgrims',
      characters: [
        { id: 'hellgum', tag: 'Leads', name: 'Hellgum', epithet: 'The American preacher', body: `Present mostly offstage. A Swedish-American lay preacher whose religious certainty is treated as genuine by Lagerlöf rather than as fraud or manipulation. His letters are read at meetings like apostolic writings. The community's conversion to his movement is the novel's central event; his own nature is left deliberately opaque.`, appears: [5, 7, 8, 11] },
        { id: 'tims-halvor', tag: 'Goes', name: 'Tims Halvor', epithet: 'Shopkeeper; Karin\'s husband', body: `A prosperous young man who had courted Karin before her first marriage. He eventually wins her, converts to Hellgumism, buys the Ingmar Farm from Karin, and departs with the pilgrims. His prosperity is what makes the purchase of the farm possible — and what makes it, in the community's eyes, unforgivable.`, appears: [4, 7, 15, 18] },
        { id: 'eva-gunnersdotter', tag: 'Goes', name: 'Old Eva Gunnersdotter', epithet: 'Forest-dwelling convert', body: `An old woman living alone in a log cabin in the forest, forgotten by most of the parish before the Hellgumists came and found her. The movement gave her brothers and sisters who cleared paths to her cabin after snowfall. Chapter 11 follows her walk to the last Hellgumist meeting in her best clothes, remembering what the movement once was. Her faith is entirely serious.`, appears: [11] },
        { id: 'hoek-matts', tag: 'Goes', name: 'Hoek Matts Ericsson', epithet: 'Father of Gabriel', body: `A farmer from the north end of the parish, so deeply rooted in his land that his son Gabriel must constantly redirect his attention from the calf he is pricing or the potato crop he is estimating toward the valley of Sharon they are about to walk through. His attachment to the particular soil of Dalarna survives his conversion right up to the morning of departure.`, appears: [14, 18] },
      ],
    },
  ],

  chapters: [
    {
      n: 1,
      title: 'Book One — The Ingmarssons',
      tourTitle: 'The dynasty',
      hook: 'A young farmer is plowing on a summer morning and asking whether he is as good a man as his father. He is not the first Ingmar Ingmarsson to ask this question. He will not be the last.',
      tour: `Book One is the novel's foundation: a long, close portrait of the Ingmarsson family across four generations in a Dalecarlian valley. Lagerlöf begins with young Ingmar plowing his field and asking whether he lives up to the fathers — then moves back through the generations, showing what the name has meant and what the method of asking has cost each one who held it. The book ends with young Ingmar choosing to marry Brita, a woman the parish despises, because he believes it is what his father would have done. The whole community of fathers — imagined, dead, watching — endorses it. The valley endorses it. The book closes on that act of faithfulness and sets the table for what Hellgum will disrupt.`,
      blurb: `Four generations of Ingmarssons on one Dalecarlian farm. Young Ingmar inherits the farm and the family method: when a hard decision comes, ask what the fathers would have done. The book ends with his choice to marry Brita — and a vision of the dead fathers approving.`,
      summary: [
        `Lagerlöf opens on a summer morning in Dalarna. Young Ingmar Ingmarsson is plowing his field, thinking about whether he is worthy of his fathers. The farm below him — gray outhouses, spreading pear trees, great haystacks — is the Ingmar Farm, held by the same family for generations. When Big Ingmar was alive, the neighbors followed his lead in everything. Young Ingmar has not yet found a way to fill that authority, and he knows it.`,
        `The rest of Book One moves through the family's history, tracing the practice that has sustained it: the method of asking, in every difficulty, what the fathers before them would have decided. Lagerlöf shows this method working across generations — in decisions about the farm, about marriages, about the parish. It is not superstition; it is a form of moral continuity, tested by time. Young Ingmar uses it consciously, imagining his dead father on a heavenly farm and carrying the conversation.`,
        `The book ends with young Ingmar's marriage to Brita — a disgraced woman the parish has rejected. He chooses her not from passion alone but from a conviction, arrived at through the family method, that it is what his father would have done. At the close, Lagerlöf gives him a vision of the assembled Ingmar fathers endorsing the choice. The valley is at peace. Then Book Two begins, and Hellgum arrives.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }, { id: 'karin', name: 'Karin Ingmarsson' }, { id: 'big-ingmar', name: 'Big Ingmar' }],
      themes: [{ slug: 'land', label: 'Land' }, { slug: 'conscience', label: 'Conscience' }],
    },
    {
      n: 2,
      title: 'Book Two — At The Schoolmaster\'s',
      tourTitle: 'Before Hellgum',
      hook: 'The parish in the early 1880s: conservative, Lutheran, self-contained. Lay preachers pass it by because, as they say, "those people don\'t want to be awakened."',
      tour: `The scene shifts to the schoolmaster Storm's household and the parish around it. Lagerlöf builds the world that Hellgum will enter: a community where people go to church on the coldest Sundays as a matter of course, where the schoolmaster and the pastor have been the same two men for decades, where there is no appetite for religious novelty. Storm is confident — too confident — that this stability is impregnable. Lagerlöf is quiet about the irony. She simply shows the community as it was before, so the reader understands what is at stake when the movement arrives.`,
      blurb: `The schoolmaster Storm's household and the Dalecarlian parish before any religious movement reaches it. Conservative, Lutheran, resistant to novelty. Storm is certain it will stay that way.`,
      summary: [
        `Lagerlöf introduces the schoolmaster Storm and his household in the early 1880s. Storm has taught in the same parish for thirty years, a self-taught farmer who manages a hundred children single-handed and is respected by pastor and peasant alike. The parish itself is conservative: regular churchgoing in any weather, no appetite for lay preachers or revival meetings, no enthusiasm for being "awakened."`,
        `Lay preachers have long since learned to bypass this parish. "Those people don't want to be awakened," they say. Not only preachers but the "awakened souls" of neighboring parishes regard the Ingmarssons and their neighbors as sinners of the worst kind — not sinners who know themselves as such, but sinners who don't see what they're missing. Storm and the pastor stroll together on Sunday afternoons and find this completely satisfactory.`,
        `The chapter is a careful act of preparation. Lagerlöf builds the community in enough detail — the bells, the winter church processions, the mutual respect of schoolmaster and pastor — that the reader understands what the Hellgum movement will have to displace to take hold here. Storm's certainty that it cannot happens to be the last moment of that certainty he will enjoy.`,
      ],
      appears: [{ id: 'storm', name: 'Storm' }, { id: 'mother-stina', name: 'Mother Stina' }],
      themes: [{ slug: 'community', label: 'Community' }, { slug: 'faith', label: 'Faith' }],
    },
    {
      n: 3,
      title: 'Book Two — And They Saw Heaven Open',
      tourTitle: 'The spring flood',
      hook: 'A great thaw floods the Dal River. Among the objects drifting past are washing piers, bathhouses, and boats. The children watch. Then something stranger happens at the mission house.',
      tour: `A spring flood in Dalarna — the Dal River rising alarmingly, carrying with it washing piers, bridges, timber. Lagerlöf uses the flood as an atmospheric frame for the chapter's central event: a vision or visitation that occurs at the schoolmaster's new mission house, which becomes the talk of the parish. The chapter introduces the possibility that something beyond ordinary Lutheran churchgoing is beginning to move through the community. It is not yet Hellgum; it is a preparation of the soil.`,
      blurb: `The Dal River floods in spring. The mission house is newly built. Something extraordinary happens there that the parish cannot quite explain — and that Lagerlöf does not quite explain either.`,
      summary: [
        `Spring brings a great thaw and the Dal River rises to an alarming height. Water comes from everywhere: rain, snowmelt, tributaries. The children run to the banks to watch the river carry past washing piers, bathhouses, boats, the wreckage of bridges. The grown folk are slower to pay attention, and then they cannot look away.`,
        `The flood serves as a frame for the chapter's real event: a gathering at the schoolmaster's new mission house, where something visionary occurs. Lagerlöf renders it with characteristic restraint — she does not establish exactly what is seen or heard, only that the parish is afterwards unable to account for it in ordinary terms. It is not a conversion scene; it is a loosening of the certainty that nothing unusual will happen here.`,
        `The chapter's effect is subtle. Nothing has changed on the surface — Storm is still Storm, the pastor is still the pastor. But the flood has shown that the river can carry things no one expected, and the mission house has shown that the same may be true of the community. Book Two has begun to move.`,
      ],
      appears: [{ id: 'storm', name: 'Storm' }, { id: 'gertrude', name: 'Gertrude' }],
      themes: [{ slug: 'faith', label: 'Faith' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 4,
      title: 'Book Two — Karin, Daughter Of Ingmar',
      tourTitle: 'Karin appears',
      hook: 'A visitor arrives at the schoolmaster\'s kitchen table: Karin Ingmarsson, stoop-shouldered, half-grown boy at her side, with a look in her face that makes Tims Halvor set down his coffee and glance around for the door.',
      tour: `Karin Ingmarsson arrives at the schoolmaster's household — the sister of young Ingmar, recently widowed by the ruinous Elof Ersson, who squandered the family money deliberately before dying. Karin is carrying the consequences. The chapter follows her reappearance in the community after Elof's death, the delicate social negotiations around Tims Halvor's old courtship, and the beginning of her interest in the religious movement that has been gathering around Storm's mission house. Gertrude is introduced here as a fully drawn character.`,
      blurb: `Karin Ingmarsson returns to the valley after her disastrous marriage to Elof Ersson, who deliberately ruined them before dying. Tims Halvor, who once courted her, is at the schoolmaster's table when she arrives. The old courtship and the new movement begin to intersect.`,
      summary: [
        `Autumn at the schoolmaster's household. Mother Stina spots a familiar figure coming down the road: Karin Ingmarsson, stoop-shouldered, half-grown boy beside her. Tims Halvor is also at the table — the young shopkeeper who once courted Karin before her family decided he wasn't quite good enough. When he sees her coming he glances around for a way out, then sits still.`,
        `Karin's situation is grim. Her late husband Elof Ersson squandered every kroner they had deliberately, leaving the farm mortgaged to the point of loss. The Ingmar name — the most respected in the parish — is now attached to poverty. Tims Halvor had told her that refusing him would be "heaping shame upon me that will be hard to bear." Now the shame runs the other way.`,
        `Gertrude is present throughout, observing Ingmar and Karin with the complicated attention she gives everything. She is the schoolmaster's daughter: imaginative, proud, fond of Ingmar in a way she has not yet examined. The chapter begins to draw the threads that Book Two will pull tight: the Ingmarsson family's reduced circumstances, Karin's moral seriousness, Gertrude's unexamined feeling for Ingmar, and the religious movement waiting in the background.`,
      ],
      appears: [{ id: 'karin', name: 'Karin Ingmarsson' }, { id: 'gertrude', name: 'Gertrude' }, { id: 'tims-halvor', name: 'Tims Halvor' }, { id: 'storm', name: 'Storm' }, { id: 'mother-stina', name: 'Mother Stina' }],
      themes: [{ slug: 'land', label: 'Land' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 5,
      title: 'Book Two — In Zion',
      tourTitle: 'The schoolmaster is wrong',
      hook: 'The pastor and Storm stand in the vestry after service, discussing the Salvation Army. Storm says the thing he is most certain of: that innovations of that sort will never touch this parish. He is entirely wrong.',
      tour: `The chapter follows Storm's encounter with the religious revival that has begun in the parish. Storm has been confident that his authority — combined with the pastor's, and rooted in thirty years of relationships — is enough to contain any enthusiasm. He discovers, at a meeting at the mission house, that it is not. Something has moved through the community that his ordinary methods cannot reach. The chapter is a careful, slightly comic portrait of a man whose competence in one domain does not protect him in another.`,
      blurb: `Storm discovers that his authority in the parish is not sufficient to keep the Hellgum movement from taking hold. Lagerlöf is gentle about this; she simply shows him being wrong in full view of a community that has always trusted him.`,
      summary: [
        `After Sunday service, Storm and the pastor discuss the Salvation Army. Storm is dismissive: innovations of that kind don't reach this parish, he says, because he and the pastor stand together. The pastor is more cautious — he knows himself to be a weak man, and he is quietly amused by Storm's certainty. He does not argue; he simply asks how Storm can be so sure. Storm does not answer.`,
        `The chapter then follows Storm through the beginnings of what will become the Hellgumist movement. The schoolmaster goes to the mission house, expecting to manage the meeting as he has managed everything else for thirty years. He cannot. The people who are gathering there are his own parishioners — people he taught, families he knows intimately — and they are finding something he cannot give them.`,
        `Lagerlöf handles Storm with great tact. She does not make him foolish; she makes him limited. His authority is real. It simply does not extend to this. The chapter closes with the movement established in the parish despite him, and with Storm unable to decide what to do about it.`,
      ],
      appears: [{ id: 'storm', name: 'Storm' }, { id: 'hellgum', name: 'Hellgum' }],
      themes: [{ slug: 'faith', label: 'Faith' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 6,
      title: 'Book Two — The Wild Hunt',
      tourTitle: 'After the ruin',
      hook: 'Elof Ersson is dead and the damage is done. Ingmar is penniless. He moves back to the schoolmaster\'s household as a student, and begins to rebuild — not the farm, but a friendship with Gertrude that neither of them knows how to name.',
      tour: `Ingmar, having lost his inheritance to Elof's deliberate destruction, moves back to the Storms' household as an older student. The chapter follows his rebuilding — not financial, but relational. Gertrude is here, and the two of them develop the closeness that will make everything that follows so costly. Lagerlöf also follows Karin through the aftermath of Elof's death: her sense that she has been punished unjustly, her grief, and the beginning of her movement toward Hellgum's community.`,
      blurb: `Ingmar, penniless after Elof's ruin, returns to the schoolmaster's as a student. He and Gertrude grow close in the careful, unexamined way of two people who have not yet decided what they are to each other. Karin, meanwhile, begins to be drawn toward the mission house.`,
      summary: [
        `Elof Ersson has died leaving Karin and Ingmar penniless — deliberately, out of spite. Many think Elof should find no peace in his grave for the way he treated them. Ingmar, who wanted to become a teacher, moves back to Storm's household as a student, borrowing books from the village while he works out his next step. Karin stays on the mortgaged farm, trying to manage the debt.`,
        `At the schoolmaster's, Ingmar and Gertrude fall into their old pattern — he helps her with lessons, minds her "like a slave," endures her condescension with complete patience. Gertrude has always treated him as slightly beneath her; now that he is genuinely poor, she weeps for him. She had dreamed, without quite knowing it, of what he would someday be. The poverty has not changed her feeling; it has clarified it.`,
        `Karin, through this period, is being drawn toward the community gathering around Storm's mission house. A lay preacher named Dagson is speaking there, and Karin goes hoping to understand why God has punished her through Elof. The answer she finds is not comfort; it is a new direction entirely. The Hellgum movement is beginning to claim her.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }, { id: 'karin', name: 'Karin Ingmarsson' }, { id: 'gertrude', name: 'Gertrude' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'conscience', label: 'Conscience' }],
    },
    {
      n: 7,
      title: 'Book Two — Hellgum',
      tourTitle: 'Hellgum arrives',
      hook: 'The night of a dance at Strong Ingmar\'s, Karin dreams of her dead husband in the next room. When she wakes, her legs will not hold her. She goes to the mission house to find out why God has punished her — and finds Hellgum.',
      tour: `Hellgum's arrival in the parish and his effect on Karin. Karin has a dream-visitation from the dead Elof that leaves her unable to walk. The physical collapse leads her to the mission house, where Hellgum is speaking. What he tells her — or what she hears, which may be different — changes her. The chapter is the turning point of Book Two: the moment when the abstract question of whether Hellgum's movement will reach the parish becomes the specific fact of Karin being reached.`,
      blurb: `Karin collapses after a dream-visitation from the dead Elof. Seeking explanation at the mission house, she encounters Hellgum. Her conversion begins. Lagerlöf renders it without mockery and without endorsement.`,
      summary: [
        `The night of a dance at Strong Ingmar's, Karin is alone in her little chamber. She has a frightful dream: Elof alive, holding a wild party in the next room, laughing close to her ear. She wakes to find a windowpane burst and the room full of cold wind — and her legs will not hold her. The doctor calls it fright. Karin believes Elof was in the room.`,
        `She is taken to Storm's mission house, where a lay preacher named Dagson is leading meetings. Karin sits in the crowded hall hoping to discover why God has punished her. She examines her conscience and can find no sin that merits what happened to her. "God is unjust to me," she thinks — then goes to hear Dagson.`,
        `What she hears, and the encounter with Hellgum that follows, begins her conversion. Lagerlöf does not dramatize a sudden transformation; she shows Karin finding, in the movement's certainty, an answer to the injustice she cannot account for in her own terms. The chapter ends with Karin changed — not loud about it, not theatrical, but changed. The Ingmar Farm is now in danger.`,
      ],
      appears: [{ id: 'karin', name: 'Karin Ingmarsson' }, { id: 'hellgum', name: 'Hellgum' }, { id: 'tims-halvor', name: 'Tims Halvor' }],
      themes: [{ slug: 'faith', label: 'Faith' }, { slug: 'land', label: 'Land' }],
    },
    {
      n: 8,
      title: 'Book Two — The New Way',
      tourTitle: 'Ingmar resists',
      hook: 'Ingmar comes back from the forest in spring, glad to sleep in a proper bed again. Karin has news: "We are no longer on earth, but in the New Jerusalem which is come down from Heaven." Ingmar listens. He cannot quite say no. He cannot quite say yes.',
      tour: `Ingmar returns from a winter in the forest cutting timber and finds his sister deep in the Hellgum movement. She wants him to join. He is drawn to Hellgum personally — he had liked the preacher before the conversion question became acute — but he cannot find a father's sanction for going. The chapter is the clearest portrait of young Ingmar's paralysis: the method that has guided his family for generations has no answer for this new question, and he cannot act without one.`,
      blurb: `Ingmar returns from winter in the forest to find Karin fully converted to Hellgumism. She urges him to join. He cannot find a reason his fathers would have endorsed. He cannot refuse. He does nothing.`,
      summary: [
        `Spring. Ingmar and Strong Ingmar return from the forest after a winter of cutting timber and making charcoal. Ingmar comes back like a bear out of hibernation — delighted by a proper bed, Karin's cooking, the warmth of the lowland village. She has ordered new clothes for him. The homecoming is tender.`,
        `Then Karin tells him they are no longer on earth but in the New Jerusalem come down from Heaven. She wants him to join the movement. Ingmar says he will think it over. He has always liked Hellgum personally — they talked at the mill the previous summer, and Ingmar found him the finest fellow he had ever met. But his father had never approved anything like this. The fathers are silent on the question of a preacher from America calling Swedish farmers to Jerusalem.`,
        `Ingmar remains suspended. He attends meetings, listens to Hellgum, feels the pull of something he cannot name — and cannot act on it without a sanction that the family method cannot provide. His inability to move is not cowardice; it is faithfulness to a mode of reasoning that has run out of road. Book Two ends with this suspension in place, and Book Three will show what it costs.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }, { id: 'karin', name: 'Karin Ingmarsson' }, { id: 'hellgum', name: 'Hellgum' }],
      themes: [{ slug: 'conscience', label: 'Conscience' }, { slug: 'faith', label: 'Faith' }],
    },
    {
      n: 9,
      title: 'Book Three — Loss Of L\'Univers',
      tourTitle: 'The ship',
      hook: 'A misty night in 1880 on the Atlantic. The great French liner L\'Univers is crossing from New York. An old sailor in his hammock cannot sleep. Something is wrong.',
      tour: `Book Three opens on the Atlantic, two years before the Hellgum movement reaches Dalarna. A French liner is crossing the ocean in the dark. Lagerlöf follows a French sailor who cannot sleep and sees a vision — a supernatural quiet, a sense of the ship going to the bottom. The chapter moves into the sinking of the ship itself, rendered with documentary precision and with the novel's characteristic restraint. The connection to the main story will emerge in Chapter 10.`,
      blurb: `A French liner crossing the Atlantic in 1880. A sailor has a premonition. The ship sinks. Lagerlöf renders the disaster with documentary calm before connecting it to the Dalarna story.`,
      summary: [
        `One misty night in the summer of 1880, the great French liner L'Univers steams across the Atlantic from New York bound for Le Havre. Below decks, a brawny old French sailor is lying in his hammock unable to sleep. The ship's timbers creak in a slight sea, and he lies there musing about the ocean — how there is nothing like it, how he would not mind if his end were a watery grave rather than a churchyard.`,
        `Then everything goes quiet. The propeller stops, the rudder chains, the waves, the wind. The sailor thinks the ship has gone to the bottom. He begins to worry that his soul, without Extreme Unction, will not find its way to heaven. He sees two small acolytes with candles moving through the crowded hammock-room — a vision he cannot explain. Then reality returns.`,
        `Later, the ship strikes something in the dark. The disaster unfolds with great speed. Lagerlöf renders it in the plain, specific language she uses throughout the novel — the color of the sea, the behavior of the sailors, the particular sound of things going wrong. Survivors will be few. The chapter ends in the water.`,
      ],
      appears: [],
      themes: [{ slug: 'faith', label: 'Faith' }],
    },
    {
      n: 10,
      title: 'Book Three — Unity, Unity.',
      tourTitle: 'After the sinking',
      hook: 'Bodies in the water. A small boat. Three survivors and someone who hears, in the noise of the disaster, what she takes to be an answer from God.',
      tour: `The aftermath of the L'Univers sinking. A woman survivor is rescued by a small boat containing three people: a brawny old sailor, an elderly woman with round owlish eyes, and a heartbroken boy. On a Norwegian ship the next afternoon, more bodies are found floating. Lagerlöf uses the shipwreck to introduce the providential framework that underlies the Hellgum movement — the sense that disasters and survivals alike are communications from God. The chapter connects the Atlantic catastrophe to the Dalarna story.`,
      blurb: `Survivors of the L'Univers sinking. A woman hears the noise of catastrophe as an answer from God. A Norwegian ship finds bodies. The Atlantic disaster begins to connect to the Swedish village.`,
      summary: [
        `A woman pulled from the water believes she has heard God speaking through the noise of the disaster — the churning, the shrieking, the waves — a voice saying "Unity, Unity." She is rescued by a small boat with three occupants: a brawny old sailor, an elderly woman with round owlish eyes, and a poor little heartbroken boy. Lagerlöf renders the rescue with the same spare precision as the sinking.`,
        `The following afternoon, a Norwegian ship sailing along the Newfoundland banks finds bodies in the water. The sea is clear and still as a mirror. The bodies drift past one by one, and the sailors watch them in silence. There is a child among them, eyes open, as if out upon an urgent errand.`,
        `The chapter establishes the novel's providential register without asserting it directly. Things happen; some people find God's hand in them. Lagerlöf does not confirm or deny. What she shows is the texture of how disasters produce faith, and how that faith travels — across oceans, into villages, through the hands of a preacher who himself survived something he could not explain.`,
      ],
      appears: [],
      themes: [{ slug: 'faith', label: 'Faith' }],
    },
    {
      n: 11,
      title: 'Book Three — Hellgum\'s Letter',
      tourTitle: 'The old woman in the forest',
      hook: 'Old Eva Gunnersdotter comes out of her log cabin in the forest in her best clothes and walks down to the Ingmar Farm for a Hellgumist meeting. She remembers when the movement was as milk and honey. It is not anymore.',
      tour: `Old Eva Gunnersdotter walks to what she fears will be a diminished meeting. She has been one of the most zealous converts to Hellgum's teachings — the movement found her in her forest solitude and gave her a community of brothers and sisters. Now she fears that defections have weakened it past recovery. Hellgum's letters are read at the meeting like scripture. The chapter is a portrait of what the movement means at its best, and of what it is beginning to cost its most loyal members.`,
      blurb: `Old Eva Gunnersdotter, the most zealous of Hellgum's converts, walks to a meeting at the Ingmar Farm remembering when the movement was at its height. It has declined. The letters from America are all that remain of the original certainty.`,
      summary: [
        `Eva Gunnersdotter comes out of her little log cabin in the forest dressed as if for church, though it is only a weekday. She is very old and very frail but holds herself erect. She has a long walk to the Ingmar Farm. Along the way she remembers what the Hellgum movement was in its early days — brothers and sisters who came to find her in her solitude, who cleared paths to her cabin after snowfall, who gave her a community she had not had in years.`,
        `Now she is troubled. Too many have abandoned the movement. The summer she had hoped would bring the departure is not bringing it. She recites to herself the lines from Hellgum's letters that she knows by heart — letters the Hellgumists treat as apostolic writings, reading them at every meeting as the Bible is read in church. The letters demand a Jerusalem departure that keeps being postponed.`,
        `The meeting at the Ingmar Farm is smaller than it once was. Hellgum's letter is read aloud. It is all they have left of the original fire. Old Eva listens, remembers, and holds to it. The chapter is a study in faith that has outlasted its first certainty and found something quieter and more stubborn in its place.`,
      ],
      appears: [{ id: 'eva-gunnersdotter', name: 'Old Eva Gunnersdotter' }, { id: 'hellgum', name: 'Hellgum' }],
      themes: [{ slug: 'faith', label: 'Faith' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 12,
      title: 'Book Three — The Big Log',
      tourTitle: 'The log',
      hook: 'At dusk, two young lovers stand in the road. Ingmar has brought a big log down from the forest — so heavy the horse could barely pull it. It is the first timber toward the house he means to build for him and Gertrude. The first. He has been at it five years.',
      tour: `A short chapter, but structurally pivotal. Ingmar has been accumulating timber for five years — slowly, one log at a time — toward a new house for himself and Gertrude. The chapter is a scene of two people who love each other standing in a road talking about a log, and it is one of the most tender and saddest in the novel. They are planning a future that the pilgrimage has already made impossible. Neither of them knows it yet.`,
      blurb: `Ingmar brings down the first log toward a new house he is building for himself and Gertrude. One log, five years in the making. They stand in the road and admire it. They are planning a future the Hellgum movement is already closing off.`,
      summary: [
        `At dusk, Ingmar drives a big log down from the forest and halts in front of the school. Gertrude comes out to look. She cannot say enough in praise of it — how long and thick and straight, what fine timber. Ingmar tells her how long it lay drying in the forest, where it was felled, how heavy it was to haul.`,
        `"But, Ingmar," she says, "it is only the first." Five years of effort have produced one log toward the house he means to build. Gertrude is slightly uneasy at this pace, but Ingmar seems confident. Difficulties can be overcome; he will get more; the house will be built.`,
        `The scene is brief. Lagerlöf gives it less than twenty paragraphs. Its weight comes from what the reader knows and the characters do not yet: that Karin has decided, and the auction of the Ingmar Farm is approaching, and Ingmar will not have a farm to build on or a marriage to build for. The log stands in the road. They look at it together.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }, { id: 'gertrude', name: 'Gertrude' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'land', label: 'Land' }],
    },
    {
      n: 13,
      title: 'Book Three — The Ingmar Farm',
      tourTitle: 'The blizzard',
      hook: 'A blizzard. The pastor, called to a sick person in the north of the forest, struggles toward the Ingmar Farm through snow that always banks against the high boarding Big Ingmar refused to remove.',
      tour: `The pastor and his servant fight their way through a blizzard toward the Ingmar Farm, hampered by the same snowdrift that has always piled against the high boarding Big Ingmar was asked repeatedly to remove and never did. The chapter is a winter meditation on the farm itself — the physical fact of the place, its stubbornness, its relationship to the families who have held it. The pastor arrives to find things changed. The sale is proceeding.`,
      blurb: `The pastor struggles toward the Ingmar Farm in a blizzard, hampered by a drift that has banked in the same place for generations — because Big Ingmar never removed the boarding that caused it. The farm is on the edge of sale.`,
      summary: [
        `A blizzard. The pastor, called to the bedside of a sick person up in the north forest, makes his way by sledge toward the Ingmar Farm. In some places the snow is manageable; in others it is deep and hard. The worst obstacle is always the same: a massive drift that banks against the high boarding near the Ingmar Farm, as hard as rock and impossible to turn aside from.`,
        `The pastor remembers that he has asked Big Ingmar many times to remove the high boarding that causes the drift. Nothing was ever done. Everything else on the farm was kept in order — Big Ingmar was meticulous — but this particular problem never got fixed. The drift reappears every winter, exactly as before.`,
        `They push through. The pastor arrives to find the farm in the condition that the blizzard outside has framed appropriately: things are in order on the surface, but the shape of what's coming is already present. The boarding stays. The drift stays. The farm is being sold.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }],
      themes: [{ slug: 'land', label: 'Land' }, { slug: 'conscience', label: 'Conscience' }],
    },
    {
      n: 14,
      title: 'Book Three — Hoek Matts Ericsson',
      tourTitle: 'A farmer in his last spring',
      hook: 'A peasant and his son walk the length of the parish on a beautiful spring day. The father cannot stop looking at the fields, pricing calves, estimating potato crops. His son keeps reminding him: in the fall we will be in the valley of Sharon.',
      tour: `Hoek Matts Ericsson and his son Gabriel traverse the parish on the last spring before departure. The father is so deeply rooted in the particular soil of Dalarna — its potatoes, its calves, its oat sowing — that his son must constantly redirect him toward Palestine. The chapter is gently comic and deeply sad: a portrait of a man whose attachment to the land he is leaving survives his conversion right to the moment of departure. Lagerlöf does not judge him. She finds him entirely comprehensible.`,
      blurb: `Hoek Matts Ericsson walks the parish on a beautiful spring day, unable to stop admiring the crops and the calves. His son Gabriel keeps reminding him that in the fall they will be in the valley of Sharon. The father brightens briefly at this and then goes back to the potatoes.`,
      summary: [
        `A beautiful spring day. Hoek Matts Ericsson and his son Gabriel are walking from the north end of the parish to the great ironworks in the south, traversing almost the entire length of the valley. The fields are newly sown, the grain just showing. Houses are being repainted; gardens are being planted. Everyone they meet has muddy shoes and grimy hands from the soil.`,
        `Hoek Matts cannot walk past any of it without stopping. He asks what kind of potatoes are being planted and when the oats were sown. He calculates the number of cows on each farm by looking at the pastures. He prices every calf and foal he sees. His son Gabriel tries repeatedly to redirect him: "I'm thinking that you and I will soon be wandering through the valley of Sharon and the desert of Judea." His father brightens, agrees it will be a blessed privilege to walk in the Lord's footsteps — and immediately notices some quicklime by the road and asks who's hauling it.`,
        `The chapter is one of Lagerlöf's most quietly devastating. Hoek Matts is entirely sincere in his faith; he is also entirely sincere in his love for this valley. The two things coexist without resolution. By fall, God willing, he will be in Jerusalem. For now, he is in Dalarna, and the Dalarna is very beautiful.`,
      ],
      appears: [{ id: 'hoek-matts', name: 'Hoek Matts Ericsson' }],
      themes: [{ slug: 'land', label: 'Land' }, { slug: 'faith', label: 'Faith' }],
    },
    {
      n: 15,
      title: 'Book Three — The Auction',
      tourTitle: 'The auction',
      hook: 'One day in May there is an auction sale at the Ingmar Farm. It is a perfect day — as warm as summer, hawthorns in bloom on the road. Mother Stina stops to pick wildflowers and thinks there is nothing lovelier than this, not even Jerusalem.',
      tour: `The auction of the Ingmar Farm — the chapter the entire novel has been building toward. Mother Stina walks to the farm through the flowering May countryside. The farm is sold. Ingmar has been trying to buy it back, but Tims Halvor has the money from the sawmills. The community watches an ancient institution be transferred, and Lagerlöf renders their reaction not as outrage but as a kind of grief too large for easy expression.`,
      blurb: `The Ingmar Farm is auctioned. Mother Stina walks there through the flowering May countryside, picking wildflowers and thinking the valley is lovelier than anywhere. The farm is sold to Tims Halvor and the Hellgumists. The community cannot forgive it.`,
      summary: [
        `A May morning, warm as summer. Mother Stina sets out for the auction at the Ingmar Farm, stopping along the road at every hawthorn in bloom, every hillock of lilies of the valley. "Where could you find anything lovelier than this," she thinks, "even if you were to go as far away as Jerusalem?" She has come to love the old parish more than ever since the Hellgumists called it a second Sodom.`,
        `At the farm, the auction proceeds. Ingmar has put in a bid — six thousand kroner, which is all he can raise. Tims Halvor has an offer from the Bergsana sawmills and ironworks for twenty-five thousand. Ingmar manages to borrow enough to match the commercial offer, but Halvor gets the farm. The Ingmar Farm, held by the same family since before anyone can remember, passes to a Hellgumist shopkeeper who will sell it for the money to go to Jerusalem.`,
        `Mother Stina watches, unable to bring herself to speak to Karin. The community's response is not dramatic — there are no scenes, no confrontations. There is simply the fact of it, standing in the May sunshine, as strange and irreversible as the hawthorn being in bloom. After today, the Ingmar Farm belongs to someone else.`,
      ],
      appears: [{ id: 'ingmar', name: 'Ingmar Ingmarsson' }, { id: 'karin', name: 'Karin Ingmarsson' }, { id: 'tims-halvor', name: 'Tims Halvor' }, { id: 'mother-stina', name: 'Mother Stina' }],
      themes: [{ slug: 'land', label: 'Land' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 16,
      title: 'Book Three — Gertrude',
      tourTitle: 'Gertrude\'s fear',
      hook: 'Something strange has come over Gertrude that she can neither stop nor control. It grows and grows until it threatens to take complete possession of her. It is the fear of seeing Ingmar.',
      tour: `The most interior chapter in the novel. Lagerlöf follows Gertrude's grief after Ingmar's marriage entirely through its physical manifestations: the kerchief pulled down over her face on the road, the detours through the ditches, the constant scan of the horizon. It is a portrait of devastation rendered in completely exterior terms. The chapter ends with Gertrude's decision — not fully formed yet, but taking shape — that she cannot remain in a parish where Ingmar is everywhere.`,
      blurb: `Gertrude cannot bear to see Ingmar after his marriage to Brita. Lagerlöf follows her fear through its daily mechanics — the avoidances, the detours, the watching of the horizon — rather than through interior monologue. It is entirely devastating.`,
      summary: [
        `Something strange has come over Gertrude. It is not grief in the ordinary sense; it is a boundless, growing fear of seeing Ingmar — on the road, at church, anywhere. She cannot stay and she cannot control it. She draws her kerchief down over her face when she goes out, takes the narrow bypaths alongside the ditches where she thinks there is less chance of meeting him, keeps her eyes lowered on the highroad.`,
        `The fear does not diminish; it grows. There is not a single place in the parish where she can be certain of not running across him. On the river he might be floating timber; in the forest he might cross her path. When weeding the garden she scans the road. Her pigeons do not fly at his approach; her dog does not bark; he is too familiar to trigger the usual alarms. She would shut herself in entirely if she could.`,
        `The chapter follows Gertrude through one extraordinary dream — she goes out to milk the cows and finds herself lost in a landscape that keeps shifting — and through the slow, inevitable movement toward a decision she cannot yet name. She will join the pilgrims. Not from faith, but because the parish has become intolerable. Lagerlöf does not explain this; she simply shows Gertrude at the end of a chapter-long interior journey, at a point of no return.`,
      ],
      appears: [{ id: 'gertrude', name: 'Gertrude' }, { id: 'ingmar', name: 'Ingmar Ingmarsson' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 17,
      title: 'Book Three — The Dean\'s Widow',
      tourTitle: 'Everyone tries to stop them',
      hook: 'Everybody tried to dissuade the Hellgumists. The doctor told them they would die of smallpox and fever in Jerusalem. The Hellgumists replied that they knew this, and that was why they were going.',
      tour: `The final attempt by the community and its authorities to stop the departure. The bailiff, the judge, the doctor, the councilmen — all try to persuade the Hellgumists to stay. The Hellgumists have an answer for each argument: they know the risks, and the risks are the reason they are going. An ancient dean's widow, who has not left her room above the post office in years, comes forward with a private offer that cuts through all the arguments. The chapter is the last moment before departure.`,
      blurb: `The authorities try to stop the departure with practical arguments. The Hellgumists have an answer for each one. An ancient dean's widow makes one last attempt, stranger than the others.`,
      summary: [
        `Everybody tried to dissuade the Hellgumists. The bailiff, the judge, and the councilmen asked how they could trust Americans they didn't know. The doctor told them Jerusalem was full of smallpox and malignant fevers; they were going only to die. The Hellgumists answered that they knew this, and that this was precisely why they were going — to fight the diseases, to build roads, to till the holy land, to transform God's country into a paradise.`,
        `Down in the village, an old lady — the widow of the Dean — has lived above the post office for years without leaving her room. The well-to-do peasant women bring her freshly baked bread on Sundays; sometimes people forget her entirely and then remember with a start. She sits by her window with an old Postil, more and more detached from the things of this world. But she has not been unaware of what is happening in the parish.`,
        `The Dean's widow sends for the Hellgumists before departure. She has something to say to them that the practical arguments of bailiff and doctor could not say. Lagerlöf renders the encounter with her characteristic restraint — the old woman's words are not reported directly; only their effect on the pilgrims is shown. After her, the opposition is spent. The departure will happen.`,
      ],
      appears: [{ id: 'storm', name: 'Storm' }],
      themes: [{ slug: 'faith', label: 'Faith' }, { slug: 'community', label: 'Community' }],
    },
    {
      n: 18,
      title: 'Book Three — The Departure Of The Pilgrims',
      tourTitle: 'The wagons leave',
      hook: 'One beautiful morning in July, a long train of carts and wagons sets out from the Ingmar Farm. The Hellgumists are leaving for Jerusalem. On the road stands Beggar Lina, sober for once, her grandchildren washed and combed.',
      tour: `The final chapter. The pilgrims depart. Lagerlöf builds the departure scene with a series of encounters along the road — the most powerful being Beggar Lina at her hovel, standing sober and dignified in a way no one has ever seen her, her grandchildren clean, doing honor to the passing carts. The chapter ends not with triumph or condemnation but with everyone weeping, including Lina. It is the novel's most earned emotion.`,
      blurb: `The pilgrims' wagons leave the Ingmar Farm on a July morning. The most moving moment comes not from the pilgrims themselves but from Beggar Lina — standing sober at the roadside, grandchildren washed and combed, doing honor to those who pass. Everyone cries, including Lina.`,
      summary: [
        `One beautiful morning in July, a long train of carts and wagons sets out from the Ingmar Farm. The Hellgumists have completed their arrangements and are leaving — the first stage of their journey being the long drive to the railway station. It is the departure the novel has been building toward since Karin's conversion in Chapter 7.`,
        `Moving toward the village, the procession must pass a wretched hovel called Mucklemire, home to the worst family in the parish: dirty, ragged children who shriek at passing vehicles, a drunken old crone who usually sits by the roadside, a quarrelsome husband and wife. Today, as the Jerusalem-farers approach, the old crone is standing erect and sober at the roadside, on the very spot where she usually sits drunk. Her grandchildren are washed and combed. She is doing them honor.`,
        `The pilgrims slow their horses as they pass. Then all of them — grown-ups and children alike — burst into tears. Nothing has moved them as much as Beggar Lina standing sober. They cry softly; the children wail. When the last wagon has passed, Beggar Lina also begins to weep. The departure of the pilgrims is over. Jerusalem begins with this — not with triumph, not with faith vindicated, but with a drunkard standing sober in the road to watch her neighbors leave.`,
      ],
      appears: [{ id: 'karin', name: 'Karin Ingmarsson' }, { id: 'tims-halvor', name: 'Tims Halvor' }, { id: 'gertrude', name: 'Gertrude' }, { id: 'hoek-matts', name: 'Hoek Matts Ericsson' }, { id: 'eva-gunnersdotter', name: 'Old Eva Gunnersdotter' }],
      themes: [{ slug: 'community', label: 'Community' }, { slug: 'faith', label: 'Faith' }, { slug: 'land', label: 'Land' }],
    },
  ],
};
