// A Midsummer Night's Dream — SEO page data for build-seo-pages.cjs
// Shakespeare, 9 scenes (5 acts), comedy.
// Voice: literary, declarative; lighter than Hamlet, willing to delight in absurdity. Quote sparingly but precisely.

module.exports = {
  id: 'midsummer',
  title: "A Midsummer Night's Dream",
  author: 'William Shakespeare',
  byline: 'c. 1595–96 · English comedy in five acts',
  titleAccent: 'a guided tour',
  hook: 'Three plots, one wood, one night. Four young Athenians flee an unjust marriage law and find themselves rearranged by a flower. The fairy queen wakes from a nap in love with a weaver wearing a donkey\'s head.',
  themesBlurb: 'Love\'s irrationality, the wood and the city, dream and waking, theatre, the night that rewrites a day.',
  castBlurb: 'Athens and the wood',
  castDesc: 'A duke, four lovers, a troupe of tradesmen, and the fairies who watch them.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Comedy', 'Drama', 'Renaissance literature'],

  about: [
    `<em>A Midsummer Night's Dream</em> tangles three plots over a single night. In Athens, Hermia loves Lysander but her father insists she marry Demetrius; faced with a death sentence or a convent, she and Lysander run into the woods. Helena, who loves Demetrius, tells him the plan and follows. In a parallel Athens, six tradesmen meet to rehearse a tragedy of Pyramus and Thisbe to perform at the duke's wedding. In the wood that surrounds both, Oberon and Titania, king and queen of the fairies, are quarreling over a changeling boy. Oberon sends his servant Puck to fetch a love-flower whose juice makes the sleeper love the first creature seen on waking. Puck applies it to the wrong man, transforms the weaver Bottom into a half-donkey, and the queen of the fairies wakes to fall in love with him.`,
    `Shakespeare wrote the play in the mid-1590s, around the same time as Romeo and Juliet — the two are companions, the comedy and the tragedy of young love. The verse is some of his most lyrical: Titania's monologue on the disordered seasons, Oberon's "I know a bank where the wild thyme blows," Puck's epilogue. The mechanicals' performance of Pyramus and Thisbe parodies Romeo and Juliet's plot inside its own comic frame. The Dream treats love, theatre, and authority as varieties of the same enchantment, and refuses to say which version is more real.`,
  ],
  chaptersSubtitle: 'All 9 scenes, by act and beat — from the duke\'s palace to Puck\'s closing epilogue.',
  chaptersLead: `<p>The Dream is structured as five acts, nine scenes total. Act I (two scenes) sets up the three plots — the lovers, the mechanicals, the fairies as quarrel — in the city. Acts II and III (four scenes between them) belong almost entirely to the wood and to the night, with the love-juice doing its rearranging. Act IV brings the morning and the disenchantments. Act V is the wedding feast and the play-within-a-play. Most of what matters happens in the wood between sundown and sunrise.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `The Dream is a comedy that takes love seriously enough to laugh at it. The five threads below are what the play is actually arguing under the lyric verse and the donkey\'s head.`,

  groups: [
    { label: 'Act I · Athens', subtitle: 'The duke, the lovers, the tradesmen — three plots set in motion.', chapters: [1, 2] },
    { label: 'Acts II–III · The wood at night', subtitle: 'Fairies, the love-juice, Bottom translated, the lovers\' quarrel.', chapters: [3, 4, 5, 6] },
    { label: 'Act IV · Morning', subtitle: 'Enchantments lifted; the lovers found; the mechanicals reunited.', chapters: [7, 8] },
    { label: 'Act V · The wedding', subtitle: 'Pyramus and Thisbe; Puck\'s epilogue.', chapters: [9] },
  ],

  themes: [
    {
      slug: 'love',
      title: 'Love as temporary insanity',
      greek: '"the course of true love never did run smooth"',
      preview: 'Each of the four young Athenians spends a night in the wood being made to love the wrong person by the juice of a flower. Shakespeare uses the device to argue something serious: that romantic love feels like total clarity from inside and looks like enchantment from outside.',
      essay: [
        `The four lovers begin the play with their affections fixed. Hermia loves Lysander. Lysander loves Hermia. Demetrius loves Hermia (against her will). Helena loves Demetrius (against his). By morning the men have been redirected twice and the women wounded by both turns. The play is structurally an argument about love — but the argument is conducted through choreography rather than speech. Watch where the love-juice falls; watch who chases whom across the stage; watch which couplings are still standing at sunrise.`,
        `Shakespeare's deepest provocation is that Demetrius leaves the wood still under the spell. Oberon never lifts the enchantment from him. The Athenian court treats his renewed love for Helena as restored to its proper object, even though the audience knows it is exactly the same magic Oberon imposed on Titania for laughs. The play does not flag this as a problem. It just lets you notice. The same chemical that makes a fairy queen love a donkey makes a young man love the woman he had been spurning a day earlier — and the second case is celebrated with a wedding.`,
        `Helena, before any of the magic begins, gives the play its dryest line on the subject: "love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind." She means it about Demetrius's preference for Hermia over her. By the end of the night the line has been demonstrated four times over. Love is what the mind decides to do with whoever happens to be in front of it when the eyes open. Shakespeare's Athenian lovers, made to fall in and out of it on a schedule, are not insulted by the device. They are revealed by it.`,
        `Modern readers raised on dating apps and the language of "compatibility" recognize the territory immediately. The play does not despair of love — it ends in three weddings and Oberon's blessing — but it refuses to pretend romantic certainty is anything other than a pleasant kind of weather. "The course of true love never did run smooth," Lysander says, in the play's most-quoted line on the subject, before he himself has been redirected by a flower. He is right, and he is about to prove it.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the lovers introduced)' },
        { n: 4, label: 'Scene 4 (Lysander redirected)' },
        { n: 6, label: 'Scene 6 (the lovers\' quarrel)' },
        { n: 7, label: 'Scene 7 (Demetrius left enchanted)' },
      ],
    },
    {
      slug: 'wood',
      title: 'The wood and the city',
      greek: 'Athens by day, the wood by night',
      preview: 'Athens is law, marriage by paternal command, and the threat of execution or convent for daughters who refuse. The wood outside is dream and disorder. Almost everything that matters in the play happens there.',
      essay: [
        `Athens in the play is rule. Theseus's first scene presents an Athenian law that gives a father the power to choose his daughter's husband, with death or the convent as her alternatives if she refuses. The duke states the law plainly. He does not propose to overrule it. Hermia is given four days to decide. The city is not a place of cruelty exactly — Theseus is patient, even kindly — but its order has the shape of coercion underneath the courtesy.`,
        `The wood is the opposite. Lovers run there to escape the law; fairies inhabit it; rules invert. Almost everything that matters in the play happens in the wood — the lovers' rearrangement, Bottom's translation, Titania's enchantment, the resolution of the fairy quarrel — and almost nothing in the city is the same on the morning after, even if the characters cannot quite say what changed. When Theseus rides into the wood at dawn to hunt and finds the four lovers asleep on the ground, he simply overrules Egeus and announces the weddings will happen alongside his own. The law has not been changed. The wood has changed it for him.`,
        `Shakespeare establishes a permanent geography here that English literature has used ever since: the wood is where the city's order is suspended and the changes happen that the city cannot perform itself. Hawthorne's <em>Scarlet Letter</em> and its forest meeting between Hester and Dimmesdale, the moors of <em>Wuthering Heights</em>, the heath of <em>King Lear</em>, the campsite in any number of contemporary coming-of-age novels — they all owe something to the topography Shakespeare laid down here.`,
        `What the play also suggests, quietly, is that the wood and the city are not really separate. The fairies live close enough to Athens to attend the wedding. Titania's opening speech in the wood is about how the lovers' quarrel between Oberon and herself has thrown the human seasons into disorder — fogs in the rivers, blighted corn, "hoary-headed frosts" falling on roses. The two worlds bleed into each other. What happens in the wood does not stay there.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the Athenian law)' },
        { n: 3, label: 'Scene 3 (the wood\'s disorder)' },
        { n: 7, label: 'Scene 7 (Theseus overrules Egeus)' },
        { n: 9, label: 'Scene 9 (fairies bless the city)' },
      ],
    },
    {
      slug: 'mechanicals',
      title: 'The mechanicals',
      greek: 'Bottom, Quince, and the play they take seriously',
      preview: 'Six Athenian tradesmen rehearse a tragedy and stage it for the duke. The aristocrats laugh at them throughout. Shakespeare gives the mechanicals the dignity the aristocrats withhold, and the funniest scenes in the play are also its most generous.',
      essay: [
        `The six Athenian tradesmen — Bottom the weaver, Quince the carpenter, Flute the bellows-mender, Snug the joiner, Snout the tinker, Starveling the tailor — are some of Shakespeare's funniest creations and the source of one of his deepest interests. They take their hopeless play with absolute seriousness. They worry whether the lion will frighten the ladies and propose a prologue assuring the audience it is only Snug the joiner inside a costume. They worry whether moonlight can be staged and consider bringing in a lantern to represent the moon. They worry about the wall and finally let one of their number play it, holding up his fingers to make a chink for the lovers to whisper through.`,
        `Bottom is the engine of the troupe. He wants to play every part — Pyramus, Thisbe, the lion, all of them — and would do them all with conviction. Quince has to manage him. The audition scenes in Act I, Scene 2 and the rehearsal in Act III, Scene 1 are pure comedy of vocation: men who do their day jobs well attempting an art they have no equipment for, and refusing to let the lack of equipment stop them. The comedy is never cruel. Shakespeare loves them.`,
        `The aristocrats in the audience at Theseus's wedding are not always so generous. Hippolyta, in particular, finds the performance painful: "this is the silliest stuff that ever I heard." Theseus answers her with one of the play's quietest pieces of grace: "the best in this kind are but shadows; and the worst are no worse, if imagination amend them." The lines are easy to miss. They are also Shakespeare's defense of his entire trade. A play is only ever shadows on a wall; the audience does the rest of the work; condescension toward the players is condescension toward the form itself.`,
        `Ordinary people taking art seriously, against the condescension of those who think they know better — Shakespeare returns to this pattern across his career, and Midsummer is its purest version. The mechanicals' Pyramus and Thisbe is also a parody of Romeo and Juliet, which Shakespeare had written or was writing in the same period. The same plot — secret lovers, a wall, a death by misunderstanding — played for tears in one play and for laughs in this one. He could see the joke in his own materials.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (casting the play)' },
        { n: 5, label: 'Scene 5 (rehearsal interrupted)' },
        { n: 8, label: 'Scene 8 (Bottom returns)' },
        { n: 9, label: 'Scene 9 (Pyramus and Thisbe performed)' },
      ],
    },
    {
      slug: 'dream',
      title: 'Dream and waking',
      greek: '"I have had a most rare vision"',
      preview: 'The play\'s title promises a dream and the play delivers one. Each of the lovers wakes uncertain whether the night happened. Bottom, alone of them, knows it did, and gives the play\'s strangest and most moving speech.',
      essay: [
        `The play's title is also its argument. What happened in the wood was a dream — or it was real and is being treated as a dream so that ordinary life can resume. Shakespeare keeps the question open. The four lovers wake at dawn on the forest floor and cannot quite remember why they are there. "These things seem small and undistinguishable, like far-off mountains turned into clouds," Demetrius says. They walk back to Athens convinced something significant occurred and unable to describe it.`,
        `Bottom is the exception. He alone remembers — or thinks he does — and his waking speech is one of the quietest, strangest passages in all of Shakespeare. "I have had a most rare vision. I have had a dream, past the wit of man to say what dream it was." He tries to describe it and fails. "The eye of man hath not heard, the ear of man hath not seen, man's hand is not able to taste, his tongue to conceive, nor his heart to report, what my dream was." The lines garble St. Paul on purpose — Paul says the eye has not seen what God has prepared; Bottom mixes up the senses entirely — and the garbling is itself the point. The vision is real. The instruments for reporting it are not equal to the task.`,
        `Puck closes the play with the same offer to the audience. "If we shadows have offended, think but this, and all is mended — that you have but slumbered here while these visions did appear. And this weak and idle theme, no more yielding but a dream, gentles, do not reprehend." The whole performance, Puck suggests, was a dream you had for two hours. You can take it as nothing or as everything; the play does not insist.`,
        `What is being suggested is something that the play of Bottom and Titania has already demonstrated: that the line between real experience and dream is not where ordinary daylight thinking puts it. A man who has spent the night with the queen of the fairies in a half-donkey's body is not lying when he says he has had a vision. The Dream takes its title's claim seriously. The vision is real. The wood is real. What is uncertain is whether anything in Athens is.`,
      ],
      where: [
        { n: 6, label: 'Scene 6 (Puck makes the night a dream)' },
        { n: 7, label: 'Scene 7 (the lovers wake)' },
        { n: 8, label: 'Scene 8 (Bottom\'s vision)' },
        { n: 9, label: 'Scene 9 (Puck\'s epilogue)' },
      ],
    },
    {
      slug: 'theatre',
      title: 'Shakespeare on theatre',
      greek: 'the play within the play',
      preview: 'Bottom and his friends are terrible actors who take their play completely seriously. Their performance — and the aristocrats\' commentary on it — is Shakespeare examining the relationship between performer, play, and audience.',
      essay: [
        `Pyramus and Thisbe — the mechanicals' play — is the most extended scene of theatre-watching in Shakespeare. Five hundred lines of a wedding audience watching an amateur tragedy and commenting on it. Shakespeare uses the scene to think out loud about what theatre is for, what audiences owe performers, and how condescension toward a form damages everyone in it.`,
        `The mechanicals' anxieties before the performance are revealing. They worry the lion will frighten the ladies. They worry that bringing a sword on stage will be too violent. They worry whether moonlight is stageable. Each anxiety is the wrong question — they have not understood that the audience already knows it is theatre and will fill in what is missing — and the comedy comes partly from watching them solve problems that do not exist. But Shakespeare also lets you see the integrity of the impulse. They take the responsibility of performing seriously. They want the audience not to be misled. They are bad theorists of theatre because they care.`,
        `The aristocratic audience does not care, and the play knows it. Theseus, Hippolyta, Demetrius, Lysander spend the performance making jokes at the expense of the players. The jokes are sometimes funny. They are also socially loaded — the educated aristocrats showing each other off at the expense of working men who cannot fight back. Theseus's defense ("the best in this kind are but shadows") is mild, almost embarrassed. He is trying to recall his guests to courtesy without scolding them.`,
        `The whole sequence is also Shakespeare's thinking on his own trade. The Globe was a public theatre playing to an audience that mixed aristocrats in galleries with working men and women in the pit. He had professional reasons to be careful with the question of who got to laugh at whom. Pyramus and Thisbe is his most generous statement about it. The audience that needs theatre is not the audience that comes already convinced of its own taste. It is the audience that lets the imagination do the work the players cannot do alone.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (casting and concerns)' },
        { n: 5, label: 'Scene 5 (rehearsal)' },
        { n: 8, label: 'Scene 8 (the play preserved)' },
        { n: 9, label: 'Scene 9 (Pyramus and Thisbe)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Theseus', role: 'Duke of Athens', body: `The play's framing authority. Returning from war with Hippolyta, queen of the Amazons, whom he is about to marry. He is patient with Hermia, polite to her father, and entirely willing to enforce a death sentence if the law requires it. The play's moral weight rests partly on the fact that he is a kindly enough man whose office still rests on a coercive law — and on the morning after the wood, he simply overrules it.` },
    { name: 'Hippolyta', role: 'Queen of the Amazons', body: `Theseus's bride, won "with my sword" in war. She speaks rarely but precisely; her four lines on the lovers' story in Act V — "all the story of the night told over... grows to something of great constancy" — are the play's clearest moment of taking the wood seriously as more than a dream. She is also the only aristocrat at the wedding feast who finds Pyramus and Thisbe painful rather than merely funny.` },
    { name: 'Hermia and Helena', role: 'The Athenian women', body: `Childhood friends whose friendship nearly snaps under the strain of the night. Hermia loves Lysander; her father has chosen Demetrius for her. Helena loves Demetrius; he has cast her aside for Hermia. Once the love-juice rearranges the men, both Athenians court Helena, and Hermia accuses her oldest friend of conspiring against her. Their quarrel — "we, Hermia, like two artificial gods, have with our needles created both one flower" — is the play's most emotionally serious passage.` },
    { name: 'Lysander and Demetrius', role: 'The Athenian suitors', body: `The two young men whose affections the love-juice keeps redirecting. They are barely distinguishable, which seems to be the point. Each loves Hermia at the start, both love Helena in the middle, and the play's ending pairs them off again on the basis of which enchantment Oberon has chosen not to remove. The women love them with total conviction; the men redirect their love like weather vanes.` },
    { name: 'Oberon and Titania', role: 'King and Queen of the Fairies', body: `The play's other married couple, quarreling over a changeling Indian boy at the start and reconciled by morning. Oberon directs the action — sends Puck for the love-flower, designs Titania's humiliation, undoes it once she has given up the boy. Titania's opening speech about how their quarrel has thrown the seasons themselves into disorder is one of the play's strangest and most adult passages. The verse given to both is some of Shakespeare's most beautiful.` },
    { name: 'Puck', role: 'Robin Goodfellow, Oberon\'s servant', body: `A sprite who works for the fairy king and treats human confusion as entertainment. He fetches the love-flower, applies its juice to the wrong Athenian, watches the resulting chaos with delight, and sets it right only after Oberon insists. He gives the play its closing lines — the famous epilogue offering the whole performance back to the audience as a dream — and asks, gently, whether any of what they just saw was real.` },
    { name: 'Bottom', role: 'The weaver', body: `An Athenian weaver and enthusiastic amateur actor who wants to play every part in his troupe's tragedy. Puck transforms his head into a donkey's. Titania falls in love with him. He accepts both with imperturbable courtesy, asking the fairy attendants for hay and a barber. His waking speech — "I have had a most rare vision" — is one of the quietest, strangest passages in Shakespeare. He is the play's most grounded character, paradoxically most himself when he is least human.` },
  ],

  castSubtitle: 'Athens and the wood — three social worlds, one night.',
  castLead: `<p>Midsummer has three sets of characters that barely overlap: the Athenian court (Theseus, Hippolyta, Egeus, the four lovers); the mechanicals (six Athenian tradesmen who rehearse a play); and the fairies (Oberon, Titania, Puck, attendants). They share a stage only at the very end. Almost every scene belongs to one of the three.</p>`,
  castGroups: [
    {
      label: 'The Athenian court',
      characters: [
        { id: 'theseus', tag: 'Mortal', name: 'Theseus', epithet: 'Duke of Athens', body: `The framing authority. Returning from his war with the Amazons to marry Hippolyta, queen of the people he has just defeated. Hears Egeus's complaint against Hermia in the opening scene and confirms the law: marry the man your father chose, or die, or take a vow of celibacy. He is patient and courteous about it; the kindness does not change the law's content. On the morning after the wood, he finds the lovers paired correctly in the clearing and overrules Egeus on the spot. Hosts the wedding feast in Act V and defends the mechanicals' play with a generosity his guests do not match.`, appears: [1, 7, 9] },
        { id: 'hippolyta', tag: 'Mortal', name: 'Hippolyta', epithet: 'Queen of the Amazons', body: `Theseus's bride, won "with my sword" in war and brought back to Athens to be married. Speaks rarely but with weight. Her four-line answer to Theseus's dismissal of the lovers' story — "all the story of the night told over, and all their minds transfigured so together... grows to something of great constancy" — is the play's clearest defense of the wood as something more than a dream. She is also the only aristocrat at the wedding play who finds the mechanicals' performance painful rather than merely funny: "this is the silliest stuff that ever I heard."`, appears: [1, 7, 9] },
        { id: 'egeus', tag: 'Mortal', name: 'Egeus', epithet: 'Hermia\'s father', body: `The play's spokesman for the Athenian law that gives a father the power to dispose of his daughter. Brings Hermia, Lysander and Demetrius before Theseus in Scene 1 and demands the death sentence if she refuses Demetrius — "as she is mine, I may dispose of her." Reappears in Scene 7 in the wood to demand the same sentence be carried out on the lovers found asleep there, and is overruled by Theseus on the spot, with the duke announcing the three weddings in his place. Disappears from the play after that; not present at Act V's wedding feast.`, appears: [1, 7] },
        { id: 'hermia', tag: 'Mortal', name: 'Hermia', epithet: 'Egeus\'s daughter, in love with Lysander', body: `Faces death or the convent if she refuses to marry Demetrius. Runs into the wood with Lysander at midnight to escape the Athenian law and reach his aunt's house, beyond the duke's jurisdiction. Wakes in the wood to find Lysander courting Helena instead and accuses her oldest friend of stealing him. The shortest of the four lovers, she nearly comes to blows with Helena in the four-way quarrel — Helena hides behind Lysander. Reunited with Lysander by morning, when the spell is lifted from him alone.`, appears: [1, 4, 6, 7, 9] },
        { id: 'helena', tag: 'Mortal', name: 'Helena', epithet: 'In love with Demetrius', body: `Loves Demetrius, who has cast her off for Hermia. Tells Demetrius about Hermia and Lysander's flight in hope of regaining his favor; he is rewarded with insults, and she follows him into the wood anyway. Her opening speech on Cupid being painted blind ("love looks not with the eyes, but with the mind") is one of the play's clearest statements on love. Wakes the next morning paired with Demetrius — still under the love-juice, though no one in Athens knows it. Her quarrel with Hermia in the wood is the play's most emotionally serious scene.`, appears: [1, 3, 4, 6, 7, 9] },
        { id: 'lysander', tag: 'Mortal', name: 'Lysander', epithet: 'In love with Hermia', body: `Hermia's lover. Plans the elopement, runs into the wood with her, falls asleep some yards apart at her insistence, has the love-juice applied by Puck's mistake, wakes in love with Helena, abandons Hermia in the dark. Restored by Oberon's reversal of the spell when Puck leads him in fog through the wood until he collapses exhausted. Speaks the play's most-quoted line on love — "the course of true love never did run smooth" — before he himself becomes its clearest demonstration. Wakes paired with Hermia.`, appears: [1, 4, 6, 7, 9] },
        { id: 'demetrius', tag: 'Mortal', name: 'Demetrius', epithet: 'Favored by Egeus, in love with Hermia', body: `Egeus's choice for Hermia, having abandoned Helena to pursue her. Follows Hermia and Lysander into the wood, with Helena pursuing him; cruel to Helena there, threatens to leave her to wild beasts. Has the love-juice applied by Oberon directly to fix Puck's mistake. Wakes in love with Helena. Critically, Oberon never lifts the enchantment; the renewed love for Helena that the Athenian court celebrates as restored to its proper object is the same magic that made Titania love a donkey. The play does not flag this as a problem.`, appears: [1, 3, 4, 6, 7, 9] },
      ],
    },
    {
      label: 'The fairies',
      characters: [
        { id: 'oberon', tag: 'God', tagClass: 'creature', name: 'Oberon', epithet: 'King of the Fairies', body: `Starts the entire plot by quarreling with Titania over a changeling boy and deciding to humiliate her in revenge. Not presented as wicked, only capricious — capricious in the way the powerful tend to be when their dignity is bruised. Directs Puck, designs Titania's enchantment with the love-juice, and reverses it once he has the boy. The play's most beautiful verse — "I know a bank where the wild thyme blows" — belongs to him. Blesses the marriages in the closing scene.`, appears: [3, 4, 6, 7, 9] },
        { id: 'titania', tag: 'God', tagClass: 'creature', name: 'Titania', epithet: 'Queen of the Fairies', body: `Bewitched by her husband's spite into loving Bottom the weaver while he wears the head of a donkey. Her scenes with Bottom are at once farcical and unexpectedly tender; she garlands his ears with roses and asks her fairies to feed him apricots and dewberries and to fan moonbeams from his sleeping eyes. She is not diminished by the enchantment. Her opening speech about how the quarrel with Oberon has thrown the human seasons themselves into disorder — fogs in the rivers, blighted corn, "hoary-headed frosts" falling on roses — is one of the play's strangest and most adult passages.`, appears: [3, 4, 5, 7, 9] },
        { id: 'puck', tag: 'God', tagClass: 'creature', name: 'Puck', epithet: 'Robin Goodfellow, Oberon\'s servant', body: `A sprite who works for the fairy king and treats human confusion as entertainment. Fetches the love-flower, applies its juice to the wrong Athenian, watches the resulting chaos with delight, and sets it right only after Oberon insists. Calls the mechanicals "the shallowest thick-skin of that barren sort" and gives Bottom a donkey's head for his trouble. Speaks the play's closing epilogue, alone on the empty stage, offering the whole performance back to the audience as a dream they had for two hours — and asking, gently, whether any of what they just saw was real.`, appears: [3, 4, 5, 6, 7, 9] },
      ],
    },
    {
      label: 'The mechanicals',
      characters: [
        { id: 'bottom', tag: 'Mortal', name: 'Bottom', epithet: 'A weaver', body: `An Athenian weaver and enthusiastic amateur actor who wants to play every part in the troupe's tragedy — Pyramus, Thisbe in falsetto, the lion with terrible roaring. Puck transforms his head into a donkey's. Titania falls in love with him. He accepts both with imperturbable courtesy, asking the fairy attendants for hay and a barber. His waking speech alone in the wood — "I have had a most rare vision, past the wit of man to say what dream it was" — garbling St. Paul on what eye has not seen, is one of the quietest, strangest passages in all of Shakespeare. The play's most grounded character, paradoxically most himself when he is least human.`, appears: [2, 5, 7, 8, 9] },
        { id: 'quince', tag: 'Mortal', name: 'Quince', epithet: 'A carpenter, director of the play', body: `The troupe's harassed director and prologue-reader. Casts the play in Scene 2 and tries to manage Bottom, who wants to play every part — patiently keeps redirecting him while the others wait. Distributes scrolls of lines, schedules the rehearsal in the wood, and delivers the famously mangled prologue at the wedding ("if we offend, it is with our good will") with absolute commitment. Mispunctuates it so badly the audience hears nonsense, but his sincerity is never in question. The chosen play is also his — "the most lamentable comedy and most cruel death of Pyramus and Thisbe," picked, the troupe agrees, with great care.`, appears: [2, 5, 8, 9] },
        { id: 'flute', tag: 'Mortal', name: 'Flute', epithet: 'A bellows-mender, plays Thisbe', body: `Cast against his will as Thisbe — he protests he has a beard coming in. Plays the part anyway, in a falsetto, and delivers Thisbe's death speech at the wedding with surprising tenderness. One of the play's quiet jokes is that Flute is better at the role than the wedding audience is prepared for; his final lines, finding Pyramus dead and stabbing himself in turn, are played for laughs but land with a glimmer of real feeling. He is also the troupe's chief mourner when Bottom is missing in Scene 8: "he hath simply the best wit of any handicraft man in Athens."`, appears: [2, 5, 8, 9] },
        { id: 'snug', tag: 'Mortal', name: 'Snug', epithet: 'A joiner, plays the Lion', body: `Cast as the Lion and given his lines late ("you may do it extempore, for it is nothing but roaring"). Worried, with the rest of the troupe, that the lion will frighten the ladies in the audience, and so the company invents a tactful prologue: Snug must identify himself as Snug the joiner before any roaring begins, so the audience knows there is no actual lion in the wedding hall. He does this with characteristic gravity. The joke that he is the only mechanical without a speaking part to butcher gives him, by accident, a quiet dignity the others lack.`, appears: [2, 5, 8, 9] },
        { id: 'snout', tag: 'Mortal', name: 'Snout', epithet: 'A tinker, plays the Wall', body: `Cast as the Wall that separates Pyramus and Thisbe — a problem the troupe solves by having Snout stand on stage holding up his fingers spread to make a chink the lovers can whisper through. The play's most literal-minded staging joke; the wedding audience finds it hilarious, and Theseus uses the moment for one of his quiet defenses of imagination ("the wall, methinks, being sensible, should curse again"). Snout commits to the role completely. He is also briefly cast as Pyramus's father in early planning before the part is dropped to keep the cast at five plus the wall.`, appears: [2, 5, 8, 9] },
        { id: 'starveling', tag: 'Mortal', name: 'Starveling', epithet: 'A tailor, plays Moonshine', body: `Cast as Moonshine, which the troupe stages by having Starveling enter with a lantern, a bundle of thorn, and a dog — the conceit being that the man in the moon is the figure of an exiled wanderer carrying his thorn-bush. Heckled mercilessly by the wedding audience and finally gives up on his lines: "All that I have to say is to tell you that the lantern is the moon, I the man in the moon, this thorn-bush my thorn-bush, and this dog my dog." Shakespeare lets him finish his work with that quiet declaration, and the audience moves on. He plays Thisbe's mother in early planning before the part is cut.`, appears: [2, 5, 8, 9] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Athens — the duke\'s court and the four lovers', tourTitle: 'The duke\'s court', hook: 'A duke about to marry. A father with a complaint. A daughter ordered to obey or die. And a fifth person — Helena — already in love with the wrong man.',
      tour: `Theseus and Hippolyta open the play discussing their wedding, four days off. Egeus interrupts with a formal complaint: his daughter Hermia refuses to marry Demetrius and loves Lysander instead. He demands the Athenian penalty — death, or a convent. Theseus confirms the law and gives Hermia until his wedding day to choose. Once the duke leaves, Hermia and Lysander plan to flee Athens for Lysander's aunt's house, beyond the law's reach. Helena enters; she loves Demetrius, who has cast her off for Hermia. They tell her the plan in the hope it will help her. Helena, alone, decides to tell Demetrius — not because it will help her, but to be near him in the chase that will follow.`,
      blurb: `Theseus's court, four days before his wedding. Egeus accuses his daughter Hermia of refusing the husband he has chosen and demands the full penalty of Athenian law. Theseus confirms it. Hermia and Lysander plan to elope into the wood, where Athenian law cannot reach them. Helena, hopelessly in love with Demetrius and rejected by him, decides to tell him the plan and follow him into the wood — not because it will help her, but to be near him in the chase that follows.`,
      summary: [
        `Athens, the palace of Theseus. Theseus and Hippolyta open the play discussing their wedding, four days off; the duke complains the moon "lingers my desires," Hippolyta replies that four nights "will quickly dream away the time." Egeus interrupts with a formal complaint against his daughter Hermia. He has chosen Demetrius for her; she refuses, in love with Lysander. Egeus demands the full penalty of Athenian law — death, or perpetual chastity in a convent. Theseus, courteous but firm, confirms the law and gives Hermia until his wedding day to choose.`,
        `The duke leaves with Egeus and Demetrius. Hermia and Lysander, alone, work out an escape. Lysander has an aunt seven leagues from Athens whose house lies outside the duke's jurisdiction; they will meet in the wood tomorrow night and run there. Lysander gives the play its most-quoted line on the subject he is about to disprove: "the course of true love never did run smooth." Helena enters in distress. She loves Demetrius, who once loved her, until he saw Hermia and abandoned her. Hermia and Lysander tell her the plan in the hope it will help her — once Hermia is gone, Demetrius's reasons to stay in Athens go with her.`,
        `Helena, alone, considers what to do. She speaks the play's clearest statement on love: "love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind." Reason has nothing to do with whom one loves; Demetrius is no more rational than she is. She decides to tell him about the elopement. The news will not make him love her — he will run after Hermia into the wood — but at least she will be following him. The first plot is in motion: four young Athenians moving toward the wood for reasons the wood is about to rearrange entirely.`,
      ],
      appears: [{ id: 'theseus', name: 'Theseus' }, { id: 'hippolyta', name: 'Hippolyta' }, { id: 'egeus', name: 'Egeus' }, { id: 'hermia', name: 'Hermia' }, { id: 'lysander', name: 'Lysander' }, { id: 'demetrius', name: 'Demetrius' }, { id: 'helena', name: 'Helena' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'wood', label: 'Wood and city' }],
    },
    {
      n: 2, title: 'Quince\'s house — the mechanicals cast their play', tourTitle: 'The mechanicals cast', hook: 'Six tradesmen meet to assign roles in a tragedy of Pyramus and Thisbe. One of them wants to play every part.',
      tour: `Six Athenian tradesmen gather in Quince's house to cast a play they hope to perform at Theseus's wedding — "the most lamentable comedy and most cruel death of Pyramus and Thisbe." Quince, the carpenter, is directing. Bottom the weaver wants to play Pyramus. He also wants to play Thisbe, in falsetto, and the lion, with terrible roaring. Quince patiently keeps reassigning him. They worry the lion will frighten the ladies and propose a prologue to reassure them. They agree to rehearse tomorrow night in the wood outside Athens, away from listening neighbors. Bottom signs off with a flourish: "we will meet, and there we may rehearse most obscenely and courageously."`,
      blurb: `Six tradesmen meet at Quince's cottage to cast a tragedy of Pyramus and Thisbe for the duke's wedding feast. Bottom the weaver wants to play every part — Pyramus, Thisbe, the lion. They worry the lion will frighten the ladies and propose a tactful prologue. The troupe agrees to rehearse the next night in the wood outside Athens, where no one will overhear them and steal the play before they perform it. The third plot of the night is now in motion.`,
      summary: [
        `A room in Quince's cottage. Six Athenian tradesmen gather to cast a play. They hope to perform it at the duke's wedding feast and earn a reward — "sixpence a day during his life," Bottom hopes. Quince has chosen "the most lamentable comedy and most cruel death of Pyramus and Thisbe": a tragic story of two lovers separated by a wall who arrange to meet at a tomb outside the city, miscommunicate, and kill themselves in turn. Quince has prepared the parts on scrolls and begins to assign them.`,
        `Bottom is the company's would-be star. He wants to play Pyramus. He also volunteers, when Flute is cast as Thisbe, to play Thisbe instead — "I'll speak in a monstrous little voice." When Snug is cast as the lion, Bottom volunteers for that too, promising to roar so well that "the duke shall say, 'Let him roar again.'" Quince patiently keeps redirecting him. The roaring is then itself a problem: the women in the audience may be frightened. Bottom proposes a tactful prologue identifying himself, mid-roar, as Snug the joiner, to reassure them. The troupe agrees this is wise.`,
        `Quince distributes the scrolls. They will need beards, costumes, and a place to rehearse where no one will overhear them and steal the play. Quince proposes the wood, a mile outside Athens, by moonlight, the next evening. Everyone agrees. Bottom closes the meeting with the line that has come to stand for the whole troupe's relationship to language: "we will meet, and there we may rehearse most obscenely and courageously." The third plot has now joined the first two. Tomorrow night the lovers will be in the wood; the mechanicals will be in the wood; and the wood, as the next scene reveals, has plans of its own.`,
      ],
      appears: [{ id: 'quince', name: 'Quince' }, { id: 'bottom', name: 'Bottom' }, { id: 'flute', name: 'Flute' }, { id: 'snug', name: 'Snug' }, { id: 'snout', name: 'Snout' }, { id: 'starveling', name: 'Starveling' }],
      themes: [{ slug: 'mechanicals', label: 'The mechanicals' }, { slug: 'theatre', label: 'Theatre' }],
    },
    {
      n: 3, title: 'The wood — Oberon, Titania, and the love-flower', tourTitle: 'The fairy quarrel', hook: 'A wood, a fairy and Puck on the same path, and the king and queen of the fairies meeting in the middle of a quarrel.',
      tour: `Puck meets a fairy attendant on a path in the wood and exchanges gossip; their masters are quarreling over a changeling boy. Oberon and Titania enter from opposite directions and have it out — Titania notes the quarrel has thrown the human seasons into disorder. They part still hostile. Oberon decides on revenge: he sends Puck to fetch a flower whose juice, applied to a sleeper's eyes, makes the sleeper love the first creature seen on waking. Demetrius and Helena cross the wood; Oberon, invisible, watches Demetrius reject Helena cruelly and decides to fix that too. He instructs Puck to anoint "an Athenian" — meaning Demetrius — with the same juice.`,
      blurb: `Puck and a fairy meet on the path; their masters Oberon and Titania are at war over a changeling boy that Titania refuses to give up. The two enter and quarrel — Titania notes the human seasons have been thrown into disorder. Oberon sends Puck for a love-flower whose juice will make Titania fall in love with whatever she next sees on waking. Demetrius and Helena cross the wood. Oberon orders Puck to anoint Demetrius too, so he will love Helena instead.`,
      summary: [
        `A wood near Athens. Puck, Oberon's mischievous servant, meets a fairy attendant on the path; she serves Titania. Their masters, the king and queen of the fairies, are due to meet here tonight, and Puck warns the fairy to keep her queen out of his master's way. They are quarreling. The cause is a changeling boy — an Indian child Titania has taken into her train and refuses to give up. Oberon wants the boy as one of his henchmen. The argument has gone on long enough that the fairies' attendants now avoid each other in the wood.`,
        `Oberon and Titania enter from opposite directions and the quarrel resumes. Titania's central speech is the play's strangest: their fight, she says, has thrown the human seasons themselves into disorder. The winds, "as in revenge," have sucked up fogs from the sea; the rivers have flooded; the corn has rotted in green ear; "the seasons alter: hoary-headed frosts fall in the fresh lap of the crimson rose." She refuses again to give up the boy — his mother, a votaress of her order, died in childbirth and Titania is keeping the child in her honor. They part still hostile.`,
        `Oberon, alone, decides on revenge. He sends Puck for a flower called "love-in-idleness" whose juice, applied to a sleeper's eyes, makes the sleeper love the first creature seen on waking. He intends it for Titania. While Puck is away, Demetrius and Helena cross the stage — Helena pursuing him, Demetrius cruel, threatening to leave her to wild beasts. Oberon, invisible, listens. He decides to use the juice on Demetrius too, so he will love Helena. When Puck returns with the flower, Oberon takes some for himself and instructs Puck to find a young Athenian man being chased by a young Athenian woman, and apply the juice to the man's eyes. Puck goes.`,
      ],
      appears: [{ id: 'puck', name: 'Puck' }, { id: 'oberon', name: 'Oberon' }, { id: 'titania', name: 'Titania' }, { id: 'demetrius', name: 'Demetrius' }, { id: 'helena', name: 'Helena' }],
      themes: [{ slug: 'wood', label: 'Wood and city' }, { slug: 'love', label: 'Love' }],
    },
    {
      n: 4, title: 'The wood — Titania anointed; Lysander redirected', tourTitle: 'The flower applied', hook: 'Two sleeps, two applications of the love-juice — and Puck applies it to the wrong Athenian.',
      tour: `Titania enters with her fairies, who sing her to sleep with the famous lullaby ("you spotted snakes with double tongue"). Oberon slips in alone and squeezes the love-juice on her eyelids — "what thou seest when thou dost wake, do it for thy true love take." Lysander and Hermia, lost and exhausted, lie down to sleep nearby, decorously apart. Puck arrives looking for the Athenian, finds Lysander, and assumes this is his target; he applies the juice. Helena, pursuing Demetrius, stumbles on Lysander and wakes him by accident. He wakes in love with her, declares it passionately, and runs after her, leaving Hermia asleep on the ground. Hermia wakes alone from a nightmare of a serpent eating her heart.`,
      blurb: `Oberon squeezes the love-juice on the sleeping Titania's eyes. Puck, looking for "an Athenian," finds the wrong one — Lysander asleep on the ground beside Hermia — and anoints him by mistake. Helena, pursuing Demetrius through the wood, stumbles on Lysander and wakes him; he falls in love with her on sight and runs after her, leaving Hermia abandoned in the dark. Hermia wakes alone from a nightmare in which a serpent has eaten her heart while Lysander watched and smiled.`,
      summary: [
        `Another part of the wood. Titania enters with her fairy train, asks them to sing her to sleep, and assigns sentries against bats and spiders. The fairies sing the famous lullaby — "you spotted snakes with double tongue, thorny hedgehogs, be not seen" — and Titania falls asleep on a flowery bed. The fairies depart, leaving one sentry. Oberon slips in alone, finds her sleeping, and squeezes the juice of the love-flower on her eyelids: "what thou seest when thou dost wake, do it for thy true love take. Love and languish for his sake — be it ounce, or cat, or bear, pard, or boar with bristled hair." He leaves.`,
        `Lysander and Hermia enter from another direction. They have been wandering the wood for hours, lost, and Hermia is exhausted. They agree to lie down and sleep until morning. Lysander wants to lie next to her; Hermia, gently, makes him keep his distance. They sleep some yards apart. Puck arrives, looking for the Athenian Oberon described. He finds Lysander, in Athenian dress, asleep on the ground with a young woman lying nearby, and assumes — reasonably wrong — that this is his target. He applies the juice and goes off to report.`,
        `Demetrius runs through, fleeing Helena. He disappears into the trees and she is left alone near the sleeping Lysander. She stumbles on him on the ground and wakes him, fearing he is hurt. Lysander opens his eyes and is instantly in love; he declares it in extravagant verse and runs after her when she flees, certain she is being mocked. Hermia wakes alone, from a nightmare in which a serpent ate her heart while Lysander watched. She calls for him. There is no answer. The mismatch is complete; the lovers are scattered through the wood.`,
      ],
      appears: [{ id: 'titania', name: 'Titania' }, { id: 'oberon', name: 'Oberon' }, { id: 'lysander', name: 'Lysander' }, { id: 'hermia', name: 'Hermia' }, { id: 'puck', name: 'Puck' }, { id: 'helena', name: 'Helena' }, { id: 'demetrius', name: 'Demetrius' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'dream', label: 'Dream and waking' }],
    },
    {
      n: 5, title: 'The wood — Bottom translated; Titania wakes', tourTitle: 'Bottom translated', hook: 'The mechanicals start their rehearsal. Puck gives Bottom a donkey\'s head. The fairy queen wakes from a nap in love with him.',
      tour: `The mechanicals gather in the wood near Titania's sleeping bower to rehearse. Bottom raises problems — the lion will frighten the ladies, the moonlight cannot be staged, the wall needs solving. They decide on a prologue, a man playing Moonshine with a lantern, and Snout playing the Wall with his fingers. The rehearsal begins. Puck, watching, decides to enliven it. When Bottom exits behind a thicket and returns for his cue, his head has been transformed into a donkey's. The others flee in terror. Bottom paces and sings to keep up his courage. Titania wakes — "what angel wakes me from my flowery bed?" — and is instantly, magnificently in love.`,
      blurb: `The mechanicals begin their rehearsal in the wood, very near Titania's sleeping bower. They worry through the staging problems — lion, moonlight, wall — and start the play. Puck, watching, transforms Bottom's head into a donkey's; the others flee in terror. Bottom, certain his friends are joking, paces and sings to keep his courage. The singing wakes Titania, who is instantly in love with him. Her fairies — Peaseblossom, Cobweb, Moth, Mustardseed — lead the half-donkey weaver away to her bower.`,
      summary: [
        `Another part of the wood, very near Titania's flowery bed. The six mechanicals gather to rehearse. Bottom raises his usual problems. The lion will frighten the ladies; he will need a prologue. There must be moonlight, since Pyramus and Thisbe meet by moonlight; either they will leave a window open in the great chamber where they perform, or someone must come on stage with a bush and a lantern and play Moonshine. The wall is harder. They settle on Snout standing on stage with his fingers spread to make a chink. Quince calls them to begin.`,
        `The rehearsal proceeds. Puck, who has stumbled on the mechanicals and concluded they are "the shallowest thick-skin of that barren sort," decides to take a hand. When Bottom exits behind a thicket on his cue and reenters, his head has been transformed into a donkey's. He does not know it. His fellow actors do; they take one look and flee, screaming. Bottom, certain they are playing a joke on him, paces the clearing alone and decides to sing to keep up his courage. He sings — flatly, off-key.`,
        `In her bower a few feet away, Titania stirs at the sound. The juice of the flower is on her eyelids. She opens her eyes and sees Bottom. "What angel wakes me from my flowery bed?" she asks, in some of the play's most beautiful verse, and falls instantly, completely in love with him. Bottom, courteous as ever, accepts the situation with the imperturbability that is his nature. Titania summons her fairies — Peaseblossom, Cobweb, Moth, Mustardseed — and instructs them to wait on him hand and foot. They will feed him apricots and dewberries; they will fan moonbeams from his sleeping eyes. He goes, asking politely after each fairy's paternity. The wood has rearranged its second couple.`,
      ],
      appears: [{ id: 'quince', name: 'Quince' }, { id: 'bottom', name: 'Bottom' }, { id: 'flute', name: 'Flute' }, { id: 'snug', name: 'Snug' }, { id: 'snout', name: 'Snout' }, { id: 'starveling', name: 'Starveling' }, { id: 'puck', name: 'Puck' }, { id: 'titania', name: 'Titania' }],
      themes: [{ slug: 'mechanicals', label: 'The mechanicals' }, { slug: 'love', label: 'Love' }, { slug: 'dream', label: 'Dream and waking' }],
    },
    {
      n: 6, title: 'The wood — the lovers\' quarrel and Oberon\'s correction', tourTitle: 'The lovers\' quarrel', hook: 'Two men in love with the same woman, two women turned against each other, and Oberon and Puck setting the spell right under cover of fog.',
      tour: `Puck reports to Oberon, delighted: he has anointed an Athenian; Titania loves a donkey-headed weaver. Oberon discovers the mistake when Demetrius enters chasing Hermia, who accuses him of murdering Lysander. Oberon applies the juice to the sleeping Demetrius himself. Puck returns with Helena, Lysander on her heels. Demetrius wakes in love with Helena; Lysander still loves her. Both men now court Helena, who is convinced they are mocking her. Hermia arrives and accuses Helena of stealing Lysander. The women's friendship breaks into open quarrel; the men prepare a duel. Oberon orders Puck to lead the men through fog until they collapse, then lift the spell from Lysander only — leaving Demetrius enchanted.`,
      blurb: `Oberon discovers Puck's mistake and applies the juice to the right Athenian himself. Now both Lysander and Demetrius are in love with Helena, who is convinced she is being mocked. Hermia arrives and accuses her oldest friend of stealing Lysander; the women's friendship breaks into open quarrel — "we, Hermia, like two artificial gods, have with our needles created both one flower." Oberon orders Puck to part the men in fog and remove the spell from Lysander only, leaving Demetrius's intact.`,
      summary: [
        `Another part of the wood. Puck reports to Oberon with cheerful self-satisfaction: he has anointed an Athenian; Titania is in love with a man wearing a donkey's head. Oberon, pleased about Titania, becomes alarmed when Demetrius enters chasing Hermia, who is accusing him of murdering Lysander. The wrong man has been anointed. Oberon orders Puck to find Helena and bring her, and applies the love-juice to the sleeping Demetrius himself.`,
        `Puck returns leading Helena with Lysander on her heels — both men still in love with her. Demetrius wakes; he too is now in love with Helena. The three crowd in on her in extravagant praise. Helena, convinced she is being mocked, becomes furious. Hermia arrives looking for Lysander and finds him courting Helena. The four-way quarrel is the longest and most emotionally serious scene in the play. Helena, in tears, recalls their childhood: "we, Hermia, like two artificial gods, have with our needles created both one flower, both on one sampler, sitting on one cushion." The men prepare a duel. Hermia, the shortest of the four, attacks Helena; Helena hides behind Lysander.`,
        `Oberon takes charge. He orders Puck to lead each man through the wood in fog until they collapse from exhaustion, and then — once they are sleeping — remove the love-juice from Lysander only. Demetrius's enchantment is to remain. Puck obeys. Imitating each man's voice, he leads them in opposite directions until both sink to the ground and sleep. Helena and Hermia, separately, wander into the same clearing exhausted and also lie down. By moonlight Puck steals to Lysander and squeezes the antidote on his eyes — "Jack shall have Jill, naught shall go ill, the man shall have his mare again, and all shall be well." Four sleepers in a clearing, none aware of the others, while Puck slips off into the dawn.`,
      ],
      appears: [{ id: 'puck', name: 'Puck' }, { id: 'oberon', name: 'Oberon' }, { id: 'demetrius', name: 'Demetrius' }, { id: 'hermia', name: 'Hermia' }, { id: 'helena', name: 'Helena' }, { id: 'lysander', name: 'Lysander' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'dream', label: 'Dream and waking' }],
    },
    {
      n: 7, title: 'Morning — Titania released; the lovers found', tourTitle: 'Morning in the wood', hook: 'The fairy queen released from her donkey. The duke\'s hunting horns. Four lovers waking up paired correctly, and not sure why.',
      tour: `Titania dotes on Bottom in her bower. He asks the fairies for hay and falls asleep in her arms. Oberon enters; he has obtained the changeling boy from the besotted Titania and is satisfied. He releases her with the antidote. She wakes, sees Bottom's donkey head, and is repulsed. They reconcile and dance; Puck removes the donkey's head. Theseus and Hippolyta enter with hunting horns, find the four lovers asleep on the ground, and wake them. Demetrius (still enchanted, though no one knows it) declares his love for Helena. Theseus overrules Egeus on the spot: the three couples will be married this morning alongside his own. They follow him out. Bottom wakes alone in the empty wood.`,
      blurb: `Oberon, having obtained the changeling boy, releases Titania from the spell. She wakes disgusted by Bottom's donkey head; they reconcile and dance. Theseus's hunting party finds the four lovers asleep in the wood, paired correctly — Demetrius (still enchanted, though no one knows it) loves Helena, Lysander loves Hermia. Theseus overrules Egeus on the spot and announces the three weddings will take place alongside his own this morning. The lovers follow him out. Bottom wakes alone in the empty wood.`,
      summary: [
        `Titania's bower at dawn. Titania reclines with Bottom in her arms, doting on him while her fairies attend. Bottom, courteous, asks Peaseblossom to scratch his head and Cobweb to kill him a red-hipped bumble-bee on the top of a thistle and bring him the honey-bag. He confesses an appetite for hay and proposes finding a barber. He falls asleep mid-conversation. Oberon enters. He has, by this point, obtained the changeling boy from the besotted Titania without difficulty; with the boy in his train, his quarrel is over. He looks at Titania with the donkey-headed weaver in her arms and decides he has had enough revenge. He squeezes the antidote on her eyes.`,
        `Titania wakes. Her first words are confused — "my Oberon, what visions have I seen!" She looks down, sees Bottom in his donkey's head, and is appalled. Oberon orders Puck to remove the head. He does. Oberon and Titania reconcile and dance together; their music summons the fairies; they leave to bless the weddings that are to come. Bottom is left sleeping on the ground, his own head restored.`,
        `Hunting horns. Theseus and Hippolyta enter the wood at dawn, with Egeus and a hunting party, on their way to the temple where they will be married. They notice the four lovers asleep on the ground. The lovers wake, confused and apologetic. Lysander explains that he and Hermia were eloping; Egeus immediately demands the law's penalty. But Demetrius — still under the love-juice, though no one in the human world knows that — declares he no longer loves Hermia: "my love to Hermia, melted as the snow," is now devoted to Helena. Theseus overrules Egeus on the spot. The three couples will be married this morning, alongside Theseus and Hippolyta. They go. Bottom wakes alone in the empty wood.`,
      ],
      appears: [{ id: 'titania', name: 'Titania' }, { id: 'bottom', name: 'Bottom' }, { id: 'oberon', name: 'Oberon' }, { id: 'puck', name: 'Puck' }, { id: 'theseus', name: 'Theseus' }, { id: 'hippolyta', name: 'Hippolyta' }, { id: 'egeus', name: 'Egeus' }, { id: 'lysander', name: 'Lysander' }, { id: 'hermia', name: 'Hermia' }, { id: 'demetrius', name: 'Demetrius' }, { id: 'helena', name: 'Helena' }],
      themes: [{ slug: 'love', label: 'Love' }, { slug: 'wood', label: 'Wood and city' }, { slug: 'dream', label: 'Dream and waking' }],
    },
    {
      n: 8, title: 'Athens — Bottom\'s vision, and the troupe reunited', tourTitle: 'Bottom\'s vision', hook: 'A weaver wakes alone in the wood. He cannot describe what he has seen. He goes to find his friends, who have given him up for lost.',
      tour: `Bottom, alone in the wood, wakes and thinks for a moment he is still at the rehearsal. Then he half-remembers the night. His speech is one of the quietest, strangest passages in Shakespeare: "I have had a most rare vision. I have had a dream, past the wit of man to say what dream it was." He resolves to have Quince write a ballad called "Bottom's Dream," because it has no bottom. In Quince's house, the troupe have given Bottom up for lost — Pyramus is a part no one else can play, and the wedding is today. Bottom bursts in. He refuses to tell them what happened. The play is on; they must hurry to the palace.`,
      blurb: `Bottom wakes alone in the wood after his transformation and gives the play's strangest speech: "I have had a most rare vision." He cannot describe it and resolves to have it set to a ballad. At Quince's house, the troupe have given him up for lost — without Pyramus there is no play. He bursts in restored, refuses to explain what happened in the wood, and tells them the play is on at the palace immediately. They must hurry, dress, and be ready.`,
      summary: [
        `The wood, mid-morning. Bottom wakes alone on the forest floor. He thinks for a moment he is still at the rehearsal, missed his cue, and starts up: "When my cue comes, call me, and I will answer. My next is, 'Most fair Pyramus.'" Then he registers that no one is there. The events of the night come back to him in fragments. His head feels strange because it has just stopped being a donkey's.`,
        `What follows is one of the quietest, strangest passages in all of Shakespeare. "I have had a most rare vision. I have had a dream, past the wit of man to say what dream it was." He tries, gamely, to describe it and fails. "Methought I was — there is no man can tell what. Methought I was, and methought I had — but man is but a patched fool, if he will offer to say what methought I had." He garbles a famous passage from St. Paul on what the eye has not seen and the ear has not heard, mixing up the senses entirely; the garbling is itself the point. His instruments for reporting the vision are not equal to it. He resolves Quince must write a ballad called "Bottom's Dream, because it hath no bottom," and sets off for Athens.`,
        `In Quince's house, the troupe has given Bottom up for lost. Without him there is no Pyramus and so no play. Flute laments: "he hath simply the best wit of any handicraft man in Athens." A messenger arrives — the duke is married, two more couples with him, the feast is on — the door opens and Bottom bursts in, restored. He refuses to tell them what happened: "ask me not, for if I tell you, I am no true Athenian." The play is on. They must hurry to the palace.`,
      ],
      appears: [{ id: 'bottom', name: 'Bottom' }, { id: 'quince', name: 'Quince' }, { id: 'flute', name: 'Flute' }, { id: 'snout', name: 'Snout' }, { id: 'starveling', name: 'Starveling' }, { id: 'snug', name: 'Snug' }],
      themes: [{ slug: 'dream', label: 'Dream and waking' }, { slug: 'mechanicals', label: 'The mechanicals' }],
    },
    {
      n: 9, title: 'The palace — Pyramus and Thisbe, and the fairies\' blessing', tourTitle: 'Pyramus and Thisbe', hook: 'Three weddings, the worst-best amateur tragedy in literature, and a sprite at the end asking the audience to forgive him if any of this offended them.',
      tour: `Theseus dismisses the lovers' story — "more strange than true." Hippolyta is less sure. The three couples enter, married, and Theseus picks "the most lamentable comedy and most cruel death of Pyramus and Thisbe" from a list of entertainments. The mechanicals perform. Quince's prologue is mispunctuated into nonsense. Snout plays the wall with his fingers, Starveling plays Moonshine and gives up his lines under heckling, Snug reassures the ladies he is not in fact a lion. Pyramus (Bottom) finds Thisbe's bloody mantle and stabs himself. Thisbe (Flute) stabs herself in turn. Theseus, kindly, defends the players. The lovers retire. Oberon, Titania and the fairies bless the house. Puck closes alone, offering the play back to the audience as a dream.`,
      blurb: `The triple wedding feast at Theseus's palace. Hippolyta and Theseus debate the lovers' story; he dismisses it as fable, she finds it consistent enough to believe. The mechanicals stage Pyramus and Thisbe; the aristocrats laugh, and Theseus defends the players with grace. The fairies arrive to bless the house and the marriages. Puck closes the play alone with the famous epilogue, offering the entire performance back to the audience as a dream they had for two hours, and asking, gently, whether any of what they saw was real.`,
      summary: [
        `The duke's palace, after the weddings. Theseus and Hippolyta open Act V discussing what the lovers have told them about the wood. Theseus dismisses it — "I never may believe these antique fables" — and gives one of the play's most-quoted speeches: "the lunatic, the lover, and the poet are of imagination all compact." Hippolyta answers with weight: "all the story of the night told over... grows to something of great constancy." The story may be mad, but its consistency is hard to dismiss. The play does not arbitrate.`,
        `The three couples enter; Theseus picks "the most lamentable comedy and most cruel death of Pyramus and Thisbe" — "very tragical mirth," a contradiction he is amused by. Philostrate warns him the play is hopeless and the players sincere; Theseus answers with the gentlest defense of amateurs: "never anything can be amiss when simpleness and duty tender it." The mechanicals enter. Quince's prologue comes out as gibberish. Snout plays the wall with his fingers spread for a chink. Starveling plays Moonshine and gives up his lines under heckling. Pyramus (Bottom) finds Thisbe's bloody mantle and stabs himself; Thisbe (Flute) stabs herself in turn. Hippolyta finds it painful: "this is the silliest stuff that ever I heard." Theseus answers gently: "the best in this kind are but shadows; and the worst are no worse, if imagination amend them."`,
        `The lovers retire. The stage empty, Oberon, Titania, Puck and the fairies dance through the dark palace, singing a blessing on the house — the children conceived tonight free of harm; the fields lucky. They depart. Puck speaks the epilogue alone: "if we shadows have offended, think but this, and all is mended — that you have but slumbered here while these visions did appear." He offers the performance back to the audience as a dream, asks for their applause, and goes.`,
      ],
      appears: [{ id: 'theseus', name: 'Theseus' }, { id: 'hippolyta', name: 'Hippolyta' }, { id: 'lysander', name: 'Lysander' }, { id: 'hermia', name: 'Hermia' }, { id: 'demetrius', name: 'Demetrius' }, { id: 'helena', name: 'Helena' }, { id: 'bottom', name: 'Bottom' }, { id: 'quince', name: 'Quince' }, { id: 'flute', name: 'Flute' }, { id: 'snout', name: 'Snout' }, { id: 'snug', name: 'Snug' }, { id: 'starveling', name: 'Starveling' }, { id: 'oberon', name: 'Oberon' }, { id: 'titania', name: 'Titania' }, { id: 'puck', name: 'Puck' }],
      themes: [{ slug: 'theatre', label: 'Theatre' }, { slug: 'mechanicals', label: 'The mechanicals' }, { slug: 'dream', label: 'Dream and waking' }, { slug: 'love', label: 'Love' }],
    },
  ],
}
