// Niels Lyhne — SEO page data for build-seo-pages.cjs
// Jens Peter Jacobsen, 14 chapters.

module.exports = {
  id: 'niels-lyhne',
  title: 'Niels Lyhne',
  author: 'Jens Peter Jacobsen',
  byline: '1880 · Danish novel',
  titleAccent: 'a guided tour',
  hook: 'A Danish dreamer tries to live without God and never quite knows what to put in God\'s place. The novel follows him through every test the next thirty years can find, including the last one — a priest at his bedside, offered and refused.',
  themesBlurb: 'Atheism that does not console, the long arc of disillusionment, poetry as failure, women as horizon, Denmark as setting.',
  castBlurb: 'Lönborggaard, Copenhagen, Fjordby, Mariagerfjord, Riva',
  castDesc: 'A handful of houses, one inward life.',
  chapterLabel: n => `Kapitel ${toRoman(n)}`,
  genre: ['Psychological novel', 'Bildungsroman', 'Scandinavian fiction'],

  about: [
    `<em>Niels Lyhne</em> is the story of a Danish dreamer who tries to live without God and never quite knows what to put in God\'s place. Jens Peter Jacobsen wrote it slowly, over six years, while dying of tuberculosis. He had trained as a botanist and translated Darwin into Danish before turning to fiction. The novel was published in Copenhagen in 1880, when he was thirty-three. He lived four more years. The book is short — about 250 pages — but covers a whole life in fourteen loosely linked chapters that move by emotional logic rather than incident.`,
    `Niels is born on a rural estate in 19th-century Jutland to a poetic, romantically miserable mother and a steady, prosaic father. From childhood he hovers between their two temperaments, drawn to poetry and inwardness. As a boy he watches his beautiful aunt Edele die calmly without faith, and the novel uses her death as the first anchor of his unbelief. As a young man in Copenhagen he loves the older Mrs. Boye, a worldly widow who treats him as a man for the first time. Years later he falls into a catastrophic affair with Fennimore, the wife of his closest friend. He marries the gentle Gerda late, and loses her, and loses their child, and finally enlists in the Second Schleswig War and is shot. The novel ends at his deathbed, where a priest is offered to him and he refuses.`,
    `It quietly reshaped European literature. Rilke read it as a young man and never stopped reading it; he carried it everywhere, called it one of the two books he could never be without, and recommended it to the young poet of the <em>Letters</em>. Stefan Zweig and Thomas Mann admired it; Freud wrote to Fliess that Jacobsen had struck him deeper than anything else he had read in years. It is the great Scandinavian novel about losing one\'s faith and trying to keep going.`,
  ],
  chaptersSubtitle: 'All 14 chapters — a whole life, from the parents\' marriage to the bedside refusal.',
  chaptersLead: `<p>The novel moves in fourteen chapters, each one a movement in the long disillusionment. Chapters I–II open at Lönborggaard with Bartholine\'s marriage and Niels\'s birth, the two parents pulling at the boy from opposite directions. Chapters III–IV bring the tutor Bigum, the arrival of the beautiful Edele, and her calm death without faith — the moment Niels\'s atheism is born. Chapters V–IX move through Copenhagen: Erik\'s arrival, Mrs. Boye\'s salon, Niels\'s public declaration of unbelief, the affair with Boye, the death of his mother at Lake Garda, and the Christmas Eve dialogue with Hjerrild. Chapters X–XI deliver the catastrophe at Mariagerfjord: Erik\'s marriage to Fennimore, Niels\'s affair with her, Erik\'s sudden death, Fennimore\'s denunciation. Chapters XII–XIV bring the late marriage to Gerda at Lönborggaard, the death of their son, Niels\'s prayer in extremity, the war, and the deathbed refusal of the priest.</p>`,
  themesByline: 'Five threads through the novel',
  themesLead: `<em>Niels Lyhne</em> looks like a long sigh and is in fact an argument. Five threads run through it. They concern an atheism that does not console its holder, a long arc of disillusionment that never quite resolves, a poetic vocation that fails to arrive, a series of women each of whom is a different kind of loss, and a Denmark of country house and manor and war that holds the whole story. None of these threads are decoration. The novel is built on them.`,

  groups: [
    { label: 'Lönborggaard · Chapters I–IV', subtitle: 'The parents, the boy, the tutor, the aunt who dies without God.', chapters: [1, 2, 3, 4] },
    { label: 'Copenhagen · Chapters V–IX', subtitle: 'Erik, Mrs. Boye, the declaration, the mother\'s death, Hjerrild on Christmas Eve.', chapters: [5, 6, 7, 8, 9] },
    { label: 'Mariagerfjord · Chapters X–XI', subtitle: 'Erik married to Fennimore, the affair, the accident, the denunciation.', chapters: [10, 11] },
    { label: 'Lönborggaard, again · Chapters XII–XIV', subtitle: 'Riva, Gerda, the dying child, the war, the priest refused.', chapters: [12, 13, 14] },
  ],

  themes: [
    {
      slug: 'atheism',
      title: 'The atheism that does not console',
      greek: 'unbelief without consolation',
      preview: 'Niels casts off God after watching Edele die calmly without faith, and the novel follows him through every test the next thirty years can find. He refuses each time, including at the end, when a priest is brought to his bedside and he sends the priest away. Jacobsen does not present this refusal as triumph.',
      essay: [
        `<em>Niels Lyhne</em> is one of the first novels in European literature to take the lived consequences of unbelief with full seriousness. Niels casts off God in adolescence after watching his aunt Edele die calmly without faith — calmly, in particular, against the village pastor\'s patient, well-meaning, almost loving offers of consolation. Edele\'s refusal is not bitter. She has, simply, no use for the comfort she is being offered, and she dies in possession of herself. The boy who watches her die takes from the bedside a conviction the rest of the novel cannot dislodge: that the consolations of faith are addressed to a fear he refuses to flatter.`,
        `The novel then spends thirty years putting the position under pressure. First love disappoints; a great romance ends in the other person\'s dignified retreat; an affair with a friend\'s wife becomes the chapter the book cannot recover from; a marriage to a gentle, religious woman ends in her own loss of faith on her deathbed. Each loss is offered to Niels as an occasion to recant. The most exposed test is in chapter XIII, when Niels\'s small son lies dying. Niels — secular, modern, twenty years past Edele\'s deathbed — finds himself praying. He prays not because he has changed his mind about God but because he is a father with a dying child and there is nothing else to do with the hands. The child dies anyway. Niels gets up from beside the bed and never prays again. The chapter is the novel at its most exact: the prayer was real and the answer was real, and the answer was nothing.`,
        `The final test arrives in the last chapter. Niels has enlisted in the Second Schleswig War of 1864 — partly out of patriotism, partly out of the long ache to do something he cannot live inside his head. He is shot, lingers, and is offered the priest. He refuses. Jacobsen does not present the refusal as triumph. The novel\'s last paragraphs are sober almost to the point of plainness. The hardest thing about losing God, the book insists, is not the metaphysics but what it does to ordinary moments — the bedside of a sick child, the letter to a grieving mother, the temptation to comfort yourself with a prayer you no longer believe. Few books since 1880 have measured the cost more honestly.`,
      ],
      where: [
        { n: 4, label: 'Chapter IV (Edele dies without faith)' },
        { n: 13, label: 'Chapter XIII (Niels prays for his son)' },
        { n: 14, label: 'Chapter XIV (the priest refused)' },
      ],
    },
    {
      slug: 'disillusionment',
      title: 'The long arc of disillusionment',
      greek: 'every successive love ends',
      preview: 'Niels stakes his life on the proposition that beauty, feeling, dreams, and poetry can stand in for what religion used to provide. The novel respects the bet. And then, with the patience of a man who has been watching his own death approach for years, Jacobsen tests the bet against everything that actually breaks a person.',
      essay: [
        `Niels stakes his life on the proposition that beauty, feeling, dreams, and the poetic temperament can stand in for what religion used to provide — that an inner life, vivid enough, can ground a meaningful existence even without a heaven beyond it. The novel respects the bet. Jacobsen gives Niels a real talent, real loves, real moments of nearly mystical perception in landscape and music and the shape of a face at evening. The first half of the book is, in places, almost lyric in the German Romantic key — the boy on the heath, the young man in the city, the long Italian journey with his dying mother to the Lake Garda she had imagined for forty years.`,
        `And then, with the patience of a man who has been watching his own death approach for years, Jacobsen tests the bet against everything that actually breaks a person. Mrs. Boye, the older Copenhagen widow who treats him as a man for the first time, sees clearly that he is not the partner she needs and lets him go; she marries someone else and Niels learns the news in a newspaper. The friendship with Erik, which has carried him since the university years, ends in his sleeping with Erik\'s wife and Erik\'s death by accident a few weeks later. The marriage to Gerda, late and almost saved, ends with her losing her faith on her deathbed and dying frightened, and with their son dying a year later in his arms.`,
        `The novel does not declare the bet a failure. It shows what living inside it looks like in long stretches. The aphorism Jacobsen never quite writes but earns is that disillusionment is not a single event but a temperature — a slow cooling of the air around an inner life that had once been warm enough to live in. By the deathbed in chapter XIV, Niels has lost almost everything an inner life can lose, and he refuses to take any of it back on terms he no longer believes. Whether romantic feeling can substitute for religion is a question every secular adult since 1880 has had to answer for themselves. Jacobsen is one of the first writers to ask it cleanly.`,
      ],
      where: [
        { n: 8, label: 'Chapter VIII (Niels and Mrs. Boye end; mother dies at Clarens)' },
        { n: 11, label: 'Chapter XI (Erik dies, Fennimore turns)' },
        { n: 13, label: 'Chapter XIII (Gerda and the son)' },
      ],
    },
    {
      slug: 'poetry',
      title: 'Poetry as failure',
      greek: 'the poet who never arrives',
      preview: 'Niels is a man who lives mostly inside his own head. He plans a poet\'s life, drafts speeches he will never deliver, falls in love with women he then watches in his imagination instead of meeting in the room. The novel is the ancestor of every later fiction about the over-examined inner life.',
      essay: [
        `Niels is a man who lives mostly inside his own head. From the first chapters at Lönborggaard he plans a poet\'s life: he drafts speeches he will never deliver, conducts entire affairs in his imagination before the real woman has done anything, and falls in love with the version of a person he has built in private rather than with the person standing in the room. The novel is exact about the texture of this kind of inwardness — its luminosity and its paralysis, the way it produces beautiful private worlds and makes ordinary action feel slightly false.`,
        `Around him everyone else simply does things. Erik sculpts; Mrs. Boye gives parties and reads books and changes her mind in public; Fennimore takes a lover; Hjerrild argues; the war breaks out and men enlist; Gerda runs a household and prays. Niels, almost alone in the cast, is mostly imagining. He produces no book the world ever sees. He never quite arrives at the poet\'s life he had been preparing for since boyhood. The closest the novel comes to a definition of his trouble is in the early Copenhagen chapters, where his friends are visibly busy at lives and he is visibly busy at the picture of one. Jacobsen, who had himself been a botanist and translator before he was a novelist, writes from the inside of this temperament without pretending it is a virtue.`,
        `The failure is not loud. There is no climactic scene of a manuscript thrown in a fire, no public disgrace at a reading, no rival who gets the laurels Niels deserved. The poet\'s life simply does not arrive. He grows older. He marries. The years pass and the work does not get written. By the time the war comes in chapter XIV, the question of whether Niels would have been a poet has lost its meaning; it has been replaced by the question of how to die. The novel is the ancestor of every later fiction about the over-examined inner life — a fault line that runs through Rilke\'s Malte, through any number of contemporary biographies of unwritten books, and feeds, even now, much of what people read about themselves online.`,
      ],
      where: [
        { n: 3, label: 'Chapter III (Bigum, the boy\'s imagination)' },
        { n: 7, label: 'Chapter VII (the public declaration)' },
        { n: 12, label: 'Chapter XII (Riva, Madame Odéro)' },
      ],
    },
    {
      slug: 'women',
      title: 'Women as horizon',
      greek: 'each woman a different kind of loss',
      preview: 'Edele, Mrs. Boye, Fennimore, Gerda — each a different kind of loss. The novel keeps placing women at the edge of Niels\'s life as figures of possibility, and each time the possibility closes. The pattern is part of what the book is saying about him.',
      essay: [
        `Four women set the limits of Niels\'s adult life, and each one is a different kind of loss. The first is Edele, his young aunt, who dies without faith when Niels is a boy and gives him both the position he will hold for the rest of his life and the standard against which he will measure every later test of it. She is, in the novel\'s economy, the only woman whose dignity in extremity Niels never sees damaged. Everyone after her will be measured against her bedside.`,
        `The second is Mrs. Boye — older, witty, worldly, a Copenhagen widow who treats him as a man for the first time and conducts an affair with him that he is too young to understand. She is the figure who gives Niels his apprenticeship in the modern attitudes: the freedom to argue about books, the freedom to think of women as people, the freedom not to apologize for a private life. She also sees, before he does, that he is not the partner she needs. She marries another man, and he learns it from a newspaper. The relationship leaves him more complicated than it found him, which is exactly what such relationships are for in a novel of this kind.`,
        `The third is Fennimore, his friend Erik\'s wife. The novel\'s most devastating relationship: Niels visits Erik, who has stopped working and started drinking, and Fennimore, who is lonely and bitter, falls into an affair with Niels almost without deciding to. When Erik dies suddenly in an accident on the road home, the affair collapses under what they have both done. Fennimore turns on Niels in a scene of fury the novel takes seriously and never quite forgives. It is the chapter the book never recovers from. The fourth is Gerda, the gentle, religious young woman Niels marries late after years of drifting. She and Niels have a son. She loses her faith on her deathbed and dies frightened; their son dies soon after. Niels sits with each of them through their last hours — the test the novel has been preparing for him since Edele. What he does and does not do at those bedsides is the moral center of the second half of the book. Jacobsen is not building a thesis about women; he is showing what an inwardly lived man does with the people who get close to him, and how each of them, in turn, slips past the horizon he had hoped they would furnish.`,
      ],
      where: [
        { n: 4, label: 'Chapter IV (Edele dies)' },
        { n: 11, label: 'Chapter XI (Fennimore\'s denunciation)' },
        { n: 13, label: 'Chapter XIII (Gerda and the son)' },
      ],
    },
    {
      slug: 'denmark',
      title: 'Denmark as setting',
      greek: 'country house, manor, war',
      preview: 'Lönborggaard at the start, Copenhagen in the middle years, the manor at Mariagerfjord, the war of 1864 at the end. The novel is set in a particular country at a particular moment, and the country itself does some of the work the plot does not.',
      essay: [
        `<em>Niels Lyhne</em> is set in a particular country at a particular moment, and the country itself does some of the work the plot does not. Lönborggaard, the country estate where Niels is born, is the first setting and the last; the novel begins there with his parents\' courtship and returns there in chapter XII when, after the catastrophe at Mariagerfjord and the wandering at Riva, Niels comes home an older man. The estate is the still point of an otherwise drifting life — the place the boy\'s imagination is shaped, the place the man returns to die.`,
        `Between the two stays at Lönborggaard the novel moves through the Denmark of Jacobsen\'s own youth. Copenhagen in the middle chapters is a city of student rooms and salons, of editors and minor poets and Mrs. Boye\'s drawing room, of Christmas Eve arguments about God with men like Hjerrild, of the long Italian journey by way of Hamburg and the Alps. The Mariagerfjord chapters take Niels to a manor in north Jutland — the wide brown fjord, the heath, the small village with its parsonage and its road — where he visits Erik and Fennimore and where the catastrophe of chapter XI happens almost in the way an accident on a country road happens, suddenly and out of weather.`,
        `And the novel ends in a war: the Second Schleswig War of 1864, in which Denmark lost a third of its territory to Prussia and Austria and which marked the country, in a way it still has not quite recovered from, with the conviction that history is something that happens to small nations from outside. Niels enlists in part because the war makes the inwardly lived life feel finally insufficient, and he is shot in a minor engagement and dies of his wound. Jacobsen, who was twenty in 1864, writes the war chapter without rhetoric; the country has lost, the men come home with nothing, and Niels dies in a field hospital with a priest at the door and a refusal on his lips. Denmark, as a place and as a defeated nation, is the frame the inward life is finally finished inside.`,
      ],
      where: [
        { n: 1, label: 'Chapter I (Lönborggaard, the marriage)' },
        { n: 6, label: 'Chapter VI (Mrs. Boye\'s Copenhagen)' },
        { n: 14, label: 'Chapter XIV (the war, the deathbed)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Niels Lyhne', role: 'The dreamer', body: `The son of a poetic mother, Bartholine, and a steady, prosaic father. He grows up reciting his mother\'s verses and watching his aunt Edele die without faith. He moves to Copenhagen, studies vaguely, falls in love repeatedly, becomes an atheist on principle, marries late, loses his wife and child, and enlists in the war of 1864. He spends most of his life inside his own head. The novel measures, patiently, what that costs him and the people who love him.` },
    { name: 'Bartholine Lyhne', role: 'The mother', body: `Niels\'s mother. She married a steady country gentleman believing he would carry her into the world of poetry she dreamed about, and discovered he had no such intention. She lives most of her life inside the books she reads and the verses she recites to her son. She is the source of Niels\'s inwardness and the first warning the novel gives about it. Her late trip with him to Lake Garda, where she finally sees the Italy she had imagined for forty years and dies at Clarens shortly after, is one of the book\'s quietest scenes.` },
    { name: 'Edele', role: 'The aunt who dies without God', body: `Niels\'s young aunt, his father\'s sister. She comes to Lönborggaard from Copenhagen to recover her health and is courted ineffectually by the local pastor in the language of consolation. She dies without conceding any of it. Her calm refusal to accept the pastor\'s offers is the moment Niels\'s atheism is born. She is on the page only briefly, but the novel returns to her again and again, as the standard against which Niels measures every later test of his unbelief.` },
    { name: 'Mrs. Boye', role: 'The widow', body: `An older Copenhagen widow, witty, worldly, and unattached. She takes Niels seriously as a man for the first time and conducts a relationship with him that he is too young to understand. She talks about books and Paris and the freedoms of married women. She eventually sees that he is not the partner she needs and lets him go; she marries another man, and Niels learns it in a newspaper. The relationship leaves him more complicated than it found him, which is exactly what such relationships are for in a novel of this kind.` },
    { name: 'Fennimore', role: 'The catastrophe', body: `Niels\'s friend Erik\'s wife. The novel\'s most devastating relationship: Niels visits Erik, who has stopped working and started drinking, and Fennimore, who is lonely and bitter, falls into an affair with Niels almost without deciding to. When Erik dies suddenly in an accident on the road home, the affair collapses under what they have both done. Fennimore turns on Niels with fury the novel takes seriously. It is the chapter the book never quite recovers from, and it is the one Niels does not.` },
    { name: 'Gerda', role: 'The late marriage', body: `The young woman Niels marries late, after years of drifting. She is gentle, religious, and unworldly. She and Niels have a son. She loses her faith on her deathbed and dies frightened. Their son dies soon after. Niels sits with each of them through their last hours — the test the novel has been preparing for him since Edele\'s death. What he does and does not do at those bedsides is the moral center of the second half of the book.` },
  ],

  castSubtitle: 'Across Lönborggaard, Copenhagen, Fjordby, Mariagerfjord, Riva, and the war.',
  castLead: `<p>Niels Lyhne has a small, deliberate cast spread across a country and a generation. The Lyhne household at Lönborggaard — father, mother, son, the tutor Bigum, the aunt Edele. The Copenhagen circle — Erik Refstrup, Mrs. Boye, the editor Hjerrild. The Mariagerfjord household where the catastrophe happens — Erik again, married now to Fennimore. The late marriage at Lönborggaard with Gerda and their son. And, at the very edge of the novel, the singer Madame Odéro at Riva, the figure who marks the lowest point of Niels\'s wandering. The novel\'s third-person voice keeps Niels at the center; the people around him are arranged according to the moral pressure each of them puts on him, not according to social rank.</p>`,
  castGroups: [
    {
      label: 'Lönborggaard',
      characters: [
        { id: 'niels', tag: 'Mortal', name: 'Niels Lyhne', epithet: 'The dreamer', body: `The son of Bartholine and Mr. Lyhne, raised at Lönborggaard in 19th-century Jutland. The novel is the story of his life from the years before his birth to the deathbed in the field hospital after the war of 1864. Plain in the world\'s sense, intensely inward, drawn to poetry and books and the imagined version of every person he loves. He becomes an atheist on the model of his aunt Edele. He spends most of his life inside his own head. Jacobsen measures, patiently, what that costs him and the people who love him.`, appears: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] },
        { id: 'bartholine', tag: 'Mortal', name: 'Bartholine Lyhne', epithet: 'The mother', body: `Niels\'s mother. The eldest daughter of the practical, prosperous Blid family, she grew up reading poems and dreaming of a world the Blids did not believe in. She married Mr. Lyhne believing he would carry her into the world of poetry she had imagined; she discovered he had no such intention. She lives most of her life inside her reading. The source of Niels\'s inwardness and the first warning the novel gives about it. Her late trip with him to Lake Garda, where she finally sees the Italy she had imagined for forty years and dies at Clarens shortly after, is one of the book\'s quietest scenes.`, appears: [1, 2, 3, 4, 8] },
        { id: 'mr-lyhne', tag: 'Mortal', name: 'Mr. Lyhne', epithet: 'The father', body: `Niels\'s father. A steady country gentleman of an old Jutland family, owner of the Lönborggaard estate. Once travelled in France and Germany and brought home tastes for engravings, German poetry, and French philosophy; once thought to be a poetic nature. By the time the novel begins, the appetite has gone out of him. He attends to his fields and the affairs of the parish with quiet competence and no enthusiasm. He loves his wife and his son in his own way, which is not Bartholine\'s way and not the boy\'s. The other side of the tug-of-war over Niels\'s temperament.`, appears: [1, 2, 3, 4] },
        { id: 'edele', tag: 'Mortal', name: 'Edele', epithet: 'The aunt who dies without God', body: `Mr. Lyhne\'s twenty-six-year-old sister, who arrives at Lönborggaard from Copenhagen in chapter III to recover her health. Beautiful, ironic, accustomed to the city, almost unbearably bored at the estate. The local pastor courts her in the language of religious consolation as her illness worsens. She refuses every offer with calm and good manners and dies in possession of herself. Her death is the first anchor of Niels\'s atheism — the moment, returned to throughout the novel, against which every later test of his unbelief is measured.`, appears: [3, 4] },
        { id: 'bigum', tag: 'Mortal', name: 'Bigum', epithet: 'The tutor', body: `The candidate for holy orders engaged as Niels\'s tutor when the boy is twelve. Almost forty, broad-chested, slightly deaf, devoted to philosophy and the violin. Convinced — privately, at first — that his intellect has a wider span than other people suspect, and that he is a genius the world has not yet noticed. The novel\'s portrait is gentle and unsparing at once; Bigum is the first adult Niels watches sustain a private grandiosity that the world does not confirm.`, appears: [3, 4] },
      ],
    },
    {
      label: 'Copenhagen',
      characters: [
        { id: 'erik', tag: 'Mortal', name: 'Erik Refstrup', epithet: 'The friend, the sculptor', body: `Niels\'s closest friend from the student years in Copenhagen. A sculptor of real promise, broad-shouldered and sociable, with the easy confidence Niels does not have. He brings Niels into Mrs. Boye\'s circle. Years later he marries Fennimore and takes her to a manor at Mariagerfjord, where his work falters and he begins to drink. He is killed in a road accident at the very moment the affair between Niels and Fennimore reaches its crisis. The novel does not let either Niels or Fennimore off the hook for what his death exposes.`, appears: [5, 6, 7, 10, 11] },
        { id: 'mrs-boye', tag: 'Mortal', name: 'Mrs. Boye', epithet: 'The widow', body: `An older Copenhagen widow, witty, worldly, unattached. The center of a small salon where students and minor poets and the better sort of editor argue about Heine and the freedoms of married women. She takes Niels seriously as a man for the first time and conducts a relationship with him that he is too young to understand. She eventually sees that he is not the partner she needs and lets him go; she marries another man, a respectable one, and Niels learns it from a newspaper. The first of the women whose retreat the novel measures.`, appears: [6, 7, 8, 9] },
        { id: 'hjerrild', tag: 'Mortal', name: 'Hjerrild', epithet: 'The editor', body: `An editor and journalist in the Copenhagen circle around Mrs. Boye. The novel\'s most articulate voice on the question of unbelief — older than Niels, more cautious about declaring himself, attentive to the social cost of saying out loud what the new generation thinks in private. The Christmas Eve dialogue between him and Niels in chapter IX is one of the book\'s set pieces: Hjerrild defending a life lived without God but quietly, Niels insisting that the position must be held in public if it is to be held at all.`, appears: [7, 9] },
      ],
    },
    {
      label: 'Mariagerfjord',
      characters: [
        { id: 'fennimore', tag: 'Mortal', name: 'Fennimore', epithet: 'Erik\'s wife', body: `Erik\'s wife. Niels first sees her in chapter X when he comes to visit them at the Mariagerfjord manor — younger than he expected, lonely in the country, watching her husband stop working and start drinking. The affair between her and Niels begins almost without a decision; it lasts only a few weeks. When Erik is killed in a road accident, Fennimore turns on Niels in a scene of fury the novel takes seriously. The chapter is the book\'s catastrophe. She does not appear again, but Niels carries her denunciation with him for the rest of the novel.`, appears: [10, 11] },
      ],
    },
    {
      label: 'Riva',
      characters: [
        { id: 'madame-odero', tag: 'Mortal', name: 'Madame Odéro', epithet: 'The singer at Riva', body: `An opera singer, encountered by Niels at Riva on Lake Garda during the wandering year that follows the catastrophe at Mariagerfjord. Famous, older, recovering her voice after illness. The novel does not give them a love affair so much as a long, exhausted attentiveness across café tables and lake walks. She is the figure of the lowest point of Niels\'s drift — the moment when nothing is moving forward and the inward life is at its quietest. She returns to her stage; he goes home.`, appears: [12] },
      ],
    },
    {
      label: 'Lönborggaard, again',
      characters: [
        { id: 'gerda', tag: 'Mortal', name: 'Gerda', epithet: 'The wife', body: `The young woman Niels marries late at Lönborggaard, after years of drifting. Gentle, religious, unworldly, the daughter of a neighboring family. She and Niels have a son. She loses her faith on her deathbed and dies frightened, in a scene the novel writes with terrible patience. Their son dies soon after. The test the novel has been preparing for Niels since Edele — the bedside of a believer who can no longer believe — and one he meets without consolation to offer.`, appears: [13] },
        { id: 'son', tag: 'Mortal', name: 'The son', epithet: 'The child', body: `Niels and Gerda\'s small son, born late in the marriage. Healthy at first, then suddenly ill, then dying. The chapter in which Niels prays for him — secular, modern, twenty years past Edele\'s deathbed, a father with a dying child and nothing else to do with the hands — is the novel at its most exact. The child dies anyway. Niels gets up from beside the bed and never prays again.`, appears: [13] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Chapter I — Bartholine and her marriage', tourTitle: 'Bartholine\'s marriage', hook: 'A poetry-reading girl in a practical Jutland family marries the young squire of Lönborggaard expecting a poet\'s life. The novel\'s first chapter is the long quiet disillusionment of that bet.',
      tour: `Bartholine is the eldest daughter of the Blid family — practical, prosperous, devout in the lukewarm way of country people. She is not of their kind. She lives on poems, dreams them, and trusts them above everything else in the world. When Lyhne of Lönborggaard, the young squire of the neighboring estate, comes courting, she falls in love at once: here at last, she thinks, is a man from the great outside world. They are married. The first year is romance; then his appetite for it is exhausted, and hers turns into doubt. By the end of the chapter they are estranged inside the same house, and Bartholine has brought a son into the world. They call him Niels.`,
      blurb: `Bartholine Blid lives on poems and trusts them above the world she actually lives in. The young squire Lyhne courts her; she takes him for the poetic nature he half is and they marry. The first year passes like the courtship. Then his appetite for romance gives out. By the end of the chapter they are estranged inside the same house and a son has been born. They call him Niels.`,
      summary: [
        `The chapter opens on the Blid family in their Jutland farmhouse. They are practical people. They do their work, sleep their sleep, take the Lord\'s Supper twice a year, and never expect anything from the world beyond the harvest home and three or four Christmas parties. Bartholine, the eldest daughter, is not of their kind. She has the dark luminous eyes of the family and the firm chin, but her cheek is pale and her voice is languid; she lives on poems. They teem with new ideas and profound truths about life in the great outside world, where grief is black and joy is red. They are full of girls who are noble and beautiful and never know it. Why might she not be such a girl herself? She is consumed with longing for the other and richer self the poets describe and forgets — what is so easily forgotten — that even the fairest dreams do not add an inch to the stature of the human soul.`,
        `Young Lyhne of Lönborggaard, a few miles away, comes courting. He is the last male descendant of a family that has for three generations served king and country with diligence and honor; he has travelled in France and Germany; he reads German poetry and French philosophy. The intelligence of his line has gone a little weary in him, but to Bartholine he arrives as the man from the great outside world she has been waiting for. He talks about painters and poets, reads her their work in the garden and on the hill above the fjord; love makes him poetic. She is happy. Her love lets her dissolve the twenty-four hours of the day into a string of romantic episodes. They are married.`,
        `The first year passes like the courtship. Then Lyhne can no longer hide from himself that he is weary of always having to find new expressions for his love. He has given her everything he had and now is expected to go on giving. Bartholine is no longer inexperienced in life or in books. They sink into estrangement inside the same house — she into ardent attempts to recover what she calls the romance of their early days, he into the country gentleman\'s steady absorption in his land. By the time their first child is born they have understood, separately, that the marriage is what marriages mostly are. The chapter closes on the cradle. They call the boy Niels.`,
      ],
      appears: [{ id: 'bartholine', name: 'Bartholine' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }, { id: 'niels', name: 'Niels (born)' }],
      themes: [{ slug: 'disillusionment', label: 'Disillusionment' }, { slug: 'denmark', label: 'Denmark' }],
    },
    {
      n: 2, title: 'Chapter II — Niels\'s birth, the parents\' tug-of-war', tourTitle: 'Tug-of-war', hook: 'The boy grows up between two temperaments. His mother feeds him heroes and verses; his father teaches him the steady weight of the commonplace. The chapter is the long quiet establishment of Niels\'s inward life.',
      tour: `In a way the child has brought the parents back together — over his cradle they meet in a common hope. But they are still far apart, and as Niels grows older the difference between them becomes the weather of his childhood. Bartholine reaches him through the imagination, telling him stories of heroes and a stillborn second son she has imagined into a paragon. Lyhne reaches him through the matter-of-fact: the fields, the parish, the slow rhythm of the seasons. Niels feels at home with both at different hours and ashamed of the alternation. The chapter closes on a boy who already understands, without being able to say so, that he lives between two temperaments and has not yet chosen.`,
      blurb: `The cradle has brought the parents into a brief truce, but they are still far apart, and the boy grows up between them. Bartholine reaches Niels through stories of heroes and the imagined life of a stillborn second son. Lyhne reaches him through fields and parish and the steady weight of the commonplace. Niels feels at home with both at different hours, and ashamed of the alternation.`,
      summary: [
        `In a way, the child has brought the parents back together. Over the cradle they meet in a common hope, a common joy, a common fear. But they are still far apart. Lyhne is absorbed in his farming and the affairs of the parish; he gives scrupulous attention to the existing order of things and acts only on the deliberate recommendations of his old head servant or the elders of the parish. Bartholine continues to live in the books she reads. She voices her grief, by turns, in the broad generalities of her favorite poets — sometimes in lofty indignation against the dungeons of tyrants, sometimes in calm pitying sorrow for a generation cowed by the soulless bustle of the day, sometimes only as a gentle sigh for the freedom of the bird in flight.`,
        `As the child grows, the struggle for him grows more intense and is waged with a wider variety of weapons. Bartholine reaches Niels through the imagination. She tells him stories. She describes the woeful plight of the hero until the boy can see no way out, and more than once he presses his cheek against hers and whispers, with eyes full of tears, "But it isn\'t really true?" When she runs out of fairy stories she begins to tell him about the heroes of war and peace, choosing those who lend themselves to a moral about the power that dwells in a single soul that wills one thing only. A few years after Niels was born she had brought a stillborn second son into the world, and from him she has built a phantom paragon — Promethean longings, Messianic courage — whose imagined life she serves up to Niels as a model.`,
        `The boy is not deceived. He understands that to be like ordinary people is contemptible and that he is expected to be a hero. He accepts the assignment in his imagination. But on weary days he feels the assignment as a fraud: he suspects himself of caring only for the petty, of belonging in his secret heart to the rabble that would gladly stone the heroes. On those days he shuns his mother and seeks out his father — the steady fields, the matter-of-fact talk, the absence of any expectation that the boy be exalted. He feels at home there too. The chapter closes on a child who already understands, without being able to say so, that he lives between two temperaments and has not chosen between them. The novel will not, in the end, ask him to choose; it will let the consequences of not choosing be his life.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'bartholine', name: 'Bartholine' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }],
      themes: [{ slug: 'poetry', label: 'Poetry' }, { slug: 'disillusionment', label: 'Disillusionment' }],
    },
    {
      n: 3, title: 'Chapter III — Bigum, the arrival of Edele', tourTitle: 'Bigum and Edele', hook: 'Niels is twelve. A new tutor arrives — Bigum, deaf, philosophical, secretly convinced he is a genius the world has not noticed. And from Copenhagen comes Edele, Lyhne\'s sister, ill and bored and too elegant for the country. The two figures who will shape him next.',
      tour: `Niels is twelve. He has outgrown the games of his early childhood and begun to read; he and Frithjof, the pastor\'s son, walk arm in arm telling stories no book has bothered to write. Two new figures arrive at Lönborggaard within the same month. The first is Mr. Bigum, the new tutor — a candidate for holy orders, slightly deaf, devoted to philosophy and the violin, secretly convinced his intellect is wider than that of other men. The second is Edele Lyhne, Lyhne\'s twenty-six-year-old sister, sent home from Copenhagen on doctor\'s orders for her lungs. She arrives bored, elegant, contemptuous of the country. The chapter is the long, careful introduction of the two minds that will shape Niels\'s next years.`,
      blurb: `Niels is twelve and reading, walking the road with the pastor\'s son Frithjof telling stories the books will not bother with. Two new figures arrive at the estate. Bigum, the new tutor: deaf, philosophical, secretly a genius. Edele, his father\'s sister: home from Copenhagen with weak lungs, bored, elegant, contemptuous of the country. The chapter is their long careful arrival.`,
      summary: [
        `The years have passed. The world is no longer the realm of wonder it had been. The dim recesses behind the elder bushes, the haunted attic rooms, the gloomy stone passage under the Klastrup road — none of it lurks there any longer. Niels and Frithjof, the pastor\'s son, have grown out of the games where a barrel hoop was a ship and a stable door was England. Niels is twelve, nearly thirteen, and a book and a corner of the sofa are enough for him now. When the book will not bear him to the shores of his longing, he hunts up Frithjof and tells him the tale the book would not yield. Their stories grow into a single long story that never ends, lives and dies with one generation after another, and folds in everything Niels reads or sees or admires or knows he ought to admire.`,
        `About a month after Niels\'s twelfth birthday, two new faces appear at Lönborggaard. The first is the new tutor, Mr. Bigum, a candidate for holy orders standing at the threshold of his forties. He is small but with the stocky strength of a work-horse, slightly stooping, his eyeballs betraying that he is slightly deaf. He loves music and plays his violin with passionate devotion. Above all he is a philosopher — not one of the productive kind, who builds systems, but one who privately believes his intellect is wider than any other man\'s and who takes a curious pleasure in the world\'s failure to notice. He has been given a non on his examination for a degree. Oh, there is rapture in feeling the brutal stupidity of an existence that tosses him aside as poor chaff while he knows in his own mind that his lightest thought is worth a world.`,
        `The second newcomer is Edele Lyhne, Lyhne\'s twenty-six-year-old sister. She has lived for years in Copenhagen with a wealthy uncle, in a whirl of balls and festivities; she has been admired everywhere and envied as faithfully. Her health has given way, the doctors have prescribed fresh air and milk, and she has been sent home. She finds Lönborggaard insufferable — the mealtimes regulated by the sun, the smell of lavender in the cupboards, the Spartan chairs, the very air. There is no one she can talk to; not one of them catches the precise shade of meaning that is the essence of what she says. And to be called Aunt Edele — how it grates. The chapter closes on a Sunday in early August: Niels has forgotten to gather the cornflowers Edele asked for and runs up to the house with them in the afternoon, and the long, half-worshipful attention the boy will pay her over the next chapter is already in motion.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'bigum', name: 'Bigum' }, { id: 'edele', name: 'Edele' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }, { id: 'bartholine', name: 'Bartholine' }],
      themes: [{ slug: 'poetry', label: 'Poetry' }, { slug: 'denmark', label: 'Denmark' }],
    },
    {
      n: 4, title: 'Chapter IV — Edele\'s death, Niels\'s atheism', tourTitle: 'Edele dies', hook: 'The pastor courts Edele in the language of religious consolation. She refuses every offer with calm and good manners and dies in possession of herself. The boy at the bedside takes a position he will hold for the rest of his life.',
      tour: `Edele\'s health does not improve at Lönborggaard. The local pastor, a kindly man, begins to visit her with the gentle persistence of a clergyman who senses death approaching a soul he believes himself responsible for. He offers her, by stages, the consolations of faith. She receives each one with calm and refuses it. She does not argue. She does not soften. She dies in possession of herself, on her own terms, with no concession made and no unhappiness shown. Niels is at the bedside in the way a boy of twelve is at the bedside of a beautiful aunt he has half worshipped from a distance, and what he takes from the room is the conviction that the consolations of faith are addressed to a fear he refuses to flatter. His atheism begins here. The novel will return to this room again and again across thirty years.`,
      blurb: `Edele\'s lungs do not heal. The pastor begins to visit her, offering the consolations of faith with gentle persistence. She refuses each one with calm and good manners and dies in possession of herself. Niels is at the bedside. He takes from the room the conviction that the consolations of faith are addressed to a fear he refuses to flatter. The atheism that will define his life begins here.`,
      summary: [
        `The summer of Niels\'s twelfth year goes by; Edele does not recover. By autumn it is clear to the household that she will not. The pastor of the parish — a decent, well-meaning man, a friend of the family — begins to come more often and to stay longer. He brings the consolations of his office in the only form he knows: gently, by stages, in the language of an old faith he himself relies on. He sits by her bed and reads. He offers prayers. He asks, eventually, the questions that clergymen ask of the dying. Edele receives him with the courtesy of a Copenhagen drawing-room. She does not argue with him. She does not, in her last weeks, become the figure of religious recovery the pastor is hoping for. She thanks him. She refuses what he is offering. She does it without bitterness and without softening; she does it as a person who has long since arranged her interior on lines that do not require what he has come to give.`,
        `She dies. The chapter is restrained about the death itself; what it shows is the texture of those final weeks — the pastor\'s patience, Edele\'s self-possession, the family\'s helpless attendance, and the boy at the edge of the room. Niels is twelve and has loved her in the way a boy loves a beautiful older woman who arrives like weather and treats him as if he might one day be a man. He has watched the pastor visit. He has watched her receive him. He has watched her, at the end, decline a god she does not believe in. She does not lecture him on the position. She holds it.`,
        `The novel does not give Niels a speech in this chapter. It gives him a position. From this bedside forward he is what the rest of the book will call him — a man without God. He has not arrived at the position by reading; he has arrived at it by watching a person he loved die well without it. This is the hinge the rest of the novel turns on. Every later test of Niels\'s atheism — the affair, the friend\'s death, the prayer for his son, the priest at his own bedside thirty-odd years later — is being measured against the room he is leaving at the end of this chapter. The novel will not give him another anchor as steady. It does not need to.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'edele', name: 'Edele' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }, { id: 'bartholine', name: 'Bartholine' }, { id: 'bigum', name: 'Bigum' }],
      themes: [{ slug: 'atheism', label: 'Atheism' }, { slug: 'women', label: 'Women' }],
    },
    {
      n: 5, title: 'Chapter V — Erik comes', tourTitle: 'Erik arrives', hook: 'A cousin\'s son comes to live at Lönborggaard. Erik Refstrup — broad-shouldered, easy with the world, going to be a sculptor. The friendship that will carry Niels through his twenties begins.',
      tour: `Some years after Edele\'s death, a cousin\'s son comes to live at Lönborggaard. Erik Refstrup is a few years older than Niels — broad-shouldered, easy in the world, with the kind of confidence Niels does not have and watches with admiration. He intends to be a sculptor. He brings into the quiet house a different temperament from the one Niels has grown up between: not dreamy like his mother, not steady like his father, but sociable, ambitious, bodily, ready. The two boys become close in the way boys do when one has what the other lacks. The friendship will carry Niels through his student years in Copenhagen and through the catastrophe at Mariagerfjord.`,
      blurb: `A few years after Edele\'s death, Erik Refstrup — a cousin\'s son, broad-shouldered, sociable, intending to be a sculptor — comes to live at Lönborggaard. He has the easy confidence Niels does not have, and Niels watches him with admiration. The friendship that will carry Niels through his twenties and through the catastrophe at Mariagerfjord begins.`,
      summary: [
        `Time passes at Lönborggaard. Edele has been buried; Niels is older; the household has folded the loss into its life in the manner of households. Bigum still teaches. Niels still reads. Frithjof, the pastor\'s son, has begun to drift toward his own future. The house is as quiet as country houses are when nothing in particular is happening, and the chapter opens in that quiet.`,
        `Into it arrives Erik Refstrup. He is the son of a cousin of Lyhne\'s — a young man a few years older than Niels, whose family has decided he should spend a stretch of months in the country before settling into his life. He is to be a sculptor. He has trained a little in Copenhagen and is to train more. He is broad-shouldered, easy with strangers, easy with his own body, easy with girls; he laughs out loud at things Niels would think about silently for a week. The novel does not over-praise him. It registers, plainly, the temperament Niels has not been given.`,
        `The two become friends. Erik, who has the social gift, draws Niels out; Niels, who has the inward gift, gives Erik something to listen to in the long evenings when there is nothing else to do at Lönborggaard. They walk on the heath. They argue about books. They make plans for Copenhagen, where each of them will go, in his own time, to study what he is going to study. The friendship is the chapter\'s gift to Niels and, unknown to him, the long fuse the novel is laying. The chapter ends with Erik\'s departure and the promise — more vivid in Niels\'s mind than in his — that they will meet again in the city.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'erik', name: 'Erik Refstrup' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }, { id: 'bartholine', name: 'Bartholine' }],
      themes: [{ slug: 'denmark', label: 'Denmark' }, { slug: 'poetry', label: 'Poetry' }],
    },
    {
      n: 6, title: 'Chapter VI — Mrs. Boye in Copenhagen', tourTitle: 'Mrs. Boye\'s salon', hook: 'Niels is in Copenhagen as a student. Erik takes him to the salon of an older widow — Mrs. Boye, witty, unattached, modern. She talks about Heine and the freedoms of married women. Niels, twenty, is given his apprenticeship in the world.',
      tour: `Niels is now in Copenhagen as a student — vaguely enrolled, more vaguely attending lectures, mostly reading on his own. Erik, ahead of him in the city, takes him one evening to the salon of an older widow named Mrs. Boye. She is witty, unattached, modern; her drawing room is the meeting place of students and minor poets and the better sort of editor. She talks about Heine and the freedoms of married women. Niels, twenty, is given his apprenticeship in the world. The chapter is the long, careful introduction of the woman who will become his first real love and his first real loss.`,
      blurb: `Niels is in Copenhagen, vaguely a student, mostly a reader. Erik takes him to the salon of an older widow. Mrs. Boye is witty, unattached, modern; her drawing room argues about Heine and the freedoms of married women. Niels, twenty, gets his apprenticeship in the world from her. The woman who will be his first real love is being introduced.`,
      summary: [
        `Niels has been a student in Copenhagen for a season. The novel is candid about how vague the studentship is. He attends lectures occasionally, reads more on his own than the curriculum requires, walks the city in the evenings, lives in a furnished room that he changes once or twice as the rents change. He is twenty. He has come to the city expecting it to deliver him the life Bartholine\'s books had described, and the city has done, so far, neither more nor less than cities do for boys from the country.`,
        `Erik is ahead of him. He has been in the city longer, has begun his training as a sculptor, has met the people one meets in the studios and the cafés. One evening he takes Niels to the salon of a Mrs. Boye. She is older than they are — a widow in her thirties, perhaps, comfortably off, unattached, witty in the modern way. Her drawing room is the meeting place of a particular Copenhagen circle: students, minor poets, the better sort of editor, men and women who argue about Heine and Hegel and the freedoms of married women. The chapter sketches the room without sentimentality. It is not a glittering salon. It is the kind of room in which a young man from the country first hears the sentences he will spend the next ten years trying to think.`,
        `Mrs. Boye looks at Niels. She has, it is clear, looked at many young men brought into the room by their friends. She decides — the novel is exact about the moment without quite naming it — that this one is worth attending to. She speaks to him. She asks him what he reads. She listens to his answers in a way that flatters him without his quite noticing he is being flattered. By the end of the chapter Niels has been included; he will come back next week. The first of the relationships that will shape the novel\'s middle has been established, and he does not yet know what kind of relationship it will be.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'erik', name: 'Erik Refstrup' }, { id: 'mrs-boye', name: 'Mrs. Boye' }],
      themes: [{ slug: 'women', label: 'Women' }, { slug: 'denmark', label: 'Denmark' }],
    },
    {
      n: 7, title: 'Chapter VII — Niels declares for atheism', tourTitle: 'The declaration', hook: 'In Mrs. Boye\'s circle the talk turns to God. Niels, who has held his position since Edele\'s deathbed, declares it in public for the first time. The chapter is the moment his private faith becomes the position he will be known for.',
      tour: `In Mrs. Boye\'s circle the talk one evening turns to God. There are believers in the room and the half-believers who outnumber them in any nineteenth-century salon, and the conversation moves in the patient way of educated people who have agreed not to be rude about it. Niels speaks. He has held his position privately since the bedside of his aunt Edele eight years before; he declares it now in public for the first time. The chapter is small but pivotal: the position is no longer a secret he keeps but a position he is known for. The first cost of holding it begins.`,
      blurb: `In Mrs. Boye\'s drawing room one evening the conversation turns to God. The room has believers and half-believers. Niels, who has held his atheism privately since Edele\'s death, declares it in public for the first time. The chapter is small but pivotal. The position is no longer a secret. He will now be known for it.`,
      summary: [
        `An evening in Mrs. Boye\'s drawing room some weeks after Niels has been folded into the circle. The room is full. There is a young woman who has just published a translation; there is an editor; there are two students besides Erik and Niels; there is Hjerrild, the editor and journalist whose voice the novel will return to in chapter IX. They have been arguing about something cheerful — the German poets, the new theatre — and someone, in the way that someone always does, turns the conversation toward religion. The believers in the room — there are believers — speak first, in the patient way of educated people who have agreed not to be rude.`,
        `Niels speaks. He has been in the room for weeks without speaking on this subject; he speaks now. He has held his position privately since his aunt Edele\'s deathbed eight years before, and he says, plainly, that he does not believe in God. He says it without the posture of a young man trying to shock; the novel is careful about this. He says it as a position he has long held and is willing now to declare. He does not lecture; he does not perform. He answers the room\'s question with the answer the room had not actually expected.`,
        `The conversation goes on. Mrs. Boye, who has more experience of these declarations than the young men in the room, redirects the talk before it can go bad. Hjerrild looks at Niels with the long, careful look of an older man who has just identified a younger one. The chapter ends on the walk home, Niels and Erik together, Erik teasing him a little and Niels — half pleased, half uneasy — registering that the position he has long held has now become the position he will be known for. The first cost of holding it has begun. The novel does not announce this. It records it.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'mrs-boye', name: 'Mrs. Boye' }, { id: 'erik', name: 'Erik Refstrup' }, { id: 'hjerrild', name: 'Hjerrild' }],
      themes: [{ slug: 'atheism', label: 'Atheism' }, { slug: 'poetry', label: 'Poetry' }],
    },
    {
      n: 8, title: 'Chapter VIII — The affair, the mother\'s death at Clarens', tourTitle: 'Mrs. Boye, Clarens', hook: 'Niels and Mrs. Boye become lovers. Then his mother\'s health gives way and he takes her south to the Italy she has dreamed of for forty years. She sees Lake Garda and dies at Clarens.',
      tour: `Niels and Mrs. Boye become lovers. The novel handles the affair as it handles everything: with patient particularity rather than scandal. They are happy in their way; she is the older partner; he is being formed by her without quite knowing it. Then word arrives from Lönborggaard that Bartholine\'s health is giving way, and Niels takes his mother south for the journey she has dreamed of since her girlhood — through Hamburg and the Alps to Italy. She sees Lake Garda. She is happy. She dies at Clarens. Niels comes back to Copenhagen to find his life with Mrs. Boye no longer quite the life it was.`,
      blurb: `Niels and Mrs. Boye become lovers; the affair runs through a Copenhagen winter with the particularity of all love affairs in this novel — happy in its way, asymmetrical, real. Then Niels\'s mother\'s health gives way and he takes her south to the Italy she has dreamed of for forty years. She sees Lake Garda. She is happy. She dies at Clarens.`,
      summary: [
        `The chapter opens on the affair. Niels and Mrs. Boye have become lovers; the novel does not stage the moment, it registers the consequence. They are happy in their way through a Copenhagen winter. He spends evenings in her rooms; he walks home through the snow at midnight; he discovers in himself the capacity to be loved and the parallel capacity to be quietly afraid of it. Mrs. Boye, older and more experienced, treats him with a kindness that is not condescension and a candor that is not cruelty. They both know the relationship is asymmetrical; both pretend, sometimes, that it is not. The chapter\'s first half is the only sustained passage of plain happiness Niels has in the book.`,
        `Then the letter from Lönborggaard. Bartholine\'s health, never robust, has given way; the doctors have recommended a milder climate. Niels travels home. He finds his mother smaller than he remembered, frighteningly tired, still — as ever — talking about the Italy of her girlhood\'s books. He proposes to take her there. Lyhne agrees. They go: by ship to Hamburg, by stages through Germany, across the Alps, down into the lake country of northern Italy. Bartholine, in the diligence and on the steamers, is happier than Niels has ever seen her. She sees Lake Garda. She walks under the cypresses she has read about for forty years. She smiles at her son in a way that, in the chapters before, she had only smiled at her books.`,
        `She dies at Clarens — Clarens on Lake Geneva, where they have come for the air. The death is gentle; she has, in a sense, completed her unfinished business with the world before it. Niels buries her. He travels home alone. He returns to Copenhagen older and less confident than he had left it. The affair with Mrs. Boye does not survive the year. She marries another man; he reads about it in a newspaper. The chapter\'s arc, end to end, is the slow loss of two of the women who had organized his life — the mother who had given him his inwardness and the lover who had given him his apprenticeship in the world.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'mrs-boye', name: 'Mrs. Boye' }, { id: 'bartholine', name: 'Bartholine' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }],
      themes: [{ slug: 'women', label: 'Women' }, { slug: 'disillusionment', label: 'Disillusionment' }],
    },
    {
      n: 9, title: 'Chapter IX — Hjerrild, Christmas Eve', tourTitle: 'Christmas Eve atheism', hook: 'Mrs. Boye has married another. Niels spends Christmas Eve with Hjerrild the editor. They argue across a long evening about whether unbelief should be held in private or declared. The novel\'s clearest dialogue on what atheism costs.',
      tour: `It is the Christmas after Niels\'s mother\'s death and Mrs. Boye\'s marriage to another man. Niels does not go home to Lönborggaard. He spends Christmas Eve in town with Hjerrild, the older editor he has known since Mrs. Boye\'s salon. The two of them sit late over a bottle and argue. Hjerrild defends a life lived without God but quietly — privately, courteously, without scandal. Niels insists that the position must be held in public if it is to be held at all. The chapter is the novel\'s clearest sustained dialogue on what atheism costs and how it should be borne.`,
      blurb: `It is Christmas Eve after the mother\'s death and Mrs. Boye\'s marriage to another. Niels stays in town with Hjerrild the editor. They argue across a long evening about whether unbelief is best held in private or declared. The chapter is the novel\'s clearest sustained dialogue on what the position costs.`,
      summary: [
        `The chapter opens on a winter evening in Copenhagen. The streets are empty in the way the streets of a Christian city are empty on Christmas Eve. Niels has not gone home to Lönborggaard for the holidays. His mother is dead; his father is at Lönborggaard alone with the housekeeper; the affair with Mrs. Boye is over and she is married. He is, for the first time in the novel, simply alone in the city. He walks for a while; he stops at Hjerrild\'s rooms.`,
        `Hjerrild — the editor and journalist, fifteen years older than Niels, who has watched the younger man with quiet attentiveness since the night of the declaration — receives him without surprise. They have a fire. They have a bottle. They begin to talk. The conversation moves, by stages, to the subject Niels has been carrying since Edele. Hjerrild defends a life lived without God but lived quietly. He argues, as a man who has read more and lived longer, that the position is true but not the kind of truth one should make a banner of. There are believers in every room; there are families to consider; there is, even in 1850s Copenhagen, the simple courtesy of not stripping people of consolations one is free to do without. He defends, in effect, the private atheism of the educated nineteenth-century gentleman.`,
        `Niels disagrees. He argues — with the stubbornness of a man who has held a position since boyhood — that the position is not real if it is not declared. To live secretly without God while letting the world go on as if one believed is to participate in the deception. He insists, against Hjerrild\'s gentler reading, that the cost of declaring the position is the proof one is sincere about it. The chapter does not arbitrate. It lets the two men sit with their disagreement. The fire burns down. Hjerrild walks Niels to the door. Outside, the city is keeping its Christmas; the bells are ringing for the late service; Niels walks home through the snow with the argument unresolved. The novel will resolve it for him only at his own deathbed, twenty years later, with the priest at the door.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'hjerrild', name: 'Hjerrild' }],
      themes: [{ slug: 'atheism', label: 'Atheism' }, { slug: 'poetry', label: 'Poetry' }],
    },
    {
      n: 10, title: 'Chapter X — Erik, Fennimore, Fjordby', tourTitle: 'Erik married', hook: 'Erik has married a young woman named Fennimore and taken her to a manor at Mariagerfjord. Niels visits. Erik is no longer working. Fennimore is bored. The catastrophe that ends the friendship is being set up with great patience.',
      tour: `Erik has married. The young woman is Fennimore — younger than the friends, gentle, intelligent, attached to Erik in a way that has not yet been tested. They have taken a small manor in the village of Fjordby on Mariagerfjord, in north Jutland. Niels visits. He finds Erik no longer working — the sculptor\'s tools laid by, the studio empty, drink at the elbow more often than is good — and Fennimore, in the long days of the country, increasingly alone with herself. The chapter is the patient setup of the catastrophe.`,
      blurb: `Erik has married Fennimore — younger than the friends, gentle, intelligent — and taken her to a small manor at Mariagerfjord. Niels visits. He finds Erik no longer working, the studio empty, drink at the elbow more often than it should be, and Fennimore alone with herself in the country. The catastrophe is being set up with great patience.`,
      summary: [
        `Some years have passed since Mrs. Boye\'s marriage and Hjerrild\'s Christmas Eve. Niels has continued in Copenhagen at the loose, unfocused life the novel has refused to sentimentalize: reading, writing nothing in particular, attending lectures, drifting from rooms to rooms. Erik, by contrast, has married. The young woman is Fennimore — daughter of a respectable family, younger than the two friends, gentle, intelligent, attached to Erik in a way that has not yet been tested by ordinary life. They have left the city. Erik\'s sculpture career, which had begun with promise, has not extended into the steady production older sculptors expect of younger ones; the couple has taken a small manor in the village of Fjordby on Mariagerfjord in north Jutland, where the rents are low and the scenery is good and the studio can be set up cheaply.`,
        `Niels travels north to visit them. The journey takes days. He arrives in late summer; the heath is in flower; the wide brown water of the fjord stretches away from the manor windows. Erik meets him at the door with the old sociability, but Niels notices, almost at once, that the studio is not what it should be — pieces half-finished, dust on the tools, the smell of damp clay where there ought to be the smell of work. Erik\'s drinking, which had always been within the limits of his constitution in Copenhagen, has expanded into the long country days. He laughs about it. He is half-aware. He is not yet alarmed.`,
        `Fennimore is younger than Niels had expected and quieter. She has been at Fjordby almost a year; the social life of a north Jutland village is what it is; her husband is half elsewhere. She is glad Niels has come. She walks with him to the fjord; she shows him the little garden behind the manor. She tells him about her childhood. The chapter does not stage anything. It records, with patience, the conditions under which the catastrophe of the next chapter will become possible: a friend\'s wife who is lonely, a friend who has stopped working, a guest who has lived inside his own head for too many years and who is for the first time in a house with someone who listens. The novel knows what it is doing. It lets us know too.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'erik', name: 'Erik Refstrup' }, { id: 'fennimore', name: 'Fennimore' }],
      themes: [{ slug: 'women', label: 'Women' }, { slug: 'disillusionment', label: 'Disillusionment' }],
    },
    {
      n: 11, title: 'Chapter XI — Mariagerfjord, Erik\'s death, the denunciation', tourTitle: 'The catastrophe', hook: 'The affair begins almost without a decision. Then Erik is killed in a road accident on the way home from town, and Fennimore turns on Niels with a fury the novel takes seriously. The chapter the book never recovers from.',
      tour: `The affair begins almost without a decision. Niels and Fennimore — the lonely wife, the half-sleeping guest — fall into it across a few summer weeks while Erik is in the village or in his studio or, more often, neither. Then, on a drive home from town in bad weather, Erik\'s carriage overturns and he is killed. Fennimore turns on Niels with a fury the novel takes seriously: she calls him by every name his behavior has earned and refuses to see him again. Niels leaves Mariagerfjord. The chapter is the catastrophe the book never recovers from, and it is the one Niels does not.`,
      blurb: `The affair begins almost without a decision. Then Erik is killed in a road accident on the way home from town in bad weather. Fennimore turns on Niels with a fury the novel takes seriously and refuses to see him again. Niels leaves Mariagerfjord. The chapter is the catastrophe the book never recovers from, and the one Niels does not.`,
      summary: [
        `The affair begins almost without a decision. The novel does not stage the seduction; it shows the conditions and lets the reader watch them work. There are walks; there are evenings in the parlor while Erik is in town; there is the long, half-undeclared attentiveness of two people who have understood, separately, that they are about to do something neither of them entirely wants. By the time Niels recognizes what is happening it has already happened. They are lovers. The novel is exact about the texture: not romance, not dignity, not tragedy in the heroic sense — just the small rooms of a country manor, the smell of the fjord through the open windows, two people who have gone past a line.`,
        `It lasts a few weeks. Then, on a wet afternoon, Erik drives into town for some piece of household business and does not come back at the expected hour. Word comes after dark. The carriage has overturned on a stretch of bad road; Erik is dead. The novel is quiet about the death itself. It is quiet about the body brought back to the manor, the local people who arrive, the funeral arrangements that must be made. Niels and Fennimore receive the news inside the architecture of what they have just been doing.`,
        `Fennimore turns on Niels. The denunciation is the chapter\'s climax and one of the most terrible scenes in the novel. She calls him by every name his behavior has earned — the friend who used the friend\'s house, the seducer who waited for the husband to be elsewhere, the man she now associates, irrevocably, with the death of the only person she had loved. The novel does not soften any of it. It does not soften it from her side and it does not soften it from his. He has, by every measure the chapter recognizes, deserved the words. He leaves Mariagerfjord the next day. He does not see her again. The catastrophe will live in him for the rest of the book — through the wandering year at Riva, through the late marriage to Gerda, through the bedside of his own son, through the field hospital at the end. The novel does not let him forget what he did at the manor on the fjord.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'erik', name: 'Erik Refstrup' }, { id: 'fennimore', name: 'Fennimore' }],
      themes: [{ slug: 'disillusionment', label: 'Disillusionment' }, { slug: 'women', label: 'Women' }],
    },
    {
      n: 12, title: 'Chapter XII — Wandering, Madame Odéro at Riva', tourTitle: 'Riva', hook: 'Niels travels for a year — Germany, Switzerland, northern Italy. At Riva on Lake Garda he spends a long convalescent stretch in the company of a singer recovering her voice. The lowest point of the drift.',
      tour: `Niels does not go straight back to Lönborggaard. He travels — Germany, Switzerland, northern Italy — for the better part of a year, in the way of men who are trying to outrun a chapter they have just lived. At Riva on Lake Garda he stays for some weeks. He meets Madame Odéro, an opera singer recovering her voice after illness; they walk the lake together; they sit in cafés in the long Italian evenings; they conduct the kind of half-romance the novel does not pretend is more than what it is. She returns to her stage. He goes home.`,
      blurb: `Niels travels for the better part of a year — Germany, Switzerland, northern Italy — trying to outrun the catastrophe. At Riva on Lake Garda he meets Madame Odéro, an opera singer recovering her voice after illness, and they conduct a long convalescent half-romance through the lake evenings. She returns to her stage. He goes home.`,
      summary: [
        `Niels does not go straight back. He cannot face Lönborggaard with the news of Erik\'s death so freshly attached to his own behavior, and he cannot face Copenhagen with the same news in different rooms. He travels. The novel sketches the travel without lingering on it: Hamburg, the Rhine cities, a stretch in Munich, the Alps, the lakes of northern Italy. He is, for a while, simply a man with money for trains and time enough to sit in the cafés of foreign cities. He reads the papers. He writes a letter occasionally to his father. He does not write to Mrs. Boye, or to Hjerrild, or to anyone who might ask the questions he is trying not to be asked.`,
        `He stops at Riva on Lake Garda — a small Italian town under the cliffs at the north end of the lake — and stays. The reason for the staying is mostly accident; the reason for the dwelling is a singer, Madame Odéro, who is also at Riva. She is older than Niels, famous in her sphere, recovering her voice after a long illness; she walks the lake with a parasol and her doctor\'s instructions; she takes her coffee at the same café Niels has begun to take his. They begin to walk together. They begin to take their evening meal at the same table. The novel does not stage a passion. It records a long, careful attentiveness between two convalescents, each of whom is using the other to think about something neither of them is willing to talk about.`,
        `She is the lowest point of the drift, and the novel knows it. She is not the figure of recovery; she is the figure that marks how far Niels has gone from the life he had imagined for himself. After several weeks she leaves Riva — her voice has come back enough; her engagements call her — and Niels stays one more week and then turns north. He goes back to Lönborggaard. His father is older and quieter than he had remembered. The estate has waited for him. The chapter ends on his return: the same gate, the same trees, the same view of the fjord his mother had loved. The novel gives him no welcome. It gives him the house.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'madame-odero', name: 'Madame Odéro' }],
      themes: [{ slug: 'disillusionment', label: 'Disillusionment' }, { slug: 'poetry', label: 'Poetry' }],
    },
    {
      n: 13, title: 'Chapter XIII — Lönborggaard, Gerda, the son\'s death, the prayer', tourTitle: 'Gerda and the prayer', hook: 'Niels marries late. Gerda is gentle and religious. They have a son. Gerda dies losing her faith. The son dies a year later. Niels prays. The child dies anyway. He gets up from beside the bed and never prays again.',
      tour: `Back at Lönborggaard, Niels marries late. Gerda is the daughter of a neighboring family — gentle, religious, much younger than he is — and the marriage is, against the evidence of the novel, a quiet happiness. They have a son. Then Gerda\'s health gives way and she dies, frightened, having lost her faith on her deathbed. A year later the son falls ill. Niels — modern, secular, twenty years past Edele\'s deathbed — finds himself praying for the boy. The boy dies. Niels gets up from beside the bed and never prays again. The novel\'s most exposed test of his atheism is in this room.`,
      blurb: `Back at Lönborggaard, Niels marries Gerda — gentle, religious, much younger than he is. They have a son. Gerda dies losing her faith on her deathbed. A year later the boy falls ill. Niels, modern and secular, finds himself praying. The boy dies anyway. Niels gets up from beside the bed and never prays again. The novel\'s most exposed test.`,
      summary: [
        `Niels has been at Lönborggaard for some months when he meets Gerda. She is the daughter of a neighboring family — younger than he is by more than a few years, gentle, devout in the unforced way of country women, untouched by any of the salons Niels has lived in. The novel is candid about how unequal the match is intellectually and how that does not, in the event, matter. She is decent. She is kind. She loves him without strain. He marries her — not as a recovery, not as a thesis, but because the marriage is the thing offered and he is finished refusing things. They live at Lönborggaard. A son is born. The novel allows them, for the first time in many chapters, a stretch of plain happiness.`,
        `Gerda\'s health gives way. The illness is one of the slow ones the nineteenth century did not understand and could not cure. Niels watches her decline through a winter and a spring. In the last weeks, faith — which had been the steadying weather of her life — leaves her. She does not lose it argumentatively; she loses it in fear. The novel\'s scenes at her bedside are among its hardest. Niels has nothing to offer her. He has held his position for thirty years; he holds it now; he is not going to lie. He sits with her. He tells her the things one tells a wife. She dies frightened. He buries her at Lönborggaard.`,
        `A year later the boy falls ill. He is small. He is the only child. The illness is the kind that takes children quickly. Niels, having watched two women die in his life, knows the shape of it. He sits at the bedside with the doctor coming and going. And then — because he is a father, and because there is nothing else to do with the hands — he prays. He prays not because he has changed his mind about God but because the impulse is older than his mind. He prays in the dark beside the bed. The chapter is exact about this, and unsparing. The boy dies. Niels gets up from beside the bed and never prays again. The novel does not tell us this in the form of a sentence; it tells us by what he does and does not do over the next pages. The atheism that does not console has been tested in the room a man can be tested in, and it has held — at the cost of everything in the room.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }, { id: 'gerda', name: 'Gerda' }, { id: 'son', name: 'The son' }, { id: 'mr-lyhne', name: 'Mr. Lyhne' }],
      themes: [{ slug: 'atheism', label: 'Atheism' }, { slug: 'women', label: 'Women' }],
    },
    {
      n: 14, title: 'Chapter XIV — The war, the deathbed, the priest refused', tourTitle: 'The deathbed', hook: 'War with Prussia in 1864. Niels enlists. He is shot in a minor engagement. In the field hospital a priest is offered to him. He sends the priest away. The novel ends.',
      tour: `War comes. In the spring of 1864 Denmark fights Prussia and Austria over Schleswig and loses badly. Niels enlists — partly out of patriotism, partly out of the long ache to do something he cannot live inside his head. He is shot in a minor engagement and brought back to a field hospital with a wound that will not heal. A priest is offered to him in the last hours. He sends the priest away. The novel ends. Jacobsen does not present the refusal as triumph. It is simply, at the end, what Niels does.`,
      blurb: `War comes. Denmark fights Prussia in 1864 and loses. Niels enlists, is shot in a minor engagement, and is brought to a field hospital with a wound that will not heal. A priest is offered to him in the last hours. He sends the priest away. The novel ends. Jacobsen does not present the refusal as triumph. It is, at the end, what Niels does.`,
      summary: [
        `War with Prussia in the spring of 1864. The novel does not pretend to write a war chapter in the heroic mode. The Second Schleswig War was, for Denmark, a brief catastrophe: a small kingdom against the Prussian and Austrian armies, an outdated army on its own ground, the loss of a third of the country\'s territory in a few months, and the long humiliation that would mark the national mood for a generation. Niels enlists. He is past the prime age for it; the army takes him anyway. The reasons for enlisting are mixed in him as they were in many of his class — patriotism for a country he has watched older men weep over, a respect for his father\'s generation, and, beneath both, the long unspoken ache of a man who has lived for forty years inside his own head and has at last been offered something that is not inside it.`,
        `He is shot in a minor engagement. The wound is in the body and it does not heal. He is brought back to a field hospital — one of the temporary ones the army set up in farmhouses behind the lines — and put on a cot among other men with similar wounds. The novel writes the field hospital with the restraint it has used for every other death scene: the smell of the room, the quiet of the night, the doctor coming and going, the women of the parish bringing what they could. Niels lies for some days. He grows weaker. He understands, in the way the dying understand, that this is the bed.`,
        `A priest is offered to him. The novel has been preparing for this offer since chapter IV — since Edele\'s bedside, since Hjerrild\'s Christmas Eve, since the bedside of his own son — and the offer arrives now in the form Edele had refused. Niels refuses it. He refuses it without theatre. He refuses it as a man who has held a position for forty years and who is not, at the very end, going to stop holding it because the position has at last become inconvenient. Jacobsen does not present the refusal as triumph. He presents it as what Niels does. The novel ends. The country has lost the war. The man has lost his life. The position has held. The book closes on a deathbed in a farmhouse behind a defeated line, with a priest at the door and a refusal on the lips of a man who, long ago, was a boy at his aunt\'s bedside watching her do exactly the same thing.`,
      ],
      appears: [{ id: 'niels', name: 'Niels' }],
      themes: [{ slug: 'atheism', label: 'Atheism' }, { slug: 'denmark', label: 'Denmark' }, { slug: 'disillusionment', label: 'Disillusionment' }],
    },
  ],
};

function toRoman(n) {
  const map = [
    [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I'],
  ];
  let out = '';
  let x = n;
  for (const [v, s] of map) {
    while (x >= v) { out += s; x -= v; }
  }
  return out;
}
