// Oedipus Rex — SEO page data for build-seo-pages.cjs
// Sophocles, 11 scenes, Greek tragedy. Voice: tight, compressed, irony-aware.

module.exports = {
  id: 'oedipus-rex',
  title: 'Oedipus Rex',
  author: 'Sophocles',
  byline: 'c. 429 BCE · Greek tragedy',
  titleAccent: 'a guided tour',
  hook: 'A king investigates a murder, follows the evidence honestly, and finds himself at the end of it. The play moves in a single afternoon, and every step toward the truth is a step Oedipus has chosen.',
  themesBlurb: 'Fate, sight, kingship, self-knowledge, the chorus as conscience.',
  castBlurb: 'King, queen, brother, prophet',
  castDesc: 'A small cast in a tightening room. Each new arrival narrows the circle.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Greek tragedy', 'Classical drama'],

  about: [
    `<em>Oedipus Rex</em> is the play in which Oedipus, king of Thebes, discovers that he is the murderer of his father Laius and the husband of his mother Jocasta — exactly what an oracle predicted of him at his birth. Sophocles wrote it around 429 BCE, when he was about sixty-six. It is the most influential single play in Western dramatic literature; Aristotle used it in the Poetics as the model of how tragedy ought to work.`,
    `The play opens with a plague on Thebes. Oedipus has sent his brother-in-law Creon to Delphi to ask the gods what is causing it. The oracle answers: the murderer of the previous king is still living in the city, and the city is polluted until he is found. Oedipus pledges to find the killer and pronounces sweeping curses on whoever it turns out to be. The rest of the play is the investigation. Each witness brings him closer; each piece of evidence narrows the circle. By the end of a single afternoon, Oedipus has identified the murderer, his queen has hanged herself, and he has put out his own eyes with the brooches from her gown.`,
  ],
  chaptersSubtitle: 'All eleven scenes — one afternoon, the noose tightening.',
  chaptersLead: `<p>Sophocles structures the play as a relentless tightening. Episodes alternate with choral odes; each episode introduces a new witness, each ode lets the city absorb what has been heard. The Prologue sets the investigation in motion. The first three episodes raise and dismiss the truth in successive shapes — a prophet, a brother-in-law, a queen. The fourth episode and the herdsman's testimony close the circle. The Exodos delivers the price.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `Oedipus Rex is a play about a man pursuing the truth of a crime that turns out to be his own. These five threads carry it. None of them are decorative; each one is the play's structural argument in a different register.`,

  groups: [
    { label: 'Scenes 1–4 · The investigation begins', subtitle: 'The plague, the oracle, the prophet who refuses to speak.', chapters: [1, 2, 3, 4] },
    { label: 'Scenes 5–8 · The circle narrows', subtitle: 'Creon defends himself; Jocasta tries to dismiss prophecy and undoes it instead.', chapters: [5, 6, 7, 8] },
    { label: 'Scenes 9–11 · Recognition and price', subtitle: 'The Corinthian, the herdsman, the queen dead, the king blind.', chapters: [9, 10, 11] },
  ],

  themes: [
    {
      slug: 'fate',
      title: 'Fate and free will',
      greek: '<em>moira</em> — the share given to each man, and the choices that fulfill it',
      preview: 'The oracle told Oedipus\'s parents what he would do. They acted to prevent it — and caused it. Oedipus acted to escape it — and fulfilled it. The play asks whether anyone in it could have chosen differently.',
      essay: [
        `The structural question of Oedipus Rex is whether anyone in it could have chosen differently. The oracle warned Laius and Jocasta that their son would kill his father. They pierced the infant's ankles and gave him to a herdsman to be exposed on Mount Cithaeron. The herdsman, pitying the child, gave him to a Corinthian shepherd; the Corinthian carried him to King Polybus, who raised him as his own. The act meant to prevent the prophecy was the act that made it possible.`,
        `Oedipus learned the same prophecy in Corinth and fled, believing Polybus and Merope were his parents. He met an old man at a crossroads, quarreled with him, killed him. He came to Thebes, solved the riddle of the Sphinx, was given the throne and the widowed queen. Every choice he made to escape his fate was the choice that delivered it. The play does not say the gods compelled the killing or the marriage; the men and women acted freely. It says they acted exactly as the prophecy required, and that the freedom and the prophecy do not contradict each other.`,
        `Sophocles is precise about this. Tiresias does not warn Oedipus and watch him resist; he warns Oedipus and watches him press on. Jocasta has the truth in her hands two scenes before Oedipus does and cannot make him stop. The mechanism by which fate works in the play is the characters' own integrity — Oedipus the good king who must save his city, Jocasta the pragmatic queen who tries to soothe her husband with a memory, Creon the loyal brother who brings back the oracle his king demanded. Take any of these virtues away and the catastrophe does not arrive on schedule.`,
        `The play does not let either side of the question win. The prophecy holds. The choices were real. What it leaves the audience with is the unsettling possibility that the two are not opposites — that fate, in the Greek sense, is the shape that free choices make when seen from the outside. Bernard Williams, in his last book, argued that this is precisely what twenty-four centuries of philosophy have not been able to dissolve.`,
      ],
      where: [
        { n: 1, label: 'Prologue (the oracle returns)' },
        { n: 7, label: 'Third Episode (the crossroads)' },
        { n: 9, label: 'Fourth Episode (the Corinthian)' },
        { n: 10, label: 'Fourth Stasimon (the herdsman)' },
      ],
    },
    {
      slug: 'sight',
      title: 'Sight and blindness',
      greek: '<em>opsis</em> and <em>typhlos</em> — clear-eyed pride, and the seer who sees',
      preview: 'Oedipus has the clearest eyes in Thebes; Tiresias is blind. By the end of the play this has reversed. Oedipus puts out his own eyes with the brooches from his mother\'s gown.',
      essay: [
        `The play turns on a single inversion. Oedipus has the clearest eyes in Thebes — he is the man who saw what no one else could see, who solved the Sphinx's riddle when better men had died trying. Tiresias is blind. He has been blind since the gods took his sight in exchange for the gift of prophecy. When Tiresias enters in the First Episode, Oedipus mocks his blindness; Tiresias answers that the king with two good eyes does not see what is around him, and that before the day is out he will be the one in the dark.`,
        `Sophocles holds the inversion through the rest of the play. The seeing king pursues the truth; the blind prophet speaks it and is dismissed. Jocasta, who begins to see, looks away. Oedipus, who refuses to look away, is the last one to understand what he has seen. The chorus calls Time the all-seeing — chronos panta horon — and watches what time uncovers when light is finally let into the corners of the house.`,
        `The recognition arrives, and Oedipus walks into the palace, finds Jocasta hanged, takes the gold brooches from her gown, and drives them into his own eyes again and again. The Exodos messenger reports it without softening: the blood ran down his beard in a black storm of hail. He blinds himself because he cannot bear to look at his children, his city, his dead. The man whose sight was his pride has chosen blindness as the only honest response to what he has now seen.`,
        `What he gains in exchange is the seer's vision. When he comes out of the palace blind, he is finally able to speak about himself with the accuracy Tiresias spoke about him in the First Episode. Sophocles does not say that physical sight is a delusion or that blindness is wisdom; he says that one is sometimes the price of the other, and that Oedipus, having spent his life seeing, has now paid.`,
      ],
      where: [
        { n: 3, label: 'First Episode (Tiresias)' },
        { n: 8, label: 'Third Stasimon (the chorus on insolence)' },
        { n: 10, label: 'Fourth Stasimon (the chorus laments)' },
        { n: 11, label: 'Exodos (the brooches)' },
      ],
    },
    {
      slug: 'pollution',
      title: 'Kingship and pollution',
      greek: '<em>miasma</em> — ritual pollution that spreads from a guilty body into the land',
      preview: 'The plague on Thebes is not a metaphor. The Greek concept of miasma is the play\'s operating premise: a hidden crime poisons the city, and only the removal of the polluted body restores it.',
      essay: [
        `The plague that opens the play is not a metaphor. The Greek concept of <em>miasma</em> — ritual pollution — held that a serious crime, especially shed kindred blood, polluted not only the doer but the soil, the herds, and the women's wombs of the place where it lived unpunished. The Priest of Zeus describes the plague in those exact terms in the Prologue: the crops fail, the cattle sicken, the women die in childbirth. The land itself is sick because something unclean is at its center.`,
        `Apollo's oracle, brought back by Creon, names the cause precisely. The murderer of Laius is still in Thebes, and Thebes will not be clean until he is driven out. The logic is not legal but ritual. The crime cannot be paid off; it can only be expelled. This is the premise on which Oedipus issues his great proclamation in the First Episode — a curse on the killer, sweeping and binding, with no clause that exempts the man pronouncing it.`,
        `What the play asks is what this logic demands of a king. Oedipus is the city; his body and the city's body are bound together. If the pollution is in him, the cure is in his expulsion. He understands this before anyone has to explain it to him; in the Exodos his first request, after the blinding, is that Creon cast him out. He does not argue for clemency. He has made the curse himself, and the city will not heal until it is carried out.`,
        `Sophocles is unsentimental about what kingship is here. It is not power; it is exposure. The king holds the city's wellbeing in his body, and when his body turns out to be the source of the pollution, the city has no choice and neither does he. Creon, taking over at the end, is careful to wait on the gods before deciding the terms of the exile. The pollution belongs to the gods to release. The king does not.`,
      ],
      where: [
        { n: 1, label: 'Prologue (the plague described)' },
        { n: 3, label: 'First Episode (Oedipus\'s curse)' },
        { n: 11, label: 'Exodos (Oedipus asks to be cast out)' },
      ],
    },
    {
      slug: 'self-knowledge',
      title: 'Self-knowledge as catastrophe',
      greek: '<em>gnōthi seauton</em> — know thyself, the inscription at Delphi',
      preview: 'The Delphic inscription "know thyself" was a warning, not a self-help slogan. Oedipus obeys it and is destroyed by it. The play is what the warning meant.',
      essay: [
        `The inscription over the entrance to the temple at Delphi was <em>gnōthi seauton</em> — know thyself. It was not a self-help slogan. It was a warning. The Greeks understood it to mean: know that you are mortal, know your limits, know what you are not. Oedipus Rex is a play about a man who obeys the inscription too literally and is destroyed by what he learns.`,
        `Oedipus's pursuit of the truth is, throughout, his most admirable quality. He is not weak. He is not corrupt. He is the king of a plague-stricken city who has sworn to find its cause and will not stop until he has. Every witness who tries to slow him down — Tiresias, Jocasta, the herdsman — is brushed past. He is the play's detective and the play's criminal, and the integrity of the detective is what destroys the criminal. There is no version of the story in which Oedipus stops asking and the city heals.`,
        `Jocasta, beside him, sees this earlier and tries to save him from it. In the Fourth Episode, when the Corinthian's news has begun to reveal what she now knows, she begs him to stop. He hears her as a queen embarrassed by his low birth, and presses on. Her last words to him are <em>iou iou, dystēne</em> — alas, doomed man — and she goes inside and hangs herself. She knew the truth one scene before he did and could not survive it. He survives it because he is harder, and because what is in front of him is unavoidable.`,
        `What the play suggests, without saying it, is that the deepest knowledge is sometimes the kind that cannot be carried. The Greeks did not romanticize this. The chorus, in the Fourth Stasimon, draws the conclusion plainly: count no man happy until he is dead, because what he learns about himself before he dies may unmake everything that came before. The Delphic inscription was about that kind of knowing. The play is what the warning meant.`,
      ],
      where: [
        { n: 7, label: 'Third Episode (Oedipus\'s memory of the crossroads)' },
        { n: 9, label: 'Fourth Episode (the Corinthian\'s revelation)' },
        { n: 10, label: 'Fourth Stasimon (count no man happy)' },
        { n: 11, label: 'Exodos (the recognition complete)' },
      ],
    },
    {
      slug: 'chorus',
      title: 'The chorus as conscience',
      greek: '<em>choros</em> — the elders of Thebes, the city\'s moral voice',
      preview: 'The Chorus of Theban Elders sing between every episode. They grieve, interpret, resist the truth as long as they can. Their last lines are the play\'s last words.',
      essay: [
        `The Chorus of Theban Elders is not decoration. They are the city's moral voice, present in every choral ode and present, half-silent, through every episode. Sophocles uses them as the play's conscience and its memory. They begin in fear, calling on Apollo to lift the plague. They listen as the king pronounces curses, as the prophet names the killer, as the queen dismisses prophecy and the king asserts the gods are dead. They keep their counsel longer than any of them — partly because the truth is too painful to face and partly because they understand that accepting it means accepting what their king has unknowingly done.`,
        `Their odes are calibrated. The First Stasimon cannot believe the seer; there is no proof, the elders say, and they will not abandon the king who saved the city from the Sphinx. The Second Stasimon, after Jocasta has dismissed prophecy, defends the oracles in the play's most famous lines — if these old prophecies fail, why should anyone dance the sacred dances anymore? The Third defends piety against insolence; the Fourth, when the truth has finally arrived, raises the lament that closes the play.`,
        `What the chorus is doing in all of this is staying loyal to two things at once — to the king who has been good to them, and to the gods whose word the king has begun to challenge. The two loyalties tear at each other through the middle of the play. By the time the Fourth Stasimon arrives, they have understood that the gods were right and the king was the price. Their grief is not abstract. They knew Oedipus. They cheered him when he came to Thebes a stranger. They have to live in the city he leaves behind.`,
        `Sophocles gives them the play's last words. Count no man happy, they say, until he has crossed the boundary of life free from pain. The line is not advice; it is what the play has spent eleven scenes proving. They are the audience inside the play, and what they have learned is what the audience outside has been shown.`,
      ],
      where: [
        { n: 2, label: 'Parodos (the prayer to Apollo)' },
        { n: 4, label: 'First Stasimon (the elders defend the king)' },
        { n: 8, label: 'Third Stasimon (the elders defend the gods)' },
        { n: 10, label: 'Fourth Stasimon (count no man happy)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Oedipus', role: 'King of Thebes', body: `Brilliant, fearless, and impatient. He arrived in Thebes years earlier as a stranger, solved the riddle of the Sphinx that no one else could solve, and was given the throne and the widowed queen as reward. He is genuinely a good king. The plague is killing his city and he has no patience for delay. Every step of the investigation he insists on, every witness he summons, every threat he makes against the unknown killer turns the noose another notch. He is the detective and the criminal.` },
    { name: 'Jocasta', role: 'Queen of Thebes', body: `Wife of Oedipus and, before him, of Laius. Pragmatic and shrewd. She understands the truth several scenes before Oedipus does. Her response is to dismiss prophecy as fraud — she tells him an oracle once predicted Laius would be killed by his own son and how it didn't happen, since Laius was killed by robbers at a crossroads. The detail destroys her. She begs Oedipus to stop asking questions. When he refuses, she goes inside and hangs herself.` },
    { name: 'Creon', role: 'Brother of the queen', body: `Oedipus's brother-in-law and second-in-command in the city. He brings back Apollo's oracle from Delphi at the start and bears the brunt of Oedipus's suspicion in the middle of the play, when Oedipus convinces himself that Creon and Tiresias are conspiring against him. He defends himself with a measured speech about the costs and benefits of being king, and is acquitted. By the play's last scene he is the one in charge, leading the blinded Oedipus indoors with a restraint that is its own kind of dignity.` },
    { name: 'Tiresias', role: 'Blind prophet of Apollo', body: `The aged seer of Thebes, blind from a divine bargain made long before. He already knows the answer when Oedipus summons him and refuses to speak. Goaded into speech by Oedipus's accusations, he names Oedipus as the killer of Laius, then delivers a chilling prophecy: the man so proud of his sight will be blind before nightfall, a beggar driven from the land. No one in the room believes him, including the man it is about.` },
    { name: 'The Herdsman', role: 'The man who would not let the child die', body: `An old slave of the house of Laius, the only survivor of the attack at the crossroads. He was given the infant Oedipus to expose on Mount Cithaeron and instead handed him to a Corinthian shepherd. Summoned in the Fourth Episode, he tries to refuse to speak. Oedipus threatens him; he tells everything. He is the witness whose testimony closes the circle.` },
    { name: 'The Chorus of Theban Elders', role: 'The city\'s conscience', body: `The older citizens of Thebes who sing between episodes — comment, grieve, interpret. They defend the king as long as they can, defend the gods when Jocasta dismisses prophecy, and resist the truth longer than anyone except Oedipus himself. Their final lines, as Oedipus is led away blind, are the play's last words.` },
  ],

  castSubtitle: 'A small cast in a tightening room.',
  castLead: `<p>Oedipus Rex has the smallest principal cast of any major Greek tragedy. Six speaking roles plus the chorus. Sophocles uses the small size deliberately — every entrance is consequential, every new arrival narrows the circle by another step. The play's structural tightness is partly a function of how few people are in it.</p>
      <p>The cards below cover all named figures. Several characters are referred to but never appear on stage — Polybus, Merope, Laius, the Sphinx — and the play depends on what is told about them as much as on what is shown.</p>`,
  castGroups: [
    {
      label: 'The royal house',
      subtitle: 'King, queen, and the queen\'s brother.',
      characters: [
        { id: 'oedipus', tag: 'Mortal', name: 'Oedipus', epithet: 'King of Thebes, solver of the Sphinx', body: `The central figure of the play and the most fully drawn man in classical drama. He arrived in Thebes a stranger, solved the riddle no one else could solve, and was given the throne and the widowed queen as reward. He is intelligent, fearless, and impatient. The plague is killing his city; he will find the cause whatever it costs. Every quality that made him a good king — and a good detective — becomes the instrument of his destruction. He is the man who pursues the truth honestly to the end and finds himself there.`, appears: [1, 3, 5, 7, 9, 10, 11] },
        { id: 'jocasta', tag: 'Mortal', name: 'Jocasta', epithet: 'Queen of Thebes, wife of two kings', body: `Wife of Oedipus and, before him, of Laius. The most fully drawn woman in Sophocles. She is pragmatic, shrewd, and tries throughout the middle of the play to talk her husband down from his fears. The story she tells him to dismiss prophecy — the infant exposed, Laius killed at the crossroads — is the story that destroys her. She understands the truth in the Fourth Episode, two scenes before Oedipus does. She begs him to stop. When he refuses, she goes into the palace and hangs herself in the bridal chamber.`, appears: [5, 7, 8, 9, 11] },
        { id: 'creon', tag: 'Mortal', name: 'Creon', epithet: 'Brother of Jocasta, second in the city', body: `Oedipus's brother-in-law and political deputy. He goes to Delphi at the start and brings back Apollo's command. In the middle of the play he is wrongly accused by Oedipus of conspiring with Tiresias to seize the throne; he defends himself with a calm, almost philosophical speech about the unattractiveness of being king when one already shares power without the burden. Acquitted by Jocasta's intercession, he returns at the end as the only authority left standing. He leads the blinded Oedipus indoors with restraint that is its own kind of dignity.`, appears: [1, 4, 5, 11] },
      ],
    },
    {
      label: 'The witnesses',
      subtitle: 'The men whose testimony closes the circle.',
      characters: [
        { id: 'tiresias', tag: 'Mortal', name: 'Tiresias', epithet: 'Blind prophet of Apollo', body: `The aged seer of Thebes. Blind, summoned reluctantly, he refuses at first to speak. Oedipus accuses him of complicity in the murder; only then does Tiresias name Oedipus as the killer of Laius and deliver the prophecy that frames the rest of the play — the man so proud of his sight will be blind before nightfall. He leaves with a parting riddle that no one in the room understands. Sophocles uses his blindness as a deliberate counterpoint to Oedipus's clear-eyed pride; by the end, the inversion is complete.`, appears: [3] },
        { id: 'priest-of-zeus', tag: 'Mortal', name: 'Priest of Zeus', epithet: 'Spokesman of the suppliants', body: `An older priest who opens the play at the altar steps before the palace, leading the suppliants of Thebes — children, elders, fellow priests — who have come to beg Oedipus to do something about the plague. His speech describes the plague in precise terms and sets the entire investigation in motion. He addresses Oedipus as the man who saved the city once before, from the Sphinx, and asks him to save it again. He does not appear after the Prologue.`, appears: [1] },
        { id: 'messenger-from-corinth', tag: 'Mortal', name: 'Messenger from Corinth', epithet: 'Bearer of the news that opens the trapdoor', body: `An old man who arrives at the palace with what seems to be good news: Polybus, king of Corinth, has died of old age, and the Corinthians wish Oedipus to come and reign there. Trying to ease the king's residual fear of the prophecy, he reveals that Polybus was not Oedipus's blood father — he himself received the infant Oedipus on Mount Cithaeron from one of Laius's herdsmen and gave him to the childless Corinthian king. The disclosure, meant as a kindness, is what closes the circle.`, appears: [8, 9] },
        { id: 'herdsman', tag: 'Mortal', name: 'The Herdsman', epithet: 'The slave who would not let the child die', body: `An old slave of the house of Laius, and the only survivor of the attack at the crossroads. Years before, he was given the infant Oedipus by Jocasta with orders to expose the child on Mount Cithaeron, and instead, out of pity, handed it to a Corinthian shepherd he met on the slopes. Summoned in the Fourth Episode and confronted with the Corinthian, he tries to refuse to speak. Oedipus threatens him with torture; he tells everything. His testimony is the last evidence Oedipus needs, and it closes the circle.`, appears: [10] },
        { id: 'second-messenger', tag: 'Mortal', name: 'Second Messenger', epithet: 'The household servant who reports what happens inside', body: `A servant of the palace who emerges in the Exodos to report what no one on stage has seen — Jocasta's suicide and Oedipus's blinding. Greek dramatic convention forbids violence on stage; the messenger's narration is therefore one of the most carefully constructed speeches in the play. He describes Jocasta locking the bridal-chamber doors and calling on Laius's name as she hangs herself, and Oedipus, finding her, driving the brooches from her gown into his own eyes again and again with a black storm of blood.`, appears: [11] },
      ],
    },
    {
      label: 'The chorus',
      subtitle: 'The city\'s moral voice.',
      characters: [
        { id: 'chorus', tag: 'Chorus', tagClass: 'god', name: 'Chorus of Theban Elders', epithet: 'The older citizens of Thebes', body: `A group of older men of Thebes who sing between every episode. They open with a prayer to Apollo to lift the plague. They defend the king when Tiresias names him; they defend the gods when Jocasta dismisses prophecy. They resist the truth longer than anyone but Oedipus himself, because accepting it means accepting what their king has unknowingly done. Their odes are some of the most quoted lyrics in Greek drama. Their last lines, as Oedipus is led away blind, are the play's last words: count no man happy until he has crossed the boundary of life free from pain.`, appears: [2, 4, 6, 8, 10, 11] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'Prologue', tourTitle: 'The plague at the palace doors', hook: 'A plague is killing Thebes. The suppliants are at the palace steps. Oedipus comes out to meet them and is told what he already knows: only the king can save the city.',
      tour: `Suppliants of every age — children, elders, priests with olive branches wreathed in wool — sit at the altar before the palace. Oedipus comes out to them. The Priest of Zeus speaks for the city: the crops are blighted, the cattle dying, the women dying in childbirth, and Thebes looks to the man who once solved the Sphinx's riddle to save it again. Oedipus answers that he has already sent Creon, his brother-in-law, to consult Apollo at Delphi. As he speaks, Creon arrives. The oracle's answer is plain: Thebes is polluted by the unavenged murder of Laius, and will not heal until the murderer is found and driven out. Oedipus pledges to find the killer.`,
      blurb: `The plague has Thebes by the throat. Suppliants of every age sit at the altar before the palace doors with olive branches. Oedipus comes out to meet them. The Priest of Zeus describes the dying — crops blighted, cattle gone, women lost in childbirth — and asks the king who once saved the city from the Sphinx to save it again. Creon returns from Delphi as the king is speaking. The oracle's answer: Thebes is polluted by the unavenged murder of Laius, and will not heal until the killer is found and driven out. Oedipus pledges to do it.`,
      summary: [
        `The play opens at dawn at the altar steps before the palace. Suppliants of every age — children barely able to walk, old priests, the flower of the Theban youth — sit with olive branches wreathed in wool, and the smell of incense lies heavy over the city. Oedipus comes out to meet them. The Priest of Zeus speaks first. He describes the plague in detail: blighted harvests, herds dying in the fields, women dying in childbirth, the city wasted. He addresses Oedipus as the man who once saved Thebes from the Sphinx and asks him to save it again.`,
        `Oedipus replies that he has not been idle. The grief of the city has been his grief; he has wept for them more than for himself; and he has already sent his brother-in-law Creon to Delphi to ask the gods what is to be done. As he speaks, Creon is sighted on the road, returning. He arrives garlanded with laurel, a sign that the news is good. He suggests speaking privately. Oedipus tells him to speak in front of the suppliants — what is at stake belongs to all of them.`,
        `Creon delivers the oracle. The land is polluted; a murderer lives in it; the murderer of Laius is the source of the plague, and Thebes will not heal until he is found and either killed or driven out. The few facts Creon can supply are scant. Laius was killed years ago at a place where three roads meet; the killers were said to be foreign brigands; only one of his attendants survived to bring back the story; the city, occupied at the time with the Sphinx, never investigated. Oedipus pledges to take the case up himself, immediately. He does not yet know he is investigating his own life.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'creon', name: 'Creon' }, { id: 'priest-of-zeus', name: 'Priest of Zeus' }],
      themes: [{ slug: 'pollution', label: 'Pollution' }, { slug: 'fate', label: 'Fate' }],
    },
    {
      n: 2, title: 'Parodos', tourTitle: 'The chorus prays to Apollo', hook: 'The Chorus of Theban Elders enters and prays to the gods to lift the plague. Their fear is the city\'s fear.',
      tour: `The Chorus of Theban Elders enters and sings the play's opening ode. They have heard that an oracle has come back from Delphi and they are waiting to learn what it says. Their fear is the city's fear — the plague is killing Thebes, the dead lie unburied, the women's labors come to nothing. They call on Athena, Artemis, and Apollo to defend the city as they did long ago. They invoke Zeus, Dionysus, the Healer of Delos, every god who has ever helped Thebes. They beg Bacchus to drive the war-god Ares out of the land. The ode is the city speaking out of its own grief, before any name has been named.`,
      blurb: `The Chorus of Theban Elders enters and sings the play's opening ode. They have heard an oracle has come back from Delphi and they are waiting to learn what it says. Their prayer goes to Apollo, Athena, and Artemis — defend the city as you defended it long ago. They count the city's losses: the earth denying her fruits, the women crying out in barren labor, the corpses spreading infection through the streets. They call on Dionysus, god of Thebes, to drive the war-god Ares out of the land. The form is liturgical; the panic underneath is unmistakable.`,
      summary: [
        `The Chorus of Theban Elders enters singing. The ode is structured as a direct prayer. The elders address themselves first to Apollo at Delphi — sweet-voiced daughter of Zeus, what news do you bring? — then to Athena, then to Artemis, then back to Apollo as the lord of the death-winged arrow. They beg for the threefold aid of all three immortals to save the city from death and ruin. The form is liturgical; the panic underneath is unmistakable. They are waiting to learn what Apollo has said and they cannot yet bear the silence.`,
        `They count their losses. The earth is denying her fruits; the women are crying out in barren labor; life after life is struck down faster than a bird's flight, faster than the onrush of the Fire-God to the western shores of Night. The corpses spread infection through the streets. Wives and grey-haired mothers throng the altars, begging release. The elders ask whether Apollo has, in days gone by, lifted such a plague before, and beg him to come near again now.`,
        `They call on Dionysus too — Bacchus, god of Thebes itself — to come with his torches and drive the war-god Ares out of the land, since this is a war Ares is waging without weapons, and there is no shore he can be driven to except the open sea. The ode ends with the chorus still in supplication. They do not yet know what the oracle has answered. The plague is the only fact they have, and it is killing them. The choral form lets the audience hear the city as a single voice, before the action narrows to the one man whose body holds the plague's cause.`,
      ],
      appears: [{ id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'pollution', label: 'Pollution' }, { slug: 'chorus', label: 'The chorus' }],
    },
    {
      n: 3, title: 'First Episode', tourTitle: 'The curse and the prophet', hook: 'Oedipus pronounces a sweeping curse on the killer. Tiresias arrives, refuses to speak, and is goaded into naming the king.',
      tour: `Oedipus comes back out and addresses the city. He pronounces a sweeping curse on whoever killed Laius, and on anyone who shelters him: no fire, no water, no prayer, no household will accept that man. He binds himself to the curse — even if the killer turns out to live in his own house. He summons Tiresias, the blind prophet, to help. Tiresias arrives led by a boy and refuses to speak. Oedipus, enraged, accuses the prophet of complicity in the murder. Goaded, Tiresias finally names Oedipus as the killer himself and prophesies that the man with two good eyes will be blind before the day is out. Oedipus dismisses every word and sends him away.`,
      blurb: `Oedipus comes back out and pronounces a sweeping curse on the killer of Laius — no fire, no water, no household will accept him. He binds himself to the curse if the killer turns out to be in his own house. Tiresias, the blind prophet, is summoned and refuses to speak. Goaded by Oedipus's accusations of complicity, he names Oedipus himself as the murderer and prophesies that the man with two good eyes will be blind before nightfall. Oedipus decides on the spot the prophet is a fraud bought by Creon. No one in the room believes him.`,
      summary: [
        `Oedipus comes back out before the city and makes his proclamation. Anyone who knows the killer of Laius must come forward; if the killer himself confesses, his only penalty will be exile. He then pronounces the curse — let no man in the land speak to the killer, share fire or water with him, give him any portion of the sacrifices; let his life waste away; let his house bear the same pollution. Oedipus binds himself to the curse. If the killer turns out to be in his own house, he says, he will accept the same penalty.`,
        `Tiresias is summoned. The blind prophet enters led by a boy, slow, reluctant. Oedipus greets him as Thebes's last hope. Tiresias asks to be allowed to leave; knowing the truth, he says, will help no one. Oedipus presses; Tiresias resists; Oedipus, enraged, accuses the prophet of complicity in Laius's murder. Only then does Tiresias speak. The man Oedipus is hunting, he says, is Oedipus himself. He repeats it. The king with two good eyes does not see what is around him; before the day is out he will be the one in the dark.`,
        `Oedipus refuses every word. He decides on the spot that Tiresias is a fraud bought by Creon, and that the two are plotting to seize the throne. He dismisses the prophet with insults. Tiresias, leaving, gives a parting riddle: the man you are hunting is here, a Theban native who thinks himself a foreigner, a man who is brother to his children and son to his wife. No one in the room understands it. The investigation has been delivered its answer in the third scene of the play, and the play has another eight to go.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'tiresias', name: 'Tiresias' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'sight', label: 'Sight' }, { slug: 'pollution', label: 'Pollution' }, { slug: 'fate', label: 'Fate' }],
    },
    {
      n: 4, title: 'First Stasimon', tourTitle: 'The chorus cannot believe it', hook: 'The Chorus of Theban Elders weighs what the prophet has said and refuses to abandon the king who saved the city from the Sphinx.',
      tour: `The chorus is left alone on stage. They sing the First Stasimon, weighing what they have just heard. Apollo's word has named the killer; the killer is somewhere in flight, hunted by the Fates. They cannot deny that. But they will not accept Tiresias's accusation against Oedipus. Where is the proof? They know of no quarrel between the house of Labdacus, Laius's family, and the son of Polybus. The seers may be wise, but seers are also wrong, and the king saved Thebes from the Sphinx when the seers could not. They will not condemn him on a prophet's word. Until the truth is shown plainly, they hold to the king who has been their salvation.`,
      blurb: `The chorus is left alone on stage and weighs what Tiresias has said. Apollo's word has named the killer; somewhere a man is in flight, hunted by the Fates as by sleuth-hounds. They cannot deny that. But they will not accept the prophet's accusation against Oedipus. There is no proof, they say, and they know of no quarrel between the house of Labdacus and the son of Polybus. Seers may be wise, but seers are also wrong, and the king saved Thebes from the Sphinx when seers could not. Until the truth is shown plainly, they hold to him.`,
      summary: [
        `The chorus is alone on stage and sings. The first part of the ode acknowledges that Apollo has spoken: somewhere a killer is in flight, hunted by the Fates as by sleuth-hounds, with no shelter that can hide him. The image is of a sullen bull wandering through forest thickets and upland groves, unable to escape the doom that flits always over his head, driven on by avenging Phoebus, that divine voice from the central shrine of Earth. The elders accept that the killer exists and is fated to fall.`,
        `The second part is harder. Tiresias has named the king, and the elders cannot accept it. They speak of being sorely troubled by the master seer's words but having no way to test them — no quarrel they remember between the house of Labdacus and the house of Polybus, no recent crime visible in Oedipus's record, no proof that anyone has ever known. Wisdom belongs to Zeus and Apollo, they say; mortal seers are not always right. They will not condemn the king on a prophet's word.`,
        `The ode closes by returning to what they remember about Oedipus himself. He came as a stranger and faced the winged maiden — the Sphinx — when better men had failed. They tested him with their own eyes and found him wise. They will not turn against him for an unproved charge, even from a man who speaks for Apollo. The ode is the play's first portrait of the chorus's loyalties tearing at each other. They are loyal to the gods and they are loyal to the king, and the play is going to make them choose.`,
      ],
      appears: [{ id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'chorus', label: 'The chorus' }, { slug: 'sight', label: 'Sight' }],
    },
    {
      n: 5, title: 'Second Episode', tourTitle: 'The quarrel with Creon', hook: 'Creon comes out to defend himself; Oedipus accuses him of treason; Jocasta enters to break the quarrel up.',
      tour: `Creon has heard what Oedipus accused him of and comes out to defend himself. Oedipus is contemptuous from the first word — the brazen-faced rogue, the would-be murderer. Creon answers calmly. He argues that a man who already shares power without responsibility would be mad to scheme for the throne; he asks for evidence; he reminds Oedipus that he himself proposed sending for Tiresias. Oedipus refuses to listen and threatens Creon with death. Jocasta comes out and rebukes both men for letting private fury erupt in public while the city is dying. The chorus joins her. Oedipus, against his own judgment, lets Creon go — warning him he is sparing him only at the queen's word.`,
      blurb: `Creon comes out to defend himself against Oedipus's charge of treason. Oedipus is contemptuous from the first word. Creon answers calmly: a man who already shares power without responsibility would be mad to scheme for a throne, and quick judgment reveals a quick temper. Oedipus refuses to listen and demands Creon's death. Jocasta comes out and rebukes both men for letting private fury erupt in public while Thebes is dying. The chorus pleads. Oedipus yields against his own conviction. Creon leaves with a parting shot. The engine that produced the accusation is still running.`,
      summary: [
        `Creon comes out before the palace, having heard what Oedipus has accused him of. His tone is wounded and steady. The chorus tries to calm him. Oedipus arrives in fury and speaks first — the brazen-faced rogue, the would-be murderer, the filcher of the crown. He tells Creon his plot is plain. Creon asks to be heard; Oedipus refuses; Creon insists on his right to answer, and the two exchange taut, line-by-line speeches in which neither yields ground.`,
        `Creon's defense is famous for being calm rather than fiery. He argues from the unattractiveness of kingship. As things stand, he says, he has all the privileges of power — he can ask favors of the king and grant them to others — without the burden of being king himself. Why plot to take a throne when he already has all that it offers and none of its risks? He asks Oedipus to send to Delphi himself if he doubts the oracle, and warns him that quick judgment reveals a quick temper. A man who would condemn a friend on suspicion alone is unfit to rule.`,
        `Oedipus is unmoved. He insists on Creon's death; Creon insists on exile at worst. Jocasta comes out from the palace and rebukes both men — strange, she says, that they let private quarrels erupt in public while Thebes is dying. The chorus joins her, begging Oedipus to spare a man who has sworn his innocence. Oedipus, against his own conviction, yields. Creon leaves with a bitter parting shot — temperaments like yours are hardest on themselves. The accusation against Creon has been deflected, but the engine that produced it is still running, and the king who pronounced it has not changed his mind.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'creon', name: 'Creon' }, { id: 'jocasta', name: 'Jocasta' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'pollution', label: 'Pollution' }, { slug: 'self-knowledge', label: 'Self-knowledge' }],
    },
    {
      n: 6, title: 'Second Stasimon', tourTitle: 'A short ode, a queen at the door', hook: 'Jocasta urges her husband inside; the chorus, briefly, asks her to leave the quarrel alone.',
      tour: `A short interlude. The chorus, instead of a full ode, exchanges lines with Jocasta, urging her to take her husband inside. She asks how the quarrel began; the chorus says only that rumor bred unjust suspicion, and that the city is too sorely distressed for old wounds to be reopened. Oedipus, still on stage, complains that the chorus is softening his zeal. The chorus answers that they would be witless to cast aside the king who guided the city through its worst danger. The exchange is brief and uneasy. It is the only stasimon in the play that does not stand alone — a sign that the action will not pause.`,
      blurb: `A short bridge rather than a full ode. The chorus exchanges lines with Jocasta, urging her to take her husband inside. She asks how the quarrel began; the elders deflect — rumor bred unjust suspicion, the city is too sorely distressed for old wounds to be reopened. Oedipus, still on stage, complains that the chorus is softening his zeal. The chorus answers that they would be witless to cast aside the king who guided the city through its worst danger; who else could steer them now? The exchange is brief and uneasy. The action will not pause for long.`,
      summary: [
        `The Second Stasimon is unusually short. The chorus does not retreat into a full lyric meditation; it exchanges lines with the queen and the king, who are still on stage. The form itself signals that the play is too tight for a long pause. The investigation cannot afford a full reflective ode here, and Sophocles compresses the moment to a brief bridge between two episodes that need to land back-to-back without the audience catching its breath.`,
        `Jocasta turns to the chorus and asks them to tell her how the quarrel started. The elders answer cautiously. Rumors bred unjust suspicions, they say, and the city is sorely distressed; better to leave sleeping troubles at rest. Jocasta presses — were both men at fault? Both, the elders say. She presses again, and the chorus deflects: ask no more. Oedipus, still listening, complains that the chorus is well-meaning but is softening and blunting his zeal at the moment he can least afford it.`,
        `The chorus answers him directly. They would be witless, they say — insane — to cast aside the king who is the prop and stay of the country, the pilot who in her moment of danger brought the distressed state to a quiet haven. Who else could guide them now? It is an unmistakable affirmation of loyalty to the king and a refusal to side against him on what they have heard so far. But the verb in the line they use to defend him — <em>guide</em>, <em>steer</em> — is the same verb the play will turn ironic by the end. They are loyal to the helmsman, and the helmsman is the one who has driven the ship onto the rocks.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'jocasta', name: 'Jocasta' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'chorus', label: 'The chorus' }],
    },
    {
      n: 7, title: 'Third Episode', tourTitle: 'The crossroads', hook: 'Jocasta tries to comfort her husband by dismissing prophecy. The story she tells contains the detail that destroys him.',
      tour: `Jocasta asks Oedipus what has shaken him. He tells her Creon has named him as the murderer. She tries to comfort him with a story. An oracle once came to Laius, predicting he would be killed by his own son; instead Laius was killed by foreign robbers at a place where three roads meet. So oracles cannot be trusted. Oedipus, hearing the crossroads, goes still. He asks her to describe Laius and the place. The descriptions match. He tells her about a furious quarrel he had on the road from Corinth, an old man in a chariot, a fight in which he killed them all. He clings to one thread: the witness said robbers, plural. He sends for him.`,
      blurb: `Jocasta tries to soothe her husband by dismissing prophecy. An oracle once said Laius would be killed by his own son, she says, but he was killed by foreign robbers at a place where three roads meet. The detail stops Oedipus cold. He asks her to describe Laius and the place; the descriptions match. He tells her, for the first time, about a fight he had on the road from Corinth — an old man in a chariot, attendants, all killed in fury. He clings to one thread: the witness said robbers, plural.`,
      summary: [
        `Jocasta and Oedipus are alone. She asks what has unsettled him so deeply; he tells her Creon has named him as the murderer of Laius through a corrupt prophet. She moves to reassure him. No mortal, she says, has any share in the art of prophecy. Here is the proof: an oracle once came to Laius — saying he would be killed by his own son. Instead, Laius was killed by foreign robbers at a crossroads, and the son she bore him was exposed as an infant on a mountainside, his ankles pinned. Apollo, she concludes, did not bring either of those things to pass.`,
        `Oedipus has stopped listening. The phrase <em>where three roads meet</em> has caught in him. He asks her where Laius was killed. How long ago. How Laius looked. The descriptions match a man Oedipus killed himself on the road from Delphi a few months before he came to Thebes. He tells Jocasta everything for the first time. He was raised in Corinth as the son of King Polybus and Queen Merope. A drunken man at a feast once called him a foundling. The oracle at Delphi told him he would kill his father and marry his mother. He fled. On a road in Phocis, where three ways met, an arrogant old man in a chariot had tried to push him off the path. He killed the old man and all his attendants in fury.`,
        `The story closes the gap between them by half. He may be the man he is hunting. He clings to one thread of doubt: the surviving witness had reported that robbers, plural, attacked the king. If there were many killers, Oedipus is not one. He sends for the witness, the old herdsman. The investigation is now investigating its investigator.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'jocasta', name: 'Jocasta' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'self-knowledge', label: 'Self-knowledge' }],
    },
    {
      n: 8, title: 'Third Stasimon', tourTitle: 'The chorus defends the gods', hook: 'After the queen has dismissed prophecy, the chorus sings the play\'s most quoted ode. If the old prophecies fail, why dance the sacred dances anymore?',
      tour: `The chorus, alone, sings the play's most famous lyric. After Jocasta has dismissed oracles as fraud, the elders defend them. May my lot be still to follow the old laws ordained on high, they sing, whose birthplace is Olympus and not mortal speech. These laws never sleep; the god in them does not grow old. Insolence breeds tyrants; the proud sinner falls from his height. If men can scoff at oracles and rise to honor, why dance the sacred dances anymore? The ode is in part a defense of religion against political convenience, in part the chorus declaring that they will hold to the gods whatever happens to the king.`,
      blurb: `After Jocasta has dismissed oracles as worthless, the chorus sings in defense of the gods — the play's most quoted lyric. May my lot be to follow the old laws ordained on high, the elders sing, whose birthplace is Olympus and not mortal speech. Insolence breeds tyrants; the proud sinner climbs a precipitous height and falls from it. If oracles fail and men can scoff at them, why dance the sacred dances anymore? Why go to Delphi or any holy shrine? The chorus places itself, openly, on the side of the gods. The next scene will close the gap.`,
      summary: [
        `The chorus is alone. Jocasta has just dismissed oracles as worthless. The elders sing in answer. The opening lines are personal: may my lot be to lead a life of innocence, in word and deed, following the old laws whose birthplace is the bright sky and whose father is Olympus alone. These laws never sleep in cold oblivion; the god in them is strong and does not grow old. The form is liturgical, the affirmation is direct, and the address is meant to land over the queen's still-fresh dismissal of prophecy as fraud.`,
        `The middle of the ode turns to insolence — <em>hybris</em>, the swollen pride that breeds tyrants. The proud man, glutted with empty riches, climbs a precipitous height and falls from it; there is no foothold on the dizzy steep. May Heaven keep the true patriot who burns with eager zeal to serve the state, the elders sing, and bring down the man who walks unjustly, who profanes the holy things, who grasps at gain by impious means. The lines are general — they would fit any tyrant — but the audience is meant to hear them aimed.`,
        `The ode ends with the famous question. If oracles fail and men can scoff at them, why dance the sacred dances anymore? Why go to Delphi or any holy shrine? The elders make their position plain: they will hold to the gods even if the queen's story is true and the prophecy was wrong. The chorus has now placed itself, openly, on the side of the oracles. They have not yet said this means against the king. The next scene will close the gap.`,
      ],
      appears: [{ id: 'chorus', name: 'Chorus' }, { id: 'jocasta', name: 'Jocasta' }],
      themes: [{ slug: 'chorus', label: 'The chorus' }, { slug: 'fate', label: 'Fate' }],
    },
    {
      n: 9, title: 'Fourth Episode', tourTitle: 'The Corinthian, and the trapdoor', hook: 'A messenger arrives from Corinth with news that seems to vindicate Jocasta. The kindness he tries to do Oedipus is what closes the circle.',
      tour: `Jocasta returns with offerings to Apollo, asking the gods to ease her husband's mind. As she prays, a messenger arrives from Corinth. Polybus has died of old age, and the Corinthians want Oedipus to come and reign. Jocasta seizes on it — the prophecy was empty. Oedipus exults. But one fear remains: his mother Merope is still alive. The Corinthian, trying to ease the king's worry, reveals that Merope was never his real mother. He himself received Oedipus as an infant on Mount Cithaeron from a herdsman of Laius and gave him to the childless Polybus. Jocasta understands the truth in a flash. She begs Oedipus to stop. He hears her as a queen embarrassed by his low birth.`,
      blurb: `A messenger from Corinth arrives with what seems to be good news. Polybus, king of Corinth, has died of old age, and the Corinthians want Oedipus to come and reign. Jocasta exults; the prophecy was empty. Oedipus rejoices but says one fear remains — his mother Merope still lives. The Corinthian, trying to ease the king's worry, reveals that Merope was never his real mother. He received the infant Oedipus on Mount Cithaeron from a herdsman of Laius and carried him to the childless Polybus. Jocasta understands in a flash. She begs Oedipus to stop, then rushes inside.`,
      summary: [
        `Jocasta enters carrying offerings to Apollo. Her husband is too shaken to pray himself. As she places her offerings on the altar, a stranger arrives from Corinth and asks for Oedipus. His news is short and good: Polybus has died of old age, and the Corinthians wish Oedipus to come and be their king. Jocasta sends for her husband and turns to him triumphantly — Polybus is dead, and not by Oedipus's hand; the oracles, she says, are dust and ashes.`,
        `Oedipus rejoices. The man he believed to be his father has died of natural causes; he is free of half the prophecy. But one fear remains — Merope, his mother, still lives. He will not go to Corinth while she is alive, in case the second half catches him. The Corinthian, listening with the easy curiosity of a man who thinks he is bringing only good news, breaks in to soothe him. There is no need to fear Merope. She was not his mother. Polybus was not his father. The Corinthian himself received Oedipus as an infant on the slopes of Mount Cithaeron — pinned at the ankles — from one of Laius's herdsmen, and carried him to the childless Polybus.`,
        `Jocasta sees it. She understands the whole truth in a single moment, while Oedipus is still asking the next question. He is pressing the Corinthian for the herdsman's name. She begs him in three short, broken lines to stop. Don't ask. Be content. He hears her as a queen embarrassed at the prospect of her husband turning out to be low-born, and snaps that he will not be ashamed of his origins. She cries out — alas, doomed man — and rushes into the palace.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'jocasta', name: 'Jocasta' }, { id: 'messenger-from-corinth', name: 'Messenger from Corinth' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'self-knowledge', label: 'Self-knowledge' }],
    },
    {
      n: 10, title: 'Fourth Stasimon', tourTitle: 'The herdsman, and the chorus\'s lament', hook: 'The herdsman is brought in, refuses to speak, and is broken. The chorus, watching, sings the play\'s great lament.',
      tour: `The herdsman is led on stage, old and reluctant. The Corinthian recognizes him at once. The herdsman tries to deny everything; Oedipus threatens him with torture; he confesses. He was given the infant by Jocasta herself with orders to expose it on Mount Cithaeron. He could not bring himself to kill it; he gave it to the Corinthian shepherd. The child was the son of Laius. Oedipus understands and cries out that he is revealed accursed — the killer of those he should not have killed. He runs into the palace. The chorus, alone, sings the great lament: count no man happy, for the most exalted of mortals can be brought down by a single day.`,
      blurb: `The herdsman is broken. Confronted with the Corinthian, he confesses he received the infant from Jocasta herself with orders to expose it on Mount Cithaeron, and could not bring himself to kill it. He gave the child to the Corinthian shepherd. The child was Laius's son. Oedipus understands the rest — the pieces fit — and cries out that he is revealed as accursed, the killer of his father, son and husband to his mother. He runs into the palace. The chorus, alone, sings the play's great lament: count no man happy until he is dead.`,
      summary: [
        `The herdsman is led on stage by Oedipus's men. He is old, frightened, reluctant. The Corinthian recognizes him at once and is delighted — here, he says, is the very man who handed me the child. The herdsman denies it; the Corinthian insists; Oedipus presses the herdsman for the truth, and when the herdsman keeps stalling, threatens him with torture. The herdsman breaks. He confesses that years ago he was given an infant by Jocasta herself, with orders to expose it on Mount Cithaeron. The child was the son of Laius. He could not bring himself to kill it. He gave it to the Corinthian shepherd.`,
        `Oedipus understands the rest. The pieces have been on the table since Tiresias spoke; now they fit. He cries out that he is revealed as accursed — born of those he should not have been born of, married to those he should not have married, the killer of those he should not have killed. He runs into the palace. The herdsman is led off. The Corinthian, who came with what he thought was good news, has caused a catastrophe.`,
        `The chorus is alone. The Fourth Stasimon is the play's great lament. The elders begin with the line that will outlast the play itself: races of mortal men, whose life is but a span — I count you but the shadow of a shade. They name Oedipus directly and admit they were wrong to defend him. He outshot the best of marksmen, they say; he beat down the vulture-maid; he was hailed as our savior and the land's strong tower. And now — uncrowned, his cradle his marriage-bed. The ode does what no character on stage can do: it absorbs the catastrophe on behalf of the city.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'herdsman', name: 'The Herdsman' }, { id: 'messenger-from-corinth', name: 'Messenger from Corinth' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'self-knowledge', label: 'Self-knowledge' }, { slug: 'fate', label: 'Fate' }, { slug: 'chorus', label: 'The chorus' }],
    },
    {
      n: 11, title: 'Exodos', tourTitle: 'The blinding, and the price', hook: 'A messenger reports what no one on stage could see. The queen is dead. The king has put out his own eyes.',
      tour: `A second messenger comes out of the palace. Jocasta rushed to the bridal chamber, locked the doors, called out the name of Laius, and hanged herself with a running noose. Oedipus broke the doors down, found her, took the gold brooches from her gown, and drove them into his own eyes. The palace doors open. Oedipus comes out blind, blood running down his face. Creon arrives in measured authority and leads him gently inside. Oedipus asks for exile; Creon says the gods will decide. The daughters Antigone and Ismene are brought out for one last embrace. The chorus closes the play: count no man happy until he has crossed the boundary of life free from pain.`,
      blurb: `A second messenger reports what no one on stage has seen. Jocasta rushed to the bridal chamber, locked the doors, called out the name of Laius, and hanged herself with a running noose. Oedipus broke the doors down, found her, took the gold brooches from her gown, and drove them into his own eyes. He comes out blind, blood on his face. Creon arrives in measured authority and takes charge. Oedipus asks for exile; Creon says the gods will decide. The two daughters, Antigone and Ismene, are brought out for one last embrace. The chorus closes the play.`,
      summary: [
        `The Second Messenger comes out of the palace. Greek convention forbids violence on stage, so the audience hears what has happened in narrative form. Jocasta, the messenger says, rushed to the bridal chamber, slammed the doors behind her, and called out the name of Laius — remembering the son she had borne him, by whom she had then conceived more children. She hanged herself. Oedipus burst in moments later, found her hanging, cut the noose, took the gold brooches from her gown, and drove them into his own eyes again and again. They would never see, he cried, the evils he had suffered and committed. The blood ran down his face like a black storm of hail.`,
        `The doors open. Oedipus comes out, blind, feeling his way. He addresses the chorus — what god has driven me to this? — and they cannot answer. He asks why he was ever saved on the mountain. Creon arrives in the quiet authority of the new ruler. He does not gloat. He instructs the servants to bring Oedipus inside and to wait on Apollo before deciding the questions of exile or burial.`,
        `Oedipus asks for three things: exile from Thebes; burial for Jocasta; one last embrace with his daughters. Creon grants the last at once. Antigone and Ismene are brought out. Oedipus holds them, weeping, and tells them their lives will be hard — no one will marry them, the curse on his house will follow them. Creon, gently but firmly, leads him indoors; the gods, he reminds him, will decide the rest. The chorus closes with the line that has become the play's signature: count no man happy until he has crossed the boundary of life free from pain. The plague is lifted by the same logic that opened the play. The price has been the king.`,
      ],
      appears: [{ id: 'oedipus', name: 'Oedipus' }, { id: 'jocasta', name: 'Jocasta' }, { id: 'creon', name: 'Creon' }, { id: 'second-messenger', name: 'Second Messenger' }, { id: 'chorus', name: 'Chorus' }],
      themes: [{ slug: 'sight', label: 'Sight' }, { slug: 'pollution', label: 'Pollution' }, { slug: 'fate', label: 'Fate' }, { slug: 'self-knowledge', label: 'Self-knowledge' }],
    },
  ],
}
