// SEO content data for Aeschylus's Oresteia (458 BCE).
// Trilogy: Agamemnon / The Libation Bearers / The Eumenides.
// Voice: literary, declarative present, Greek-tragic-precise.
// New schema — matches hamlet.cjs.

module.exports = {
  id: 'oresteia',
  title: 'The Oresteia',
  author: 'Aeschylus',
  byline: '458 BC · Greek tragic trilogy',
  titleAccent: 'a guided tour',
  hook: 'A king comes home from Troy. His wife is waiting with an axe. The son who avenges him is then hunted by the Furies. The only way to end the cycle is to invent a court.',
  genre: ['Tragedy', 'Drama', 'Ancient Greek literature'],
  themesBlurb: 'Blood vengeance, justice, the curse that passes through generations, the birth of law.',
  castBlurb: 'Argos — Athens',
  castDesc: 'A cursed royal house and the gods who cannot agree on how to judge it.',
  castSubtitle: 'Argos to Athens — from the house of Atreus to the Areopagus hill.',
  chapterLabel: n => `Scene ${n}`,

  about: [
    `<em>The Oresteia</em> is the only complete tragic trilogy that survives from ancient Greece. Three plays, performed in sequence on a single day at Athens in 458 BCE: <em>Agamemnon</em>, in which a victorious king returns from Troy and is murdered in his bath by his wife; <em>The Libation Bearers</em>, in which his son Orestes comes home from exile, kills his mother in vengeance, and is immediately set upon by the Furies; and <em>The Eumenides</em>, in which the case is taken to Athens, Athena empanels the first jury, the votes are tied, she casts the deciding ballot, and the Furies are persuaded, with extraordinary care, to give up the blood-right and become the city's guardians instead.`,
    `What Aeschylus achieves across the three plays is the founding myth of legal justice. The family of Atreus has been destroying itself for three generations, each act of vengeance producing the next, each killer equally convinced of the rightness of their cause. The answer is not a final killing but a court — an institution standing outside the family, whose authority both sides agree to accept. His audience in 458 BCE was sitting on the slopes of the actual Areopagus hill, watching a play that named that hill as the monument of what they were building.`,
  ],

  chaptersSubtitle: "All 26 scenes, across three plays — from the watchman's beacon-fire to the torchlit procession of the Kindly Ones.",
  chaptersLead: `<p>The Oresteia unfolds in three plays of increasing scope. <em>Agamemnon</em> (scenes 1–10) stays inside the royal palace at Argos: the beacon from Troy, the homecoming, the purple carpet, Cassandra's vision, the axe. <em>The Libation Bearers</em> (scenes 11–18) returns to the same palace eight years later: Orestes at the tomb, the recognition, the Kommos, the killing of Aegisthus and Clytemnestra, the Furies appearing. <em>The Eumenides</em> (scenes 19–26) moves to Delphi and then Athens: the Furies pursuing Orestes, Athena founding a court, the trial, the tied vote, and the final reconciliation. Twenty-six scenes in all.</p>`,

  themesByline: 'Five threads through the trilogy',
  themesLead: `The Oresteia is a trilogy about the same thing looked at from three different angles: what happens when an act of justice produces another act of justice in reply, indefinitely. The first two plays show the problem in its fullest form. The third play invents the institution that can interrupt it.`,

  groups: [
    {
      label: 'Agamemnon · The homecoming',
      subtitle: 'The beacon from Troy. The purple carpet. The axe in the bath.',
      chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
    {
      label: 'The Libation Bearers · The vengeance',
      subtitle: 'Orestes at the tomb. The recognition. The Kommos. The killing.',
      chapters: [11, 12, 13, 14, 15, 16, 17, 18],
    },
    {
      label: 'The Eumenides · The trial',
      subtitle: 'The Furies pursuing. Athena\'s court. The tied vote. The kindly ones.',
      chapters: [19, 20, 21, 22, 23, 24, 25, 26],
    },
  ],

  themes: [
    {
      slug: 'curse',
      title: 'The inherited curse',
      greek: 'the doer suffers; the deed is fixed forever',
      preview: 'The House of Atreus has been cursing itself for three generations. Tantalus, Pelops, Atreus, Agamemnon — each inheriting and amplifying the crime. The trilogy asks whether anything can stop the replication.',
      essay: [
        `The Oresteia opens in the middle of a story that began two generations before the first scene. Tantalus fed his son to the gods. The gods cursed the line. Pelops won his bride by treachery and was cursed again by the man who helped him. Pelops's son Atreus killed his brother Thyestes's children and served them to their father at a banquet of supposed reconciliation. Thyestes's surviving son Aegisthus grew up on the memory of that meal. Agamemnon sacrificed his daughter at Aulis. By the time the watchman appears on the palace roof of Argos, the blood-debt is incalculable.`,
        `The chorus in <em>Agamemnon</em> meditates on this pattern in some of the densest poetry in Greek literature: the doer is doomed to suffer, the deed once done is fixed forever in time, and the stones of the house cry out for the blood that has soaked them. The curse is not magical in the simple sense — it is structural. When a wrong is done and its perpetrator escapes, someone who loves the victim carries the grievance forward. When that person takes revenge, they create another victim, and another griever, and the cycle continues without any possible termination from within the family.`,
        `Aeschylus's diagnosis is precise: the cycle cannot be broken by any further act of justice within the family, because every act of vengeance is also an act of injustice from the point of view of the person it falls on, who will in turn be avenged. The first two plays demonstrate this with the killing of Agamemnon and then the killing of Clytemnestra. Both killers are in some sense right. Both killings produce further violence. The only answer is to take the case out of the family entirely — which is what the third play does.`,
        `The Oresteia is therefore a myth about the institutional prerequisites for civilization. The family curse ends not because someone makes a morally better decision than their predecessors, but because Athena invents an institution capable of absorbing the dispute. The Areopagus court is not just a plot resolution. It is the answer to the structural problem the curse represents.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (the curse recalled — the parodos)' },
        { n: 4, label: 'Scene 4 (the first stasimon on doom)' },
        { n: 10, label: 'Scene 10 (Clytemnestra\'s exultation)' },
        { n: 24, label: 'Scene 24 (the trial ends the cycle)' },
      ],
    },
    {
      slug: 'justice',
      title: 'What justice means',
      greek: 'each killer is also a victim',
      preview: 'Clytemnestra kills her husband for killing their daughter. Orestes kills his mother for killing his father. Both acts are called justice by those who commit them. The trilogy\'s argument is that both are right — and that this is the problem.',
      essay: [
        `The central moral difficulty of the Oresteia is that every act of violence in it is also an act of justice. Clytemnestra killed Agamemnon because he killed Iphigenia — child for child, life for life. Orestes killed Clytemnestra because she killed Agamemnon — parent for parent, obedient to Apollo's command. Each killing satisfies what Greek law called the law of the blood feud. And the chorus cannot settle, across all three plays, which killing was more justified, because neither argument can be refuted on the terms both parties share.`,
        `Clytemnestra's speech after the murder of Agamemnon is the key passage. She does not hide or minimize what she has done. She stands over the body and lays out her case: she acted in justice, not in passion; the blood she spilled answers the blood he spilled; the curse has moved through her by its own logic and she is its instrument. The chorus disagrees but cannot refute her. Her grievance is real. Her reasoning is the reasoning of the blood feud. And the blood feud, in the world of the first two plays, is the only available framework.`,
        `What the third play argues, through the institution of the jury, is that justice cannot be administered by the parties to a dispute. Clytemnestra was wronged and is therefore disqualified from judging her own case. Orestes was wronged and is disqualified from judging his. Apollo and the Furies represent competing principles and are equally partial. Only an institution standing outside all the parties — twelve Athenian citizens chosen by lot — can make a determination that both sides are obligated to accept. The determination may be wrong on the merits (the jury is tied; Athena's reasoning for her casting vote has been disputed for two and a half millennia). What matters is not that it is correct but that both sides accept its authority. That is what a legal system is.`,
      ],
      where: [
        { n: 10, label: 'Scene 10 (Clytemnestra\'s defence)' },
        { n: 15, label: 'Scene 15 (Orestes\'s justification)' },
        { n: 24, label: 'Scene 24 (the arguments at trial)' },
        { n: 26, label: 'Scene 26 (Athena\'s decision)' },
      ],
    },
    {
      slug: 'clytemnestra',
      title: 'Clytemnestra',
      greek: '"a woman with the counsel of a man"',
      preview: 'The most fully drawn female character in Greek tragedy. She has been waiting ten years for Agamemnon to come home. The purple carpet is her invention. So is what happens in the bath.',
      essay: [
        `The chorus of Argive elders, in the opening scene, describes Clytemnestra as a woman with the counsel of a man — and they mean it as a compliment, in the Greek way. She has held Argos for ten years while her husband has been at Troy. She has organized the beacon-relay from Troy to Argos — a chain of fires stretching across the Aegean — so that she will know the moment Troy falls. The first play's first scene, before she appears, is a watchman bewildered by her intelligence and half-afraid of what he knows.`,
        `When she does appear, she is in complete command. She announces the fall of Troy to the chorus before the herald arrives to confirm it. She greets her husband with a speech of welcome so polished and so calculated that it takes him several exchanges to detect the danger, and by then he is already walking across the purple cloth. The purple carpet scene — in which she persuades the reluctant king to tread on robes meant only for gods — is the play's fulcrum. She knows it is impious. That is the point. She wants the gods to mark what she is about to do as a counter-impiety answering his sacrifice of their daughter.`,
        `After the murder she is magnificent. She does not weep or excuse herself. She stands over the body and gives the most uncompromising defence of the blood feud in the trilogy. She is wrong in the sense that the trilogy ultimately shows the blood feud cannot resolve the situations it produces. But within the terms of the blood feud she is right. And Aeschylus never lets the audience forget that Iphigenia is real, that the sacrifice at Aulis was real, and that whatever Clytemnestra has become, she became it standing at an altar in a harbour watching her daughter die.`,
      ],
      where: [
        { n: 3, label: 'Scene 3 (the beacon speech)' },
        { n: 7, label: 'Scene 7 (the purple carpet)' },
        { n: 10, label: 'Scene 10 (after the murder)' },
        { n: 20, label: 'Scene 20 (her ghost wakes the Furies)' },
      ],
    },
    {
      slug: 'furies',
      title: 'The Furies and the old law',
      greek: 'older than the Olympians, born from blood',
      preview: 'The Furies are the oldest powers in the trilogy — born from the blood of the wounded Uranus, dwelling under the earth, pursuing anyone who spills kindred blood. They are not villains. They are the enforcement mechanism of an earlier world.',
      essay: [
        `The Furies (Erinyes) predate the Olympian gods. In Hesiod they are born from the blood of the wounded Uranus when Cronus castrates him — the first violence in the world produces the first avengers. They dwell under the earth. They pursue anyone who spills the blood of a blood relation. They do not distinguish between justified and unjustified killings within the family: if a son kills a mother, whatever his reasons, they come for him. They are not a punishment. They are the mechanism of a world in which the deepest bond is the blood bond, and the deepest crime is its violation.`,
        `In the <em>Eumenides</em> they appear on stage as a sleeping pack around Orestes's suppliant body at Delphi, and the priestess's description of them is the most frightening passage in the trilogy. She cannot compare them to anything — not Gorgons, not Harpies. They are wingless, black, and altogether abominable. Apollo drives them away with the force of his bow. They follow Orestes to Athens and prosecute the case against him with complete conviction: he spilled his mother's blood; that is their mandate; the verdict is not in dispute.`,
        `What makes the third play so careful — and so difficult — is that Athena does not banish the Furies or prove them wrong. She reasons with them. She offers them an honoured place beneath the Areopagus, a new role as guardians of the city's prosperity and fertility, a new name: the Eumenides, the Kindly Ones. What she is arguing is that their principle — the avenging of blood — is not abolished by the new institution of the court. It is incorporated into it. The court gives their principle a new, controlled form. They do not lose their power. They lose only the right to exercise it without authorisation. The procession that ends the trilogy escorts them by torchlight to their new shrine under the hill. They accept. The cycle ends.`,
      ],
      where: [
        { n: 18, label: 'Scene 18 (the Furies appear to Orestes)' },
        { n: 19, label: 'Scene 19 (the Furies at Delphi)' },
        { n: 20, label: 'Scene 20 (the binding song)' },
        { n: 26, label: 'Scene 26 (Athena\'s persuasion)' },
      ],
    },
    {
      slug: 'law',
      title: 'The invention of the court',
      greek: 'twelve citizens, a hill, a tied vote',
      preview: 'The most extraordinary political act in Greek tragedy. Athena refuses to judge the case alone, summons twelve Athenian citizens, and founds the court that will bear the name of the hill she is standing on. The audience is sitting on that hill.',
      essay: [
        `The founding of the Areopagus court, midway through the <em>Eumenides</em>, is the most carefully composed moment in the trilogy. Orestes has arrived at Athens as Athena's suppliant. The Furies have followed him. Apollo has followed them. Athena faces three serious claims and two divine advocates in direct opposition. She could, as a goddess, simply rule. She refuses. The matter, she says, is too grave for any single mind, mortal or immortal, to resolve by authority alone. She summons twelve Athenian citizens and constitutes them as a court.`,
        `Her speech founding the court is the trilogy's political centrepiece. She charges the jurors not to drive fear from the city — fear here meaning the awe citizens feel before their own law — and not to corrupt their institutions either with novelty or with tyranny, but to hold to the middle course in which the city's safety lies. She names the hill: it will be called forever the hill of Ares, the Areopagus, and on it will sit the court she now founds to judge cases of homicide. The Athenian audience in 458 BCE is sitting on that hill while she says this.`,
        `The trial proceeds. The Furies prosecute: did you kill your mother? Orestes admits it. Apollo defends: by divine command. The Furies: a mother's blood outweighs a husband's. Apollo: the father is the only true parent; the mother is only the soil in which the seed grows. The votes are counted. They are tied. Athena casts the deciding vote for acquittal — on the ground, which has puzzled readers ever since, that she herself has no mother and is therefore inclined to favour the male line. Modern scholarship has argued for a century about whether her reasoning is supposed to convince anyone, and a strong case can be made that it is not meant to — that the tied vote is the structural point. Justice must be administered even when the merits cannot be resolved. The institution must work even when the arguments cannot be settled. That is the invention the trilogy is celebrating.`,
      ],
      where: [
        { n: 22, label: 'Scene 22 (Athena announces the court)' },
        { n: 24, label: 'Scene 24 (the trial)' },
        { n: 25, label: 'Scene 25 (the vote)' },
        { n: 26, label: 'Scene 26 (the reconciliation)' },
      ],
    },
  ],

  keyFigures: [
    {
      name: 'Aeschylus',
      role: 'Author — c. 525–456 BCE',
      body: `Born in Eleusis of an aristocratic family. Fought at Marathon in 490 BCE and almost certainly at Salamis in 480. Lost his brother Cynegeirus at Marathon. By ancient testimony, the man who introduced the second actor to the tragic stage — the innovation that made genuine dramatic dialogue possible. Composed perhaps eighty plays, of which seven survive. Won the first prize at the Dionysia thirteen times. The Oresteia was performed in 458 BCE when he was about sixty-seven. It is the only complete tragic trilogy to survive from antiquity. He died at Gela in Sicily in 456 or 455.`,
    },
    {
      name: 'Agamemnon',
      role: 'King of Argos',
      body: `Leader of the Greek expedition to Troy. On stage for perhaps thirty minutes out of the entire trilogy — he arrives in a chariot in scene 7, is lured across the purple carpet by Clytemnestra, and is dead before scene 10 ends. The play is careful not to let him be merely a victim: he sacrificed Iphigenia at Aulis, brought Cassandra home as a concubine, and allowed himself to be flattered into the act of sacrilege that marks his death. His absence across eight years, and then his murder on return, is the engine of everything that follows.`,
    },
    {
      name: 'Clytemnestra',
      role: 'Queen of Argos',
      body: `The most fully realized female character in surviving Greek tragedy. Organised the beacon-relay from Troy. Lured Agamemnon across the purple carpet. Killed him in his bath with three blows of an axe. Gave the most uncompromising defence of the blood feud in the trilogy. Killed in the second play by her own son Orestes. Her ghost rises in the third play to wake the sleeping Furies and urge them to prosecute. Across all three plays she is the one character whose reasoning the trilogy most seriously engages with and most carefully refuses to fully endorse.`,
    },
    {
      name: 'Orestes',
      role: 'Son of Agamemnon',
      body: `Sent away as a child, raised in the court of Strophius of Phocis with his cousin Pylades. Commanded by Apollo to avenge his father. Returns in the second play, is recognised by Electra at the tomb, kills Aegisthus and then his mother, and is immediately hounded by the Furies. In the third play comes to Athens, is tried before the Areopagus, and is acquitted. He is the figure on whom the trilogy's entire inherited burden falls; his acquittal is the point at which the cycle closes.`,
    },
    {
      name: 'Athena',
      role: 'Goddess of Athens',
      body: `Patron of the city in which the play is being performed. Founder of the Areopagus court. Refuses to judge the case alone because it is too grave for any single authority. After the tied vote, casts the deciding ballot for acquittal and then spends the rest of the play reasoning the Furies out of their rage. The most carefully drawn divine figure in the trilogy — not because she resolves the argument but because she refuses to let any party claim a simple victory.`,
    },
    {
      name: 'The Furies',
      role: 'The Erinyes',
      body: `Powers older than the Olympians. Born from the blood of the wounded sky-god, dwelling under the earth, pursuing all who spill kindred blood. They appear on stage as a sleeping pack around Orestes at Delphi, described by the horrified priestess as beyond any comparison she can find. They prosecute at the trial with complete conviction. They are persuaded, not defeated. The closing procession of the trilogy escorts them to their new shrine under the Areopagus hill. They become the Eumenides — the Kindly Ones.`,
    },
  ],

  castLead: `<p>The Oresteia's cast spans three generations of one family and two orders of divinity. The human figures — Agamemnon, Clytemnestra, Orestes, Electra — carry the curse forward through the first two plays. The divine figures — Apollo, Athena, the Furies — bring it to trial in the third. Almost every character in the first two plays is dead by the time Athena founds the court.</p>`,

  castGroups: [
    {
      label: 'The house of Atreus',
      characters: [
        {
          id: 'agamemnon',
          tag: 'Mortal',
          name: 'Agamemnon',
          epithet: 'King of Argos, lord of the expedition to Troy',
          body: `Returns to Argos after ten years at Troy expecting the welcome owed to a victorious king. Is greeted by his wife with an equivocal speech, lured across purple tapestries he knows he should not walk on, and killed in his bath within an hour. The play allows him both grandeur and culpability — he sacrificed Iphigenia, brought home Cassandra, committed the impiety of the carpet. His death is the answer to all three.`,
          appears: [5, 7, 9, 10],
        },
        {
          id: 'clytemnestra',
          tag: 'Mortal',
          name: 'Clytemnestra',
          epithet: 'Queen of Argos, wife who waited',
          body: `The trilogy's central human intelligence. Organises the beacon network. Delivers the homecoming speech that is the most dangerous piece of theatrical rhetoric in Greek drama. Stands over her husband's body without apology. Is killed in the second play by her own son and returns as a ghost in the third to wake the sleeping Furies. The trilogy engages her argument more seriously than any other character's because her argument is the strongest.`,
          appears: [3, 5, 6, 7, 8, 9, 10, 15, 17, 20],
        },
        {
          id: 'orestes',
          tag: 'Mortal',
          name: 'Orestes',
          epithet: 'Son of Agamemnon, sent from exile to avenge',
          body: `The trilogy's protagonist across the second and third plays. Commanded by Apollo, recognised by Electra at his father's tomb, kills first Aegisthus and then his mother. Sees the Furies the moment the act is done. Flees to Delphi, then to Athens. Is tried before the Areopagus and acquitted by Athena's casting vote. Leaves the third play purified; the trilogy ends without him.`,
          appears: [11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24, 25, 26],
        },
        {
          id: 'electra',
          tag: 'Mortal',
          name: 'Electra',
          epithet: 'Daughter of Agamemnon, sister of Orestes',
          body: `Present only in the second play. Discovered at her father's tomb, sent there on Clytemnestra's instruction to pour libations to his ghost. Recognises Orestes from a lock of hair, a footprint, a woven pattern on his cloak. Participates in the great lyric exchange of the Kommos. Drops out of the narrative after the recognition scene; the killing is Orestes's to carry.`,
          appears: [12, 13, 14],
        },
        {
          id: 'aegisthus',
          tag: 'Mortal',
          name: 'Aegisthus',
          epithet: 'Clytemnestra\'s lover, surviving son of Thyestes',
          body: `Son of Thyestes, who was served his own children at Atreus's banquet. Has been nursing the grievance through two reigns. Co-author of Agamemnon's murder. Appears briefly in the exodos of the first play to assert his claim over the killing. Is killed by Orestes in the second play, off stage, before Clytemnestra.`,
          appears: [10, 15, 17],
        },
        {
          id: 'cassandra',
          tag: 'Mortal',
          name: 'Cassandra',
          epithet: 'Trojan prophet, Agamemnon\'s concubine',
          body: `Brought home from Troy as Agamemnon's prize. Cursed by Apollo to speak true prophecy that no one believes. Her scene in the fourth episode of <em>Agamemnon</em> — in which she sees the crimes of the house, the death of Agamemnon, and her own death, and speaks them aloud to a chorus that cannot understand — is the most sustained piece of lyric prophecy in Greek tragedy. She enters the palace knowing what awaits her.`,
          appears: [8, 9],
        },
      ],
    },
    {
      label: 'The gods',
      characters: [
        {
          id: 'apollo',
          tag: 'God',
          tagClass: 'creature',
          name: 'Apollo',
          epithet: 'God of Delphi, of prophecy, of the male line',
          body: `Commanded Orestes to kill his mother and threatened him with worse if he refused. Appears in the <em>Eumenides</em> to defend Orestes before Athena's court. His argument — that the mother is only the soil in which the father's seed grows, and the father is the only true parent — has troubled readers since antiquity. He represents the principle of the new Olympian civic order in direct collision with the older chthonic powers of the Furies.`,
          appears: [19, 21, 22, 24],
        },
        {
          id: 'athena',
          tag: 'God',
          tagClass: 'creature',
          name: 'Athena',
          epithet: 'Goddess of Athens, founder of the court',
          body: `Patron of the city where the play is performed. Refuses to judge the case of Orestes alone because no single mind should bear that authority. Summons twelve Athenian citizens, founds the Areopagus court, charges it to hold the middle course between tyranny and anarchy. After the tied vote casts the deciding ballot for acquittal. Then reasons the Furies, in careful, patient verse, out of their rage. Her persuasion of the Furies — not her founding of the court — is the trilogy's final act.`,
          appears: [21, 22, 23, 24, 25, 26],
        },
        {
          id: 'furies',
          tag: 'God',
          tagClass: 'creature',
          name: 'The Furies',
          epithet: 'The Erinyes — avengers of kindred blood',
          body: `The oldest powers in the play — older than the Olympians, born from primordial blood, dwelling under the earth. They pursue anyone who kills a blood relation. They appear on stage as a sleeping pack around Orestes at Delphi and are described by the horrified priestess as beyond any comparison she can find. They prosecute at the Areopagus with complete conviction and complete sincerity. They are not defeated at the trial; the vote is tied. They are persuaded by Athena to accept a new role as guardians of Athens. They leave the stage as the Eumenides, the Kindly Ones, escorted to their shrine by torchlight.`,
          appears: [18, 19, 20, 21, 22, 23, 24, 25, 26],
        },
      ],
    },
    {
      label: 'The witnesses',
      characters: [
        {
          id: 'watchman',
          tag: 'Mortal',
          name: 'The Watchman',
          epithet: 'On the palace roof, waiting for the beacon',
          body: `Opens the trilogy. Has been lying on the roof of Agamemnon's palace for a year, waiting for the beacon from Troy. Half-afraid of what he knows about the house. Sees the fire, dances his opening steps of joy, and says the phrase that tells the audience all they need to know: "an ox stands heavy on my tongue." He will say no more about what he knows. His silence in the face of what is coming establishes the moral atmosphere of everything that follows.`,
          appears: [1],
        },
        {
          id: 'herald',
          tag: 'Mortal',
          name: 'The Herald',
          epithet: 'Messenger from the Greek army at Troy',
          body: `Arrives after ten years to announce the victory and the king's return. His speech of greeting — to the earth, the sun, the gods, his homeland — is the trilogy's most unguarded expression of joy. The chorus cannot tell him about Clytemnestra's plans. He sails back to Sparta not knowing what is about to happen in the palace behind him.`,
          appears: [5],
        },
        {
          id: 'chorus-argos',
          tag: 'Mortal',
          name: 'The Argive Elders',
          epithet: 'Chorus of the first two plays',
          body: `Twelve old men who were too old to go to Troy. They hold the moral weight of <em>Agamemnon</em> and much of <em>The Libation Bearers</em>, since every other character in those plays either commits or enables violence. Their odes — especially the parodos and the great stasima on Zeus, on hybris, and on the curse — are the trilogy's philosophical backbone. They cannot stop what happens. They can only witness and interpret.`,
          appears: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        },
      ],
    },
  ],

  chapters: [
    {
      n: 1,
      title: 'Agamemnon — Prologue',
      tourTitle: 'The watchman on the roof',
      hook: 'A man has been lying on the palace roof for a year, waiting for a beacon fire. He sees it. He dances. He knows something he will not say.',
      tour: `The watchman has been stationed on the roof of Agamemnon's palace at Argos for a full year, watching the night sky for a signal-fire from Troy. When it finally blazes across the dark he springs to his feet, shouts with joy, dances the opening steps of his relief. He calls for the queen — Clytemnestra — to be told. And then, in the most precise dramatic foreshadowing in the trilogy, he says that an ox stands heavy on his tongue. He knows something about the house. He will not say it. But "if the house itself had a voice, it could best tell its own tale."`,
      blurb: `The watchman on the palace roof sees the beacon from Troy after a year of waiting. He shouts, dances, calls for the queen — and then goes silent on what he knows about the house he serves.`,
      summary: [
        `The first image of the Oresteia is a man lying on a palace roof in the dark. The watchman has been there for a year, propped on one arm, told by Clytemnestra to watch for the beacon-fire that will signal the fall of Troy. He has come to know the midnight sky too well. Fear stands beside him instead of sleep. When he tries to sing himself to rest, he falls to weeping — for the house is no longer governed by honor as it once was.`,
        `Then the fire blazes across the horizon. Troy has fallen. He springs up and cries his relief — calls for the queen, shouts his joy, dances the opening steps of the celebration. His master's dice, he says, have fallen well: the triple six, the lucky throw. He will gladly clasp the hand of his returned master.`,
        `But then he stops. An ox stands heavy on his tongue, he says. If the house itself could speak it would tell the tale better than he can. "To the wise I speak; to others — I remember nothing and recognize nothing." The watchman knows something he cannot say — something about the house, about the woman who commanded his post, about what is waiting for the king who is coming home. He vanishes from the play. The chorus of old men enters, and the great parodos begins.`,
      ],
      appears: [],
      themes: [{ slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 2,
      title: 'Agamemnon — Parodos',
      tourTitle: 'The parodos: ten years, the eagles, Aulis',
      hook: 'The chorus of old men enters and sings the founding myth of the expedition to Troy — and the sacrifice that launched it.',
      tour: `The twelve Argive elders, leaning on their staves, enter chanting. Ten years since the army sailed. They recall the omen at the harbour of Aulis: two eagles tearing open a pregnant hare, a sign read by the prophet Calchas as meaning Troy will fall — and that Artemis, angry at the killing, will demand a price. The ode moves from the omen to the sacrifice at Aulis, where Agamemnon chose to kill his daughter Iphigenia in order to get a wind for the fleet. The parodos is the longest and most complex choral passage in surviving Greek tragedy; it is also the moral foundation of everything that follows.`,
      blurb: `The old men of Argos enter singing the history of the expedition — the omen of the eagles, the prophet's warning, the sacrifice of Iphigenia at Aulis. This is the founding injury behind the whole trilogy.`,
      summary: [
        `Twelve old men — too old for Troy, left behind — enter leaning on their staves and begin the great parodos. Ten years have passed since Agamemnon and Menelaus sailed with a thousand ships to recover Helen from Priam's Troy. As they marched out, two eagles flew over the palace — one black, one white-tailed — and tore apart a pregnant hare. The prophet Calchas read the sign: the two kings will take Troy, but Artemis, goddess of wild things, is angry at the killing of the mother beast and her unborn young.`,
        `Artemis, Calchas says, will hold the Greek fleet windbound in harbour until her price is paid. What price? The sacrifice of Agamemnon's eldest daughter, Iphigenia, at the altar. The chorus does not narrate this bluntly. It moves toward it in images: the windless harbour, the rotting ships, the prophet's terrible announcement. Then, after the great formula "Zeus, whoever he may be — by that name I address him" — it tells the sacrifice directly: Iphigenia in her saffron robe, the gag to prevent her curse from falling on the house, the gaze she turned on each of the men she had known since childhood, asking for help that did not come, the axe.`,
        `Agamemnon, the chorus says, was not compelled. He chose. He put on the yoke of necessity himself — chose to be the instrument of the sacrifice rather than abandon the expedition. The parodos ends with the chorus in a state of suspended dread: the army has sailed, the ten years have passed, the beacons are burning — and they do not yet know whether what has been done to get here can be answered for.`,
      ],
      appears: [],
      themes: [{ slug: 'curse', label: 'The inherited curse' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 3,
      title: 'Agamemnon — First Episode',
      tourTitle: 'Clytemnestra and the beacon chain',
      hook: 'Clytemnestra tells the chorus how she knows Troy has fallen — through a chain of beacon-fires she herself designed.',
      tour: `Clytemnestra appears and tells the incredulous elders that Troy has fallen. Her proof: a relay of beacon-fires she arranged from Troy to Argos — mountain peak to mountain peak across the sea. She names every station. The speech is extraordinary as a demonstration of planning, intelligence, and control. The elders are astonished. She is already five steps ahead of everyone.`,
      blurb: `Clytemnestra announces the fall of Troy to the disbelieving chorus. Her proof is a chain of relay-beacons she herself designed, stretching from the fires of Troy to the palace roof of Argos. The play's first glimpse of how her mind works.`,
      summary: [
        `Clytemnestra comes forward from the altars she has been kindling and announces to the chorus: Troy is ours. The old men are sceptical — can she trust a night vision, a rumour? She tells them her proof: a relay of beacon-fires, mountain to mountain across the Aegean, each fire lit by signal from the last. She names every station — Ida, Lemnos, Athos, Macistus, the Euripus, Cithaeron, and finally the peak above Argos, where the watchman saw the blaze. The chain stretches from the moment Troy fell, across the sea, to her waiting eyes.`,
        `The speech establishes everything the play needs us to understand about Clytemnestra before her husband arrives. She thinks in systems. She planned for this return ten years in advance. She is not simply a woman waiting; she is the person who constructed the apparatus of knowledge that lets the city know what she knows when she knows it. The chorus calls her a woman with the counsel of a man, and in their mouths it is the highest compliment they can give.`,
        `She describes what is happening in Troy at this moment — the Greeks feasting in the conquered city, the Trojans wailing in the wreckage — and issues a warning. If the army respects the gods they have not harmed, if they do not desecrate the temples, if they come home without sacrilege, the gods may bring them safely. If not, the dead will demand a price. The chorus does not fully understand the layers of what she has just said. The audience does.`,
      ],
      appears: [],
      themes: [{ slug: 'clytemnestra', label: 'Clytemnestra' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 4,
      title: 'Agamemnon — First Stasimon',
      tourTitle: 'First stasimon: Zeus and the justice of suffering',
      hook: 'The chorus meditates on Zeus, on Paris, on the price of hubris — and on the law that wisdom comes only through suffering.',
      tour: `The first stasimon is the most important choral ode in Agamemnon for understanding the trilogy's theology. Zeus is not simply powerful; he compels wisdom through suffering. Paris stole Helen; Troy will pay for it in blood. But the ode circles back to a harder question: what is the price for the man who started all this — who sacrificed his daughter to get the war that is now, finally, won? The chorus cannot answer. It knows that the law is inescapable: whoever acts transgresses; whoever transgresses suffers.`,
      blurb: `The chorus sings of Zeus's law — that wisdom comes only through suffering — and of Paris's crime. The ode moves toward the question it cannot quite ask: what is the price for Agamemnon's own transgression at Aulis?`,
      summary: [
        `The first stasimon opens by naming Zeus as the one who set mortals on the path to wisdom through pain. "Zeus it is who leads mortals to think rightly, who has established that wisdom comes by suffering." This is not consolation. It is description. The law operates whether or not the sufferer understands it or welcomes it.`,
        `The chorus turns to Paris, who stole Helen from Menelaus's house — violating the sacred bond of guest-friendship — and brought the Trojan War on his city in consequence. They describe Menelaus's grief at the empty bed, the empty chair, the ghost of Helen in his dreams. They describe the bronze urns coming home from Troy with the ashes of the dead, and the anger of the Argive people at the thought that so many men died for one woman.`,
        `But the ode does not stay on Paris. It turns to the problem of the man who seems to prosper from transgression — who has won the war, who is coming home in triumph — and warns that the gods see through such appearances. Excessive happiness breeds insolence; insolence breeds ruin. The man who has what he should not have will eventually be brought low. The chorus is not quite saying this about Agamemnon. But it is circling it.`,
      ],
      appears: [],
      themes: [{ slug: 'curse', label: 'The inherited curse' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 5,
      title: 'Agamemnon — Second Episode',
      tourTitle: 'The herald arrives from Troy',
      hook: 'The herald reaches Argos after ten years. He weeps. He cannot tell the chorus the truth about the fleet.',
      tour: `A herald arrives from Troy — the first man to reach Argos from the war in ten years. He greets the earth, the gods, the homeland with tears of joy. The chorus cannot tell him what is waiting for his master, because Clytemnestra is present. The herald reports the fall of Troy, praises Agamemnon, and is asked about Menelaus. He hedges, then confesses: a storm struck the fleet on the way home. Menelaus is missing. The chorus takes the news with dread.`,
      blurb: `The herald reaches Argos after a decade's absence and weeps at the sight of his homeland. He brings news of Troy's fall and Agamemnon's glory — and reluctantly admits that a storm has scattered the fleet and Menelaus is missing.`,
      summary: [
        `The herald arrives and his first act is to fall to his knees and greet the soil of Argos. He has not expected to see it again. He greets the sun, Zeus, Apollo, Hermes, the heroes of the land. He announces the news: Troy has fallen; Agamemnon is coming; the expedition has succeeded. His joy is real and uncomplicated — and it is therefore the most painful moment so far in the play, because the audience knows what is waiting.`,
        `Clytemnestra is present. The chorus cannot speak plainly. It congratulates the herald and asks how it can receive Agamemnon appropriately. Clytemnestra delivers a second speech of welcome — as elaborate and as calculated as the first — in which she describes her devoted vigil through the ten years of her husband's absence. Every sentence is technically true and completely false. The herald does not detect anything amiss. He will report her loyal words to the king when he arrives.`,
        `Then the chorus asks about Menelaus. The herald hesitates. A storm struck the Greek fleet off the coast. It was catastrophic. Many ships are gone. Menelaus himself is missing — no one knows whether he is alive or dead. The chorus receives this as bad news portending worse. For the audience, the storm is also justice — the Greek fleet sacked the temples of Troy on its way to victory, and the gods are answering. The herald, bewildered, sails away.`,
      ],
      appears: [],
      themes: [{ slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 6,
      title: 'Agamemnon — Second Stasimon',
      tourTitle: 'Second stasimon: Helen and the ruin she brought',
      hook: "The chorus sings of Helen — first as a lioness's cub brought home as a pet, beautiful and destructive; then as the cause of Troy\'s ruin.",
      tour: `The second stasimon meditates on Helen through two interlocking images: first, the lion's cub raised as a pet that grows up to destroy the house that sheltered it; second, the spirit of Ruin that enters a prosperous city in the shape of a beautiful woman. The ode is not a misogynist attack on Helen — it is a meditation on how destruction conceals itself inside what looks like grace. The chorus is also, obliquely, thinking about the woman who is even now preparing the palace for Agamemnon's return.`,
      blurb: `The chorus sings of Helen through the image of a lion's cub raised as a pet — beautiful, then fatal. The ode circles the question of how ruin hides inside prosperity, and how the city knows too late that the thing it welcomed was its destroyer.`,
      summary: [
        `The second stasimon opens with an extended image: someone brought home a lion's cub, raised it by hand, let it play among the children, fed it from the table. Then it grew up. It tore the household apart. The chorus applies the image to Helen — brought to Troy in beauty, revealed in carnage.`,
        `The ode turns to the spirit of Ruin (Ate), which enters a house first as the spirit of Delight, then reveals itself as Destruction. Everything that came with Helen was welcome at first: the bride, the celebration, the peace. Then the grief began. The ode does not resolve the question of whether Helen is the cause or the occasion of Troy's destruction; that is precisely its point. The city cannot tell a beautiful disaster from a beautiful gift until it is too late.`,
        `The stasimon ends with the observation that Justice shines in smoke-darkened dwellings and honours the righteous life, while she averts her eyes from the gold-decked halls of the powerful. The chorus is not quite able to name what it is circling. But the audience knows that somewhere behind the walls of the palace, Clytemnestra is preparing the bath.`,
      ],
      appears: [],
      themes: [{ slug: 'clytemnestra', label: 'Clytemnestra' }, { slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 7,
      title: 'Agamemnon — Third Episode',
      tourTitle: 'The purple carpet',
      hook: 'Agamemnon arrives in his chariot. His wife greets him with a speech of welcome. She asks him to walk into the palace across a path of purple robes.',
      tour: `Agamemnon enters on a chariot with Cassandra beside him. Clytemnestra delivers her great speech of welcome — describing her lonely ten years, her vigilance, her devotion — in terms that the audience knows are systematically false. Then she orders her women to strew the path with purple tapestries and asks the king to walk across them. Agamemnon resists: this is the honour of gods, not men. Clytemnestra presses him. He gives in. He walks across the purple and into the palace.`,
      blurb: `Agamemnon arrives home. Clytemnestra greets him with a speech of exhausting flattery and persuades him to walk into the palace on a path of purple robes — an honour due only to gods. He hesitates, warns against impiety, gives in anyway.`,
      summary: [
        `Agamemnon arrives on a chariot with Cassandra seated beside him — the Trojan princess and prophet he has brought home as a concubine. He gives a speech of appropriate piety: the gods have helped the Greeks win; he will thank them properly; there is also a matter of civic disease at home that he will diagnose and cauterize as needed. Then he steps down and Clytemnestra appears.`,
        `Her speech of welcome is the great set-piece of the first play. She describes her ten years without him — the false reports of his death that sent her to the noose again and again (others cut her down), the sleepless nights, the tears dried to nothing, the vigils. Every word is selected for the king's ears. It is entirely plausible. It is entirely false. The audience knows she has been Aegisthus's lover; she knows the audience knows; she is performing for Agamemnon, and she is superb at it.`,
        `Then she orders the purple robes to be laid out. Walk to your palace on this path, she says — these crimson tapestries steeped in the sea. Agamemnon objects, quite correctly: this is the honour of the gods; he is a mortal; this is hubris. She presses him: Priam would have walked on purple. He gives in, removes his sandals so as not to soil the dye with his feet — still a gesture of scruple that he himself recognises is already contradicted by the act — and walks across. The gods have noticed. The chorus is afraid.`,
      ],
      appears: [{ id: 'agamemnon', name: 'Agamemnon' }, { id: 'clytemnestra', name: 'Clytemnestra' }, { id: 'cassandra', name: 'Cassandra' }],
      themes: [{ slug: 'clytemnestra', label: 'Clytemnestra' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 8,
      title: 'Agamemnon — Third Stasimon',
      tourTitle: 'Third stasimon: the foreboding of the chorus',
      hook: 'The chorus tries to explain the dread it cannot shake. The king has come home in triumph. Why is it afraid?',
      tour: `The third stasimon is the chorus's attempt to diagnose its own fear. Agamemnon has returned, Troy has fallen, the prayers of ten years have been answered. And yet there is an inexplicable dread in the chorus's breast — a sense that something is not right, that the scales are about to move. The ode turns on the image of blood spilled on the ground that cannot be called back, and the law that prosperity, left unchecked, eventually destroys itself.`,
      blurb: `The chorus is afraid and cannot explain why. Troy has fallen, the king has returned, the gods have been thanked. The ode turns on the image of blood spilled and irreversible — and on the dread that gathers in a house where happiness has been too great.`,
      summary: [
        `The third stasimon is quieter than the first two, but it is the most frightened. The chorus has just watched Agamemnon walk into the palace on the purple robes. It cannot name what is wrong. The king has come home, the war is won. And yet there is dread in the breast, a pounding of the heart that no one has taught it.`,
        `The ode turns on the one fact the chorus does know: that blood once spilled on the ground cannot be called back. When a man lies dead, no healer's art or sorcerer's power can restore the dark fluid of life. There is no singing back the dead. The chorus is thinking about all the dead of the past ten years — at Aulis, at Troy, on the sea — and wondering what the reckoning is.`,
        `The ode ends with what might be a prayer: may it not be so, may the chorus be wrong in its fear, may what it senses not come to pass. But the image that has been building through all three stasima will not go away. The chorus knows, without quite being able to say it, that someone's blood is about to be spilled in the house it is standing outside.`,
      ],
      appears: [],
      themes: [{ slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 9,
      title: 'Agamemnon — Fourth Episode',
      tourTitle: 'Cassandra\'s vision',
      hook: 'Cassandra will not enter the palace. She knows what is inside. She tells the chorus, in terrible lyric verse, everything that has happened in the house and everything that is about to happen.',
      tour: `Cassandra has been sitting silent in the chariot since Agamemnon's arrival. Clytemnestra tries to get her into the palace; she will not move. When Clytemnestra gives up and goes in, Cassandra begins to speak — first in cries, then in oracular verse, then in plain speech. She names the curse on the house, sees the murdered children of Thyestes, sees the bathtub, sees the axe. The chorus cannot understand her. She is the trilogy's most complete witness: she knows the past crimes, sees the present crime as it is happening, and knows her own death is five minutes away. Then she takes off her prophet's robes and goes in.`,
      blurb: `Cassandra, silent until now, begins to prophesy. She sees the children of Thyestes. She sees the bathtub and the woman holding the axe. She names the deed before it happens, in verse the chorus cannot follow. Then she removes her prophet's robes and walks into the palace to her death.`,
      summary: [
        `Clytemnestra re-emerges and addresses Cassandra — still seated silent in the chariot — with elaborate courtesy: come in, the bath is ready, the altars are lit. Cassandra does not move or speak. The chorus tries. Nothing. Clytemnestra gives up and goes back in, disgusted. And then, alone with the chorus, Cassandra begins to cry out.`,
        `Her first speech is inarticulate grief: Apollo, Apollo, Destroyer. The chorus does not understand. Then she begins to see. She names the curse on the house of Atreus — the banquet of Thyestes, the murdered children, the blood soaked into the foundations. She is seeing not only the past but the present: there is a woman and a net and something like a bath. She names the axe. She names the blow that is being prepared. The chorus cannot follow her; it knows her as a prophetess but cannot connect her images to what they mean. She pities them. She is perfectly clear on what she sees.`,
        `Then she shifts into direct speech. She is going to die, she says; she knows it; she accepts it. She takes off her prophet's robes — the wreath and staff Apollo gave her — and breaks them. She was right and she was not believed; she has been bought and sold and is about to be killed in a foreign land beside the man she served. She asks only to be remembered. She goes in. The chorus stands outside, trying to find something to say, when a scream comes from within the palace.`,
      ],
      appears: [{ id: 'cassandra', name: 'Cassandra' }],
      themes: [{ slug: 'curse', label: 'The inherited curse' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 10,
      title: 'Agamemnon — Exodos',
      tourTitle: 'The exodos: the murder, the body, the defence',
      hook: 'A scream from inside the palace. The chorus debates what to do. The doors open. Clytemnestra stands over two bodies and gives the most uncompromising speech in the trilogy.',
      tour: `Agamemnon's voice cries out from inside the palace — struck, again, mortally. The twelve old men fragment into twelve separate voices, each suggesting a different action, none decisive enough to act. The doors open. Clytemnestra stands in a pool of blood over the bodies of Agamemnon and Cassandra. She gives a speech of absolute self-justification: she did this; she is not ashamed; this blood answers the blood of Iphigenia; the curse of the house has moved through her and she has discharged its debt. The chorus mourns, argues, condemns her. Aegisthus appears to claim political power. The scene ends in a standoff.`,
      blurb: `The scream from the palace. The chorus in paralysis. The doors open: Clytemnestra stands over the bodies of Agamemnon and Cassandra and delivers her defence — the sacrifice of Iphigenia answered by the sacrifice of the king. Aegisthus appears to claim the throne.`,
      summary: [
        `The voice of Agamemnon cries from inside the palace: he has been struck a mortal blow, and then again, another blow. The chorus breaks into fragments — each elder saying something different, some calling for action, some for caution, all unable to agree on what must be done. The scene is deliberately theatrical: twelve individual old men with no single will, paralysed by the event they have dreaded and not prevented.`,
        `The doors open. Clytemnestra stands in a pool of blood over two bodies — her husband and Cassandra beside him. She does not apologise or weep. She gives the most sustained self-justification in Greek tragedy. She planned this, she says, and carried it through. The gods of the underworld helped her; she gives them thanks. She struck three blows: two for the man himself, one as a gift to Zeus below. She is not the adulteress who seized power while her husband was away. She is the mother of Iphigenia, and the blood she has poured out today is the answering blood for the blood he poured out at Aulis. The law of the blood feud has been fulfilled. The curse, she says, has passed through her and is done.`,
        `The chorus mourns and accuses her. She replies steadily: you did not mourn for Iphigenia. You did not mourn for the men who died for Menelaus's wife. You condemn me because I am the woman who did the act, when it was men who did the acts that made this necessary. Then Aegisthus enters — strutting, triumphant, claiming the killing as justice for what Atreus did to his father Thyestes. The chorus turns its contempt on him. He threatens the elders. They defy him. Clytemnestra restores order, barely: put away your swords. There is blood enough.`,
      ],
      appears: [{ id: 'clytemnestra', name: 'Clytemnestra' }, { id: 'aegisthus', name: 'Aegisthus' }],
      themes: [{ slug: 'clytemnestra', label: 'Clytemnestra' }, { slug: 'justice', label: 'What justice means' }, { slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 11,
      title: 'The Libation Bearers — Prologue',
      tourTitle: 'Orestes at his father\'s tomb',
      hook: 'Eight years later. A young man kneels at a grave-mound and cuts two locks of hair — one for the river that nurtured his childhood, one for his father\'s death.',
      tour: `Eight years have passed. Orestes has grown up in exile at the court of Strophius of Phocis. He has come home to Argos with his cousin Pylades, commanded by Apollo to avenge his father's murder. He kneels at Agamemnon's tomb and cuts two locks of hair — a ritual offering. Then he sees a group of women coming in mourning clothes toward the tomb: his sister Electra among them, sent by Clytemnestra to pour libations. He steps aside to watch.`,
      blurb: `Eight years after the murder. Orestes arrives at his father's tomb and cuts offering-locks of hair. He sees a group of mourning women approaching — among them his sister Electra, sent by Clytemnestra to pour libations. He steps aside to watch.`,
      summary: [
        `The second play opens at a grave-mound — Agamemnon's burial site outside the palace at Argos. A young man kneels there. It is Orestes, returned from years of exile in Phocis, now grown, now commanded by the oracle of Apollo at Delphi to come home and avenge his father. He speaks a prayer to the god of the dead and to Agamemnon's ghost, and he cuts two locks of hair: one he dedicates to the river Inachus, the nurturer of his childhood; one he lays on the tomb as a mourning offering long overdue.`,
        `He was not here when his father died. He could not stand at the body or help carry it to burial. He is here now, exiled's debts unpaid, and he calls on Zeus to help him. Then he sees what he did not expect: a group of women in sable mourning clothes coming toward the tomb, and among them his sister Electra. He recognizes her but does not know why they are coming. He steps back with Pylades to watch.`,
        `The prologue is almost wordless compared to the great opening of Agamemnon — three paragraphs and two exits. The contrast is deliberate: this play is quieter, more private, the grief more intimate. The world of the second play is the world of an occupied household, watched by enemies, grieving in secret. The grand public theatre of Agamemnon's homecoming is gone.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }],
      themes: [{ slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 12,
      title: 'The Libation Bearers — Parodos',
      tourTitle: 'Parodos: the women sent to the tomb',
      hook: 'Clytemnestra has had a dream. She has sent her women to pour libations at Agamemnon\'s grave — to soothe a dead man\'s ghost she has reason to fear.',
      tour: `Electra leads a chorus of captive women toward the tomb. They sing of the terror of the night — Clytemnestra has had a dream, and the dream was bad enough to send them out with offerings for the dead king she murdered. The women are loyal to the house of Atreus, not to its current rulers; their grief is real. They describe the dream in their song: a serpent nursed at a woman's breast.`,
      blurb: `Clytemnestra has been woken by a nightmare and sent these women to Agamemnon's tomb with libations. They sing of the terror of the night, of the dream — a serpent at a woman's breast. They hate their mistress and grieve for the dead.`,
      summary: [
        `The women of the chorus enter in mourning, sent by Clytemnestra to pour libations at the grave. They are not willing servants — they are captive women, enslaved to the household that killed the king they loved. Their song is the grief of the occupied house: they mourn in secret, they cannot speak openly, they pour the offerings without the prayers of love.`,
        `Clytemnestra has had a dream. The chorus describes it obliquely: a serpent was nursed at a woman's breast and drew blood along with milk. The dream frightened her. The wisest interpreters in the house understand it as a threat from the dead king's ghost, and she has sent these offerings to appease him. But the offerings will not appease him. The dream, as the play makes clear, is prophetic — the serpent is Orestes, and the woman's breast is Clytemnestra's own.`,
        `Electra walks at the head of the procession, unsure how to pray. What words can she use to pour libations sent by her mother? She cannot dedicate them "from a loving wife to a loving husband." She turns to the chorus for guidance.`,
      ],
      appears: [{ id: 'electra', name: 'Electra' }],
      themes: [{ slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 13,
      title: 'The Libation Bearers — First Episode',
      tourTitle: 'The recognition at the tomb',
      hook: 'Electra finds a lock of hair on her father\'s grave. Then footprints. Then a young man who completes her sentences.',
      tour: `Electra pours the libations and prays — for the return of an avenger, for Orestes. Then she sees on the grave a lock of hair — the same colour as her own, the same texture. She is bewildered: she cannot believe it is from anyone but Orestes, and yet she cannot be sure. Then she finds the footprints. Then Orestes steps forward, and they are recognised — in a scene that is the emotional centre of the second play.`,
      blurb: `Electra discovers a lock of hair and then footprints at the tomb. Then Orestes steps forward. The recognition scene — the most intensely private moment in the trilogy — is also the compact of vengeance that sets the rest of the play in motion.`,
      summary: [
        `Electra pours the libations and prays to the gods and to her father's ghost: send Orestes home, send an avenger, bring the killers to justice. Then she sees the lock of hair on the grave-mound. It is exactly the colour and texture of her own hair. She cannot believe it belongs to anyone but her brother — and yet she knows he has been away for eight years and she cannot trust appearances. She stands over the lock in a state of suspended hope.`,
        `Then she finds footprints. Two sets — one matching hers in size and gait exactly, another beside it. She is almost certain. And then Orestes steps forward. He is a stranger to her eyes after eight years, and her first instinct is to back away. But he finishes her sentences. He knows things only her brother could know — the lock was cut from his head; the footprints are his; the woven cloth she recognizes is from her own loom, sent with him when he was exiled as a child.`,
        `The recognition is not triumphant. Electra's first response is a speech that catalogues the four loves she redirects to her brother: he is now her father (since her father is dead), her mother (since her mother is her enemy), her sister Iphigenia (who died on the altar), and herself, who loves him above all. The compact of vengeance has been formed. But it is rooted in loss, not triumph.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'electra', name: 'Electra' }],
      themes: [{ slug: 'curse', label: 'The inherited curse' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 14,
      title: 'The Libation Bearers — Kommos',
      tourTitle: 'The Kommos: the great lyric exchange',
      hook: 'Orestes, Electra, and the chorus stand at the tomb and call the dead man up from below in a long, three-way lyric exchange that is unlike anything else in Greek tragedy.',
      tour: `The Kommos is the lyric and emotional heart of the second play. Orestes, Electra, and the chorus exchange verses at the tomb — calling on Agamemnon's ghost to hear them, naming their grievances, building toward the decision that must be made. It is not a plan; it is a summoning. The three parties are not plotting a course of action; they are drawing on the dead man's weight to give them the strength to do what they have to do.`,
      blurb: `The three-way lyric exchange at the tomb — Orestes, Electra, the chorus — calling on Agamemnon's ghost for strength and authority. The emotional and ritual centre of the second play, unlike anything else in the trilogy.`,
      summary: [
        `The Kommos is the most sustained piece of lyric exchange in surviving Greek tragedy: Orestes, Electra, and the chorus of captive women, taking turns over many verses, address the dead Agamemnon below the ground. The ritual purpose is clear: they are calling the ghost up, asking it to lend its weight and authority to what they are about to do. But the exchange is also an outpouring of grief — years of suppressed mourning being finally spoken aloud at the grave where they could never be spoken before.`,
        `Orestes names what he lacked — he was not there at his father's burial; he was sent away like an object of shame; the murderers feasted while the dead man lay unlamented. Electra names what has been done to her in the eight years since the murder — kept in a condition of mourning and servility, used by her mother as an instrument, denied the name of daughter by the woman who called herself queen. Both of them name Clytemnestra, and both stop short of the specific word for what must be done to her.`,
        `The chorus names the justice in what they are contemplating. They have lived in the house of Atreus through eight years of Clytemnestra's rule; they know what is being preserved and what is being destroyed. They give their voices to the call on the dead. The Kommos ends not with a plan but with a decision: both the desire and the authority to act. Then they begin to plot.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'electra', name: 'Electra' }],
      themes: [{ slug: 'curse', label: 'The inherited curse' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 15,
      title: 'The Libation Bearers — Second Episode',
      tourTitle: 'The plan: Orestes will enter as a stranger',
      hook: 'Orestes, Electra, and the nurse who raised Orestes as a baby work out what must happen next. Orestes will enter the palace disguised as a traveller with news of his own death.',
      tour: `The recognition scene leads directly into planning. Orestes lays out what Apollo commanded and what he intends to do: enter the palace as a Phocian stranger with news that Orestes is dead, gain Clytemnestra's trust, and kill Aegisthus first, then her. He gives the chorus its instructions. Then, crucially, the nurse Cilissa appears — a woman who raised Orestes from infancy and is genuinely grieving at the false news of his death — and the chorus uses her to ensure that Aegisthus will come alone, without his bodyguard.`,
      blurb: `Orestes lays out Apollo's command and his plan — enter the palace as a stranger, announce his own death, kill Aegisthus first, then Clytemnestra. The chorus intercepts the nurse sent to fetch Aegisthus and changes her message: he should come without his guards.`,
      summary: [
        `The planning scene. Orestes explains to Electra and the chorus what Apollo commanded at Delphi: avenge your father or suffer things too terrible to describe. He names the threats Apollo made against those who do not perform the blood-duty: disease, madness, the persecution of the Furies. Then he lays out the practical scheme — he and Pylades will enter the palace as Phocian travellers with news that Orestes is dead. Clytemnestra, thinking herself safe, will receive them. Aegisthus must be killed first; then Clytemnestra.`,
        `Electra's role ends here. She disappears from the play as the men begin to act. This is not Aeschylus's failure; it is the play's realism. In the world of the second play, Electra cannot do what Orestes is about to do. She is witness and partner to the decision; the killing belongs to her brother and to Apollo who commanded him.`,
        `The nurse Cilissa appears — the woman who actually nursed Orestes as a baby, who changed his swaddling-clothes, who knows the difference between public and private grief. She is weeping. The false news of Orestes's death has reached the household, and her grief is real: Clytemnestra, she says, was glad in private even while weeping publicly, but the nurse's grief is genuine. The chorus intercepts her. She has been told to fetch Aegisthus with his bodyguard; the chorus persuades her to change the message. He should come alone. She agrees.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'electra', name: 'Electra' }],
      themes: [{ slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 16,
      title: 'The Libation Bearers — Second Stasimon',
      tourTitle: 'Second stasimon: crimes of women, justice coming',
      hook: 'The chorus sings of women who have committed terrible crimes — and of the justice that is about to walk through the palace door.',
      tour: `The second stasimon of the Libation Bearers catalogues famous crimes of women — Althaea who burned the brand that held her son's life, the women of Lemnos who killed all their husbands, Scylla who betrayed her father for a foreign enemy. The ode is not simply a list of atrocities; it is the chorus building its moral authority for what is about to happen. Then it turns: and now, Justice herself is being sharpened and put into a hand fit to wield it.`,
      blurb: `The chorus sings of women who committed terrible crimes — Althaea, the Lemnian women, Scylla — before turning to the justice about to enter the palace. The ode gives moral weight to what Orestes is about to do.`,
      summary: [
        `The chorus sings three mythological precedents for women's crimes: Althaea, who burned the brand that held her son Meleager's life, killing him to avenge her brothers; the women of Lemnos, who murdered all their husbands in a single night and gave their name to the worst atrocities; and Scylla, who cut the golden hair that protected her father's kingdom, giving it to the enemy who had seduced her, and drowned in his wake.`,
        `These are not parallel cases — they are a catalogue of the worst the tradition knew, assembled to establish that what has happened in the house of Atreus belongs in this company of crimes. Clytemnestra, the ode implies without naming her, belongs in this list. What has been done to Agamemnon and what she represents is as bad as anything the chorus can remember.`,
        `The ode turns at its end to Justice. She is being forged, the chorus says; she is being put into the right hand; and the son of Zeus — the avenger — is being directed toward his mark. The second stasimon is the play's prayer before the act, and it gives the audience permission to regard what is about to happen as righteous, even though the trilogy will immediately begin to complicate that permission.`,
      ],
      appears: [],
      themes: [{ slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 17,
      title: 'The Libation Bearers — Third Episode',
      tourTitle: 'The killing — Aegisthus, then Clytemnestra',
      hook: 'Orestes and Pylades are inside the palace. Aegisthus enters and is killed. Then Clytemnestra faces her son.',
      tour: `Orestes and Pylades, disguised as Phocian travellers, have gained entry and told Clytemnestra that Orestes is dead. Aegisthus arrives alone, as the chorus arranged. He is killed inside, off stage. A servant runs out crying murder. Clytemnestra appears. She and Orestes speak directly to each other — mother and son — and she bares her breast and asks if he will kill the woman who nursed him. Pylades speaks his only lines in the play: Apollo's command must be obeyed. Orestes takes her inside. The killing happens off stage.`,
      blurb: `Orestes kills Aegisthus. Then Clytemnestra appears and faces her son. She bares her breast and pleads. Orestes hesitates. Pylades speaks his only lines: Apollo commanded this. They go inside together. When the doors open again, the bodies are on the floor.`,
      summary: [
        `The episode begins with Clytemnestra inside the palace receiving the false news of her son's death. She weeps publicly. She gives the travellers hospitality. The servant comes out to fetch the nurse; the chorus redirects her. Aegisthus enters, alone. He is told the news directly. He goes inside to see for himself — and is killed in the instant, off stage, his cry barely heard before silence.`,
        `A servant runs out shrieking murder. Clytemnestra appears immediately, asking what has happened — and in the instant she sees Orestes's face, she understands. The dialogue between mother and son is the play's most concentrated exchange: she has heard his voice before; she knows this face; she calls on a servant to bring an axe. Then she speaks directly to Orestes. She bares her breast — the breast she suckled him from as an infant — and asks if he can look at this and strike. Orestes turns to Pylades. Should I spare my mother? Pylades speaks his only three lines in the play: Apollo commanded this; break faith with Apollo and you break faith with all. Orestes takes his mother inside. The doors close.`,
        `When the doors open again, both bodies are on the floor — Aegisthus and Clytemnestra — and Orestes is standing over them, the net she used to trap Agamemnon spread over the bodies as proof. He gives his justification: she conspired against Agamemnon; she wore him in a net like a fish; he has done what Apollo commanded. And then — almost immediately — he sees them. The Furies. Moving at the edge of his vision, winding themselves around him, their eyes dripping blood. The chorus cannot see them. Orestes is already gone from the world the other characters inhabit.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'clytemnestra', name: 'Clytemnestra' }, { id: 'aegisthus', name: 'Aegisthus' }],
      themes: [{ slug: 'justice', label: 'What justice means' }, { slug: 'furies', label: 'The Furies and the old law' }],
    },
    {
      n: 18,
      title: 'The Libation Bearers — Exodos',
      tourTitle: 'Orestes flees — the Furies begin',
      hook: 'Orestes sees the Furies when no one else can. He names them. He runs.',
      tour: `The final scene of the second play is very short. Orestes stands over the bodies, justifying his actions. And then — mid-speech — he begins to see things the others cannot: women, robed in black, with snakes in their hair, dripping blood from their eyes. He knows what they are. The chorus cannot see them. He names them: the Furies of his mother. He tells the chorus he will go to Delphi and throw himself on Apollo's protection. He runs.`,
      blurb: `Orestes, mid-justification, begins to see the Furies — the chorus cannot. He names them, tells the chorus he will flee to Delphi, and runs from the stage. The second play ends with the inexorable logic of the blood feud: the avenger becomes the fugitive.`,
      summary: [
        `The exodos of the Libation Bearers is barely four paragraphs — the shortest final movement in the trilogy. Orestes stands over the two bodies and displays his justifications: the net that trapped Agamemnon, the evidence of the plot, Apollo's command. The chorus accepts his argument. The act was just.`,
        `And then he loses his grip on the shared world. He sees them — or begins to see them, at the edge of vision. Women. Black-robed. Snake-haired. Blood dripping from their eyes. The Furies of his mother. The chorus is alarmed by his state but cannot see what he sees. He tells them: these are the hounds of his mother's blood-right; they are real; they are already beginning to move toward him.`,
        `He gives his final speech: I am not mad, I swear it; these are real; I cannot stay. He will go to Delphi, to Apollo's shrine, to the one god who commanded the act and who may be able to protect him from its consequences. He runs. The chorus, left alone, sings the refrain of the Oresteia: first the beast Thyestes, then the king in his bath, and now — what? A third catastrophe, or a third thing entirely? They do not know the answer. The third play provides it.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }, { slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 19,
      title: 'The Eumenides — Prologue',
      tourTitle: 'The Pythia finds something at the altar',
      hook: 'The priestess of Apollo enters to open the shrine. She comes back out almost immediately — shaken, crawling on her hands.',
      tour: `The Pythian priestess opens the temple of Apollo at Delphi with a prayer cataloguing the gods who have held the shrine since the beginning. Then she goes in to open for the day's consultations. She comes back out almost immediately, unable to stand upright, crawling on her hands. At the central altar is a blood-stained man with a drawn sword and an olive branch. Around him, slumped asleep on the altar steps, a pack of women unlike anything she has ever seen — not quite Gorgons, not quite Harpies, "black, and altogether abominable." She calls for Apollo.`,
      blurb: `The Pythia opens the shrine of Apollo at Delphi with a solemn prayer, goes inside, and comes back out crawling on her hands. At the altar: a blood-stained suppliant clutching an olive branch. Asleep on the steps around him: a pack of creatures she cannot compare to anything she knows.`,
      summary: [
        `The opening of the third play is one of the most theatrical moments in the trilogy. The Pythia — the priestess of Apollo — enters to begin the day's consultation and prays a catalogue of the gods who have possessed the shrine since the beginning: Earth, Themis, Phoebe, and finally Apollo, who received it as a birth-gift and came to it from Delos and from Athens. She names Pallas Athena, the Nymphs, Poseidon, Zeus highest of all. Then she goes in.`,
        `She returns almost immediately, walking on her hands. Her strength is gone; fear and age together have unmanned her. At the central altar of the shrine, she says, crouches a man — stained with blood, clutching a drawn sword and an olive branch wound with white wool, the sign of the suppliant. And around him, crouched on the altar steps, a pack of women asleep. Not like women — not like Gorgons either, or Harpies. Wingless. Black. Their breath poisonous. Their eyes dripping blood. She has no comparison for what she saw.`,
        `She asks Apollo to deal with it. The scene opens to reveal what she has described: Orestes at the altar, the Furies asleep around him. Apollo is present. He tells Orestes he has never abandoned him, never will; now Orestes must flee to Athens and to the shrine of Athena, where judges will be found and the case resolved. He orders Hermes to escort the fugitive.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'furies', name: 'The Furies' }, { id: 'apollo', name: 'Apollo' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }],
    },
    {
      n: 20,
      title: 'The Eumenides — Parodos',
      tourTitle: 'Parodos: the ghost of Clytemnestra wakes the Furies',
      hook: 'The ghost of Clytemnestra appears and wakes the sleeping Furies. They moan, then wake, then begin their binding song.',
      tour: `The ghost of Clytemnestra appears above the sleeping Furies. She taunts them: while they sleep, their quarry is escaping. She is among the dishonoured dead — killed by her own son — and they have done nothing. She wakes them one by one. The Furies rouse, sniff the air for Orestes's blood, find he has gone, and break into the binding song — their great hymn to their own power, with which they intend to freeze their prey wherever he has fled.`,
      blurb: `The ghost of Clytemnestra rises and wakes the Furies from their sleep — Orestes has escaped Delphi while they slumbered. The Furies wake, find him gone, and begin the binding song: the ancient hymn of their pursuit, meant to freeze a fugitive's limbs and paralyse his mind.`,
      summary: [
        `The ghost of Clytemnestra rises. She speaks to the sleeping Furies with controlled fury: while they sleep in their comfortable den, her killer is escaping. She names her wound — the axe-blow in her side — and demands they pursue him. She has no weight in the underworld because she died by kindred blood, killed by her own son, and the shame of that lies on the Furies who should have answered it.`,
        `The Furies begin to wake. Their waking is terrible — they moan in their sleep, cry out, begin to sniff the air for blood. Apollo appears and drives them out of his shrine with his bow. They are old, they tell him; he is young; he has dishonoured the ancient powers by protecting a matricide. Apollo dismisses them: go to Athens; the case will be judged there.`,
        `The Furies left alone begin the binding song — their great lyric hymn, the only part of the play they own completely. The song is an incantation: we are the daughters of Night, we pursue the blood-guilty, we bind the limbs of fugitives, we dry up their minds. It is not a threat; it is a description of what they are and what they do. And they are going to Athens.`,
      ],
      appears: [{ id: 'furies', name: 'The Furies' }, { id: 'apollo', name: 'Apollo' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }, { slug: 'curse', label: 'The inherited curse' }],
    },
    {
      n: 21,
      title: 'The Eumenides — First Episode',
      tourTitle: 'Orestes at the shrine of Athena',
      hook: 'Orestes reaches Athens and takes hold of the ancient statue of Athena. He is still pursued. He calls for Athena.',
      tour: `Orestes has arrived at Athens and taken hold of the ancient wooden statue of Athena at the Acropolis — the act of a formal suppliant claiming divine protection. He has followed every instruction: he has kept himself ritually pure, he has done what Apollo commanded, he has come to the one place Apollo said would give him justice. He calls on Athena to come and judge his case.`,
      blurb: `Orestes reaches Athens and grasps the ancient statue of Athena as a suppliant. He calls on the goddess to hear his case. The Furies surround the statue, claiming their right to him.`,
      summary: [
        `Orestes stands at the shrine of Athena in Athens — not the Parthenon, which is later, but the ancient wooden image of the goddess at the heart of the Acropolis. He holds the image in the ritual posture of the suppliant. He has done everything required: he has purified himself of blood, he has wandered through the Greek world as Apollo commanded, he has come to Athens. Now he calls for Athena.`,
        `The Furies have followed him and surround the statue. They cannot simply seize him here — the rules of sanctuary apply even to them — but they will prosecute. They describe their own nature and mandate: they pursue those who kill blood relations; they do not distinguish between justified and unjustified; the act and the relationship are the only relevant facts. Orestes killed his mother. That is their whole case.`,
        `Orestes speaks his own defence: he has been purified; he has followed Apollo's command; he is no longer guilty of the blood that was on his hands; he calls on Athena to judge. The stage holds two parties, each with a legitimate claim, neither able to resolve the standoff on its own. Athena must come.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }, { slug: 'law', label: 'The invention of the court' }],
    },
    {
      n: 22,
      title: 'The Eumenides — Second Episode',
      tourTitle: 'Athena arrives and founds the court',
      hook: 'Athena hears the case from both sides and refuses to judge it alone. She summons twelve Athenian citizens and founds the court on the hill of Ares.',
      tour: `Athena appears, having heard Orestes's prayer from afar — from her temple at Troy, in fact. She listens to both parties. The Furies explain their mandate; Orestes explains his situation. Athena says: the case is too grave for any single authority to resolve. She will summon a jury of twelve Athenian citizens. She names the place — the hill of Ares, the Areopagus — and the purpose: a court for homicide cases, to stand forever as the city's legal institution. She goes to summon the jurors.`,
      blurb: `Athena arrives, hears both parties, and announces that she cannot judge this case alone. She founds the Areopagus court — twelve Athenian citizens, on the hill of Ares, to judge cases of homicide. The founding act of law.`,
      summary: [
        `Athena arrives — she has heard the prayer from far away, from her cult at Troy where she was attending to some matter. She sees the situation immediately: a suppliant grasping her statue, a circle of beings she has never seen in the city before. She asks the Furies who they are. They describe themselves: daughters of Night, avengers of blood, haters of the light, born before the Olympian gods.`,
        `Athena hears both sides. The Furies: this man killed his mother; we claim him. Orestes: I have been purified; Apollo commanded this; I beg your protection. Athena considers. The case, she says, is beyond the authority of any single mind to settle — even hers. It is too grave. She will not dismiss either party's claim. Instead, she will assemble a jury of the best citizens of Athens and submit the case to them, with her own vote added.`,
        `She names the institution she is founding: a court to sit on the Areopagus hill, the hill of Ares, forever, to judge cases of homicide. She charges it to hold the middle course between tyranny and anarchy, to cherish awe as the guardian of the law, and to let neither anarchy nor despotism rule the city. Then she leaves to summon the jurors. The founding speech of the Areopagus is also the play's political centrepiece and the trilogy's clearest statement of what civic order is for.`,
      ],
      appears: [{ id: 'athena', name: 'Athena' }, { id: 'orestes', name: 'Orestes' }, { id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'law', label: 'The invention of the court' }, { slug: 'justice', label: 'What justice means' }],
    },
    {
      n: 23,
      title: 'The Eumenides — First Stasimon',
      tourTitle: 'First stasimon: the Furies defend their ancient right',
      hook: 'While the court is being assembled, the Furies sing of what will happen to Athens if their right is overruled.',
      tour: `The Furies sing their stasimon while the jury is being assembled. Their ode is a defence of fear — not panic, but the awe that citizens feel before the law, especially before the oldest laws that govern blood. If the new court acquits Orestes, they warn, the old laws that hold murder in check will be dissolved. Men will commit crimes without fear. The city will suffer. The Furies are not simply defending themselves; they are defending the principle of deterrence.`,
      blurb: `The Furies sing in defence of their own principle — the awe of bloodguilt — and warn that if it is overruled, the old laws that restrain murder will collapse. Their stasimon is a defence of fear as the ground of civic order.`,
      summary: [
        `The Furies sing while the jury assembles. Their ode is addressed both to the city and to the principle they represent. They begin with the admission that they are old — older than the Olympians, older than Zeus himself — and that the new gods have overridden the old rights that were assigned to them at the beginning of the world. They are angry. They have been insulted. They have been bypassed.`,
        `But then the ode turns from complaint to argument. Fear, they say, is the ground of civic order. Not panic — the specific awe that citizens feel before the laws that govern the worst crimes. Strip away that awe and you strip away the deterrent that keeps men from killing. If a jury of mortals acquits a matricide because a god commanded the deed, then any murderer can claim divine sanction and escape. The oldest law — the law of blood — will dissolve.`,
        `The Furies are right that they represent a real principle. The trilogy acknowledges this throughout. What the third play argues is not that their principle is wrong but that the form of its enforcement must change. The fear they invoke must survive the trial; it must find a new channel in the institution Athena is building. This is what Athena will argue to them after the vote.`,
      ],
      appears: [{ id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }, { slug: 'law', label: 'The invention of the court' }],
    },
    {
      n: 24,
      title: 'The Eumenides — Third Episode',
      tourTitle: 'The trial on the Areopagus',
      hook: 'Twelve Athenian citizens take their seats on the hill of Ares. The Furies prosecute. Apollo defends. Orestes testifies. The votes are counted.',
      tour: `The trial of Orestes before the first Athenian jury. The Furies prosecute: did you kill your mother? Yes. Then the blood-right is theirs. Apollo defends: on divine command; and in any case, the mother is not the true parent, only the vessel for the father's seed. Athena charges the jury. The votes are cast into the urns — one for conviction, one for acquittal. When the count comes, the votes are exactly equal.`,
      blurb: `The first trial before the first jury. The Furies prosecute; Apollo defends; Orestes testifies. The votes are counted. They are tied.`,
      summary: [
        `The herald calls the court to order. The jury of twelve Athenian citizens takes their seats. Athena opens the proceedings: the Furies will speak first, as is right for those whose case is being heard. The Furies address Orestes directly: did you kill your mother? He answers plainly — yes, with a drawn sword, I gashed her neck. The Furies press: and who commanded you? Apollo. They turn to Apollo: is this true? Yes.`,
        `Apollo's defence is audacious and troubling. He argues that Orestes was right to kill in obedience to divine command; that Agamemnon's death was worse than Clytemnestra's, because Agamemnon was a man and a king; and — most controversially — that the mother is not the true parent of the child she bears. The true parent is the father who provides the seed; the mother is only the nurse who tends the seedling. As proof, he points to Athena herself: born from the head of Zeus, with no mother at all. Therefore, the killing of a mother is less grave than the killing of a father.`,
        `The Furies make their counter-argument: the mother's blood is kindred blood; that is all that matters; the relationship between mother and child is the deepest human bond; Apollo's biology is irrelevant. The jury votes. Each juror casts a pebble into one of two urns. Athena counts the votes. They are equal — six for conviction, six for acquittal. The decision falls to Athena.`,
      ],
      appears: [{ id: 'orestes', name: 'Orestes' }, { id: 'apollo', name: 'Apollo' }, { id: 'furies', name: 'The Furies' }, { id: 'athena', name: 'Athena' }],
      themes: [{ slug: 'law', label: 'The invention of the court' }, { slug: 'justice', label: 'What justice means' }, { slug: 'furies', label: 'The Furies and the old law' }],
    },
    {
      n: 25,
      title: 'The Eumenides — Second Stasimon',
      tourTitle: 'Second stasimon: the Furies\' rage at the verdict',
      hook: 'The votes are tied. Athena casts for acquittal. Orestes goes free. The Furies begin to threaten the city.',
      tour: `Athena declares her ballot: she votes for acquittal, because she herself was born without a mother and is therefore inclined to favour the male principle in all disputes. With her vote, acquittal has one more than conviction. Orestes is free. He thanks Athena and the court and leaves for Argos. The Furies begin their stasimon of rage: they have been dishonoured by younger gods; they will poison Athens and destroy its crops.`,
      blurb: `Athena casts for acquittal; the tied vote breaks in Orestes's favour. He departs thanking Athens. The Furies begin their stasimon of rage — they have been dishonoured and they will make the city suffer for it.`,
      summary: [
        `Athena announces her vote: she casts for acquittal. Her reasoning has been debated ever since antiquity — she was born without a mother, having sprung from the head of Zeus, and therefore she finds herself inclined in all disputes to support the male principle over the female. With her vote, the acquittal side has a majority. Orestes is free.`,
        `He speaks his gratitude with precision: he thanks Athena, he thanks the court, he pledges on behalf of himself and all future rulers of Argos that Argos will be the eternal ally of Athens, never sending an army against the Attic soil. Then he leaves. The chorus of Furies erupts. They have been robbed, they say, of their ancient right. The younger gods have overruled the older. They will avenge themselves on Athens — they will breathe poison on the earth and the crops, they will blight the city's prosperity, they will undo what this trial has done.`,
        `The stasimon is a threat and an expression of genuine pain. The Furies are not lying — they have been overruled, their principle has been subordinated to a newer institution, and they have no framework to understand how this is not a defeat. It will be Athena's task in the final scene to give them such a framework.`,
      ],
      appears: [{ id: 'athena', name: 'Athena' }, { id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'furies', label: 'The Furies and the old law' }, { slug: 'law', label: 'The invention of the court' }],
    },
    {
      n: 26,
      title: 'The Eumenides — Exodos',
      tourTitle: 'Athena persuades the Furies: the Eumenides',
      hook: 'Athena persuades the raging Furies, one argument at a time, to accept a new home in Athens and a new name. The trilogy ends with a torchlit procession to their shrine under the hill.',
      tour: `Athena speaks to the Furies three times — each time they refuse; each time she offers more — until they finally accept. She offers them a home beneath the Areopagus, permanent honour from the citizens, a share in Athens's prosperity, and a new name: the Eumenides, the Kindly Ones. They accept. The procession forms — citizens, torchbearers, the Furies now robed in crimson, the whole city escorting them to their new shrine. The cycle of vengeance ends not with a final killing but with a ceremony.`,
      blurb: `Athena reasons the Furies through their rage with patient, precise argument: they are not defeated; their principle is preserved in the new court; they are offered permanent honour in Athens. The Furies accept. They become the Eumenides. The torchlit procession closes the trilogy.`,
      summary: [
        `Athena faces the enraged Furies alone. She does not command them. She reasons with them. First she offers what the court has given them: their principle — the avenging of blood — is not abolished; it is now housed in an institution whose authority is permanent. The court she has founded will honour blood-law in all future cases. The Furies have not lost their principle; they have gained a framework within which it will operate forever.`,
        `Then she offers them something more concrete: a home beneath the Areopagus hill, permanent shrines in the city, the worship of the Athenians, a share in the city's harvests and prosperity and good childbirth. She offers them a new name: not the Erinyes, the avenging ones, but the Eumenides, the Kindly Ones. She promises that their blessing will be the condition of the city's prosperity — every household, every harvest, every wedding will be made with their goodwill.`,
        `The Furies deliberate. Athena speaks again. She points to what they would lose by leaving — the rolling tide of time brings greater glory to Athens; if they go, they will one day long for this offer. They deliberate again. And then — in the most carefully composed moment of the entire trilogy — they accept. They bless Athens. The chorus of citizens gathers; torches are lit; the procession forms. The Furies are robed in crimson and escorted to their new shrine under the hill of the Areopagus. The trilogy ends not with blood but with light, not with revenge but with a ceremony of civic incorporation. The curse of the house of Atreus is over.`,
      ],
      appears: [{ id: 'athena', name: 'Athena' }, { id: 'furies', name: 'The Furies' }],
      themes: [{ slug: 'law', label: 'The invention of the court' }, { slug: 'furies', label: 'The Furies and the old law' }, { slug: 'justice', label: 'What justice means' }],
    },
  ],
};
