// The Aeneid — SEO page data for build-seo-pages.cjs
// Virgil, 12 books, Latin epic. Voice: more polished and morally weighted than Homer. Specific.

module.exports = {
  id: 'the-aeneid',
  title: 'The Aeneid',
  author: 'Virgil',
  byline: '29–19 BCE · Latin epic poem',
  titleAccent: 'a guided tour',
  hook: 'The first words of the poem are arms and the man. The Aeneid is the founding myth of Rome — and its great poet was not entirely sure the founding was worth what it cost.',
  themesBlurb: 'Pietas, fate, the price of empire, the weight of Homer, the unreconciled cost of duty.',
  castBlurb: 'Trojans, Italians, gods',
  castDesc: 'A wandering exile, a queen abandoned, a rival defending his land, the Olympians who push the plot.',
  chapterLabel: n => `Book ${n}`,
  genre: ['Epic poetry', 'Classical literature'],

  about: [
    `<em>The Aeneid</em> is the great Latin epic and the founding myth of the Roman state, written by a poet who saw the Republic die and the Empire begin. Virgil composed it in hexameter for the emperor Augustus between 29 and 19 BCE. He was still revising when he died, and left instructions that the unfinished manuscript be burned. Augustus refused. The poem was published in twelve books, with two unfinished half-lines preserved as Virgil left them.`,
    `It is deliberately modeled on Homer. Books I–VI echo the Odyssey of wandering: Aeneas escapes the fall of Troy carrying his father on his back, is shipwrecked at Carthage, loves and abandons Queen Dido, and descends into the underworld where his dead father shows him the parade of unborn Roman souls. Books VII–XII echo the Iliad of war: Aeneas arrives in Italy, fights the local prince Turnus for the land and the king's daughter, and ends the poem standing over a wounded man begging for his life. Dante chose Virgil as his guide through hell because the Aeneid was the closest thing Latin literature had to a sacred text.`,
    `The poem celebrates Roman destiny and refuses to look away from what destiny costs. Aeneas is called <em>pius</em> — devoted, dutiful — more than any other word, with steady ambiguity. He leaves Dido, who kills herself with the sword he leaves behind. He kills Turnus, who has surrendered. He founds the line that will become Rome. The poem does not celebrate any of these acts. It shows founding as costly and asks, with steady refusal to provide a clean answer, whether the cost was worth what was built.`,
  ],
  chaptersSubtitle: 'All 12 books summarized — six of wandering, six of war.',
  chaptersLead: `<p>The Aeneid splits cleanly down the middle. Books I–VI are the wandering — the storm at sea, the queen at Carthage, the long story of Troy's fall, the descent into the underworld. Books VII–XII are the war for Italy — the broken peace, the gathering of allies, the death of young Pallas, the final duel. The first half is in conversation with the Odyssey; the second half with the Iliad. Virgil knew his readers would hold both Homeric poems in their heads as they read.</p>`,
  themesByline: 'Five threads through the poem',
  themesLead: `The Aeneid is a founding poem and a grief poem and a poem about the cost of duty, all at once. These five threads carry it. None of them resolve cleanly.`,

  groups: [
    { label: 'Books I–VI · The Wandering', subtitle: 'Storm, Carthage, Troy remembered, the underworld.', chapters: [1, 2, 3, 4, 5, 6] },
    { label: 'Books VII–XII · The War', subtitle: 'Italy, the broken peace, the duel for Lavinia.', chapters: [7, 8, 9, 10, 11, 12] },
  ],

  themes: [
    {
      slug: 'pietas',
      title: 'Pietas',
      greek: '<em>pietas</em> — the Roman virtue of duty to gods, family, and state',
      preview: 'Aeneas is called pius — devoted, dutiful — more than any other word in the poem. The virtue is what makes him Roman rather than Greek. The poem keeps asking what it costs.',
      essay: [
        `Virgil calls Aeneas <em>pius</em> — devoted, dutiful — more than a hundred times. The Latin word is wider than the English "pious." It means duty to the gods, duty to one's family, duty to the state, all at once. It is the Roman virtue, the quality the empire wanted to see in itself, and Virgil makes it Aeneas's defining attribute. Aeneas does not have Achilles's rage or Odysseus's cunning. He has pietas, and that has to be enough.`,
        `The poem is unsparing about what pietas requires. It requires Aeneas to leave Dido, who has saved him and loved him, because Jupiter has ordered him to Italy. It requires him to drag his elderly father out of burning Troy on his back and lose his wife in the smoke without turning around. It requires him to kill a man who is begging for his life because that man has killed a young friend Aeneas had promised to protect. Each act is correct. Each act is also costly in a way the poem refuses to soften.`,
        `Virgil's question is whether a man who suppresses every personal desire for collective purpose is admirable or hollow. He never quite answers it. Aeneas weeps often, but the weeping does not change what he does. He is the most obedient hero in classical literature and the least free. The Greeks chose their fates with their eyes open; Aeneas executes one. The poem invites you to admire him and to mourn the man inside the duty, in the same line, without resolving the tension.`,
        `The contrast with Homer is exact. Achilles in the Iliad rages against his commander and refuses to fight; Odysseus in the Odyssey lies to anyone in his way to get home. Both act on what they want. Aeneas almost never does. Pietas is what makes him Roman, and pietas is what the poem treats as both the highest virtue and the heaviest cost. The empire was built on it. So was the unhappiness of every founder it required.`,
      ],
      where: [
        { n: 2, label: 'Book II (carrying his father out of Troy)' },
        { n: 4, label: 'Book IV (leaving Dido)' },
        { n: 6, label: 'Book VI (the prophecy of Rome)' },
        { n: 12, label: 'Book XII (killing Turnus)' },
      ],
    },
    {
      slug: 'fate',
      title: 'Fate and Roman destiny',
      greek: '<em>fatum</em> — the spoken decree of the gods, the future already written',
      preview: 'The poem is told from inside a future already known. Aeneas does not choose where he is going; Rome is the destination set down before he is born, and the gods announce it again and again.',
      essay: [
        `The Aeneid is told from inside a future already known. The reader knows Rome is coming. Augustus has already founded the empire by the time Virgil writes. The characters know it too, in pieces — Jupiter announces it to Venus in Book I; the Sibyl prophesies it at Cumae; Anchises shows it as a parade of unborn souls in the underworld in Book VI; the shield Vulcan forges for Aeneas in Book VIII shows scenes from Roman history that have not happened yet, including the battle of Actium where Augustus defeated Antony. The poem keeps lifting its eyes from the action to the long arc.`,
        `This makes the Aeneid feel different from Homer. The Iliad and the Odyssey are urgent because their characters do not know the outcome; in the Aeneid, the outcome is the subject. Aeneas's choices feel less like decisions than like the working out of something already decided. He does not choose Italy; Italy is set down for him. He does not choose to leave Dido; the order arrives from Jupiter through Mercury. He does not choose to kill Turnus; he is acted on, in the final lines, by a fury he cannot name.`,
        `Virgil is exact about this. The gods of the poem are powerful but bounded. Juno hates Troy and tries for twelve books to stop the founding; she cannot. Venus protects her son but cannot remove the suffering from his path. Even Jupiter, the king of the gods, says he is administering fate, not making it. The frame of the poem is bigger than any of its actors. They are all working a destiny set down before them.`,
        `What this gives the poem is a strange grandeur and a strange melancholy. Rome is going to be built; that much is certain. But the men and women who build it are caught in something they did not author and cannot refuse, and Virgil keeps showing the cost. Anchises in the underworld shows Aeneas the parade of Rome's future heroes — and weeps for the young Marcellus, who will die early, before Aeneas's eyes. The future is glorious. It also has its dead.`,
      ],
      where: [
        { n: 1, label: 'Book I (Jupiter\'s prophecy to Venus)' },
        { n: 6, label: 'Book VI (the parade of Roman souls)' },
        { n: 8, label: 'Book VIII (the shield of Aeneas)' },
        { n: 12, label: 'Book XII (Juno yields to fate)' },
      ],
    },
    {
      slug: 'dido',
      title: 'Dido and the cost of empire',
      greek: '<em>infelix Dido</em> — unhappy Dido, the queen the founding requires',
      preview: 'Dido is the most fully realised character in the poem. She loves the wrong man at the wrong moment, and her death — by the sword Aeneas leaves behind — is the place where Virgil\'s loyalty to Rome most visibly cracks.',
      essay: [
        `Dido is the most fully drawn character in the Aeneid. She is the widowed queen of Carthage, who has built a great city in exile after her husband's murder. She receives the storm-battered Trojan fleet, listens to Aeneas tell the long story of Troy's fall, and falls catastrophically in love with him during a hunt interrupted by a divine storm. Books I and IV are her books. They are the emotional center of the poem.`,
        `What happens to her is not presented as simple. Aeneas does not seduce her cynically; the gods arrange it. He does not abandon her lightly; Jupiter sends Mercury with an explicit order to leave. He does what pietas requires. Virgil does not let any of this make Dido's grief less real. She rages, pleads, curses his line, and finally builds a pyre in the courtyard, climbs it, and falls on the sword Aeneas left behind. Her last words are a curse — that her people and his will be enemies forever, and that an avenger will rise from her bones. The Punic Wars, Hannibal at the gates of Rome, are seeded into the poem here.`,
        `The Carthaginian queen, in Roman eyes, was supposed to be a foreign menace; Dido is the great enemy seen from inside her own life. She is not vilified. She is given the most affecting language in the poem and treated as a tragic figure on the scale of Sophocles. When Aeneas meets her again in the underworld in Book VI and tries to explain himself, she turns away from him without speaking and walks back into the shade — and Virgil treats her silence as more eloquent than any speech.`,
        `The technique is the heart of Virgil's method. Rome is built; the queen at Carthage dies for it; the poem will not pretend otherwise. Dido becomes the figure for every people Rome will later destroy — the Carthaginians most directly, but also the Gauls, the Britons, the cities of Asia. Their grief is given the most beautiful language in the poem. It does not stop the founding. It refuses to be forgotten while the founding goes on.`,
      ],
      where: [
        { n: 1, label: 'Book I (Dido welcomes the Trojans)' },
        { n: 4, label: 'Book IV (love, abandonment, and her death)' },
        { n: 6, label: 'Book VI (her shade in the underworld)' },
      ],
    },
    {
      slug: 'homer',
      title: 'The shadow of Homer',
      greek: '<em>imitatio</em> — the deliberate echo, set against the original',
      preview: 'Books I–VI are an Odyssey of wandering; Books VII–XII are an Iliad of war. Virgil knew his readers would hold both Homeric poems in their heads. Where Aeneas falls short of Odysseus or Achilles is sometimes the whole point.',
      essay: [
        `The Aeneid is the most deliberate piece of literary imitation in classical literature. Virgil's readers had Homer memorized, and Virgil knew it. The first half of his poem rewrites the Odyssey: a hero blown off course by the gods, taken in by a queen on a foreign shore, telling the story of his past at her dinner table, descending to the underworld, finally arriving home. The second half rewrites the Iliad: an arriving army, a war over a woman promised to one man and claimed by another, a young friend killed in battle whose death drives the hero to a final duel.`,
        `The echoes are exact and constant. Aeneas in Book III meets the same monsters Odysseus met — Polyphemus, the Harpies — but they are already familiar to the reader, encountered earlier in another poem. Dido in Book IV plays the role of Calypso and Circe combined, with the morality reversed: the woman is sympathetic, the leaving is the wrong some part of the poem cannot fully forgive. The shield of Aeneas in Book VIII echoes the shield of Achilles in Iliad XVIII, but where Achilles's shield shows the timeless human world, Aeneas's shows specific scenes from the future history of Rome. Pallas dies in Book X the way Patroclus dies in Iliad XVI — and in both poems, his death is what releases the hero into a final, terrible rage.`,
        `What this does is make the Aeneid double-voiced. Every scene is what is happening in Italy and what happened in Greece, at the same time. The reader is being asked to compare. Sometimes Aeneas is a lesser figure than the Greek hero he echoes — he does not have Odysseus's wit, does not have Achilles's overwhelming force. Sometimes the comparison goes the other way: Aeneas chooses the future, where the Greek heroes only chose themselves. The poem invites both readings and commits to neither.`,
        `Virgil's larger argument is that Roman epic is something different from Greek. Homer's heroes are individuals; Virgil's hero is an instrument of the state. Homer's gods are vivid and petty; Virgil's gods are administrators of fate. Homer's wars are about who wins; Virgil's war is about what kind of civilization wins, and at what cost. The Aeneid is in conversation with Homer about the very meaning of heroism — and is never fully resolved on whether Roman heroism is an advance or a loss.`,
      ],
      where: [
        { n: 3, label: 'Book III (Odyssey monsters revisited)' },
        { n: 4, label: 'Book IV (Dido as Calypso, reversed)' },
        { n: 8, label: 'Book VIII (the shield, Roman not human)' },
        { n: 10, label: 'Book X (Pallas as Patroclus)' },
      ],
    },
    {
      slug: 'ending',
      title: 'The ending — Turnus and Pallas\'s belt',
      greek: '<em>furiis accensus</em> — kindled by furies, the last act of the poem',
      preview: 'The poem ends mid-duel. Turnus has been wounded; he is begging for his life; Aeneas hesitates and then sees the belt of dead Pallas on Turnus\'s shoulder and kills him. The Aeneid ends in twelve final lines that have unsettled readers for two thousand years.',
      essay: [
        `The Aeneid does not end with Rome founded, or with a wedding, or with a return home. It ends in the middle of a duel. Aeneas has driven Turnus to the ground. Turnus is wounded; he raises his hand; he speaks. He surrenders. He asks Aeneas to give his body back to his father, or to spare him for the sake of the old man waiting in the city. He says: you have won. Take Lavinia. Hate me no further.`,
        `Aeneas hesitates. The poem says clearly that he is about to spare him. Then he sees the sword-belt of young Pallas on Turnus's shoulder — the trophy Turnus stripped from Pallas's body in Book X. Pallas was the son of Aeneas's ally Evander, sent to fight at Aeneas's side, killed in his first real battle. Aeneas had promised to bring him home safe. He could not. The belt is the visible proof of the failure. Aeneas, in the poem's word, is kindled by furies. He drives the spear through Turnus's chest. The poem ends in the next four lines: Turnus's limbs go cold; his life flees with a groan, indignant, into the shadows below.`,
        `The ending has unsettled readers for two thousand years. Augustine could not bear it. Dante kept thinking about it. Modern critics divide sharply: some read the killing as just — Turnus deserves it; Pallas demands it; the founding requires it. Others read it as the final crack in the poem's loyalty to Rome — Aeneas, the man who has been called <em>pius</em> for twelve books, kills a surrendering enemy in a fit of rage, and the poem ends not on the founding but on a soul going down to the underworld unwillingly. The same word — <em>indignant</em> — closes the poem and closed the death of Camilla earlier; Virgil seems to be marking the loss as a loss.`,
        `What the ending suggests, without saying it, is that the founding cannot be made clean. Aeneas's last act in the poem is not a wedding or a city-laying; it is a killing, done out of grief for a young man he could not save, on a man who was begging. The Aeneid does not provide a triumphal ending because Virgil cannot give one. He has spent twelve books showing what Rome costs. He will not, in the last lines, pretend the cost was paid by someone else.`,
      ],
      where: [
        { n: 10, label: 'Book X (Pallas killed; Turnus takes the belt)' },
        { n: 11, label: 'Book XI (Pallas\'s body sent home)' },
        { n: 12, label: 'Book XII (the duel and the final lines)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Aeneas', role: 'Trojan exile, founder', body: `Trojan prince, son of the goddess Venus and the mortal Anchises, survivor of Troy's fall. Carries his father out of the burning city on his back; loses his wife in the smoke. Storm-driven to Carthage; loves and leaves Queen Dido; descends to the underworld and is shown the parade of unborn Roman souls. Lands in Italy and fights the local prince Turnus for the land and the king's daughter. Virgil calls him <em>pius</em> — devoted, dutiful — more than any other word in the poem, with steady ambiguity. Whether his obedience makes him heroic or hollow is the question the Aeneid refuses to settle.` },
    { name: 'Dido', role: 'Queen of Carthage', body: `The widowed queen who has built a great city in exile after her husband Sychaeus was murdered by her own brother. Receives the storm-battered Trojan fleet, listens to Aeneas tell the long story of Troy's fall, and falls catastrophically in love with him during a hunt interrupted by a divine storm. When Jupiter orders Aeneas to leave, she rages, pleads, curses his line, and falls on the sword he leaves behind on a great pyre as his ships sail away. Her books (I and IV) are the emotional heart of the Aeneid and the place where Virgil's loyalty to Rome most visibly cracks.` },
    { name: 'Turnus', role: 'Prince of the Rutulians', body: `Betrothed to the Latin princess Lavinia before Aeneas arrived to claim her. He is not a villain. He is a young warrior defending the woman he was promised and the land he was born in, and the poem makes you understand why his fight is his to fight. The last six books are largely his story. He kills young Pallas in Book X and strips the boy's sword-belt as a trophy — a decision that will undo him. He dies in the final lines, surrendering, asking for mercy that Aeneas cannot bring himself to grant.` },
    { name: 'Anchises', role: 'Aeneas\'s father', body: `Aeneas's mortal father, once the lover of Venus in his youth. Old and frail when Troy falls; carried out of the burning city on his son's back. Travels with the fleet through the years of wandering and dies peacefully in Sicily before they reach Italy. In Book VI, Aeneas descends to the underworld and finds him standing in the Elysian Fields, where he shows his son the parade of unborn Roman souls — Romulus, Caesar, Augustus, the heroes of the Republic. The scene is the philosophical heart of the poem. The future the living are sacrificing for is shown as actually present, just below.` },
    { name: 'Juno', role: 'Queen of the gods', body: `Queen of the gods, wife and sister of Jupiter, implacable enemy of Troy ever since Paris judged Venus more beautiful than her. Drives the plot through twelve books of divine stubbornness — the storm at sea that opens the poem, the love at Carthage, the war in Italy, the rage that takes hold of Turnus and the Italian queen Amata. Even at the end, when Jupiter has overruled her, she negotiates terms: the Trojans must take the Latin name and language, Italy must remain Italy. She does not lose so much as accept a settlement.` },
    { name: 'Venus', role: 'Aeneas\'s mother', body: `Goddess of love, mother of Aeneas, counterweight to Juno on Olympus. Pleads with Jupiter for her son's safety in Book I and sets the long prophecy of Rome in motion; appears to Aeneas disguised as a huntress and guides him to Carthage; reveals to him in burning Troy the gods who are tearing the city down. Persuades Vulcan to forge the divine armor and the engraved shield in Book VIII. Heals his wound with a magical herb in Book XII so he can return to the duel. The gods of the Aeneid are powerful; they are not omnipotent against fate, and a mother who is also a goddess can only do so much.` },
  ],

  castSubtitle: 'Trojans, Italians, gods.',
  castLead: `<p>The Aeneid has a famously bicultural cast. Three layers: the Trojan exiles led by Aeneas, the Italian peoples whose land they have come to claim, and the Olympian gods who push the plot. The poem treats both human sides with care — there are no faceless enemies. Turnus and Camilla are as fully drawn as Aeneas and his Trojan companions, and the Italian dead are mourned with the same language as the Trojan dead.</p>
      <p>The cards below cover the main figures. Many minor warriors who get a paragraph of biography just before they die — a technique Virgil borrowed from Homer — are not listed here; the reader will encounter them in the chapter pages.</p>`,
  castGroups: [
    {
      label: 'The Trojans',
      subtitle: 'The exiles led by Aeneas to Italy.',
      characters: [
        { id: 'aeneas', tag: 'Mortal', name: 'Aeneas', epithet: 'Trojan prince, founder of Rome\'s lineage', body: `The central figure of the poem. Son of the goddess Venus and the mortal Anchises. Survives the fall of Troy by carrying his father out of the burning city on his back; loses his wife Creusa in the smoke. Storm-driven to Carthage in Book I, loves and leaves Dido in Book IV, descends to the underworld in Book VI, arrives in Italy in Book VII, fights the war for Lavinia in VIII–XII. Called <em>pius</em> — devoted, dutiful — more than any other word in the poem, with steady ambiguity. Kills Turnus in the final lines.`, appears: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12] },
        { id: 'anchises', tag: 'Mortal', name: 'Anchises', epithet: 'Aeneas\'s father, beloved of Venus', body: `Aeneas's mortal father, once the lover of Venus in his youth. Old and frail when Troy falls; Aeneas carries him out of the burning city on his back. Travels with the fleet through the years of wandering and dies peacefully in Sicily before they reach Italy. In Book VI, Aeneas descends to the underworld and finds him in the Elysian Fields, where he shows his son the parade of unborn Roman souls. The scene is the philosophical heart of the poem.`, appears: [2, 3, 5, 6] },
        { id: 'ascanius', tag: 'Mortal', name: 'Ascanius (Iulus)', epithet: 'Aeneas\'s son', body: `Aeneas's young son, also called Iulus. The Julian line — Julius Caesar, Augustus — claimed descent from him through this name. A child during Troy's fall, led by the hand through the burning city. Leads the Trojan boys in mounted exercises during the funeral games for Anchises in Book V. In Book IX, with his father away, he makes his first kill in battle — Apollo himself comes down to congratulate him and tell him to fight no more.`, appears: [2, 5, 9] },
        { id: 'creusa', tag: 'Mortal', name: 'Creusa', epithet: 'Aeneas\'s first wife, lost in Troy\'s fall', body: `Aeneas's wife in Troy. Lost during the escape from the burning city — Aeneas turns and finds her gone, retraces his steps through the smoke, calls her name in the empty streets. Her ghost appears to him and tells him not to grieve: she is held by the gods; he must seek a new kingdom in the west, and a new wife. She vanishes three times as he tries to embrace her. The scene is one of the most painful in the poem.`, appears: [2] },
      ],
    },
    {
      label: 'The Italians',
      subtitle: 'The peoples whose land Aeneas has come to claim.',
      characters: [
        { id: 'dido', tag: 'Mortal', name: 'Dido', epithet: 'Queen of Carthage', body: `The widowed queen of Carthage, who has built a great city in exile after her husband Sychaeus was murdered by her brother. Receives the storm-battered Trojan fleet, listens to Aeneas tell the story of Troy, and falls catastrophically in love with him during a hunt interrupted by a divine storm. When Jupiter orders Aeneas to leave, she rages, pleads, and finally kills herself on a funeral pyre with the sword he leaves behind, cursing his line. In Book VI, her shade in the underworld turns away from Aeneas without speaking.`, appears: [1, 4, 6] },
        { id: 'turnus', tag: 'Mortal', name: 'Turnus', epithet: 'Prince of the Rutulians, Aeneas\'s rival', body: `Betrothed to the Latin princess Lavinia before Aeneas arrived to claim her. Incited by Juno's fury Allecto, raises an army against the Trojans and breaks King Latinus's peace. Kills young Pallas in Book X and strips his sword-belt as a trophy. Refuses peace in Book XI; challenges Aeneas to single combat in Book XII. Defeated, wounded, and surrendering — he is killed in the final lines of the poem when Aeneas sees Pallas's belt on his shoulder.`, appears: [7, 9, 10, 11, 12] },
        { id: 'latinus', tag: 'Mortal', name: 'Latinus', epithet: 'King of Latium, father of Lavinia', body: `The aged king of the Latins. Welcomes the Trojans in Book VII and offers Aeneas his daughter Lavinia in fulfillment of an oracle. Juno's interference undoes the peace; the king cannot hold his people back from war. In Book XI he calls a war council and urges peace, but is overruled. A weary king caught between fate and his own people, witness to the final duel that ends the war.`, appears: [7, 11, 12] },
        { id: 'lavinia', tag: 'Mortal', name: 'Lavinia', epithet: 'Latin princess, destined bride of Aeneas', body: `The daughter of King Latinus, promised to Aeneas in fulfillment of a prophecy. Her mother Amata and the Rutulian prince Turnus oppose the match, and the war breaks out over her. She has very few lines in the poem — Virgil shows her almost entirely through what is done over her, around her, for and against her. Turnus fights and dies for her. Aeneas's victory secures her as his bride and unites the two peoples.`, appears: [7, 12] },
        { id: 'evander', tag: 'Mortal', name: 'Evander', epithet: 'Greek king of Pallanteum, Aeneas\'s ally', body: `An old Greek exile who has founded a small settlement on the Palatine — the future site of Rome. Welcomes Aeneas as a kinsman, walks him through the landscape that will one day be the Forum, and sends his only son Pallas to fight at his side. Receives Pallas's body in Book XI with a grief so terrible Virgil pauses the war to grieve with him.`, appears: [8, 11] },
        { id: 'pallas', tag: 'Mortal', name: 'Pallas', epithet: 'Evander\'s son, young warrior', body: `The young son of King Evander, sent by his father to fight alongside Aeneas. Aeneas promises to bring him home safe and treats him as a son. Fights heroically in his first real battle in Book X, but is killed by Turnus, who strips his sword-belt as a trophy. His death becomes the emotional core of the war and the proximate cause of Aeneas's killing of Turnus in the poem's final lines.`, appears: [8, 10, 11] },
        { id: 'camilla', tag: 'Mortal', name: 'Camilla', epithet: 'Volscian warrior maiden', body: `A maiden warrior dedicated to the goddess Diana, swift enough to run across wheat without bending the stalks. Listed among the warriors rallying to Turnus in Book VII. Leads the Volscian cavalry in a brilliant charge in Book XI; kills many Trojans before being struck down by a javelin from ambush. Virgil mourns her death in the same word — <em>indignant</em> — that he will use four books later for Turnus.`, appears: [7, 11] },
        { id: 'sibyl', tag: 'Mortal', name: 'The Sibyl', epithet: 'Prophetess of Cumae', body: `The priestess of Apollo at Cumae in Italy. Aeneas comes to her in Book VI to ask for entry to the underworld; she foretells the wars he will face in Italy and guides him through the world below to the Elysian Fields where his father Anchises waits. The descent and return are her work. She speaks the most famous line in the poem about the underworld: easy is the descent — the climb back is the hard one.`, appears: [6] },
      ],
    },
    {
      label: 'The gods',
      subtitle: 'The Olympians who push the plot.',
      characters: [
        { id: 'jupiter', tag: 'God', tagClass: 'god', name: 'Jupiter', epithet: 'King of the gods, arbiter of fate', body: `The supreme Olympian. Bound, in Virgilian theology, by fates set down before any of this began; he administers them rather than authoring them. Reassures Venus in Book I that Aeneas's destiny is secure — Rome will be founded, Augustus will rule. Sends Mercury to Carthage in Book IV to order Aeneas on. Forbids the gods from interfering in Book X; brokers the final peace with Juno in Book XII.`, appears: [1, 4, 10, 12] },
        { id: 'juno', tag: 'God', tagClass: 'god', name: 'Juno', epithet: 'Queen of the gods, enemy of the Trojans', body: `Wife and sister of Jupiter, implacable enemy of Troy ever since Paris judged Venus more beautiful than her. Sends the storm that opens the poem in Book I; conspires with Venus to bring Aeneas and Dido together in Book IV; unleashes the fury Allecto in Book VII to incite the war in Italy. Yields to fate at the end of Book XII — but only on the condition that the Trojans take the Latin name and language. She does not lose so much as negotiate terms.`, appears: [1, 4, 7, 12] },
        { id: 'venus', tag: 'God', tagClass: 'god', name: 'Venus', epithet: 'Goddess of love, Aeneas\'s mother', body: `Mother of Aeneas, counterweight to Juno on Olympus. Pleads with Jupiter for her son's safety in Book I; appears to him disguised as a huntress and guides him to Carthage. Reveals to him in Book II the gods who are destroying Troy. Persuades Vulcan to forge divine armor for him in Book VIII. Heals his wound with a magical herb in Book XII so he can return to the final duel.`, appears: [1, 2, 8, 12] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'The storm and the welcome at Carthage', tourTitle: 'Storm and Carthage', hook: 'I sing of arms and the man — the poem opens with a storm at sea and ends, that night, with a queen who has just begun, against her will, to love.',
      tour: `The poem opens with its famous first line — "I sing of arms and the man" — and a question: why is heaven so angry with one good man? Juno, hating Troy, asks Aeolus to wreck the Trojan fleet. The storm sinks one ship; Neptune calms the sea, furious at the trespass. Aeneas, with seven ships left, lands on an unknown African shore. His mother Venus, in the form of a huntress, sends him under a cloak of mist to Carthage, where Queen Dido receives him with extraordinary generosity. At the welcoming feast, Venus has Cupid take the place of Ascanius and sit on Dido's lap. The queen, kissing the false child, begins to fall in love.`,
      blurb: `The poem's first day. Juno's storm wrecks the Trojan fleet. Aeneas is washed up at Carthage, where Queen Dido welcomes him with extraordinary generosity. Venus, scheming for her son's safety, has Cupid take the place of Aeneas's young son Ascanius and sit on the queen's lap during the welcoming feast; Dido — against her own will — begins to love. The book ends with her asking the stranger at her table to tell the story of Troy.`,
      summary: [
        `The poem opens with its famous first line — <em>arma virumque cano</em>, "I sing of arms and the man" — and a question. Why is heaven so angry with one good man? The answer is Juno. She hates the Trojans because of an old judgment in which Paris chose Venus over her, and she has heard a prophecy that Trojan descendants will one day destroy her favorite city of Carthage. She goes to Aeolus, the god who keeps the winds, and orders him to wreck the Trojan fleet. The storm hits at sea. One ship goes down with all hands; the rest are scattered. Neptune, hearing the noise and furious at the trespass, rises and calms the storm with one rebuke.`,
        `Aeneas, with seven ships of his original twenty, finds an African harbor and lands. He climbs a hill alone and shoots seven deer for his hungry men. He speaks the line Dante will quote: "Perhaps one day it will give us pleasure to remember even these things." Then his mother Venus meets him in the woods disguised as a huntress, tells him whose country he is in — Carthage, the new city of the widowed queen Dido — and wraps him and his companion Achates in a cloud of mist. They walk into the half-built city and watch from inside the cloud as Dido holds court.`,
        `The cloud parts; Aeneas appears; Dido receives him with extraordinary courtesy and invites the Trojans to a banquet. Venus, fearing for her son in this Juno-favored city, has her own son Cupid take the form of Aeneas's young Ascanius and sit on Dido's lap that night. The queen, kissing what she thinks is a child, begins — against her own will — to love. The book closes with her asking Aeneas to tell the story of Troy. He does, in the next two books.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'dido', name: 'Dido' }, { id: 'venus', name: 'Venus' }, { id: 'juno', name: 'Juno' }, { id: 'jupiter', name: 'Jupiter' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'dido', label: 'Dido' }],
    },
    {
      n: 2, title: 'The fall of Troy', tourTitle: 'The fall of Troy', hook: 'Aeneas tells the story Homer never told. The wooden horse, the slaughter inside the walls, his father on his back, his wife lost in the smoke.',
      tour: `Aeneas walks the reader directly into the night Homer left out. The Greeks pretend to sail away, leaving a wooden horse on the beach. The Trojans, against Laocoön's warning, drag it inside the walls; that night, Greek soldiers slip out of its belly. Aeneas wakes to the city already burning. He fights through the streets and reaches Priam's palace just as the old king is murdered at his own altar. His mother Venus reveals the gods themselves tearing the walls of Troy down. He lifts old Anchises onto his shoulders, takes young Ascanius by the hand, and leads them out through the smoke. His wife Creusa, following, is gone; her ghost appears, foretells his future kingdom in the west, and vanishes.`,
      blurb: `Aeneas tells Dido the story of Troy's fall. The wooden horse, the slaughter at Priam's altar, Aeneas carrying his old father out of the burning city on his back, his small son led by the hand, his wife Creusa lost in the smoke. The book is the poem's most direct argument that pietas — duty to family, gods, and what comes next — is the only thing that can be salvaged when a world ends.`,
      summary: [
        `Aeneas, at Dido's table, walks the reader directly into the night Homer left out. The Greeks have given up the siege and sailed away — or appear to. They leave a great wooden horse on the beach with an inscription claiming it is an offering to Athena. The priest Laocoön throws his spear into its side and warns the city against trusting Greek gifts; two enormous serpents rise out of the sea, kill him and his sons in front of everyone, and disappear into the temple of Athena. The Trojans take this as confirmation and drag the horse inside the walls.`,
        `That night the Greek soldiers hidden in the horse's belly open the gates. The army, returned secretly from behind Tenedos, pours in. Aeneas wakes from a dream of the dead Hector — bloody, dragged in the dust — warning him to flee. The city is already burning. He fights through the streets and reaches Priam's palace just as the old king is murdered at his own altar by Achilles's son Pyrrhus. Aeneas sees Helen hiding in a corner and is ready to kill her in his rage. His mother Venus appears, stays his hand, and reveals to him the gods themselves dismantling the walls of Troy. The war is over. He must save what he can.`,
        `He goes home. His father Anchises, old and stubborn, refuses to leave; an omen of flame around the head of young Ascanius finally moves him. Aeneas lifts his father onto his shoulders, takes his small son by the hand, tells his wife Creusa to follow, and goes out through the smoke. He reaches the rendezvous and finds Creusa gone. He runs back into the burning city alone, calling her name. Her ghost appears at last — she is held by the gods, he must go on, find a kingdom in the west, find a new wife. She vanishes three times as he tries to embrace her. He gathers the survivors at Mount Ida and begins building a fleet.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'anchises', name: 'Anchises' }, { id: 'creusa', name: 'Creusa' }, { id: 'ascanius', name: 'Ascanius' }, { id: 'venus', name: 'Venus' }],
      themes: [{ slug: 'pietas', label: 'Pietas' }, { slug: 'fate', label: 'Fate' }],
    },
    {
      n: 3, title: 'The wanderings of Aeneas', tourTitle: 'The wanderings', hook: 'Years at sea. Wrong landfalls, false oracles, prophetic warnings. Anchises dies in Sicily; the journey is unfinished.',
      tour: `Aeneas continues his story. The fleet sails to Thrace, where a bleeding bush — a murdered Trojan — sends them on. They consult Apollo at Delos, misread the oracle, sail to Crete, are driven out by plague. The household gods name Italy in a dream. They bear west. The harpies in the Strophades curse them to eat their own tables before they find a home. They pass the cave of the Cyclops, rescuing a Greek left behind by Odysseus. They reach Sicily — and there, before Italy, Anchises dies of old age. Aeneas breaks off the story; Dido has been listening with her whole self.`,
      blurb: `Years at sea, told in one book. False oracles, monstrous harpies, the cave of the Cyclops where Odysseus's old crewman has been left behind. The fleet finally reaches western Sicily, where Anchises — Aeneas's father, the man he carried out of Troy — dies before they can reach Italy. The journey, like the story, is unfinished when Aeneas stops, and Dido has been listening with her whole self.`,
      summary: [
        `Aeneas's story continues. After leaving Troy, he and his band of survivors built a fleet at Mount Ida and sailed for the unknown. They went first to Thrace. There, gathering branches for a sacrifice, Aeneas pulled a sapling from a mound and saw it bleed. The voice of a murdered Trojan friend, killed there years before, told him the place was cursed; they reburied the body and sailed on. They went to Delos, the holy island, and consulted Apollo's oracle. The god told them to seek the land their ancestors came from. Anchises took this to mean Crete. They sailed to Crete and began building a city; a plague broke out. The household gods of Troy appeared to Aeneas in a dream and corrected the reading: not Crete, but Italy.`,
        `The fleet bore west and was caught by storms and driven to the Strophades, an island of monstrous harpies who fouled their food. The harpy queen Celaeno cursed them: they would not found their city until hunger made them eat their own tables. They sailed on. They passed the coast of mainland Greece, where they met the Trojan princess Andromache — Hector's widow — now married to a fellow Trojan exile and ruling a small replica of Troy in Epirus. The reunion was painful and brief.`,
        `They rounded Italy and the Sicilian coast. They passed close to the cave of the Cyclops and were begged for rescue by a Greek who had been left behind by Odysseus's expedition; they took him aboard, then heard the giant Polyphemus crashing through the surf behind them and rowed for their lives. They reached western Sicily. There, before they could continue to Italy, Anchises died. Aeneas buried his father, performed the rites, and the storm that opened Book I drove the fleet from Sicily to Carthage — which is where Dido finds him, and where he stops his tale. The queen's heart, by now, is undone.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'anchises', name: 'Anchises' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'homer', label: 'Homer' }],
    },
    {
      n: 4, title: 'Dido, love, and the leaving', tourTitle: 'Dido and the leaving', hook: 'The most painful book in the poem. Dido loves; Aeneas is ordered on; Dido kills herself with the sword he leaves behind.',
      tour: `Dido is in love. Juno and Venus conspire to bring the lovers together. During a hunt, a divine storm scatters the party; Dido and Aeneas take shelter in a cave. The queen calls it marriage. Aeneas has lost his sense of mission. Jupiter sees and sends Mercury down with an explicit order: leave. Aeneas prepares the fleet in secret. Dido finds out. She rages, pleads, curses him. He cannot answer her grief; he can only repeat the order. The fleet sails before dawn. Dido has a great pyre built in the courtyard, climbs it, calls down a curse, and falls on the sword he left behind. The ships, already at sea, see the smoke rise from the city.`,
      blurb: `The emotional center of the poem. Dido and Aeneas come together in a cave during a hunt; the queen calls it marriage. Jupiter, watching, sends Mercury with an explicit order: leave. Dido — abandoned — builds a pyre in the courtyard, climbs it, falls on the sword Aeneas leaves behind, and curses his line. Her last words seed the Punic Wars and the rise of Hannibal. The Trojan ships, already at sea, see the smoke rise from the city.`,
      summary: [
        `Dido is in love and undone by it. She has not slept; she keeps Aeneas at her side day and night; the half-built towers of Carthage stand frozen because the queen has stopped giving orders. She tells her sister Anna everything. Anna, kindly, encourages her: the city is exposed, an alliance with this Trojan prince could only help. Juno and Venus, scheming for their own ends, agree to push the lovers together. During a great hunt the next day, Juno sends a storm that scatters the party. Dido and Aeneas, separated from the others, take shelter together in a cave. Virgil leaves what happens there to the reader; he says only that this day was the cause of all that followed. Dido, after, calls it marriage. Rumor flies through Africa.`,
        `Word reaches Jupiter that Aeneas has stopped. He is wearing Tyrian purple now, has built towers in Dido's city, has forgotten Italy. Jupiter sends Mercury down with an explicit message: leave at once. Mercury delivers the order. Aeneas, stricken, knows he has no choice. He gives quiet orders to ready the fleet in secret. Dido finds out almost immediately and confronts him. She speaks one of the longest and most painful speeches in classical literature — pleads, threatens, curses, mocks. Aeneas does not argue. He says, terribly, "I do this against my will," and tells her that Italy is not his choice but the gods'. He leaves her standing in the hall and goes to the harbor.`,
        `The fleet sails before dawn. Dido watches from the wall. She has a great pyre built in the courtyard on a pretext — she will burn the things he left behind. She climbs it. She calls down the curse — her people and his enemies forever, an avenger to rise from her bones — and falls on his sword. Her sister Anna runs to her and finds her dying. Iris is sent down by Juno to release her struggling soul. The Trojan ships, already at sea, see the smoke rise from the city. Aeneas does not know what it is. He keeps sailing.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'dido', name: 'Dido' }, { id: 'juno', name: 'Juno' }, { id: 'venus', name: 'Venus' }, { id: 'jupiter', name: 'Jupiter' }],
      themes: [{ slug: 'dido', label: 'Dido' }, { slug: 'pietas', label: 'Pietas' }],
    },
    {
      n: 5, title: 'Funeral games for Anchises', tourTitle: 'Funeral games', hook: 'Sicily again, on the anniversary of the father\'s death. A boat race, a foot-race, a boxing match, an arrow that catches fire in mid-air.',
      tour: `The fleet, blown back to Sicily, finds itself near Anchises's tomb on the exact anniversary of his death. Aeneas calls funeral games — a boat race won by reckless cornering, a foot-race won when the leader slips in spilled blood, a boxing match between an old veteran and a young Sicilian, an arrow that catches fire in mid-air as an omen. While the men compete, the Trojan women, weary of years at sea, are roused by Juno's messenger and set fire to the ships. Most are saved by a sudden rain. Anchises appears to Aeneas in a dream and tells him to come find him in the underworld at Cumae.`,
      blurb: `A year after Anchises's death, the fleet is blown back to his tomb in Sicily. Aeneas holds funeral games — boat race, foot-race, boxing, archery, an arrow that catches fire in mid-air as an omen. The Trojan women, weary of seven years at sea, set fire to the ships; most are saved by a sudden rain Jupiter sends. Anchises appears in a dream and tells his son to meet him in the underworld at Cumae before reaching Italy.`,
      summary: [
        `Driven from Carthage by storms, the fleet finds itself near western Sicily — the place where Anchises died and was buried a year before. Aeneas takes it as a sign and lands. He announces nine days of funeral games. Four ships race around an offshore rock; the captain in the lead grounds his ship by cutting the corner too tight, and the captain who had been third wins by reckless seamanship. A foot-race is won by the second runner when the leader slips in a pool of bull's blood. A boxing match pits the gigantic young Sicilian Dares against the aged Trojan veteran Entellus; Entellus wins. An archery contest produces an omen — the last archer's arrow catches fire and traces a path across the sky.`,
        `While the men are at the games, the Trojan women have been left on the beach. They are exhausted — seven years at sea — and a rumor, encouraged by Juno's messenger Iris in the disguise of an old Trojan matron, has been spreading: why keep going, why not settle here, why not burn the ships and force the issue? They set fire to the fleet. Aeneas runs to the harbor with the captains. Four ships are already lost. He prays to Jupiter; a sudden heavy rain comes down and saves the rest.`,
        `The disaster shakes Aeneas. The Trojan elder Nautes counsels him: leave the weary, take the willing, build a city here for those who cannot go on. That night Anchises appears to Aeneas in a dream and tells him to go to Italy as he has been told — and before he reaches the new kingdom, to come find him in the underworld; at Cumae, the Sibyl will guide him down. Aeneas founds a small Trojan settlement, leaves the weary in it, and sails on. Venus has gone meanwhile to Neptune to ask for safe passage. The god agrees, on a price: one Trojan must drown for the rest. The pilot Palinurus, falling asleep at the helm, is pulled overboard in the night.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'anchises', name: 'Anchises' }, { id: 'ascanius', name: 'Ascanius' }, { id: 'venus', name: 'Venus' }],
      themes: [{ slug: 'pietas', label: 'Pietas' }, { slug: 'homer', label: 'Homer' }],
    },
    {
      n: 6, title: 'The descent into the underworld', tourTitle: 'The underworld', hook: 'Aeneas goes down to the dead. He meets Dido, who turns away in silence. He meets his father, who shows him the parade of unborn Roman souls.',
      tour: `The philosophical heart of the poem. The fleet lands at Cumae. Aeneas finds the Sibyl in her cave; she prophesies the wars he will face in Italy and agrees to lead him into the underworld to find his father. He buries his trumpeter Misenus and gathers the golden bough as a gift for Persephone. They descend at midnight. He sees the river of the unburied dead, the lovers in the Fields of Mourning where Dido walks among them and turns away from him without speaking. They reach the Elysian Fields. Anchises shows him the parade of unborn Roman souls — Romulus, Caesar, Augustus, the heroes of the Republic. The future is shown as actually present, just below.`,
      blurb: `The philosophical heart of the poem. Aeneas descends into the underworld at Cumae with the Sibyl as guide. He meets Dido — she turns away in silence and walks back into the shade. He finds his father in the Elysian Fields, who shows him the parade of unborn Roman souls in a long prophecy ending on the early death of Augustus's young heir Marcellus. The future the founding serves is made visible. So is its cost.`,
      summary: [
        `The fleet lands at Cumae, on the Italian coast north of Naples. Aeneas climbs to the temple of Apollo and finds the Sibyl in her cave. The prophecy comes through her in pieces — wars in Italy worse than the war at Troy, a foreign bride who will be the cause as Helen was. He asks her to take him down to find his father. She agrees on conditions: he must bury a man who lies unburied on the shore, and find a golden bough as a gift for Persephone. He goes back and finds Misenus, his trumpeter, drowned that morning. He buries him. Two doves, his mother's birds, lead him to the bough.`,
        `They descend at midnight through a cave at Lake Avernus. What follows is the most famous descent into the underworld in classical literature, and the model for Dante's Inferno. They cross the Styx; they pass the unburied waiting a hundred years; the souls of children weeping; the lovers in the Fields of Mourning, where Dido is among them. Aeneas, weeping, swears he left her against his will. She turns her face away and walks back into the shade with her first husband Sychaeus. They pass the warrior dead. They come to the fork: Tartarus left, Elysium right. They go right.`,
        `Anchises is there, in a green valley by the river Lethe. Aeneas tries three times to embrace him; three times the embrace passes through air. Anchises explains the metaphysics — souls drink of Lethe to forget their old lives and come back into bodies — and then shows his son, in a long parade, the souls who will become Romans: Silvius, Romulus, Numa, the kings; the consuls of the Republic; Julius Caesar; Augustus, who will bring back the golden age. The catalogue ends with a sudden grief: the young Marcellus, Augustus's heir-apparent, who will die at nineteen. Aeneas asks how the future can hold such suffering. Anchises has no answer. He sends his son out through the ivory gate of false dreams.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'anchises', name: 'Anchises' }, { id: 'sibyl', name: 'The Sibyl' }, { id: 'dido', name: 'Dido' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'dido', label: 'Dido' }, { slug: 'pietas', label: 'Pietas' }],
    },
    {
      n: 7, title: 'Arrival in Italy; the broken peace', tourTitle: 'Arrival in Latium', hook: 'The fleet reaches Italy. Latinus offers his daughter; Juno releases a fury who poisons every household. The war for the future of Rome begins.',
      tour: `The fleet reaches the mouth of the Tiber. The Trojans land and eat their meal on flat cakes — and notice they are eating their tables, fulfilling the harpy curse from Book III. They have arrived. King Latinus, whose oracles have told him his daughter Lavinia must marry a foreigner, offers her to Aeneas. But Lavinia is already promised to Turnus, prince of the Rutulians. Juno summons up the fury Allecto from the underworld. Allecto poisons Queen Amata; she poisons Turnus; she drives a young Trojan hunter to wound a domesticated stag. Within days the peaceful kingdom is at war. The book ends with Virgil's catalogue of Italian warriors gathering.`,
      blurb: `The Trojans land in Italy and notice they are eating their tables — the harpy curse fulfilled. King Latinus offers Aeneas his daughter Lavinia in fulfillment of an oracle. Juno, refusing to yield to fate, releases the fury Allecto from the underworld; she poisons Queen Amata, then Turnus, then the countryside. Within days, the kingdom is at war. The book ends with a great catalogue of Italian warriors — Mezentius, Camilla, Turnus at their head.`,
      summary: [
        `The fleet rounds the Italian coast and reaches the mouth of the Tiber. Aeneas leads the men ashore. They eat their first meal on Italian soil, laying out the food on flat cakes of bread for plates; when they finish the food they begin eating the bread, and Ascanius cries out, "Look — we are eating our tables." Aeneas remembers the harpy curse from Book III. They have arrived. He sends an embassy to the local king. Latinus rules over the Latins and the surrounding peoples; he is old and good and at peace. He has heard the oracles — his daughter Lavinia must marry a foreigner — and he greets the Trojan envoys joyfully. He offers Aeneas his daughter and his alliance.`,
        `But Lavinia is already promised. Turnus, the young prince of the neighboring Rutulians, has been the favored suitor for years; the queen Amata in particular wants the marriage. Juno, watching from above, sees an opening. She cannot stop fate, but she can drag the founding through every kind of suffering before it is complete. She summons up the fury Allecto from the deepest underworld and sends her into Italy to break the peace. Allecto is one of the most terrifying figures in the poem — snakes for hair, torches in her hands, all anger.`,
        `She works. She poisons Amata first, who runs raving with the women of Italy into the woods, hiding her daughter. She poisons Turnus, who wakes raging and rallies his men for war. She prods a young Trojan hunter — Ascanius, on his first hunt — into shooting a domesticated stag, the favorite of the local shepherds; the shepherds rise to avenge it. Within days the countryside is at war. Latinus, helpless, withdraws into his palace and refuses to take part. The book ends with Virgil's grand catalogue of the Italian peoples gathering — Mezentius the brutal Etruscan exile; Camilla, the warrior maiden of the Volsci, swift as wind; Turnus at their head, in his polished helmet, with a Chimera crest spitting flame.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'latinus', name: 'Latinus' }, { id: 'lavinia', name: 'Lavinia' }, { id: 'turnus', name: 'Turnus' }, { id: 'juno', name: 'Juno' }, { id: 'camilla', name: 'Camilla' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'homer', label: 'Homer' }],
    },
    {
      n: 8, title: 'On the future site of Rome; the shield', tourTitle: 'Evander and the shield', hook: 'Aeneas rows up the Tiber and is welcomed at the small settlement on the Palatine — the future Forum. That night Vulcan forges him a shield engraved with all of Rome to come.',
      tour: `Aeneas, advised by the river-god Tiber in a dream, rows a single ship up the river to find allies. He reaches Pallanteum on the Palatine Hill — a Greek exile-colony ruled by King Evander, on the site that will one day be Rome. Evander walks him through what is at present a wood with cattle in it: this outcrop will be the Capitol; this is where the Forum will stand. He sends his only son Pallas, untested in war, to fight at Aeneas's side. Meanwhile Venus asks Vulcan for divine armor. The shield takes Virgil more than a hundred lines to describe — engraved with the future history of Rome, ending at Augustus's triumph at Actium.`,
      blurb: `Aeneas rows a single ship up the Tiber and is welcomed by old King Evander at the small Greek settlement on the future site of Rome. Evander walks him through what will become the Forum, the Capitol, the Tarpeian Rock. Pallas, Evander's only son, is sent to fight at Aeneas's side. That night Vulcan forges Aeneas a shield engraved with all of Roman history to come — ending at Augustus's victory at Actium against Antony and Cleopatra.`,
      summary: [
        `Aeneas needs allies. The river-god Tiber appears to him in a dream and tells him to row upstream — there he will find a Greek exile, Evander, who has founded a small settlement and who hates the local Italians enough to join him. The omen of a white sow with thirty piglets confirms the dream. Aeneas takes a single ship up the river. He reaches Pallanteum, a small wooden town on the Palatine Hill, just as the people are sacrificing to Hercules. Evander welcomes him as a kinsman — they share an ancestor on the Trojan side — and invites him to the feast.`,
        `The next morning Evander walks Aeneas around the settlement. The walk is one of Virgil's great quiet scenes. The old king points out a rocky outcrop where the goats wander: that will be the Capitol. He shows him a swampy area below: that is where the Forum will be. He shows him the Tarpeian Rock, the Asylum, the ancient altar of Hercules. The reader, of course, knows every site he names. The future is being walked, in slow motion, on its own ground. Evander gives Aeneas his only son Pallas — young, untested, eager — to ride with the cavalry he is providing, and sends a delegation to the Etruscans, who have already revolted against the brutal Mezentius and who, by an oracle, must be led by a foreign general.`,
        `Meanwhile, on Olympus, Venus has gone to her husband Vulcan and asked him to forge new armor for their son. Vulcan agrees and goes to his volcanic forge under Mount Etna; he sets the Cyclopes to work that night. The book closes with the longest description of armor in classical literature: the shield, engraved with the future history of Rome. Romulus and Remus suckling the wolf. The rape of the Sabines. Horatius at the bridge. The battle of Actium itself, with Augustus standing on the prow of his ship. Aeneas, when the armor is delivered, lifts the shield and is shown not knowing what is on it: he marvels and admires, says Virgil, lifting on his shoulder the fame and the fates of his descendants.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'evander', name: 'Evander' }, { id: 'pallas', name: 'Pallas' }, { id: 'venus', name: 'Venus' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'homer', label: 'Homer' }],
    },
    {
      n: 9, title: 'Turnus attacks the camp; Nisus and Euryalus', tourTitle: 'The night raid', hook: 'With Aeneas away, Turnus attacks the Trojan camp. Two young friends slip out for a night raid and do not return.',
      tour: `Juno tells Turnus that Aeneas is away. He attacks the Trojan camp. The Trojans refuse to come out; Turnus tries to burn the fleet and the ships are transformed by the goddess Cybele into sea-nymphs that swim out to sea. The siege settles in for the night. Two young Trojan friends, Nisus and Euryalus — close as brothers — slip out to carry word to Aeneas. They make it through the Rutulian camp; they are tempted, fatally, to start killing sleeping men. Euryalus's polished helmet catches the moonlight. They are spotted and hunted down. Their bodies are paraded back at dawn. The next day Ascanius makes his first kill in battle — Apollo comes down to tell him to fight no more.`,
      blurb: `With Aeneas away, Turnus assaults the Trojan camp. The fleet is miraculously transformed by the goddess Cybele into sea-nymphs to escape Turnus's fires. Two young friends, Nisus and Euryalus, slip out for a night raid and do not return — Euryalus's polished helmet catches the moonlight and gives them away. The next day Ascanius, fourteen, makes his first kill in battle, and Apollo comes down to tell him to fight no more.`,
      summary: [
        `Juno's messenger Iris brings Turnus the news: Aeneas has gone upriver. The Rutulian prince attacks at once. The Trojan camp is fortified at the mouth of the Tiber; Aeneas has left orders that they are not to come out and fight in his absence. Turnus tries to burn the fleet on the shore. The goddess Cybele intervenes — the timber of the Trojan ships was cut from her sacred mountain — and turns the ships, in front of the army, into sea-nymphs that swim out to sea. The Italians are stunned. The siege settles in for the night.`,
        `Two young Trojan friends, Nisus and Euryalus — older brother and younger, beautiful, almost the same age — propose to slip out through the Italian lines and carry word to Aeneas. The elders agree. Euryalus asks Ascanius to look after his mother if he does not return. They make it cleanly through the camp. Then they are tempted. The Italians are sleeping after a feast; Nisus begins killing them where they lie. Euryalus, fatally, takes a polished helmet from one of the dead. In the moonlit woods the helmet glints. A returning patrol sees the flash. Euryalus is caught in dense brush; Nisus turns back; the patrol's leader kills Euryalus before Nisus can save him; Nisus charges out and dies on his body. Both heads are paraded back on spears at dawn.`,
        `The assault on the camp resumes. Turnus's army storms the gates; the Trojans hold. Ascanius — the boy, fourteen — fires an arrow and brings down the Italian who has been mocking the Trojans from a tower; it is his first kill in battle. Apollo himself comes down in the disguise of an old tutor and tells him to fight no more. At one point the Trojans, against orders, open a gate to make a sally; Turnus and a few of his men slip in before they can close it. Turnus is now inside the camp, cut off from his army. He kills many men. Cornered and exhausted, he reaches the river side and jumps in fully armed; the current carries him back to his own side.`,
      ],
      appears: [{ id: 'turnus', name: 'Turnus' }, { id: 'ascanius', name: 'Ascanius' }, { id: 'aeneas', name: 'Aeneas' }],
      themes: [{ slug: 'pietas', label: 'Pietas' }, { slug: 'fate', label: 'Fate' }],
    },
    {
      n: 10, title: 'Aeneas returns; Pallas dies', tourTitle: 'The death of Pallas', hook: 'Jupiter forbids the gods from interfering. Aeneas returns by sea with the Etruscans. Pallas is killed; Turnus strips his belt; the death will undo them both.',
      tour: `On Olympus, Jupiter forbids the gods from any further interference. Fate will decide. Aeneas, with the Etruscan fleet, returns by sea and leaps from his ship into the surf in his new armor; the Italian line breaks. Pallas, in his first major battle, is drawn into combat with Turnus, who is older and stronger; Turnus kills him with a spear-throw. Then he commits the act that will undo him: he strips the sword-belt from the dead boy and puts it on. Aeneas, hearing, goes mad with grief. He kills Lausus, the young son of Mezentius, who has thrown himself between his father and Aeneas's spear; he is moved to pity for the body. He then kills Mezentius himself.`,
      blurb: `Jupiter forbids the gods from interfering — fate will decide. Aeneas returns by sea with the Etruscan allies and leaps into the surf in the new armor Vulcan made him. Young Pallas is killed by Turnus, who strips his sword-belt as a trophy — a decision that will undo him. Aeneas, in grief, kills Mezentius's young son Lausus and Mezentius himself. The day belongs to the Trojans, but Pallas is dead.`,
      summary: [
        `On Olympus, Jupiter calls the council of the gods together. He has forbidden interference once already and they have ignored him. He forbids it again, in plain terms: any god who continues to take a side will be punished. Venus pleads for the Trojans; Juno pleads for the Italians; Jupiter rules that fate will decide and goes silent. Aeneas, meanwhile, returns by sea with the Etruscan fleet — thirty ships of allies — and reaches the Trojan camp. He leaps from his ship into the surf in the new armor Vulcan made him, the shield with all of Rome on it on his arm. The Italians, pressing the camp, are caught between its defenders and Aeneas's relieving force. The line breaks.`,
        `Pallas, on his first major day in the field, kills several Italian warriors. His confidence rises. He is finally drawn into combat with Turnus himself — the older and far stronger Rutulian prince. Pallas's friends try to keep them apart; Pallas refuses. They throw spears. Pallas's spear glances off Turnus's armor; Turnus's spear goes through Pallas's chest. The boy falls. Turnus, looking down at him, says he is sending him back to his father. Then, in front of everyone, he strips the polished sword-belt from the body and buckles it on himself. Virgil pauses to address the reader: human minds, blind to what waits for them in success — Turnus will one day wish he had never seen this belt.`,
        `Aeneas hears within the hour. The grief that overtakes him is described in the language of madness. He goes through the field killing men he would otherwise have spared; he refuses to ransom prisoners. He meets Lausus, the young son of the Etruscan exile-king Mezentius — Lausus has thrown himself between his wounded father and Aeneas's spear. The boy keeps fighting; Aeneas kills him with a single thrust. Looking at the body, he is moved to pity — Lausus died in <em>pietas</em>, defending his father; Aeneas himself once carried his own father out of Troy. He gently lifts the body and gives it back. He then finds Mezentius and kills him too. The day ends with the Italian line broken and Aeneas in command of the field. But Pallas is dead.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'turnus', name: 'Turnus' }, { id: 'pallas', name: 'Pallas' }, { id: 'jupiter', name: 'Jupiter' }],
      themes: [{ slug: 'pietas', label: 'Pietas' }, { slug: 'fate', label: 'Fate' }, { slug: 'ending', label: 'The ending' }],
    },
    {
      n: 11, title: 'Pallas\'s funeral; Camilla dies', tourTitle: 'Camilla\'s charge', hook: 'A truce to bury the dead. Pallas is sent home to Evander. Camilla, the warrior maiden, leads a brilliant cavalry charge — and is killed by an ambush from a coward.',
      tour: `Dawn after the battle. Aeneas prepares Pallas's body for the journey home. The procession is one of the great mourning scenes in classical literature — a thousand Trojan elders, the boy on a bier of woven branches, his father Evander waiting at the gates. A truce is granted; the Latin council debates peace, but Turnus refuses. The fighting resumes. Camilla, the warrior maiden of the Volsci, leads the Italian cavalry against the Trojans and kills warrior after warrior. Then a coward — Arruns, who has been stalking her — throws a single javelin from cover and hits her in the breast. She dies in the arms of her servant. The Italian line breaks.`,
      blurb: `A truce to bury the dead. Pallas is sent home to his father Evander with a great procession; the old king's grief is unbearable. The Latin council debates peace; Turnus refuses. The fighting resumes. The warrior maiden Camilla leads a brilliant cavalry charge against the Trojans and is killed from cover by a coward named Arruns, with a single javelin. The Italian line breaks. Turnus, hearing the news, rides for the city.`,
      summary: [
        `Dawn after the long fight. Aeneas dedicates the spoils of the dead Mezentius to Mars and prepares Pallas's body for the journey home. He chooses a thousand elders to escort it. The boy is laid on a bier of woven branches, carried out through the camp gates with horses following — the boy's own horse Aethon weeping, says Virgil. The procession reaches Pallanteum. Evander is waiting at the gates. He throws himself on his son's body. He cannot hold himself up. He sends the procession back with a single message to Aeneas: I am alive only to see you take vengeance for him.`,
        `A delegation arrives from the Latin king to ask for a truce to bury the dead of both sides. Aeneas grants it gladly — he was never at war with the Latins, only with Turnus. The Latin council meets while the smoke is still rising. Most want peace. Latinus urges it. Drances, an older noble who hates Turnus personally, makes a long speech against him. Turnus answers with rage and contempt. Word arrives mid-debate that the Trojans are moving on the city; the council breaks up. Turnus sets an ambush in a narrow pass and sends the Italian cavalry to face the Trojans in the open ground in front of the walls.`,
        `The cavalry battle that follows takes most of the book. Camilla is the center of it — in light armor, bare-shouldered like Diana her patron, riding without restraint. She kills warrior after warrior, her band of Volscian women behind her. Then Camilla, as great fighters do in the poem, is undone by her own success. She is fixated on chasing down a particular Trojan, gold-armored Chloreus, for his armor. She does not see Arruns, an Etruscan stalking her from cover, who has prayed to Apollo for the chance. He throws a single javelin from concealment. It hits her in the breast. She dies in the arms of her servant Acca with a last message for Turnus to come to the city. Apollo grants Arruns the kill but denies him the safe return; Diana's nymph Opis shoots him with an arrow.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'turnus', name: 'Turnus' }, { id: 'pallas', name: 'Pallas' }, { id: 'evander', name: 'Evander' }, { id: 'camilla', name: 'Camilla' }, { id: 'latinus', name: 'Latinus' }],
      themes: [{ slug: 'fate', label: 'Fate' }, { slug: 'ending', label: 'The ending' }],
    },
    {
      n: 12, title: 'The duel; the killing of Turnus', tourTitle: 'The final duel', hook: 'Aeneas and Turnus meet in single combat. Turnus is wounded and surrenders. Aeneas hesitates — and then sees Pallas\'s belt on his shoulder.',
      tour: `Turnus, with his army broken, agrees to settle the war in single combat. The kings swear oaths. Then Juno breaks the truce through Turnus's sister Juturna, who in disguise rouses the Italians to attack. Aeneas is wounded; Venus heals him. On Olympus, Juno yields to Jupiter — her one condition is that the Trojans take the Latin name and language. The two men meet at last. Aeneas's spear hits Turnus in the thigh. Turnus falls, raises his hand, and surrenders. Aeneas hesitates. Then he sees the sword-belt of Pallas on Turnus's shoulder. He drives the spear through Turnus's chest. The poem ends in the next four lines, on a soul going down to the shadows indignant.`,
      blurb: `The poem's last book. Single combat is arranged; Juno breaks it through Turnus's sister Juturna; the war resumes. Aeneas is wounded and healed by Venus. Juno yields to Jupiter on the condition that the Trojans take the Latin name and language. The duel happens. Turnus surrenders, asks for mercy. Aeneas hesitates, sees Pallas's belt on his shoulder, and kills him in fury. The poem ends in the next four lines, on a soul going down to the shadows indignant.`,
      summary: [
        `Turnus accepts that the war must be settled in single combat. Latinus and Amata beg him not to fight; he is unmoved. Lavinia listens without speaking — Virgil shows her face going red, the only thing she does in the entire poem. The terms are arranged. The kings swear oaths at dawn. Aeneas swears that whoever wins, he will not impose Trojan rule. Juno cannot bear the cleanness of the settlement. She sends Turnus's divine sister Juturna into the field in disguise; Juturna rouses the Italian troops, an omen is read in their favor, the Italians attack. Aeneas is hit by an arrow from no one Virgil names, and led from the field. Venus heals the wound with a magical herb.`,
        `Aeneas takes the field again. He pursues Turnus; Juturna takes the reins and drives him in circles to keep him from his pursuer. Aeneas, frustrated, turns the army on the city itself. The walls are stormed. The queen Amata, watching from the palace and believing Turnus dead, hangs herself. The city is in flames. Turnus hears the wail and finally understands. He sends his sister away — sister, even you cannot keep me from this — and rides into the open ground before the walls. He calls Aeneas's name. The two armies stand back. On Olympus, Juno finally yields to Jupiter, on one condition: the Trojans must give up their name and their language; Italy must remain Italy. Jupiter agrees gladly. Juno smiles for the first time in the poem and withdraws.`,
        `The duel begins. Turnus's borrowed sword shatters on Aeneas's divine armor. He runs; Aeneas pursues; they run five circles in the dust. Turnus throws a great boundary stone; it goes wide. Aeneas's spear goes through Turnus's shield and into his thigh. Turnus falls. He raises his right hand. He has earned this, he says, and asks no quarter for himself; only that his body be given to his old father, or that Aeneas return him alive. You have won. Lavinia is yours. Hate me no further. Aeneas hesitates. The poem says clearly he is on the point of sparing him. Then his eyes fall on Turnus's shoulder. The sword-belt is there — the polished belt of young Pallas. Aeneas, kindled by furies, says, "Pallas it is — Pallas — who strikes this blow," and drives the spear through Turnus's chest. Turnus's limbs go cold; his life flees, with a groan, indignant, into the shadows below. The poem ends.`,
      ],
      appears: [{ id: 'aeneas', name: 'Aeneas' }, { id: 'turnus', name: 'Turnus' }, { id: 'lavinia', name: 'Lavinia' }, { id: 'latinus', name: 'Latinus' }, { id: 'juno', name: 'Juno' }, { id: 'jupiter', name: 'Jupiter' }, { id: 'venus', name: 'Venus' }],
      themes: [{ slug: 'ending', label: 'The ending' }, { slug: 'pietas', label: 'Pietas' }, { slug: 'fate', label: 'Fate' }],
    },
  ],
}
