// The Tempest — SEO page data for build-seo-pages.cjs
// Shakespeare, 10 scenes (5 acts + epilogue), late romance.
// Voice: magical, melancholy, valedictory; quote sparingly but precisely.

module.exports = {
  id: 'the-tempest',
  title: 'The Tempest',
  author: 'William Shakespeare',
  byline: 'c. 1610–11 · English romance in five acts',
  titleAccent: 'a guided tour',
  hook: 'A magician on a small island raises a storm, wrecks a ship full of his old enemies, and over the course of one afternoon takes a controlled revenge — and then, having every reason to destroy them, forgives them and breaks his staff.',
  themesBlurb: 'Usurpation, magic, colonialism, the masque, forgiveness, renunciation.',
  castBlurb: 'The island',
  castDesc: 'Two long-time inhabitants, one growing daughter, and the shipwrecked court of Naples and Milan.',
  chapterLabel: n => `Scene ${n}`,
  genre: ['Romance', 'Drama', 'Renaissance literature'],

  about: [
    `<em>The Tempest</em> is Shakespeare's last solo-authored play, written around 1611 and performed at court for King James. It is short — under three hours — and unusually obedient to the classical unities of time, place, and action: the whole story takes place in one afternoon, on one island, around one man. That man is Prospero, the deposed Duke of Milan, who twelve years ago was set adrift in a rotten boat by his usurping brother Antonio and washed up on this island with his three-year-old daughter Miranda. He has spent the intervening years studying magic. The play opens with him conjuring the storm of its title to wreck the ship that happens to be carrying Antonio, the King of Naples, and the king's son Ferdinand onto his shore.`,
    `What follows has been read in more incompatible ways than perhaps any other Shakespeare. As a meditation on art and the artist's renunciation of his powers. As a coded farewell to the theater — Prospero's epilogue is often quoted as Shakespeare's own. As a colonial document, with Prospero the European invader and Caliban the dispossessed islander. As a study in forgiveness, or a study in the failure of forgiveness, with Antonio's silence at the end as the open wound. The play accommodates every reading because it is uneasy with each of them. Prospero's magic is benign and coercive at once, his mercy partial, his reconciliation incomplete. The Tempest is at its most powerful in the gaps between the readings it invites.`,
  ],
  chaptersSubtitle: 'All 10 scenes, by act and beat — from the storm at sea to the magician asking the audience to set him free.',
  chaptersLead: `<p>The Tempest is structured as five short acts and an epilogue. Act I sets the world: the storm, then the long expository scene at Prospero's cell where Miranda hears for the first time who she is, Ariel reports on the wreck, and Caliban states his claim. Act II splits the survivors: Alonso's grieving court on one part of the island, the drunken butler and jester meeting Caliban on another. Act III is the play's hinge — Ferdinand and Miranda pledge their love, Caliban plots Prospero's murder, and Ariel as a harpy accuses the men of sin. Act IV is the betrothal masque and Prospero's most-quoted speech. Act V is the renunciation and the forgiving. The epilogue is Prospero alone, addressing the audience.</p>`,
  themesByline: 'Five threads through the play',
  themesLead: `The Tempest is a comedy with a tragedy under it. Almost every theme it touches has both a serious and a clownish version on stage — the same evening. These five threads carry it.`,

  groups: [
    { label: 'Act I · The storm and the island', subtitle: 'The wreck, and the long scene where Prospero finally tells Miranda who she is.', chapters: [1, 2] },
    { label: 'Act II · The survivors', subtitle: 'Alonso\'s court grieves; Caliban meets a drunk butler and decides he is a god.', chapters: [3, 4] },
    { label: 'Act III · The hinge', subtitle: 'Ferdinand and Miranda pledge; Caliban plots; the banquet vanishes.', chapters: [5, 6, 7] },
    { label: 'Act IV · The masque', subtitle: 'A betrothal pageant interrupted by the memory of a murder plot.', chapters: [8] },
    { label: 'Act V · The renunciation', subtitle: 'Prospero breaks his staff, forgives his enemies, and reclaims his dukedom.', chapters: [9] },
    { label: 'Epilogue', subtitle: 'The magician alone on stage, asking the audience to release him.', chapters: [10] },
  ],

  themes: [
    {
      slug: 'usurpation',
      title: 'Usurpation and forgiveness',
      greek: 'the brother who took the dukedom; the brother who lets him keep his life',
      preview: 'Antonio took Milan from Prospero twelve years ago and set him adrift in a rotten boat. Prospero now has every weapon he has spent twelve years building, his enemies asleep on the beach, and the simple choice: punish or forgive. The play is the story of how he chooses the harder one.',
      essay: [
        `Prospero's grievance is genuine and severe. His younger brother Antonio, while Prospero buried himself in his books, conspired with Alonso of Naples to seize the dukedom of Milan. Prospero and his three-year-old daughter were put into a rotten boat — "a rotten carcass of a butt, not rigged, nor tackle, sail, nor mast" — and pushed out to sea. Only an honest counselor named Gonzalo, who provisioned the boat with food, water, and Prospero's books, kept them alive. Twelve years later Prospero has the men who did this asleep on his beach.`,
        `He has the power to do anything he wants to them. The storm has shown that much. Yet from the start the play signals that the revenge will be controlled — no one drowns; not a hair is harmed; the ship rides safe in harbor. What Prospero stages instead is something between trial and theater: he separates the survivors, he frightens them, he brings the guilty into a state of penitence through Ariel's harpy speech, and only then does he reveal himself.`,
        `The forgiveness is hard-won and partial. Alonso, who has spent the day believing his son drowned, weeps and asks pardon openly; Prospero gives it openly. Sebastian, who tried to murder his brother in his sleep on this very island, is forgiven without confession. Antonio is forgiven without confession either, and — in the play's most-discussed silence — says nothing in return. He is given his life. He is given no contrition. The reconciliation the comedy needs goes on around him while he stays mute.`,
        `What Shakespeare seems to be writing is not a clean moral lesson but a study of what mercy actually costs. Prospero gives up the satisfactions of revenge, the security of certainty about his enemies, and finally his magic itself — and gets, in exchange, his dukedom back, his daughter married into the line that wronged him, and a brother whose silence will outlast every reconciliation speech in the script. The play earns its forgiveness by refusing to pretend it solves everything.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (Prospero tells Miranda the story)' },
        { n: 3, label: 'Scene 3 (Antonio repeats his crime on Sebastian)' },
        { n: 7, label: 'Scene 7 (the harpy accuses the three sinners)' },
        { n: 9, label: 'Scene 9 (the forgiveness, and Antonio\'s silence)' },
      ],
    },
    {
      slug: 'magic',
      title: 'Magic and its limits',
      greek: 'the staff that will be broken, the book that will be drowned',
      preview: 'Prospero is the most powerful magician in Shakespeare and almost the only one Shakespeare allows to renounce his power on stage. The play is a study of what magic can and cannot do — and of why the man who can do anything chooses, finally, to do nothing.',
      essay: [
        `Prospero's magic is total within its limits. He can raise a storm, scatter a ship, separate its passengers, put a court to sleep, conjure a banquet and dissolve it, command spirits to perform a wedding masque, set spirit-hounds on a drunken plot. Almost every event in the play is something he has arranged. Shakespeare is careful to keep showing the seams: Ariel is the agent; the storm was a controlled illusion; no harm was actually done. The magic is real, but it is also stage-management.`,
        `What the magic cannot do is the work of the heart. It cannot make Antonio repent. It cannot return the years on the island to Miranda or restore Prospero's lost decade in Milan. It cannot, finally, make Ariel free without Prospero giving him up. The book and the staff buy him every effect except the ones that matter most, and the play knows it. Prospero's most-quoted speech in Act IV — "we are such stuff as dreams are made on, and our little life is rounded with a sleep" — is delivered immediately after he has had to abandon a magical pageant because he forgot a real-world plot to murder him. Magic does not protect against forgetting.`,
        `So in Act V he gives it up. "I'll break my staff, bury it certain fathoms in the earth, and deeper than did ever plummet sound I'll drown my book." Renunciation is the play's final magical act. The gesture is offstage in the strictest reading — what we see is the speech, not the breaking — but staging tradition has made it the climax. The most powerful man in the play voluntarily becomes the least powerful. He will go back to Milan, the speech in Act V tells us, where every third thought will be of his grave.`,
        `Why magic must end is the play's quiet argument. Magic that lasts becomes tyranny. Caliban is a slave because a magician decided he should be one; Ariel is a servant because a magician rescued him and immediately took him on. To keep the staff is to keep the right to compel other people. Prospero's last freedom is his power to walk away from his own power. The play treats that act as the deepest one available to a human being.`,
      ],
      where: [
        { n: 1, label: 'Scene 1 (the storm)' },
        { n: 7, label: 'Scene 7 (the vanishing banquet)' },
        { n: 8, label: 'Scene 8 (the masque, and the interruption)' },
        { n: 9, label: 'Scene 9 (the renunciation)' },
      ],
    },
    {
      slug: 'caliban',
      title: 'Caliban and colonialism',
      greek: '"This island\'s mine, by Sycorax my mother, which thou tak\'st from me"',
      preview: 'Caliban was on the island first. He was given language by Prospero and uses it, the first time he speaks, to curse him. He is enslaved by someone who calls it education. He is the most morally uncomfortable character Shakespeare wrote, and the twentieth century has not let him go.',
      essay: [
        `Caliban is the son of the witch Sycorax, the only previous human inhabitant of the island, and was its sole human resident when Prospero and the three-year-old Miranda washed up. Prospero befriended him, taught him language, "stroked thee and made much of thee," gave him the names of "the bigger light and the lesser." Caliban, in return, attempted to assault Miranda. Prospero enslaved him. That is the version of the story Prospero tells. Caliban's version is shorter and uglier: "this island's mine, by Sycorax my mother, which thou tak'st from me."`,
        `Shakespeare gives him both. He gives him the attempted rape, which the play does not soften. He also gives him some of the most beautiful poetry in the play — the speech about the isle being "full of noises, sounds and sweet airs that give delight and hurt not." He gives him the great line about education: "you taught me language; and my profit on't is, I know how to curse." He makes him a clown, drunken and murderous in his alliance with Stephano and Trinculo, and he makes him, in his last appearance, capable of a kind of self-recognition the courtly characters never reach: "I'll be wise hereafter, and seek for grace."`,
        `Twentieth and twenty-first century readings have placed him at the center. The Martinican poet Aimé Césaire rewrote the play as <em>Une Tempête</em> with Caliban as protagonist. The Barbadian writer George Lamming read the play as the Caribbean's foundational text in <em>The Pleasures of Exile</em>. Octavio Mannoni, then Frantz Fanon, then a generation of postcolonial critics treated Caliban as the founding figure of the colonized voice in European literature. The protest "this island's mine" is a question the play does not answer, and refusing to answer it is part of what has kept the play urgent.`,
        `Whether Shakespeare meant any of this is a separate question. The play was written shortly after the Virginia Company's first reports back from Jamestown; the wreck of the <em>Sea Venture</em> on Bermuda in 1609 is one of its known sources. Shakespeare was breathing the air of early colonialism when he wrote it. Whether he saw the structure he was putting on the stage clearly is something the play will not say. What it will say is that Caliban is given a fair share of the script, and that the script, four centuries on, has not let his claim go.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (Caliban\'s claim)' },
        { n: 4, label: 'Scene 4 (Caliban meets the drunkards)' },
        { n: 6, label: 'Scene 6 ("the isle is full of noises")' },
        { n: 9, label: 'Scene 9 ("seek for grace")' },
      ],
    },
    {
      slug: 'masque',
      title: 'The masque and the dream',
      greek: '"We are such stuff as dreams are made on"',
      preview: 'In Act IV Prospero stages a wedding masque for his daughter and her prince. He interrupts it himself, halfway through, when he remembers a real-world plot to murder him. The speech he gives next is one of the most-quoted in Shakespeare, and the play\'s sharpest meditation on the unreality of every made thing.',
      essay: [
        `The court masque was a real-world entertainment Shakespeare's audience would have recognized: a lavish, allegorical pageant put on at court, full of gods and goddesses descending from machinery, complete with music and dancing. King James loved them; Ben Jonson and Inigo Jones were turning them into the most expensive art form in England. The masque inside <em>The Tempest</em> is partly Shakespeare doing his version — Iris, Ceres, and Juno appear, sing, bless the betrothal, summon nymphs and reapers — and partly a comment on the form. It is offered as a gift and almost immediately revealed as illusion.`,
        `Prospero, mid-pageant, remembers Caliban's plot. He stops the masque. The spirits "to a strange, hollow, and confused noise, heavily vanish." Ferdinand and Miranda are bewildered; Prospero turns to them and gives the play's most-quoted speech. "Our revels now are ended. These our actors, as I foretold you, were all spirits and are melted into air, into thin air... we are such stuff as dreams are made on, and our little life is rounded with a sleep."`,
        `The speech is doing several things at once. It is consoling Ferdinand, who saw something beautiful disappear; it is acknowledging that Prospero himself, the magician, can have his attention pulled away by mortal fears; it is saying that the masque, the play we are watching, all human creation, and human life itself are made of the same fading material. The four objects in the speech — the cloud-capped towers, the gorgeous palaces, the solemn temples, the great globe itself (with a glance at the Globe theatre) — collapse together. Everything dissolves.`,
        `What gives the speech its weight is that it is not despairing. It is matter-of-fact. Shakespeare puts it in a mouth that has just demonstrated the most powerful magic in his canon, and has it admit that its products are no more permanent than a dream. The play does not flinch from this. It builds the rest of its action — the renunciation, the forgiveness, the leaving — on the assumption that the speech is true. If we are made of dream-stuff, then mercy and going home are the only things worth doing while the dream lasts.`,
      ],
      where: [
        { n: 8, label: 'Scene 8 (the masque, and the speech)' },
        { n: 9, label: 'Scene 9 (the renunciation, in the same key)' },
        { n: 10, label: 'Scene 10 (the epilogue addresses the audience as dreamers)' },
      ],
    },
    {
      slug: 'freedom',
      title: 'Freedom and service',
      greek: '"Then to the elements be free"',
      preview: 'The play is full of servants and masters. Ariel serves Prospero on the promise of freedom. Caliban serves on the threat of pain. Ferdinand serves Prospero willingly out of love for Miranda. Stephano calls himself a king for fifteen minutes. The play asks, in five different keys, what it means to be free.',
      essay: [
        `The Tempest is structured around acts of service. Ariel performs every magical effect in the play under bond to Prospero; Caliban hauls wood, fetches water, and is whipped if he refuses; Ferdinand carries logs to prove his love for Miranda; Stephano and Trinculo briefly enroll Caliban as their footman in an imaginary kingdom; Prospero himself was once a duke who failed his obligations as a ruler and is now, in some sense, the servant of a project of restoration. Everyone in the play is bound to someone. The question is what the bond is for and when it ends.`,
        `Ariel's case is the play's clearest. He was imprisoned in a cloven pine by the witch Sycorax twelve years before; Prospero released him and immediately bound him to "do me business in the veins o' the earth." The bond is for one year, then two, then twelve. Ariel reminds Prospero, with increasing edge, that he was promised freedom. Prospero responds with both irritation and tenderness — "my brave spirit," "my dainty Ariel" — and keeps extending the term. Only at the very end, his magic broken and his enemies forgiven, does Prospero actually say it: "to the elements be free, and fare thou well." Ariel exits singing. The freedom, when it comes, is total and unceremonious.`,
        `Caliban's case is the opposite. He serves under the threat of "cramps" and "side-stitches," supernatural pain Prospero can inflict at will. Released into the company of Stephano and Trinculo, he tries to swap masters — "I'll show thee every fertile inch o' the island, and I will kiss thy foot... thou shalt be lord of it" — and the new masters are worse than the old. The play does not give him freedom in the end. He is returned to Prospero's authority, instructed to clean the cell, and shown the dukedom Prospero is about to leave. His last words are about seeking grace, not about being released.`,
        `Underneath the Ariel and Caliban arcs runs a question about Prospero himself. He has spent the play giving and withholding freedom, and the closing epilogue inverts the relationship. He stands alone on stage and tells the audience his charms are now overthrown — what strength he has is his own. He cannot leave the stage without their applause. "Let your indulgence set me free." The man who has spent the play binding and releasing others now needs to be released himself.`,
      ],
      where: [
        { n: 2, label: 'Scene 2 (Ariel reminds Prospero of the promise)' },
        { n: 5, label: 'Scene 5 (Ferdinand serves willingly)' },
        { n: 9, label: 'Scene 9 ("be free")' },
        { n: 10, label: 'Scene 10 (the epilogue)' },
      ],
    },
  ],

  keyFigures: [
    { name: 'Prospero', role: 'The exiled Duke of Milan, a magician', body: `The protagonist. Twelve years on the island, master of every event in the play. He raised the storm, separated the survivors, set Ferdinand's trial, exposed his brother's continuing treachery, frightened Caliban into submission — and he narrates almost all of this himself, to Miranda and to the audience. He is wise, obsessive, controlling, and exhausted. His final act is to break his staff, drown his book, and forgive his enemies. Whether that makes him saint, tyrant retired, or simply tired is the play's open question.` },
    { name: 'Miranda', role: 'Prospero\'s daughter', body: `Fifteen years old, raised on the island since she was three, who has known no human face except her father's and Caliban's. When she first sees Ferdinand and the rest of the shipwrecked court, she utters the line the twentieth century has not let go of — "O brave new world, that has such people in't." Her wonder is genuine; her frame of reference is desperately small. The play loves her and is clear-eyed about her ignorance.` },
    { name: 'Ariel', role: 'A spirit, indentured to Prospero', body: `A spirit of air and fire whom Prospero rescued from a cloven pine where Sycorax had imprisoned him, and immediately bound to his own service. Ariel performs every magical task in the play — the storm, the music, the banquet that vanishes, the harpy's curse — and reminds Prospero, with increasing edge, that he was promised freedom. The relationship is the play's most ambiguous: a master who calls the slave "my dainty Ariel" and a slave who serves brilliantly because the alternative is being put back in the tree.` },
    { name: 'Caliban', role: 'The native inhabitant', body: `Son of the witch Sycorax, the island's only previous human resident, now Prospero's slave. Prospero taught him language. Caliban uses it to curse him: "you taught me language; and my profit on't is, I know how to curse." The play gives him some of its most beautiful poetry — the speech about the isle being full of noises — and also makes him a coarse, drunken figure who plots Prospero's murder with two shipwrecked clowns. He is the most morally uncomfortable character Shakespeare wrote, and modern readings place him at the play's center.` },
    { name: 'Ferdinand', role: 'Prince of Naples', body: `The son of the King of Naples, separated from his shipmates by Prospero's storm and washed ashore alone. He believes his father drowned. He meets Miranda and falls in love within minutes. Prospero immediately accuses him of being a spy, sets him to hauling logs, and tests his constancy — the trial succeeds and the engagement is made. He is decent, well-mannered, and politically convenient: marrying him to Miranda makes Prospero the future grandfather of a king of Naples and seals the reconciliation the play needs.` },
    { name: 'Antonio', role: 'Prospero\'s brother, the usurper', body: `The man who took the dukedom of Milan twelve years earlier and exiled his brother and infant niece in a rotten boat. He is unrepentant. On the island, when he discovers the King of Naples is asleep and unguarded, he proposes that the king's brother Sebastian murder him on the spot to take the throne — exactly the same crime he committed against Prospero. The play forgives him formally at the end. He says nothing. His silence is the open wound on the comedy's reconciliation.` },
  ],

  castSubtitle: 'The island — three long-time inhabitants and a shipwrecked court.',
  castLead: `<p>The Tempest has a small cast: about a dozen named figures, plus mariners, spirits, and the masque's goddesses. The play turns on the island's three long-term residents — Prospero, Miranda, Caliban — together with the indentured spirit Ariel, and on the shipwrecked court of Naples and Milan that Prospero's storm has delivered to his shore.</p>`,
  castGroups: [
    {
      label: 'The island',
      characters: [
        { id: 'prospero', tag: 'Mortal', name: 'Prospero', epithet: 'The exiled Duke of Milan, a magician', body: `The protagonist. Twelve years ago, while he buried himself in his books, his brother Antonio seized his dukedom; he and his three-year-old daughter Miranda were set adrift in a rotten boat and washed up on this island. He has spent the intervening years studying magic. He stages every event in the play, including most of his own renunciation. Breaks his staff and drowns his book in Act V; closes the epilogue alone on stage asking the audience to release him.`, appears: [2, 5, 7, 8, 9, 10] },
        { id: 'miranda', tag: 'Mortal', name: 'Miranda', epithet: 'Prospero\'s daughter', body: `Fifteen, raised on the island since she was three. Knows no human face except her father's and Caliban's until the play opens. Falls in love with Ferdinand on first sight. In Act V, when she sees the rest of the shipwrecked court, she gives the play's most-quoted line: "O brave new world, that has such people in't." Aldous Huxley took the title of his dystopia from her precisely because the irony was already there.`, appears: [2, 5, 8, 9] },
        { id: 'ariel', tag: 'God', tagClass: 'creature', name: 'Ariel', epithet: 'A spirit, indentured to Prospero', body: `A spirit of air and fire whom Prospero released from a cloven pine where the witch Sycorax had imprisoned him, and immediately bound to his own service. Performs every magical effect in the play — the storm, the invisible music, the harpy at the banquet, the spirit-hounds, the masque. Reminds Prospero with increasing edge that freedom was promised. Released "to the elements" in Act V and exits singing.`, appears: [2, 3, 6, 7, 8, 9] },
        { id: 'caliban', tag: 'God', tagClass: 'creature', name: 'Caliban', epithet: 'The native inhabitant, son of Sycorax', body: `The island's only previous human resident, now Prospero's slave. Was taught language by Prospero and uses it, on his first appearance, to curse him: "this island's mine, by Sycorax my mother, which thou tak'st from me." The play gives him some of its most beautiful poetry — the "isle is full of noises" speech — and also makes him a clown, drunken and murderous in his alliance with Stephano and Trinculo. Ends the play promising to "seek for grace."`, appears: [2, 4, 6, 8, 9] },
      ],
    },
    {
      label: 'The shipwrecked court',
      characters: [
        { id: 'alonso', tag: 'Mortal', name: 'Alonso', epithet: 'King of Naples', body: `The man who, twelve years ago, helped Antonio depose Prospero. The play opens with him on the wrecked ship; the storm separates him from his son Ferdinand, whom he believes drowned for most of the day. Spends the play in mourning that turns to penitence. Confronted by the harpy in Act III, then formally forgiven by Prospero in Act V, where he is reunited with Ferdinand and finds him engaged to Miranda. Of all the guilty men, the only one who openly asks pardon.`, appears: [1, 3, 7, 9] },
        { id: 'ferdinand', tag: 'Mortal', name: 'Ferdinand', epithet: 'Prince of Naples, son of Alonso', body: `Separated from his shipmates by the storm, washed ashore alone, believes his father drowned. Led by Ariel's music to Prospero's cell, where he meets Miranda and falls in love within minutes. Prospero, suspicious of an easy match, tests him by setting him to haul logs — a trial he submits to gladly. Engaged to Miranda by Act III. Reunited with his father in Act V. The marriage seals the reconciliation between Milan and Naples.`, appears: [1, 2, 5, 8, 9] },
        { id: 'antonio', tag: 'Mortal', name: 'Antonio', epithet: 'Prospero\'s brother, current Duke of Milan', body: `The usurper. Twelve years ago he seized his brother's dukedom with Alonso's help. On this island, with Alonso asleep and unguarded, he tempts Sebastian to repeat the crime — kill the sleeping king and take the throne — almost word for word the same proposition he himself acted on against Prospero. Forgiven by Prospero in Act V without ever asking for it. Says nothing in reply. His silence is the open wound on the comedy's last scene.`, appears: [1, 3, 7, 9] },
        { id: 'sebastian', tag: 'Mortal', name: 'Sebastian', epithet: 'Brother of Alonso', body: `Brother to the King of Naples. Cynical, sharp-tongued throughout. In Act II, with Alonso and Gonzalo asleep on the beach, he is talked by Antonio into a plot to murder his brother and seize the crown. They draw their swords; Ariel wakes Gonzalo; the moment passes. Forgiven in Act V, like Antonio, without confession. The play places his guilt squarely on the record without quite punishing it.`, appears: [1, 3, 7, 9] },
        { id: 'gonzalo', tag: 'Mortal', name: 'Gonzalo', epithet: 'An honest old counselor', body: `The play's moral center among the courtiers. Twelve years ago, when Prospero and Miranda were set adrift, it was Gonzalo who provisioned the rotten boat with food, water, and Prospero's books — the reason they survived at all. On the island he tries to keep Alonso's spirits up, sketches a famous utopian commonwealth ("no kind of traffic would I admit; no name of magistrate"), and is the only courtier who survives the play with his honor untouched. Thanked and honored by Prospero in Act V.`, appears: [1, 3, 7, 9] },
        { id: 'boatswain', tag: 'Mortal', name: 'Boatswain', epithet: 'The ship\'s boatswain', body: `Commands the crew during the opening storm. Bluntly tells the noblemen to stay below deck — the waves, he points out, care nothing for royal titles. Disappears for most of the play. Brought ashore in Act V by Ariel with the news that the ship is miraculously intact and the crew unharmed. The first sign to the wider company that the storm was, all along, controlled.`, appears: [1, 9] },
      ],
    },
    {
      label: 'The clowns',
      characters: [
        { id: 'stephano', tag: 'Mortal', name: 'Stephano', epithet: 'Alonso\'s drunken butler', body: `Survived the wreck by floating ashore on a barrel of wine. Meets Caliban in Act II and is taken for a god — Caliban has never tasted wine and Stephano has plenty of it. Recruited into Caliban's plot to murder Prospero with a promise of being "lord of the island" and Miranda as his queen. Distracted from the plot by glittering clothes Prospero leaves as a trap. Chased off by spirit-hounds. Returned to Alonso in disgrace at the end.`, appears: [4, 6, 8, 9] },
        { id: 'trinculo', tag: 'Mortal', name: 'Trinculo', epithet: 'Alonso\'s jester', body: `Washed ashore alone. Encounters Caliban hiding under a cloak and, mistaking him for a strange fish, takes shelter under the same cloak during a downpour — creating one of Shakespeare's most-staged comic tableaux. Joins Stephano and Caliban in the murder plot, mostly because there is wine. Mocked by the invisible Ariel mimicking his voice. Caught with the glittering clothes and chased off. Brought before Prospero in disgrace alongside the others.`, appears: [4, 6, 8, 9] },
      ],
    },
  ],

  chapters: [
    {
      n: 1, title: 'On a ship at sea — the storm', tourTitle: 'On a ship at sea', hook: 'A ship full of noblemen, a working sailor with no patience for them, and a storm that should not be survivable.',
      tour: `A ship at sea in a tempest. The Master orders the Boatswain to get the sailors moving before the ship runs aground. The Boatswain shouts the crew through the work. Then the noblemen come up on deck — Alonso the King of Naples, his brother Sebastian, his counselor Gonzalo, and Antonio, Duke of Milan — and demand to know what is happening. The Boatswain bluntly orders them below: the waves do not care about a king's name. They go. The storm worsens, the mariners come up wet and crying that all is lost, the ship "splits." The play has been on stage less than ten minutes and seems to have killed its entire court.`,
      blurb: `A ship in a storm. The Boatswain orders the noblemen below — the waves care nothing for a king's name. The mariners come up crying "all lost." The ship splits. The play opens by appearing to drown its entire cast.`,
      summary: [
        `A ship at sea, in the middle of a tempest of thunder and lightning. The Master, calling out from somewhere unseen, gives orders to his Boatswain: get the sailors moving, fall to it quickly, or we run ourselves aground. The Boatswain shouts the crew through the work — take in the topsail, listen for the master's whistle, blow until you burst as long as we have room to maneuver. The opening pace is breathless and technical, and Shakespeare uses it to put the audience on the deck of the ship before any of the speaking parts arrive.`,
        `Then the court comes up: Alonso, the King of Naples; his brother Sebastian; his counselor Gonzalo; Antonio, Duke of Milan; and the king's son Ferdinand. They want to know what is happening; they want the captain. The Boatswain — the working sailor with no patience for any of them — answers bluntly. "What cares these roarers for the name of king?" He orders them below. Gonzalo notes ruefully that the man does not have the look of a drowning man about him: he looks more like he was born for the gallows. They go.`,
        `The storm worsens. Mariners come up wet, crying "all lost!" Sebastian and Antonio curse the Boatswain. Gonzalo, in the moment of supposed death, says he would gladly trade a thousand miles of sea for one acre of barren ground — heath, broom, anything dry. A confused noise within: "Mercy on us! We split, we split!" "Farewell, my wife and children!" "Farewell, brother!" The ship is gone. The play has been on stage less than ten minutes and seems to have killed every named character it has introduced. The next scene will reveal that none of this was what it appeared.`,
      ],
      appears: [{ id: 'boatswain', name: 'Boatswain' }, { id: 'alonso', name: 'Alonso' }, { id: 'antonio', name: 'Antonio' }, { id: 'sebastian', name: 'Sebastian' }, { id: 'ferdinand', name: 'Ferdinand' }, { id: 'gonzalo', name: 'Gonzalo' }],
      themes: [{ slug: 'magic', label: 'Magic' }],
    },
    {
      n: 2, title: 'The island, before Prospero\'s cell', tourTitle: 'Prospero\'s cell', hook: 'The longest scene in the play. Prospero finally tells Miranda who she is, summons Ariel, curses Caliban, and watches Ferdinand fall in love.',
      tour: `Miranda, having watched the wreck from the shore, begs her father to calm the sea. Prospero reassures her: the ship is safe; the storm was his magic; no one has been harmed. Then he sits her down and tells her, for the first time, who she is. Twelve years ago he was Duke of Milan; his brother Antonio, with the help of Alonso of Naples, deposed him; he and three-year-old Miranda were set adrift in a rotten boat. They survived only because Gonzalo provisioned it. Miranda hears the whole story and falls asleep. Prospero summons Ariel, who reports that the wreck went exactly as planned and reminds Prospero that freedom was promised. Caliban is called in, curses, and is sent to fetch wood. Then Ariel leads Ferdinand to the cell on a thread of music. He sees Miranda; she sees him; love at first sight. Prospero, secretly delighted, accuses him of being a spy and puts him in chains.`,
      blurb: `The play's longest scene. Prospero finally tells Miranda the story of their exile, summons Ariel, curses Caliban, and stages the meeting between Miranda and Ferdinand. Love at first sight; Prospero pretends to disapprove and sets Ferdinand to hauling logs.`,
      summary: [
        `Miranda comes in distraught — she has watched the ship break up from the shore and is sure good men have drowned. Prospero, calmly, sets her down on a rock and tells her the storm was his and no one has been harmed. Then, with a long-delayed deliberateness, he tells her who she is. Twelve years ago he was Duke of Milan and one of the most learned men in Europe. He left the running of the dukedom to his brother Antonio. Antonio, with the support of Alonso, King of Naples, seized the dukedom and put Prospero and the three-year-old Miranda into "a rotten carcass of a butt" and pushed them out to sea. Only Gonzalo's secret provisioning of food, water, and Prospero's books kept them alive. Miranda, hearing the story for the first time, falls asleep — Prospero's magic again.`,
        `He summons Ariel. Ariel reports on the storm: the ship is hidden in a deep cove, the mariners are asleep below decks under a charm, the passengers are scattered across the island, all unharmed. Ariel reminds Prospero, with practiced edge, that he was promised liberty for this work. Prospero, irritated, reminds him of the cloven pine — Sycorax had trapped him in it for twelve years; Prospero released him and is owed gratitude. Ariel agrees to one more day's service and is sent off to take the shape of a sea-nymph, invisible to all but Prospero.`,
        `Caliban is called from his cave, curses Prospero in three lines, and reminds him with bitter clarity that the island was his by inheritance from his mother before Prospero arrived. Prospero answers with the rape attempt. Caliban does not deny it; he wishes it had been completed. He is sent for wood. Then Ariel, invisible, leads Ferdinand on stage on a thread of music — "Come unto these yellow sands" — and Ferdinand, who believes his father drowned, follows the song. He sees Miranda; she sees him. The recognition is total and immediate. Prospero, secretly delighted, plays the suspicious father, accuses Ferdinand of being a spy, and freezes him with magic. The trial that will fill Act III has begun.`,
      ],
      appears: [{ id: 'prospero', name: 'Prospero' }, { id: 'miranda', name: 'Miranda' }, { id: 'ariel', name: 'Ariel' }, { id: 'caliban', name: 'Caliban' }, { id: 'ferdinand', name: 'Ferdinand' }],
      themes: [{ slug: 'usurpation', label: 'Usurpation' }, { slug: 'magic', label: 'Magic' }, { slug: 'caliban', label: 'Caliban' }, { slug: 'freedom', label: 'Freedom' }],
    },
    {
      n: 3, title: 'Another part of the island — Antonio tempts Sebastian', tourTitle: 'Antonio tempts Sebastian', hook: 'The grieving king falls asleep on a beach. His brother and the man who deposed Prospero look at each other — and one of them proposes the next murder.',
      tour: `Alonso, Sebastian, Antonio, Gonzalo, and other lords have washed ashore on a different part of the island. Alonso is sunk in grief; he is sure Ferdinand drowned. Gonzalo tries to lift the mood — sketches a famous utopian commonwealth ("no kind of traffic would I admit") — and is mocked by Antonio and Sebastian. Ariel enters invisibly and plays solemn music; Alonso, Gonzalo, and most of the lords fall asleep. Antonio and Sebastian remain awake. Antonio proposes that Sebastian kill his sleeping brother and take the throne of Naples — exactly the crime Antonio committed against Prospero. They draw swords. Ariel wakes Gonzalo just in time. Antonio improvises a story about hearing wild beasts. They press on, looking for the king's son.`,
      blurb: `The shipwrecked court on another beach. Gonzalo sketches his utopian commonwealth; Antonio and Sebastian mock him. Ariel puts most of the party to sleep. Antonio talks Sebastian into murdering the sleeping king. Ariel wakes Gonzalo before the swords come down.`,
      summary: [
        `A different part of the island. Alonso, the King of Naples, is in heavy mourning — Ferdinand is gone, drowned for all he knows. Gonzalo, the honest old counselor, tries to lift the company's spirits, pointing out that their clothes are miraculously dry and the air is wholesome. He builds out a long playful sketch of the commonwealth he would establish on this island if he were its king — no commerce, no magistrate, no riches, no poverty, all things in common, the soil bringing forth on its own. The speech is one of Shakespeare's most-quoted utopian visions and is taken almost verbatim from Montaigne's essay "Of the Cannibals." Antonio and Sebastian, the two cynics of the party, mock him through it.`,
        `Ariel enters invisibly and plays solemn music. Alonso, Gonzalo, and most of the lords fall asleep where they sit. Only Antonio and Sebastian remain awake. Antonio looks at the sleeping king and at his sleeping brother Gonzalo and at the unguarded throne of Naples that lies behind both, and begins, with careful, smiling pressure, to propose the next crime. If Sebastian were to kill the king now, he would be king. The plot is exactly the one Antonio carried out against Prospero — the same logic, the same opportunity, the same persuasive voice. Sebastian, after a moment of feigned scruple, agrees. They draw their swords.`,
        `Ariel returns invisibly and sings into Gonzalo's ear: "while you here do snoring lie, open-eyed conspiracy his time doth take." Gonzalo wakes and shouts; Alonso wakes; the swords are caught suspended above sleeping bodies. Antonio improvises smoothly — he says they thought they heard a herd of wild beasts roaring nearby and drew their weapons in defense. Alonso, distracted by grief, accepts the explanation. The party gathers itself and presses on, looking for Ferdinand. The play has just shown the audience exactly what Antonio is and what Sebastian is willing to be — a fact Prospero will hold over both of them, silently, for the rest of the play.`,
      ],
      appears: [{ id: 'alonso', name: 'Alonso' }, { id: 'sebastian', name: 'Sebastian' }, { id: 'antonio', name: 'Antonio' }, { id: 'gonzalo', name: 'Gonzalo' }, { id: 'ariel', name: 'Ariel' }],
      themes: [{ slug: 'usurpation', label: 'Usurpation' }],
    },
    {
      n: 4, title: 'Caliban meets Stephano and Trinculo', tourTitle: 'Caliban meets the drunkards', hook: 'A jester, a butler with a barrel of wine, a slave who has never tasted alcohol — and one of the strangest first meetings in Shakespeare.',
      tour: `Caliban, hauling wood, sees Trinculo coming and hides under his cloak. Trinculo, fleeing a downpour, sees the cloaked shape, decides it must be some islander or strange fish, and crawls under the same cloak for shelter. Stephano, the drunken butler, arrives singing — he has survived the wreck on a barrel of wine and is now well-supplied. He sees a four-legged shape with two heads and assumes it is a monster. Trinculo recognizes Stephano's voice; the cloak is pulled off; the joke unwinds. Caliban, having tasted wine for the first time, decides Stephano is a god and worships him. He swears to show him every fertile inch of the island. The scene ends with Caliban singing a drunken song of freedom.`,
      blurb: `Caliban hides under a cloak from a downpour. Trinculo crawls in under the same cloak. Stephano arrives drunk with a barrel of wine. Caliban, tasting wine for the first time, decides Stephano is a god and pledges himself as his servant. A drunken song of freedom.`,
      summary: [
        `Another part of the island. Caliban enters carrying a load of wood and cursing Prospero. He hears someone coming — assumes it is one of Prospero's spirits sent to torment him — and throws himself flat under his cloak. Enter Trinculo, the king's jester, who has been wandering alone since the wreck. A storm is gathering. He sees the cloaked, motionless shape on the ground, decides it is "either some islander or some strange fish," and crawls under the cloak for shelter. The audience now sees one cloak with two pairs of legs underneath.`,
        `Enter Stephano, Alonso's drunken butler, who has survived the wreck by floating ashore on a barrel of wine and has been working steadily on it ever since. He sees the four-legged, two-headed shape on the ground and assumes it is a local monster. Caliban groans; Stephano, drunk, decides the monster has a fever and pours wine into Caliban's mouth as medicine. Trinculo, hearing his old friend's voice, calls out from his end of the cloak. Stephano, terrified, thinks the monster is speaking with Trinculo's voice. The cloak is pulled off. Trinculo and Stephano embrace. Caliban, who has now tasted wine for the first time in his life, has fallen to his knees.`,
        `The conversion is immediate and total. Caliban decides Stephano is a god — "hast thou not dropped from heaven?" — and offers himself as his servant. He swears to show him every fertile inch of the island, every spring, every nut-tree, every rock where shellfish cluster. The new master is a drunken servant from a wrecked ship; the old master was a powerful magician; Caliban does not seem able to imagine an existence not under a master, and Shakespeare lets the comedy hold that observation without softening it. Caliban ends the scene singing his own drunken song: "Ca-Caliban has a new master — get a new man! Freedom, high-day, freedom!" The freedom is to a different bondage. The audience can hear the irony; Caliban cannot.`,
      ],
      appears: [{ id: 'caliban', name: 'Caliban' }, { id: 'trinculo', name: 'Trinculo' }, { id: 'stephano', name: 'Stephano' }],
      themes: [{ slug: 'caliban', label: 'Caliban' }, { slug: 'freedom', label: 'Freedom' }],
    },
    {
      n: 5, title: 'Before Prospero\'s cell — Ferdinand carrying logs', tourTitle: 'Ferdinand carrying logs', hook: 'A prince hauling wood for love, a daughter offering to do it for him, and Prospero watching from behind a rock.',
      tour: `Ferdinand, set to work hauling logs for Prospero, finds the labor light because Miranda's love makes it so. Miranda, slipping out without her father's knowledge (or so she thinks — Prospero is watching from the side), offers to carry the logs herself; Ferdinand refuses; they trade tender refusals. They exchange names: hers, "Miranda," he treats as miraculous; his, she has heard her father speak. They pledge themselves to each other, kneel, and become formally engaged. Prospero, watching, blesses them silently — "fair encounter of two most rare affections! Heavens rain grace on that which breeds between 'em!" — and goes back to his book.`,
      blurb: `Ferdinand carries logs for Prospero; Miranda slips out and offers to do it for him; they refuse each other tenderly and exchange vows. Prospero, watching unseen, blesses the engagement and returns to his book.`,
      summary: [
        `In front of Prospero's cell. Ferdinand enters carrying a log. He has been set to the same work Caliban was set to — hauling wood — and is finding it light only because his love for Miranda makes it so. "There be some sports are painful, and their labor / delight in them sets off." He had thought his father drowned and the world ended; instead he finds himself a prisoner doing slave's work, and is happier than he has ever been.`,
        `Miranda enters. She has slipped away, she thinks, without her father's knowledge — Prospero is in fact watching from behind a rock at the side of the stage, invisible to both of them. She offers to carry the logs for Ferdinand; he refuses. She insists. They argue tenderly about which of them gets to do the labor. Then, in one of Shakespeare's plainest love-scenes, they exchange vows. He asks her name; she tells him; he repeats it as a miracle. She tells him she has been forbidden to speak with him and is doing so anyway, against her father's command, because she would rather be his wife than free. He says he is a king's son — though, he adds bitterly, he wishes he were not, because then he would not be set to log-hauling. They kneel. They are formally engaged.`,
        `Prospero, behind his rock, says aside what the audience can see in his face: this is exactly what he has been engineering for the entire play. "Fair encounter of two most rare affections! Heavens rain grace on that which breeds between 'em!" The trial — Ferdinand's willingness to suffer manual labor for Miranda — has been passed. The marriage will go through. The strategic dimension of Prospero's plot, the one that secures Milan to Naples by way of his daughter's heart, is now in place. He returns to his book. Ferdinand and Miranda return to their work. The play has just produced, in the middle of a revenge plot, one of its few unguarded scenes of love.`,
      ],
      appears: [{ id: 'ferdinand', name: 'Ferdinand' }, { id: 'miranda', name: 'Miranda' }, { id: 'prospero', name: 'Prospero' }],
      themes: [{ slug: 'freedom', label: 'Freedom' }, { slug: 'usurpation', label: 'Usurpation' }],
    },
    {
      n: 6, title: 'Caliban plots; "the isle is full of noises"', tourTitle: 'Caliban plots Prospero\'s murder', hook: 'A drunk butler, a jester, and a slave plan a murder. The slave delivers the most beautiful speech in the play.',
      tour: `Caliban, Stephano, and Trinculo are drunk on the beach. Caliban proposes the plan in detail: at noon, when Prospero is asleep, drive a nail into his head — but seize the books first, because the books are the source of his power. Without his books he is a fool, like them. Stephano agrees and styles himself king of the island, with Miranda as his queen. Ariel, invisible, mimics Trinculo's voice and starts an argument among them. Then, frightened by Ariel's music, Stephano panics and Caliban, in a moment of pure poetry, calms him: "be not afeard; the isle is full of noises, sounds and sweet airs that give delight and hurt not." It is the most beautiful speech in the play and it comes out of Caliban\'s mouth.`,
      blurb: `Caliban, Stephano, and Trinculo plot Prospero's murder — but Caliban warns to seize his books first. Ariel, invisible, sets them quarrelling. Caliban, calming a frightened Stephano, delivers the play's most beautiful speech: "the isle is full of noises."`,
      summary: [
        `Another part of the island. The three of them are drunk and getting drunker. Caliban — clearer-eyed than either of his companions despite being more drunk than usual — lays out the murder plan with surprising precision. At about noon Prospero will be asleep. Stephano can drive a nail into his skull or paunch him with a stake or cut his throat. But — Caliban insists — first seize his books. The books are everything. Without them Prospero has no spirits to command, no charms to throw; he is, Caliban says, "but a sot, as I am." With the master dead, Stephano will be king of the island and may have Miranda as his bride; she is a "nonpareil," a beauty without equal. Stephano, drunk and flattered, agrees.`,
        `Ariel enters invisibly. As Caliban speaks, Ariel mimics Trinculo's voice — calling Caliban a liar, contradicting him in his own ally's tone. Trinculo protests his innocence; Stephano grows angry; the plot dissolves into a small drunken brawl about who said what. Ariel watches and steers, planting confusion exactly where needed. The murder plan is not stopped, exactly, but it is made stupid; the conspirators cannot agree among themselves long enough to organize anything.`,
        `Then, in the middle of the squabble, the spirit-music begins again, this time clearly audible to all three. Stephano panics — what is that sound? Caliban answers, in the play's most surprising and beautiful speech: "be not afeard; the isle is full of noises, sounds and sweet airs that give delight and hurt not. Sometimes a thousand twangling instruments will hum about mine ears, and sometime voices that, if I then had waked after long sleep, will make me sleep again." The same Caliban who has been plotting murder reveals an inner life of remembered dreams and waking-into-music. The speech is the play's deepest insistence that whatever else Caliban is, he is also a person who has loved this island. The drunkards, untouched by it, follow the music off-stage, hoping it leads to more wine.`,
      ],
      appears: [{ id: 'caliban', name: 'Caliban' }, { id: 'stephano', name: 'Stephano' }, { id: 'trinculo', name: 'Trinculo' }, { id: 'ariel', name: 'Ariel' }],
      themes: [{ slug: 'caliban', label: 'Caliban' }, { slug: 'magic', label: 'Magic' }],
    },
    {
      n: 7, title: 'The vanishing banquet; Ariel as harpy', tourTitle: 'The vanishing banquet', hook: 'A magical feast appears, the hungry men step forward — and a harpy descends and tells them what they did twelve years ago.',
      tour: `Alonso's company is exhausted from searching the island for Ferdinand. Solemn music; strange shapes bring in a banquet, dance around it, invite the men to eat, and vanish. The lords approach the table. Ariel descends as a harpy with a clap of thunder; the banquet vanishes; Ariel, in a long terrible speech, accuses Alonso, Antonio, and Sebastian of being "three men of sin" and reminds them of what they did to Prospero twelve years ago. The sea, he says, has remembered. Ferdinand's "loss" is the price. The only path back is "heart's sorrow and a clear life ensuing." Ariel vanishes. Prospero, watching unseen above, congratulates him. Alonso, in a kind of trance, hears the wind say his crime to him. Sebastian and Antonio, less stricken, draw their swords against invisible enemies. Gonzalo herds them off-stage to keep them from harming themselves.`,
      blurb: `A magical banquet appears in front of the starving courtiers; as they reach for it, Ariel descends as a harpy, the food vanishes, and the harpy names their crime against Prospero. Alonso, Antonio, and Sebastian are reduced to penitence and panic. Prospero, watching unseen, calls the trick "bravely performed."`,
      summary: [
        `Alonso's party — exhausted from searching the island for Ferdinand — comes upon a clearing. Solemn and strange music plays. Prospero, invisible and standing above the action, watches. Several "strange shapes" enter carrying a banquet, dance around it with gentle gestures of invitation, and depart. The courtiers, hungry and astonished, approach the table. Sebastian, with characteristic dryness, says he will now believe that there are unicorns and that the phoenix throne is in Arabia. Gonzalo notes the gentleness of the islanders. Alonso, more cautious, hesitates — and then, persuaded by hunger, steps forward to eat.`,
        `Thunder and lightning. Ariel descends, in the shape of a harpy, claps his wings on the table — and the banquet vanishes. The courtiers draw their swords and find them magically heavy, useless in their hands. Ariel speaks. He calls them three men of sin: "you 'mongst men being most unfit to live, I have made you mad." He recounts, in the king's hearing, what was done to Prospero and his three-year-old daughter twelve years ago. "Therefore the powers, delaying not forgetting, have incensed the seas and shores, yea, all the creatures, against your peace." Ferdinand's apparent death, he says, is the first installment of the price. The only way back is heart's sorrow and a changed life from this day on. He vanishes, leaving the words hanging in the air.`,
        `Prospero, watching from above, says aside: "bravely the figure of this harpy hast thou performed, my Ariel." His enemies are now exactly where he wanted them. Alonso, in a trance of guilt, hears the words again as the sound of wind and water — the very sea has accused him; he feels his son's death is the visited weight of his crime, and goes to drown himself beside him. Sebastian and Antonio, less penitent, do not collapse; they react with bravado, drawing swords against the invisible spirits. Gonzalo, who has heard nothing of the accusation but sees its effects, recognizes that the three are in some kind of guilt-induced trance and herds the company off-stage to keep them from harming themselves before whatever is governing this island finishes its business with them.`,
      ],
      appears: [{ id: 'alonso', name: 'Alonso' }, { id: 'antonio', name: 'Antonio' }, { id: 'sebastian', name: 'Sebastian' }, { id: 'gonzalo', name: 'Gonzalo' }, { id: 'ariel', name: 'Ariel' }, { id: 'prospero', name: 'Prospero' }],
      themes: [{ slug: 'usurpation', label: 'Usurpation' }, { slug: 'magic', label: 'Magic' }],
    },
    {
      n: 8, title: 'The masque; "our revels now are ended"', tourTitle: 'The masque', hook: 'Three goddesses descend to bless a wedding. Halfway through, the magician remembers a murder plot and stops the show.',
      tour: `Prospero, having approved the engagement, presents Ferdinand and Miranda with a wedding masque. Iris, Ceres, and Juno descend; nymphs and reapers enter and dance. Mid-pageant Prospero starts and remembers Caliban's murder plot. The spirits "to a strange, hollow, and confused noise, heavily vanish." Ferdinand and Miranda are alarmed by his change. Prospero gives them — and the play — its most-quoted speech: "our revels now are ended... we are such stuff as dreams are made on, and our little life is rounded with a sleep." He sends them to his cell to compose themselves and turns to Ariel. Caliban, Stephano, and Trinculo are coming. He has Ariel hang a line of glittering clothes outside the cell as a trap. The drunkards arrive, the clothes catch their attention, they steal them; spirit-hounds are loosed and chase them off. The two main plots — the courtly and the comic — converge into one.`,
      blurb: `Prospero presents Ferdinand and Miranda with a wedding masque of goddesses. Halfway through he remembers Caliban's plot and ends it. The "our revels now are ended" speech follows. He sets glittering clothes as a trap for the conspirators; spirit-hounds chase them off.`,
      summary: [
        `Before Prospero's cell. Prospero gives Ferdinand a stern lecture on chastity until the wedding and, satisfied with his promise, presents the engaged couple with a betrothal masque. Three goddesses descend on machinery: Iris, the rainbow messenger; Ceres, goddess of the harvest; Juno, queen of the gods. They sing blessings on the marriage. Nymphs in green enter and dance with sunburnt reapers in a stately country dance. Ferdinand, watching, says he could live in this place forever. The spectacle is the high point of Prospero's stage-management.`,
        `Then, mid-dance, Prospero starts. He has remembered, with a sudden cold, that Caliban and his two companions are at this moment moving through the woods toward the cell to murder him. The spirits "to a strange, hollow, and confused noise, heavily vanish." Ferdinand and Miranda are bewildered. Prospero turns to them and gives the speech that has become one of the most-quoted in Shakespeare. "Our revels now are ended... the cloud-capped towers, the gorgeous palaces, the solemn temples, the great globe itself, yea, all which it inherit, shall dissolve... we are such stuff as dreams are made on, and our little life is rounded with a sleep." It is the play's deepest meditation on the unreality of the made world, delivered by the magician whose business has been making.`,
        `He apologizes for his "infirmity," sends Ferdinand and Miranda to his cell to recover, and turns to Ariel. The drunkards are nearly here. He has Ariel hang a line of glittering, expensive-looking robes outside the cell as bait. Caliban, Stephano, and Trinculo arrive wet from a stinking pool Ariel has led them through. Caliban begs them to ignore the clothes and finish the murder first — "let it alone, thou fool, it is but trash" — but Stephano and Trinculo cannot resist the silks. They strip the line. Spirit-hounds are loosed at Prospero's command; the three are chased off-stage, yelping. All Prospero's enemies are now at his mercy, and within an hour the labors of the day will end.`,
      ],
      appears: [{ id: 'prospero', name: 'Prospero' }, { id: 'ferdinand', name: 'Ferdinand' }, { id: 'miranda', name: 'Miranda' }, { id: 'ariel', name: 'Ariel' }, { id: 'caliban', name: 'Caliban' }, { id: 'stephano', name: 'Stephano' }, { id: 'trinculo', name: 'Trinculo' }],
      themes: [{ slug: 'masque', label: 'The masque' }, { slug: 'magic', label: 'Magic' }, { slug: 'caliban', label: 'Caliban' }],
    },
    {
      n: 9, title: 'The renunciation; the forgiving', tourTitle: 'The renunciation', hook: 'Prospero breaks his staff, drowns his book, forgives every man who wronged him — and Antonio, given his life back, says nothing.',
      tour: `Prospero, robed in his magic for the last time, draws a circle on the ground and brings the courtiers into it. They stand frozen as he speaks the renunciation: he will break his staff, drown his book "deeper than did ever plummet sound," forgive his enemies, return to Milan. The charm wears off; the courtiers wake. Alonso weeps and asks pardon openly; Prospero gives it and embraces him. Sebastian and Antonio — Prospero turns to each in turn and forgives without confession; Antonio says nothing in reply. Then Prospero opens his cell to reveal Ferdinand and Miranda playing chess. Alonso, who has spent the day mourning his son, cries out. Miranda, seeing the courtiers for the first time, speaks the play's most-quoted line: "O wonder! How many goodly creatures are there here! How beauteous mankind is! O brave new world, that has such people in't!" The Boatswain arrives with news that the ship is whole. Caliban, Stephano, and Trinculo are dragged in in stolen clothes; Caliban says he will be wise hereafter. Ariel is freed. The play prepares to sail home.`,
      blurb: `Prospero forgives every man who wronged him, breaks his staff, and drowns his book. Ferdinand is restored to Alonso; Miranda gives the "brave new world" line. The ship is whole. Caliban is brought in chains and promises to seek grace. Ariel is freed. The play turns toward Milan.`,
      summary: [
        `Before Prospero's cell. Ariel reports that the courtiers are all gathered, frozen by Prospero's spell, weeping. Prospero decides he has gone far enough. "The rarer action is in virtue than in vengeance." He puts on his magic robe one last time, draws a circle on the ground, and Ariel leads the company in: Alonso, Sebastian, Antonio, Gonzalo, all standing as if charmed. Prospero, invisible to them, addresses each in turn. He speaks the renunciation: "this rough magic I here abjure... I'll break my staff, bury it certain fathoms in the earth, and deeper than did ever plummet sound I'll drown my book." The charm dissolves. The courtiers wake to find Prospero standing in the dukely robes Ariel has dressed him in.`,
        `Alonso, dazed, recognizes him. Prospero embraces him. Alonso resigns the dukedom of Milan, asks pardon, and is given it openly. Then Prospero turns to Sebastian and Antonio. To Sebastian he says he could, if he chose, "justify you traitors" — name, in front of the king, what was attempted on the beach — and chooses not to. To Antonio he says, "for you, most wicked sir, whom to call brother would even infect my mouth, I do forgive thy rankest fault... and require my dukedom of thee, which perforce, I know, thou must restore." Antonio gives the dukedom back. He says nothing else. The line over which more critical ink has been spilled than perhaps any other in the play is the line Antonio does not speak.`,
        `Prospero draws back the curtain to his cell and reveals Ferdinand and Miranda playing chess. Alonso, who has spent the day believing his son drowned, weeps for joy. Miranda, seeing the courtiers behind him, gives the play's most-quoted line: "O wonder! How many goodly creatures are there here! How beauteous mankind is! O brave new world, that has such people in't!" Prospero, who knows exactly what kind of people these are, says quietly, "tis new to thee." The Boatswain arrives with news that the ship is whole. Ariel drives in Caliban, Stephano, and Trinculo in their stolen robes; Caliban, looking at his father's old enemy, says, "I'll be wise hereafter, and seek for grace. What a thrice-double ass was I, to take this drunkard for a god." Prospero promises one last night's hospitality and a fair voyage home in the morning. Then, alone with Ariel, he releases him: "to the elements be free, and fare thou well." Ariel exits singing.`,
      ],
      appears: [{ id: 'prospero', name: 'Prospero' }, { id: 'ariel', name: 'Ariel' }, { id: 'alonso', name: 'Alonso' }, { id: 'antonio', name: 'Antonio' }, { id: 'sebastian', name: 'Sebastian' }, { id: 'gonzalo', name: 'Gonzalo' }, { id: 'ferdinand', name: 'Ferdinand' }, { id: 'miranda', name: 'Miranda' }, { id: 'caliban', name: 'Caliban' }, { id: 'stephano', name: 'Stephano' }, { id: 'trinculo', name: 'Trinculo' }, { id: 'boatswain', name: 'Boatswain' }],
      themes: [{ slug: 'usurpation', label: 'Usurpation' }, { slug: 'magic', label: 'Magic' }, { slug: 'freedom', label: 'Freedom' }, { slug: 'caliban', label: 'Caliban' }],
    },
    {
      n: 10, title: 'Epilogue — spoken by Prospero', tourTitle: 'The epilogue', hook: 'The magician alone on stage, charms gone, asking the audience to clap him out of the theater.',
      tour: `The stage empties. Prospero alone, in front of the audience. The robe of magic is gone. The verse changes — short, rhymed couplets, in place of the great blank-verse paragraphs of the play. "Now my charms are all o'erthrown, and what strength I have's mine own." He needs the audience to send him on his way; without their applause he is, technically, still confined to the island and the stage. "Let your indulgence set me free." It is the play's quietest and strangest moment. The man who has spent the play binding and releasing others stands, finally, asking to be released.`,
      blurb: `Prospero alone on stage, his magic gone, asking the audience for the breath of their applause. The man who has spent the play binding and releasing others now needs to be released. Often read as Shakespeare's own farewell to the theater.`,
      summary: [
        `The stage has emptied. Ferdinand and Miranda have gone to compose themselves. Alonso and the courtiers have gone to Prospero's cell for the night's storytelling. Caliban is fetching firewood for the last time. Ariel is gone — vanished into the elements, free. What remains is Prospero alone, downstage, in front of the audience. He is no longer wearing the magic robe. The verse he has been speaking in for five acts — long, supple blank verse — has been replaced by the shorter, rhymed couplets of an epilogue.`,
        `He addresses the house directly. His charms, he says, are all overthrown. What strength he has now is his own. The island is behind him; he is to be sent to Naples in the morning; but right now, at this moment in the theater, he is technically still confined here — a player who has finished his part and cannot leave the stage until the audience consents. "Now I want / spirits to enforce, art to enchant; / and my ending is despair / unless I be relieved by prayer, / which pierces so that it assaults / mercy itself, and frees all faults. / As you from crimes would pardoned be, / let your indulgence set me free."`,
        `It is the strangest moment in the play. The man who has spent every preceding scene binding and releasing others — Ariel, Caliban, Ferdinand, the entire court of Naples — now stands as a supplicant in front of the audience and asks to be released. The breath of their applause is the wind that will carry his ship home. The autobiographical reading — Shakespeare, fifty years old, on the brink of leaving London for Stratford and retirement, his last solo play just ending — has shaped centuries of how the moment is staged and heard. Whether or not Shakespeare intended it, the gesture is one of the great gestures of renunciation in Western drama: an artist, having exhausted his powers, acknowledges that he is now in his audience's hands. The applause comes. The play ends.`,
      ],
      appears: [{ id: 'prospero', name: 'Prospero' }],
      themes: [{ slug: 'magic', label: 'Magic' }, { slug: 'masque', label: 'The masque' }, { slug: 'freedom', label: 'Freedom' }],
    },
  ],
}
