#!/usr/bin/env python3
"""Write EVIDENCE.md: exact quotes, with coordinates, from the pinned texts.

For each evidence point it prints the Garnett source (original-en), live
modern-en and accepted candidate text, plus the paragraph-end UTF-16 offset
in each. Offline and deterministic.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INP = ROOT / "inputs"
norm = lambda t: re.sub(r" {2,}", " ", t.replace("\n", " "))
u16 = lambda t: len(t.encode("utf-16-le")) // 2
py = lambda t, o: len(t.encode("utf-16-le")[: 2 * o].decode("utf-16-le"))

TEXTS = {"source (original-en, Garnett)": "source.json", "live modern-en": "baseline-live-modern-en.json",
         "accepted candidate modern-en": "candidate.json"}
POINTS = [
    ((3, 38), "First mention: the mother's letter. The reader learns Dounia was a governess in the Svidrigaïlovs' house and that he treated her rudely. The rest of the paragraph shows Marfa Petrovna is his living wife and active in the story, so he is not a widower here, and he is in the country, not St. Petersburg.", None),
    ((16, 73), "First statement that Marfa Petrovna is dead. From 3.38 the reader knows she is his wife, so this is the earliest support for 'recently widowed'.", r"Marfa Petrovna(?:'s| is|’s) dead"),
    ((17, 47), "The link is restated for Raskolnikov: Marfa Petrovna Svidrigaïlov.", r"Marfa Petrovna Svidriga"),
    ((20, 68), "He appears in person in Raskolnikov's room in St. Petersburg and introduces himself. This supports his presence in the city, but the family is not yet aware.", r"Svidriga"),
    ((22, 31), "Luzhin tells the family that he set off for Petersburg right after his wife's funeral.", r"Petersburg"),
    ((22, 32), "Dounia's alarm.", r"alarm|Petersburg"),
    ((22, 34), "Pulcheria's alarm: the whole family now knows and is alarmed.", r"peace"),
    ((22, 36), "Pulcheria is convinced he caused Marfa Petrovna's death.", r"cause"),
    ((22, 37), "Luzhin reports a hushed-up criminal case of homicidal brutality: 'rumored to be responsible for terrible things' is now supported. This is the release point for svidrigailov-2.", r"hushed up"),
]


def main():
    data = {k: json.loads((INP / f).read_text())["chapters"] for k, f in TEXTS.items()}
    cards = json.loads((INP / "crime-and-punishment.v1.json").read_text())["editions"]
    fm = {ed: next(c for c in cards[ed]["characters"] if c["id"] == "svidrigailov")["firstMention"]["offset"] for ed in cards}
    out = ["# Source evidence: Svidrigaïlov snapshot correction", "",
           "Generated by `tools/build_evidence.py` from the pinned inputs. Coordinates are chapter.paragraph (1-based chapter, 0-based paragraph). `end` is the paragraph-end offset in UTF-16 units after `prose-reader-v1` normalization.", ""]
    for (c, p), why, pat in POINTS:
        out += [f"## {c}.{p}", "", why, ""]
        for label, chs in data.items():
            t = norm(chs[c - 1]["paragraphs"][p])
            if (c, p) == (3, 38):
                # Candidate first-mention end = accepted identity-review ledger entry R025 final span end (2536).
                off = fm["original-en"] if label.startswith("source") else fm["modern-en"] if label.startswith("live") else 2536
                i = py(t, off)
                quote = "…" + t[max(0, i - 260):i] + f" ⟦first mention ends here, offset {off}⟧"
            else:
                m = re.search(pat, t)
                i = m.start() if m else 0
                quote = ("…" if i > 200 else "") + t[max(0, i - 200):i + 220] + ("…" if i + 220 < len(t) else "")
            out.append(f"- **{label}** (end {u16(t)}): {quote}")
        out.append("")
    (ROOT / "EVIDENCE.md").write_text("\n".join(out) + "\n")
    print("EVIDENCE.md written")


if __name__ == "__main__":
    main()
