#!/usr/bin/env python3
"""Write EVIDENCE.md: exact quotes, with coordinates, from the pinned texts.

For each evidence point it prints the Garnett source (original-en), live
modern-en and accepted candidate text, plus the paragraph-end UTF-16 offset
in each. Offline and deterministic.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INP = ROOT / "inputs"
norm = lambda t: re.sub(r" {2,}", " ", t.replace("\n", " "))
u16 = lambda t: len(t.encode("utf-16-le")) // 2
py = lambda t, o: len(t.encode("utf-16-le")[: 2 * o].decode("utf-16-le"))

TEXTS = {"source (original-en, Garnett)": "source.json", "live modern-en": "baseline-live-modern-en.json",
         "accepted candidate modern-en": "candidate.json"}
POINTS = [
    ((3, 38), "First mention (svidrigailov-1 availability). Before the name the reader knows only: Dounia had a hard time at the Svidrigaïlovs', she took the governess position there, and she has been back with her mother for six weeks. This is all svidrigailov-1 now says. The rest of the paragraph shows Marfa Petrovna is his living wife, so he is not a widower, and he is in the country, not St. Petersburg.", None),
    ((3, 38, "reveal"), "Same paragraph, after the first mention: the letter stages his passion for Dounia as a surprise ('And how do you think it all turned out? Would you believe...'). Under the card policy a relationship revealed as a surprise stays gated, so 'pursued Dunya' is released at the end of 3.38 (svidrigailov-2), not at the name. 'Unsettling' is not part of the surprise: it is a character judgement resting on text after the name (his rudeness, mocking remarks and drinking), and such judgements are released at paragraph end, so it too joins svidrigailov-2.", r"how do you think it (?:was all explained|all turned out)"),
    ((3, 38, "proposal"), "The open proposal, and 'another estate (of his)'. That estate is the only property reference in 3.38; it does not establish that he is wealthy, and wealth is not inferred from it.", r"proposal"),
    ((21, 33), "Wealth check: his own account ('not considered poor'; income from forests and water meadows). This is his claim, and 'not poor' is not 'wealthy'; it does not establish wealth.", r"poor"),
    ((22, 2), "Wealth check: Raskolnikov calls him 'that landowner'. Landowning is not a statement of wealth.", r"landowner"),
    ((21, 37), "Wealth check: debtors' prison, bought out by Marfa Petrovna. Not used to infer poverty.", r"debtors|debt"),
    ((21, 43), "Wealth check: Marfa Petrovna 'had a fortune' and gave him money. It is her fortune; this does not establish that he is wealthy.", r"fortune"),
    ((21, 103), "Wealth check: 'though I'm not rich' and a free ten thousand. His own claim and his offer are both excluded as evidence either way, as instructed. A whole-text scan of 3.38-22.34 finds no passage that establishes him as wealthy (the nearest are 3.38 'another estate', 21.33, 21.43 and 22.2 above), so 'Wealthy' is omitted from every snapshot.", r"rich"),
    ((16, 73), "First statement that Marfa Petrovna is dead. From 3.38 the reader knows she is his wife, so this is the earliest support for 'recently widowed'.", r"Marfa Petrovna(?:'s| is|’s) dead"),
    ((17, 47), "The link is restated for Raskolnikov: Marfa Petrovna Svidrigaïlov.", r"Marfa Petrovna Svidriga"),
    ((17, 49), "First rumor of terrible deeds, which also supports the dark-reputation subtitle: Pulcheria says he seems to have caused his wife's death ('They say he beat her dreadfully'). Raskolnikov repeats it to him at 21.16.", r"beat her"),
    ((20, 68), "He appears in person in Raskolnikov's room in St. Petersburg and introduces himself. This supports his presence in the city, but the family is not yet aware.", r"Svidriga"),
    ((22, 31), "Luzhin tells the family that he set off for Petersburg right after his wife's funeral.", r"Petersburg"),
    ((22, 32), "Dounia's alarm.", r"alarm|Petersburg"),
    ((22, 34), "Pulcheria's alarm: the whole family now knows and is alarmed. Every clause of svidrigailov-3 is now supported, so this is its release point.", r"peace"),
    ((22, 36), "Pulcheria is convinced he caused Marfa Petrovna's death.", r"cause"),
    ((22, 37), "Luzhin's further account of a hushed-up criminal case of homicidal brutality (after the release point; corroborates the rumor clause).", r"hushed up"),
]


def main():
    data = {k: json.loads((INP / f).read_text())["chapters"] for k, f in TEXTS.items()}
    cards = json.loads((INP / "crime-and-punishment.v1.json").read_text())["editions"]
    fm = {ed: next(c for c in cards[ed]["characters"] if c["id"] == "svidrigailov")["firstMention"]["offset"] for ed in cards}
    out = ["# Source evidence: Svidrigaïlov snapshot correction", "",
           "Generated by `tools/build_evidence.py` from the pinned inputs. Coordinates are chapter.paragraph (1-based chapter, 0-based paragraph). `end` is the paragraph-end offset in UTF-16 units after `prose-reader-v1` normalization.", ""]
    for key, why, pat in POINTS:
        c, p = key[0], key[1]
        out += [f"## {c}.{p}" + (f" ({key[2]})" if len(key) > 2 else ""), "", why, ""]
        for label, chs in data.items():
            t = norm(chs[c - 1]["paragraphs"][p])
            if key == (3, 38):
                # Candidate first-mention end = accepted identity-review ledger entry R025 final span end (2536).
                off = fm["original-en"] if label.startswith("source") else fm["modern-en"] if label.startswith("live") else 2536
                i = py(t, off)
                quote = "…" + t[max(0, i - 260):i] + f" ⟦first mention ends here, offset {off}⟧"
            else:
                m = re.search(pat, t)
                i = m.start() if m else 0
                quote = ("…" if i > 200 else "") + t[max(0, i - 200):i + 220] + ("…" if i + 220 < len(t) else "")
            out.append(f"- **{label}** (end {u16(t)}): {quote}")
        out.append("")
    (ROOT / "EVIDENCE.md").write_text("\n".join(out) + "\n")
    print("EVIDENCE.md written")


if __name__ == "__main__":
    main()
