"""Manually authored recognition copy for the full Enquiry, including its notes."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='reference',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))
for row in [
('cicero','Cicero','The Roman orator and philosophical writer, also called Tully.','Cicero|Tully'),
('aristotle','Aristotle','The Greek philosopher whose work ranges across logic, ethics and the natural world.','Aristotle'),
('bruyere','Jean de La Bruyère','The French writer known for his portraits of human character.','La Bruyere|La Bruyère'),
('malebranche','Nicolas Malebranche','The French philosopher associated with the view that God directly causes events.','Malebranche|MALEBRANCHE'),
('addison','Joseph Addison','The English essayist used as an example of accessible philosophical writing.','Addison'),
('locke','John Locke','The English philosopher whose account of ideas Hume repeatedly examines.','Locke|LOCKE'),
('adam','Adam','The first man in the biblical creation story, imagined here reasoning without previous experience.','Adam'),
('euclid','Euclid','The ancient Greek mathematician whose geometry supplies examples of demonstration.','Euclid'),
('epictetus','Epictetus','The Stoic philosopher named in the discussion of philosophy and everyday life.','Epictetus'),
('tiberius','Tiberius','The Roman emperor used as a historical example of tyranny.','TIBERIUS|Tiberius'),
('nero','Nero','The Roman emperor cited alongside Tiberius in the argument about experience.','NERO|Nero'),
('plato','Plato','The Athenian philosopher associated with the Academy.','Plato'),
('speusippus','Speusippus','Plato’s nephew and successor as head of the Academy.','Speusippus'),
('xenocrates','Xenocrates','The Greek philosopher who led the Academy after Speusippus.','Xenocrates'),
('polemo','Polemo','The philosopher who succeeded Xenocrates at the Academy.','Polemo'),
('scipio','Scipio Aemilianus','The Roman statesman and general recalled in Cicero’s quotation about memorable places.','Scipionem'),
('cato-elder','Cato the Elder','The Roman statesman and censor remembered in the Latin quotation from Cicero.','Catonem'),
('laelius','Gaius Laelius','The Roman statesman associated with Scipio Aemilianus, named in Cicero’s quotation.','Laelium'),
('newton','Isaac Newton','The English mathematician and natural philosopher whose account of motion Hume discusses.','Sir ISAAC NEWTON|Sir Isaac Newton'),
('descartes','René Descartes','The French philosopher discussed in relation to causation and systematic doubt.','DES CARTES|Des Cartes|Descartes'),
('clarke','Samuel Clarke','The English philosopher and theologian named in the note on causal power.','CLARKE|Clarke'),
('cudworth','Ralph Cudworth','The English philosopher and theologian cited alongside Locke and Clarke.','CUDWORTH|Cudworth'),
('hippocrates','Hippocrates','The ancient Greek physician invoked in comparing human and natural history.','Hippocrates'),
('polybius','Polybius','The Greek historian whose accounts of human conduct Hume recommends studying.','Polybius'),
('tacitus','Tacitus','The Roman historian cited both on human conduct and on reported miracles.','Tacitus'),
('curtius','Quintus Curtius','The Roman historian of Alexander the Great.','Quintus Curtius'),
('alexander-great','Alexander the Great','The Macedonian king and conqueror whose extraordinary exploits are discussed.',''),
('tillotson','John Tillotson','The English archbishop whose argument about testimony opens the discussion of miracles.','Dr. Tillotson|Tillotson'),
('cato-younger','Cato the Younger','The Roman statesman whose reputation for truthfulness supplies Hume’s example about testimony.','Cato|Catonis'),
('plutarch','Plutarch','The ancient Greek biographer cited as a source of historical testimony.','Plutarch'),
('demosthenes','Demosthenes','The Athenian orator used as a comparison for religious eloquence.','Demosthenes'),
('alexander-prophet','Alexander of Abonoteichus','The religious impostor described by Lucian, used in Hume’s discussion of miracle reports.',''),
('lucian','Lucian','The Greek satirist whose account exposes Alexander’s religious imposture.','Lucian|Luciani'),
('marcus','Marcus Aurelius','The Roman emperor and philosopher mentioned in the examples about religion and philosophy.','Marcus Aurelius'),
('livy','Livy','The Roman historian, also called Titus Livius, whose reports of prodigies Hume discusses.','Titus Livius|Livy'),
('muhammad','Muhammad','The prophet of Islam, named in comparing religious miracle traditions.','Mahomet|Mohammed'),
('vespasian','Vespasian','The Roman emperor at the center of Tacitus’s account of alleged healing miracles.','Vespasian'),
('demetrius','Demetrius Poliorcetes','The Macedonian ruler mentioned as accepting divine honors.','Demetrius'),
('suetonius','Suetonius','The Roman biographer cited in the note on Vespasian.','Suetonius'),
('retz','Cardinal de Retz','The French churchman and politician who recounts the alleged healing at Saragossa.','Cardinal de Retz|Retz'),
('paris','Abbé Pâris','The French Jansenist deacon whose tomb became the focus of reported cures.','Abbe Paris|Abbé Paris'),
('montgeron','Montgeron','The French judicial official who published evidence for the Jansenist miracle claims.','Mons. Montgeron|Montgeron'),
('noailles','Cardinal Noailles','The archbishop of Paris under whose authority evidence for the cures was examined.','cardinal Noailles|Noailles'),
('le-franc','Mademoiselle le Franc','The woman whose reported cure became a disputed Jansenist miracle case.','Mademoiselle le Franc'),
('herault','Hérault','The Paris police official charged with investigating and discrediting the reported cures.','Mons. Heraut|Heraut|Mons. Hérault|Hérault'),
('thibaut','Mademoiselle Thibaut','The woman examined by De Sylva in another disputed healing case.','Mademoiselle Thibaut'),
('sylva','De Sylva','The physician sent to examine Mademoiselle Thibaut.','De Sylva|De Silva'),
('paul','Saint Paul','The Christian apostle invoked in the comparison with miraculous prison releases.','St. Paul|Paul'),
('chatillon','Duc de Châtillon','The French nobleman who testified about a reported cure of his servant.','Due de Chatillon|Duc de Châtillon|Duc de Chatillon'),
('pascal','Blaise Pascal','The French mathematician and religious writer whose niece is discussed in the miracle examples.','Pascal'),
('racine','Jean Racine','The French dramatist and historian of Port-Royal cited on the reported cure.','Racine'),
('arnauld','Antoine Arnauld','The French Jansenist theologian named among Port-Royal’s influential writers.','Amaud|Arnauld'),
('nicole','Pierre Nicole','The French moralist and theologian associated with Port-Royal.','Nicole'),
('herodotus','Herodotus','The ancient Greek historian whose marvelous accounts are compared with later religious histories.','Herodotus'),
('mariana','Juan de Mariana','The Spanish historian and Jesuit cited among Christian writers of marvelous accounts.','Mariana'),
('bede','Bede','The English monk and historian cited alongside Mariana.','Bede'),
('lucretius','Lucretius','The Roman poet cited for the Latin phrase about an eager audience.','Lucret'),
('elizabeth','Elizabeth I','The English queen used in an explicitly imaginary example of death and resurrection.','Queen Elizabeth'),
('bacon','Francis Bacon','The English philosopher quoted on scrutinizing reports of extraordinary events.','Lord Bacon'),
('protagoras','Protagoras','The Greek sophist mentioned in the discussion of religious persecution.','Protagoras'),
('socrates','Socrates','The Athenian philosopher whose trial and death enter the discussion of tolerance.','Socrates'),
('epicurus','Epicurus','The Greek philosopher whose position the skeptical friend defends in an imagined speech.','Epicurus'),
('dio','Cassius Dio','The Roman historian cited in the note on imperial support for philosophy.','Dio'),
('zeuxis','Zeuxis','The ancient Greek painter used in an example about what a work reveals of its maker.','Zeuxis'),
('berkeley','George Berkeley','The Irish philosopher whose arguments about perception Hume discusses.','Dr. Berkeley|Berkeley'),
('bayle','Pierre Bayle','The French philosopher and critic mentioned in the discussion of skepticism.','Bayle'),
('caesar','Julius Caesar','The Roman statesman used in an example distinguishing existence from mathematical truth.','Caesar'),
]:add(*row)
for row in [
('venus','Venus','The Roman goddess of love, mentioned as a subject for painting.','Venus','mythological-figure'),
('helen','Helen of Troy','The famously beautiful woman of Greek legend, mentioned as a subject for painting.','Helen','literary-figure'),
('god','God','The divine creator whose existence and causal role are examined in the philosophical arguments.','God|Deity|Supreme Being|Creator|Maker|Almighty|Author of nature|author of nature','religious-figure'),
('jesus','Jesus Christ','The central figure of Christianity, called the Savior in the discussion of miracle testimony.','Saviour|Savior','religious-figure'),
('spirit','The Holy Spirit','The divine Spirit invoked in the discussion of Christian belief and testimony.','Holy Spirit','religious-figure'),
('serapis','Serapis','The Egyptian and Greek god invoked in the account of Vespasian’s alleged cures.','Serapis','mythological-figure'),
('devil','The Devil','The evil spiritual being invoked in an explanation offered for the disputed miracles.','devil','religious-figure'),
('jupiter','Jupiter','The Roman chief god used in the imagined argument about divine providence.','Jupiter','mythological-figure'),
('gabriel','Gabriel','The angel used alongside Caesar in an example about claims of existence.','angel Gabriel|Gabriel','religious-figure'),
]:add(*row[:4],kind=row[4])
for row in [
('indian-prince','The Indian prince','The unnamed prince in the anecdote about finding reports of frost hard to believe.','Indian prince'),
('blind-man','The blind man in Alexandria','The man said to have been healed by Vespasian’s spittle.',''),
('lame-man','The lame man in Alexandria','The man said to have been healed by Vespasian’s touch.',''),
('doorkeeper','The Saragossa doorkeeper','The cathedral doorkeeper whose supposedly restored leg is described by Cardinal de Retz.',''),
('noailles-successor','Noailles’s successor','The later archbishop of Paris asked to examine the Jansenist miracle claims.',''),
('chatillon-servant','Châtillon’s servant','The servant whose reported recovery is supported by his employer’s testimony.',''),
('marguerite','Marguerite Périer','Pascal’s niece, whose reported healing at Port-Royal is discussed.',''),
('tournay','The bishop of Tournay','The churchman cited as using the Port-Royal healing account against unbelief.',''),
('queen-regent','The queen-regent of France','The French regent who sends her physician to examine the Port-Royal cure.',''),
('queen-physician','The queen-regent’s physician','The doctor sent to investigate the reported cure at Port-Royal.',''),
('king-france','The king of France','The French king whose edict closes access to the abbé’s tomb.',''),
]:add(*row,kind='unnamed-role' if row[0]!='marguerite' else 'person')
add('friend','The skeptical friend','Hume’s unnamed conversation partner in the discussion of providence and a future life.','',category='supporting',kind='unnamed-role')
add('hume-dialogue','Hume, in the conversation','The author speaking with his skeptical friend in the staged philosophical conversation.','',category='supporting')
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='hume-enquiry',contentVersion='2026-09-10.1',coverage='All twelve sections, stored as nineteen reading units, including the source notes in both English editions. Named thinkers, historical, literary and religious references; identified people in miracle examples; and the speakers in the staged conversation. No conjectural identities for generic thought-experiment people or school-name adjectives.',entities=entities),ensure_ascii=False,indent=2)+'\n')
