"""Manually authored recognition cards for both full English texts of the play."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

for row in [
('falstaff','Sir John Falstaff','An old knight of the Prince’s company, fat, penniless and quick.','FALSTAFF|Falstaff|Jack Falstaff','central'),
('prince-henry','Prince Henry','King Henry’s eldest son and heir, called Harry Monmouth.','PRINCE|PRINCE HENRY|HENRY V','central'),
('henry-iv','King Henry the Fourth','The King, worn down by rebellion and sickness.','HENRY IV','major'),
('shallow','Justice Shallow','A country justice of Gloucestershire, and Falstaff’s old acquaintance.','SHALLOW|Shallow|Robert Shallow','major'),
('chief-justice','The Lord Chief Justice','The chief justice of the King’s Bench, who once committed the Prince.','CHIEF JUSTICE','major'),
('hostess','Mistress Quickly','Hostess of the Boar’s Head tavern in Eastcheap.','HOSTESS|Hostess|Nell Quickly|Quickly','major'),
('doll','Doll Tearsheet','A woman of the Boar’s Head, and Falstaff’s companion.','DOLL|Doll Tearsheet|Doll|Dorothy','major'),
('pistol','Pistol','An ancient in Falstaff’s following, given to fustian and quarrels.','PISTOL|Pistol','major'),
('bardolph','Bardolph','A corporal in Falstaff’s following, known by his red face.','BARDOLPH','major'),
('poins','Poins','A companion of the Prince’s.','POINS|Poins','major'),
('lancaster','Prince John of Lancaster','King Henry’s second son, who commands against the rebels.','LANCASTER','major'),
('archbishop','The Archbishop of York','Richard Scroop, the churchman leading the rebellion.','ARCHBISHOP|Scroop','major'),
('warwick','The Earl of Warwick','A nobleman of the King’s council, of the Nevil family.','WARWICK|Warwick|Nevil','major'),
('westmoreland','The Earl of Westmoreland','A nobleman who commands for the King.','WESTMORELAND|Westmoreland','major'),
('lord-bardolph','Lord Bardolph','A nobleman of the rebel party; not the corporal of the same name.','LORD BARDOLPH','major'),
('northumberland','The Earl of Northumberland','Hotspur’s father, and the rebellion’s absent leader.','NORTHUMBERLAND|Northumberland','major'),
('page','The Page','The boy Prince Henry gave Falstaff for a page.','PAGE'),
('mowbray','Lord Mowbray','The Earl Marshal, one of the rebel lords.','MOWBRAY|Mowbray'),
('hastings','Lord Hastings','One of the rebel lords.','HASTINGS|Hastings'),
('silence','Justice Silence','A country justice, Shallow’s cousin.','SILENCE|Silence'),
('clarence','Thomas, Duke of Clarence','King Henry’s son, brother to the Prince.','CLARENCE|Thomas of Clarence'),
('davy','Davy','Justice Shallow’s servant, who runs his household and his farm.','DAVY|Davy'),
('gloucester','Humphrey, Duke of Gloucester','King Henry’s youngest son.','GLOUCESTER|Humphrey'),
('fang','Fang','A sergeant employed to arrest Falstaff.','FANG|Fang'),
('feeble','Francis Feeble','A woman’s tailor, pressed for the wars.','FEEBLE|Feeble|Francis Feeble'),
('morton','Morton','The gentleman who brings Northumberland the true news from Shrewsbury.','MORTON|Morton'),
('mouldy','Ralph Mouldy','A Gloucestershire man pressed for the wars, and bought out again.','MOULDY|Mouldy|Ralph Mouldy'),
('bullcalf','Peter Bullcalf','A Gloucestershire man pressed for the wars, and bought out again.','BULLCALF|Bullcalf|Peter Bullcalf'),
('colevile','Sir John Colevile','A rebel knight who yields himself to Falstaff.','COLEVILE|Colevile|Sir John Colevile'),
('gower','Gower','A gentleman who brings the Chief Justice his news.','GOWER|Gower'),
('snare','Snare','A sergeant employed with Fang to arrest Falstaff.','SNARE|Snare'),
('shadow','Simon Shadow','A Gloucestershire man pressed for the wars.','SHADOW|Shadow|Simon Shadow'),
('wart','Thomas Wart','A Gloucestershire man pressed for the wars.','WART|Wart|Thomas Wart|Wart’s'),
('travers','Travers','Northumberland’s servant, who brings him the first false report.','TRAVERS|Travers'),
('lady-northumberland','Lady Northumberland','Northumberland’s wife.','LADY NORTHUMBERLAND'),
('lady-percy','Lady Percy','Hotspur’s widow, and Northumberland’s daughter-in-law.','LADY PERCY'),
('surrey','The Earl of Surrey','A nobleman attending the King.','Surrey'),
('harcourt','Harcourt','A gentleman who brings the King news of the northern defeat.','Harcourt'),
('blunt','Sir John Blunt','A knight in Prince John’s company.','Blunt'),
('rumour','Rumour','The figure painted full of tongues who speaks the Induction.','RUMOUR|Rumour|Rumor'),
('epilogue','The Epilogue','The speaker who kneels for the audience’s favour at the end.','EPILOGUE'),
]:add(*row)

for row in [
('servant','The servant','The Chief Justice’s servant, sent after Falstaff.','SERVANT'),
('first-drawer','The First Drawer','A drawer at the Boar’s Head.','FIRST DRAWER'),
('second-drawer','The Second Drawer','A drawer at the Boar’s Head.','SECOND DRAWER'),
('first-beadle','The First Beadle','The beadle who carries off the Hostess and Doll.','FIRST BEADLE'),
('porter','The Porter','Northumberland’s porter.','PORTER'),
('first-groom','The First Groom','A groom strewing rushes for the coronation.','FIRST GROOM'),
('second-groom','The Second Groom','A groom strewing rushes for the coronation.','SECOND GROOM'),
('messenger','The messenger','A messenger bringing word to the rebel camp.','MESSENGER'),
('sneak','Sneak','The leader of the musicians the Hostess sends for.','Sneak'),
]:add(*row,kind='unnamed-role')

for row in [
('lords','The lords','The lords of the King’s council and the rebel party.','Lords'),
('officers','The officers','The officers who attend the Chief Justice and the arrests.','Officers'),
('beadles','The beadles','The beadles who take the Hostess and Doll into custody.','Beadles'),
('drawers','The drawers','The drawers at the Boar’s Head.','Drawers'),
('grooms','The grooms','The grooms strewing rushes for the coronation.','Grooms'),
('justices','The justices','Shallow and Silence together on the Gloucestershire bench.','Justices'),
]:add(*row,kind='group')

for row in [
('hotspur','Harry Percy, called Hotspur','Northumberland’s son, killed at Shrewsbury before this play opens.','Hotspur|Coldspur|Percy','person'),
('gaunt','John of Gaunt','King Henry’s father, whom Shallow claims to have known.','John a Gaunt|John of Gaunt','person'),
('edward-iii','King Edward the Third','The King’s great-grandfather.','','person'),
('richard-ii','King Richard the Second','The king Henry the Fourth deposed, whose blood the rebels invoke.','Richard','person'),
('glendower','Owen Glendower','The Welsh leader whose death is reported to the King.','Glendower','person'),
('douglas','The Earl of Douglas','The Scottish lord who fought at Shrewsbury.','Douglas','person'),
('elder-mowbray','Thomas Mowbray, Duke of Norfolk','The old Duke, whom Falstaff served as page; the rebel Mowbray’s father.','Thomas Mowbray, Duke of Norfolk','person'),
('umfrevile','Sir John Umfrevile','A knight who turned Travers back on the road with news.','Sir John Umfrevile','person'),
('katharine','Katharine of France','The French princess the Epilogue promises for the next play.','Katharine','person'),
('oldcastle','Oldcastle','The martyr the Epilogue distinguishes from Falstaff.','Oldcastle','person'),
('jane-nightwork','Jane Nightwork','A woman of Shallow’s young days, remembered at Gloucestershire.','Jane Nightwork','person'),
('robin-nightwork','Robin Nightwork','Jane Nightwork’s son.','Robin Nightwork','person'),
('ellen','Ellen','Silence’s daughter and Shallow’s god-daughter.','Ellen','person'),
('william-shallow','William','Shallow’s cousin, now at Oxford.','','person'),
('william-cook','William cook','The cook of Shallow’s household.','William cook','person'),
('william-visor','William Visor of Woncot','A man of Shallow’s country whom Davy asks him to favour.','William Visor','person'),
('clement-perkes','Clement Perkes','A man of the hill, William Visor’s adversary.','Clement Perkes','person'),
('john-doit','John Doit','A Staffordshire man of Shallow’s young days.','John Doit','person'),
('george-barnes','George Barnes','A man of Shallow’s young days.','George Barnes','person'),
('francis-pickbone','Francis Pickbone','A man of Shallow’s young days.','Francis Pickbone','person'),
('will-squele','Will Squele','A Cotswold man of Shallow’s young days.','Will Squele','person'),
('sampson-stockfish','Sampson Stockfish','A fruiterer Shallow fought behind Gray’s Inn.','Sampson Stockfish','person'),
('scoggin','Scoggin','A man whose head Shallow claims to have broken.','Scoggin','person'),
('surecard','Master Surecard','The name Falstaff gives Silence on meeting him.','Surecard','unresolved-name'),
('puff','Puff of Barson','A man Pistol boasts of outfacing.','Puff','person'),
('smooth','Master Smooth','A silkman the Hostess says Falstaff owes money to.','Smooth','person'),
('dommelton','Master Dommelton','The draper who would not take Bardolph’s security.','Dommelton','person'),
('keech','Goodwife Keech','The butcher’s wife who came to borrow vinegar.','Keech','person'),
('tisick','Master Tisick','The deputy who warned the Hostess about her guests.','Tisick','person'),
('robin-hood','Robin Hood','The outlaw of the ballad Silence sings.','Robin Hood','literary-figure'),
('will-scarlet','Scarlet','One of Robin Hood’s men in the same ballad.','Scarlet','literary-figure'),
('little-john','Little John','Another of Robin Hood’s men in the same ballad.','','literary-figure'),
('arthur','King Arthur','The king of the romances; Falstaff calls the Page his Dagonet.','Arthur','literary-figure'),
('dagonet','Dagonet','King Arthur’s fool in the romances.','Dagonet','literary-figure'),
('cophetua','King Cophetua','The king of the ballad Pistol quotes.','Cophetua','literary-figure'),
('calipolis','Calipolis','The queen of an old play Pistol quotes at Doll.','Calipolis','literary-figure'),
('hiren','Hiren','The name Pistol gives his sword, out of an old play.','Hiren','unresolved-name'),
('amurath','Amurath','The Turkish sultan whose succession was a massacre of brothers.','Amurath','person'),
('achitophel','Achitophel','The false counsellor of the Bible, in Pistol’s abuse.','Achitophel','religious-figure'),
('cain','Cain','The first murderer, in Falstaff’s abuse of the Page.','Cain','religious-figure'),
('japhet','Japhet','Noah’s son, whom all men claim descent from.','Japhet','religious-figure'),
('job','Job','The patient sufferer of the Bible.','Job','religious-figure'),
('psalmist','The Psalmist','The writer of the psalms, cited by Shallow.','Psalmist','religious-figure'),
('jesus','Jesus','Named in the oaths of the play.','Jesu|Jesus','religious-figure'),
('saint-george','Saint George','The saint whose field in London Shallow remembers.','Saint George','religious-figure'),
('lucifer','Lucifer','The chief of the fallen angels.','Lucifer','religious-figure'),
('galen','Galen','The Greek physician, cited by Falstaff on his own diseases.','Galen','person'),
('caesar','Caesar','The Roman conqueror, in Pistol’s and Falstaff’s flourishes.','Caesar|Caesars','person'),
('agamemnon','Agamemnon','The Greek commander at Troy.','Agamemnon','literary-figure'),
('hector','Hector','The great defender of Troy.','Hector','literary-figure'),
('helen','Helen','The woman of Troy, in Pistol’s rant.','Helen','literary-figure'),
('priam','Priam','The king of Troy, who heard his city burning before the news came.','Priam','literary-figure'),
('althaea','Althaea','The mother of Greek myth whose burning brand ended her son’s life.','Althaea','mythological-figure'),
('atropos','Atropos','The fate who cuts the thread of life.','Atropos','mythological-figure'),
('alecto','Alecto','One of the Furies, in Pistol’s rant.','Alecto','mythological-figure'),
('cerberus','Cerberus','The dog of the underworld.','Cerberus','mythological-figure'),
('erebus','Erebus','The darkness of the underworld.','Erebus','mythological-figure'),
('pluto','Pluto','The god of the underworld.','Pluto','mythological-figure'),
('neptune','Neptune','The god of the sea.','Neptune','mythological-figure'),
('jove','Jove','The king of the gods.','Jove','mythological-figure'),
('saturn','Saturn','The cold planet-god, paired with Venus in the Prince’s joke.','Saturn','mythological-figure'),
('venus','Venus','The planet and goddess of love.','Venus','mythological-figure'),
('hydra','Hydra','The many-headed monster.','Hydra','mythological-figure'),
('furies','The Furies','The avenging spirits Pistol calls on.','Furies','mythological-figure'),
('vice','The Vice','The mischief-maker of the old morality plays.','Vice','literary-figure'),
]:add(*row[:4],category='reference',kind=row[4])

# Later cards: the crown passes, and the old company is turned off.
updates={
 'prince-henry':[((14,55),'King Henry the Fourth’s heir, now king in his father’s place.')],
 'falstaff':[((19,52),'The old knight of the Prince’s company, banished from the new king’s presence.')],
 'lancaster':[((11,37),'King Henry’s second son, who has taken the rebel leaders at Gaultree by a promise.')],
 'northumberland':[((6,8),'Hotspur’s father, persuaded by his wife and Hotspur’s widow to leave the rebellion for Scotland.')],
}
for e in entities:e['snapshots']=[dict(after=list(at),body=body) for at,body in updates.get(e['id'],[])]
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='henry-iv-part-2',contentVersion='2026-09-10.1',coverage='All nineteen scenes in both original-en and modern-en, with the Induction and Epilogue: named cast, speaking and stage roles, the Gloucestershire and Eastcheap acquaintance named only in talk, and the classical, biblical and balladic figures of the play’s allusions.',entities=entities),ensure_ascii=False,indent=2)+'\n')
