"""Manually authored recognition cards for both full English texts of the Iliad.

Butler's original uses the Roman names for the gods and for Odysseus (Jove,
Minerva, Juno, Mars, Neptune, Vulcan, Venus, Mercury, Diana, Ulysses); the
modern edition restores the Greek. Both forms are carried as aliases on one
entity.

Scope: named people, gods, personified powers, named horses and named peoples.
Places, rivers as geography, mountains, islands, ships and the adjectival forms
of place names are not cast. Where a river is addressed or fights as a god, it
is included as a person.
"""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

# ------------------------------------------------------------------ principals
for row in [
('achilles','Achilles','Son of Peleus and Thetis, the best fighter among the Greeks; the poem opens with his quarrel with Agamemnon.','Achilles','central'),
('hector','Hector','Priam’s eldest son and the commander of Troy’s defence.','Hector','central'),
('agamemnon','Agamemnon','King of Mycenae and commander-in-chief of the Greek army, Menelaus’s brother.','Agamemnon','major'),
('patroclus','Patroclus','Son of Menoetius and Achilles’ closest companion, raised in Peleus’s house.','Patroclus','major'),
('priam','Priam','The old king of Troy, father of Hector and of fifty sons.','Priam','major'),
('menelaus','Menelaus','King of Sparta and Agamemnon’s brother; the war is fought over his wife.','Menelaus','major'),
('helen','Helen','Menelaus’s wife, now living in Troy with Paris; the woman the war is fought over.','Helen','major'),
('paris','Paris','Priam’s son, who carried Helen away from Sparta. The poem calls him Alexandrus as often as Paris.','Alexandrus|Paris|Alexandria','major'),
('odysseus','Odysseus','King of Ithaca, the shrewdest of the Greek captains. Butler’s original calls him Ulysses.','Ulysses|Odysseus','major'),
('diomed','Diomed','Son of Tydeus and, after Achilles, the most dangerous fighter on the Greek side. The modern edition also spells him Diomedes.','Diomed|Diomedes','major'),
('nestor','Nestor','The old king of Pylos, knight of Gerene, who has outlived two generations and advises everyone.','','major'),
('ajax','Ajax','Son of Telamon, the biggest man in the Greek army and its most reliable defender.','','major'),
('ajax-oileus','Ajax son of Oileus','The Locrian captain, a small man and the fastest runner in the army; called Ajax the less to distinguish him from Telamon’s son.','','major'),
('ajaxes','The two Ajaxes','Ajax son of Telamon and Ajax son of Oileus, who fight side by side and are often named as a pair.','','supporting','group'),
('aeneas','Aeneas','Son of Anchises and Aphrodite, leader of the Dardanians and the best Trojan fighter after Hector.','Aeneas','major'),
('sarpedon','Sarpedon','Son of Zeus and captain of the Lycians, the strongest of Troy’s allies.','Sarpedon','major'),
('glaucus','Glaucus','Son of Hippolochus and Sarpedon’s second in command among the Lycians.','Glaucus','supporting'),
('idomeneus','Idomeneus','King of Crete, son of Deucalion, and one of the older Greek captains.','Idomeneus','major'),
('meriones','Meriones','Idomeneus’s second in command among the Cretans, son of Molus.','Meriones','major'),
('antilochus','Antilochus','Nestor’s son, the fastest runner among the younger Greek captains.','Antilochus','major'),
('teucer','Teucer','Ajax’s half-brother by the same father, and the best archer in the Greek army.','Teucer','major'),
('polydamas','Polydamas','Son of Panthous, born the same night as Hector; the one Trojan whose counsel Hector ought to take.','Polydamas','supporting'),
('briseis','Briseis','The woman awarded to Achilles from the sack of Lyrnessus, whom Agamemnon takes from him.','Briseis','major'),
('chryseis','Chryseis','Chryses’s daughter, taken as Agamemnon’s prize; her father’s prayer brings the plague.','Chryseis','supporting'),
('chryses','Chryses','Priest of Apollo, father of Chryseis, whose rejected ransom opens the poem.','Chryses','supporting'),
('calchas','Calchas','Son of Thestor and the army’s chief augur, who guided the fleet to Troy.','Calchas','supporting'),
('andromache','Andromache','Hector’s wife, daughter of Eetion of Thebe.','Andromache','major'),
('astyanax','Astyanax','Hector and Andromache’s baby son. His father named him Scamandrius; the people call him Astyanax.','Astyanax','supporting'),
('hecuba','Hecuba','Priam’s wife and queen of Troy, mother of Hector and Paris.','Hecuba','supporting'),
('automedon','Automedon','Son of Diores and Achilles’ charioteer, who drives for Patroclus in his place.','Automedon','supporting'),
('phoenix','Phoenix','The old man who brought Achilles up in Peleus’s house and is sent as one of the three envoys to him.','','supporting'),
('thersites','Thersites','The ugliest and most abusive man in the Greek army, beaten by Odysseus for railing at Agamemnon.','Thersites','supporting'),
('dolon','Dolon','Son of the herald Eumedes, a rich Trojan who volunteers to spy on the Greek camp by night.','Dolon','supporting'),
('rhesus','Rhesus','The newly arrived Thracian king whose white horses Odysseus and Diomed carry off.','Rhesus','supporting'),
('machaon','Machaon','A son of Aesculapius and one of the army’s two surgeons.','Machaon','supporting'),
('podalirius','Podalirius','A son of Aesculapius and, with his brother Machaon, a surgeon to the army.','Podalirius','reference'),
('thetis','Thetis','A sea goddess, Achilles’ mother, married to the mortal Peleus.','Thetis','major','deity'),
('peleus','Peleus','Achilles’ father, an old king among the Myrmidons.','Peleus','supporting'),
('menoetius','Menoetius','Patroclus’s father, son of Actor, who put his son in Peleus’s care.','Menoetius','reference'),
('atreus','Atreus','Father of Agamemnon and Menelaus.','Atreus','reference'),
('tydeus','Tydeus','Diomed’s father, one of the Seven against Thebes, and a byword for reckless courage.','Tydeus','reference'),
('telamon','Telamon','Father of Ajax and Teucer.','Telamon','reference'),
('oileus','Oileus','Father of Ajax the less and of the bastard Medon.','','reference'),
('laertes','Laertes','Odysseus’s father.','Laertes','reference'),
('anchises','Anchises','Aeneas’s father, whom Aphrodite loved on the slopes of Ida.','','reference'),
('hippolochus','Hippolochus','Glaucus’s father, son of Bellerophon.','','reference'),
('antenor','Antenor','An elder of Troy and its wisest counsellor, who argues for giving Helen back.','Antenor','supporting'),
('theano','Theano','Daughter of Cisseus, wife of Antenor and priestess of Athena in Troy.','Theano','supporting'),
('deiphobus','Deiphobus','A son of Priam and one of Troy’s leading fighters.','Deiphobus','supporting'),
('helenus','Helenus','A son of Priam and the best augur in Troy.','','supporting'),
('cebriones','Cebriones','A bastard son of Priam who drives Hector’s chariot.','Cebriones','supporting'),
('polydorus','Polydorus','Priam’s youngest and dearest son, whom his father forbade to fight.','Polydorus','supporting'),
('lycaon','Lycaon','A son of Priam by Laothoe, sold into slavery by Achilles and taken again at the river.','','supporting'),
('pandarus','Pandarus','Son of Lycaon of Zelea, the archer who breaks the truce by shooting Menelaus.','Pandarus','supporting'),
('lycaon-zelea','Lycaon','Pandarus’s father, of Zelea under Ida.','','reference'),
('asius','Asius','Son of Hyrtacus, a Trojan ally who refuses to leave his chariot at the wall.','Asius','supporting'),
('idaeus','Idaeus','Priam’s herald, who drives for him and carries his messages.','','supporting'),
('talthybius','Talthybius','One of Agamemnon’s two heralds.','Talthybius','supporting'),
('eurybates','Eurybates','A herald of the Greek army; the man of Ithaca who attends Odysseus.','Eurybates','supporting'),
('agenor','Agenor','A son of Antenor and one of the steadiest Trojan fighters.','Agenor','supporting'),
('asteropaeus','Asteropaeus','Son of Pelegon and grandson of the river Axius, captain of the Paeonians and ambidextrous with the spear.','Asteropaeus','supporting'),
('euphorbus','Euphorbus','Son of Panthous, the Trojan who wounds Patroclus first.','Euphorbus','supporting'),
('eurypylus','Eurypylus','Son of Euaemon, a Greek captain who is wounded in the thigh and nursed by Patroclus.','','supporting'),
('menestheus','Menestheus','Son of Peteos and captain of the Athenians.','Menestheus','supporting'),
('meges','Meges','Son of Phyleus and captain of the men of Dulichium.','Meges','supporting'),
('thrasymedes','Thrasymedes','A son of Nestor and a captain of the night watch.','Thrasymedes','supporting'),
('sthenelus','Sthenelus','Son of Capaneus and Diomed’s charioteer and constant companion.','','supporting'),
('protesilaus','Protesilaus','The first Greek killed at Troy, leaping ashore ahead of the rest; his men now follow Podarces.','Protesilaus','supporting'),
('podarces','Podarces','Son of Iphiclus, who leads Protesilaus’s men after his brother’s death.','Podarces','supporting'),
('philoctetes','Philoctetes','The skilful archer left behind sick on Lemnos, whose men came without him.','Philoctetes','reference'),
]:add(*row)

# ------------------------------------------------------------------------ gods
for row in [
('zeus','Zeus','King of the gods, who holds the balance of the war. Butler’s original calls him Jove throughout, with a single slip into Zeus at 16:51.','Jove|Zeus|Jupiter','major','deity'),
('hera','Hera','Zeus’s wife and sister, implacably against Troy. Butler’s original calls her Juno.','Juno|Hera','major','deity'),
('athena','Athena','Zeus’s daughter, goddess of war and craft, and the Greeks’ fiercest partisan. Butler’s original calls her Minerva.','Minerva|Athena|Alalcomene','major','deity'),
('apollo','Apollo','God of archery and plague, and Troy’s chief defender among the gods; also called Phoebus.','Apollo|Phoebus','major','deity'),
('poseidon','Poseidon','God of the sea and the earthquake, who works for the Greeks against his brother’s orders. Butler’s original calls him Neptune.','Neptune|Poseidon','major','deity'),
('ares','Ares','God of war, who fights on the Trojan side until Diomed wounds him. Butler’s original calls him Mars.','Mars|Ares','major','deity'),
('aphrodite','Aphrodite','Goddess of love, Aeneas’s mother, and Paris’s protector. Butler’s original calls her Venus.','Venus|Aphrodite|Cyprian','supporting','deity'),
('hephaestus','Hephaestus','The lame smith of the gods, who makes Achilles’ new armour. Butler’s original calls him Vulcan.','Vulcan|Hephaestus','supporting','deity'),
('hermes','Hermes','The messenger god, who guides Priam through the Greek camp. Butler’s original calls him Mercury.','Mercury|Hermes','supporting','deity'),
('artemis','Artemis','Goddess of the hunt and Apollo’s sister. Butler’s original calls her Diana.','Diana|Artemis','supporting','deity'),
('iris','Iris','The gods’ messenger, who carries their orders down to the plain.','Iris','supporting','deity'),
('leto','Leto','Mother of Apollo and Artemis; the original also names her Latona.','Leto|Latona','reference','deity'),
('hades','Hades','God of the world below; the name also stands for his house.','Hades','supporting','deity'),
('persephone','Persephone','Queen of the dead. Butler’s original calls her Proserpine.','Proserpine|Persephone','reference','deity'),
('demeter','Demeter','Goddess of the harvest. Butler’s original calls her Ceres.','Ceres|Demeter','reference','deity'),
('cronus','Cronus','Zeus’s father, imprisoned below with the Titans. Butler’s original calls him Saturn.','Saturn|Cronus|Cronos','reference','deity'),
('rhea','Rhea','Mother of Zeus, Poseidon and Hades. The original spells her Rhaea.','Rhea|Rhaea','reference','deity'),
('dione','Dione','Aphrodite’s mother, who comforts her on Olympus after Diomed wounds her.','Dione','reference','deity'),
('hebe','Hebe','Daughter of Zeus and Hera, who pours the nectar and harnesses Hera’s chariot.','Hebe','reference','deity'),
('themis','Themis','A goddess of Olympus who greets Hera on her return and summons the gods to council.','Themis','reference','deity'),
('charis','Charis','Hephaestus’s wife, who receives Thetis in the smith’s house.','Charis','reference','deity'),
('dawn','Dawn','The goddess of daybreak, who rises from beside Tithonus.','Dawn','supporting','deity'),
('oceanus','Oceanus','The stream encircling the earth, spoken of as the father of the gods.','Oceanus','reference','deity'),
('tethys','Tethys','Oceanus’s wife, named with him as the source of the gods.','Tethys','reference','deity'),
('sleep','Sleep','Death’s own brother, whom Hera bribes to close Zeus’s eyes.','','supporting','personification'),
('scamander','Scamander','The river of the Trojan plain, who rises against Achilles; men call him Scamander and the gods Xanthus.','Scamander','major','deity'),
('eileithyia','Ilithuia','Goddess of the pains of childbirth. The original also uses the plural Ilithuiae.','Ilithuia|Eileithyia|Ilithuiae|Eileithyiae|Eilithuiae','reference','deity'),
('paeon','Paeeon','The healer of the gods, who cures Ares and Hades of their wounds.','Paeeon','reference','deity'),
('dionysus','Bacchus','God of wine, driven into the sea by Lycurgus when he was young.','Bacchus|Dionysus','reference','deity'),
('erinyes','The Erinyes','The avenging spirits a wronged parent calls down; the original also uses the singular Erinys.','Erinyes|Erinys','reference','group'),
('muses','The Muses','The nine goddesses of song, invoked for the catalogue of ships; the poem also addresses one Muse.','Muses|Muse','supporting','group'),
('nereus','Nereus','The old sea god, Thetis’s father.','Nereus','reference','deity'),
('boreas','Boreas','The north wind, spoken of as a god.','Boreas','reference','deity'),
('zephyrus','Zephyrus','The west wind, spoken of as a god and as the sire of Achilles’ horses.','Zephyrus','reference','deity'),
('podarge','Podarge','The harpy who bore Achilles’ immortal horses to the west wind.','Podarge','reference','deity'),
('enyo','Enyo','A goddess of battle, named beside Athena as a waster of cities.','Enyo','reference','deity'),
('stentor','Stentor','The brazen-voiced herald whose shout Hera borrows.','Stentor','reference'),
('aegaeon','Aegaeon','The hundred-handed monster whom the gods call Briareus and men Aegaeon.','Aegaeon|Briareus','reference','mythological-figure'),
('titans','The Titans','The elder gods imprisoned with Cronus below the earth.','Titans','reference','group'),
('iapetus','Iapetus','A Titan imprisoned with Cronus in the depths below.','Iapetus','reference','deity'),
('gorgon','The Gorgon','The monstrous head set on Athena’s aegis and on Agamemnon’s shield; also called Gorgo.','Gorgon|Gorgo','reference','mythical-being'),
('styx','Styx','The river of the world below, by which the gods swear.','Styx','reference','deity'),
('orcus','Orcus','The dread power of the world below, of whom the Titaresius is called a branch.','Orcus','reference','deity'),
('achelous','Achelous','A great river named as second only to Zeus among waters.','Achelous','reference','deity'),
('graces','The Graces','The goddesses of grace; Hera promises one of them, Pasithea, to Sleep.','Graces','reference','group'),
('pasithea','Pasithea','The youngest of the Graces, whom Hera promises to Sleep in marriage.','Pasithea','reference','deity'),
('olympians','The Olympians','The gods of Olympus, taken together.','Olympians','reference','group'),
('sea-nymphs','The sea-nymphs','Thetis’s sisters, the daughters of Nereus, who gather round her in the sea.','','supporting','group'),
('strife','Strife','The goddess of discord, who is sent to the ships and grows until her head touches heaven; the original also names Riot and Rumour beside her.','Strife|Riot|Rumour|Rumor','supporting','personification'),
]:add(*row)
for n in ['Glauce','Thalia','Cymodoce','Nesaia','Speo','Thoe','Halie','Cymothoe','Actaea','Limnorea','Melite','Iaera','Amphithoe','Agave','Doto','Proto','Pherusa','Dynamene','Dexamene','Amphinome','Callianeira','Doris','Panope','Galatea','Nemertes','Apseudes','Callianassa','Clymene','Ianeira','Ianassa','Maera','Oreithuia','Amatheia']:
 # Clymene is also the name of one of Helen's handmaids; that one is bound by position.
 add(n.lower()+'-nereid',n,'One of the sea-nymphs, daughters of Nereus, who gather round Thetis when she mourns.','' if n=='Clymene' else n,'reference','deity')

# ------------------------------------------------- Greek captains and followers
for row in [
('peneleos','Peneleos','A captain of the Boeotians.','Peneleos'),
('leitus','Leitus','A captain of the Boeotians.','Leitus'),
('arcesilaus','Arcesilaus','A captain of the Boeotians.','Arcesilaus'),
('prothoenor','Prothoenor','A captain of the Boeotians, son of Areilycus.','Prothoenor'),
('clonius','Clonius','A captain of the Boeotians.','Clonius'),
('areilycus','Areilycus','Father of the Boeotian captain Prothoenor.','Areilycus','reference'),
('ascalaphus','Ascalaphus','A son of Ares who leads the men of Aspledon and Orchomenus.','Ascalaphus'),
('ialmenus','Ialmenus','A son of Ares who leads the men of Aspledon and Orchomenus with his brother.','Ialmenus'),
('astyoche','Astyoche','The maiden who bore Ascalaphus and Ialmenus to Ares in Actor’s house.','Astyoche','reference'),
('actor-azeus','Actor','Son of Azeus, in whose house Astyoche bore the sons of Ares.','','reference'),
('azeus','Azeus','Father of the Actor in whose house Ascalaphus and Ialmenus were born.','Azeus','reference'),
('schedius','Schedius','A captain of the Phoceans, son of Iphitus.','',''),
('schedius-perimedes','Schedius','A leader of the Phoceans, son of Perimedes, killed by Hector.','',''),
('epistrophus-phocean','Epistrophus','A captain of the Phoceans, son of Iphitus.','',''),
('iphitus-naubolus','Iphitus','Father of the Phocean captains Schedius and Epistrophus.','','reference'),
('iphitus-archeptolemus','Iphitus','Father of Archeptolemus, Hector’s second charioteer.','',''),
('naubolus','Naubolus','Grandfather of the Phocean captains.','Naubolus','reference'),
('perimedes','Perimedes','Father of the Phocean leader Schedius killed by Hector.','Perimedes','reference'),
('elephenor','Elephenor','Son of Chalcodon and chief of the Abantes of Euboea.','Elephenor'),
('chalcodon','Chalcodon','Father of Elephenor.','Chalcodon','reference'),
('peteos','Peteos','Father of Menestheus of Athens.','Peteos','reference'),
('agapenor','Agapenor','Son of Ancaeus and commander of the Arcadians.','Agapenor'),
('ancaeus','Ancaeus','Father of the Arcadian commander Agapenor.','Ancaeus','reference'),
('amphimachus','Amphimachus','Son of Cteatus and one of the four Epean captains; Poseidon’s grandson.','',''),
('amphimachus-carian','Amphimachus','A son of Nomion who leads the Carians and comes to war wearing gold.','',''),
('thalpius','Thalpius','Son of Eurytus and one of the four Epean captains.','Thalpius'),
('cteatus','Cteatus','One of the Moliones, father of the Epean captain Amphimachus.','Cteatus','reference'),
('eurytus-molione','Eurytus','One of the Moliones, father of the Epean captain Thalpius.','',''),
('moliones','The two Moliones','The twin sons of Actor whom Nestor could not beat in his youth, saved by Poseidon.','Moliones','reference','group'),
('actor-moliones','Actor','Father of the Moliones; the Epean captains are called men of his race.','',''),
('diores','Diores','Son of Amarynceus and one of the four Epean captains.','Diores'),
('amarynceus','Amarynceus','Father of the Epean captain Diores.','Amarynceus','reference'),
('polyxenus','Polyxenus','Son of Agasthenes and one of the four Epean captains.','Polyxenus'),
('agasthenes','Agasthenes','Father of the Epean captain Polyxenus, son of Augeas.','Agasthenes','reference'),
('augeas','Augeas','King of Elis in the old days, grandfather of Polyxenus.','Augeas','reference'),
('phyleus','Phyleus','Meges’s father, who quarrelled with his own father and settled in Dulichium.','Phyleus','reference'),
('tlepolemus','Tlepolemus','Son of Heracles, who brought nine ships from Rhodes and is killed by Sarpedon.','',''),
('tlepolemus-myrmidon','Tlepolemus','A Trojan killed by Patroclus in his charge on the city.','',''),
('astyochea','Astyochea','The woman Heracles carried off from Ephyra, mother of Tlepolemus.','Astyochea','reference'),
('licymnius','Licymnius','Heracles’ uncle, killed by the young Tlepolemus.','Licymnius','reference'),
('nireus','Nireus','The handsomest man who came to Troy after Achilles, though he brought few men.','Nireus'),
('pheidippus','Pheidippus','A son of Thessalus who leads the men of Cos and Nisyrus.','Pheidippus'),
('antiphus-thessalus','Antiphus','A son of Thessalus who leads the men of Cos and Nisyrus with his brother.','',''),
('eumelus','Eumelus','Son of Admetus and Alcestis, who drives the finest horses in the Greek army.','Eumelus'),
('admetus','Admetus','Eumelus’s father.','Admetus','reference'),
('alcestis','Alcestis','Eumelus’s mother, loveliest of the daughters of Pelias.','Alcestis','reference'),
('pelias','Pelias','Alcestis’s father.','Pelias','reference'),
('medon','Medon','The bastard son of Oileus by Rhene, Ajax the less’s half-brother, living in exile at Phylace.','',''),
('medon-trojan','Medon','A Trojan ally whom Hector cheers on in the fight for Patroclus’s body.','',''),
('rhene','Rhene','Oileus’s concubine, mother of Medon.','Rhene','reference'),
('eriopis','Eriopis','Oileus’s wife, whose kinsman Medon killed.','Eriopis','reference'),
('iphiclus','Iphiclus','Podarces’s father, rich in sheep.','Iphiclus','reference'),
('phylacus','Phylacus','Grandfather of Podarces and Protesilaus.','','reference'),
('phylacus-trojan','Phylacus','A Trojan killed by Leitus as he fled.','',''),
('prothous','Prothous','Son of Tenthredon and commander of the Magnetes.','Prothous'),
('tenthredon','Tenthredon','Father of the Magnete commander Prothous.','Tenthredon','reference'),
('guneus','Guneus','The captain who brought two and twenty ships from Cyphus.','Guneus'),
('polypoetes','Polypoetes','Son of Pirithous and one of the two Lapith captains who hold the gate.','Polypoetes'),
('leonteus','Leonteus','Son of Coronus and the other Lapith captain at the gate.','Leonteus'),
('coronus','Coronus','Leonteus’s father, son of Caeneus.','Coronus','reference'),
('pirithous','Pirithous','Polypoetes’s father, a son of Zeus by Ixion’s wife and one of the great men of the last age.','Pirithous|Peirithous','reference'),
('lycomedes','Lycomedes','Son of Creion, a Greek captain of the night watch.','Lycomedes'),
('creion','Creion','Father of Lycomedes; the poem also spells the name Creontes.','Creion|Creontes','reference'),
('aphareus','Aphareus','A Greek captain of the night watch, son of Caletor.','Aphareus'),
('caletor-aphareus','Caletor','Father of the Greek captain Aphareus.','',''),
('deipyrus','Deipyrus','A Greek captain of the night watch, killed by Helenus.','Deipyrus'),
('stichius','Stichius','A captain of the Athenians.','Stichius'),
('pheidas','Pheidas','A captain of the Athenians.','Pheidas'),
('bias-athenian','Bias','A captain of the Athenians.','',''),
('bias-pylian','Bias','A Pylian chief marshalling Nestor’s men.','',''),
('bias-trojan','Bias','Father of the Trojans Laogonus and Dardanus.','',''),
('amphion-epean','Amphion','A commander of the Epeans at the ships.','Amphion',''),
('dracius','Dracius','A commander of the Epeans at the ships.','Dracius'),
('pelagon','Pelagon','A Pylian chief marshalling Nestor’s men.','Pelagon'),
('haemon-pylian','Haemon','A Pylian chief marshalling Nestor’s men.','',''),
('haemon-maeon','Haemon','Father of the Theban captain Maeon.','',''),
('haemon-laerces','Haemon','Father of Laerces and grandfather of Alcimedon.','',''),
('alcimedon','Alcimedon','A Myrmidon captain, son of Laerces, who takes the reins from Automedon. His father’s name is spelled Laerceus at 16:10 and Laerces at 17:29.','Alcimedon'),
('laerces','Laerces','Alcimedon’s father; the poem spells the name Laerceus once and Laerces once.','Laerces|Laerceus','reference'),
('alcimus','Alcimus','A Myrmidon who harnesses Achilles’ chariot with Automedon.','Alcimus'),
('menesthius','Menesthius','Captain of the first Myrmidon company, son of the river Spercheius and Polydora.','',''),
('menesthius-arne','Menesthius','A Trojan of Arne, son of Areithous the Mace-man, killed by Paris.','',''),
('polydora','Polydora','Peleus’s daughter, mother of the Myrmidon Menesthius by the river Spercheius.','Polydora','reference'),
('spercheius','Spercheius','A river that streams from heaven, father of the Myrmidon Menesthius.','Spercheius','reference','deity'),
('borus','Borus','Son of Perieres, who married Polydora and was called Menesthius’s father.','',''),
('borus-meonian','Borus','A Meonian, father of Phaesus.','',''),
('perieres','Perieres','Father of Borus.','Perieres','reference'),
('eudorus','Eudorus','Captain of the second Myrmidon company, son of Hermes and Polymele.','Eudorus'),
('polymele','Polymele','Phylas’s daughter, mother of Eudorus by Hermes.','Polymele','reference'),
('phylas','Phylas','Polymele’s father, a graceful dancer.','Phylas','reference'),
('echecles','Echecles','Son of Actor, who married Polymele after Eudorus was born.','Echecles','reference'),
('actor-echecles','Actor','Father of Echecles, who married Polymele.','',''),
('pisander-myrmidon','Pisander','Captain of the third Myrmidon company, son of Maemalus and the best spearman among them after Patroclus.','',''),
('maemalus','Maemalus','Father of the Myrmidon captain Pisander.','Maemalus','reference'),
('epeigeus','Epeigeus','A Myrmidon, son of Agacles, once king in Budeum, killed by Hector.','Epeigeus'),
('agacles','Agacles','Father of the Myrmidon Epeigeus.','Agacles','reference'),
('hecamede','Hecamede','Daughter of Arsinous, awarded to Nestor from Tenedos, who mixes the drink in his tent.','Hecamede'),
('arsinous','Arsinous','Hecamede’s father, of Tenedos.','Arsinous','reference'),
('diomede','Diomede','Phorbas’s daughter, carried off from Lesbos and given to Achilles.','Diomede','reference'),
('phorbas-lesbos','Phorbas','Father of Diomede of Lesbos.','',''),
('phorbas-trojan','Phorbas','A rich Trojan flock-master favoured by Hermes, father of Ilioneus.','',''),
('iphis','Iphis','The woman Achilles gave to Patroclus when he took Scyros.','Iphis','reference'),
('enyeus','Enyeus','King of Scyros when Achilles took it.','Enyeus','reference'),
]:add(*row)

# --------------------------------------------------- Trojans and their allies
for row in [
('panthous','Panthous','A Trojan elder, father of Polydamas, Euphorbus and Hyperenor.','Panthous','reference'),
('lampus-elder','Lampus','A Trojan elder, son of Laomedon and father of Dolops.','',''),
('clytius-elder','Clytius','A Trojan elder, son of Laomedon and father of Caletor.','',''),
('hiketaon','Hiketaon','A Trojan elder of the race of Ares, father of Melanippus. The modern edition spells him Hicetaon.','Hiketaon|Hicetaon','reference'),
('thymoetes','Thymoetes','A Trojan elder seated with Priam at the Scaean gates.','Thymoetes','reference'),
('ucalegon','Ucalegon','A Trojan elder and one of the two sages seated by the Scaean gates.','Ucalegon','reference'),
('laomedon','Laomedon','Priam’s father, who cheated Poseidon and Apollo of their wages.','Laomedon','reference'),
('dardanus','Dardanus','Zeus’s son and the founder of the Trojan line.','','reference'),
('dardanus-bias','Dardanus','A Trojan, son of Bias, killed by Achilles.','',''),
('erichthonius','Erichthonius','Dardanus’s son, the wealthiest man of his time, whose mares the north wind covered.','Erichthonius','reference'),
('tros','Tros','Erichthonius’s son and king of the Trojans, who gave his name to the people.','',''),
('tros-alastor','Tros','A young Trojan, son of Alastor, who clasps Achilles’ knees in vain.','',''),
('ilus','Ilus','Tros’s son, whose tomb stands in the middle of the plain.','Ilus','reference'),
('assaracus','Assaracus','Tros’s son, Capys’s father and Aeneas’s great-grandfather.','Assaracus','reference'),
('ganymede','Ganymede','Tros’s son, the comeliest of mortals, carried up to be Zeus’s cup-bearer.','Ganymede','reference'),
('capys','Capys','Assaracus’s son and Anchises’ father.','Capys','reference'),
('tithonus','Tithonus','Laomedon’s son and Dawn’s consort.','Tithonus','reference'),
('laothoe','Laothoe','Daughter of Altes, one of Priam’s wives and mother of Lycaon and Polydorus.','Laothoe','reference'),
('altes','Altes','King of the Lelegae at Pedasus and Laothoe’s father.','Altes','reference'),
('castianeira','Castianeira','One of Priam’s wives, mother of Gorgythion.','Castianeira','reference'),
('gorgythion','Gorgythion','A son of Priam killed by an arrow meant for Hector.','Gorgythion'),
('laodice','Laodice','Priam’s fairest daughter, married to Helicaon son of Antenor.','',''),
('laodice-agamemnon','Laodice','One of Agamemnon’s three daughters, offered to Achilles.','',''),
('chrysothemis','Chrysothemis','One of Agamemnon’s three daughters, offered to Achilles.','Chrysothemis','reference'),
('iphianassa','Iphianassa','One of Agamemnon’s three daughters, offered to Achilles.','Iphianassa','reference'),
('orestes','Orestes','Agamemnon’s son, being brought up at home in all abundance.','',''),
('orestes-charioteer','Orestes','A Greek charioteer killed by Ares and Hector.','',''),
('orestes-trojan','Orestes','A Trojan captain in Asius’s company, killed by Leonteus.','',''),
('cassandra','Cassandra','Priam’s fairest daughter, promised to Othryoneus for driving the Greeks away.','Cassandra','reference'),
('helicaon','Helicaon','A son of Antenor, married to Priam’s daughter Laodice.','Helicaon','reference'),
('cisseus','Cisseus','Theano’s father.','Cisseus','reference'),
('archelochus','Archelochus','A son of Antenor who leads a Trojan company with his brother Acamas.','Archelochus'),
('acamas','Acamas','A son of Antenor who leads a Trojan company with Archelochus.','',''),
('acamas-thracian','Acamas','Son of Eussorus and chief of the Thracians, the best man among them.','',''),
('eussorus','Eussorus','Father of the Thracian chief Acamas.','Eussorus','reference'),
('polybus-antenor','Polybus','A son of Antenor, in Hector’s company at the wall.','Polybus',''),
('iphidamas','Iphidamas','A son of Antenor brought up in Thrace by his grandfather Cisses, killed by Agamemnon.','Iphidamas'),
('cisses','Cisses','Iphidamas’s grandfather, who brought him up in Thrace.','Cisses','reference'),
('coon','Coon','Antenor’s eldest son, who wounds Agamemnon avenging his brother.','Coon'),
('pedaeus','Pedaeus','A bastard son of Antenor brought up by Theano as her own, killed by Meges.','Pedaeus'),
('laodocus','Laodocus','A son of Antenor whose shape Athena takes to find Pandarus.','',''),
('laodocus-greek','Laodocus','A comrade of Antilochus, who takes his armour when he runs from the fight.','',''),
('polites','Polites','A son of Priam, fleet of foot, who watches from Aesyetes’ tomb.','Polites'),
('aesyetes','Aesyetes','A Trojan of old whose tomb serves as the Trojans’ watch-post.','Aesyetes','reference'),
('antiphus-priam','Antiphus','A son of Priam born in wedlock, killed by Agamemnon beside his bastard brother.','',''),
('isus','Isus','A bastard son of Priam, killed by Agamemnon beside his brother Antiphus.','Isus'),
('agathon','Agathon','A son of Priam, upbraided by his father as he prepares for the ransom.','Agathon','reference'),
('pammon','Pammon','A son of Priam, upbraided by his father as he prepares for the ransom.','Pammon','reference'),
('antiphonus','Antiphonus','A son of Priam, upbraided by his father as he prepares for the ransom.','Antiphonus','reference'),
('hippothous-priam','Hippothous','A son of Priam, upbraided by his father as he prepares for the ransom.','',''),
('dius','Dius','A son of Priam, upbraided by his father as he prepares for the ransom.','Dius','reference'),
('troilus','Troilus','A son of Priam, a dauntless charioteer, already dead when the poem opens.','Troilus','reference'),
('nestor-trojan','Nestor','A son of Priam, named among the bravest his father has lost.','',''),
('doryclus','Doryclus','A bastard son of Priam, killed by Ajax.','Doryclus'),
('echemmon','Echemmon','A son of Priam killed by Diomed in his brother’s chariot.','Echemmon'),
('chromius-priam','Chromius','A son of Priam killed by Diomed in his brother’s chariot.','',''),
('hippothous','Hippothous','Son of the Pelasgian Lethus, who leads the Pelasgian spearsmen.','',''),
('pylaeus','Pylaeus','Son of the Pelasgian Lethus, who leads the Pelasgian spearsmen with his brother.','Pylaeus'),
('lethus','Lethus','The Pelasgian father of Hippothous and Pylaeus, son of Teutamus.','Lethus','reference'),
('teutamus','Teutamus','Grandfather of the Pelasgian captains.','Teutamus','reference'),
('peirous','Peirous','Son of Imbrasus and captain of the Thracians, who kills Diores and is killed by Thoas.','Peirous'),
('imbrasus','Imbrasus','Father of the Thracian captain Peirous.','Imbrasus','reference'),
('euphemus','Euphemus','Son of Troezenus and captain of the Ciconian spearsmen.','Euphemus'),
('troezenus','Troezenus','Father of the Ciconian captain Euphemus.','Troezenus','reference'),
('pyraechmes','Pyraechmes','Leader of the Paeonian archers from Amydon.','Pyraechmes'),
('pelegon','Pelegon','Asteropaeus’s father, son of the river Axius and Periboea.','Pelegon','reference'),
('axius','Axius','A broad river spoken of as Pelegon’s father.','Axius','reference','deity'),
('periboea','Periboea','Acessamenus’s eldest daughter, mother of Pelegon by the river Axius.','Periboea','reference'),
('odius','Odius','A captain of the Halizoni from Alybe.','Odius'),
('epistrophus-halizoni','Epistrophus','A captain of the Halizoni from Alybe.','',''),
('epistrophus-lyrnessus','Epistrophus','A son of king Evenor of Lyrnessus, overthrown by Achilles.','',''),
('mynes','Mynes','A son of king Evenor of Lyrnessus, overthrown by Achilles.','Mynes','reference'),
('evenor','Evenor','King of Lyrnessus, father of Mynes and Epistrophus.','Evenor','reference'),
('chromis','Chromis','A leader of the Mysians.','Chromis'),
('ennomus','Ennomus','A Mysian augur whose skill did not save him from Achilles in the river.','Ennomus'),
('phorcys','Phorcys','A leader of the Phrygians from Ascania, son of Phaenops, killed by Ajax.','Phorcys'),
('ascanius','Ascanius','A leader of the Phrygians from Ascania.','Ascanius'),
('mesthles','Mesthles','A commander of the Meonians, son of Talaemenes.','Mesthles'),
('antiphus-meonian','Antiphus','A commander of the Meonians, son of Talaemenes.','',''),
('talaemenes','Talaemenes','Father of the Meonian commanders.','Talaemenes','reference'),
('nastes','Nastes','A leader of the Carians, son of Nomion.','Nastes'),
('nomion','Nomion','Father of the Carian leaders Nastes and Amphimachus.','Nomion','reference'),
('pylaemenes','Pylaemenes','Commander of the Paphlagonians; the original spells the name Pylaemanes at his first appearance.','Pylaemenes|Pylaemanes'),
('harpalion','Harpalion','Son of Pylaemenes, who came to Troy with his father and did not go home again.','Harpalion'),
('adrestus-trojan','Adrestus','A leader of the men of Adresteia and Apaesus, son of Merops.','',''),
('amphius','Amphius','A leader of the men of Adresteia and Apaesus, son of Merops, whose breastplate was of linen.',''),
('merops','Merops','A diviner of Percote who forbade his sons to go to the war.','Merops','reference'),
('adrestus-captive','Adrestus','A Trojan thrown from his chariot, who begs Menelaus for his life.','',''),
('adrestus-patroclus','Adrestus','A Trojan killed by Patroclus.','',''),
('hyrtacus','Hyrtacus','Father of Asius.','Hyrtacus','reference'),
('adamas','Adamas','Son of Asius, one of the Trojan captains at the wall.','Adamas'),
('iamenus','Iamenus','A Trojan captain in Asius’s company.','Iamenus'),
('oenomaus','Oenomaus','A Trojan captain in Asius’s company.','',''),
('oenomaus-greek','Oenomaus','A Greek killed by Ares and Hector.','',''),
('thoon-asius','Thoon','A Trojan captain in Asius’s company.','',''),
('thoon-phaenops','Thoon','A son of Phaenops killed by Diomed.','',''),
('thoon-ulysses','Thoon','A Trojan killed by Odysseus.','',''),
('thoon-antilochus','Thoon','A Trojan killed by Antilochus from behind.','',''),
('alcathous','Alcathous','A Trojan captain, Anchises’ son-in-law, killed by Idomeneus.','Alcathous'),
('othryoneus','Othryoneus','A newcomer from Cabesus who asked for Cassandra and offered to drive the Greeks away.','Othryoneus'),
('deiphobus-note','placeholder','unused','',''),
('asteropaeus-note','placeholder','unused','',''),
('caletor','Caletor','Son of the elder Clytius, killed by Ajax as he carried fire to the ships.','',''),
('lycophontes','Lycophontes','A Trojan killed by Teucer.','Lycophontes'),
('amopaon','Amopaon','A Trojan killed by Teucer, son of Polyaemon.','Amopaon'),
('polyaemon','Polyaemon','Father of the Trojan Amopaon.','Polyaemon','reference'),
('daetor','Daetor','A Trojan killed by Teucer.','Daetor'),
('archeptolemus','Archeptolemus','Son of Iphitus, Hector’s charioteer after Eniopeus.','Archeptolemus'),
('eniopeus','Eniopeus','Son of Thebaeus and Hector’s charioteer, killed by Diomed.','Eniopeus'),
('thebaeus','Thebaeus','Father of Hector’s charioteer Eniopeus.','Thebaeus','reference'),
('dolopion','Dolopion','Priest of the river Scamander and father of Hypsenor.','Dolopion','reference'),
('hypsenor','Hypsenor','Son of Dolopion the river-priest, killed by Eurypylus.','',''),
('hypsenor-hippasus','Hypsenor','Son of Hippasus, a Greek killed by Deiphobus.','',''),
('hippasus-hypsenor','Hippasus','Father of the Greek Hypsenor.','',''),
('hippasus-socus','Hippasus','Father of Socus and Charops.','',''),
('hippasus-apisaon','Hippasus','Father of the Trojan Apisaon killed by Lycomedes.','',''),
('socus','Socus','A rich Trojan, son of Hippasus, who wounds Odysseus and is killed by him.','Socus'),
('charops','Charops','Socus’s brother, son of Hippasus, killed by Odysseus.','Charops'),
('apisaon','Apisaon','Son of Phausius, a Trojan killed by Eurypylus.','',''),
('apisaon-hippasus','Apisaon','Son of Hippasus, a Trojan captain killed by Lycomedes.','',''),
('phausius','Phausius','Father of the Trojan Apisaon killed by Eurypylus.','Phausius','reference'),
('leiocritus','Leiocritus','Son of Arisbas and a follower of Lycomedes, killed by Aeneas.','Leiocritus'),
('arisbas','Arisbas','Father of the Greek Leiocritus.','Arisbas','reference'),
('euchenor','Euchenor','Son of the seer Polyidus, who came to Troy knowing it would kill him.','Euchenor'),
('polyidus-seer','Polyidus','A seer of Corinth, father of Euchenor, who foretold his son’s death.','',''),
('polyidus-eurydamas','Polyidus','A son of the dream-reader Eurydamas, killed by Diomed.','',''),
('abas','Abas','A son of the dream-reader Eurydamas, killed by Diomed.','Abas'),
('eurydamas','Eurydamas','An old reader of dreams whose two sons Diomed killed.','Eurydamas','reference'),
('podes','Podes','Son of Eetion, a rich Trojan and Hector’s friend at table, killed by Menelaus.','Podes'),
('eetion','Eetion','King of Cilician Thebe and Andromache’s father, killed by Achilles.','',''),
('eetion-imbros','Eetion','A guest-friend of Imbros who ransomed Lycaon out of Lemnos.','',''),
('eetion-podes','Eetion','Father of the Trojan Podes.','',''),
('mentor-imbrius','Mentor','A Trojan rich in horses, father of Imbrius.','Mentor','reference'),
('imbrius','Imbrius','Son of Mentor, married to a bastard daughter of Priam, killed by Teucer.','Imbrius'),
('medesicaste','Medesicaste','A bastard daughter of Priam, married to Imbrius.','Medesicaste','reference'),
]:add(*row)
entities[:]=[e for e in entities if not e['id'].endswith('-note')]

# ------------------------------------------------------ the rest of the fallen
SIMPLE=[
('echepolus','Echepolus','Son of Thalysius, the first Trojan killed in the fighting.','',''),
('echepolus-sicyon','Echepolus','A rich man of Sicyon, son of Anchises, who gave Agamemnon the mare Aethe to avoid the war.','',''),
('thalysius','Thalysius','Father of the first Trojan killed.','Thalysius','reference'),
('anchises-sicyon','Anchises','A man of Sicyon, father of Echepolus.','',''),
('simoeisius','Simoeisius','Son of Anthemion, born by the banks of the Simois, killed by Ajax.','Simoeisius'),
('anthemion','Anthemion','Father of Simoeisius.','Anthemion','reference'),
('leucus','Leucus','A comrade of Odysseus killed by Antiphus’s stray spear.','Leucus'),
('democoon','Democoon','A bastard son of Priam from Abydos, killed by Odysseus.','Democoon'),
('diores-note','placeholder','unused','',''),
('elatus','Elatus','A Trojan of Pedasus on the Satnioeis, killed by Agamemnon.','Elatus'),
('melanthus','Melanthus','A Trojan killed by Eurypylus.','Melanthus'),
('phegeus','Phegeus','A son of the priest Dares, killed by Diomed.','Phegeus'),
('idaeus-dares','Idaeus','A son of the priest Dares, saved by Hephaestus.','',''),
('dares','Dares','A rich and blameless Trojan, priest of Hephaestus, father of Phegeus and Idaeus.','Dares','reference'),
('phaesus','Phaesus','Son of Borus the Meonian, killed by Idomeneus.','Phaesus'),
('scamandrius-hunter','Scamandrius','Son of Strophius, a mighty huntsman taught by Artemis, killed by Menelaus.','',''),
('strophius','Strophius','Father of the huntsman Scamandrius.','Strophius','reference'),
('phereclus','Phereclus','Son of Tecton, the shipwright who built the ships that carried Paris to Sparta.','Phereclus'),
('tecton','Tecton','Father of the shipwright Phereclus.','Tecton','reference'),
('hermon','Hermon','Grandfather of the shipwright Phereclus.','Hermon','reference'),
('pedaeus-note','placeholder','unused','',''),
('astynous','Astynous','A Trojan killed by Diomed at the opening of his rampage.','',''),
('astynous-protiaon','Astynous','Son of Protiaon, who is given Hector’s horses to hold.','',''),
('protiaon','Protiaon','Father of the Trojan Astynous.','Protiaon','reference'),
('hypeiron','Hypeiron','A Trojan shepherd of his people killed by Diomed.','Hypeiron'),
('xanthus-phaenops','Xanthus','A son of Phaenops killed by Diomed, one of two who left their father childless.','',''),
('phaenops','Phaenops','An old Trojan whose two sons Diomed killed, leaving him without an heir.','',''),
('phaenops-phorcys','Phaenops','Father of the Phrygian leader Phorcys.','',''),
('phaenops-asius','Phaenops','A man of Abydos, Hector’s dearest guest-friend, whose likeness Apollo takes.','',''),
('chersidamas','Chersidamas','A Trojan killed by Odysseus.','Chersidamas'),
('deiopites','Deiopites','A Trojan killed by Odysseus.','Deiopites'),
('crethon','Crethon','One of the twin sons of Diocles of Phere, killed by Aeneas.','Crethon'),
('orsilochus','Orsilochus','One of the twin sons of Diocles of Phere, killed by Aeneas.','',''),
('orsilochus-river','Orsilochus','Son of the river Alpheus and father of Diocles, a ruler over much people.','',''),
('orsilochus-teucer','Orsilochus','A Trojan, the first man Teucer killed.','',''),
('diocles','Diocles','A rich man of Phere, son of Orsilochus and father of the twins Crethon and Orsilochus.','Diocles','reference'),
('deicoon','Deicoon','Son of Pergasus, a comrade of Aeneas honoured like one of Priam’s sons, killed by Agamemnon.','Deicoon'),
('pergasus','Pergasus','Father of the Trojan Deicoon.','Pergasus','reference'),
('aesepus','Aesepus','A son of Bucolion by the nymph Abarbarea, killed by Euryalus.','',''),
('pedasus-twin','Pedasus','A son of Bucolion by the nymph Abarbarea, killed by Euryalus.','',''),
('bucolion','Bucolion','Laomedon’s eldest son, born out of wedlock, father of twins by a naiad.','Bucolion','reference'),
('abarbarea','Abarbarea','The naiad nymph who bore twins to Bucolion.','Abarbarea','reference'),
('dresus','Dresus','A Trojan killed by Euryalus.','Dresus'),
('opheltius','Opheltius','A Trojan killed by Euryalus.','',''),
('opheltius-hector','Opheltius','A Greek killed by Hector.','',''),
('astyalus','Astyalus','A Trojan killed by Polypoetes.','Astyalus'),
('pidytes','Pidytes','A man of Percote killed by Odysseus.','Pidytes'),
('aretaon','Aretaon','A Trojan killed by Teucer.','Aretaon'),
('ablerus','Ablerus','A Trojan killed by Antilochus.','Ablerus'),
('axylus','Axylus','A rich and hospitable man of Arisbe, son of Teuthranus, killed by Diomed.','Axylus'),
('teuthranus','Teuthranus','Father of Axylus of Arisbe.','Teuthranus','reference'),
('calesius','Calesius','Axylus’s squire and charioteer, killed with him.','Calesius'),
('menesthes','Menesthes','A Greek killed by Hector, sharing a chariot with Anchialus.','Menesthes'),
('anchialus','Anchialus','A Greek killed by Hector, sharing a chariot with Menesthes.','Anchialus'),
('amphius-selagus','Amphius','A rich man of Paesus, son of Selagus, killed by Ajax.','',''),
('selagus','Selagus','Father of Amphius of Paesus.','Selagus','reference'),
('teuthras','Teuthras','A Greek killed by Ares and Hector.','Teuthras'),
('trechus','Trechus','An Aetolian killed by Ares and Hector.','Trechus'),
('helenus-oenops','Helenus','Son of Oenops, a Greek killed by Ares and Hector.','',''),
('oenops-helenus','Oenops','Father of the Greek Helenus.','Oenops','reference'),
('oresbius','Oresbius','A wealthy man of the Cephisian lake, killed by Ares and Hector.','Oresbius'),
('periphas','Periphas','Son of Ochesius and the bravest of the Aetolians, killed by Ares.','',''),
('periphas-epytus','Periphas','Son of Epytus, an old herald of Anchises, whose likeness Apollo takes.','',''),
('ochesius','Ochesius','Father of the Aetolian Periphas.','Ochesius','reference'),
('epytus','Epytus','Father of Anchises’ herald Periphas.','Epytus','reference'),
('coeranus','Coeranus','A Lycian killed by Odysseus.','',''),
('coeranus-meriones','Coiranus','Meriones’s charioteer from Lyctus, killed saving Idomeneus.','Coiranus'),
('alastor-lycian','Alastor','A Lycian killed by Odysseus.','',''),
('alastor-pylian','Alastor','A Pylian chief marshalling Nestor’s men.','',''),
('alastor-squire','Alastor','A Greek squire who helps carry the wounded from the field.','',''),
('alastor-tros','Alastor','Father of the young Trojan Tros killed by Achilles.','',''),
('chromius-lycian','Chromius','A Lycian killed by Odysseus.','',''),
('chromius-pylian','Chromius','A Pylian chief marshalling Nestor’s men.','',''),
('chromius-teucer','Chromius','A Trojan killed by Teucer.','',''),
('chromius-aeneas','Chromius','A Trojan captain who goes with Aeneas and Aretus against Automedon.','',''),
('alcandrus','Alcandrus','A Lycian killed by Odysseus.','Alcandrus'),
('halius','Halius','A Lycian killed by Odysseus.','Halius'),
('noemon','Noemon','A Lycian killed by Odysseus.','',''),
('noemon-greek','Noemon','A comrade of Antilochus, given the mare he wins at the games.','',''),
('prytanis','Prytanis','A Lycian killed by Odysseus.','Prytanis'),
('mydon','Mydon','Son of Atymnius, Pylaemenes’s charioteer, killed by Antilochus.','',''),
('mydon-paeonian','Mydon','A Paeonian killed by Achilles in the river.','',''),
('atymnius','Atymnius','Father of the charioteer Mydon.','Atymnius','reference'),
('otus','Otus','A giant son of Aloeus who bound Ares in a bronze jar.','',''),
('otus-cyllenian','Otus','A Cyllenian captain of the Epeans, killed by Polydamas.','',''),
('ephialtes','Ephialtes','A giant son of Aloeus who bound Ares in a bronze jar with his brother.','Ephialtes','reference'),
('aloeus','Aloeus','Father of the giants Otus and Ephialtes.','Aloeus','reference'),
('eeriboea','Eeriboea','Stepmother to the sons of Aloeus, who told Hermes where Ares was imprisoned.','Eeriboea','reference'),
('amphitryon','Amphitryon','Alcmena’s husband; Heracles is called his son.','Amphitryon','reference'),
('aegialeia','Aegialeia','Diomed’s wife, daughter of Adrastus.','Aegialeia','reference'),
('deipylus','Deipylus','Sthenelus’s chosen comrade, to whom he gives the captured horses.','Deipylus'),
('hypeirochus','Hypeirochus','A Trojan killed by Odysseus.','Hypeirochus'),
('hippodamus','Hippodamus','A Trojan killed by Odysseus.','Hippodamus'),
('thymbraeus','Thymbraeus','A Trojan struck from his chariot by Diomed.','Thymbraeus'),
('molion','Molion','Thymbraeus’s squire, killed by Odysseus.','Molion'),
('bienor','Bienor','A Trojan leader, the first man Agamemnon killed in his rampage.','Bienor'),
('oileus-charioteer','Oileus','Bienor’s charioteer, killed by Agamemnon.','',''),
('antimachus','Antimachus','The Trojan who took Paris’s gold and argued against giving Helen back.','Antimachus','reference'),
('pisander-antimachus','Pisander','A son of Antimachus, killed by Agamemnon.','',''),
('hippolochus-antimachus','Hippolochus','A son of Antimachus, killed by Agamemnon.','',''),
('pisander-trojan','Pisander','A Trojan who fights Menelaus hand to hand with a battle-axe.','',''),
('agastrophus','Agastrophus','Son of Paeon, killed by Diomed after leaving his chariot too far off.','Agastrophus'),
('paeon-agastrophus','Paeon','Father of the Trojan Agastrophus.','','reference'),
('asaeus','Asaeus','A Greek killed by Hector.','Asaeus'),
('autonous','Autonous','A Greek killed by Hector.','',''),
('autonous-trojan','Autonous','A Trojan killed by Patroclus.','',''),
('opites','Opites','A Greek killed by Hector.','Opites'),
('dolops-clytius','Dolops','Son of Clytius, a Greek killed by Hector.','',''),
('dolops-lampus','Dolops','Son of the Trojan elder Lampus, killed by Meges and Menelaus.','',''),
('clytius-dolops','Clytius','Father of the Greek Dolops killed by Hector.','',''),
('agelaus-phradmon','Agelaus','Son of Phradmon, a Trojan killed by Diomed.','',''),
('agelaus-greek','Agelaus','A Greek killed by Hector.','',''),
('phradmon','Phradmon','Father of the Trojan Agelaus.','Phradmon','reference'),
('aesymnus','Aesymnus','A Greek killed by Hector.','Aesymnus'),
('orus','Orus','A Greek killed by Hector.','Orus'),
('hipponous','Hipponous','A Greek killed by Hector.','Hipponous'),
('pandocus','Pandocus','A Trojan wounded by Ajax.','Pandocus'),
('lysandrus','Lysandrus','A Trojan wounded by Ajax.','Lysandrus'),
('pyrasus','Pyrasus','A Trojan wounded by Ajax.','Pyrasus'),
('pylartes','Pylartes','A Trojan wounded by Ajax.','',''),
('pylartes-patroclus','Pylartes','A Trojan killed by Patroclus.','',''),
('itymoneus','Itymoneus','A man of Elis killed by the young Nestor in a cattle raid.','Itymoneus'),
('mulius','Mulius','Augeas’s son-in-law, the first man the young Nestor killed.','',''),
('mulius-patroclus','Mulius','A Trojan killed by Patroclus.','',''),
('mulius-achilles','Mulius','A Trojan killed by Achilles with a spear through the ear.','',''),
('agamede','Agamede','Augeas’s eldest daughter, who knew every herb that grows.','Agamede','reference'),
('thootes','Thootes','Menestheus’s herald, sent to fetch Ajax to the wall.','Thootes'),
('epicles','Epicles','A comrade of Sarpedon killed by Ajax with a stone.','Epicles'),
('alcmaon','Alcmaon','Son of Thestor, a Greek killed by Sarpedon.','Alcmaon'),
('antiphates','Antiphates','A Trojan killed by Leonteus at the wall.','Antiphates'),
('menon','Menon','A Trojan killed by Leonteus at the wall.','Menon'),
('pylon','Pylon','A Trojan killed by Leonteus at the wall.','Pylon'),
('ormenus-leonteus','Ormenus','A Trojan killed by Leonteus at the wall.','',''),
('ormenus-teucer','Ormenus','A Trojan killed by Teucer.','',''),
('ormenus-amyntor','Ormenus','Amyntor’s father, Phoenix’s grandfather.','',''),
('hippomachus','Hippomachus','A Trojan killed by Leonteus at the wall.','Hippomachus'),
('amyntor','Amyntor','Phoenix’s father, who cursed him over a concubine; Autolycus once robbed his house.','Amyntor','reference'),
('laodamas','Laodamas','Antenor’s son, a captain of foot soldiers, killed by Ajax.','Laodamas'),
('deiochus','Deiochus','A Greek struck down by Paris as he fled.','Deiochus'),
('sphelus','Sphelus','Father of Iasus of Athens.','Sphelus','reference'),
('iasus','Iasus','A leader of the Athenians, son of Sphelus, killed by Aeneas.','Iasus'),
('boucolos','Boucolos','Grandfather of the Athenian Iasus.','Boucolos','reference'),
('mecisteus-echius','Mecisteus','Son of Echius, a Greek squire who helps carry the wounded off the field.','',''),
('mecisteus-talaus','Mecisteus','Son of Talaus, Euryalus’s father, who once won every prize at Thebes.','',''),
('mecisteus-polydamas','Mecisteus','A Greek killed by Polydamas.','',''),
('echius-mecisteus','Echius','Father of the Greek squire Mecisteus.','',''),
('echius-polites','Echius','A Greek killed by Polites.','',''),
('echius-damastor','Echius','Son of Damastor, a Trojan killed by Patroclus.','',''),
('damastor','Damastor','Father of the Trojan Echius.','Damastor','reference'),
('talaus','Talaus','Euryalus’s grandfather.','Talaus','reference'),
('euryalus','Euryalus','Son of Mecisteus and one of Diomed’s companions; he boxes Epeus at the funeral games.','Euryalus'),
('cleitus','Cleitus','Son of Pisenor and Polydamas’s comrade, shot by Teucer as he drove for Hector.','Cleitus'),
('pisenor','Pisenor','Father of the Trojan Cleitus.','Pisenor','reference'),
('melanippus-hiketaon','Melanippus','Son of Hiketaon, a Trojan whom Hector rebukes and Antilochus kills.','',''),
('melanippus-teucer','Melanippus','A Trojan killed by Teucer.','',''),
('melanippus-patroclus','Melanippus','A Trojan killed by Patroclus.','',''),
('melanippus-greek','Melanippus','A Greek captain who goes with Achilles to Agamemnon’s tent.','',''),
('periphetes','Periphetes','A man of Mycenae, son of Copreus, the best of his father’s line; killed by Hector after tripping on his shield.','',''),
('periphetes-teucer','Periphetes','A Trojan killed by Teucer.','',''),
('copreus','Copreus','Eurystheus’s herald to Heracles, father of Periphetes of Mycenae.','Copreus','reference'),
('lycophron','Lycophron','Mastor’s son of Cythera, Ajax’s squire, killed by Hector.','Lycophron'),
('mastor','Mastor','Father of Ajax’s squire Lycophron.','Mastor','reference'),
('euphetes','Euphetes','King of Ephyra, who gave Phyleus the corslet Meges wears.','Euphetes','reference'),
('hyrtius','Hyrtius','Son of Gyrtius and captain of the Mysians, killed by Ajax.','Hyrtius'),
('gyrtius','Gyrtius','Father of the Mysian captain Hyrtius.','Gyrtius','reference'),
('phalces','Phalces','A Trojan captain, killed by Antilochus.','Phalces'),
('mermerus','Mermerus','A Trojan killed by Antilochus.','Mermerus'),
('morys','Morys','Son of Hippotion, a Trojan killed by Meriones.','Morys'),
('hippotion','Hippotion','Father of the Trojan Morys, killed by Meriones.','Hippotion'),
('prothoon','Prothoon','A Trojan killed by Teucer.','Prothoon'),
('hyperenor','Hyperenor','A son of Panthous, wounded by Menelaus and boasted over.','Hyperenor'),
('orthaeus','Orthaeus','A Trojan captain in the press about Cebriones.','Orthaeus'),
('polyphetes','Polyphetes','A Trojan captain in the press about Cebriones.','Polyphetes'),
('palmys','Palmys','A Trojan captain in the press about Cebriones.','Palmys'),
('erymas','Erymas','A Trojan speared in the mouth by Idomeneus.','',''),
('erymas-patroclus','Erymas','A Trojan killed by Patroclus.','',''),
('lycon','Lycon','A Trojan who fights Peneleos hand to hand and is killed by him.','Lycon'),
('acamas-meriones','placeholder','unused','',''),
('cleobulus','Cleobulus','A Trojan taken alive and killed by Ajax the less.','Cleobulus'),
('amisodorus','Amisodorus','The man who reared the Chimaera; his two sons fell to the sons of Nestor.','Amisodorus','reference'),
('chimaera','The Chimaera','The monster Bellerophon killed, reared by Amisodorus. The modern edition spells it Chimera.','Chimaera|Chimera','reference','mythical-being'),
('laogonus','Laogonus','Son of Onetor the priest of Zeus, killed by Meriones.','',''),
('laogonus-bias','Laogonus','A Trojan, son of Bias, killed by Achilles.','',''),
('onetor','Onetor','Priest of Zeus of Ida and father of the Trojan Laogonus.','Onetor','reference'),
('bathycles','Bathycles','A rich Myrmidon of Hellas, son of Chalcon, killed by Glaucus.','Bathycles'),
('chalcon','Chalcon','Father of the Myrmidon Bathycles.','Chalcon','reference'),
('sthenelaus','Sthenelaus','Son of Ithaemenes, a Trojan killed by Patroclus.','Sthenelaus'),
('ithaemenes','Ithaemenes','Father of the Trojan Sthenelaus.','Ithaemenes','reference'),
('pronous','Pronous','A Trojan killed by Patroclus.','Pronous'),
('thestor','Thestor','Enops’s son, a Trojan charioteer hooked out of his chariot by Patroclus.','',''),
('thestor-calchas','Thestor','Calchas’s father.','',''),
('thestor-alcmaon','Thestor','Father of the Greek Alcmaon killed by Sarpedon.','',''),
('enops','Enops','Father of the charioteer Thestor and of Satnius by a naiad.','Enops','reference'),
('satnius','Satnius','Son of Enops by a naiad nymph, wounded by Ajax the less.','Satnius'),
('amphoterus','Amphoterus','A Trojan killed by Patroclus.','Amphoterus'),
('epaltes','Epaltes','A Trojan killed by Patroclus.','Epaltes'),
('pyris','Pyris','A Trojan killed by Patroclus.','Pyris'),
('ipheus','Ipheus','A Trojan killed by Patroclus.','Ipheus'),
('euippus','Euippus','A Trojan killed by Patroclus.','Euippus'),
('polymelus','Polymelus','Son of Argeas, a Trojan killed by Patroclus.','Polymelus'),
('argeas','Argeas','Father of the Trojan Polymelus.','Argeas','reference'),
('echeclus','Echeclus','A Trojan killed by Patroclus.','',''),
('echeclus-achilles','Echeclus','Son of Agenor, a Trojan cut down by Achilles.','',''),
('perimus','Perimus','Son of Megas, a Trojan killed by Patroclus.','Perimus'),
('megas','Megas','Father of the Trojan Perimus.','Megas','reference'),
('epistor','Epistor','A Trojan killed by Patroclus.','Epistor'),
('elasus','Elasus','A Trojan killed by Patroclus.','Elasus'),
('thersilochus','Thersilochus','A Paeonian captain, killed by Achilles in the river.','Thersilochus'),
('deisenor','Deisenor','A Trojan ally whom Hector cheers on over Patroclus’s body.','Deisenor'),
('aretus','Aretus','A Trojan who goes with Chromius and Aeneas against Automedon and is killed.','Aretus'),
('epeus','Epeus','Son of Panopeus, a skilful boxer who beats Euryalus at the funeral games.','Epeus'),
('panopeus','Panopeus','Father of the boxer Epeus.','Panopeus','reference'),
('astypylus','Astypylus','A Paeonian killed by Achilles in the river.','Astypylus'),
('mnesus','Mnesus','A Paeonian killed by Achilles in the river.','Mnesus'),
('thrasius','Thrasius','A Paeonian killed by Achilles in the river.','Thrasius'),
('oeneus-paeonian','Oeneus','A Paeonian killed by Achilles in the river.','',''),
('ophelestes-paeonian','Ophelestes','A Paeonian killed by Achilles in the river.','',''),
('ophelestes-teucer','Ophelestes','A Trojan killed by Teucer.','',''),
('iphition','Iphition','Son of Otrynteus by a naiad, a leader of much people, the first man Achilles killed on his return.','Iphition'),
('otrynteus','Otrynteus','Father of Iphition, a city-sacker of Meonia.','Otrynteus','reference'),
('demoleon','Demoleon','A son of Antenor, killed by Achilles.','Demoleon'),
('hippodamas','Hippodamas','A Trojan killed by Achilles as he sprang from his chariot.','Hippodamas'),
('demouchus','Demouchus','Son of Philetor, a big and powerful Trojan killed by Achilles.','Demouchus'),
('philetor','Philetor','Father of the Trojan Demouchus.','Philetor','reference'),
('deucalion-trojan','Deucalion','A Trojan whose arm Achilles pinned before beheading him.','',''),
('deucalion-crete','Deucalion','Minos’s son and Idomeneus’s father.','',''),
('rhigmus','Rhigmus','Son of Peires, a Thracian killed by Achilles.','Rhigmus'),
('peires','Peires','Father of the Thracian Rhigmus.','Peires','reference'),
('areithous','Areithous','Rhigmus’s squire, killed by Achilles.','',''),
('areithous-mace','Areithous','The Mace-man of Arne, father of Menesthius.','',''),
('phylomedusa','Phylomedusa','Wife of Areithous the Mace-man and mother of Menesthius.','Phylomedusa','reference'),
('eioneus','Eioneus','A Greek killed by Hector at the single-combat challenge.','Eioneus'),
('iphinous','Iphinous','Son of Dexius, a Greek killed by Glaucus.','Iphinous'),
('dexius','Dexius','Father of the Greek Iphinous.','Dexius','reference'),
('promachus','Promachus','A Boeotian killed by Acamas, son of Alegenor.','Promachus'),
('alegenor','Alegenor','Father of the Boeotian Promachus.','Alegenor','reference'),
('ilioneus','Ilioneus','The only son of the rich flock-master Phorbas, killed by Peneleos.','Ilioneus'),
('adamas-note','placeholder','unused','',''),
]
for row in SIMPLE:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# --------------------------------------------------- myth, genealogy, the past
for row in [
('heracles','Heracles','Zeus’s mortal son, who sacked Troy in Laomedon’s day. Butler’s original calls him Hercules.','Hercules|Heracles','reference'),
('alcmena','Alcmena','Heracles’ mother, whom Zeus loved in Thebes. The modern edition spells her Alcmene.','Alcmena|Alcmene','reference'),
('eurystheus','Eurystheus','The king who set Heracles his labours, born before him by Hera’s contrivance.','Eurystheus','reference'),
('bellerophon','Bellerophon','The hero of Glaucus’s family story, sent to Lycia with a sealed message and set three deadly tasks.','Bellerophon','reference'),
('proetus','Proetus','The king who drove Bellerophon out of Argos with a letter meant to kill him.','Proetus','reference'),
('sisyphus','Sisyphus','The craftiest of mankind, Glaucus’s ancestor, who lived at Ephyra.','Sisyphus','reference'),
('aeolus','Aeolus','Sisyphus’s father.','Aeolus','reference'),
('isander','Isander','A son of Bellerophon, killed by Ares fighting the Solymi.','Isander','reference'),
('laodameia','Laodameia','Bellerophon’s daughter, who bore Sarpedon to Zeus.','Laodameia','reference'),
('lycurgus','Lycurgus','Son of Dryas, who drove Dionysus into the sea and was blinded for it.','Lycurgus','reference'),
('dryas','Dryas','Lycurgus’s father; also one of the great men of Nestor’s youth.','Dryas','reference'),
('caeneus','Caeneus','One of the great men of Nestor’s youth.','Caeneus','reference'),
('exadius','Exadius','One of the great men of Nestor’s youth.','Exadius','reference'),
('polyphemus','Polyphemus','One of the great men of Nestor’s youth, named among the Lapiths.','Polyphemus','reference'),
('theseus','Theseus','Son of Aegeus, named among the great men of Nestor’s youth.','Theseus','reference'),
('aegeus','Aegeus','Theseus’s father.','Aegeus','reference'),
('ereuthalion','Ereuthalion','The champion the young Nestor killed in single combat.','Ereuthalion','reference'),
('pelops','Pelops','The mighty charioteer, from whom Agamemnon’s sceptre descends.','Pelops','reference'),
('thyestes','Thyestes','Atreus’s brother, rich in flocks, who held the sceptre before Agamemnon.','Thyestes','reference'),
('adrastus','Adrastus','The old king who reigned at Sicyon; his line married into Tydeus’s.','Adrastus','reference'),
('polynices','Polynices','The exile with whom Tydeus went to Mycenae to raise an army against Thebes.','Polynices','reference'),
('eteocles','Eteocles','The Theban in whose house Tydeus found the Cadmeans feasting.','Eteocles','reference'),
('maeon','Maeon','Son of Haemon, one of the two Theban captains who ambushed Tydeus and the only one he spared.','Maeon','reference'),
('polyphontes','Polyphontes','Son of Autophonus and one of the two Theban captains who ambushed Tydeus.','Polyphontes','reference'),
('autophonus','Autophonus','Father of the Theban captain Polyphontes.','Autophonus','reference'),
('oedipus','Oedipus','The Theban king at whose funeral games Mecisteus beat everyone.','Oedipus','reference'),
('cadmus','Cadmus','The founder of Thebes; its people are called after him.','Cadmus','reference'),
('meleager','Meleager','The Aetolian hero of Phoenix’s story, who withdrew from the fighting in anger and came back too late for the gifts.','Meleager','reference'),
('oeneus','Oeneus','King of Calydon, Meleager’s father, whose neglected sacrifice brought the boar.','',''),
('althaea','Althaea','Meleager’s mother, who cursed him for killing her brother.','Althaea','reference'),
('cleopatra','Cleopatra','Meleager’s wife, who persuaded him to fight at last.','Cleopatra','reference'),
('marpessa','Marpessa','Cleopatra’s mother, over whom Ides faced Apollo himself.','Marpessa','reference'),
('ides','Ides','The man who took his bow against Apollo for Marpessa’s sake.','Ides','reference'),
('euenus','Euenus','Marpessa’s father.','Euenus','reference'),
('alcyone','Alcyone','The by-name Cleopatra’s parents gave her, after the halcyon’s cry.','Alcyone','reference'),
('niobe','Niobe','The mother of twelve children killed by Apollo and Artemis, who ate at last for all her grief.','Niobe','reference'),
('tydeus-note','placeholder','unused','',''),
('danae','Danae','Acrisius’s daughter, mother of Perseus by Zeus. The original spells her Danae, the modern Danaë.','Danae|Danaë','reference'),
('acrisius','Acrisius','Danae’s father.','Acrisius','reference'),
('perseus','Perseus','Danae’s son by Zeus, the famed hero and Sthenelus’s father.','',''),
('sthenelus-perseus','Sthenelus','Son of Perseus and father of Eurystheus.','',''),
('capaneus','Capaneus','Father of Diomed’s companion Sthenelus.','Capaneus','reference'),
('semele','Semele','A woman of Thebes by whom Zeus begot Dionysus.','Semele','reference'),
('minos','Minos','Zeus’s son by the daughter of Phoenix, chief ruler in Crete and Deucalion’s father.','Minos','reference'),
('rhadamanthus','Rhadamanthus','Zeus’s son by the daughter of Phoenix, Minos’s brother.','Rhadamanthus','reference'),
('phoenix-father','Phoenix','The father of the woman who bore Minos and Rhadamanthus to Zeus.','',''),
('ixion','Ixion','The man whose wife bore Pirithous to Zeus.','Ixion','reference'),
('typhoeus','Typhoeus','The monster lashed by Zeus’s thunder in the land of the Arimi.','Typhoeus','reference','mythological-figure'),
('tityus-note','placeholder','unused','',''),
('jason','Jason','Father of Eueneus of Lemnos by Hypsipyle.','Jason','reference'),
('eueneus','Eueneus','Son of Jason, who sent wine from Lemnos and bought Lycaon as a slave. The modern edition spells him Euneus.','Eueneus|Euneus','reference'),
('hypsipyle','Hypsipyle','Eueneus’s mother.','Hypsipyle','reference'),
('eurytus','Eurytus','King of Oechalia, who boasted he could outshoot Apollo.','',''),
('thamyris','Thamyris','The minstrel the Muses met at Dorium and silenced for his boasting.','Thamyris','reference'),
('aesculapius','Aesculapius','The healer, father of Machaon and Podalirius. The modern edition calls him Asclepius.','Aesculapius|Asclepius','reference'),
('chiron','Chiron','The centaur who gave Aesculapius his drugs and Peleus the great ash spear.','Chiron','reference'),
('minyas','Minyas','The old ruler of Orchomenus, whose realm it is called.','Minyas','reference'),
('erechtheus','Erechtheus','The earth-born king of Athens whom Athena established in her own sanctuary.','Erechtheus','reference'),
('pittheus','Pittheus','Father of Helen’s handmaid Aethrae.','Pittheus','reference'),
('aethrae','Aethrae','One of Helen’s two handmaids in Troy.','Aethrae','reference'),
('clymene','Clymene','One of Helen’s two handmaids in Troy.','','reference'),
('castor','Castor','Helen’s brother, a breaker of horses, whom she cannot find among the Greeks.','',''),
('pollux','Pollux','Helen’s brother, a mighty boxer, whom she cannot find among the Greeks.','Pollux','reference'),
('otreus','Otreus','A Phrygian leader with whom Priam once camped as an ally.','Otreus','reference'),
('mygdon','Mygdon','A Phrygian leader with whom Priam once camped as an ally.','Mygdon','reference'),
('amazons','The Amazons','The women who fight like men, who once came against the Phrygians.','Amazons','reference','group'),
('daedalus','Daedalus','The craftsman who made the dancing-floor at Cnossus for Ariadne.','Daedalus','reference'),
('ariadne','Ariadne','Minos’s daughter, for whom Daedalus made the dancing-floor.','Ariadne','reference'),
('makar','Makar','The old ruler of Lesbos, named in measuring the bounds of Priam’s former wealth.','Makar','reference'),
('eumedes','Eumedes','The famous herald, Dolon’s father.','Eumedes','reference'),
('autolycus','Autolycus','The thief who stole the boar’s-tusk helmet out of Amyntor’s house.','Autolycus','reference'),
('amphidamas','Amphidamas','The man of Cythera to whom Autolycus gave the boar’s-tusk helmet.','Amphidamas','reference'),
('molus','Molus','Meriones’s father, who was given the boar’s-tusk helmet.','Molus','reference'),
('hippocoon','Hippocoon','Rhesus’s kinsman and comrade, roused by Apollo to find the Thracian camp plundered.','Hippocoon'),
('polydamna-note','placeholder','unused','',''),
('argus','Argus','The watcher Hermes killed; the god is called his slayer throughout.','Argus','reference','mythological-figure'),
('sintians','The Sintians','The people of Lemnos who tended Hephaestus when he fell out of heaven.','Sintians','reference','group'),
('curetes','The Curetes','The people who fought the Aetolians round Calydon in Phoenix’s story.','Curetes','reference','group'),
('lapiths','The Lapithae','The people of Polypoetes and Leonteus, who drove the mountain savages from Pelion.','Lapithae|Lapiths','reference','group'),
('centaurs','The mountain savages','The shaggy hill-dwellers Pirithous drove from Pelion to the Aithices.','','reference','group'),
('hippodameia','Hippodameia','Pirithous’s wife, who bore Polypoetes on the day he took his revenge on the mountain savages.','Hippodameia','reference'),
('hippemolgi','The Hippemolgi','The noble milk-drinking people of the north, on whom Zeus turns his eyes away from Troy.','Hippemolgi','reference','group'),
('selli','The Selli','The prophets of Zeus at Dodona, who sleep on the ground with unwashed feet.','Selli','reference','group'),
('pramnian-note','placeholder','unused','',''),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ----------------------------------------------------------------- the peoples
for row in [
('achaeans','The Achaeans','The Greek army before Troy; the poem calls them Achaeans, Argives and Danaans indifferently.','Achaeans|Argives|Danaans|Greeks','major','group'),
('trojans','The Trojans','The people of Troy and Hector’s army.','Trojans','major','group'),
('myrmidons','The Myrmidons','Achilles’ own people, who sit out the fighting with him.','Myrmidons','supporting','group'),
('lycians','The Lycians','Sarpedon and Glaucus’s people, the strongest of Troy’s allies.','Lycians','supporting','group'),
('dardanians','The Dardanians','Aeneas’s people, of the older Trojan line.','Dardanians','supporting','group'),
('boeotians','The Boeotians','The Greek contingent under Peneleos, Leitus and their fellow captains.','Boeotians','reference','group'),
('locrians','The Locrians','Ajax the less’s people, light-armed men who fight with bow and sling.','Locrians','reference','group'),
('abantes','The Abantes','The fierce spearmen of Euboea under Elephenor.','Abantes','reference','group'),
('athenians','The Athenians','The Greek contingent under Menestheus.','Athenians','reference','group'),
('phoceans','The Phoceans','The Greek contingent under Schedius and Epistrophus.','Phoceans','reference','group'),
('cretans','The Cretans','Idomeneus and Meriones’s people, from the hundred cities of Crete.','Cretans','reference','group'),
('epeans','The Epeans','The people of Elis and Buprasium, under four captains.','Epeans','reference','group'),
('cephallenians','The Cephallenians','Odysseus’s people, of Ithaca and the islands.','Cephallenians','reference','group'),
('aetolians','The Aetolians','Thoas’s people, of Pleuron and Calydon.','Aetolians','reference','group'),
('arcadians','The Arcadians','Agapenor’s people, who sailed in ships Agamemnon lent them.','Arcadians','reference','group'),
('pylians','The Pylians','Nestor’s people.','Pylians','reference','group'),
('phthians','The Phthians','The men of Phthia, led by Medon and Podarces.','Phthians','reference','group'),
('lesbians','The Lesbians','The women of Lesbos whom Achilles took, offered back among Agamemnon’s gifts.','Lesbians','reference','group'),
('thracians','The Thracians','Troy’s allies from beyond the Hellespont, under Acamas and Peirous.','Thracians','reference','group'),
('paeonians','The Paeonians','Troy’s allies from Amydon on the Axius, archers and then spearmen.','Paeonians','reference','group'),
('mysians','The Mysians','Troy’s allies under Chromis and Ennomus the augur.','Mysians','reference','group'),
('phrygians','The Phrygians','Troy’s allies from Ascania under Phorcys and Ascanius.','Phrygians','reference','group'),
('meonians','The Meonians','Troy’s allies from under Mount Tmolus.','Meonians','reference','group'),
('carians','The Carians','Troy’s allies of a strange speech, under Nastes and Amphimachus.','Carians','reference','group'),
('paphlagonians','The Paphlagonians','Troy’s allies under Pylaemenes.','Paphlagonians','reference','group'),
('halizoni','The Halizoni','Troy’s allies from Alybe, where the silver comes from.','Halizoni','reference','group'),
('cicones','The Cicons','Troy’s allies; the modern edition spells them Cicones.','Cicons|Cicones','reference','group'),
('pelasgians','The Pelasgi','Troy’s Pelasgian allies from Larissa; the modern edition calls them Pelasgians.','Pelasgi|Pelasgians','reference','group'),
('leleges','The Lelegae','Altes’s people, whom Achilles attacked with the Trojans. The modern edition calls them Leleges.','Lelegae|Leleges','reference','group'),
('cauconians','The Cauconians','A people camped on the Trojan side, named by Dolon.','Cauconians','reference','group'),
('cadmeans','The Cadmeans','The people of Thebes, who ambushed Tydeus.','Cadmeans','reference','group'),
('hellenes','The Hellenes','The people of Hellas, named beside the Achaeans.','Hellenes','reference','group'),
('cilicians','The Cilicians','Eetion’s people at Thebe under Mount Placus.','Cilicians','reference','group'),
('ethiopians','The Ethiopians','The people at whose feast Zeus and the gods are entertained.','Ethiopians','reference','group'),
('solymi','The Solymi','The far-famed people Bellerophon fought, the hardest of his battles.','Solymi','reference','group'),
('dolopians','The Dolopians','The people on the borders of Phthia over whom Peleus made Phoenix ruler.','Dolopians','reference','group'),
('peraebi','The Peraebi','The people who followed Guneus from about Dodona.','Peraebi','reference','group'),
('enienes','The Enienes','The people who followed Guneus from about Dodona.','Enienes','reference','group'),
('magnetes','The Magnetes','Prothous’s people, by the Peneus and Mount Pelion.','Magnetes','reference','group'),
('minyan','placeholder','unused','',''),
]:add(*row)
entities[:]=[e for e in entities if e['name']!='placeholder']

# ------------------------------------------------------------------ the horses
for row in [
('xanthus-horse','Xanthus','One of Achilles’ two immortal horses, born to the west wind; Hera gives him speech to warn his master.','','supporting','animal'),
('balius','Balius','Achilles’ other immortal horse, born to the west wind.','Balius','supporting','animal'),
('pedasus','Pedasus','The mortal trace-horse Achilles took at Thebe, killed beside the immortal pair.','',''),
('xanthus-hector','Xanthus','One of Hector’s four horses, called on by name before the ships.','','reference','animal'),
('podargus','Podargus','One of Hector’s four horses; also the name of Menelaus’s own horse at the games.','','reference','animal'),
('aethon','Aethon','One of Hector’s four horses.','Aethon','reference','animal'),
('lampus','Lampus','One of Hector’s four horses.','','reference','animal'),
('aethe','Aethe','Agamemnon’s mare, lent to Menelaus for the chariot race.','Aethe','reference','animal'),
('arion','Arion','Adrastus’s horse, of divine race, named as the fastest there is.','Arion','reference','animal'),
]:add(*row)
for e in entities:
    if e['id']=='pedasus':e['kind']='animal';e['category']='supporting'

Path(__file__).parent.joinpath('editorial.json').write_text(json.dumps(dict(
 contentVersion='2026-09-11.1',
 coverage='Both full English editions, all twenty-four books: named people, gods, personified powers, named horses and named peoples. Places, rivers as geography, mountains, islands, ships and adjectival forms of place names are excluded; a river that speaks or fights is included.',
 entities=entities),ensure_ascii=False,indent=2)+'\n')
print(len(entities),'entities')
