"""Manually authored recognition cards for both full English texts of the play."""
import json
from pathlib import Path
entities=[]
def add(id,name,body,aliases='',category='supporting',kind='person'):
 entities.append(dict(id=id,name=name,body=body,aliases=aliases.split('|') if aliases else [],category=category,kind=kind,subtitle='',snapshots=[]))

# Principals and named speaking cast. Aliases are case-sensitive. Bare "Henry" is
# never an alias: it belongs to Lord Scroop, to Henry the Sixth and to the King.
for row in [
('king-henry','King Henry V','The young King of England, who presses a claim to the crown of France.','KING HENRY V|KING HENRY|King Henry|Harry|Harry le Roy|Le Roy|Henry Plantagenet','central'),
('french-king','The King of France','The French king, Katharine’s father; the play never gives his name.','FRENCH KING|French King|King of France','major'),
('dauphin','The Dauphin','The French king’s son and heir, who sends King Henry a mocking gift.','DAUPHIN|Dauphin','major'),
('constable','The Constable of France','Charles Delabreth, High Constable of France and commander of its army.','CONSTABLE|Constable|Charles Delabreth|Delabreth','major'),
('fluellen','Fluellen','A Welsh captain in the English army, devoted to the ancient disciplines of war.','FLUELLEN|Fluellen','major'),
('pistol','Pistol','An ensign in the English army, formerly of Falstaff’s London company.','PISTOL|Pistol|Ancient Pistol|Anchient Pistol|Ensign Pistol','major'),
('exeter','The Duke of Exeter','King Henry’s uncle, who carries his demands to the French court.','EXETER|Exeter','major'),
('katharine','Princess Katharine','The French king’s daughter, whom King Henry claims as part of his terms.','KATHARINE|KATHERINE|Katharine|Katherine|Kate','major'),
('chorus','The Chorus','The speaker who opens each act and asks the audience to imagine what the stage cannot show.','CHORUS|Chorus','major'),
('montjoy','Montjoy','The French herald, who carries his king’s messages to King Henry.','MONTJOY|Montjoy','major'),
('canterbury','The Archbishop of Canterbury','The Archbishop, who lays out King Henry’s claim to France.','CANTERBURY|Canterbury|Archbishop of Canterbury','major'),
('orleans','The Duke of Orleans','Charles, Duke of Orleans, a French nobleman and the king’s nephew.','ORLEANS|Orleans','major'),
('gower','Gower','An English captain and Fluellen’s friend.','GOWER|Gower','major'),
('williams','Michael Williams','A soldier in the English army who argues with the disguised King on the eve of battle.','WILLIAMS|Williams|Michael Williams','major'),
('gloucester','The Duke of Gloucester','King Henry’s brother, who directs the siege works at Harfleur.','GLOUCESTER|Gloucester'),
('bedford','The Duke of Bedford','King Henry’s brother.','BEDFORD|Bedford'),
('clarence','The Duke of Clarence','King Henry’s brother.','Clarence'),
('westmorland','The Earl of Westmorland','An English nobleman of King Henry’s council.','WESTMORLAND|Westmorland'),
('warwick','The Earl of Warwick','An English nobleman in King Henry’s train.','WARWICK|Warwick'),
('salisbury','The Earl of Salisbury','An English nobleman who takes his charge before Agincourt.','SALISBURY|Salisbury'),
('huntingdon','The Earl of Huntingdon','An English nobleman at the French court for the peace terms.','Huntingdon|Huntington'),
('york','The Duke of York','Edward, Duke of York, who asks to lead the vanguard at Agincourt.','YORK|York'),
('ely','The Bishop of Ely','The Bishop, who presses King Henry’s French claim alongside Canterbury.','ELY|Ely|Bishop of Ely'),
('scroop','Lord Scroop','Henry, Lord Scroop of Masham, one of King Henry’s intimates.','SCROOP|Scroop|Henry Lord Scroop|Masham'),
('cambridge','The Earl of Cambridge','Richard, Earl of Cambridge.','CAMBRIDGE|Cambridge'),
('grey','Sir Thomas Grey','A knight of Northumberland.','GREY|Grey'),
('erpingham','Sir Thomas Erpingham','An old English knight, whose cloak the King borrows the night before Agincourt.','ERPINGHAM|Erpingham|Sir Thomas Erpingham'),
('jamy','Captain Jamy','A Scottish captain in the English army.','JAMY|Jamy|Captain James'),
('macmorris','Captain Macmorris','An Irish captain in the English army, in charge of the mines at Harfleur.','MACMORRIS|Macmorris'),
('bates','John Bates','A soldier in the English army.','BATES|Bates|John Bates'),
('court','Alexander Court','A soldier in the English army; not the Macedonian king Fluellen argues about later.','COURT|Alexander Court'),
('bardolph','Bardolph','A lieutenant in the English army, formerly of Falstaff’s London company.','BARDOLPH|Bardolph'),
('nym','Nym','A corporal in the English army, formerly of Falstaff’s London company.','NYM|Nym'),
('hostess','The Hostess','Nell Quickly, who keeps a London tavern and has married Pistol.','HOSTESS|Hostess|Nell|Quickly'),
('boy','The Boy','The boy who serves Pistol, Bardolph and Nym, and interprets for Pistol in France.','BOY|Boy'),
('queen-isabel','Queen Isabel','The Queen of France, Katharine’s mother.','QUEEN ISABEL|Queen Isabel'),
('alice','Alice','An old gentlewoman attending Princess Katharine, who has been in England.','ALICE|Alice'),
('burgundy','The Duke of Burgundy','The French duke who brokers the meeting between the two kings.','BURGUNDY|Burgundy'),
('bourbon','The Duke of Bourbon','John, Duke of Bourbon, a French nobleman.','BOURBON|Bourbon'),
('rambures','Lord Rambures','A French lord, master of the crossbows.','RAMBURES|Rambures'),
('grandpre','Lord Grandpré','A French lord who describes the English army on the morning of Agincourt.','GRANDPRÉ|Grandpré'),
('berry','The Duke of Berry','A French duke summoned to the defence.','Berry'),
('brittany','The Duke of Brittany','A French duke summoned to the defence.','Brittany'),
('brabant','The Duke of Brabant','Anthony, Duke of Brabant, brother to the Duke of Burgundy.','Brabant'),
('alencon','The Duke of Alençon','John, Duke of Alençon, from whose helmet King Henry took a glove.','Alençon'),
('bar','The Duke of Bar','Edward, Duke of Bar, a French nobleman.','Duke of Bar'),
('chatillon','Jacques Chatillon','Admiral of France.','Jacques Chatillon|Jacques of Chatillon|Chatillon'),
('boucicault','Lord Boucicault','A French lord, taken prisoner at Agincourt.','Boucicault'),
('guichard-dauphin','Sir Guichard Dauphin','Great Master of France; a nobleman of that surname, not the king’s son.','Sir Guichard Dauphin|Guichard Dauphin|Guichard'),
('vaudemont','Vaudemont','A French earl named among the dead at Agincourt.','Vaudemont'),
('beaumont','Beaumont','A French earl named among the dead at Agincourt.','Beaumont'),
('roussi','Roussi','A French earl named among the dead at Agincourt.','Roussi'),
('fauconbridge','Fauconbridge','A French earl named among the dead at Agincourt.','Fauconbridge'),
('foix','Foix','A French earl named among the dead at Agincourt.','Foix'),
('lestrale','Lestrale','A French earl named among the dead at Agincourt.','Lestrale'),
('marle','Marle','A French earl named among the dead at Agincourt.','Marle'),
('charolois','Charolois','A French lord called to the field.','Charolois'),
]:add(*row)

for row in [
('governor','The Governor of Harfleur','The governor who yields the town to King Henry.','GOVERNOR|Governor'),
('french-soldier','Monsieur Le Fer','A French gentleman-soldier taken prisoner by Pistol on the field.','FRENCH SOLDIER|Monsieur le Fer|Master Fer'),
('english-herald','The English herald','King Henry’s herald, who brings him the count of the dead.','HERALD'),
('french-court-messenger','The messenger at the French court','The messenger who announces the English embassy to the French king.',''),
('french-camp-messenger','The messenger in the French camp','The messenger who brings the French commanders word of the English position.',''),
('french-ambassador','The French ambassador','The ambassador who delivers the Dauphin’s answer and his gift to King Henry.','FIRST AMBASSADOR|AMBASSADOR'),
]:add(*row,kind='unnamed-role')

for row in [
('french-ambassadors','The French ambassadors','The embassy sent from France to King Henry’s court.',''),
('english-ambassadors','The English ambassadors','The embassy King Henry sends into France, headed by Exeter.',''),
('attendants','The attendants','The attendants waiting on King Henry at his court.','Attendants'),
('lords','The lords','The English and French lords at the two courts.','LORDS|Lords'),
('ladies','The ladies','The ladies attending the French queen and princess.','Ladies'),
('soldiers','The soldiers','The soldiers of the English army.','Soldiers'),
('citizens','The citizens of Harfleur','The townspeople on the walls when King Henry demands the town.','citizens'),
]:add(*row,kind='group')

# People discussed but never present, and cited figures.
for row in [
('falstaff','Sir John Falstaff','The old knight of King Henry’s wild years, whose London company Pistol, Bardolph and Nym come from.','Sir John Falstaff|Falstaff','person'),
('henry-fourth','King Henry the Fourth','King Henry’s father, who took the crown from Richard the Second; the play names him only as the King’s father.','','person'),
('richard-second','King Richard the Second','The king King Henry’s father deposed, for whose soul King Henry pays priests to sing.','','person'),
('henry-sixth','Henry the Sixth','King Henry’s infant son, crowned King of France and England after him.','Henry the Sixth','person'),
('edward-third','King Edward the Third','King Henry’s great-grandfather, from whom the claim to France descends.','Edward the Third|King Edward','person'),
('black-prince','Edward the Black Prince','King Henry’s great-uncle, victor over the French at Crécy.','Edward the Black Prince|Edward, Black Prince of Wales|Edward the Plack Prince of Wales','person'),
('king-of-scots','The King of Scots','A Scottish king taken prisoner by the English and sent into France.','King of Scots','person'),
('holy-roman-emperor','The Emperor','The Holy Roman Emperor, expected in England to mediate the peace; he is never named.','','person'),
('suffolk','The Earl of Suffolk','An English nobleman who dies at Agincourt beside the Duke of York.','Suffolk','person'),
('ketly','Sir Richard Ketly','An English knight named among the dead at Agincourt.','Sir Richard Ketly|Ketly','person'),
('davy-gam','Davy Gam','A Welsh esquire named among the English dead at Agincourt.','Davy Gam','person'),
('talbot','Talbot','An English commander named in King Henry’s roll of remembered names.','Talbot','person'),
('doll-tearsheet','Doll Tearsheet','A London woman of Pistol’s old company, whose death he hears of at the end.','Doll Tearsheet|Doll','person'),
('pharamond','Pharamond','The legendary Frankish king the French cite as the founder of the Salic law.','Pharamond','person'),
('charles-the-great','Charlemagne','The Frankish emperor who subdued the Saxons and settled the French beyond the Sala.','Charles the Great|Charlemagne','person'),
('charlemain','Charlemain','A later Frankish king in Canterbury’s pedigree, father of Lady Lingare; the text keeps him distinct from Charlemagne.','Charlemain','person'),
('pepin','King Pepin','The Frankish king who deposed Childeric and claimed France through the female line.','King Pepin|Pepin','person'),
('childeric','Childeric','The Frankish king deposed by Pepin.','Childeric','person'),
('blithild','Blithild','King Clothair’s daughter, from whom Pepin claimed descent.','Blithild','person'),
('clothair','King Clothair','A Frankish king, Blithild’s father.','King Clothair|Clothair','person'),
('hugh-capet','Hugh Capet','The French king who took the crown from Charles, Duke of Lorraine.','Hugh Capet|Capet','person'),
('charles-lorraine','Charles, Duke of Lorraine','The last male heir of Charlemagne’s line, displaced by Hugh Capet.','Charles the Duke of Lorraine|Charles Duke of Lorraine','person'),
('lingare','Lady Lingare','Charlemain’s daughter, from whom Hugh Capet traced his title.','Lady Lingare|Lingare','person'),
('ermengare','Lady Ermengare','Daughter of Charles, Duke of Lorraine, and ancestress of Queen Isabel the grandmother.','Lady Ermengare|Ermengare','person'),
('lewis-emperor','Lewis the Emperor','A Frankish emperor in Canterbury’s pedigree, son of Charlemagne.','Lewis the Emperor','person'),
('lewis-tenth','King Lewis the Tenth','The French king who wore the crown uneasily until his descent through the female line satisfied him.','King Lewis the Tenth|Lewis the Tenth','person'),
('isabel-grandmother','Queen Isabel','King Lewis the Tenth’s grandmother in Canterbury’s pedigree; a different Queen Isabel from the French queen in the play.','','person'),
('alexander-the-great','Alexander the Great','The Macedonian king, whom Fluellen compares to King Henry.','Alexander the Great|Alexander the Pig|Alexander','person'),
('philip-of-macedon','Philip of Macedon','Alexander the Great’s father.','Philip of Macedon','person'),
('cleitus','Cleitus','The friend Alexander killed in drink.','Cleitus','person'),
('pompey-the-great','Pompey the Great','The Roman general whose camp Fluellen holds up as a model of discipline.','Pompey the Great|Pompey','person'),
('mark-antony','Mark Antony','The Roman commander Fluellen names as a byword for valour.','Mark Antony','person'),
('agamemnon','Agamemnon','The Greek commander at Troy, Fluellen’s measure of greatness of soul.','Agamemnon','person'),
('caesar','Caesar','The Roman conqueror whose triumphal return the Chorus likens King Henry’s to.','Caesar','person'),
('brutus','Brutus','The Roman who hid his purpose under an appearance of folly.','Brutus','person'),
('herod','Herod','The king of Judea whose soldiers killed the children, in King Henry’s threat to Harfleur.','Herod','person'),
('adam','Adam','The first man, whose offending nature the Archbishop says was whipped out of the King.','Adam','religious-figure'),
('arthur','Arthur','King Arthur; the Hostess puts Falstaff in “Arthur’s bosom”, meaning Abraham’s.','Arthur','literary-figure'),
('cadwallader','Cadwallader','The Welsh king Pistol invokes when he refuses Fluellen’s leek.','Cadwallader','person'),
('saint-george','Saint George','The patron saint of England, King Henry’s battle cry.','Saint George','religious-figure'),
('saint-david','Saint David','The patron saint of Wales, whose day the Welsh mark by wearing the leek.','Saint Davy|Saint David|Saint Tavy','religious-figure'),
('saint-denis','Saint Denis','The patron saint of France.','Saint Denis','religious-figure'),
('saint-crispin','Saint Crispin and Saint Crispian','The paired saints whose feast day falls on the day of the battle.','Crispin Crispian|Crispin Crispianus|Crispian|Crispin','religious-figure'),
('lucifer','Lucifer','The chief of the fallen angels, in Fluellen’s oath.','Lucifer|Lucifier','religious-figure'),
('beelzebub','Beelzebub','A devil named beside Lucifer in Fluellen’s oath.','Beelzebub|Belzebub','religious-figure'),
('barbason','Barbason','A demon whose name Nym says cannot be used to conjure him.','Barbason','mythological-figure'),
('cressid','Cressid','The faithless lover of the Troy story, invoked in Pistol’s insult.','Cressid','literary-figure'),
('jove','Jove','The Roman king of the gods, who comes in thunder.','Jove','mythological-figure'),
('mars','Mars','The Roman god of war.','Mars','mythological-figure'),
('phoebus','Phoebus','The sun god, also called Hyperion here.','Phoebus','mythological-figure'),
('hyperion','Hyperion','The sun god whose horse the labourer helps to saddle at dawn.','Hyperion','mythological-figure'),
('hermes','Hermes','The Greek god whose pipe the Dauphin says his horse outplays.','Hermes','mythological-figure'),
('mercury','Mercury','The winged messenger god; the Chorus calls the English youth “English Mercuries”.','Mercuries','mythological-figure'),
('pegasus','Pegasus','The winged horse of Greek myth.','Pegasus','mythological-figure'),
('perseus','Perseus','The Greek hero who rode Pegasus.','Perseus','mythological-figure'),
('parca','Parca','The fate who spins and cuts the thread of life.','Parca','mythological-figure'),
('fortune','Fortune','Fortune painted blind on her rolling stone, turning men’s luck.','Fortune','mythological-figure'),
('empress','The gracious empress','The reigning queen the Chorus addresses his own London audience about; she is not named in the play.','','person'),
('irish-general','The general from Ireland','The commander the Chorus imagines returning from Ireland; the play does not name him.','','person'),
]:add(*row[:4],category='reference',kind=row[4])

# Later cards: identity changes and the two named disguised or renamed moments only.
updates={
 'king-henry':[((14,22),'The King of England, who gives Pistol the name Harry le Roy while he walks the camp unknown.'),
               ((21,22),'The King of England, victor on the field the heralds name Agincourt.')],
 'pistol':[((3,11),'An ensign in the English army, now married to the Hostess.')],
 'hostess':[((3,11),'Nell Quickly, who keeps a London tavern and has married Pistol.')],
 'falstaff':[((5,2),'The old knight of King Henry’s wild years; Pistol brings his company word that he has died.')],
 'katharine':[((23,13),'The French king’s daughter, named by King Henry as the first article of his terms.')],
 'bardolph':[((12,32),'A lieutenant of the English army, condemned for robbing a church.')],
}
for e in entities:e['snapshots']=[dict(after=list(at),body=body) for at,body in updates.get(e['id'],[])]
BASE=Path(__file__).resolve().parent
(BASE/'editorial.json').write_text(json.dumps(dict(bookId='henry-v',contentVersion='2026-09-10.1',coverage='All twenty-three scenes in both original-en and modern-en: named cast, speaking and stage roles, the named French and English nobility of the battle rolls, and the historical, classical and religious figures cited in the play.',entities=entities),ensure_ascii=False,indent=2)+'\n')
