// AUTO-GENERATED by app/scripts/generate-sitemap.cjs.
// Run `npm run sitemap` to regenerate. Do not hand-edit.
// Provides per-book <title>/<meta description> for /read/{bookId}.

export interface BookMetaEntry {
  title: string
  description: string
}

export const GENERATED_BOOK_META: Record<string, BookMetaEntry> = {
  'odyssey': {
    title: 'Read The Odyssey by Homer — Free Online with AI Companion | Tinct',
    description: 'The epic journey of Odysseus as he struggles to return home after the Trojan War. Monsters, gods, and the endurance of the human spirit across twenty years of wandering.',
  },
  'ulysses': {
    title: 'Read Ulysses by James Joyce — Free Online with AI Companion | Tinct',
    description: 'One day in Dublin, June 16, 1904. Leopold Bloom wanders through the city in a modern retelling of The Odyssey — stream of consciousness, parody, and the ordinary made extraordinary.',
  },
  'war-and-peace': {
    title: 'Read War and Peace by Leo Tolstoy — Free Online with AI Companion | Tinct',
    description: 'The sweeping epic of Russian society during the Napoleonic Wars. Five aristocratic families navigate love, death, and the search for meaning across battlefields and ballrooms.',
  },
  'bible': {
    title: 'Read The Bible by Various — Free Online with AI Companion | Tinct',
    description: 'The foundational text of Western civilization. 66 books spanning creation, law, history, poetry, prophecy, gospels, and revelation — the story of God and humanity across thousands of years.',
  },
  'gilgamesh': {
    title: 'Read The Epic of Gilgamesh by Anonymous — Free Online with AI Companion | Tinct',
    description: 'The oldest surviving great work of literature. A king and a wild man become brothers, slay monsters, and defy the gods — then face the one enemy no mortal can defeat.',
  },
  'hamlet': {
    title: 'Read Hamlet by William Shakespeare — Free Online with AI Companion | Tinct',
    description: 'A prince haunted by his father\'s ghost, paralyzed by doubt, driven toward revenge. The play that invented the modern mind — and the question that never stops: to be, or not to be.',
  },
  'macbeth': {
    title: 'Read Macbeth by William Shakespeare — Free Online with AI Companion | Tinct',
    description: 'A warrior seduced by prophecy and ambition murders his king — then watches his world unravel. Shakespeare\'s darkest, fastest tragedy: blood, guilt, and the wages of unchecked power.',
  },
  'midsummer': {
    title: 'Read A Midsummer Night\'s Dream by William Shakespeare — Free Online with AI Companion | Tinct',
    description: 'Lovers lost in an enchanted forest, fairies at war, and a weaver turned into a donkey. Shakespeare\'s most magical comedy — where love is ridiculous, wonderful, and completely out of anyone\'s control.',
  },
  'romeo-and-juliet': {
    title: 'Read Romeo and Juliet by William Shakespeare — Free Online with AI Companion | Tinct',
    description: 'Two teenagers fall in love across a blood feud and burn through five days that end in a tomb. The original star-crossed lovers — and the play that made tragedy feel like poetry.',
  },
  'the-tempest': {
    title: 'Read The Tempest by William Shakespeare — Free Online with AI Companion | Tinct',
    description: 'A sorcerer on a remote island conjures a storm to shipwreck his enemies — then chooses mercy over revenge. Shakespeare\'s farewell to the stage: magic, forgiveness, and letting go.',
  },
  'the-art-of-war': {
    title: 'Read The Art of War by Sun Tzu — Free Online with AI Companion | Tinct',
    description: 'Thirteen chapters on strategy, deception, and the nature of conflict — written 2,500 years ago, still the sharpest manual on how to win without fighting.',
  },
  'pride-and-prejudice': {
    title: 'Read Pride and Prejudice by Jane Austen — Free Online with AI Companion | Tinct',
    description: 'A sharp-tongued woman and a proud gentleman circle each other through balls, misunderstandings, and pride — until they don\'t. The novel that invented the romantic comedy.',
  },
  'crime-and-punishment': {
    title: 'Read Crime and Punishment by Fyodor Dostoevsky — Free Online with AI Companion | Tinct',
    description: 'A brilliant student commits the perfect murder — then discovers that guilt is a punishment no logic can escape. Dostoevsky\'s masterpiece of conscience, paranoia, and redemption.',
  },
  'the-republic': {
    title: 'Read The Republic by Plato — Free Online with AI Companion | Tinct',
    description: 'Socrates and his friends spend one long night asking the hardest question: what is justice? Along the way they build a city in words, discover the Forms, and descend into a cave. Philosophy begins here.',
  },
  'meditations': {
    title: 'Read Meditations by Marcus Aurelius — Free Online with AI Companion | Tinct',
    description: 'A Roman emperor\'s private journal — written on campaign, never meant to be read. No self-help platitudes, just a man wrestling with duty, mortality, and how to be good when the world isn\'t.',
  },
  'divine-comedy': {
    title: 'Read The Divine Comedy by Dante Alighieri — Free Online with AI Companion | Tinct',
    description: 'A poet walks through Hell, climbs the mountain of Purgatory, and ascends into Paradise — guided first by reason, then by love. The journey that mapped the afterlife and invented Italian literature.',
  },
  'jane-eyre': {
    title: 'Read Jane Eyre by Charlotte Brontë — Free Online with AI Companion | Tinct',
    description: 'An orphan with a fierce will and a quiet voice fights her way from cruelty to independence — then falls in love with a man hiding a terrible secret. "Reader, I married him."',
  },
  'the-aeneid': {
    title: 'Read The Aeneid by Virgil — Free Online with AI Companion | Tinct',
    description: 'A Trojan prince flees the ruins of his city, wanders the Mediterranean for seven years, and fights to found a new homeland in Italy. The epic that gave Rome its origin story — and Latin literature its masterpiece.',
  },
  'paradise-lost': {
    title: 'Read Paradise Lost by John Milton — Free Online with AI Companion | Tinct',
    description: 'Satan rebels against Heaven, corrupts humanity, and loses everything — but never stops talking. Milton\'s blind epic of free will, disobedience, and the cost of knowledge.',
  },
  'frankenstein': {
    title: 'Read Frankenstein by Mary Shelley — Free Online with AI Companion | Tinct',
    description: 'A young scientist creates life from dead flesh — then abandons it. The creature, articulate and desperate, wants only to be loved. The novel that invented science fiction and never lets you decide who the real monster is.',
  },
  'the-manual': {
    title: 'Read The Manual by Epictetus — Free Online with AI Companion | Tinct',
    description: 'The essential handbook of Stoic philosophy. In 52 short sections, Epictetus sets out the single most important idea in Stoicism: distinguish what is in your power from what is not, and concern yourself only with the former.',
  },
  'apology': {
    title: 'Read Apology by Plato — Free Online with AI Companion | Tinct',
    description: 'Socrates stands trial for his life in Athens. Accused of corrupting the youth and denying the gods, he mounts a fearless defense — not of himself, but of the examined life.',
  },
  'symposium': {
    title: 'Read Symposium by Plato — Free Online with AI Companion | Tinct',
    description: 'At a dinner party in Athens, seven men take turns praising Love. From Aristophanes\' comic myth of split souls to Socrates\' account of Diotima\'s ladder of beauty — the Western world\'s founding text on love and desire.',
  },
  'phaedo': {
    title: 'Read Phaedo by Plato — Free Online with AI Companion | Tinct',
    description: 'The last hours of Socrates. In prison awaiting execution, he argues for the immortality of the soul — not from fear, but from philosophical conviction. His friends weep; he drinks the hemlock calmly.',
  },
  'crito': {
    title: 'Read Crito by Plato — Free Online with AI Companion | Tinct',
    description: 'Socrates is in prison awaiting execution. His friend Crito comes at dawn with an escape plan. Socrates refuses — and walks Crito through the argument: justice matters more than life, and a citizen has a contract with the laws of his city. The shortest, most direct of Plato\'s prison dialogues.',
  },
  'phaedrus': {
    title: 'Read Phaedrus by Plato — Free Online with AI Companion | Tinct',
    description: 'Socrates and Phaedrus walk outside Athens to a plane tree by the Ilissus, where Phaedrus reads a speech by Lysias arguing that the non-lover should be preferred to the lover. Socrates answers with two speeches of his own — and the second, the great Palinode, unfolds the soul as a winged charioteer, the immortality of the soul, and divine madness as the source of every great good. The dialogue closes with the famous critique of writing: the myth of Theuth and Thamus, and Socrates\' warning that the written word is a reminder, not a teacher.',
  },
  'poetics': {
    title: 'Read Poetics by Aristotle — Free Online with AI Companion | Tinct',
    description: 'The earliest surviving work of dramatic theory in Western literature. Aristotle defines tragedy, dissects plot and character, and explains why a story moves us — laying the foundation that every subsequent theory of drama, fiction, and storytelling has built on.',
  },
  'moby-dick': {
    title: 'Read Moby Dick by Herman Melville — Free Online with AI Companion | Tinct',
    description: 'Call me Ishmael. A young sailor boards the whaling ship Pequod, captained by the monomaniac Ahab, who will hunt the great white whale to the ends of the earth — and beyond reason.',
  },
  'great-expectations': {
    title: 'Read Great Expectations by Charles Dickens — Free Online with AI Companion | Tinct',
    description: 'Pip, an orphan in the Kent marshes, receives a mysterious fortune that transforms his life. But his great expectations carry a price — and the truth about his benefactor will shatter everything he believes.',
  },
  'the-histories': {
    title: 'Read The Histories by Herodotus — Free Online with AI Companion | Tinct',
    description: 'The first great work of history in the Western world. Herodotus travels the ancient world — Egypt, Persia, Scythia, Greece — recording customs, wars, and wonders, building toward the epic clash between Greece and Persia.',
  },
  'niels-lyhne': {
    title: 'Read Niels Lyhne by J.P. Jacobsen — Free Online with AI Companion | Tinct',
    description: 'A young Danish dreamer searches for meaning through art, love, and atheism in nineteenth-century Denmark. Jacobsen\'s masterpiece — the novel Rilke called "the most important book in the world."',
  },
  'imitation-of-christ': {
    title: 'Read The Imitation of Christ by Thomas à Kempis — Free Online with AI Companion | Tinct',
    description: 'The most widely read Christian devotional work after the Bible. In 114 short chapters, Thomas à Kempis counsels the reader toward humility, inner peace, and the practice of following Christ in daily life.',
  },
  'jerusalem': {
    title: 'Read Jerusalem by Selma Lagerlöf — Free Online with AI Companion | Tinct',
    description: 'A Swedish farming community is torn apart when a charismatic preacher leads half its people on a pilgrimage to the Holy Land. Lagerlöf\'s Nobel Prize-winning novel of faith, land, and the cost of conviction.',
  },
  'the-awakening': {
    title: 'Read The Awakening by Kate Chopin — Free Online with AI Companion | Tinct',
    description: 'A young mother on a Louisiana island begins to feel the pull of the sea — and of a life entirely her own. Chopin\'s 1899 novel scandalized its readers and was forgotten for decades. It is now recognized as one of the first great feminist novels in American literature.',
  },
  'brothers-karamazov': {
    title: 'Read The Brothers Karamazov by Fyodor Dostoevsky — Free Online with AI Companion | Tinct',
    description: 'Dostoevsky\'s final novel: three brothers and their father, a murder, a trial, and the deepest questions of faith, doubt, and human freedom. Includes the legendary parable "The Grand Inquisitor."',
  },
  'iliad': {
    title: 'Read The Iliad by Homer — Free Online with AI Companion | Tinct',
    description: 'The wrath of Achilles and the final weeks of the Trojan War. Homer\'s first epic — rage, fate, gods at war with men, and the funeral of Hector.',
  },
  'nicomachean-ethics': {
    title: 'Read Nicomachean Ethics by Aristotle — Free Online with AI Companion | Tinct',
    description: 'The foundational work of virtue ethics. Aristotle asks what the good life is for a human being, and answers: flourishing (eudaimonia), achieved through practical wisdom, moral virtue, and contemplation. The golden mean, friendship, justice, and the nature of happiness — the vocabulary ethics has used ever since.',
  },
  'the-prince': {
    title: 'Read The Prince by Niccolò Machiavelli — Free Online with AI Companion | Tinct',
    description: 'The coldest clear-eyed book about power ever written. Machiavelli, exiled from Florence, drafted a manual for the ruler who would unify Italy — and in the process invented modern political realism. Fortune, virtù, the fox and the lion, and whether it is better to be loved or feared.',
  },
  'beyond-good-and-evil': {
    title: 'Read Beyond Good and Evil by Friedrich Nietzsche — Free Online with AI Companion | Tinct',
    description: 'Nietzsche at his most corrosive and most exhilarating. A frontal attack on the dogmas of philosophers, the pieties of Christianity, and the democratic instinct — and a sketch of the "free spirit" who would live beyond the old moral categories. Master-morality, slave-morality, the will to power, and the question: what is noble?',
  },
  'beowulf': {
    title: 'Read Beowulf by Anonymous — Free Online with AI Companion | Tinct',
    description: 'The oldest surviving epic in English. A Geatish warrior crosses the sea to fight three monsters across a lifetime — Grendel, Grendel\'s mother, and a dragon — in a poem about courage, kingship, and the long defeat that all heroes face.',
  },
  'candide': {
    title: 'Read Candide by Voltaire — Free Online with AI Companion | Tinct',
    description: 'Voltaire\'s attack on Leibnizian optimism. A young man is tutored in the belief that this is "the best of all possible worlds" — then the world systematically dismantles that belief through earthquake, war, plague, Inquisition, and the slave trade. Ends with the most famous closing line in the Enlightenment: "we must cultivate our garden."',
  },
  'democracy-in-america': {
    title: 'Read Democracy in America by Alexis de Tocqueville — Free Online with AI Companion | Tinct',
    description: 'A young French aristocrat travels the United States in 1831 and returns with the first, and still the most penetrating, analysis of democratic life — its equality, its restlessness, its softness, and the strange new tyranny of the majority.',
  },
  'oedipus-rex': {
    title: 'Read Oedipus Rex by Sophocles — Free Online with AI Companion | Tinct',
    description: 'The king who solved the riddle of the Sphinx saves his city from plague — by discovering that the polluter is himself. Sophocles\' archetypal tragedy of fate, knowledge, and the will to see what the gods have forbidden.',
  },
  'oedipus-at-colonus': {
    title: 'Read Oedipus at Colonus by Sophocles — Free Online with AI Companion | Tinct',
    description: 'Old, blind, and exiled, Oedipus arrives at a grove outside Athens seeking the death the gods have prepared for him. Sophocles\' final play, written at ninety, is a meditation on suffering, reconciliation, and the hero\'s strange blessing on the land that receives him.',
  },
  'antigone': {
    title: 'Read Antigone by Sophocles — Free Online with AI Companion | Tinct',
    description: 'Two brothers have killed each other fighting for Thebes; the new ruler forbids burial to the one who attacked the city. Antigone, sister to both, buries him anyway. Sophocles\' starkest confrontation between the unwritten laws of the gods and the public law of the state.',
  },
  'genealogy-of-morals': {
    title: 'Read On the Genealogy of Morals by Friedrich Nietzsche — Free Online with AI Companion | Tinct',
    description: 'Three essays asking where our moral concepts actually came from. Nietzsche traces "good," "evil," "guilt," and "bad conscience" back through Greek aristocratic codes, Christian inversion, and the priestly imagination — and finds, beneath every moral judgment, a will to power.',
  },
  'descartes-meditations': {
    title: 'Read Meditations on First Philosophy by René Descartes — Free Online with AI Companion | Tinct',
    description: 'Six meditations in which Descartes resolves to doubt everything he can — and from the wreckage retrieves one indubitable point: the thinking self. From this single foothold he reconstructs God, the world, and the foundations of modern philosophy.',
  },
  'on-liberty': {
    title: 'Read On Liberty by John Stuart Mill — Free Online with AI Companion | Tinct',
    description: 'Mill\'s defense of the individual against the social tyranny he saw rising in democratic societies. The "harm principle," the marketplace of ideas, and the case for eccentricity as a public good — the founding text of modern liberal thought.',
  },
  'utilitarianism': {
    title: 'Read Utilitarianism by John Stuart Mill — Free Online with AI Companion | Tinct',
    description: 'Mill\'s defense of the greatest-happiness principle against its critics. Pleasures differ in kind, not just amount; better to be Socrates dissatisfied than a fool satisfied. Where On Liberty drew the political line, Utilitarianism supplies the moral standard behind it.',
  },
  'peloponnesian-war': {
    title: 'Read History of the Peloponnesian War by Thucydides — Free Online with AI Companion | Tinct',
    description: 'The first great work of political history. Thucydides reports the twenty-seven-year war between Athens and Sparta as he saw it — speeches, plagues, betrayals, and the slow corruption of every virtue under the pressure of war. Pericles\' Funeral Oration, the Plague of Athens, the Melian Dialogue, the Sicilian Expedition: the foundations of how the West thinks about power.',
  },
  'aristotle-politics': {
    title: 'Read Politics by Aristotle — Free Online with AI Companion | Tinct',
    description: 'The founding text of political science. Aristotle surveys constitutions, citizenship, justice, revolution, and the best possible state — drawing on 158 real constitutions to ask what arrangement of power serves human flourishing. Still the sharpest framework for thinking about democracy, oligarchy, tyranny, and why states rise and fall.',
  },
  'fear-and-trembling': {
    title: 'Read Fear and Trembling by Søren Kierkegaard — Free Online with AI Companion | Tinct',
    description: 'A short, savage book about Abraham — the father of faith — who is told by God to murder his son. Kierkegaard, writing under the name Johannes de Silentio, refuses every comfortable Hegelian explanation and forces the reader to feel what faith actually demands. The "knight of faith" and the "teleological suspension of the ethical" begin here.',
  },
  'communist-manifesto': {
    title: 'Read The Communist Manifesto by Karl Marx & Friedrich Engels — Free Online with AI Companion | Tinct',
    description: 'Twelve thousand words written in 1848 that changed the political vocabulary of the next century. The bourgeoisie has dissolved every old certainty into the cash nexus; the proletariat will dissolve the bourgeoisie. Class struggle, world history, and the call that ends the book: workers of all countries, unite.',
  },
  'second-treatise': {
    title: 'Read Second Treatise of Government by John Locke — Free Online with AI Companion | Tinct',
    description: 'The book Mill is responding to. Locke argues that government exists to protect the natural rights of its citizens — life, liberty, property — and that when it ceases to do so, the people may dissolve it. The blueprint for the American revolution and the entire liberal tradition that followed.',
  },
  'social-contract': {
    title: 'Read The Social Contract by Jean-Jacques Rousseau — Free Online with AI Companion | Tinct',
    description: 'Man is born free, and everywhere he is in chains. Rousseau\'s short, dense argument for the only legitimate form of authority: a contract among equals, governed by the general will. The book the French Revolution thought it was reading.',
  },
  'faust-part-1': {
    title: 'Read Faust, Part One by Johann Wolfgang von Goethe — Free Online with AI Companion | Tinct',
    description: 'The scholar who has mastered every science still finds himself unable to live, makes a pact with Mephistopheles, and is led through pleasure, Walpurgis-Night, and the destruction of Gretchen. The defining work of German literature — and the play that taught the modern world how to talk about ambition, knowledge, and damnation.',
  },
  'oresteia': {
    title: 'Read The Oresteia by Aeschylus — Free Online with AI Companion | Tinct',
    description: 'The only surviving Greek trilogy. A king returns from Troy and is murdered by his wife. Their son returns to avenge him by killing his mother. The Furies pursue him until Athena establishes the first court of law and acquits him. Aeschylus traces the birth of justice itself out of the cycle of blood revenge.',
  },
  'bacchae': {
    title: 'Read The Bacchae by Euripides — Free Online with AI Companion | Tinct',
    description: 'Dionysus comes to Thebes in disguise, demanding that the city worship him. King Pentheus refuses. The god drives the women of Thebes into ecstatic frenzy on Mount Cithaeron, and Pentheus, fatally curious, goes up to spy. His own mother, in the grip of the god, tears him apart with her bare hands. Euripides\' last play and the most disturbing in the Greek tragic canon.',
  },
  'medea': {
    title: 'Read Medea by Euripides — Free Online with AI Companion | Tinct',
    description: 'Medea has given up everything for Jason — her father, her country, her brother — and now he is leaving her for a princess of Corinth. Her revenge will be calibrated to destroy what he loves most. The play that gave us a heroine more terrifying than any villain.',
  },
  'confessions': {
    title: 'Read Confessions by Augustine — Free Online with AI Companion | Tinct',
    description: 'The first great spiritual autobiography. Augustine traces his journey from youthful sin through Manichaean philosophy to Christian conversion — wrestling with desire, will, and the nature of God across thirteen searingly honest books.',
  },
  'notes-from-underground': {
    title: 'Read Notes from Underground by Fyodor Dostoevsky — Free Online with AI Companion | Tinct',
    description: 'The first existentialist novel: a feverish monologue from a self-aware, spiteful man who has retreated from society to attack the rationalist faith of his age. Dostoevsky\'s declaration of war on "the Crystal Palace" and the seed of every novel he wrote afterward.',
  },
  'magna-carta': {
    title: 'Read Magna Carta by Anonymous (sealed by King John) — Free Online with AI Companion | Tinct',
    description: 'The Great Charter of 1215 — the document that bound a king to law, sealed at Runnymede after the barons rose against royal absolutism. Its iconic Clause 39 ("No free man shall be seized or imprisoned…") is the seed of due process, habeas corpus, and the rule of law in the English-speaking world.',
  },
  'us-founding-documents': {
    title: 'Read The US Founding Documents by Various (Jefferson, Madison, et al.) — Free Online with AI Companion | Tinct',
    description: 'The four texts that built the American Republic: the Declaration of Independence (1776), the Constitution (1787), the Bill of Rights (1791), and every Amendment since. Together they define how a continental democracy was imagined, codified, and then expanded to include those it once excluded.',
  },
  'federalist-papers': {
    title: 'Read The Federalist Papers by Hamilton, Madison, Jay (as "Publius") — Free Online with AI Companion | Tinct',
    description: 'Eighty-five newspaper essays written by Hamilton, Madison, and Jay in 1787-88 to defend the proposed Constitution. The most influential work of political theory in American history — including Madison\'s celebrated "factions" paper (No. 10), the "if men were angels" argument for checks and balances (No. 51), and Hamilton\'s case for judicial review (No. 78).',
  },
  'a-little-princess': {
    title: 'Read A Little Princess by Frances Hodgson Burnett — Free Online with AI Companion | Tinct',
    description: 'Sara Crewe, the doted-on daughter of an English captain in India, is placed at Miss Minchin\'s Select Seminary in London. On her eleventh birthday her father dies and his fortune collapses; she is moved to a freezing attic and worked as an unpaid drudge. The book is the story of what survives in a person when status, money, and protection are stripped away in a single afternoon — and of the man who has been searching London for her, living next door.',
  },
  'jungle-book': {
    title: 'Read The Jungle Book by Rudyard Kipling — Free Online with AI Companion | Tinct',
    description: 'Seven stories from the Indian jungle — Mowgli raised by wolves, Rikki-Tikki-Tavi the mongoose, the White Seal, Toomai of the Elephants. Kipling\'s masterpiece of animal fable and moral adventure, which invented the modern coming-of-age story and shaped how the world imagines the wild.',
  },
  'around-the-world-80-days': {
    title: 'Read Around the World in Eighty Days by Jules Verne — Free Online with AI Companion | Tinct',
    description: 'Phileas Fogg, the most precise man in London, bets his fortune that he can circle the globe in eighty days. From London to Bombay to Yokohama to New York — a race against time, a detective on his heels, and a rescue along the way. Verne\'s great comedy of English phlegm against the chaos of the world.',
  },
  'heart-of-darkness': {
    title: 'Read Heart of Darkness by Joseph Conrad — Free Online with AI Companion | Tinct',
    description: 'Marlow sits on a yawl on the Thames and tells the story of his journey up the Congo River to retrieve a company agent named Kurtz who has gone deep into the interior and stopped sending word. The hundred-page novella that founded modern fiction — and the work the colonial project never recovered from.',
  },
  'discourse-on-inequality': {
    title: 'Read Discourse on the Origin of Inequality by Jean-Jacques Rousseau — Free Online with AI Companion | Tinct',
    description: 'Rousseau asks how human beings, who came into the world equal, ended up so radically unequal — and answers that the answer is not in nature but in property, civilization, and the institutions we built to defend them. The argument that set up The Social Contract and put the French Revolution in motion.',
  },
  'jekyll-and-hyde': {
    title: 'Read Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson — Free Online with AI Companion | Tinct',
    description: 'The lawyer Utterson investigates the strange friendship of his upright client Dr Jekyll with the brutish, hated Mr Hyde — and uncovers the experiment that gave English its phrase for the divided self. A short, vicious tale of respectability and the appetites it conceals.',
  },
}
