"""Pass D: restore '!' where the modern text dropped it (live numbering, 0-based paragraph index).
Each edit is anchored on a unique substring of the modern paragraph."""
from edits import apply

EDITS = [
    (16, 5, 'It seemed hopeless, unless he tried', 'In vain! Unless, indeed, he tried'),
    (16, 6, 'Nothing could be subtler than that gradual change.', 'Nothing could be subtler than that gradual change!'),
    (16, 12, 'No matter. It was the one thing', 'No matter! It was the one thing'),
    (16, 22, '“No. He bored me.', '“No! He bored me.'),
    (17, 42, 'Ah, you’re too young and frivolous', 'Ah! You’re too young and frivolous'),
    (17, 61, 'Or should I say poor Rosamond?', 'Or should I say, poor Rosamond!'),
    (18, 17, '“Oh, poor things, poor things!”', '“Oh, poor things! Poor things!”'),
    (18, 27, '“Ah, you’re a fortunate man,”', '“Ah! You’re a fortunate man,”'),
    (20, 4, 'Ah, no use gazing after her', 'Ah! No use gazing after her'),
    (20, 8, '“What, the clergyman? He looks', '“What! The _Geistlicher_? He looks'),
    (20, 4, 'the sallow clergyman for her father', 'the sallow _Geistlicher_ for her father'),
    (20, 16, 'my dear fellow, insofar as', 'my dear fellow!—insofar as'),
    (20, 21, 'it’s nonsense.', 'it’s nonsense!'),
    (23, 1, 'not especially gifted.', 'not especially gifted!'),
    (23, 56, 'The thought makes me furious.', 'The thought makes me furious!'),
    (25, 25, 'someone’s knocking. Run', 'someone’s knocking! Run'),
    (25, 39, '“That’s enough, Ben. Run along,”', '“That’s enough, Ben! Run along,”'),
    (25, 44, '“Why, Fred, my boy!”', '“Why! Fred, my boy!”'),
    (25, 66, '“Oh no. She’s always', '“Oh no! She’s always'),
    (25, 67, 'interrupt business terribly.”', 'interrupt business terribly!”'),
    (26, 11, 'But no; she could', 'But no! She could'),
    (26, 26, 'Oh no, learning a tune', 'Oh no! Learning a tune'),
    (26, 38, '“Ah. Did he come specially?”', '“Ah! Did he come specially?”'),
    (27, 3, 'mother. It’s nothing,”', 'mother! It’s nothing,”'),
    (28, 1, 'before it, however, and suddenly those scratches', 'before it, however, and lo! those scratches'),
    (28, 34, '“What—does the book belong to Mr. Plymdale?', '“What! Does the book belong to Mr. Plymdale?'),
    (29, 23, '“Celia, has something happened?”', '“Celia! Has something happened?”'),
    (32, 43, 'you’ve refused. One is still available', 'you’ve refused!—and one is still available'),
    (32, 56, '“What, having yourself tied', '“What! Having yourself tied'),
    (33, 35, '“What, because I’ve seen the old gentleman?”', '“What! Because I’ve seen the old gentleman?”'),
    (35, 26, '“How dreadful,” said Dorothea.', '“How dreadful!” said Dorothea.'),
    (36, 34, 'defend that, Garth.”', 'defend that, Garth!”'),
    (37, 46, '“Darling, your eyes are red.”', '“Darling! Your eyes are red.”'),
    (37, 48, '“You can’t hide it from me,”', '“You can’t hide it from me!”'),
    (37, 79, '“Dear Papa, how does', '“Dear Papa! How does'),
    (37, 80, 'in this condition. People call', 'in this condition! People call'),
    (38, 45, 'Was she happy with her husband?', 'I wonder whether she was happy with her husband!'),
    (45, 13, 'hardly see.”', 'hardly see!”'),
    (46, 31, '“Nonsense, no need for law,” said Toller.', '“Pooh, no need for law!” said Toller.'),
    (46, 36, '“Really! Ah, I recognized', '“Really! Ah! I recognized'),
    (46, 63, 'about them—emotional elephant that he was—was that', 'about them (emotional elephant that he was!) was that'),
    (49, 55, 'repeated, “I’m ready.”', 'repeated, “I’m ready!”'),
    (52, 17, 'No—the only way to force', 'No! The only way to force'),
    (54, 14, 'But by Jove, Nick, you look', 'But by Jove, Nick! You look'),
    (54, 50, '“I’ll tell you what. Give', '“I’ll tell you what! Give'),
    (55, 59, 'when I’ve nothing else?', 'when I’ve nothing else!'),
    (57, 4, 'Bless me, it reminds me', 'Bless me! It reminds me'),
    (57, 41, '“Aye,” each man', '“Aye!” each man'),
    (57, 42, 'of the kind. They’re', 'of the kind! They’re'),
    (57, 45, '“Aye, good for the big folk', '“Aye! Good for the big folk'),
    (58, 13, 'to have Christy home.”', 'to have Christy home!”'),
    (59, 28, 'And yet—well, he was deeply', 'And yet—well! He was deeply'),
    (59, 33, 'But dear me, surely we', 'But dear me! Surely we'),
    (59, 51, '“There, you see,”', '“There! You see,”'),
    (59, 81, '“Of course not, dear,”', '“Of course not, dear!”'),
    (60, 9, '“Good God, what are you', '“Good God! What are you'),
    (61, 9, 'it was made in the last century.', 'it was made in the last century!'),
    (61, 35, 'No, though: on the whole', 'But no! On the whole'),
    (61, 37, 'Lord, lord, you could see', 'Lord, lord! You could see'),
    (61, 39, '“Ah, well! I’ve often', '“Ah! Well! I’ve often'),
    (61, 41, 'to like her people. That was it.”', 'to like her people. That was it!”'),
    (61, 41, 'But Lord, Sarah would', 'But Lord! Sarah would'),
    (61, 44, 'Well, even if the truth', 'Well! Even if the truth'),
    (62, 15, 'calmly unconcerned as possible.', 'calmly unconcerned as possible!'),
    (62, 49, 'is no longer alive?”', 'is no longer alive!”'),
    (63, 59, 'undo today’s decision.', 'undo today’s decision!'),
    (64, 21, 'Go back and listen.”', 'Go back and listen!”'),
    (72, 4, '“By jingo, that reminds me,”', '“By jingo! That reminds me,”'),
    (72, 37, '“A finer gentleman? I’ll warrant', '“A finer gentleman! I’ll warrant'),
    (74, 7, 'Alas, scientific conscience', 'Alas! Scientific conscience'),
    (74, 8, 'as though I were a leper.', 'as though I were a leper!'),
    (84, 1, 'Oh dear, nothing.', 'Oh dear! Nothing.'),
]

if __name__ == '__main__':
    apply(EDITS)
